angular/components

- src/lib/tabs/tab-header.ts
> feat(tabs): make the updatePagination method public

- src/lib/stepper/_stepper-theme.scss
> fix(stepper): fix text contrast ratio of stepper labels

- src/cdk/overlay/fullscreen-overlay-container.ts
Similarly to the base overlay container, provides the fullscreen overlay container in the root.
> fix(overlay): provide fullscreen overlay container in root

- src/lib/slider/slider.spec.ts
- src/lib/slider/slider.ts
Fixes the slider re-assigning the value when it's right clicked.
> fix(slider): changing value on right click

- src/universal-app/kitchen-sink/kitchen-sink.html
- src/universal-app/kitchen-sink/kitchen-sink.ts
Adds `drag-drop` to the Angular Universal CI checks.
> build: set up universal checks for drag&drop

- .circleci/config.yml
- package.json
- test/karma.conf.js
- yarn.lock
Since we run only one browsers on Saucelabs, we can run the browser twice in order to speed up the tests.
> build: run saucelabs browsers in parallel

- src/dev-app/dev-app.html
Fixes the dev app not having landmark elements. This removes some of the noise when doing accessibility checks with aXe.
> chore: add landmark elements to dev app

- src/dev-app/dialog/dialog-demo.ts
- src/lib/bottom-sheet/_bottom-sheet-theme.scss
- src/lib/bottom-sheet/bottom-sheet-config.ts
- src/lib/dialog/_dialog-theme.scss
- src/lib/dialog/dialog-config.ts
- src/lib/dialog/dialog.ts
Reverts angular/material2#13065
The sync into google3 gets into a stage with many failure after PR already merge, revert it back to get into a clean state.
> Revert "fix(dialog,bottom-sheet): invert backdrop color on dark themes"

- src/material-examples/radio-overview/radio-overview-example.css
> docs(radio-button): fix radio button spacing

- src/cdk/a11y/focus-trap/focus-trap.ts
Fixes the `focus` event handlers, which retain a reference to the focus trap, not being cleaned up from the focus trap anchor elements on destroy.
> fix(a11y): remove listeners when focus trap anchors are removed

- src/lib/datepicker/datepicker.spec.ts
Hello,
There is a typo in the test for the mat datepicker
> fix(datepicker): typo in datepicker.spec.ts

- tools/public_api_guard/lib/tabs.d.ts
Fixes the tabs API goldens not being up to date. These changes fix the CI failures in master.
> chore(tabs): update api goldens

- WORKSPACE
* Updates to the latest Bazel sass rule
> build: update bazel sass rules

- src/lib/stepper/step-header.html
- src/lib/stepper/step-header.ts
- tools/public_api_guard/lib/stepper.d.ts
> fix(stepper): ensure step state is not minified

- CHANGELOG.md
Reverts angular/material2#13902
> Revert "docs: pointing out breaking change for MatSidenav and MatDrawer in 7.0"

- guides/theming-your-components.md
extract individual colors a palette -> extract individual colors from a palette.
> docs: fix minor typo on comment

- guides/theming-your-components.md
> fix(guides): typo

- src/material-examples/button-toggle-exclusive/button-toggle-exclusive-example.html
> Toggle buttons aria labels changes #14999

- README.md
> docs: update readme for Q1 2019

- src/material-examples/chips-autocomplete/chips-autocomplete-example.html
- src/material-examples/chips-input/chips-input-example.html
- src/material-examples/chips-overview/chips-overview-example.html
- src/material-examples/chips-stacked/chips-stacked-example.html
> fix(docs): aria labels added for mat-chip-list examples #15010

- src/lib/menu/menu.spec.ts
Reworks a test that depends on static queries and fails under Ivy.
> test(menu): refactor test that depends on static queries

- src/lib/sidenav/drawer.spec.ts
- src/lib/sidenav/drawer.ts
- src/lib/sidenav/sidenav.ts
* Fixes one unit test that was depending on static queries.
* Fixes the remaining 16 failures that were due to some code that was commented out while waiting for a task which was resolved.
> test(sidenav): fix sidenav failures under Ivy

- src/cdk/accordion/accordion.spec.ts
Found while investigating Ivy's issue FW-1131
> test(accordion): update static query test

- src/material-examples/tab-group-dynamic-height/tab-group-dynamic-height-example.ts
Fixes a minor spelling/wording mistake.
> fix: correct example title

- src/lib/list/_list-theme.scss
- src/lib/list/list.scss
- src/lib/list/list.spec.ts
- src/lib/list/list.ts
Since the action list is interactive, it needs styles when it's hovered and focused.
> fix(list): action list missing focus and hover styling

- src/cdk/table/table.spec.ts
Same commit as https://github.com/angular/material2/pull/15273 without the formatting changes
> test(table): remove unnecessary test

- src/lib/table/table.spec.ts
> test(table): update static query test

- src/lib/input/input.spec.ts
Same as #15460 but for the ivy-2019 branch
> test(input): make the type validation test to pass in Ivy

- tools/public_api_guard/lib/tooltip.d.ts
Fixes the API golden check failing against master.
> chore: update tooltip golden file

- src/material-examples/focus-monitor-focus-via/focus-monitor-focus-via-example.ts
- src/material-examples/focus-monitor-overview/focus-monitor-overview-example.ts
> refactor(focus-monitor): adapt demo examples for Ivy

- src/lib/snack-bar/snack-bar-container.ts
Reworks the snack bar to account for a breaking change in Ivy.
> refactor(snack-bar): rework to account for ivy

- src/lib/sidenav/drawer.ts
Fixes a couple of internal subjects not being completed in MatDrawer and MatDrawerContainer.
> fix(sidenav): some internal subjects not being completed

- package.json
- src/lib/card/card.scss
- yarn.lock
Bumps to the latest versions of stylelint and tslint, and fixes a new failure.
> build: bump linter versions and fix failure

- package.json
- src/lib/icon/icon-registry.ts
- yarn.lock
Bumps to TypeScript 3.3.3333. Also fixes the @angular/compiler-cli version being out of sync.
> build: update to typescript 3.3

- guides/theming.md
> docs(theming): add explicit customization guidance

- src/cdk/drag-drop/drag-drop.md
> docs(cdk): add cdk-drag-handle to Styling 

- src/cdk-experimental/tsconfig-build.json
- src/material-experimental/mdc-checkbox/checkbox.ts
- src/material-experimental/mdc-checkbox/public-api.ts
- src/material-experimental/tsconfig-build.json
- src/material-experimental/tsconfig.json
- tools/gulp/packages.ts
consistent with cdk and material.
> build: make cdk-experimental and material-experimental build settings

- tools/package-tools/gulp/build-tasks-gulp.ts
Fixes the build not waiting for the styles to finish building before starting to compile TS.
> build: fix race condition when building styles

- src/material-experimental/mdc-menu/menu.scss
- src/material-experimental/mdc-slide-toggle/slide-toggle.scss
* Fixes an e2e test failure in the slide toggle prototype.
* Fixes the underlines not being reset in the menu item.
> chore: minor prototype fixes

- src/cdk/portal/portal.ts
> fix(portal): TemplatePortal generic parameter

- src/material/chips/chip-remove.spec.ts
- src/material/chips/chip.ts
Fixes users being able to remove disabled chips by clicking on their remove button.
Fixes #15708.
> fix(chips): able to remove disabled chip via remove button

- src/cdk-experimental/popover-edit/form-value-container.ts
- src/cdk-experimental/popover-edit/popover-edit.spec.ts
- src/cdk-experimental/popover-edit/public-api.ts
- src/material-examples/popover-edit-mat-table/popover-edit-mat-table-example.html
- src/material-examples/popover-edit-mat-table/popover-edit-mat-table-example.ts
- src/material-experimental/popover-edit/popover-edit.spec.ts
Honestly not sure if this is worthwhile, but throwing it out there for comment.
> feat(popover-edit): Helper to reduce form state boilerplate

- src/material/core/common-behaviors/common-module.ts
Reverts angular/components#16231
> Revert "refactor(core): remove version placeholder workaround"

- src/dev-app/expansion/expansion-demo.html
- src/dev-app/expansion/expansion-demo.ts
- src/material/expansion/accordion-base.ts
- src/material/expansion/accordion.spec.ts
- src/material/expansion/accordion.ts
- src/material/expansion/expansion-panel-header.scss
- src/material/expansion/expansion-panel-header.ts
- src/material/expansion/expansion-panel.ts
- tools/public_api_guard/material/expansion.d.ts
> feat(expansion): allow expansion toggle indicator positioning

- guides/getting-started.md
I can found the spell mistake.
> Spell Mistake | Bug

- src/material/form-field/form-field.md
> docs(form-field): fix link

- src/material/schematics/ng-generate/nav/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
> refactor(schematics): allow subscription sharing on `isHandset$`

- src/material/expansion/expansion-panel.ts
> docs(expansion): fix docs for togglePosition input

- src/cdk/portal/dom-portal-outlet.ts
- src/cdk/portal/portal-directives.ts
- src/cdk/portal/portal.ts
- src/cdk/portal/public-api.ts
- tools/public_api_guard/BUILD.bazel
- tools/public_api_guard/cdk/portal.d.ts
Adds API goldens for the portal package and fixes some compilation errors that showed up when I was trying to generate it.
> build: add API goldens for portal

- package.json
- src/material-experimental/mdc-chips/chip-grid.ts
- src/material-experimental/mdc-chips/chip-icons.ts
- src/material-experimental/mdc-chips/chip-listbox.ts
- src/material-experimental/mdc-chips/chip-set.ts
- src/material-experimental/mdc-chips/chip.html
- src/material-experimental/mdc-chips/chip.ts
- src/material-experimental/mdc-helpers/BUILD.bazel
- yarn.lock
This reverts commit 8942602b05bfa5ff98284154bafb4e1a904b8f4e.
Reverting since this was reverted in google3
> Revert "Update MDC to latest alpha (#16724)"

- src/material-experimental/mdc-button/button-base.ts
- src/material-experimental/mdc-button/button.spec.ts
- src/material-experimental/mdc-button/fab.ts
Copies the tests straight from button.spec.ts
> feat(material-experimental/mdc-button): copy tests from button

- src/material-experimental/mdc-dialog/harness/dialog-harness-filters.ts
- src/material-experimental/mdc-dialog/harness/dialog-harness.spec.ts
- src/material-experimental/mdc-dialog/harness/dialog-harness.ts
Fixes an error due to a couple of PRs getting merged in out of sequence.
> build: fix compilation error in dialog harness

- .github/workflows/lock-closed.yml
> ci: set up angular-automatic-lock-bot for the repo

- package.json
- tools/defaults.bzl
- yarn.lock
Pre-req for https://github.com/angular/angular/pull/32485
> build: use protractor_web_test_suite from @bazel/protractor

- src/material-experimental/mdc-button/README.md
- src/material-experimental/mdc-button/button.ts
- src/material-experimental/mdc-button/fab.ts
- src/material-experimental/mdc-button/icon-button.ts
Just a few minor places where comments need to be added in
> fix(material-experimental/button): minor comment changes

- src/dev-app/autocomplete/autocomplete-demo.ts
Fixes the autocomplete demo not working correctly, because some testing changes weren't cleaned up in #15606.
> chore: fix autocomplete demo in dev app

- src/dev-app/dialog/dialog-demo.ts
This is minor change in the example code replacing usage of deprecated api with new one.
Thanks!
> docs(dialog): update dialog example

- src/cdk/stepper/stepper.md
> fix "varieties" typo

- src/cdk/drag-drop/drag-styling.ts
This version compiles in 3.5 and 3.6.
> chore(drag-drop): Fix compilation in TS3.6.

- src/cdk/testing/using-component-harnesses.md
>  docs(cdk/testing): add guide for using harnesses

- src/cdk/testing/testing.md
This PR adds docs for test authors using component harnesses. Future PRs will add docs for component harness authors ands harness environment authors
> docs(cdk/testing): create user docs for cdk/testing

- src/cdk/overlay/overlay.ts
cc @thekiba who helped me understand it
> docs(overlay): Minor comment fix in overlay.ts

- src/google-maps/README.md
Add documentation for Google Maps components.
> docs(google-maps): Add docs for Google Maps components

- tools/public_api_guard/generate-guard-tests.bzl
- tools/public_api_guard/google-maps/google-maps.d.ts
Now that the `google-maps` package is released, we should have an API golden for it.
> build: set up API golden for google-maps package

- src/material-experimental/mdc-chips/chip-set.spec.ts
- src/material-experimental/mdc-chips/chip-set.ts
Fixes the MDC-based chip set not picking up indirect descendant chips.
> fix(material-experimental/mdc-chips): chip set not picking up indirect descendant chips

- tools/public_api_guard/google-maps/google-maps.d.ts
Fixes the API golden check failing in master.
> build: api golden check failure

- src/material/slider/_slider-theme.scss
Fixes a few places in the slider theme which can break if the consumer is using CSS variables for their theme.
> fix(slider): some potentially broken styles when using css variables

- src/material-experimental/mdc-snackbar/BUILD.bazel
- src/material-experimental/mdc-snackbar/snackbar.ts
Fixes some CI issues in the `mdc-snackbar` build setup.
> build: fix errors in mdc-snackbar build

- src/google-maps/google-map/google-map.ts
- src/universal-app/BUILD.bazel
- src/universal-app/kitchen-sink/kitchen-sink.html
- src/universal-app/kitchen-sink/kitchen-sink.ts
Fixes the `google-map` component throwing errors during server-side rendering.
> fix(google-maps): error during server-side rendering

- README.md
> docs(readme): update docs url for ripples

- tools/dgeni/docs-package.ts
- tools/dgeni/processors/async-functions.ts
- tools/dgeni/templates/method.template.html
> build: mark asynchronous functions in API docs

- src/youtube-player/youtube-player.ts
Switches the internal observables of the `youtube-player` to be `Subject` so they're consistent with the rest of the repo and ensures that they're completed on destroy.
> fix(youtube-player): clean up internal observables

- src/dev-app/google-map/google-map-demo.html
- src/dev-app/google-map/google-map-demo.ts
- src/google-maps/google-maps-module.ts
- src/google-maps/map-polyline/map-polyline.spec.ts
- src/google-maps/map-polyline/map-polyline.ts
- src/google-maps/public-api.ts
- src/google-maps/testing/fake-google-map-utils.ts
- tools/public_api_guard/google-maps/google-maps.d.ts
Add a MapPolyline component to @angular/google-maps that allows drawing
polylines on a Google Map.
> feat(google-maps): Add MapPolyline component

- src/material-experimental/mdc-slide-toggle/slide-toggle.html
See: https://github.com/material-components/material-components-web/pull/5312
> fix(mdc-switch): updated to latest DOM structure guidance

- package.json
- packages.bzl
- src/material-experimental/mdc-chips/chip-icons.ts
- src/material-experimental/mdc-chips/chip-option.ts
- src/material-experimental/mdc-chips/chip-row.ts
- src/material-experimental/mdc-chips/chip.ts
- src/material-experimental/mdc-helpers/BUILD.bazel
- src/material-experimental/mdc-progress-bar/progress-bar.ts
- yarn.lock
Reverts angular/components#17760
Whoops, this has not been merged yet in g3
> Revert "chore: update MDC to latest canary"

- .github/CODEOWNERS
- src/dev-app/BUILD.bazel
- src/dev-app/dev-app/dev-app-layout.ts
- src/dev-app/dev-app/routes.ts
- src/dev-app/mdc-snackbar/BUILD.bazel
- src/dev-app/mdc-snackbar/mdc-snackbar-demo-module.ts
- src/dev-app/mdc-snackbar/mdc-snackbar-demo.html
- src/dev-app/mdc-snackbar/mdc-snackbar-demo.scss
- src/dev-app/mdc-snackbar/mdc-snackbar-demo.ts
- src/material-experimental/mdc-snackbar/BUILD.bazel
- src/material-experimental/mdc-snackbar/snackbar.ts
Add demo scaffolding  for MDC snackbar component
> feat(material-experimental/mdc-snackbar): Add demo.

- src/material/grid-list/grid-list.ts
- src/material/grid-list/grid-tile.ts
- src/material/grid-list/public-api.ts
- src/material/grid-list/testing/BUILD.bazel
- src/material/grid-list/testing/grid-list-harness-filters.ts
- src/material/grid-list/testing/grid-list-harness.spec.ts
- src/material/grid-list/testing/grid-list-harness.ts
- src/material/grid-list/testing/grid-tile-harness.ts
- src/material/grid-list/testing/index.ts
- src/material/grid-list/testing/public-api.ts
- src/material/grid-list/testing/shared.spec.ts
- src/material/grid-list/tile-coordinator.ts
* Adds a test harness for grid-list
> feat(material/grid-list): add test harness

- README.md
> docs: update readme for Q1 2020

- src/cdk/testing/test-harnesses.md
We want to resolve multiple menu items so we need `ComponentHarness#locatorForAll(HarnessPredicate)`.
> docs(cdk): correct code sample for test harnesses

- src/components-examples/material/table/table-expandable-rows/table-expandable-rows-example.css
- ref: https://material.io/components/data-tables/#behavior
> docs(material/table): use a hover color that is consistent with Material Design spec

- CHANGELOG.md
- package.json
> chore: bump version to 9.0.0-rc.8 w/ changelog (#18199)

- tools/tslint-rules/coercionTypesRule.ts
Currently the coercion types lint rule enforces compatibility
with the `async` pipe and strict null checks, by enforcing that
the input is assignable to `null` and `undefined`.
This is currently done by checking for known types (like
`BooleanInput`), or by checking for explicit type unions.
This is not very robust, and unflexible if new type aliases are
introduced. Since we updated to TS 3.7, we can leverage the type
relation API (which is now available; but just not exposed publicly
yet). For our lint rule, it should be fine using it already. We'll get
notified if something changes internally (which is unlikely though)
> build: coercion types rule should check type assignability

- src/material-experimental/mdc-form-field/BUILD.bazel
- src/material-experimental/mdc-form-field/directives/notched-outline.ts
- src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.html
- src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.ts
Fixes server side rendering issues for the MDC-based form-field, and
adds the form-field to the universal-app for CI testing.
> fix(material-experimental/mdc-form-field): fix server side rendering failures

- src/cdk/a11y/focus-trap/event-listener-inert-strategy.spec.ts
Reworks the `EventListenerFocusTrapInertStrategy` to avoid some of the flakes that we've been seeing in master recently. This is something that we've dealt with in the past where the timing of when focus events are dispatched is inconsistent between browsers and is asynchronous in some cases.
cc @vanessanschmitt
> build: rework flaky focus trap tests

- src/material/core/BUILD.bazel
- src/material/core/_core.scss
- src/material/core/theming/_theming.scss
- src/material/core/theming/tests/BUILD.bazel
- src/material/core/theming/tests/test-css-variables-theme.scss
- src/material/core/theming/tests/test-theming-api.scss
- src/material/core/typography/_all-typography.scss
- src/material/divider/_divider-theme.scss
See individual commit messages/titles.
**Note**: The Sass test file already helped a lot catching issues. I think that it's definitely something we should merge into the repository together with the upcoming density API.
> Fixes for density API and introduction of a new test for validating the API

- src/dev-app/mdc-input/mdc-input-demo.html
- src/dev-app/mdc-input/mdc-input-demo.ts
- src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss
- src/material-experimental/mdc-form-field/directives/notched-outline.ts
- src/material-experimental/mdc-form-field/form-field.html
- src/material-experimental/mdc-form-field/form-field.scss
- src/material-experimental/mdc-form-field/form-field.ts
> Various follow-up fixes for MDC-based form-field 

- package.json
- yarn.lock
Bumps to the final version of MDC 5.0.0.
> build: update to MDC 5.0.0 final

- src/dev-app/google-map/google-map-demo.html
- src/dev-app/google-map/google-map-demo.ts
- src/google-maps/google-maps-module.ts
- src/google-maps/map-polygon/map-polygon.spec.ts
- src/google-maps/map-polygon/map-polygon.ts
- src/google-maps/map-polyline/map-polyline.ts
- src/google-maps/map-rectangle/map-rectangle.spec.ts
- src/google-maps/map-rectangle/map-rectangle.ts
- src/google-maps/public-api.ts
- src/google-maps/testing/fake-google-map-utils.ts
- tools/public_api_guard/google-maps/google-maps.d.ts
Original commits should be preserved; the first two commits were previously reviewed, the latest commit resolves merge conflicts
> Merge google-maps-next branch into master

- guides/theming.md
> docs(theming): removed extra only (angular#35465)

- packages.bzl
Thanks to Paul for having the check in the script to make sure this was caught
> chore: fix Angular package version number

- src/material/dialog/dialog.ts
Replaces the usage of our custom `PortalInjector` with Angular's `Injector`. The advantage of using the default one is that the injection logic is consistent with everything else and we don't have to require users to polyfill `WeakMap`.
The idea here is to eventually replace all usages of `PortalInjector` with `Injector` and to deprecate it, but I wanted to try it out against `dialog` since it's probably the most used and well tested of the components that are using the custom injector.
> refactor(dialog): remove custom injector usage

- src/material-experimental/mdc-form-field/BUILD.bazel
- src/material-experimental/mdc-form-field/_form-field-density.scss
- src/material-experimental/mdc-form-field/_form-field-sizing.scss
- src/material-experimental/mdc-form-field/_form-field-theme.scss
- src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss
- src/material-experimental/mdc-form-field/form-field.scss
* Adds support for density scaling of MDC-based form-field. A few structure overrides had to be moved from fixed variables to variables that are based on the density scale.
> feat(mdc-form-field): support density scaling

- src/dev-app/google-map/google-map-demo.html
- src/dev-app/google-map/google-map-demo.ts
- src/google-maps/google-maps-module.ts
- src/google-maps/map-circle/map-circle.spec.ts
- src/google-maps/map-circle/map-circle.ts
- src/google-maps/public-api.ts
- src/google-maps/testing/fake-google-map-utils.ts
- tools/public_api_guard/google-maps/google-maps.d.ts
Add Circle component to Google Maps
> Maps circle

- CHANGELOG.md
- package.json
(cherry picked from commit c88780fa99a5032a97866ac643bd0cbf64f96571)
> chore: bump version to 9.1.3 w/ changelog (#18841)

- src/components-examples/material-experimental/mdc-form-field/mdc-form-field-custom-control/form-field-custom-control-example.ts
- src/components-examples/material/form-field/form-field-custom-control/form-field-custom-control-example.ts
> docs(form-field): Use Form Validation in custom control example

- src/material/dialog/dialog.spec.ts
The event was modified here but never dispatch it.
> test(dialog): add missing event dispatch

- src/components-examples/material/button/BUILD.bazel
- src/components-examples/material/button/button-overview/button-overview-example.css
- src/components-examples/material/button/button-overview/button-overview-example.html
- src/components-examples/material/button/index.ts
- src/dev-app/button/BUILD.bazel
- src/dev-app/button/button-demo-module.ts
- src/dev-app/button/button-demo.html
> docs(button): add more comprehensive button examples

- src/google-maps/map-circle/map-circle.ts
- src/universal-app/kitchen-sink/kitchen-sink.html
Fixes the `map-circle` component throwing an error during server-side rendering.
> fix(google-maps): map circle error during server-side rendering

- src/material/tabs/tab-nav-bar/tab-nav-bar.html
Fixes the pagination animation not being disabled when using the `NoopAnimationsModule`.
> fix(tabs): tab nav bar not disabling pagination animation

- src/dev-app/theme.scss
- src/material-experimental/mdc-helpers/_focus-indicator.scss
- src/material/core/focus-indicator/_focus-indicator.scss
> refactor: rename MDC strong-focus indicator mixin for consistent naming

- package.json
- src/material-experimental/mdc-helpers/BUILD.bazel
- yarn.lock
Updates to the latest Canary version of MDC and fixes a build error.
> build: update to latest MDC canary and fix error

- goldens/ts-circular-deps.json
- package.json
- yarn.lock
Updates to the latest changes of the shared dev-infra
package. We recently landed a few improvements for the
circular-deps tool there. i.e. more deterministic order
of circular dependencies in the golden (hence the update).
> build: update to latest dev-infra package changes

- src/google-maps/map-info-window/map-info-window.ts
- src/universal-app/prerender.ts
* See individual commits.
Caretaker: Please preserve commits when merging this.
> fix(google-maps): avoid runtime error on server 

- package.json
- src/cdk/testing/testbed/fake-events/dispatch-events.ts
- src/cdk/testing/testbed/fake-events/event-objects.ts
- src/cdk/testing/testbed/unit-test-element.ts
- src/material-experimental/mdc-slider/slider.spec.ts
- yarn.lock
> feat(cdk/testing/testbed): emit pointer events for test element click

- README.md
> docs: update readme for Q2 2020

- src/material/datepicker/date-range-input.spec.ts
Fixes one of the datepicker tests that fails when running against ViewEngine.
> test(datepicker): fix test failure against view engine

- tools/markdown-to-html/docs-marked-renderer.ts
add more parameters to embedded example comments in md docs to be rendered into example components to implement compact view for example components in material docs page
> refactor: update api for embedded example comments in md docs

- .circleci/config.yml
- src/material-experimental/column-resize/_column-resize.scss
See individual commits.
**Caretaker Note*: Please merge manually into the `9.2.x` branch.
> build: fix failing ci jobs in patch branch [patch only]

- src/cdk/testing/testbed/BUILD.bazel
- src/cdk/testing/testbed/fake-events/event-objects.spec.ts
- src/cdk/testing/testbed/fake-events/event-objects.ts
- tools/defaults.bzl
> fix(cdk/testing/testbed): synthetic DOM events cannot be prevented multiple times

- src/components-examples/cdk/stepper/cdk-linear-stepper-with-form/cdk-linear-stepper-with-form-example.css
- src/components-examples/cdk/stepper/cdk-linear-stepper-with-form/cdk-linear-stepper-with-form-example.html
- src/components-examples/cdk/stepper/cdk-linear-stepper-with-form/cdk-linear-stepper-with-form-example.ts
- src/components-examples/cdk/stepper/cdk-linear-stepper-with-form/example-custom-linear-stepper.css
- src/components-examples/cdk/stepper/cdk-linear-stepper-with-form/example-custom-linear-stepper.html
- src/components-examples/cdk/stepper/index.ts
Created new linear stepper example for the cdk-stepper. I used the existing example as a reference since I figured we would want them to be similar to each other besides the linear feature. I also used some of the layout styling from the existing mat-stepper linear example. If we would like this example to be more different from these other examples, I can do so.
> Cdk linear stepper example

- src/cdk-experimental/package.json
- src/cdk/package.json
- src/google-maps/package.json
- src/material-experimental/package.json
- src/material-moment-adapter/package.json
- src/material/package.json
- src/youtube-player/package.json
Reverts angular/components#19500
> Revert "build: remove wombot proxy registry from package.jsons for release"

- src/dev-app/mdc-input/mdc-input-demo.html
- src/material-experimental/mdc-form-field/BUILD.bazel
- src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss
- src/material-experimental/mdc-form-field/directives/floating-label.ts
- src/material-experimental/mdc-form-field/form-field.html
- src/material-experimental/mdc-form-field/form-field.ts
- src/material-experimental/mdc-form-field/testing/BUILD.bazel
- src/material-experimental/mdc-input/BUILD.bazel
- src/material-experimental/mdc-input/input.spec.ts
- src/material-experimental/mdc-input/testing/BUILD.bazel
> fix(material-experimental/mdc-form-field): various fixes

- goldens/size-test.json
Fixes a failure in one of the size checks that's breaking master.
> build: fix size check failure

- src/cdk-experimental/menu/BUILD.bazel
- src/cdk-experimental/menu/menu-bar.ts
- src/cdk-experimental/menu/menu-errors.ts
- src/cdk-experimental/menu/menu-group.spec.ts
- src/cdk-experimental/menu/menu-interface.ts
- src/cdk-experimental/menu/menu-item-checkbox.spec.ts
- src/cdk-experimental/menu/menu-item-radio.spec.ts
- src/cdk-experimental/menu/menu-item-trigger.spec.ts
- src/cdk-experimental/menu/menu-item-trigger.ts
- src/cdk-experimental/menu/menu-item.spec.ts
- src/cdk-experimental/menu/menu-item.ts
- src/cdk-experimental/menu/menu-module.ts
- src/cdk-experimental/menu/menu-panel.ts
- src/cdk-experimental/menu/menu.spec.ts
- src/cdk-experimental/menu/menu.ts
- src/dev-app/cdk-experimental-menu/cdk-menu-demo.html
Implement logic to open/close attached menus and submenus when triggering the specified MenuItem to which the menu is attached to
> feat(cdk-experimental/menu): implement menu handling logic

- tools/markdown-to-html/docs-marked-renderer.spec.ts
- tools/markdown-to-html/docs-marked-renderer.ts
was breaking doc site by putting `'undefined'`(string) in HTML
> empty string if no file/region defined

- src/components-examples/material/list/list-single-selection/list-single-selection-example.html
> docs(list): fix single selection example (#19723)

- test/benchmarks/material/slide-toggle/BUILD.bazel
- test/benchmarks/material/slide-toggle/app.module.ts
- test/benchmarks/material/slide-toggle/slide-toggle.perf-spec.ts
* Test the render speed of a slide toggle
* Test the click speed between of a slide toggle
> test(slide-toggle): add performance tests for mat-slide-toggle

- test/benchmarks/material/chips/BUILD.bazel
- test/benchmarks/material/chips/app.module.ts
- test/benchmarks/material/chips/chips.perf-spec.ts
* Test the render speed of a single chip
* Test the render speed of a 6 chips
* Test the click speed of a single chip
> test(chips): add performance tests for mat-chips

- test/benchmarks/material/button/BUILD.bazel
- test/benchmarks/material/button/app.module.ts
- test/benchmarks/material/button/button.perf-spec.ts
* Test the render speed
* Test the click speed
* Small changes to checkbox benchmark
> test(button): add performance tests for mat-raised-button

- .github/CODEOWNERS
- src/e2e-app/BUILD.bazel
- src/e2e-app/devserver-configure.js
- src/e2e-app/e2e-app/e2e-app-layout.html
- src/e2e-app/e2e-app/routes.ts
- src/e2e-app/mdc-input/mdc-input-e2e-module.ts
- src/e2e-app/mdc-input/mdc-input-e2e.html
- src/e2e-app/mdc-input/mdc-input-e2e.ts
- src/material-experimental/mdc-form-field/_form-field-sizing.scss
- src/material-experimental/mdc-input/input.e2e.spec.ts
> Setup e2e tests for MDC based input and improve input/control alignment

- src/cdk/portal/portal.md
- src/components-examples/cdk/portal/cdk-portal-overview/cdk-portal-overview-example.html
- src/components-examples/cdk/portal/cdk-portal-overview/cdk-portal-overview-example.ts
Add the DomPortal example in the cdk-portal-overview-example component and update the Portal markdown documentation adding TemplatePortal and DomPortal.
> docs(cdk/portal): update portal docs

- test/benchmarks/material/card/BUILD.bazel
- test/benchmarks/material/card/app.module.ts
- test/benchmarks/material/card/card.perf-spec.ts
> test(card): add performance tests for mat-card

- src/components-examples/BUILD.bazel
- src/components-examples/material-experimental/mdc-card/BUILD.bazel
- src/components-examples/material-experimental/mdc-card/index.ts
- src/components-examples/material-experimental/mdc-card/mdc-card-fancy/mdc-card-fancy-example.css
- src/components-examples/material-experimental/mdc-card/mdc-card-fancy/mdc-card-fancy-example.html
- src/components-examples/material-experimental/mdc-card/mdc-card-fancy/mdc-card-fancy-example.ts
- src/e2e-app/BUILD.bazel
- src/e2e-app/mdc-card/mdc-card-e2e-module.ts
- src/e2e-app/mdc-card/mdc-card-e2e.html
- src/e2e-app/mdc-card/mdc-card-e2e.ts
- src/material-experimental/mdc-card/card.e2e.spec.ts
> test(material-experimental/mdc-card): add e2e tests

- src/e2e-app/mdc-button/mdc-button-e2e-module.ts
- src/e2e-app/mdc-button/mdc-button-e2e.html
- src/e2e-app/mdc-button/mdc-button-e2e.ts
- src/material-experimental/mdc-button/button.e2e.spec.ts
Copied from current button e2e
> test(material-experimental/mdc-button): add e2e tests

- test/benchmarks/material/form-field/BUILD.bazel
- test/benchmarks/material/form-field/app.module.ts
- test/benchmarks/material/form-field/form-field.perf-spec.ts
Render a form-field with an input.
Render a form-field with a select.
Render a form field with a textarea.
> test(form-field): add performance tests for mat-form-field

- package.json
- tools/defaults.bzl
- yarn.lock
* The latest commit to dev-infra contains fixes for issues that were breaking
our performance benchmarks.
> build(dev-infra): update dev-infra to latest commit

- src/cdk-experimental/menu/menu-stack.ts
Addresses https://github.com/angular/components/pull/19962#discussion_r454487001
> refactor(cdk-experimental/menu) use typing  to expose a subject as observable and skip method call

- README.md
> docs: update readme for Q3 2020

- test/benchmarks/material/form-field/app.module.ts
Not sure how I messed this up a comment...twice. This should fix it for good.
> fix(form-field): fix form-field comment for google sync

- src/universal-app/kitchen-sink/kitchen-sink.html
Adds the new KML layer component to the server-side rendering checks.
> build: add server-side rendering check for kml layer

- package.json
- src/material-experimental/mdc-slider/slider.ts
- yarn.lock
Fixes an error introduced by the latest MDC canary version.
> build: fix compilation error with latest MDC canary

- src/material-experimental/mdc-theming/BUILD.bazel
- test/benchmarks/mdc/radio/BUILD.bazel
- test/benchmarks/mdc/radio/app.module.ts
- test/benchmarks/mdc/radio/radio.perf-spec.ts
> test(mdc-radio): add performance tests for mdc-radio

- src/material/datepicker/datepicker.md
> docs(datepicker): add link to date implementation at the top

- src/material-experimental/mdc-theming/BUILD.bazel
- test/benchmarks/mdc/table/BUILD.bazel
- test/benchmarks/mdc/table/app.module.html
- test/benchmarks/mdc/table/app.module.ts
- test/benchmarks/mdc/table/basic-table.ts
- test/benchmarks/mdc/table/fake-table-data.ts
- test/benchmarks/mdc/table/table.perf-spec.ts
> test(mdc-table): add performance tests for mdc-table

- src/material/config.bzl
- src/material/stepper/step-header.html
- src/material/stepper/stepper-button.ts
- src/material/stepper/testing/BUILD.bazel
- src/material/stepper/testing/index.ts
- src/material/stepper/testing/public-api.ts
- src/material/stepper/testing/shared.spec.ts
- src/material/stepper/testing/step-harness-filters.ts
- src/material/stepper/testing/step-harness.ts
- src/material/stepper/testing/stepper-button-harnesses.ts
- src/material/stepper/testing/stepper-harness.spec.ts
- src/material/stepper/testing/stepper-harness.ts
- tools/public_api_guard/material/stepper/testing.d.ts
Adds test harnesses for the stepper-related components.
> feat(stepper): add test harness

- package.json
- src/material-experimental/mdc-slider/slider.ts
- yarn.lock
Fixes a compilation error due to MDC changing an  interface.
> build: fix error from latest MDC canary version

- package.json
- src/material-experimental/mdc-slider/slider.ts
- yarn.lock
Updates an object to match the signature from the latest MDC Canary version.
> build: fix error with latest MDC canary version

- package.json
- src/material-experimental/mdc-progress-bar/BUILD.bazel
- src/material-experimental/mdc-progress-bar/progress-bar.ts
- src/material-experimental/tsconfig-tests.json
- tsconfig.json
- yarn.lock
* bump MDC canary version from 85a1fa9ea to fc0eb5013
* implement new functions of MDCLinearProgressAdapter
> build: bump MDC canary version

- .yarnrc
Update the vendored version of yarn to the latest version.
> build: update to latest version of yarn

- package.json
- src/material-experimental/mdc-slider/slider.ts
- yarn.lock
Fixes a build error due to a new required property.
> build: fix build failure in latest MDC canary

- .stylelintrc.json
Update the stylelint config file to use unit-allowed-list
> build: update stylelint usage to use unit-allowed-list

- .stylelintrc.json
Update the stylelint config file to use declaration-property-value-disallowed-list
function-url-scheme-disallowed-list
> build: update stylelint remove usages of the term blacklist

- .dependabot/config.yml
- .github/CODEOWNERS
configure dependabot updates to use the expected commit message type/scope
> build: configure dependabot updates

- src/dev-app/drag-drop/drag-drop-demo.html
I left in some invalid code in the `drag-drop` demo by accident while working on #20668 which is throwing an error now.
> build: fix drag-drop demo

- .gitignore
- package.json
- yarn.lock
> Restore commit messages on failures

- package.json
- src/material-experimental/mdc-form-field/form-field.ts
- yarn.lock
> fix(material-experimental/mdc-form-field): implement new methods added to text field adapter

- README.md
> docs: update readme for Q4 2020

- scripts/saucelabs/start-tunnel.sh
Update the version of the sauceconnect binary used to the latest
version.
> ci: update sauceconnect verstion to 4.6.2

- .circleci/config.yml
- .circleci/env-helpers.inc.sh
- .circleci/env.sh
- .circleci/rebase-pr.js
PRs should be rebased before running and CI checks to test the code
that would be merged, rather than the code of the repository the PR
was created from at the time it was created.
> ci: rebase PRs before running CI checks

- package.json
- src/material-experimental/mdc-slider/slider.ts
- yarn.lock
The slider adapter was updated on MDC's side which is breaking the build.
> build: fix error with latest MDC version

- package.json
- src/material-experimental/mdc-slider/slider.ts
- yarn.lock
Accounts for a breaking change in the latest MDC canary version.
> build: fix errors with latest MDC canary version

- src/material/datepicker/_datepicker-theme.scss
Fixes: https://github.com/angular/components/issues/18845
Before:
After:
> fix(material/datepicker): adjust focused date background for better visibility

- src/material/select/select.md
see https://github.com/angular/components/pull/20082
and
https://github.com/angular/components/blob/3c37e4b1c1cb74a3d0a90d173240fc730d21d9d4/src/material/select/select.ts#L1107
> docs(material/select): update accessibility information on roles

- src/material-experimental/mdc-checkbox/_checkbox-theme.scss
- src/material-experimental/mdc-checkbox/checkbox.scss
> Project import generated by Copybara.

- LICENSE
> build: bump year

- src/material-experimental/mdc-chips/chip-grid.spec.ts
- src/material-experimental/mdc-chips/chip-grid.ts
- src/material-experimental/mdc-chips/chip-remove.spec.ts
- src/material-experimental/mdc-chips/chip-row.spec.ts
- src/material-experimental/mdc-chips/chip-row.ts
- src/material-experimental/mdc-chips/chip.spec.ts
- src/material-experimental/mdc-chips/chip.ts
- src/material-experimental/mdc-chips/chips.scss
- src/material-experimental/mdc-chips/testing/chip-harness.ts
Reverts angular/components#21586
> Revert "fix(material-experimental/mdc-chips): decouple removal from animation"

- .yarnrc
Update to the latest version of yarn.
> build: update to yarn v1.22.10

- src/google-maps/map-circle/map-circle.ts
documentation reference for getRadius method is wrong
> fix(google-maps): correct minor typo in the code

- src/google-maps/map-circle/README.md
https://github.com/angular/components/issues/20557
> docs: radius typed instead of assigned

- src/components-examples/material/button-toggle/button-toggle-forms/button-toggle-forms-example.html
- src/components-examples/material/button-toggle/button-toggle-forms/button-toggle-forms-example.ts
- src/components-examples/material/button-toggle/index.ts
- src/material/button-toggle/button-toggle.md
> docs: document button-toggle-group usage with forms(+add example)

- src/material-experimental/mdc-core/_core-theme.import.scss
- src/material-experimental/mdc-theming/_all-theme.import.scss
> fix(material-experimental/mdc-core): rename core import file

- src/material/autocomplete/autocomplete.ts
Fix aria label comment which was introduced with #20892
> docs(material/autocomplete): fix aria-label docs

- packages.bzl
> build: fix angular version

- src/material/badge/badge.md
> docs(badge): specify badge targets must be block-level

- src/material-experimental/mdc-core/option/_option-theme.scss
This was broken by https://github.com/angular/components/pull/22157
already in g3 sync
> fix(material-experimental/mdc-core): fix broken list option style

- src/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.__style__.template
Updates the generated CSS class to match the current version.
Fixes #22269
> fix(cdk/schematics): update generated css class

- src/material-experimental/mdc-tooltip/tooltip.html
Merge when cl/364880888 is submitted
> fix(material-experimental/mdc-tooltip): use new MDC class names

- src/material-experimental/mdc-theming/prebuilt/indigo-pink.scss
Fixes a lint failure in one of the Sass files.
> build: fix stylelint failure

- src/google-maps/map-directions-renderer/README.md
By using suggested coordinates the service returns no directions ("ZERO_RESULTS") and in console is logged: "Directions request returned no results".
I suggest to modify the coordinates with two points that allow the component to render directions.
> docs: minor fix in code

- src/material-experimental/mdc-typography/_all-typography.import.scss
- src/material-experimental/mdc-typography/_all-typography.scss
Caretaker note: there's one internal usage that will need to be updated
> fix(material-experimental/mdc-typography): add missing @import forward

- README.md
> docs: update readme project status for Q2 2021

- src/material-experimental/mdc-slider/slider.ts
- src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.html
Resolves a TODO about setting up an SSR check. It seems like the function call is safe, because we don't initialize the MDC logic on the server.
> test(material-experimental/mdc-slider): add server-side rendering test

- src/components-examples/material/tree/tree-nested-overview/tree-nested-overview-example.css
- src/components-examples/material/tree/tree-nested-overview/tree-nested-overview-example.html
> docs(tree): A11Y improvement for Nested Tree example.

- CHANGELOG.md
Includes some missing changelog updates from 11.2.x patches
> release: update changelog to 12.0.1

- rollup-globals.bzl
- src/components-examples/material/datepicker/datepicker-locale/datepicker-locale-example.ts
> docs(material/datepicker): import used locales in example

- src/components-examples/material/checkbox/checkbox-reactive-forms/checkbox-reactive-forms-example.css
- src/components-examples/material/checkbox/checkbox-reactive-forms/checkbox-reactive-forms-example.html
- src/components-examples/material/checkbox/checkbox-reactive-forms/checkbox-reactive-forms-example.ts
- src/components-examples/material/checkbox/index.ts
> docs(material/checkbox): add example of using mat-checkbox with reactive forms

- src/components-examples/material/table/index.ts
- src/components-examples/material/table/table-generated-columns/table-generated-columns-example.css
- src/components-examples/material/table/table-generated-columns/table-generated-columns-example.html
- src/components-examples/material/table/table-generated-columns/table-generated-columns-example.ts
> docs(material/table): create example with columns defined dynamically

- tools/dgeni/processors/docs-private-filter.ts
Fixes that docs private members weren't being filtered out from interfaces.
Also moves the code around slightly so that we don't mutate the data inside `Array.filter` since the expectation is that the filter function is pure.
Fixes #20327.
> build: filter out docs private members from interfaces

- WORKSPACE
- package.json
- scripts/circleci/setup-angular-snapshots.js
- src/cdk/testing/tests/webdriver-test.bzl
- tools/defaults.bzl
- yarn.lock
> build: update to the latest `@angular/dev-infra-private` version

- src/material/core/ripple/ripple-renderer.ts
Aligns the ripple timings with the numbers from MDC.
> fix(material/core): align ripple animation parameters with spec

- src/cdk/table/cell.ts
- src/cdk/table/table.spec.ts
- src/cdk/table/table.ts
- src/material-experimental/mdc-table/cell.ts
Reverts angular/components#22491
> Revert "fix(cdk/table): set default role of table to 'table'"

- src/components-examples/material/table/table-expandable-rows/table-expandable-rows-example.css
- src/material-experimental/mdc-table/table.scss
- src/material/table/_table-flex-styles.scss
- src/material/table/_table-theme.scss
- src/material/table/table.scss
Reverts angular/components#22350
> Revert "fix(material/table): switch back to class-based styling for flex tables"

- src/material/radio/radio.scss
Reverts angular/components#22066
> Revert "fix(material/radio): hidden circle visible on some zoom levels"

- src/cdk/table/cell.ts
- src/cdk/table/table.spec.ts
- src/cdk/table/table.ts
- src/material-experimental/mdc-table/cell.ts
Reverts angular/components#23150
> Revert "Revert "fix(cdk/table): set default role of table to 'table'""

- src/material-experimental/mdc-menu/menu.spec.ts
- src/material/menu/menu.spec.ts
We were only using `fakeAsync` on about half of the menu tests which could cause state to leak between them. These changes add `fakeAsync` to all of them to try and address the recent flakes that we've been seeing.
> test(material/menu): switch all tests to fakeAsync

- src/material/core/typography/_typography-deprecated.scss
> fix(material/theming): correctly configure input typography level

- yarn.lock
Updates dependencies in the lock file as some dependencies
have loose version ranges and will match with more recent
versions.
> build: update dependencies in lock file

- src/material-experimental/mdc-button/button.scss
CARETAKER NOTE: This should be merged once cl/386915262 is submitted
> fix(material-experimental/mdc-button): fix ripple size after MDC changes

- src/cdk/drag-drop/drag-ref.ts
Fix proposed by internal user to fix an issue with dragging. Open for discussion on whether this fix is valid.
> fix(cdk/drag-drop): add conditional to scroll update

- package.json
Changelog script in package json refers to a deleted tool
> build: remove changelog script from package.json

- .github/workflows/deploy-dev-app.yml
Updates the Firebase preview instance for the dev-app previews to an internal one with more capacity.
> build: update firebase preview instance to internal one

- .prettierignore
- .yarnrc
Update to the latest version of yarn, 1.22.17.
> build: update to yarn v1.22.17

- CHANGELOG.md
- package.json
Reverts angular/components#23974
> Revert "Bump version to "v13.0.2" with changelog."

- integration/mdc-migration/BUILD.bazel
- src/cdk/schematics/ng-update/devkit-migration-rule.ts
- src/cdk/schematics/ng-update/public-api.ts
- src/cdk/schematics/ng-update/upgrade-data.ts
- src/cdk/schematics/testing/test-case-setup.ts
- src/cdk/schematics/update-tool/index.ts
- src/cdk/schematics/update-tool/migration.ts
- src/cdk/schematics/update-tool/utils/diagnostics.ts
- src/cdk/schematics/update-tool/utils/parse-tsconfig.ts
- src/cdk/schematics/update-tool/utils/virtual-host.ts
- src/material/schematics/BUILD.bazel
- src/material/schematics/collection.json
- src/material/schematics/ng-generate/mdc-migration/BUILD.bazel
- src/material/schematics/ng-generate/mdc-migration/index.ts
- src/material/schematics/ng-generate/mdc-migration/rules/theming-styles.spec.ts
- src/material/schematics/ng-generate/mdc-migration/rules/theming-styles.ts
- src/material/schematics/ng-generate/mdc-migration/schema.d.ts
- src/material/schematics/ng-generate/mdc-migration/schema.json
- src/material/schematics/ng-update/migrations/hammer-gestures-v9/hammer-gestures-migration.ts
> Initial update-tool and bundle setup for the mdc migration

- src/material/sidenav/drawer.ts
- src/material/sidenav/sidenav.ts
An older PR was merged in from before we had format checking.
> build: fix sidenav formatting

- CHANGELOG.md
Cherry-picks the changelog from the "13.1.x" branch to the next branch (master).
> docs: release notes for the v13.1.3 release

- CHANGELOG.md
- package.json
Also this PR cherry-picks the changelog for v13.2.0-rc.0 into the master branch so that the changelog is up to date.
> Update next branch to reflect new release-train "v13.3.0-next.0".

- CHANGELOG.md
- package.json
Reverts angular/components#24281
> Revert "Bump version to "v13.2.0" with changelog."

- CHANGELOG.md
> docs: release notes for the v13.2.0 release

- .github/workflows/feature-requests.yml
Add feature request voting process github actions to the repo.
> build: add an action for handling feature requests

- CHANGELOG.md
> docs: release notes for the v13.2.1 release

- src/cdk/overlay/dispatchers/overlay-keyboard-dispatcher.spec.ts
- src/cdk/overlay/dispatchers/overlay-keyboard-dispatcher.ts
- src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.spec.ts
- src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.ts
- tools/public_api_guard/cdk/overlay.md
Reverts angular/components#23962
> Revert "perf(cdk/overlay): add event listeners for overlay dispatchers outside of zone"

- src/material-experimental/mdc-checkbox/checkbox.ts
> fix(material-experimental/mdc-checkbox): add missing classes for checked

- src/material/schematics/ng-generate/mdc-migration/BUILD.bazel
- src/material/schematics/ng-generate/mdc-migration/rules/components/button/button-styles.spec.ts
- src/material/schematics/ng-generate/mdc-migration/rules/components/button/button-styles.ts
- src/material/schematics/ng-generate/mdc-migration/rules/components/checkbox/checkbox-styles.spec.ts
- src/material/schematics/ng-generate/mdc-migration/rules/components/checkbox/checkbox-styles.ts
- src/material/schematics/ng-generate/mdc-migration/rules/components/test-setup-helper.ts
- src/material/schematics/ng-generate/mdc-migration/rules/components/util.ts
- src/material/schematics/ng-generate/mdc-migration/rules/index.ts
> Add checkbox styles migrator

- CHANGELOG.md
> docs: release notes for the v13.2.2 release

- src/material/tabs/tabs.md
This docs update was missed in my most recent docs change.
> docs(material/tabs): Update tabs keyboard interaction section.

- src/components-examples/material/chips/chips-avatar/chips-avatar-example.html
- src/components-examples/material/chips/chips-avatar/chips-avatar-example.ts
- src/components-examples/material/chips/index.ts
> docs(material/chips): add chips avatar sample

- src/cdk/overlay/dispatchers/overlay-keyboard-dispatcher.spec.ts
- src/cdk/overlay/dispatchers/overlay-keyboard-dispatcher.ts
- src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.spec.ts
- src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.ts
- tools/public_api_guard/cdk/overlay.md
This is a re-submit as asked here https://github.com/angular/components/pull/23962#issuecomment-1034184023
> perf(cdk/overlay): add event listeners for overlay dispatchers outside of zone

- src/material/schematics/ng-add/schema.json
Fixes a formatting failure that made it in through an older PR.
> build: fix formatting failure

- src/material-experimental/mdc-dialog/_dialog-theme.scss
- src/material-experimental/mdc-dialog/dialog.scss
This reverts commit 353a5482e3811b8d684669973bfa02b4ac2ca0f6.
> Revert "feat(material-experimental/mdc-dialog): switch to new theming api (#23620)"

- CHANGELOG.md
> docs: release notes for the v13.2.5 release

- scripts/caretaking/firebase-functions/yarn.lock
- yarn.lock
Patch port of https://github.com/angular/components/pull/24488
> [13.2.x] build: lock file maintenance

- scripts/caretaking/firebase-functions/yarn.lock
- yarn.lock
Co-authored-by: Renovate Bot <bot@renovateapp.com>
> [13.2.x] build: lock file maintenance (#24531)

- src/cdk/schematics/collection.json
- src/material/schematics/collection.json
These schematics are meant to be used with `ng-add` and shouldn't be made visibily. By setting these schematics hidden we don't shown them in the `ng generate` help output.
Now
```
ng generate
Generates and/or modifies files based on a schematic.
Commands:
ng g <schematic>           Run the provided schematic.                                                                                                                 [default]
ng g address-form [name]                                                                                    [aliases: address-form, material-address-form, material-addressForm]
ng g dashboard [name]                                                                                                                              [aliases: material-dashboard]
ng g …
```
> fix(schematics): mark `ng-add` schematics as hidden

- integration/mdc-migration/golden/src/styles.scss
- src/material/schematics/ng-generate/mdc-migration/rules/components/autocomplete/autocomplete-styles.spec.ts
- src/material/schematics/ng-generate/mdc-migration/rules/components/autocomplete/autocomplete-styles.ts
- src/material/schematics/ng-generate/mdc-migration/rules/components/form-field/form-field-styles.spec.ts
- src/material/schematics/ng-generate/mdc-migration/rules/components/form-field/form-field-styles.ts
- src/material/schematics/ng-generate/mdc-migration/rules/components/input/input-styles.spec.ts
- src/material/schematics/ng-generate/mdc-migration/rules/components/input/input-styles.ts
- src/material/schematics/ng-generate/mdc-migration/rules/components/select/select-styles.spec.ts
- src/material/schematics/ng-generate/mdc-migration/rules/components/select/select-styles.ts
- src/material/schematics/ng-generate/mdc-migration/rules/index.ts
These four components are in this one PR since they have to be migrated together
> add autocomplete, form-field, input, and select styles migrator and tests

- firebase.json
Prevent the dev app site from being place in an iframe.
> build: prevent framing of dev app with X-Frame-Options

- src/material/core/typography/_typography.scss
> docs: Fix typo in word typpography

- CHANGELOG.md
> docs: release notes for the v13.3.2 release

- tools/public_api_guard/material/checkbox.md
Fixes a failure of the API golden check in master.
> build: fix API golden failure

- CHANGELOG.md
> docs: release notes for the v13.3.3 release

- .circleci/config.yml
- .circleci/rebase-pr.js
- .github/workflows/scorecard.yml
Preparation for the components repo as outlined our planning
document.
**TODO once merged:**
> build: preparation for primary branch rename in the Angular repos

- .github/CODEOWNERS
this is a patch port of #24787 24780
> build: add Zach (zarend) to datepicker code owners

- .circleci/config.yml
- .circleci/rebase-pr.js
Preparation for the components repo as outlined our planning
document.
> [11.x]: build: preparation for primary branch rename in the Angular repos

- src/cdk/menu/context-menu-trigger.ts
- src/cdk/menu/menu-trigger.ts
- src/cdk/menu/menu.spec.ts
- src/components-examples/cdk/menu/cdk-menu-context/cdk-menu-context-example.css
- src/components-examples/cdk/menu/cdk-menu-inline/cdk-menu-inline-example.css
- src/components-examples/cdk/menu/cdk-menu-menubar/cdk-menu-menubar-example.css
- src/components-examples/cdk/menu/cdk-menu-standalone-menu/cdk-menu-standalone-menu-example.css
- src/components-examples/cdk/menu/cdk-menu-standalone-menu/cdk-menu-standalone-menu-example.html
- src/components-examples/cdk/menu/cdk-menu-standalone-stateful-menu/cdk-menu-standalone-stateful-menu-example.css
- src/components-examples/cdk/menu/cdk-menu-standalone-stateful-menu/cdk-menu-standalone-stateful-menu-example.html
- src/dev-app/cdk-menu/cdk-menu-demo.html
Resolves some issues with the CDK menu. See the individual commits for more info, but at a high level, these changes:
* Fix a unit test that was only failing locally.
* Fix some accessibility issues in the docs examples.
* Resolve some UX issues when the user tries to scroll while a menu is open.
> Miscellaneous fixes for the CDK menu

- src/material-experimental/mdc-form-field/BUILD.bazel
- src/material-experimental/mdc-form-field/directives/floating-label.ts
- src/material-experimental/mdc-form-field/directives/line-ripple.ts
- src/material-experimental/mdc-form-field/directives/notched-outline.html
- src/material-experimental/mdc-form-field/directives/notched-outline.ts
- src/material-experimental/mdc-form-field/form-field.ts
Refactors the MDC form field so that it doesn't use any of MDC's adapters.
> refactor(material-experimental/mdc-form-field): remove MDC adapter usage

- .circleci/config.yml
> build: update saucelabs and browserstack key

- integration/ng-add-standalone/yarn.lock
- integration/yarn-pnp-compat/package.json
- integration/yarn-pnp-compat/yarn.lock
- package.json
- scripts/caretaking/firebase-functions/package.json
- scripts/caretaking/firebase-functions/yarn.lock
- yarn.lock
Bumps up the build dependencies to TypeScript 4.7 final.
> build: update to TypeScript 4.7 final

- src/cdk/schematics/migration.json
- src/cdk/schematics/ng-update/index.ts
- src/cdk/schematics/update-tool/target-version.ts
- src/material/schematics/migration.json
- src/material/schematics/ng-update/index.ts
Prepares the schematics infrastructure for the next major version.
> build: set up schematics for version 15

- src/material/schematics/migration-utilities/BUILD.bazel
- src/material/schematics/migration-utilities/index.spec.ts
- src/material/schematics/migration-utilities/index.ts
- src/material/schematics/ng-generate/mdc-migration/BUILD.bazel
- src/material/schematics/ng-generate/mdc-migration/rules/components/card/card-template.ts
- src/material/schematics/ng-generate/mdc-migration/rules/components/chips/chips-template.ts
- src/material/schematics/ng-generate/mdc-migration/rules/template-migration.ts
- src/material/schematics/ng-generate/mdc-migration/rules/template-migrator.ts
* move update file content updating logic to migration-utilities
> refactor(material/schematics): create shared migration utilities folder

- src/components-examples/material/chips/chips-avatar/chips-avatar-example.html
Fix image stretch issue raised here:
https://github.com/angular/components/issues/19822
> Fix mat-chip avatar image stretch issue

- src/material-experimental/mdc-core/theming/tests/BUILD.bazel
- src/material-experimental/mdc-core/theming/tests/test-theming.scss
- src/material/core/theming/tests/BUILD.bazel
- src/material/core/theming/tests/test-theming-bundle.scss
> build: ensure mdc snapshot tests run theming Sass tests

- src/cdk/dialog/dialog.spec.ts
- src/cdk/dialog/dialog.ts
Hello. I resume the PR https://github.com/angular/components/pull/25277 ldulary being absent for the next two months
> fix(cdk/dialog): use config injector if provided

- CHANGELOG.md
Cherry-picks the changelog from the "14.1.x" branch to the next branch (main).
> docs: release notes for the v14.1.1 release

- src/material/card/_card-theme.scss
- src/material/card/card.scss
- src/material/card/card.ts
This reverts commit 3738a2412d00fd3a7c8d24921b43e44e4bdbdad5.
> Revert "refactor(material/card): switch to new theming API"

- src/material/expansion/expansion.spec.ts
> fix(material/expansion): fix lint issue

- package.json
- yarn.lock
update to the latest version of ng-dev
> build: update ng-dev version

- src/bazel-tsconfig-build.json
- src/components-examples/material/form-field/form-field-custom-control/example-tel-input-example.html
- src/components-examples/material/form-field/form-field-hint/form-field-hint-example.html
- src/components-examples/material/list/list-single-selection/list-single-selection-example.html
- src/dev-app/example/example-list.ts
- src/dev-app/legacy-select/legacy-select-demo.html
- src/dev-app/legacy-select/legacy-select-demo.ts
- src/dev-app/select/select-demo.html
- src/dev-app/select/select-demo.ts
- src/material/legacy-select/select.html
- src/material/legacy-select/select.ts
- tools/public_api_guard/material/legacy-select.md
- tsconfig.json
Turns the extended template diagnostic warnings into errors and resolves all of the existing ones.
> fix(multiple): resolve extended template diagnostic warnings

- src/material/slider/BUILD.bazel
- src/material/slider/slider.ts
Switches to use more specific MDC slider targets to fix internal test failures
> Use more specific MDC slider targets

- pkg-externals.bzl
- src/material/slider/BUILD.bazel
- tools/public_api_guard/material/slider.md
Fix lint error in slider by running `yarn buildifier
src/material/slider/BUILD.bazel`
> build: fix lint error in slider

- src/material/legacy-select/select.spec.ts
- src/material/select/select.spec.ts
Tries to reduce the amount of flakes we've been seeing in the select tests by getting one of the slower tests to run faster.
> test(material/select): attempt to reduce test flakes

- .circleci/config.yml
Contains: https://github.com/angular/dev-infra/pull/838
> build: update shared dev-infra orb to fix snapshot tests

- guides/v15-mdc-migration.md
Updates the sections I was assigned to in the MDC migration guide.
> MDC migration guide updates

- scripts/saucelabs/start-tunnel.sh
Update to saucelabs connect 4.8.1
> build: update saucelabs connect version

- .github/workflows/dev-infra.yml
Update to the latest version of the action
> build: update commit message based labels action

- src/cdk/testing/test-element.ts
- tools/public_api_guard/cdk/testing.md
Adds a change that is present in g3, but not externally.
> build: sync g3 change

- scripts/breaking-changes.ts
Reworks the breaking changes script so that it doesn't depend on `tsutils`. This is a step towards removing the package completely from our dependencies.
> build: remove tsutils dependency from breaking changes script

- CHANGELOG.md
> docs: release notes for the v15.0.0-rc.0 release

- src/material/form-field/form-field.scss
> fix(material/form-field): don't block click on prefix/suffix when disabled

- src/material/schematics/ng-generate/mdc-migration/rules/template-migration.ts
* related to issue #26038
* catch & log errors from tmpl migrations
> fix(material/schematics): improve mdc-migration error logging

- src/material/slider/slider.ts
> fix(material/slider): fix slider resize w/ transforms

- src/material/schematics/ng-generate/mdc-migration/rules/tree-traversal.ts
* potential fix for issue #26038
> fix(material/schematics): add undefined check

- src/material/list/list.scss
Fixes a syntax error due to a bad rebase.
> build: resolve syntax error in list

- .github/workflows/build-dev-app.yml
- .github/workflows/deploy-dev-app.yml
Contains a fix for the missing trailing brace.
> build: update version of preview deploy actions

- .github/workflows/build-dev-app.yml
- .github/workflows/deploy-dev-app.yml
Contains a fix where the bash execution failed due to an unexpected quote character.
> build: update preview deploy github actions

- CHANGELOG.md
> docs: release notes for the v15.0.1 release

- src/material/schematics/ng-generate/mdc-migration/rules/components/button/button-styles.ts
> fix(material/schematics): update flat button styles class name mapping

- CHANGELOG.md
> docs: release notes for the v15.0.2 release

- src/material/schematics/ng-update/migrations/legacy-components-v15/constants.ts
> fix(material/schematics): fix transform for FloatLabelType

- CHANGELOG.md
> docs: release notes for the v15.0.3 release

- .github/workflows/deploy-dev-app.yml
- .gitignore
- firebase.json
> build: switch to canonical dev-infra GCP project for previews

- CHANGELOG.md
> docs: release notes for the v15.1.0 release

- tools/region-parser/region-parser.ts
the commented code of debugger in region parser file remove
> fix(multiple): remove the commented out code

- src/cdk/dialog/dialog.spec.ts
unused variable remove from the test case file
> fix(multiple): removed unused variable from sepc file

- src/components-examples/cdk/dialog/cdk-dialog-overview/cdk-dialog-overview-example.html
- src/components-examples/cdk/listbox/cdk-listbox-compare-with/cdk-listbox-compare-with-example.html
- src/components-examples/material/card/card-media-size/card-media-size-example.html
html tags like b and i are update and add the alt attribute in the img tag
> fix(multiple): update the html tags and add the alt attr

- CHANGELOG.md
> docs: release notes for the v15.1.1 release

- src/material/schematics/ng-generate/mdc-migration/rules/ts-migration/runtime-migration.ts
> fix(material/schematics): add string literal check

- .github/CODEOWNERS
- src/dev-app/BUILD.bazel
- src/dev-app/dev-app/dev-app-layout.html
- src/dev-app/performance/BUILD.bazel
- src/dev-app/performance/performance-demo.html
- src/dev-app/performance/performance-demo.scss
- src/dev-app/performance/performance-demo.ts
- src/dev-app/routes.ts
* provides easy setup for debugging the rendering speed of our components
> test(multiple): add performance testing page to dev-app

- CHANGELOG.md
> docs: release notes for the v15.1.3 release

- guides/typography.md
> docs(material/typography): fix "kids theme" example

- .circleci/config.yml
- .github/workflows/build-dev-app.yml
Update to the latest RBE setup after key rotation.
> build: update to latest remote build execution setup

- CHANGELOG.md
> docs: release notes for the v15.2.0 release

- CHANGELOG.md
> docs: release notes for the v15.2.3 release

- integration/mdc-migration/golden/yarn.lock
- integration/mdc-migration/sample-project/yarn.lock
- integration/ng-add-standalone/yarn.lock
- package.json
- yarn.lock
Bumps up the repo to the final version of TypeScript 5.
> build: update to TypeScript 5.0 final

- integration/mdc-migration/golden/yarn.lock
- integration/mdc-migration/sample-project/yarn.lock
- integration/ng-add-standalone/yarn.lock
- yarn.lock
Patch-port version of
https://github.com/angular/components/pull/26949
> build: fix browserlists unknown browser error for CLI integration tests

- src/material/progress-bar/progress-bar.scss
* remove todo since MDC claim's our workaround is the intended behavior - b/275625642
> docs(material/progress-bar): remove todo

- .github/workflows/scorecard.yml
Bumps up the scorecard dependencies in an attempt to fix the current failures.
> build: update scorecard dependencies

- .github/workflows/scorecard.yml
Updates the scoredcard config to include the ID token.
> build: update scorecard config

- integration/harness-e2e-cli/yarn.lock
- integration/ng-add-standalone/yarn.lock
- integration/ng-add/yarn.lock
- yarn.lock
Updates the caniuse version in an attempt to resolve some integration test failures.
> build: update caniuse version

- guides/theming.md
fixes: https://github.com/angular/components/issues/25702
> docs: fix reading hues from palettes

- src/material/table/row.ts
closes: https://github.com/angular/components/issues/27143
> docs(material/table): fix description for MatHeaderRow

- integration/harness-e2e-cli/package.json
- integration/harness-e2e-cli/yarn.lock
- integration/ng-add/package.json
- integration/ng-add/yarn.lock
- package.json
- yarn.lock
We were running a few versions behind on zone.js, compared to the framework.
> build: update zone.js version

- src/material/legacy-select/public-api.ts
- src/material/legacy-select/select.ts
- src/material/select/select.spec.ts
- src/material/select/select.ts
- tools/public_api_guard/material/legacy-select.md
- tools/public_api_guard/material/select.md
Adds an input that allows users to control the width of the panel.
Fixes #26000.
> feat(material/select): add input to control the panel width

- src/cdk/observers/private/shared-resize-observer.spec.ts
The resize observer tests have been causing some flakiness, because it's up to the browser when to fire the callback and iOS appears to be inconsistent with all other browsers.
These changes mock out the `ResizeObserver` API.
> test(cdk/observers): reduce flakiness in resize observer tests

- src/material/slider/slider-input.ts
- src/material/slider/slider-thumb.ts
> fix(material/slider): handle contextmenu events

- integration/harness-e2e-cli/yarn.lock
- integration/mdc-migration/golden/yarn.lock
- integration/mdc-migration/sample-project/yarn.lock
- integration/ng-add-standalone/yarn.lock
- integration/ng-add/yarn.lock
- integration/yarn-pnp-compat/package.json
- integration/yarn-pnp-compat/yarn.lock
- yarn.lock
Fixes that the integration tests were failing because of a browserslist error on the patch branch.
> build: resolve browserslist errors in patch branch

- CHANGELOG.md
> docs: release notes for the v16.1.1 release

- src/material/slider/slider.spec.ts
- src/material/slider/slider.ts
- src/material/slider/testing/slider-harness.spec.ts
> fix(material/slider): fix voiceover on ios

- src/material/select/select.scss
Fixes that the select.scss is out of sync with g3.
> build: fix out of sync file

- src/material/core/tokens/m2/mdc/_dialog.scss
- src/material/core/tokens/tests/test-validate-tokens.scss
Adds a test for the dialog tokens since one wasn't added when the dialog was converted to tokens.
> test(material/dialog): add tokens test

- src/google-maps/README.md
> docs(google-maps): remove synchronous loading example

- CHANGELOG.md
- package.json
This reverts commit 71eb8cbc8550da57af106fa1f641412cb5bffaf4.
> Revert "release: cut the v16.1.4 release"

- .circleci/config.yml
- .github/angular-robot.yml
- .github/workflows/ci.yml
Migrate lint to Github Actions
> ci: migrate lint job from CircleCI to GHA

- src/dev-app/datepicker/datepicker-demo.html
- src/material/core/theming/tests/theming-api.spec.ts
- src/material/core/tokens/m2/mat/_datepicker.scss
- src/material/datepicker/BUILD.bazel
- src/material/datepicker/_datepicker-theme.scss
- src/material/datepicker/calendar-body.scss
- src/material/datepicker/calendar.scss
- src/material/datepicker/date-range-input.scss
- src/material/datepicker/datepicker-content.scss
- src/material/datepicker/datepicker-toggle.scss
Reworks the datepicker to use tokens for theming.
> refactor(material/datepicker): switch to tokens API

- src/cdk/menu/menu-item.ts
- src/cdk/menu/menu-trigger.ts
The CDK menu supports opening a nested menu by hover, but the problem is that touch devices dispatch fake `mouseenter` events which end up closing the menu immediately. These changes add some logic to ignore such events.
Fixes #27508.
> fix(cdk/menu): nested menus requiring two taps to open touch devices

- src/components-examples/material/sidenav/BUILD.bazel
- src/components-examples/material/sidenav/sidenav-fixed/sidenav-fixed-example.ts
Error: mat-form-field must contain a MatFormFieldControl.
> docs: fix broken example due to missing input module import

- DEV_ENVIRONMENT.md
> docs: update developer environment to setup project

- src/material/slider/slider-input.ts
fixes https://github.com/angular/components/issues/27700
> fix(material/slider): keep ios safari slider value binding in sync

- src/cdk/overlay/overlay-directives.ts
- tools/public_api_guard/cdk/overlay.md
add disposeOnNavigation to overlay directive
fixes #27545
> feat(cdk/overlay): add disposeOnNavigation

- src/material/slider/slider.scss
* fixes https://github.com/angular/components/issues/27612
> fix(material/slider): set word-break on value-indicator

- src/material/paginator/_paginator-variables.scss
This reverts commit 8d44900ead60f8a58bd44845f8d2c7953d0d9492.
> Revert "refactor(material/paginator): remove unused file (#27685)"

- .circleci/config.yml
- .github/workflows/ci.yml
Migrate linker tests to Github Actions
> ci: migrate linker tests to GHA

- CHANGELOG.md
- package.json
This reverts commit 7e755d4b9a383c6818988d3c383e814ac5889518.
> Revert "release: cut the v16.2.2 release"

- .stylelintrc.json
- src/material-experimental/column-resize/_column-resize-theme.scss
- src/material-experimental/popover-edit/_popover-edit-theme.scss
- src/material/core/color/_all-color.scss
- src/material/core/density/private/_all-density.scss
- src/material/core/focus-indicators/_private.scss
- src/material/core/theming/_all-theme.scss
- src/material/core/theming/_inspection.scss
- src/material/core/theming/_m2-inspection.scss
- src/material/core/tokens/m2/mat/_datepicker.scss
- src/material/core/tokens/m2/mat/_stepper.scss
- src/material/core/typography/_all-typography.scss
- src/material/core/typography/_typography.scss
- src/material/datepicker/_datepicker-theme.scss
- src/material/sort/_sort-theme.scss
- src/material/stepper/_stepper-theme.scss
- src/material/tree/_tree-theme.scss
Converts: datepicker, tree, stepper, sort, column-resize, popover-edit
> refactor(multiple): convert components to theme inspection API (round 3)

- WORKSPACE
- package.json
- yarn.lock
Updates the repo to the latest version of Sass since we had fallen behind a bit.
> build: update to latest version of Sass

- guides/theming.md
> docs(theming): change color pallete format

- src/material/autocomplete/autocomplete.spec.ts
Fixes a lint failure on the main branch.
> build: fix lint failure

- src/dev-app/theme-m3.scss
- src/material-experimental/theming/_custom-tokens.scss
- src/material-experimental/theming/_m3-density.scss
- src/material-experimental/theming/_m3-tokens.scss
- src/material/radio/_radio-theme.scss
> feat(material-experimental/theming): add M3 radio support

- src/material/button/_button-theme.scss
- src/material/core/tokens/m2/mdc/_button-protected.scss
* fix bug where the raised button is accidentally using the flat button color tokens
> fix(material/button): fix color tokens of raised buttons

- src/dev-app/snack-bar/snack-bar-demo.ts
- src/material/snack-bar/module.ts
- src/material/snack-bar/simple-snack-bar.ts
- src/material/snack-bar/snack-bar-container.ts
- src/material/snack-bar/snack-bar-content.ts
- src/material/snack-bar/snack-bar.ts
- tools/public_api_guard/material/snack-bar.md
Converts the snack bar module to standalone.
> feat(material/snack-bar): convert to standalone

- src/material/toolbar/toolbar.scss
* increase specificity of mat-toolbar overrides
> fix(material/button): buttons in toolbars

- .github/workflows/ci.yml
Provide environment variables for deploying docs site
> ci: fix environment variables

- .github/workflows/ci.yml
Include the env variables for the step for deploying docs
> ci: provide environment variables to the right step

- src/material/button/_button-theme.scss
Adds a change that was missed in #28007.
> refactor(material/button): fix out of sync file

- .github/workflows/ci.yml
Include the env variables for the step for deploying docs related to doc site access
> ci: provide environment variables to the deploy step

- src/material/schematics/ng-add/index.spec.ts
Fixes a failing test in the `ng add` schematic.
> test(material/schematics): fix failing test

- .github/workflows/deploy-dev-app-main-push.yml
This will make it easier to discover the URL for the dev-app deployment.
> ci: add deployment status for automatic dev-app deployments

- src/material/button/_icon-button-theme.scss
Fixes that the RC branch was failing the lint check.
> build: fix lint failure in rc branch

- CHANGELOG.md
> docs: release notes for the v17.0.0 release

- integration/harness-e2e-cli/yarn.lock
Update the yarn lockfile in integration/harness-e2e-cli directory. It seems to be out-of-date with its corresponding package.json file.
Updated the lockfile by running command:
```
cd integration/harness-e2e-cli && yarn
```
> build: update integration/harness-e2e-cli/yarn.lock

- src/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html.template
- src/material/schematics/ng-generate/address-form/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html.template
- src/material/schematics/ng-generate/dashboard/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html.template
- src/material/schematics/ng-generate/navigation/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html.template
- src/material/schematics/ng-generate/navigation/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
Reworks our schematics to use the new control from Angular v17.
> fix(material/schematics): switch to new control flow

- CODE_REVIEWS.md
Update bulleted points in CODE_REVIEWS.md to remove '.' at the end of each point to be cohesive with the CONTRIBUTING.md guidelines.
> docs: update CODE_REVIEWS.md bullet formatting

- CHANGELOG.md
This reverts commit 4c255ab34126619f0cd12452f5844d91ac612111.
> Revert "release: cut the v17.1.0-next.0 release"

- src/dev-app/youtube-player/youtube-player-demo.ts
- src/universal-app/kitchen-sink/kitchen-sink.ts
- src/youtube-player/README.md
- src/youtube-player/youtube-module.ts
- src/youtube-player/youtube-player.spec.ts
- src/youtube-player/youtube-player.ts
- tools/public_api_guard/youtube-player/youtube-player.md
Converts youtube player module to standalone
> refactor(youtube-player): convert to standalone

- src/cdk/a11y/aria-describer/aria-reference.ts
Observed a tiny but measurable improvement to the performance of creating and destroying matTooltips.
> perf(cdk/a11y): Micro-optimizations to aria-reference.ts.

- src/material/autocomplete/autocomplete.ts
- src/material/menu/menu.ts
- src/material/select/select.ts
- src/material/sidenav/drawer.ts
- src/material/sidenav/sidenav.ts
- src/universal-app/kitchen-sink/kitchen-sink.html
Cherry-picks the changes from #28343 and #28340 to the patch branch.
> Cherry-pick hydration fixes

- tools/public_api_guard/material/select.md
Fixes a failure in the API goldens.
> build: resolve api golden failure

- src/material/stepper/stepper.html
- src/material/stepper/stepper.ts
- tools/public_api_guard/material/stepper.md
Enables hydration on the stepper and adds a workaround for an issue that prevented the content from being rendered out.
> fix(material/stepper): enable hydration

- tools/public_api_guard/material/core.md
Fixes an out-of-date API golden.
> build: update API golden

- src/dev-app/theme-m3.scss
- src/material-experimental/theming/_custom-tokens.scss
- src/material-experimental/theming/_m3-density.scss
- src/material-experimental/theming/_m3-tokens.scss
- src/material/_index.scss
- src/material/core/selection/pseudo-checkbox/_pseudo-checkbox-theme.scss
- src/material/core/tokens/m2/_index.scss
Sets up the M3 tokens for the pseudo checkbox component.
> feat(material-experimental/theming): add M3 tokens for pseudo checkbox

- src/components-examples/material/input/input-prefix-suffix/input-prefix-suffix-example.html
|Before|After|
|-|-|
|<video src='https://github.com/angular/components/assets/32067562/670edd35-0e9b-4a08-8ed1-6081bddeae6e'>|<video src='https://github.com/angular/components/assets/32067562/8af386a6-4ddd-4947-8aa7-7c25e321de98'>|
> Fix example in input-prefix-suffix-example.html

- src/material-experimental/theming/_custom-tokens.scss
- src/material-experimental/theming/_m3-tokens.scss
- src/material/checkbox/_checkbox-theme.scss
- src/material/checkbox/checkbox.scss
- src/material/core/tokens/m2/_index.scss
- src/material/core/tokens/m2/mat/_checkbox.scss
Includes a couple of fixes to get the M3 checkbox to match the spec.
> M3 checkbox fixes

- CHANGELOG.md
- package.json
This reverts commit b22362474a53b1b04981f6a8c4f02f6ff79ad1c1.
> Revert "release: cut the v17.1.0 release"

- CHANGELOG.md
This reverts commit cd754d40a82c86e763c0dea02ddb6859b6ab38df.
> Revert "release: cut the v17.2.0-next.0 release"

- src/dev-app/dev-app/dev-app-layout.scss
- src/dev-app/theme-m3.scss
- src/material-experimental/theming/_custom-tokens.scss
- src/material/core/tokens/m2/mat/_sidenav.scss
- src/material/sidenav/drawer.scss
Aligns the sidenav styles with the M3 spec.
> refactor(material-experimental/theming): align sidenav with M3

- src/dev-app/chips/chips-demo.html
- src/material-experimental/theming/_custom-tokens.scss
- src/material-experimental/theming/_m3-tokens.scss
- src/material/chips/_chips-theme.scss
- src/material/chips/chip.scss
- src/material/core/tokens/m2/_index.scss
- src/material/core/tokens/m2/mat/_chip.scss
- src/material/core/tokens/m2/mdc/_chip.scss
Depends on https://github.com/angular/components/pull/28497
> fix(material/chips): Tokenize the selected state

- CHANGELOG.md
Cherry-picks the changelog from the "17.2.x" branch to the next branch (main).
> docs: release notes for the v17.2.0 release

- src/material/tabs/ink-bar.ts
- src/material/tabs/tab-label-wrapper.ts
- src/material/tabs/tab-nav-bar/tab-nav-bar.ts
- tools/public_api_guard/material/tabs.md
Replaces a usage of a mixin function in the tabs with a base class.
> refactor(material/tabs): remove mixin function

- src/material-experimental/theming/_custom-tokens.scss
- src/material/core/tokens/m2/mat/_switch.scss
- src/material/slide-toggle/slide-toggle.scss
* fix(material/slide-toggle): m3 selected track outline
* fixup! fix(material/slide-toggle): m3 selected track outline
(cherry picked from commit 63a764de6147a5c1cb09f388de454eda9ee3414a)
> fix(material/slide-toggle): m3 selected track outline (#28625)

- .github/workflows/ci.yml
Pin the dep for actions/upload-artifact
> ci: pin dependency for actions/upload-artifact

- CHANGELOG.md
> docs: release notes for the v17.3.0 release

- src/cdk/a11y/live-announcer/live-announcer.spec.ts
- src/cdk/observers/observe-content.spec.ts
- src/cdk/observers/observe-content.ts
- src/material/tabs/tab-header.spec.ts
Cherrypick of #28858 for patch branch
> fix(cdk/observers): don't observe content of comments

- src/cdk/scrolling/virtual-scroll-viewport.ts
- src/dev-app/main.ts
This reverts commit d91d0d424b043c4da7b69d296967e62a751eac23.
This broke an app in g3, reverting while we investigate
> Revert "fix(cdk/scrolling): fix virtual scrolling jankiness with run coalescing (#28846)

- package.json
- src/youtube-player/package.json
- yarn.lock
We were a few versions behind on the typings for YouTube. These changes update to the latest ones.
> build: update to latest YouTube typings

- src/components-examples/material/form-field/form-field-prefix-suffix/form-field-prefix-suffix-example.html
- src/components-examples/material/form-field/form-field-prefix-suffix/form-field-prefix-suffix-example.ts
> Bug #29047 - Glitchy password form field 

- src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
- src/cdk/a11y/focus-monitor/focus-monitor.zone.spec.ts
- src/cdk/a11y/live-announcer/live-announcer.spec.ts
- src/cdk/clipboard/copy-to-clipboard.spec.ts
- src/cdk/drag-drop/directives/drag.spec.ts
- src/cdk/drag-drop/directives/drag.zone.spec.ts
- src/cdk/drag-drop/directives/test-utils.spec.ts
- src/cdk/drag-drop/drag-drop.spec.ts
- src/cdk/listbox/listbox.spec.ts
- src/cdk/observers/observe-content.spec.ts
- src/cdk/overlay/overlay-directives.spec.ts
- src/cdk/overlay/overlay-directives.zone.spec.ts
cherrypick #29083 to patch branch
> test: move some CDK tests to zoneless

- src/dev-app/main.ts
- src/material/core/style/_vendor-prefixes.scss
- src/material/table/table.scss
Simplifies the table's structural styles to make them smaller and easier to maintain. Also fixes an error in the table demo.
> refactor(material/table): simplify structural styles

- src/material/list/_list-theme.scss
- src/material/list/list-option.scss
- src/material/radio/_radio-common.scss
- src/material/radio/_radio-theme.scss
- src/material/radio/radio.scss
Simplifies the radio button's structural styles to make them smaller and easier to maintain.
> refactor(material/radio): simplify structural styles

- src/material/form-field/form-field.ts
This reverts commit 6318f24d57572b9aeb1da9b4556030fd38efad8a because I broke some apps internally.
> Revert "fix(material/form-field): outline label position (#29138)"

- src/material/button/_button-base.scss
- src/material/button/_button-theme.scss
- src/material/button/button.scss
- src/material/core/tokens/m2/mdc/_extended-fab.scss
- src/material/core/tokens/m2/mdc/_fab-small.scss
- src/material/core/tokens/m2/mdc/_fab.scss
- src/material/core/tokens/m2/mdc/_protected-button.scss
- src/material/core/tokens/m3/mdc/_protected-button.scss
- src/material/core/tokens/tests/test-validate-tokens.scss
Simplifies the structural styles for the button to make them simpler and easier to maintain.
> refactor(material/button): simplify structural styles

- src/material/core/internal-form-field/internal-form-field.scss
Reworks the internal form field styles to be smaller and easier to maintain.
> refactor(material/core): simplify internal form field styles

- src/material/chips/chip.scss
This reverts commit d6aed804460d4b75082d7d04e051f2cae9b4f8f6.
> Revert "fix(material/chips): remove button is too small (#29351)"

- tools/public_api_guard/material/tooltip.md
Fixes an outdated API golden that is breaking the CI.
> build: fix outdated API golden

- src/material/core/style/_elevation.scss
Simplifies the elevation styles to make them more maintainable.
> refactor(material/core): simplify elevation styles

- src/material/core/m2/_typography.scss
Simplifies the typography setup to make it easier to maintain.
> refactor(material/core): simplify typography setup

- src/dev-app/slide-toggle/slide-toggle-demo.html
- src/dev-app/slide-toggle/slide-toggle-demo.ts
- src/material/slide-toggle/slide-toggle-config.ts
- src/material/slide-toggle/slide-toggle.html
- src/material/slide-toggle/slide-toggle.scss
- src/material/slide-toggle/slide-toggle.spec.ts
- src/material/slide-toggle/slide-toggle.ts
- tools/public_api_guard/material/slide-toggle.md
Adds the `disabledInteractive` input which allows users to interact with slide toggles that are disabled.
> feat(material/slide-toggle): add the ability to interact with disabled toggle

- src/material/core/theming/tests/theming-definition-api.spec.ts
- src/material/core/tokens/m3/definitions/_md-sys-color.scss
> fix(material/core): Fix incorrect color role mappings

- src/material/core/theming/tests/m3-theme.spec.ts
Fixes a build that was breaking after #29688.
> build: fix broken build

- src/material/list/list.ts
> docs: show MatListItem activated type

- src/dev-app/dev-app/dev-app-state.ts
Sets the dev app to M3 when landing on it for the first time.
> build: default the dev app to M3

- CHANGELOG.md
- package.json
This reverts commit 74dc8de5701a1bd660de469cdd9271c4e484f967.
> Revert "release: cut the v19.0.0-next.9 release"

- guides/schematics.md
- guides/theming.md
> docs: update theme schematic link for v18

- CHANGELOG.md
> docs: release notes for the v19.0.0-rc.0 release

- src/cdk/testing/protractor/protractor-element.ts
Fixes a file that isn't in sync with the internal codebase.
> refactor(cdk/testing): fix out of sync file

- CHANGELOG.md
> docs: release notes for the v19.0.0 release

- .github/workflows/ci.yml
- .github/workflows/deploy-dev-app-main-push.yml
- .github/workflows/dev-infra.yml
- .github/workflows/google-internal-tests.yml
- .github/workflows/pr.yml
- .github/workflows/preview-build-dev-app.yml
- .github/workflows/preview-deploy-dev-app.yml
- .github/workflows/scheduled-ci.yml
> ci: update to latest actions from angular/dev-infra

- guides/creating-a-custom-form-field-control.md
> fix(docs): update errorState example to cover handle missing state

- src/material/form-field/form-field.md
> fix(docs): update document refs to mat-chip-set

- src/components-examples/material/sidenav/BUILD.bazel
Fixes a missing dependency that's breaking the build.
> build: add missing dependency

- .github/workflows/assistant-to-the-branch-manager.yml
- .github/workflows/ci.yml
- .github/workflows/deploy-dev-app-main-push.yml
- .github/workflows/dev-infra.yml
- .github/workflows/google-internal-tests.yml
- .github/workflows/pr.yml
- .github/workflows/preview-build-dev-app.yml
- .github/workflows/preview-deploy-dev-app.yml
- .github/workflows/scheduled-ci.yml
- material.angular.io/.github/workflows/ci.yml
- material.angular.io/.github/workflows/pr.yml
- material.angular.io/WORKSPACE.bazel
Closes #30219 as a pr takeover
> build: update angular shared dev-infra code to 359350b

- src/material/select/select.scss
> fix(material/select): remove color transition w/ no animations module

- src/material/slider/slider.spec.ts
- src/material/slider/slider.ts
> fix(material/slider): tick mark positioning

- src/components-examples/cdk/tree/cdk-tree-flat-children-accessor/cdk-tree-flat-children-accessor-example-data.ts
- src/components-examples/cdk/tree/cdk-tree-flat-children-accessor/cdk-tree-flat-children-accessor-example.ts
- src/components-examples/cdk/tree/cdk-tree-flat-level-accessor/cdk-tree-flat-level-accessor-example-data.ts
- src/components-examples/cdk/tree/cdk-tree-flat-level-accessor/cdk-tree-flat-level-accessor-example.ts
- src/components-examples/cdk/tree/cdk-tree-nested-children-accessor/cdk-tree-nested-children-accessor-example-data.ts
- src/components-examples/cdk/tree/cdk-tree-nested-children-accessor/cdk-tree-nested-children-accessor-example.ts
- src/components-examples/cdk/tree/cdk-tree-nested-level-accessor/cdk-tree-nested-level-accessor-example-data.ts
- src/components-examples/cdk/tree/cdk-tree-nested-level-accessor/cdk-tree-nested-level-accessor-example.ts
> docs-bug(cdk/tree): fix broken examples in stackblitz

- material.angular.io/src/app/pages/component-sidenav/component-sidenav.ts
- src/material/chips/chip-grid.spec.ts
Removes a couple of animations that aren't necessary anymore.
> Remove unnecessary animations

- src/components-examples/material/chips/chips-autocomplete/chips-autocomplete-example.html
> docs: clear input field whenever a selection is made in chips autocomplete example

- src/material/chips/chip-listbox.spec.ts
Fixes a test that's failing at head.
> build: fix failing test

- .github/workflows/pr.yml
Begin checking upstream dependency licenses.
> ci: begin checking licenses of upstream dependencies to ensure they are approved

- package.json
Bumps the main branch to target v20.
> build: update main branch to v20

- src/material/slide-toggle/slide-toggle.scss
This reverts commit d9460557f734df46e6f20a35877e442f4cda0280.
> Revert "perf(material/slide-toggle): Optimize :state descendant selectors

- package.json
- yarn.lock
Updates the repo to TypeScript 5.8 to be in line with the rest of Angular.
> build: update to TypeScript 5.8

- tools/extract-tokens/extract-tokens.ts
Removes a log that was left after debugging.
> build: remove leftover log

- .aspect/rules/external_repository_action_cache/npm_translate_lock_MzA5NzUwNzMx
- CHANGELOG.md
- package.json
- pnpm-lock.yaml
This reverts commit a0fcdb69cb56965ad08ec3a6f2c749d84a0bec1c.
> Revert "release: cut the v20.0.0-next.6 release"

- src/material/snack-bar/snack-bar-config.ts
- src/material/snack-bar/testing/snack-bar-harness.spec.ts
change politeness level of snack bar to polite to match docs
fixes b/364250804
> fix(material/snack-bar): change politeness level

- .github/workflows/ci.material-aio.yml
- .github/workflows/ci.yml
- .github/workflows/pr.material-aio.yml
- .github/workflows/pr.yml
- WORKSPACE
- docs/BUILD.bazel
- scripts/docs-deploy/monitoring/index.mts
Backport of last two commits on `main`. 
https://github.com/angular/components/commit/c624353c91e68817b124baa2d61386d13041c3fd
https://github.com/angular/components/commit/917187d610be1940f24c59e69cb2a3fb215b186a
> Backport of CI fixes

- package.json
- pnpm-lock.yaml
Re-adds accidentally removed ibazel
> build: re-add accidentally removed ibazel

- CHANGELOG.md
This reverts commit de7ef428e6be67457d76f8faff66410e145a767e.
> Revert "release: cut the v19.2.13 release"

- CHANGELOG.md
> docs: release notes for the v19.2.14 release

- WORKSPACE
Includes a few improvements to the Jasmine integration to better show errors.
> build: update `rules_browsers` to include latest jasmine improvements

- pnpm-lock.yaml
- pnpm-workspace.yaml
- src/dev-app/main.ts
- test/angular-test.init.ts
Updates the repo to the release candidate of Angular v20 and resolves a breaking change.
> build: update to the Angular v20 RC

- renovate.json
Re-enables Renovate and picks up all the great improvements from @alan-agius4
> ci: re-enable renovate and sync with config from framework

- src/cdk-experimental/ui-patterns/behaviors/expansion/expansion.spec.ts
Fixes that the build is broken after the latest commit.
> build: fix compilation error

- goldens/cdk/testing/index.api.md
> build: update golden

- CHANGELOG.md
> docs: release notes for the v20.0.0-rc.1 release

- WORKSPACE
- docs/tools/lighthouse-audit.mjs
Update dev-infra for latest RBE changes.
> build: update dev-infra for latest RBE changes

- WORKSPACE
- docs/tools/lighthouse-audit.mjs
Update dev-infra for latest RBE changes.
> [19.2.x] build: update dev-infra for latest RBE changes (#31137)

- docs/src/app/material-docs-app.ts
- docs/src/app/shared/header-tag-manager.ts
Let's update the cannonical link for each page. This is the same code used on ADEV.
> docs: dynamic canonical link

- goldens/cdk/accordion/index.api.md
- goldens/material/select/index.api.md
- goldens/material/tabs/index.api.md
- src/cdk/accordion/accordion-item.ts
- src/components-examples/material/checkbox/checkbox-harness/checkbox-harness-example.spec.ts
- src/material/checkbox/checkbox.ts
- src/material/checkbox/testing/checkbox-harness.spec.ts
- src/material/core/option/option.ts
- src/material/datepicker/calendar.spec.ts
- src/material/datepicker/calendar.ts
- src/material/datepicker/date-range-input-parts.ts
- src/material/datepicker/date-range-input.spec.ts
- src/material/expansion/accordion.spec.ts
- src/material/select/select.spec.ts
- src/material/select/select.ts
- src/material/sidenav/drawer.spec.ts
- src/material/sidenav/drawer.ts
- src/material/sidenav/sidenav.spec.ts
- src/material/sidenav/testing/sidenav-harness.spec.ts
- src/material/tabs/tab-nav-bar/tab-nav-bar.spec.ts
- src/material/tabs/tab-nav-bar/tab-nav-bar.ts
Fixes "changed after checked" errors across several components. See the individual commits for more information.
> Resolve more "changed after checked" errors

- CHANGELOG.md
- package.json
This reverts commit 063b7e9c359b79aa59b1d3589fd1146a5b202af9.
> Revert "release: cut the v20.0.0 release"

- goldens/material/button/testing/index.api.md
Reflects updates made in https://github.com/angular/components/pull/31327
> fix(material/button): update button golden

- CHANGELOG.md
Cherry-picks the changelog from the "20.1.x" branch to the next branch (main).
> docs: release notes for the v20.1.0 release

- pnpm-lock.yaml
- src/youtube-player/fake-youtube-player.ts
See associated pull request for more information.
Closes #31463 as a pr takeover
> build: lock file maintenance

- package.json
- pnpm-lock.yaml
- src/youtube-player/fake-youtube-player.ts
- src/youtube-player/package.json
Updates the YouTube player package to the latest types and resolves a breakage.
> fix(youtube-player): update to latest types and fix error

- pnpm-lock.yaml
Fixes that the lock file in the patch branch was out of sync.
> build: broken lock file in patch branch

- CHANGELOG.md
Cherry-picks the changelog from the "20.2.x" branch to the next branch (main).
> docs: release notes for the v20.2.0 release

- .github/workflows/assistant-to-the-branch-manager.yml
- .github/workflows/ci.material-aio.yml
- .github/workflows/ci.yml
- .github/workflows/deploy-dev-app-main-push.yml
- .github/workflows/dev-infra.yml
- .github/workflows/docs-preview-build.yml
- .github/workflows/docs-preview-deploy.yml
- .github/workflows/google-internal-tests.yml
- .github/workflows/pr.material-aio.yml
- .github/workflows/pr.yml
- .github/workflows/preview-build-dev-app.yml
- .github/workflows/preview-deploy-dev-app.yml
- .github/workflows/scheduled-ci.yml
- MODULE.bazel
- package.json
- pnpm-lock.yaml
See associated pull request for more information.
Closes #31882 as a pr takeover
> [20.2.x] build: update cross-repo angular dependencies 

- goldens/cdk/overlay/index.api.md
- scripts/deploy/publish-build-artifacts.sh
The snapshots job was failing because we don't have a builds repo for Angular ARIA yet.
> build: fix snapshots job

- src/components-examples/material/list/list-single-selection-reactive-form/list-single-selection-reactive-form-example.html
- src/components-examples/material/list/list-single-selection-reactive-form/list-single-selection-reactive-form-example.ts
- src/components-examples/material/list/list-single-selection/list-single-selection-example.html
- src/components-examples/material/list/list-single-selection/list-single-selection-example.ts
- Revert single selection example from #29348
close #31989
> docs(material/list): single selection example
