angular/components

README.md

chore(): add quick links to README

---

src/components/button/button.spec.ts
src/components/button/button.ts
tslint.json

R: @robertmesserle @hansl @kara
I based the rules on Google's style guide for JS and from my own preferences. Let me know if you disagree with something.

chore(): add tslint.json

---

test/karma.config.ts
tslint.json

chore(): remove triple-equals lint rule & make some lint fixes to karma config.

---

CODING_STANDARDS.md

R: @robertmesserle @hansl @kara 
Let me know if there's anything we should change or add.

docs(): add coding standards doc

---

ember-cli-build.js
src/demo-app/button/button-demo.html
src/demo-app/button/button-demo.ts
src/demo-app/card/card-demo.html
src/demo-app/card/card-demo.scss
src/demo-app/card/card-demo.ts
src/demo-app/demo-app.html
src/demo-app/demo-app.scss
src/demo-app/demo-app.ts
src/demo-app/sidenav/sidenav-demo.html
src/demo-app/sidenav/sidenav-demo.scss
src/demo-app/sidenav/sidenav-demo.ts
src/index.html
src/main.ts

chores(demos): add router to separate demo pages

---

.gitignore
.travis.yml
docs/dart/writing-compatible-typescript.md
ember-cli-build.js
package.json
pubspec.yaml
scripts/ci/README.md
scripts/ci/build-and-test.sh
scripts/ci/dart_analyzer.ts
scripts/ci/install_dart.sh
scripts/ci/sources/env_dart.sh
scripts/ci/sources/mode.sh
scripts/ci/sources/tunnel.sh
src/components/button/button.spec.ts
src/components/sidenav/sidenav.spec.ts
src/components/sidenav/sidenav.ts
src/directives/dir/dir.ts
src/main.dart
test/karma-test-shim.js
test/karma.config.ts
test/packages
tools/broccoli/broccoli-dartfmt.ts
tools/build/dart.ts
tools/build/dart_analyzer.ts
tools/travis/fold.ts

What remains to clear Issue #37:
* facades implementation (we don't need any right now)
* moving the files to a pub-compatible directory structure.
* running dartanalyzer
* running unit tests in Dart.
Now the code is formatted (and validated). Just not dartanalyzed.
The rest of the typescript code has been improved to be Dart compatible.

feat(): Dartanalyzer!

---

DEV_ENVIRONMENT.md
docs/scss-theming.md
src/core/style/_palette.scss

docs(): add docs for new devs to get started.

---

docs/dart/writing-compatible-typescript.md
package.json
scripts/ci/build-and-test.sh
scripts/ci/dart_analyzer.ts
src/components/progress-circle/progress_circle.spec.ts
src/components/progress-circle/progress_circle.ts
src/components/sidenav/sidenav.spec.ts
src/demo-app/demo-app.ts
tools/build/dart_analyzer.ts

Adding Dartanalyzer to travis. Please note this is branched off PR #69, which needs to be merged first.

build(): Dartanalyzer travis

---

docs/dart/writing-compatible-typescript.md

docs(): add gotcha for dart not having generic methods.

---

.gitignore
.travis.yml
DEV_ENVIRONMENT.md
ember-cli-build.js
package.json
scripts/ci/build-and-test.sh
src/components/sidenav/sidenav.spec.ts
src/index.html
src/typings.d.ts
test/karma-test-shim.js
test/karma.config.ts
tools/broccoli/broccoli-ts2dart.ts
tools/build/dart_analyzer.ts
typings.json

This took longer because of ts2dart which was trying to find stuff in the wrong place.

chore(): update to Beta.6, including having our own typings.

---

config/environment.js

Fixes the router location strategy. Can't find the issue # right now.

chore(): add environment configuration to configure the router.

---

src/core/portal/README.md
src/core/portal/portal-directives.ts
src/core/portal/portal.spec.ts
src/core/portal/portal.ts
src/demo-app/demo-app.html
src/demo-app/demo-app.scss
src/demo-app/demo-app.ts
src/demo-app/portal/portal-demo.html
src/demo-app/portal/portal-demo.scss
src/demo-app/portal/portal-demo.ts
src/index.html
src/main.ts
test/karma.config.ts

R: @hansl @kara 
See the [design doc](https://docs.google.com/document/d/1jSMjkKSdzbQa2cuCeSFpzFAwDHr7xY4eqsXkfF6MeqA/preview)

feat(portal): add initial portal foundation

---

README.md

chore(): update README w/ project status

---

src/components/button/button.ts
src/components/progress-circle/progress_circle.ts
src/components/sidenav/sidenav.html
src/components/sidenav/sidenav.spec.ts
src/components/sidenav/sidenav.ts
src/core/facade/test_injector.ts
src/core/portal/portal-directives.ts
src/core/portal/portal.ts
src/directives/dir/dir.ts
tools/build/dart_analyzer.ts
tools/typings/jasmine/jasmine.d.ts
tslint.json

style(): change all private identifiers to leading underscore

---

src/components/card/README.md

docs(card): added docs for card

---

test/browser-providers.ts

build(): make FF beta optional until SL fixes it.

---

src/tsconfig.json

R: @hansl 
To be used in npm releases

build(): generate .d.ts files during build.

---

.gitattributes
.travis.yml
e2e/_screenshot.js
e2e/index.e2e.js
package.json
protractor.conf.js
screenshots/initial state.screenshot.png
scripts/ci/build-and-test.sh
scripts/ci/sources/tunnel.sh
scripts/e2e.sh
scripts/sauce/sauce_config.js
scripts/sauce/sauce_connect_block.sh
scripts/sauce/sauce_connect_setup.sh

initial setup for screenshot tests

---

CHANGELOG.md
README.md

@bradlygreen @naomiblack @IgorMinar 
@hansl @kara @robertmesserle 
Will submit this commit upon doing the `npm publish`

chore(): release alpha.0

---

src/core/README.md

docs(): add readme for core

---

.gitignore
src/components/button/button.spec.ts
src/components/checkbox/checkbox.spec.ts
src/components/progress-circle/progress-circle.spec.ts
src/components/sidenav/sidenav.spec.ts
src/components/toolbar/toolbar.spec.ts
src/core/portal/portal.spec.ts
tslint.json

R: @hansl 
Also added `/deploy` to the `.gitignore`

chore: remove ddescribe and iit completely

---

scripts/release/enact-release.sh

build(): add actual publish script.

---

src/components/list/README.md

docs(list): added docs for list

---

src/components/list/list.scss
src/demo-app/list/list-demo.html
src/demo-app/list/list-demo.ts

Quick PR to update demo page with new images and avatar styles.
r: @jelbourn

fix(list): updated demo page

---

ember-cli-build.js
src/core/overlay/overlay-container.ts
src/core/overlay/overlay.scss
src/core/overlay/overlay.ts
src/demo-app/overlay/overlay-demo.ts
src/index.html
src/main.dart
src/main.scss
src/main.ts

feat(overlay): add overlay container & styles

---

scripts/release/enact-release.sh

chore: always npm logout when publish is done.

---

src/components/button/_button-base.scss
src/demo-app/button/button-demo.html

Also add a section for baseline vertical alignment.

fix: vertically align buttons with the surrounding text.

---

src/components/input/README.md
src/components/input/input.html
src/components/input/input.scss
src/components/input/input.ts
src/demo-app/input/input-demo.html
src/demo-app/input/input-demo.scss
src/demo-app/input/input-demo.ts

* Change the CSS to allow for autofill reactions; it works!
* Add a lot of examples and information to the README.md
* Add support for `warn` color to the labels.

feat(MdInput): README.md improvements and autofill support.

---

.travis.yml
package.json
scripts/ci/build-and-test.sh
scripts/ci/forbidden-identifiers.js
scripts/ci/sources/mode.sh

* Move the lint and forbidden-keywords check to a required travis matrix dimension. When those fail, the tests will still be run.
* Only install Dart SDK on tests that require Dart.

chore: strengthen and improve forbidden-keywords.

---

e2e/components/button/button.e2e.js
src/demo-app/button/button-demo.html
src/demo-app/button/button-demo.scss
src/demo-app/button/button-demo.ts

test(button): add e2e test for button

---

src/core/overlay/overlay-state.ts
src/core/overlay/overlay.scss
src/core/overlay/overlay.spec.ts
src/core/overlay/overlay.ts
src/core/overlay/position/global-position-strategy.spec.ts
src/core/overlay/position/global-position-strategy.ts
src/core/overlay/position/position-strategy.ts
src/core/overlay/position/relative-position-strategy.ts
src/demo-app/overlay/overlay-demo.html
src/demo-app/overlay/overlay-demo.scss
src/demo-app/overlay/overlay-demo.ts

R: @hansl @robertmesserle @kara 
After much API discussion, this is what I went with. It's probable that this global strategy gets refactored once we actually start using it to build components and find it lacking.

feat(overlay): add global position strategy

---

package.json
src/index.html

R: @hansl 
Fixes the demo site in IE11

fix(demo): add missing polyfill and up ng version

---

README.md

This PR adds an NPM Version Number to the readme.

add correct npm version badge

---

firebase.json

chore: add url rewrite for routing on firebase

---

src/components/progress-circle/progress-circle.html
src/components/progress-circle/progress-circle.scss

fix: md-progress-circle rendering on firefox and internet explorer

---

package.json

r: @jelbourn 
- Angular update is necessary to enable my gestures PR
- Zones update is required by newest version of Angular
- Broccoli-merge-trees should be in package.json (or fresh npm installs will break).

chore(deps): update angular2 and zones versions

---

src/components/button/button.ts

chore(button): change selector :not(a) to button

---

src/components/list/list.scss
src/components/list/list.ts
src/core/style/_palette.scss
src/demo-app/demo-app.html
src/demo-app/demo-app.scss
src/demo-app/demo-app.ts
src/demo-app/list/list-demo.html
src/demo-app/list/list-demo.scss
src/demo-app/list/list-demo.ts

Basic PR for nav list styles.
Still TODO:
- Discuss approach for shared focus strategy and add
- Add sugared syntax for basic nav lists

feat(list): add nav list styles

---

src/demo-app/demo-app.html
src/demo-app/demo-app.scss
src/demo-app/demo-app.ts
src/index.html

chore(demos): add home route content and fix styles

---

src/demo-app/demo-app.html
src/demo-app/list/list-demo.html
src/demo-app/list/list-demo.scss

r: @jelbourn 
In this PR:
- Fixed list demo styles for mobile
- Alphabetized components in sidenav to make it easier to find them

chore(demos): update list styles for mobile

---

src/components/list/README.md

docs(list): add nav list docs

---

CHANGELOG.md
package.json
scripts/release/changelog.js
src/components/button/package.json
src/components/card/package.json
src/components/checkbox/package.json
src/components/input/package.json
src/components/list/package.json
src/components/progress-bar/package.json
src/components/progress-circle/package.json
src/components/radio/package.json
src/components/sidenav/package.json
src/components/toolbar/package.json
src/core/package.json

chore: update version to alpha.3 w/ changelog

---

src/components/grid-list/grid-list.html
src/components/grid-list/grid-list.ts
src/components/grid-list/package.json
src/demo-app/demo-app.html
src/demo-app/demo-app.ts
src/demo-app/grid-list/grid-list-demo.html
src/demo-app/grid-list/grid-list-demo.ts

This PR contains just a basic scaffold for grid list: placeholder component class, Sass, and HTML files, as well as the grid-list demo component.  Actual implementation coming in a separate PR.

feat(grid-list): basic scaffold for grid list

---

src/demo-app/demo-app.html
src/demo-app/demo-app.scss

r: @jelbourn 
Small PR to fix the sidenav styles in the demo.

chore(demos): fix sidenav styles

---

src/components/list/list-item.html
src/components/list/list.scss
src/demo-app/list/list-demo.html
src/demo-app/list/list-demo.scss
src/demo-app/list/list-demo.ts

r: @jelbourn
Avatars and icons need slightly different styling (icons need to be smaller). This PR adds support for default styling for icons.

feat(list): add icon support

---

src/components/button/_button-base.scss
src/demo-app/button/button-demo.scss
src/demo-app/demo-app.scss

fix(button): cleaned up button theming

---

src/components/icon/package.json

chore(icon): add package.json

---

src/components/sidenav/sidenav.scss

fix(sidenav): add min width for empty navs

---

src/index.html

chore(demo): update to hammer on google cdn

---

src/components/sidenav/sidenav.scss

fix(sidenav): add scrolling style to enable iOS momentum scroll

---

src/components/grid-list/grid-list-errors.ts
src/components/icon/icon-registry.ts
src/components/icon/icon.ts
src/components/input/input.ts
src/components/sidenav/sidenav.ts
src/core/errors/error.ts
src/core/portal/portal-errors.ts
src/core/portal/portal.ts

fix(errors): ensure error message is set

---

src/components/input/input.html
src/components/input/input.ts

Added focus() function to the component.
Clicking anywhere on the host it will focus the input.

feat(input): add focus function on host element

---

src/components/radio/radio.ts

fix(radio): remove event global to work in node

---

src/demo-app/demo-app.html
src/demo-app/demo-app.scss

fix(demo-app) icon inside a button in the toolbar

---

src/components/button/button.ts

r: @jelbourn 
This unused arg is causing the offline template compiler to complain.

fix(button): remove unused arg

---

src/components/input/input.html
src/components/input/input.spec.ts
src/components/input/input.ts

fix(input): adds blur and focus event support

---

src/components/sidenav/sidenav-transitions.scss

R: @jelbourn @hansl 
closes #404

fix(sidenav): removes margin transitions

---

src/components/input/input.html
src/components/input/input.spec.ts
src/components/input/input.ts

R: @jelbourn @hansl 
closes #446

fix(input): adds support for name property for input element

---

src/components/input/input.ts
src/demo-app/input/input-demo.html

fix(input): inputs now work in IE11

---

scripts/ci/build-and-test.sh

chore: fix e2e tests to use e2e app.

---

.github/ISSUE_TEMPLATE.md

R: @kara @robertmesserle 
Our current issue template is somewhat noisy, and I think this discourages people from actually following it. I want to try this simpler template and see if it has an affect on people using it.

chore: simplify issue template

---

src/components/grid-list/grid-list.ts
src/components/grid-list/tile-styler.ts

fix(grid-list): make dir optional

---

src/components/tab-group/README.md

update(tabs): adds README file for tabs

---

package.json
test/protractor.conf.js

protractor-accessibility-plugin for audit on CI

---

angular-cli-build.js

fix: include scss sources in packages

---

package.json
src/components/button/package.json
src/components/card/package.json
src/components/checkbox/package.json
src/components/grid-list/package.json
src/components/icon/package.json
src/components/input/package.json
src/components/list/list.ts
src/components/list/package.json
src/components/progress-bar/package.json
src/components/progress-circle/package.json
src/components/radio/package.json
src/components/sidenav/package.json
src/components/slide-toggle/package.json
src/components/tabs/package.json
src/components/toolbar/package.json
src/core/core.ts
src/core/package.json

R: @kara 
Intentionally no changelog here; that will come once we do a full alpha.6

chore: bump version to alpha.5-2 w/ md-line fix

---

src/components/tabs/tab-group.scss

fix(tabs): removes minimum height

---

src/components/tabs/tabs.ts

refactor(tabs): simplifies line from previous PR

---

src/components/checkbox/checkbox.ts
src/components/radio/radio.html
src/components/radio/radio.scss
src/components/radio/radio.spec.ts
src/components/radio/radio.ts
src/demo-app/baseline/baseline-demo.html
src/demo-app/baseline/baseline-demo.scss
src/demo-app/baseline/baseline-demo.ts
src/demo-app/demo-app/demo-app.html
src/demo-app/demo-app/demo-app.ts
src/demo-app/radio/radio-demo.html
src/demo-app/radio/radio-demo.ts

Fix the `ngModel` on the checkbox as well.
Fixes #357, #638.

fix(radio): fix the baseline of radio buttons

---

src/core/overlay/overlay.scss

fix(overlay): add a z-index.

---

src/components/card/card.scss
src/components/list/list.scss

fix(theme): fix card and list colors for dark themes

---

angular-cli-build.js
src/demo-app/system-config.ts
src/demo-app/tsconfig.json
src/e2e-app/system-config.ts

Fixes #541, I think.
Need to chat to @jelbourn to try to see if that fixes the release itself, not jsut local.

build: add root to the sourcemap so it won't use absolute pathing

---

src/components/toolbar/toolbar.scss
src/components/toolbar/toolbar.ts

* Disables the view encapsulation for the toolbar component.
To be consistent with other components and simplify custom styling.
Fixes #676.

fix(toolbar): disable view encapsulation.

---

GETTING_STARTED.md

R: @kara 
The shell expansion has confused a few people.

docs: don't use shell expansion in Getting Started example

---

CHANGELOG.md
package.json
src/components/button/package.json
src/components/card/package.json
src/components/checkbox/package.json
src/components/grid-list/package.json
src/components/icon/package.json
src/components/input/package.json
src/components/list/package.json
src/components/progress-bar/package.json
src/components/progress-circle/package.json
src/components/radio/package.json
src/components/sidenav/package.json
src/components/slide-toggle/package.json
src/components/tabs/package.json
src/components/toolbar/package.json
src/core/core.ts
src/core/package.json

chore: release alpha.6

---

src/components/menu/menu.spec.ts
src/demo-app/menu/menu-demo.ts

chore(menu): remove unused imports

---

package.json
scripts/release/enact-release.sh
scripts/release/stage-release.sh
src/components/button/package.json
src/components/card/package.json
src/components/checkbox/package.json
src/components/grid-list/package.json
src/components/icon/package.json
src/components/input/package.json
src/components/list/package.json
src/components/menu/package.json
src/components/progress-bar/package.json
src/components/progress-circle/package.json
src/components/radio/package.json
src/components/sidenav/package.json
src/components/slide-toggle/package.json
src/components/tabs/package.json
src/components/toolbar/package.json
src/core/package.json
src/demo-app/tsconfig.json

R: @hansl 
Some of the things I've done with bash here are... questionable. Let me know if you have ideas on how to improve it. I'm going to do a publish under the `next` label so that Misko can install and test.

chore: include .metadata.json files in packages for deployment

---

src/components/menu/README.md

Typo in import statement

---

src/components/button-toggle/README.md
src/components/button-toggle/package.json
src/components/slider/README.md
src/components/slider/package.json

Add README.md and package.json for slider.
R: @jelbourn @kara

Add README.md and package.json to Slider

---

src/components/button/button.ts

Type is becoming Type<?> in https://github.com/angular/angular/pull/10616

fix(button): Avoid breakage by angular change

---

src/components/menu/menu.spec.ts

chore(menu): remove TestComponentBuilder

---

src/components/list/list.spec.ts

chore(list): remove TestComponentBuilder

---

src/components/toolbar/toolbar.spec.ts

chore(toolbar): remove TestComponentBuilder

---

src/components/tooltip/tooltip.spec.ts

chore(tooltip): remove TestComponentBuilder

---

src/components/slider/slider.spec.ts

R: @kara 
CC: @iveysaur :smile:

chore(slider): remove TestComponentBuilder

---

src/components/progress-circle/progress-circle.spec.ts

chore(progress-circle): remove TestComponentBuilder

---

src/components/tabs/tab-group.spec.ts

chore(tabs): remove TestComponentBuilder

---

package.json
src/components/button-toggle/package.json
src/components/button/package.json
src/components/card/package.json
src/components/checkbox/package.json
src/components/grid-list/package.json
src/components/icon/package.json
src/components/input/package.json
src/components/list/package.json
src/components/menu/package.json
src/components/progress-bar/package.json
src/components/progress-circle/package.json
src/components/radio/package.json
src/components/sidenav/package.json
src/components/slide-toggle/package.json
src/components/slider/package.json
src/components/tabs/package.json
src/components/toolbar/package.json
src/components/tooltip/package.json
src/core/package.json

R: @hansl or @kara 
For the future: do either of you care if we skip the review process on version bumps like this?

chore: bump version to alpha.7-3

---

src/components/card/card.html
src/components/card/card.scss
src/demo-app/card/card-demo.html

fix(card): remove unnecessary intermediate div

---

src/lib/button-toggle/button-toggle.ts
src/lib/button/button.ts
src/lib/card/card.ts
src/lib/checkbox/checkbox.ts
src/lib/dialog/dialog-container.ts
src/lib/grid-list/grid-list.ts
src/lib/grid-list/grid-tile.ts
src/lib/icon/icon.ts
src/lib/input/input.ts
src/lib/list/list.ts
src/lib/menu/menu-directive.ts
src/lib/module.d.ts
src/lib/progress-bar/progress-bar.ts
src/lib/progress-circle/progress-circle.ts
src/lib/radio/radio.ts
src/lib/sidenav/sidenav.ts
src/lib/slide-toggle/slide-toggle.ts
src/lib/slider/slider.ts
src/lib/tabs/tabs.ts
src/lib/toolbar/toolbar.ts
src/lib/tooltip/tooltip.ts

R: @hansl 
Needed by Google's internal build tools for the near term.

chore: re-add moduleId temporarily

---

src/demo-app/demo-app-module.ts
src/demo-app/demo-app/routes.ts
src/e2e-app/e2e-app-module.ts
src/e2e-app/e2e-app/routes.ts

chore: remove deprecated router api use

---

src/lib/checkbox/checkbox.ts

Add export statement to ensure correct d.ts

fix(checkbox): export TransitionCheckState enum

---

package.json
src/lib/button-toggle/package.json
src/lib/button/package.json
src/lib/card/package.json
src/lib/checkbox/package.json
src/lib/core/package.json
src/lib/grid-list/package.json
src/lib/icon/package.json
src/lib/input/package.json
src/lib/list/package.json
src/lib/menu/package.json
src/lib/progress-bar/package.json
src/lib/progress-circle/package.json
src/lib/radio/package.json
src/lib/sidenav/package.json
src/lib/slide-toggle/package.json
src/lib/slider/package.json
src/lib/tabs/package.json
src/lib/toolbar/package.json
src/lib/tooltip/package.json

chore(release): version bump for packaging fix

---

src/lib/core/overlay/position/connected-position-strategy.ts
src/lib/core/overlay/position/global-position-strategy.ts

fix(core): fix cyclic dependency

---

src/lib/input/README.md

fixed minor spelling error to clear up possible translation issues

Update spelling REAME

---

CHANGELOG.md

Add missing comma to to imports.

docs(CHANGELOG): Add missing comma to imports example

---

CHANGELOG.md

docs: mention index.js changes in changelog

---

src/lib/core/overlay/position/global-position-strategy.ts

fix typos in comments in GlobalPositionStrategy

---

GETTING_STARTED.md

Updated to the latest and greatest with that webpack goodness.

chore(docs): Update getting started for webpack CLI

---

package.json
src/lib/button-toggle/package.json
src/lib/button/package.json
src/lib/card/package.json
src/lib/checkbox/package.json
src/lib/core/package.json
src/lib/grid-list/package.json
src/lib/icon/package.json
src/lib/input/package.json
src/lib/list/package.json
src/lib/menu/package.json
src/lib/progress-bar/package.json
src/lib/progress-circle/package.json
src/lib/radio/package.json
src/lib/sidenav/package.json
src/lib/slide-toggle/package.json
src/lib/slider/package.json
src/lib/tabs/package.json
src/lib/toolbar/package.json
src/lib/tooltip/package.json

I've already published this, just adding the changes back to master now.

chore: bump to alpha.8-2 and all deps to ^2.0.0

---

src/lib/grid-list/README.md
src/lib/list/README.md

chore: fix typos in list/grid-list readmes

---

src/lib/core/core.ts
src/lib/dialog/dialog.ts
src/lib/module.ts

fix(aot): fix aot error w/ live announcer

---

package.json
src/lib/dialog/index.ts
src/lib/package.json
src/lib/snack-bar/index.ts

Workaround for https://github.com/angular/angular/issues/11889

fix(aot): export dialog/snackbar containers through index

---

src/lib/button-toggle/button-toggle.scss
src/lib/button/_button-base.scss

fix(button): Changed button corner radius from 3px to 2px

---

package.json

Updates the `engines` section in the `package.json` to match the one from Angular.
Fixes #1502.

chore(): update `engines` to match angular

---

src/demo-app/demo-app/demo-app.html
src/demo-app/demo-app/demo-app.ts

Use ngFor to loop through nav items on the sidenav. Add click event handler for each item to close the sidenav.
Note: did not add click handler to md-nav-list so that clicking the `<hr>` element is no-op

chore: close sidenav on nav item click

---

src/lib/button-toggle/button-toggle.ts

fix(button-toggle): add exportAs

---

src/lib/sidenav/README.md

docs(sidenav): add buttons to open start/end sidenavs on example

---

src/lib/button/button.spec.ts
src/lib/radio/README.md
src/lib/radio/_radio-theme.scss
src/lib/radio/radio.html
src/lib/radio/radio.scss
src/lib/radio/radio.spec.ts
src/lib/radio/radio.ts

Removed the placeholder ripple effect and added the real md-ripple.
R: jelbourn

feature(radio): Add ripple effect for radio buttons

---

package.json

chore: add gulp-cli as dev dep

---

scripts/sauce/sauce_connect_setup.sh

chore: update sauce connect binary to latest version

---

package.json

chore: update @angular/compiler-cli version

---

firebase.json

R: @kara or @andrewseguin or @tinayuangao

chore: fix firebase dev instance

---

src/demo-app/slider/slider-demo.html
src/demo-app/slider/slider-demo.ts
src/lib/slider/slider.spec.ts
src/lib/slider/slider.ts

Fix(slider): Update slider position when value binding changes.

---

src/lib/core/a11y/list-key-manager.spec.ts
src/lib/core/a11y/list-key-manager.ts

chore(a11y): make disabled property optional

---

src/lib/slider/slider.spec.ts
src/lib/slider/slider.ts

fix(slider): clamp thumb between min and max

---

src/lib/radio/radio.ts

fix(radio): only fire group change if there is a group

---

src/lib/core/overlay/_overlay.scss
stylelint-config.json

fix(overlay): ensure container covers entire screen

---

src/lib/tabs/tabs.ts

fix(tabs): make @Output not private

---

src/lib/tabs/tab-group.spec.ts

chore: add test for @ViewChild in tab content

---

src/lib/button-toggle/button-toggle.scss

fix(button-toggle): Disable user-select in button-toggle

---

src/lib/toolbar/toolbar.ts

* Moves two separated imports to one single import statement.

chore(toolbar): combine imports from same file

---

src/lib/checkbox/checkbox.scss

fix(checkbox): Fix checkbox is not vertically aligned when there's no text

---

src/lib/input/input.scss

- Fix webkit autofill would float placeholder even with
floatingPlaceholder disabled.
Closes #1694

Fix(input): webkit autofill & floating placeholder

---

src/lib/button/button.spec.ts
src/lib/button/button.ts

chore(button): use disabled property, not attr

---

src/lib/button-toggle/README.md
src/lib/button-toggle/button-toggle.ts

fix(button-toggle): Provide better docs for `ngModel` in wq`button-toggle-group multiple`

---

.travis.yml

chore: update travis nodejs version

---

docs/theming-your-components.md
docs/theming.md

This updates the path of the theme files used in the examples provided in the documentation.

docs: update path in theme docs

---

e2e/components/dialog/dialog.e2e.ts
src/e2e-app/dialog/dialog-e2e.html
src/e2e-app/dialog/dialog-e2e.ts
src/e2e-app/e2e-app-module.ts
src/e2e-app/e2e-app/e2e-app.html
src/e2e-app/e2e-app/routes.ts

Adds e2e tests for the dialog component.
Fixes #1642.

test(dialog): add e2e tests

---

e2e/components/list/list.e2e.ts
src/e2e-app/e2e-app-module.ts
src/e2e-app/e2e-app/e2e-app.html
src/e2e-app/e2e-app/routes.ts
src/e2e-app/list/list-e2e.html
src/e2e-app/list/list-e2e.ts

Adds basic sanity check e2e tests for the list component.
Fixes #547.

test(list): add basic e2e tests

---

src/lib/slider/slider.ts

fix(slider): emit change event after updating value accessor

---

src/lib/button/README.md

In the screenshot, it doesn't contain favorite button.

docs(button): match code sample with image

---

src/demo-app/select/select-demo.html
src/lib/select/select.scss

This PR fixes the trigger positioning issues in IE and Firefox.
r: @jelbourn

fix(select): fix style for ie and firefox

---

README.md

chore: update status on readme

---

DEV_ENVIRONMENT.md

docs(DEV_ENVIRONMENT): remove redundant dot

---

README.md

chore: update readme status for December

---

src/lib/sidenav/sidenav.ts

chore(sidenav): add providers to sidenav forRoot

---

README.md

addresses https://github.com/angular/material2/issues/2113

chore: update layout/textarea status in readme

---

scripts/release/publish-build-artifacts.sh

* Exit process if pipeline fails or any line fails.
* Fixes authentication for Git

chore(artifacts): properly authenticate git.

---

e2e/components/slide-toggle/slide-toggle.e2e.ts
src/e2e-app/e2e-app-module.ts
src/e2e-app/e2e-app/e2e-app.html
src/e2e-app/e2e-app/routes.ts
src/e2e-app/slide-toggle/slide-toggle-e2e.html
src/e2e-app/slide-toggle/slide-toggle-e2e.ts

* Adds some basic e2e tests for the md-slide-toggle component.
Closes #1963.

chore: add e2e tests for md-slide-toggle

---

src/demo-app/portal/portal-demo.html

Very mission critical stuff here :yum:

Fixed typo in portal-demo.html

---

package.json
tools/dgeni/index.js
tools/dgeni/processors/categorizer.js
tools/dgeni/processors/component-grouper.js
tools/dgeni/processors/docs-private-filter.js
tools/dgeni/templates/common.template.html
tools/dgeni/templates/componentGroup.template.html
tools/gulp/tasks/docs.ts

This outputs a basic starting point for the API docs. Most of the information we want is present; following steps will be to tweak this and add styles.

chore(doc): initial version of dgeni setup for api docs

---

package.json

chore: fix incorrect gulp task in pkg scripts

---

LICENSE
tools/gulp/constants.ts

chore: bump year

---

package.json
test/karma.config.ts

* This adds support for sourcemaps in Karma. This can help debugging failing tests when working on unit tests.

chore(karma): add support for sourcemaps

---

CHANGELOG.md

add missing changelog of #2157

chore(CHANGELOG): add changelog for #2157

---

tools/gulp/tasks/clean.ts

build:change gulp clean dist dir

---

src/demo-app/demo-app/demo-app.scss

Removes some horizontal scrolling in the local development app.

chore: avoid horizontal overflow in testing app

---

src/demo-app/demo-app/demo-app.scss
src/demo-app/slider/slider-demo.html
src/demo-app/slider/slider-demo.ts
src/lib/slider/_slider-theme.scss
src/lib/slider/slider.html
src/lib/slider/slider.scss
src/lib/slider/slider.spec.ts
src/lib/slider/slider.ts

part of #2603 making slider look like mocks for all states

fix(slider): make disabled state look like mocks

---

src/lib/select/select.spec.ts
src/lib/select/select.ts

Fixes the select component not highlighting the model value when the options get added after initialization.
Fixes #2497.

fix(select): selected option not being highlighted when options are added asynchronously

---

src/demo-app/input/input-container-demo.html
src/demo-app/input/input-demo.html
src/lib/input/OVERVIEW.md
src/lib/input/README.md
src/lib/input/input-container.html
src/lib/input/input.html

* Renames the md-prefix and md-suffix directives to camelcase.
Closes #2636

fix(input): camel-case md-prefix and md-suffix

---

src/lib/select/select.spec.ts
src/lib/select/select.ts

fix(select): support use inside a custom value accessor

---

src/lib/autocomplete/autocomplete-trigger.ts
src/lib/autocomplete/autocomplete.html
src/lib/autocomplete/autocomplete.spec.ts
src/lib/autocomplete/autocomplete.ts

I don't know how I accidentally closed this. Reopening.

feat(autocomplete): add screenreader support

---

README.md

Added --save to "npm install @angular/material" to save the package to the dependencies list in package.json

Added --save to "npm install @angular/material"

---

src/lib/slide-toggle/slide-toggle.scss
src/lib/slide-toggle/slide-toggle.spec.ts
src/lib/slide-toggle/slide-toggle.ts

* Adds an option to change the position of the slide-toggle's label.
Closes #2820

feat(slide-toggle): add support for labelPosition

---

src/lib/slider/slider.spec.ts
src/lib/slider/slider.ts

also disable animation for keyboard changes because they look crazy.
fixes #2764

fix(slider): fire change event on value change via keyboard.

---

src/demo-app/autocomplete/autocomplete-demo.html
src/demo-app/autocomplete/autocomplete-demo.scss
src/demo-app/autocomplete/autocomplete-demo.ts
src/lib/autocomplete/OVERVIEW.md
src/lib/autocomplete/README.md
src/lib/autocomplete/_autocomplete-theme.scss
src/lib/autocomplete/autocomplete-trigger.ts
src/lib/autocomplete/autocomplete.html
src/lib/autocomplete/autocomplete.scss
src/lib/autocomplete/autocomplete.spec.ts
src/lib/autocomplete/autocomplete.ts
src/lib/autocomplete/index.ts
src/lib/core/a11y/list-key-manager.spec.ts
src/lib/core/a11y/list-key-manager.ts
src/lib/core/option/_option-theme.scss
src/lib/core/option/option.ts
src/lib/core/overlay/position/connected-position-strategy.spec.ts
src/lib/core/overlay/position/connected-position-strategy.ts

This is simply a port to move all the previously-approved PRs from the autocomplete branch to the master branch.

Add autocomplete component

---

src/lib/core/platform/features.ts

input(input): fix chrome 56 warning

---

e2e/components/fullscreen/fullscreen.e2e.ts
e2e/components/menu/menu.e2e.ts
e2e/screenshot.ts
tools/gulp/tasks/lint.ts

* Now runs TSLint also against the e2e/ directory.
* Add comments for the different tasks in the lint file.
* Refactors the screenshot e2e file to pass TSLint and also to be less nested.

build: run tslint against e2e directory

---

src/lib/core/option/_option.scss

fix(option): revert duplicate prop

---

src/lib/button/button.scss

fix(button): Add default color for mat-raised-button

---

src/lib/dialog/dialog.md

docs(dialog): change then to subscribe

---

src/lib/icon/icon-registry.ts
src/lib/icon/icon.ts

related issue --> https://github.com/angular/material2/issues/3130

Fix icon not found

---

src/demo-app/autocomplete/autocomplete-demo.html

Fix: removed un-used "this" from html bindings

chore(autocomplete): removed un-used "this" from html bindings

---

src/lib/tabs/tab-nav-bar/tab-nav-bar.html
src/lib/tabs/tab-nav-bar/tab-nav-bar.scss

Should fix issue where the nav contains link layout styles
Closes #3197

fix(nav): remove flex; bring ink into same parent as links

---

src/lib/input/input-container.scss

fix(input): remove jitter that occurs on focus

---

src/lib/input/input-container.scss

fix(input): fix chrome autofill style

---

src/lib/button-toggle/_button-toggle-theme.scss
src/lib/core/theming/_palette.scss

 fix(button-toggle): Add color for selected button toggle and selected disabled button toggle

---

src/lib/dialog/dialog.md

afterClosed is callable function. 
afterClosed(): Observable<any>;

docs(dialog): Update dialog.md - afterClosed

---

src/lib/slider/slider.html
src/lib/slider/slider.ts

* group @Input and @Outputs at the top
* make stuff internal that should be internal
* add descriptions for MdSliderChange properties

docs(slider): clean up docs

---

src/examples/grid-list-overview/grid-list-overview-example.css
src/examples/grid-list-overview/grid-list-overview-example.html
src/examples/grid-list-overview/grid-list-overview-example.ts

Adding a background color helps clarify what's going on. It also looks a bit large on desktop, so adding a rowHeight ratio.

docs(grid-list): improve basic grid-list example

---

scripts/release/publish-build-artifacts.sh
scripts/release/publish-docs-content.sh

chore: publish docs content under angular org

---

guides/theming.md

docs(theming): add colon

---

src/lib/slider/_slider-theme.scss
src/lib/slider/index.ts
src/lib/slider/slider.html
src/lib/slider/slider.scss
src/lib/slider/slider.spec.ts
src/lib/slider/slider.ts

Differentiate sliders focused via keyboard vs other means

---

src/lib/select/select.scss

Fixes #3112
Closing #3242 due to merge conflicts

bug(md-select): change the arrow position to absolute

---

src/lib/select/select.scss

Reverts angular/material2#3580

Revert "bug(md-select): change the arrow position to absolute"

---

package.json

api script was running the incorrect gulp command.

fix(package.json): Fix failing `npm run api` command

---

README.md

add tree to feature status list

Update README.md - add tree to feature status list

---

src/lib/button/_button-base.scss

bug(button): remove dotted border on firefox

---

scripts/saucelabs/start-tunnel.sh

* Updates the Saucelabs Tunnel connector to the latest version

build: update saucelabs tunnel binary

---

src/lib/select/_select-theme.scss

fix(select): show focus indicator even with validation errors

---

src/lib/input/input-container.ts

partially addresses #3585 
temporary demo: https://mmalerba-demo2.firebaseapp.com/input

fix(input): fix blank aria-describedby

---

src/lib/list/list.scss

fix(list): add font-family style to subheader

---

src/demo-app/slide-toggle/slide-toggle-demo.scss
src/lib/slide-toggle/slide-toggle.scss

* Angular Material components should not have any outer-margin on component host elements (Similar as for the checkbox component)

fix(slide-toggle): remove host element margin

---

guides/theming.md

#3550 
Added the 4 available themes to the theming guide.
Detailed that more updates to come as development continues.

docs(theming-guide): list available themes

---

src/lib/dialog/dialog-config.ts

#3651 
Contribution guidelines are important..
Added a description to the viewContainerRef variable in MdDialogConfig.

docs(dialog-config-ts): MdDialogConfig viewContainerRef

---

package.json

- Previously the build script tried to run an invalid gulp task.

build: fix build script in package.json

---

guides/theming.md

* Repeated reminders to only include mat-core once.
* Note about including a theme file via styleUrls
* Add section for theming only certain components
* Move section on overlay theming after section for multiple themes

docs: clarify points to address common issues

---

src/lib/dialog/dialog-container.ts

* Switches the `translate` to `translate3d` for hardware accelerated animations.

perf(dialog): switch dialog animations to translate3d

---

scripts/closure-compiler/build-devapp-bundle.sh

docs (build-devapp-bundle.sh) : fix typo

---

src/lib/input/autosize.ts

Fixes bug where change detection error occurs on autosize (test failure in Google).

fix(textarea): fix change detection error on autosize

---

src/lib/card/_card-theme.scss
src/lib/list/_list-theme.scss

Fixes [#3936](https://github.com/angular/material2/issues/3936).

fix(card, list): Update MdCard and MdListItem color property to use theme's text color.

---

src/lib/core/option/option.ts

One slice of the Renderer update needed to fix Google test failures.

refactor(option): remove old renderer

---

src/lib/autocomplete/index.ts
src/lib/button-toggle/index.ts
src/lib/button/index.ts
src/lib/card/index.ts
src/lib/checkbox/index.ts
src/lib/core/common-behaviors/common-module.ts
src/lib/core/core.ts
src/lib/core/line/line.ts
src/lib/core/ripple/index.ts
src/lib/dialog/index.ts
src/lib/grid-list/index.ts
src/lib/icon/index.ts
src/lib/list/index.ts
src/lib/menu/index.ts
src/lib/module.ts
src/lib/progress-bar/index.ts
src/lib/progress-spinner/index.ts
src/lib/radio/index.ts
src/lib/select/index.ts
src/lib/sidenav/index.ts
src/lib/slide-toggle/index.ts
src/lib/slider/index.ts
src/lib/snack-bar/index.ts
src/lib/toolbar/index.ts
src/lib/tooltip/index.ts

I will move the run-time sanity checks from CompatibilityModule to here
once #4178 is merged.

chore: add MdCommonModule for all components

---

tools/dgeni/processors/categorizer.js

* Fixes multi-line selectors not being detected properly (https://github.com/angular/material2/blob/master/src/lib/button/button.ts#L185-L185)
* Template strings not being detected properly (https://github.com/angular/material2/blob/master/src/lib/input/input-container.ts#L103-L103)
* No longer repeats RegExp logic multiple times. More generic function.
**Note**: This is still a very naive approach, but it nearly works for every selector now. It only fails for selectors like: https://github.com/angular/material2/blob/master/src/lib/button/button.ts#L93-L93

build: fix multi-line selectors in dgeni

---

src/lib/checkbox/_checkbox-theme.scss
src/lib/chips/_chips-theme.scss
src/lib/core/selection/pseudo-checkbox/_pseudo-checkbox-theme.scss
src/lib/tabs/_tabs-theme.scss

style(checkbox,chips,tabs): remove hardcoded hues

---

src/lib/tabs/_tabs-theme.scss

fixes #4320

---

src/lib/autocomplete/autocomplete.spec.ts
src/lib/core/overlay/overlay.spec.ts
src/lib/core/overlay/position/global-position-strategy.spec.ts
src/lib/core/overlay/scroll/close-scroll-strategy.spec.ts
src/lib/core/overlay/scroll/reposition-scroll-strategy.spec.ts
src/lib/snack-bar/snack-bar.spec.ts
src/lib/tooltip/tooltip.spec.ts

Fixes some unit tests that were leaking elements into other tests.

chore: random test leaks

---

src/lib/autocomplete/autocomplete.md

docs(autocomplete): fix regex filter search

---

src/lib/core/core.ts
src/lib/core/overlay/index.ts

* Exposes the interface that allows developers to build custom position
strategies for overlays.

feat(overlay): expose interface for custom positions

---

src/lib/core/platform/platform.ts

* Fixes typos in comments of the `Platform` service.

chore(platform): fix typos in comments

---

.github/ISSUE_TEMPLATE.md
CHANGELOG.md

chore(changelog): add missing note about TS 2.2

---

tools/gulp/tasks/publish.ts

* Adds the CDK to the `publish` task. This allows us to release Material and the CDK together.
* Adds some colors to the messages because you can easily oversee the info messages.
@jelbourn I thought about adding a way to only publish a single package (e.g just the CDK) but since I don't want to have hard-coded tasks I looked for a way run gulp tasks dynamically. Unfortunately there is no easy way to run tasks dynamically.

build: release cdk in publish task

---

scripts/release/publish-build-artifacts.sh

* Publish the CDK release output to the cdk-builds repository.
**Note**: Review using the diff that ignores whitespace changes: [Here](https://github.com/angular/material2/pull/4527/files?w=1)

build: publish to cdk-builds

---

src/demo-app/radio/radio-demo.scss
src/lib/checkbox/_checkbox-theme.scss
src/lib/radio/_radio-theme.scss

fix(radio, checkbox): Make disabled radio and disabled checkbox label color disabled

---

src/lib/input/_input-theme.scss
src/lib/input/input-container.scss

also add underline ripple effect from the mocks
demo: https://mmalerba-demo1.firebaseapp.com/input
fixes #3490

make input underline thick when in error state.

---

src/lib/datepicker/datepicker-toggle.scss

Related to https://github.com/angular/material2/pull/4542
@crisbeto @mmalerba

fix(datepicker): don't use pointer cursor on toggle when disabled

---

src/lib/core/platform/platform.ts

fix(universal): gate platform checks on being on browser

---

src/demo-app/button/button-demo.html
src/demo-app/button/button-demo.ts
src/lib/button/button.html
src/lib/button/button.spec.ts

fix(button): complete ripple when button becomes disabled

---

src/lib/datepicker/_datepicker-theme.scss
src/lib/datepicker/datepicker-content.scss

cleanup(datepicker): move pane styles from calendar to datepicker-content

---

src/lib/menu/menu-directive.ts
src/lib/menu/menu.html
src/lib/menu/menu.spec.ts

fix(menu): close menu panel on escape

---

src/lib/datepicker/calendar.html
src/lib/datepicker/calendar.spec.ts
src/lib/datepicker/calendar.ts

fix(datepicker): make datepicker work in compatibility mode

---

tools/gulp/tasks/coverage.ts
tools/gulp/tasks/payload.ts
tools/gulp/tasks/screenshots.ts
tools/gulp/util/firebase.ts

* Properly close the Firebase app connections to avoid that the NodeJS process keeps hanging.
**Note**: This should fix that the CI times out.

build: properly close firebase apps

---

guides/theming.md

Adding a period at the end of one of the notes sentences.

Punctuation fix/addition

---

src/lib/checkbox/checkbox.html
src/lib/checkbox/checkbox.scss
src/lib/radio/radio.html

fix(checkbox, radio): Fix checkbox label not read in JAWS

---

src/e2e-app/environment.ts

#* Removes the unused environment file from the old build process with the Angular CLI

chore: remove unused environment file

---

.travis.yml

* Removes the Travis workaround from https://github.com/travis-ci/travis-ci/issues/4681#issuecomment-304919767 since it has been fixed officially.

build: remove travis workaround

---

src/lib/datepicker/calendar.scss

Fixes the calendar arrows pointing in the wrong direction in RTL.

fix(datepicker): invert calendar arrow direction in rtl

---

src/lib/autocomplete/autocomplete-trigger.ts

https://github.com/angular/material2/issues/4866
any tests needed?
@jelbourn

feat(autocomplete): extend selector to match textarea

---

src/lib/dialog/dialog-config.ts
src/lib/dialog/dialog.spec.ts
src/lib/dialog/dialog.ts

Allows users to set the layout direction of a dialog.

feat(dialog): allow setting the layout direction

---

src/demo-app/style/style-demo.html
src/lib/checkbox/checkbox.ts
src/lib/core/style/focus-origin-monitor.spec.ts
src/lib/core/style/focus-origin-monitor.ts
src/lib/radio/radio.ts
src/lib/slide-toggle/slide-toggle.ts

focusVia 2nd parameter is unused

chore(focus-origin-monitor): remove unused method parameter

---

src/lib/core/core.ts
src/lib/core/placeholder/placeholder-options.ts
src/lib/input/input-container.spec.ts
src/lib/input/input-container.ts
src/lib/input/input.md
src/lib/select/select.md
src/lib/select/select.spec.ts
src/lib/select/select.ts

* Implement global placeholder options so the
default float option can be set to something
other than 'auto'
Fixes #4311

feat(placeholder): add global placeholder options

---

src/lib/checkbox/checkbox.spec.ts

* Removes an unused variable from a checkbox test component.

chore(checkbox): remove unused test variable

---

tools/dashboard/functions/jwt/verify-token.ts
tools/dashboard/functions/package.json
tools/dashboard/functions/tsconfig.json

* Fixes a TypeScript error in the dashboard functions.

build: fix dashboard typescript error

---

src/lib/dialog/dialog-container.ts
src/lib/dialog/dialog-ref.ts
src/lib/dialog/dialog.ts

chore(dialog): rename config to avoid name collisions

---

tools/dashboard/.angular-cli.json
tools/dashboard/package.json
tools/dashboard/src/app/dashboard-app.html
tools/dashboard/src/app/dashboard-app.ts
tools/dashboard/src/app/dashboard-module.ts
tools/dashboard/src/app/data-definitions.ts
tools/dashboard/src/environments/environment.prod.ts
tools/dashboard/src/environments/environment.ts
tools/dashboard/src/environments/firebase.ts
tools/dashboard/src/styles.css
tools/dashboard/src/theme.scss

* As part of the initial dashboard setup, this installs Angular Fire and Angular Material in the dashboard.
* For testing purposes the list of all payload results will be printed right now.
EDIT: Maybe this is rather a `chore` instead of a `build change`. But should be fine though..

build: firebase integration for dashboard

---

src/lib/tabs/tab-group.ts

Fixes https://github.com/angular/material2/issues/5274

docs(tabs): Fix missing api description

---

tools/dashboard/package.json
tools/dashboard/src/app/dashboard-app.css
tools/dashboard/src/app/dashboard-app.html
tools/dashboard/src/app/dashboard-module.ts
tools/dashboard/src/app/data-definitions.ts
tools/dashboard/src/app/payload-chart/ngx-definitions.ts
tools/dashboard/src/app/payload-chart/payload-chart.html
tools/dashboard/src/app/payload-chart/payload-chart.ts
tools/dashboard/src/styles.css

* Adds the initial chart for the payloads inside of the dashboard.
There are still things missing. Currently the chart is filled with a lot of data and therefore it doesn't feel very smooth etc.

chore: initial chart for dashboard

---

src/demo-app/input/input-demo.html

demo(input): align input with text in input demo

---

CHANGELOG.md
package.json
src/cdk/package.json
src/lib/package.json

cc @DevVersion the version script didn't update the CDK versions where necessary so I temporarily hard-coded them

chore: bump version to beta.8 w/ changelog

---

test/karma.conf.js

* Randomizes the order of test execution inside of Jasmine / Karma.

build: randomize execution order of tests

---

src/lib/slider/slider.spec.ts
src/lib/slider/slider.ts

fix(slider): emit events for home and end keys when appropriate.

---

src/lib/grid-list/grid-list.ts
src/lib/grid-list/grid-tile.ts

Switches the grid list component to OnPush change detection.
Relates to #5035.

chore(grid-list): switch to OnPush change detection

---

tools/dashboard/functions/payload-github-status.ts

* Fixes the dashboard deployment to Firebase. Currently the deployment is being cancelled because the functions are having compilation errors (due to TypeScript definition updates of `express`)

build: fix dashboard deployment

---

scripts/deploy/deploy-screenshot-functions.sh
tools/gulp/util/firebase.ts

Forked from #5060 since I needed to make a small change and @DevVersion is travelling
(changed to use the existing screenshot firebase key)

build: fix deploying of screenshot functions

---

src/lib/paginator/index.ts

fix(paginator): expose MdPaginatorIntl

---

README.md

People kept sending PRs to remove the empty line, so I made it a real line.

chore: add separator line in readme

---

src/lib/tabs/tab-nav-bar/tab-nav-bar.ts

Fixes the issue [#215](https://github.com/angular/material.angular.io/issues/215) from `material.angular.io`.

fix(tab-nav-bar): check if the subscription is defined

---

src/lib/datepicker/datepicker-content.scss

fix(datepicker): make height of calendar constant in non-touch mode

---

src/lib/button-toggle/button-toggle.ts

* Switches the button toggle component to OnPush change detection.
* Fixes an issue where some toggles wouldn't be unselected when moving between toggles.
* Relates to #5035.

chore(button-toggle): switch to OnPush change detection

---

src/material-examples/cdk-table-basic/cdk-table-basic-example.css
src/material-examples/table-basic/table-basic-example.css
src/material-examples/table-filtering/table-filtering-example.css
src/material-examples/table-overview/table-overview-example.css
src/material-examples/table-pagination/table-pagination-example.css
src/material-examples/table-sorting/table-sorting-example.css

docs(table): fix ie overflow issue

---

tools/gulp/tasks/screenshots.ts

* Fixes that the screenshot goldens are not uploaded properly in push builds.

build: fix golden upload in push builds

---

src/material-examples/input-errors/input-errors-example.css
src/material-examples/input-form/input-form-example.css
src/material-examples/input-hint/input-hint-example.css
src/material-examples/input-prefix-suffix/input-prefix-suffix-example.css

- This fixes an issue where, on small screens, the form would extend beyond the bounds of the containing card
See here:

docs(demos): bound input example form width

---

tools/screenshot-test/src/index.html

fix(screenshot): add lang attribute to html element

---

src/lib/expansion/expansion-panel-header.scss
src/lib/expansion/expansion-panel.scss

* Fixes some margins not being inverted in RTL.
* Simplifies a couple of declarations.

fix(expansion-panel): wrong margins in rtl

---

src/demo-app/datepicker/datepicker-demo.ts
src/lib/datepicker/datepicker.ts

fix(datepicker): use correct viewContainerRef for dialog.

---

src/material-examples/checkbox-configurable/checkbox-configurable-example.html

upper part is updated
Closes #4391

docs(checkbox): Update the checkbox example so when user make checkbox checked, the

---

scripts/saucelabs/start-tunnel.sh

* Updates the saucelabs connector to the latest version

build: update saucelabs connector

---

src/lib/button-toggle/button-toggle.spec.ts
src/lib/button-toggle/button-toggle.ts

fix(button-toggle): remove emit change event when value changes

---

src/lib/input/input-container.scss

fix(input): set default width of 200px on input-container

---

src/demo-app/a11y/a11y-module.ts
src/demo-app/a11y/a11y.ts
src/demo-app/a11y/button-toggle/button-toggle-a11y.html
src/demo-app/a11y/button-toggle/button-toggle-a11y.ts
src/demo-app/a11y/routes.ts
src/lib/button-toggle/button-toggle.ts

Added default `role=group` for button toggle group with multi-selection

a11y(button-toggle): Add accessibility demo page for button toggle

---

src/universal-app/kitchen-sink/kitchen-sink.html
src/universal-app/kitchen-sink/kitchen-sink.ts

* Adds the expansion panel to the universal app that will be validated on the CI.

chore: add expansion panel to prerender check

---

src/lib/datepicker/datepicker-input.ts
src/lib/datepicker/datepicker.spec.ts

fix(datepicker): mark input tocuhed on calendar date selected

---

src/material-examples/table-basic/table-basic-example.html
src/material-examples/table-filtering/table-filtering-example.html
src/material-examples/table-http/table-http-example.html
src/material-examples/table-overview/table-overview-example.html
src/material-examples/table-pagination/table-pagination-example.html
src/material-examples/table-sorting/table-sorting-example.html

docs(table): switch to md- prefix

---

src/demo-app/ripple/ripple-demo.scss
src/lib/autocomplete/autocomplete.scss
src/lib/button/button.scss
src/lib/checkbox/checkbox.scss
src/lib/input/_input-theme.scss
src/lib/progress-bar/progress-bar.scss
src/lib/sidenav/sidenav.scss
src/lib/slide-toggle/_slide-toggle-theme.scss
src/lib/slider/slider.scss
stylelint-config.json

Enforces a 100-character line length in the SCSS files for consistency with the TS.

build: enforce line length in scss files

---

src/demo-app/a11y/a11y-module.ts
src/demo-app/a11y/a11y.ts
src/demo-app/a11y/autocomplete/autocomplete-a11y.html
src/demo-app/a11y/autocomplete/autocomplete-a11y.ts
src/demo-app/a11y/routes.ts

Adds a demo page for testing the autocomplete accessibility.

a11y: add autocomplete accessibility demo

---

src/lib/input/input-container.spec.ts
src/lib/input/input-container.ts

fix(input): update aria-describedby to also include errors

---

src/lib/slider/slider.spec.ts
src/lib/slider/slider.ts

fix(slider): fix change & input emit logic.

---

src/universal-app/kitchen-sink/kitchen-sink.html
src/universal-app/kitchen-sink/kitchen-sink.ts

* Adds the CDK table to the universal app. This ensures that CDK tables can be rendered inside of platform-server.

chore: add cdk table to universal app

---

e2e/components/toolbar-e2e.spec.ts
src/e2e-app/e2e-app/routes.ts
src/material-examples/public_api.ts

* Adds the toolbar demo to the e2e app and adds a screenshot diff for it.

test(): screenshot diff for toolbar

---

e2e/components/dialog-e2e.spec.ts

* Creates a screenshot for a simple opened dialog

test(): screenshot diff for opened dialog

---

tools/package-tools/version-placeholders.ts

For the version placeholde replacement a Grep statement is used as well. For Windows environments there is an alternative called `Findstr` which can be used to avoid having a dependency on ported Unix-tools.
References https://github.com/angular/material2/issues/6211

build: version placeholder replacement grep alternative

---

src/lib/radio/radio.spec.ts
src/lib/radio/radio.ts

fix(radio): forward focus to native input

---

src/cdk/observers/observe-content.ts

* Runs the underlying `MutationObserver` outside the Angular zone.
* Runs the debounce timeout outside the Angular zone.
via https://github.com/angular/flex-layout/pull/370.

perf(observe-content): run outside Angular zone

---

src/demo-app/a11y/a11y-module.ts
src/demo-app/a11y/a11y.ts
src/demo-app/a11y/menu/menu-a11y.html
src/demo-app/a11y/menu/menu-a11y.scss
src/demo-app/a11y/menu/menu-a11y.ts
src/demo-app/a11y/routes.ts

@mmalerba - This is the same PR as #6153 just cleaned to latest in a single commit.

a11y(menu): menu tests 

---

src/material-examples/chips-overview/chips-overview-example.ts

docs(ChipsOverview): Added stylesUrls to reference css.

---

src/material-moment-adapter/index.spec.ts
src/material-moment-adapter/index.ts
src/material-moment-adapter/package.json
src/material-moment-adapter/public_api.ts
src/material-moment-adapter/tsconfig-build.json
src/material-moment-adapter/tsconfig-tests.json
tools/gulp/gulpfile.ts
tools/gulp/packages.ts
tools/gulp/tasks/examples.ts
tools/gulp/tasks/publish.ts
tools/gulp/tasks/unit-test.ts

* Initialization of the `material-moment-adapter` package in the Material repository.

build: initial material moment adapter package

---

e2e/components/expansion-e2e.spec.ts
src/e2e-app/e2e-app/e2e-app.html
src/e2e-app/e2e-app/routes.ts
src/material-examples/example-module.ts
src/material-examples/expansion-overview/expansion-overview-example.ts
src/material-examples/expansion-steps/expansion-steps-example.ts
src/material-examples/material-module.ts
src/material-examples/public_api.ts

* Adds the expansion overview example to the e2e app and captures a screenshot diff for it.
* Also adds a e2e test for the button-toggle

test(): screenshot diff for expansion

---

src/demo-app/a11y/chips/chips-a11y.html
src/demo-app/a11y/chips/chips-a11y.ts

Added remove chip demo
Added notification for adding/removing chips

demo(chips): snackbar notification for adding/removing chips

---

.github/CODEOWNERS
tools/gulp/tasks/publish.ts

* Adds @mmalerba as codeowner for the new Material moment adapter package.
* Also adds a small info what packages will be published/released.
**Note**: Just to ensure that the moment adapter package won't be published accidentally (since it's empty right now)

chore: add codeowner for moment adapter package

---

src/lib/sort/sort-header.html
src/lib/sort/sort-header.scss
src/lib/sort/sort-header.ts
src/lib/sort/sort.spec.ts

Uses @angular/animations module to animate sort order change.

feat(sort): add sorting indicator animation

---

src/material-examples/table-basic/table-basic-example.css

docs(table): fix overflow issue on ie11 site

---

src/lib/list/list-option.html
src/lib/list/selection-list.ts

Fixes the selection list not working in M1 compatibility mode.
Fixes #6746.

compat: selection list not working in compatibility mode

---

CODING_STANDARDS.md

chore: add try-catch section to coding standards

---

src/demo-app/a11y/a11y-module.ts
src/demo-app/a11y/a11y.ts
src/demo-app/a11y/routes.ts
src/demo-app/a11y/tabs/routes.ts
src/demo-app/a11y/tabs/tabs-a11y.html
src/demo-app/a11y/tabs/tabs-a11y.ts

demo(tabs): Add accessibility demo page for tabs

---

src/lib/menu/menu-trigger.ts
src/lib/menu/menu.spec.ts

Reverts angular/material2#6961

Revert "fix(menu): multiple close events for a single close"

---

package.json

Fixes: https://github.com/angular/material.angular.io/issues/260

Bump to gulp-highlight-files@0.0.5

---

src/material-examples/sidenav-fab/sidenav-fab-example.css

Fixes https://github.com/angular/material2/issues/7051

fix(sidenav-fab-example): correctly position fab in plunker

---

src/lib/chips/chip-input.ts
src/lib/chips/chip-list.ts
src/lib/chips/chip.ts
src/material-examples/chips-input/chips-input-example.ts

Fixes a few linting errors in master and a TS error.

chore: linting and TS errors

---

e2e/components/stepper-e2e.spec.ts

Fixes some selectors that weren't renamed in the e2e tests.

chore: stepper e2e failures

---

guides/bidirectionality.md

Fixes https://github.com/angular/material2/issues/6996

docs(bidi): update to secondary entry-points

---

src/lib/sort/sort-header.scss

Thanks IE for keeping me accountable and specific about my styles. 
Fixes #7304

fix(sort): style changes to fix IE

---

src/lib/sort/sort-header.html
src/lib/sort/sort-header.ts

Adds animations for when the sorting arrow is added and removed from the DOM.

feat(sort): add enter and leave arrow animations

---

src/lib/button-toggle/button-toggle.spec.ts
src/lib/button-toggle/button-toggle.ts

fix(button-toggle): Update button toggle group disabled

---

guides/theming-your-components.md

fix minor typos to clarify docs on setting up themes

docs(theme): fix a few typos to improve readability

---

src/cdk/layout/media-matcher.md

Fixes https://github.com/angular/material2/commit/811e50451bb6304a07a3600ae304e5350e41c0e0#commitcomment-24666962
cc @josephperrott

docs(layout): fix media matcher code snippet

---

src/lib/snack-bar/simple-snack-bar.scss
src/lib/snack-bar/simple-snack-bar.ts

Adds a subtle fade in animation to the snack bar content.
Fixes #7502.

fix(snack-bar): add content fade in animation

---

src/lib/autocomplete/autocomplete.md

Fixes https://github.com/angular/material2/issues/7420

docs(autocomplete): add mention of reactive forms

---

src/cdk/scrolling/scroll-dispatcher.spec.ts

The demo app won't build due to PR #7630.

fix(scroll): Replace references to scrollableReferences

---

src/lib/autocomplete/autocomplete.spec.ts

Fixes an autocomplete test failure in iOS Safari 10.

build: autocomplete test failure in iOS Safari

---

README.md

docs(readme): update high-level work for Q4 2017

---

src/material-examples/card-fancy/card-fancy-example.css
src/material-examples/card-fancy/card-fancy-example.html

fix(card): change image path to https in example

---

tools/dgeni/templates/method.template.html
tools/dgeni/templates/property.template.html

Reverts angular/material2#7713

Revert "chore(docs): adds types column and null checks for description"

---

src/material-examples/table-http/table-http-example.ts

Fixes a linting error in the docs

chore: lint error

---

README.md

fix broken ripples link 
use aio for getting started
nested menus are here, remove coming Q3 message
remove unused theming link

docs(readme): cleanup

---

tools/dgeni/templates/method.template.html
tools/dgeni/templates/property.template.html

docs(types): null chk descriptions, type placement updates

---

src/lib/core/datetime/date-adapter.ts
src/lib/core/datetime/native-date-adapter.spec.ts
src/material-moment-adapter/adapter/moment-date-adapter.spec.ts

chore: fix lint error

---

src/lib/radio/radio.spec.ts
src/lib/radio/radio.ts

Fixes #7166
Here's the reproduction Plunk corresponding to the added unit test: http://plnkr.co/edit/ZQ721sXbVJfDjn3kSnCw?p=preview
This is my first PR to Material 2 so please bear with me. Any suggestions how to improve it are welcome.

fix(radio) detect non-direct mat-radio descendants of mat-radio-group

---

src/demo-app/chips/chips-demo.html

It's confusing to only have addOnBlur work for one example.

demo(chips): Set addOnBlur for both inputs

---

CHANGELOG.md

chore:  fix changelog bullet indentation

---

e2e/components/expansion-e2e.spec.ts
src/e2e-app/main.ts
src/lib/expansion/expansion-panel.ts
src/material-examples/expansion-overview/expansion-overview-example.html
src/material-examples/expansion-overview/expansion-overview-example.ts

fix(expansion): add expansion panel outputs

---

src/lib/datepicker/calendar-body.ts
src/lib/datepicker/calendar.ts
src/lib/datepicker/datepicker-toggle.ts
src/lib/datepicker/datepicker.ts
src/lib/datepicker/month-view.ts
src/lib/datepicker/year-view.ts

fix(datepicker): add missing exportAs

---

src/cdk/a11y/a11y-module.ts
src/cdk/a11y/focus-trap.spec.ts
src/cdk/a11y/focus-trap.ts
src/cdk/a11y/public-api.ts

This also renames "FocusTrapDirective" to "CdkTrapFocus" and re-exports it under the old name.

feat(a11y): add autoCapture option to cdkTrapFocus

---

src/material-examples/slider-configurable/slider-configurable-example.html

docs(slider): change slider value binding to ngModel

---

src/lib/chips/chips.scss

fix(chips): Remove chip bottom margin in sibling chips

---

src/cdk/a11y/live-announcer.ts
src/cdk/bidi/bidi-module.ts
src/cdk/overlay/keyboard/overlay-keyboard-dispatcher.ts
src/cdk/overlay/overlay-container.ts
src/cdk/overlay/overlay.ts
src/cdk/overlay/position/connected-position-strategy.spec.ts
src/cdk/overlay/position/connected-position-strategy.ts
src/cdk/overlay/position/global-position-strategy.spec.ts
src/cdk/overlay/position/global-position-strategy.ts
src/cdk/overlay/position/overlay-position-builder.ts
src/demo-app/dialog/dialog-demo.ts
src/lib/autocomplete/autocomplete-trigger.ts
src/lib/datepicker/datepicker.ts
src/lib/dialog/dialog-container.ts
src/lib/sidenav/drawer.ts
src/universal-app/kitchen-sink/kitchen-sink.ts

Fixes multiple server-side rendering issues in the overlay that were causing errors when an overlay is opened in Universal.
Fixes #8412.

fix(overlay): better handling of server-side rendering

---

src/lib/menu/menu-item.html
src/lib/menu/menu-item.ts
src/lib/menu/menu.scss
src/lib/menu/menu.spec.ts

* Allows disabling ripples for specific menu items.
Closes #8261

feat(menu-item): allow disabling ripples

---

src/lib/datepicker/datepicker-content.scss

fix(datepicker): correct overlay broad selector

---

src/material-examples/example-module.ts

* Adds the table-selection example to the `ExamplesModule`.

docs: add table-selection example

---

src/cdk/overlay/position/connected-position-strategy.spec.ts

Fixes a compilation error due to the constructor changing between PRs.

chore: fix test compilation error

---

tools/dashboard/package.json
tools/dashboard/src/app/coverage-chart/coverage-chart.html
tools/dashboard/src/app/dashboard-app.ts
tools/dashboard/src/app/dashboard-module.ts
tools/dashboard/src/app/payload-chart/payload-chart.html

* Fixes TypeScript errors for the dashboard app.
* Adds timeline to the payload and coverage graphs.

build: fix dashboard compile failures

---

src/lib/sidenav/drawer.scss
src/lib/sidenav/drawer.spec.ts

fix(sidenav): remove min-width

---

src/lib/chips/chip-list.spec.ts
src/lib/chips/chip-list.ts
src/lib/chips/chips-module.ts
src/lib/core/common-behaviors/error-state.ts
src/lib/core/common-behaviors/index.ts
src/lib/core/common-behaviors/tabindex.ts
src/lib/input/input.ts
src/lib/select/select.ts

fix(chip-list): fix error state changes in chip list

---

src/demo-app/ripple/ripple-demo.scss
src/lib/core/ripple/ripple-renderer.ts
src/lib/core/ripple/ripple.spec.ts

* Now handles touch events properly.
**Note**: Tested it thoroughly already and it works great. Still want to test on more devices manually to make sure it works fine!
Fixes #7062

feat(ripple): handle touch events

---

src/lib/menu/menu.spec.ts

Fixes a failure in the menu tests due to a few PRs being merged at the same time.

chore: fix menu test failure

---

.circleci/config.yml

fix: CircleCI broken with current version of Angular

---

src/lib/datepicker/datepicker.spec.ts

Fixes a test failure in the datepicker that came up after merging in a couple of conflicting fixes at the same time.

chore(datepicker): fix test failure

---

package-lock.json
package.json
scripts/caretaking/write-presumbit-scheduler.js

@mmalerba @josephperrott @tinayuangao @andrewseguin 
This is my first pass at writing a low-effort presubmit scheduler. I decided it to have it write a script so that you can make any local modifications necessary before running it (such as adding `--cherrypick` or omiting certain PRs). Let me know if you have any ideas to improve it.

chore: add script to generate caretaker presubmit scheduler script

---

package-lock.json
src/lib/autocomplete/autocomplete.spec.ts

Fixes the various testing tasks exiting silently due to the autocomplete tests not compiling cleanly with ngc.

build: fix autocomplete tests not compiling

---

src/lib/divider/BUILD.bazel

build: add bazel rules for divider

---

src/lib/divider/tsconfig-build.json

build: add missing typecheck to divider

---

src/lib/dialog/dialog-config.ts
src/lib/dialog/dialog-module.ts
src/lib/dialog/dialog.spec.ts
src/lib/dialog/dialog.ts

Implements global dialog options.
Fixes #5664

feat(dialog): allow default dialog options to be configurable

---

guides/getting-started.md

Wrong Command, Change Install to Add

Updating Getting Started.md

---

CHANGELOG.md

Removes a PR that was reverted from the current changelog.

chore: remove reverted change from changelog

---

guides/creating-a-custom-form-field-control.md

docs(form-field): set correct method name

---

guides/getting-started.md

Added the yarn option for Gesture section

Yarn option for Gesture hammerjs

---

src/lib/radio/radio.ts

* Fixes the `MatRadioButton` class description.

docs: fix radio button description

---

src/lib/slide-toggle/slide-toggle.ts

docs(slide-toggle): add missing docs for 'MatSlideToggleChange' class

---

src/lib/core/style/_variables.scss

fix(card,tabs,toolbar): Change media query breakpoints

---

src/cdk/overlay/public-api.ts

Export OverlayPositionBuilder to aide in extending the Overlay class.
Closes #9263

chore(overlay): export OverlayPositionBuilder

---

e2e/components/menu-e2e.spec.ts

Fixes an e2e test that is failing after #9383.

chore: fix menu e2e test failure

---

src/universal-app/index.html

Quick spelling issue in universal-app/index.html

Fix(spelling): universal-app/index.html title tag | Univeral -> Universal

---

src/lib/radio/radio.ts

chore(radio): change declaration of MatRadioChange class

---

src/material-examples/card-fancy/card-fancy-example.css

docs(card): fix example card overflowing on smaller screens

---

src/lib/paginator/paginator.spec.ts

the test was referencing the wrong page
discovered in #9278

test(paginator): fix incorrect test name

---

src/lib/chips/chip-input.ts
src/lib/icon/icon.ts

Finish the work started in #9583. Must be merged before #8200.
cc: @jelbourn

build: fix remaining unescaped html tags

---

src/cdk/layout/breakpoints.ts

feat(layout): add window breakpoints from spec

---

src/lib/checkbox/checkbox.md

dependency injection
Fixes #8890

docs(checkbox): Fix checkbox docs, and add example and link about

---

tools/gulp/tasks/development.ts

Fixes the demo app 404ing on the favicon.

chore: fix demo app not serving the favicon

---

src/lib/tabs/_tabs-common.scss
src/lib/tabs/tab-group.html

This is needed for some customization cases.
cc @ErinCoughlan

chore: add span around tab label content

---

src/cdk/portal/portal.md

Typo fix in portal.md

---

src/lib/checkbox/checkbox.html
src/lib/radio/radio.html
src/lib/slide-toggle/slide-toggle.html

* Updates the slide-toggle, radio and checkbox ripples to have a quicker enter animation. This aligns more with the behavior MDC provides, and also feels more appropriate (for focus indicators) and is also more aligned with the specs.

update(radio, slide-toggle, checkbox): faster ripple enter animations

---

src/cdk/a11y/live-announcer/live-announcer.spec.ts
src/lib/tabs/tab-body.ts
src/lib/tabs/tab.ts

Fixes a few lint warnings that got into master.

chore: fix lint warnings

---

src/cdk/overlay/overlay.ts

Typo fix (in the comments)

---

src/lib/progress-spinner/progress-spinner.scss
src/lib/progress-spinner/progress-spinner.ts

this fixes  [#8984](https://github.com/angular/material2/issues/8984)

fix(progress spinner) : fix flickering animation

---

src/material-examples/bottom-sheet-overview/bottom-sheet-overview-example.ts

Fixes a compilation error in the examples, presumably due to a faulty rebase.

chore: fix example compilation error

---

src/cdk-experimental/dialog/dialog.ts

fix(cdk-dialog): decorate dialog as an injectable

---

src/material-examples/snack-bar-position/snack-bar-position-example.html
src/material-examples/snack-bar-position/snack-bar-position-example.ts

Adds an example for positioning snack bars.

docs(snackbar): add position example

---

src/lib/tooltip/tooltip.md

docs(tooltip): fix typo left/right

---

src/cdk/tree/nested-node.ts
src/cdk/tree/tree.spec.ts
src/cdk/tree/tree.ts
src/demo-app/tree/checklist-tree-demo/checklist-tree-demo.ts
src/demo-app/tree/dynamic-tree-demo/dynamic-database.ts
src/demo-app/tree/loadmore-tree-demo/loadmore-tree-demo.ts

Same as pr #10053 
Now target master branch since tree branch is merged to master

fix(tree): fix type error in tree

---

src/lib/datepicker/datepicker-input.ts
src/universal-app/kitchen-sink/kitchen-sink.html

Fixes disabled datepicker inputs throwing an error when rendering on the server.
Fixes #10248.

fix(datepicker): server-side rendering error for disabled input

---

src/lib/tree/tree.scss

Fixes #10104 
demo: https://tina-demo1.firebaseapp.com/tree

fix(tree): fix mat-tree paddings

---

src/material-examples/slider-configurable/slider-configurable-example.html

Fixes a couple of instances that were missed when removing the slider deletion targets and were breaking e2e runs.

chore: fix error in slider docs

---

src/demo-app/connected-overlay/connected-overlay-demo.ts

Fixes the aot CI check failing due to a faulty rebase.

chore: fix aot check failure

---

src/lib/sidenav/drawer.scss

Fixes the open drawer blending in with the app background in high contrast mode.

fix(drawer): better handling of high contrast mode

---

src/lib/menu/menu.spec.ts

Along the same lines as #10517. Refactors the menu unit tests to make them faster and (hopefully) more reliable.

refactor(menu): improved unit test speed

---

src/lib/tree/node.ts

fix(tree): fix nested node is not working

---

src/material-examples/chips-autocomplete/chips-autocomplete-example.html
src/material-examples/sidenav-open-close/sidenav-open-close-example.ts
src/material-examples/table-basic/table-basic-example.css
src/material-examples/table-filtering/table-filtering-example.css
src/material-examples/table-http/table-http-example.css
src/material-examples/table-overview/table-overview-example.css
src/material-examples/table-pagination/table-pagination-example.css
src/material-examples/table-selection/table-selection-example.css
src/material-examples/table-sorting/table-sorting-example.css

Small fixes to the examples that were broken in recent commits

chore(examples): minor fixes

---

README.md

chore: update readme for Q2 2018

---

src/lib/schematics/utils/devkit-utils/config.ts

fix(schematics): ignore e2e projects w/ `ng add`

---

src/cdk/overlay/public-api.ts

export ConnectedPosition alongside FlexibleConnectedPositionStrategy as part of the public api for overlay

chore(overlay): export ConnectedPosition interface

---

src/lib/bottom-sheet/bottom-sheet-container.ts
src/universal-app/kitchen-sink/kitchen-sink.ts

* Fixes a server-side rendering error when opening a bottom sheet.
* Adds the bottom sheet to the prerender CI check.

fix(bottom-sheet): server-side rendering error when opened

---

src/cdk/tree/nested-node.ts
src/cdk/tree/node.ts
src/cdk/tree/tree.spec.ts
src/cdk/tree/tree.ts

feat(tree): add level to tree node context

---

src/material-examples/sidenav-overview/sidenav-overview-example.css

docs(sidenav): make the sidenav easier to see in overview example

---

tools/screenshot-test/package-lock.json
tools/screenshot-test/package.json

* Fixes the screenshot tool not compiling.
* Adds the `package-lock.json` for the screenshot tool.

build: fix screenshot tool compilation errors

---

.github/angular-robot.yml

see https://github.com/angular/angular/pull/23665

ci: add config for size plugin of the github rebot

---

src/material-examples/table-footer-row/table-footer-row-example.html

docs(table): fix table footer doc

---

README.md

chore: update README.md with new available features that came with v6

---

src/lib/schematics/utils/ast.ts

fix: add custom theme using string ref in angular.json

---

src/material-examples/table-overview/table-overview-example.ts

Addresses https://github.com/angular/material2/issues/9965

docs(table): fix example not correctly changing pages when filtering

---

src/cdk/table/table-errors.ts
src/cdk/table/table.spec.ts
src/cdk/table/table.ts
src/lib/table/table.spec.ts
src/material-examples/table-multiple-header-footer/table-multiple-header-footer-example.css
src/material-examples/table-multiple-header-footer/table-multiple-header-footer-example.html
src/material-examples/table-multiple-header-footer/table-multiple-header-footer-example.ts

feat(table): allow multiple header/footer rows

---

src/cdk/tree/nested-node.ts
src/cdk/tree/tree.md
src/cdk/tree/tree.spec.ts
src/cdk/tree/tree.ts

Add trackBy support to cdk-tree component

feat(tree): Add support for trackBy

---

CHANGELOG.md
package.json

This PR for master (earlier PR was for the patch branch)

chore: update version and changelog for 6.0.2

---

src/material-examples/stepper-vertical/stepper-vertical-example.ts

Fixes a lint failure that was introduced by a PR being merged in close to another one that introduced new lint rules.

chore: fix lint failure

---

src/demo-app/expansion/expansion-demo.html
src/demo-app/expansion/expansion-demo.ts
src/lib/expansion/_expansion-theme.scss
src/lib/expansion/accordion.spec.ts
src/lib/expansion/accordion.ts
src/lib/expansion/expansion-animations.ts
src/lib/expansion/expansion-panel-header.html
src/lib/expansion/expansion-panel-header.scss
src/lib/expansion/expansion-panel-header.ts
src/lib/expansion/expansion-panel.ts
src/lib/expansion/expansion.md
src/lib/expansion/expansion.spec.ts

Reverts angular/material2#8199

Revert "feat(expansion): allow expansion indicator positioning."

---

src/lib/sidenav/drawer-container.html
src/lib/sidenav/drawer.spec.ts
src/lib/sidenav/drawer.ts
src/lib/sidenav/sidenav.md
src/lib/sidenav/sidenav.ts

Reverts angular/material2#11517

Revert "fix(sidenav): scrollable instance not exposed when explicitly specifying content element"

---

src/material-examples/tab-group-lazy-loaded/tab-group-lazy-loaded-example.html

Missed commit from merged PR #11712

chore(tabs): remove minor spacing in examples

---

src/demo-app/tree/dynamic-tree-demo/dynamic-database.ts

This reverts commit 0c4f5990cc8707584f4b6fff7b92577e452e20bc.

Revert "This commit fixes #11148"

---

src/material-examples/table-sticky-footer/table-sticky-footer-example.html

fix(docs): add missing semicolon

---

src/lib/button-toggle/button-toggle.html
src/lib/button-toggle/button-toggle.ts

fix(button-toggle): allow event bubbling for toggle button clicks

---

src/demo-app/bottom-sheet/bottom-sheet-demo.html
src/demo-app/bottom-sheet/bottom-sheet-demo.ts
src/demo-app/dialog/dialog-demo.html
src/demo-app/sidenav/sidenav-demo.html
src/demo-app/tsconfig-aot.json
src/e2e-app/tsconfig-build.json
src/material-examples/tsconfig-build.json

* Enables `fullTemplateTypeCheck` in the aot demo app and e2e app.

build: enable fullTemplateTypeCheck in aot mode 

---

README.md

docs: update README for Q3 2018

---

src/cdk-experimental/drag-drop/drop-container.ts
src/cdk-experimental/drag-drop/public-api.ts

fix(drag-drop): make `CDK_DROP_CONTAINER` public

---

src/lib/schematics/dashboard/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html
src/lib/schematics/dashboard/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts

add async pipe in dashboard template to prevent object iteration

fix(schematics): fix object iteration error in dashboard

---

guides/theming.md

docs(theming): update theming.md for angular 6

---

BUILD.bazel
package-lock.json
package.json

* Removes unused dependencies.

build: remove unused dependencies

---

src/lib/select/select.spec.ts

Fixes a flaky test that is failing on iOS.

chore(select): fix flaky positioning test

---

src/cdk/scrolling/virtual-scroll-viewport.html
src/cdk/scrolling/virtual-scroll-viewport.scss
src/cdk/scrolling/virtual-scroll-viewport.ts

* Adds some CSS properties to help improve performance
* Changes spacer element to use a transform rather than width/height to expand the viewport

perf(virtual-scroll): improve scrolling performance

---

src/lib/button/button.scss

fix(button): allow transition for the button focus overlay for all buttons

---

src/lib/button/button.ts

fix(button): allow for non-colored flat button

---

src/lib/slide-toggle/_slide-toggle-theme.scss

fix(slide-toggle): update font sizing

---

src/lib/dialog/dialog-ref.ts
src/lib/dialog/dialog.ts

Fixes some lint failures that got into master by an older PR getting merged.

chore: fix deletion target lint failure

---

src/cdk/datetime/calendar-view.ts
src/cdk/datetime/datepicker-input.ts
src/cdk/datetime/datepicker.spec.ts
src/cdk/datetime/datepicker.ts
src/lib/core/datetime/date-formats.ts
src/lib/core/datetime/native-date-formats.ts
src/lib/core/datetime/public-api.ts
src/lib/core/public-api.ts
src/lib/datepicker/calendar.spec.ts
src/lib/datepicker/calendar.ts
src/lib/datepicker/datepicker-input.ts
src/lib/datepicker/datepicker.spec.ts
src/lib/datepicker/month-view.ts
src/lib/datepicker/multi-year-view.ts
src/lib/datepicker/year-view.ts
src/material-moment-adapter/adapter/moment-date-formats.ts

Added checks for CalendarView in the CDK datepicker tests

Passing information between CalendarView and CDK Datepicker + Datepicker Input

---

src/lib/sidenav/sidenav.md

Information from comments on [#8330](https://github.com/angular/material2/issues/8330#issuecomment-343640044)

docs(sidenav): add note about `mat-sidenav` placement

---

src/lib/datepicker/datepicker.md

Fixes MAT_MOMENT_DATE_ADAPTER_OPTIONS reference in DatePicker Documentation

 Fixes MAT_MOMENT_DATE_ADAPTER_OPTIONS

---

src/demo-app/expansion/expansion-demo.html
src/demo-app/expansion/expansion-demo.scss
src/demo-app/expansion/expansion-demo.ts
src/lib/expansion/expansion-panel.ts
src/lib/expansion/expansion.spec.ts

feat(expansion): emit animation events for expansion panels

---

tools/gulp/tasks/publish/branch-check.ts

@DevVersion I made this work for now, but it will need an extra bit of knowledge after we publish v7. At that point, `master` will represent the next `minor` release, so we need to allow that if a corresponding minor branch (e.g. `7.x.x`) does not yet exist on upstream (directly checking `git@github.com:angular/material2.git`).

chore: make publish version+branch check support minor and patch

---

src/lib/schematics/tree/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html
src/lib/schematics/tree/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts

fix(schematics): remove unnecessary semicolon in tree component

---

src/lib/schematics/nav/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts

fix no-trailing-whitespace errors

fix(schematics): nav schematic generates TSLint errors

---

src/lib/bottom-sheet/bottom-sheet.spec.ts

Fixes a compilation error that got introduced in master because of the TS 3.1 update.

chore: fix compilation error in master

---

src/lib/schematics/nav/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html
src/lib/schematics/nav/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts

This reverts commit 381c03725cbee3661aadb9996f1e98c6f520fd1b.

Revert "avoid multiple async calls (#13301)"

---

src/lib/bottom-sheet/bottom-sheet.spec.ts
src/lib/bottom-sheet/bottom-sheet.ts

Dismisses the open bottom sheet if the service is destroyed.

fix(bottom-sheet): dismiss bottom sheet on destroy

---

src/lib/slide-toggle/slide-toggle.ts

* Improves the readability of the API Docs for the Slide Toggle component.

docs: clean up slide toggle API Docs

---

src/lib/table/table.md

Fixes #13197
Best regards,
Benedikt

docs(table component): Improve instructions on sorting

---

src/material-examples/select-panel-class/select-panel-class-example.css

doc(select): correct css styles in select panel custom styling example

---

src/lib/bottom-sheet/bottom-sheet.spec.ts

Fixes a compilation error that got in through a PR that was opened before we updated to TS 3.1.

chore: fix compilation error in bottom sheet tests

---

package.json
yarn.lock

fix warning with incompatible peerDependencies

build: update codelyzer
