WORKSPACE
Updates to the latest release of the NodeJS Bazel rules.
=> build: update to rules nodejs v1.6.1

src/components-examples/cdk/text-field/text-field-autofill-directive/text-field-autofill-directive-example.html, src/components-examples/cdk/text-field/text-field-autofill-monitor/text-field-autofill-monitor-example.html
There were a couple of examples which would trigger a page refresh if the user pressed one of the buttons, because we were using a form without preventing its default action.
=> docs: prevent form submission in examples

src/material-experimental/mdc-form-field/_form-field-native-select.scss, src/material-experimental/mdc-form-field/_form-field-theme.scss
On dark themes the `color` of the native `select` inside of an MDC-based form field is usually set to some shade of white. The problem is that the color of the native `select` dropdown preserves its white background, making the text invisible. These changes make it so that the options always use a dark text color.
=> fix(material-experimental/mdc-input): native select option blending in with background on dark themes

DEV_ENVIRONMENT.md, package.json, scripts/approve-api-golden.js
The Bazel targets for approving public API changes are a little convoluted and hard to remember. These changes add a small script to make it easier to manage. E.g. `yarn api:approve material/chips`.
=> build: add script for approving public API changes

src/cdk/schematics/utils/build-component.ts
The internal `project` file will be deleted with this change https://github.com/angular/angular-cli/pull/17597, this copies that implementation to the file were it's needed.
=> refactor: remove usage of private `buildDefaultPath` method from `@schematics/angular`

scripts/run-component-tests.js
Fixes not being able to run the schematics tests through `yarn test`. The logic for resolving the package was correct, but we were appending the wrong target name.
Fixes #19182.
=> build: unable to run schematics tests through test script

src/material/datepicker/calendar-body.html
Fixes the calendar cells having two `role` attributes.
Fixes #17280.
=> fix(datepicker): double role definition on calendar cell

.github/CODEOWNERS, src/dev-app/BUILD.bazel, src/dev-app/dev-app/dev-app-layout.ts, src/dev-app/dev-app/routes.ts, src/dev-app/mdc-sidenav/BUILD.bazel, src/dev-app/mdc-sidenav/mdc-sidenav-demo-module.ts, src/dev-app/mdc-sidenav/mdc-sidenav-demo.html, src/dev-app/mdc-sidenav/mdc-sidenav-demo.scss, src/dev-app/mdc-sidenav/mdc-sidenav-demo.ts
Sets up a place in the dev app to make it easier to debug the MDC sidenav.
=> build: add dev app for MDC sidenav

src/material-experimental/mdc-form-field/public-api.ts
We recently added a new injection token called `MAT_FORM_FIELD`. This
token should allow form control implementers to inject the form-field
without having to bring in the actual `MatFormField` as a side-effect.
We should expose that token from the MDC form-field entry-point too,
as that will ease the migration. Also it would be unexpected if an
application switches to the MDC-based form field, but would still need
to import from the non-MDC form field entry-point.
=> feat(material-experimental/mdc-form-field): expose `MAT_FORM_FIELD` injection token

integration/ts-compat/BUILD.bazel, package.json, src/cdk/drag-drop/drag-ref.ts, src/cdk/drag-drop/drag-styling.ts, src/cdk/drag-drop/drop-list-ref.ts, src/material/tooltip/tooltip.spec.ts, src/material/tooltip/tooltip.ts, tools/tslint-rules/tsLoaderRule.js, tools/tslint-rules/tsconfig.json, yarn.lock
The Framework team is in the process of updating to TS 3.9 (see https://github.com/angular/angular/pull/36989) which means that soon we'll have to switch to it as well. These changes update us to the latest RC and resolve all of the build issues so that we can quickly switch to the final version once it's available.
**Note:** I had to add some `as any` casts, because a few non-standard properties were removed from the `CSSStyleDeclaration`.
=> build: update to typescript 3.9

src/cdk/overlay/keyboard/overlay-keyboard-dispatcher.ts, src/cdk/overlay/overlay-ref.ts, tools/public_api_guard/cdk/overlay.d.ts
Removes an unnecessary observable that has the potential for memory leaks.
Fixes #10573.
=> fix(overlay): remove potentially leaky observable

src/google-maps/google-map/google-map.ts, src/google-maps/map-circle/map-circle.ts, src/google-maps/map-ground-overlay/map-ground-overlay.ts, src/google-maps/map-info-window/map-info-window.ts, src/google-maps/map-marker/map-marker.ts, src/google-maps/map-polygon/map-polygon.ts, src/google-maps/map-polyline/map-polyline.ts, src/google-maps/map-rectangle/map-rectangle.ts
We can take advantage of TypeScript's `asserts` keyword so that we don't have to cast values to be non-nullable, when we've already asserted that they exist.
=> refactor(google-maps): use assert functions to avoid casting to non-nullable value

src/material/table/testing/cell-harness.ts, src/material/table/testing/shared.spec.ts, src/material/table/testing/table-harness-filters.ts, tools/public_api_guard/material/table/testing.d.ts
Adds an extra filter to the column harness to allow cells to be picked out by column name.
Fixes #19172.
**Note:** even though this is marked as a `feat`, I'm setting it for `patch`, because it's pretty minor and all of the parts for it were already in place. I don't feel strongly against bumping it up to a `minor` though.
=> feat(table/testing): allow filtering by column name

.bazelrc
A long-standing issue with our Bazel setup was that the switch
between `ibazel` and `bazel` always resulted a slow down.
It was difficult to debug this because Bazel did not print
anything about what is going on. i.e. it was not clear whether
the analysis cache, or repositories have been discarded. After
investigation it turns out that we set Bazel starlark semantic options
that are applied on to `build` while technically this option also is
relevant for Bazel's first processing phase (i.e. `loading phase`) that runs
for `query`. See how the `QueryCommand` processes the semantic options:
1. https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/runtime/commands/QueryEnvironmentBasedCommand.java;l=103;drc=dcead939ba5fe39d61da6a18a6f83d75e1117f46
2. …
=> build: fix unexpected bazel cache discarding

scripts/run-component-tests.js
We cannot run `yarn test all` with ibazel due to Ibazel
not supporting the flags we need in order to filter out
build/test targets.
We temporarily always run in non-watch mode, print a warning
until the upstream fix lands: https://github.com/bazelbuild/bazel-watcher/pull/382.
Also ensures that the script runs Yarn through bazelisk. We previously regressed here
due to a local debugging change having made it into a PR (my bad!)
=> build: disable watch mode for `yarn test all` script

src/material/dialog/dialog-container.ts, src/material/dialog/dialog.spec.ts
In #18826 some code was moved around, and as a result, the focus trap was being created lazily only when we interact with its API. The problem is that this means that focus trapping will be disabled if `autoFocus` was turned off.
Fixes #19246.
=> fix(dialog): focus trap not attached if autoFocus is disabled

src/material/chips/chip-list.spec.ts, src/material/chips/chip-list.ts, src/material/chips/chip.ts, tools/public_api_guard/material/chips.d.ts
When a chip list is disabled, it goes through all the chips and sets their `disabled` values. The problem is that this overrides any individual values the consumer may have set. These changes fix the issue by saving the value to a different field.
Fixes #19213.
=> fix(chips): chip list overriding chip disabled value

src/material-experimental/mdc-tabs/tab-header.spec.ts, src/material/tabs/paginated-tab-header.ts, src/material/tabs/tab-header.spec.ts
Switches to only preventing the default enter/space action if we did something with the event, otherwise we risk interfering with other user events.
Fixes #19190.
=> fix(tabs): don't prevent default space/enter action if active tab doesn't change

src/material/list/selection-list.spec.ts, src/material/list/selection-list.ts
In #18445 the selection list was changed so that it moves focus to the first item when the list receives focus. The problem is that the logic that marks it as touched was still using the list's `blur` event which means that it'll be marked as touched when focus goes from the list to the item. These changes switch to only using the `blur` event on the item.
Fixes #19171.
=> fix(list): selection list marked as touched when tabbing in

src/material-experimental/mdc-input/input.ts, src/material/input/input.ts, tools/public_api_guard/material/input.d.ts
Since the node's type can't change, it's unnecessary to check the DOM in the `_isTextarea` on every invocation. This affects the MDC form field in particular since it's used in a data binding.
=> fix(input): avoid repeat accesses to check if element is a textarea

src/material/form-field/form-field-module.ts, tools/public_api_guard/material/form-field.d.ts
We seem to miss the `MatCommonModule` in the form-field. This came up
when doing size comparison between the MDC-based form-field.
It's unclear to me if there is any reason why we didn't add it to the form-field
in the past. Maybe it was just an oversight.
=> fix(form-field): add missing material common module

package.json, src/material-experimental/mdc-chips/chip-icons.ts, src/material-experimental/mdc-chips/chip.ts, yarn.lock
These changes are mostly based on @crisbeto's #18877 with some
additional changes from @prodee
=> refactor(material-experimental/mdc-chips): implement trailing icon foundation

src/material/expansion/expansion-panel-header.ts, src/material/expansion/expansion.spec.ts
For the density system, we reworked the expansion panel to no longer
rely on Angular animations. Looks like the refactoring missed that units
are already set for the `expandedHeight` and `collapsedHeight` inputs.
This hasn't been catched in any unit test, so tests are updated to catch this now.
=> fix: unable to set expanded or collapsed height in expansion panel

src/cdk/table/table.ts, tools/public_api_guard/cdk/table.d.ts
Removes the APIs that have been deprecated for v10.
* `CdkTable.setHeaderRowDef` has been removed. Use `CdkTable.addHeaderRowDef` and `CdkTable.removeHeaderRowDef` instead.
* `CdkTable.setFooterRowDef` has been removed. Use `CdkTable.addFooterRowDef` and `CdkTable.removeFooterRowDef` instead.
=> refactor(cdk/table): remove deprecated APIs for version 10

src/material-experimental/mdc-slide-toggle/slide-toggle-config.ts, src/material-experimental/mdc-slide-toggle/slide-toggle.ts, src/material/schematics/ng-update/data/constructor-checks.ts, src/material/slide-toggle/BUILD.bazel, src/material/slide-toggle/slide-toggle-config.ts, src/material/slide-toggle/slide-toggle.spec.ts, src/material/slide-toggle/slide-toggle.ts, tools/public_api_guard/material/slide-toggle.d.ts
Removes the APIs that were marked as deprecated for v10.
* `MatSlideToggleDefaultOptions.disableDragValue` has been removed.
* `MatSlideToggle.dragChange` has been removed.
* The `_ngZone` and `_dir` parameters have been removed from the `MatSlideToggle` constructor.
=> refactor(slide-toggle): remove deprecated APIs for version 10

src/material/core/focus-indicators/_focus-indicators.scss, src/material/datepicker/calendar-body.html, src/material/datepicker/calendar-body.spec.ts
We ended up using the same pseudo elements for the strong focus indication and the date range, causing the focus indication to always be shown. These changes move the focus indicator to a different element.
=> fix(datepicker): strong focus indication in calendar always shown

src/cdk/drag-drop/directives/config.ts, src/cdk/drag-drop/directives/drag.ts, src/cdk/drag-drop/directives/drop-list.ts, tools/public_api_guard/cdk/drag-drop.d.ts
Removes some deprecated APIs that were marked to be removed in v10. Also marks some more APIs that were supposed to deprecated.
* `CdkDropList.start` has been removed.
* `CdkDropList.drop` has been removed.
* `CdkDropList.enter` has been removed.
* `CdkDropList.exit` has been removed.
* `CdkDropList.getItemIndex` has been removed.
* `CDK_DRAG_CONFIG_FACTORY` has been removed.
=> refactor(drag-drop): remove deprecated APIs for version 10

src/cdk/text-field/_text-field.scss, src/cdk/text-field/autosize.ts
When we're measuring the height of an autosized textarea, we apply a class that has `overflow: hidden`. The `overflow` declaration seems to hit a bug on Firefox that doesn't allow users to undo/redo what they've typed. These changes add a specific workaround for Firefox.
Fixes #16629.
=> fix(text-field): unable to undo/redo in autosized text field on firefox

package.json, scripts/breaking-changes.ts, yarn.lock
It seems like using the RC of TS 3.9 causes a typing mismatch which breaks the `breaking-changes` script. Temporarily switches to using 3.8.
=> build: fix breaking changes script compilation error

src/cdk/a11y/focus-monitor/focus-monitor.spec.ts, src/cdk/a11y/focus-monitor/focus-monitor.ts
With the current logic, if an element is being monitored with `checkChildren` set to `true` and then we start monitoring it with `false`, the initial monitor call will stop checking the children, because we take the `checkChildren` value from the most-recent call. This is something that we discussed in https://github.com/angular/components/pull/19135#discussion_r412471591, but now we have a case where it can happen: setting a tooltip on a sort header. The sort header looks for child focus, whereas the tooltip doesn't, causing the sort focus indication to break.
These changes fix the issue by treating all focus as `checkChildren`, as soon as there's at least one call to `monitor` with `checkChildren` turned on.
Fixes #19218.
=> fix(a11y): focus monitor not checking children if monitor is called multiple times with different parameters

src/material-experimental/mdc-form-field/_form-field-density.scss, src/material-experimental/mdc-form-field/_form-field-focus-overlay.scss, src/material-experimental/mdc-form-field/_form-field-native-select.scss, src/material-experimental/mdc-form-field/_form-field-subscript.scss, src/material-experimental/mdc-form-field/_form-field-theme.scss, src/material-experimental/mdc-form-field/form-field.scss
Mixins like `_mat-form-field-density` also exist in the non-mdc
form-field implementation. Even though there might be no density styles
there, the actual MDC-based from-field will loose its default density
styles and render incorrectly if the wrong mixin is picked up accidentally.
=> refactor(mdc-form-field): disambiguate mixin names from non-mdc form-field

src/youtube-player/youtube-player.ts, tools/public_api_guard/youtube-player/youtube-player.d.ts
Changes the APIs that were marked as deprecated in the `youtube-player` module.
* The `platformId` parameter of the `YouTubePlayer` constructor is now required.
=> refactor(youtube-player): change deprecated APIs for version 10

src/cdk/schematics/ng-update/devkit-file-system.ts, src/cdk/schematics/ng-update/devkit-migration-rule.ts, src/cdk/schematics/ng-update/migrations/attribute-selectors.ts, src/cdk/schematics/ng-update/migrations/class-names.ts, src/cdk/schematics/ng-update/migrations/css-selectors.ts, src/cdk/schematics/ng-update/migrations/element-selectors.ts, src/cdk/schematics/ng-update/migrations/input-names.ts, src/cdk/schematics/ng-update/migrations/output-names.ts, src/cdk/schematics/ng-update/migrations/property-names.ts, src/cdk/schematics/ng-update/test-cases/misc/external-resource-resolution.spec.ts, src/cdk/schematics/ng-update/test-cases/misc/external-resource-resolution_input.ts, src/cdk/schematics/testing/test-case-setup.ts, src/cdk/schematics/update-tool/component-resource-collector.ts, src/cdk/schematics/update-tool/file-system.ts, src/cdk/schematics/update-tool/index.ts, src/cdk/schematics/update-tool/migration.ts, src/cdk/schematics/utils/project-index-file.ts, src/cdk/schematics/utils/project-main-file.ts, src/material/schematics/ng-update/migrations/hammer-gestures-v9/hammer-gestures-migration.ts, src/material/schematics/ng-update/migrations/hammer-gestures-v9/import-manager.ts, src/material/schematics/ng-update/migrations/misc-ripples-v7/ripple-speed-factor-migration.ts, src/material/schematics/ng-update/migrations/package-imports-v8/secondary-entry-points-migration.ts
Schematics using the TypeScript compiler API have a significant issue
with paths. The problem is that the TypeScript compiler API intends to
rely fully on absolute paths, while ng-update and the devkit tree intend
to rely on project-scoped/relative paths.
This is problematic as it is straightforward to mix paths up, leading to
unexpected errors. For example, computing a relative path between a devkit
path and an absolute disk path results in a non-existent path.
To fix this ambiguity, we improve type safety of paths by using branded
primitives such as the `@angular-devkit/core` `Path` or an even more
strict type called `WorkspacePath`. A normal string is considered an
unresolved path and cannot be assigned to a `WorkspacePath`. Similarly a
`WorkspacePath` cannot be assigned to a `string`. …
=> refactor: ensure paths are safely passed around in ng-update

src/material/autocomplete/autocomplete-trigger.ts
When an autocomplete is inserted, we try to figure out whether it's in the shadow DOM so that we can handle outside clicks properly. It seems like our logic can run too early in some cases, causing it to be detected incorrectly. These changes move the logic later in the process, right before the overlay is attached to the DOM.
Fixes #19330.
**Note:** In the first iteration I had a unit test for this, but I couldn't get it to pass on ViewEngine, because one of the APIs I used to query for an element in the shadow DOM wasn't working. Since we don't have a way of disabling tests for ViewEngine, I ended up reverting it.
=> fix(autocomplete): incorrectly detecting shadow DOM when inserted through an embedded view

src/material/datepicker/_datepicker-theme.scss
Currently the date range input separator inherits its color which may not always be correct. These changes set the color explicitly based on the theme.
=> fix(datepicker): set color on range separator

src/dev-app/google-map/google-map-demo.html, src/dev-app/google-map/google-map-demo.ts, src/google-maps/map-ground-overlay/map-ground-overlay.spec.ts, src/google-maps/map-ground-overlay/map-ground-overlay.ts, src/google-maps/testing/fake-google-map-utils.ts, tools/public_api_guard/google-maps/google-maps.d.ts
As things are set up at the moment, changing the ground overlay's `url` won't do anything. These changes add some extra logic to update the URL and to tell the map to re-render.
cc @mbehrlich
=> fix(google-maps): allow for ground overlay image to be changed

src/material/icon/icon.spec.ts, src/material/icon/icon.ts
Currently we can stack up in-flight quests if the icon name changes quickly. These changes will cancel any in-flight requests if that happens or if the icon is destroyed.
Fixes #19259.
=> fix(icon): cancel in-flight icon requests if the icon changes

guides/v9-hammerjs-migration.md
Fixes a failure in the docs generation task due to a couple of wrong links.
=> build: fix wrong anchors in docs

src/material/expansion/expansion-panel-header.scss, src/material/expansion/expansion-panel-header.ts, tools/public_api_guard/material/expansion.d.ts
We recently refactored the header height transition from Angular
animations to plain CSS (to support density styles).
It looks like this means that we no longer respect the noop animations
module for that animation. This commit fixes that.
=> fix(expansion): disable header height transition if noop animations is set

CHANGELOG.md
Cherry picking the changelog from #19386 to master
=> chore: bump version to 9.2.4 w/ changelog

package.json, src/material-experimental/mdc-form-field/BUILD.bazel, yarn.lock
Bumps to the latest canary version of MDC and fixes a build error due to some code that was moved around.
Related change: https://github.com/material-components/material-components-web/commit/bcdad99bbf9ac4d2bbc09cf6378c0c040521e514
=> build: update to latest MDC canary and fix error

src/bazel-tsconfig-build.json, src/bazel-tsconfig-test.json, src/universal-app/prerender.ts, tools/BUILD.bazel, tools/defaults.bzl, tools/postinstall/apply-patches.js
In the past, we added a workaround for https://github.com/angular/angular/issues/30586,
so that tsickle actually runs on the devmode output. We can remove this since there
is a more simpler workaround until View Engine is completely gone. Ivy is supposed
to fix this unless the output format is modified to preserve TS decorator calls.
If that would be the case (it's not at time of writing), then we can
still use the global mocking (which is not that unreasonable), or wire
up build optimizer (which would be quite complicated in Bazel).
This is a preparation change for https://github.com/angular/angular/pull/37221, but generally is useful as it simplifies the workaround.
=> build: remove devmode tsickle decorator processing workaround

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/drag-ref.ts
The events that Firefox emits when it emulates a mobile device in the dev tools are incomplete which causes an error to be thrown at the end of a drag seequence. These changes add a bit of extra logic so everything doesn't break down.
Fixes #19385.
=> fix(drag-drop): error during device emulation on firefox

src/material/schematics/ng-update/data/constructor-checks.ts, src/material/slider/slider.ts, tools/public_api_guard/material/slider.d.ts
Changes the APIs that were marked as deprecated for v10 in the slider.
* The `_ngZone` and `_document` parameters in the `MatSlider` constructor are now required.
=> refactor(slider): change deprecated APIs for version 10

src/cdk/clipboard/copy-to-clipboard.ts, src/cdk/schematics/ng-update/data/output-names.ts, tools/public_api_guard/cdk/clipboard.d.ts
Changes the APIs that have been marked as deprecated for v10.
* The `copied` event from `cdkCopyToClipboard` has been renamed to `cdkCopyToClipboardCopied`.
* The `_ngZone` parameter in the `CdkCopyToClipboard` constructor is now required.
=> refactor(clipboard): remove deprecated APIs for version 10

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/drop-list-ref.ts
In #19116 some logic was added so that we use `insertBefore` when an item is entering from the top, rather than `appendChild`. The problem is that an error will be thrown if the first item in the drop list isn't a sibling of the first draggable element.
Fixes #19359.
=> fix(drag-drop): error when item enters from the top and list has an intermediate child

src/material/dialog/dialog-container.ts, src/material/dialog/dialog.spec.ts
In #18826 we added some logic to recapture focus if the user clicks on a disabled backdrop. The problem is that we didn't account for the `autoFocus` config option.
Fixes #19350.
=> fix(dialog): focus recapturing not accounting for autoFocus option

src/cdk/table/sticky-styler.ts, src/cdk/table/table.spec.ts
The loop that sticks headers and footers is run in reverse for footers. The problem is that we were only reversing the order of the elements, but not the sticky states which resulted in them being flipped. E.g. setting the last row to be sticky would actually stick the first one.
Fixes #19311.
=> fix(table): incorrectly sticking multiple footer rows

src/google-maps/map-anchor-point.ts, src/google-maps/map-info-window/map-info-window.spec.ts, src/google-maps/map-info-window/map-info-window.ts, src/google-maps/map-marker/map-marker.ts, src/google-maps/public-api.ts, tools/public_api_guard/google-maps/google-maps.d.ts
Currently the info window is limited only to markers, but the API allows for any kind of `MVCObject`. These changes expand the type so that we can make it more flexible in the future.
cc @mbehrlich
=> fix(google-maps): allow different anchor objects for info window

src/cdk/schematics/testing/index.ts, src/cdk/schematics/testing/test-library.ts, src/cdk/schematics/testing/test-project.ts, src/material/schematics/ng-add/index.spec.ts, src/material/schematics/ng-add/setup-project.ts
Skip app related ng-add steps when working with library projects
close #19156
=> fix(ng-add): ng add @angular/material fails in library projects

src/material-experimental/mdc-theming/_all-theme.scss
The MDC Web slider is going to be basically get rewritten. Removing the current CSS from the all-theme until we can update this to the new version.
=> fix(material-experimental/mdc-slider): remove slider theme from all-theme

tools/markdown-to-html/BUILD.bazel, tools/markdown-to-html/docs-marked-renderer.spec.ts, tools/markdown-to-html/tsconfig.json
These tests are meant to simply document and verify the existing
behavior of the DocsMarkedRenderer. They aren't necessarily meant to be
a good example of unit testing best-practices.
A characterization test "is a means to describe (characterize) the actual behavior of an existing piece of software, and therefore protect existing behavior of legacy code against unintended changes via automated testing."
https://en.wikipedia.org/wiki/Characterization_test
=> test: add characterization tests for DocsMarkedRenderer

src/material/schematics/ng-update/data/constructor-checks.ts, src/material/sort/sort-header.ts, tools/public_api_guard/material/sort.d.ts
Cleans up the APIs that were marked as deprecated for v10.
* The `_focusMonitor` and `_elementRef` parameters in the `MatSortHeader` constructor are now required.
=> refactor(sort): change deprecated APIs for version 10

src/material/button-toggle/button-toggle.spec.ts, src/material/button-toggle/button-toggle.ts, src/material/schematics/ng-update/data/class-names.ts, tools/public_api_guard/material/button-toggle.d.ts
Removes the `button-toggle` APIs that were deprecated back in 8, but were never removed.
* `MatButtonToggleGroupMultiple` has been removed. Use `MatButtonToggleGroup` instead.
=> refactor(button-toggle): remove deprecated APIs for version 10

src/cdk/testing/protractor/protractor-element.ts, src/cdk/testing/test-element.ts, src/cdk/testing/testbed/unit-test-element.ts, src/cdk/testing/tests/test-main-component.ts, src/cdk/testing/tests/testbed.spec.ts, src/material/config.bzl, src/material/tooltip/testing/BUILD.bazel, src/material/tooltip/testing/index.ts, src/material/tooltip/testing/public-api.ts, src/material/tooltip/testing/shared.spec.ts, src/material/tooltip/testing/tooltip-harness-filters.ts, src/material/tooltip/testing/tooltip-harness.spec.ts, src/material/tooltip/testing/tooltip-harness.ts, src/material/tooltip/tooltip.ts, tools/public_api_guard/cdk/testing.d.ts, tools/public_api_guard/cdk/testing/protractor.d.ts, tools/public_api_guard/cdk/testing/testbed.d.ts, tools/public_api_guard/material/tooltip/testing.d.ts
This is redo of #16676. Adds a test harness for `mat-tooltip`, as well as an API to move the pointer away from an element, as an opposite to `TestElement.hover`.
=> feat(tooltip/testing): add test harness for mat-tooltip

package.json, yarn.lock
All of the core packages were at 10.0.0-rc.0, but the tooling ones were still on `next`. These changes align the version.
=> build: bump tooling packages to rc

src/material/autocomplete/autocomplete-trigger.ts, src/material/schematics/ng-update/data/constructor-checks.ts, tools/public_api_guard/material/autocomplete.d.ts
Changes the APIs that were marked as deprecated for v10.
* The `_viewportRuler` parameter in the `MatAutocompleteTrigger` constructor is now required.
=> refactor(autocomplete): change deprecated APIs for version 10

src/cdk/a11y/focus-trap/focus-trap.spec.ts, src/cdk/a11y/high-contrast-mode/high-contrast-mode-detector.spec.ts, src/cdk/a11y/interactivity-checker/interactivity-checker.spec.ts, src/cdk/platform/platform.ts, src/cdk/schematics/ng-update/data/constructor-checks.ts, src/material-experimental/mdc-input/input.spec.ts, src/material-experimental/mdc-slider/slider.spec.ts, src/material/checkbox/testing/shared.spec.ts, src/material/input/input.spec.ts, src/material/radio/testing/shared.spec.ts, src/material/slide-toggle/testing/shared.spec.ts, tools/public_api_guard/cdk/platform.d.ts
Changes the APIs that were deprecated for v10 in the `cdk/platform` module.
* The `_platformId` parameter in the `Platform` constructor is now required.
=> refactor(platform): change deprecated APIs for version 10

src/material/schematics/ng-update/data/constructor-checks.ts, src/material/tooltip/tooltip.ts, tools/public_api_guard/material/tooltip.d.ts
Changes an API that was marked for deprecation in v10.
* The `_hammerLoader` parameter has been removed from the `MatTooltip` constructor.
=> refactor(tooltip): change deprecated APIs for version 10

src/material/icon/icon-registry.ts, src/material/icon/icon.ts, src/material/schematics/ng-update/data/constructor-checks.ts, tools/public_api_guard/material/icon.d.ts
Changes the APIs that were marked as deprecated for v10.
* The `_location` and `_errorHandler` parameters in the `MatIcon` constructor are now required.
* The `_errorHandler` parameter in the `MatIconRegistry` constructor is now required.
=> refactor(icon): change deprecated APIs for version 10

src/cdk/a11y/focus-trap/focus-trap.ts
Fix typo in doc string for CDK FocusTrap class.
=> docs(cdk/focus-trap): fix FocusTrap class documentation typo

src/material/tooltip/testing/BUILD.bazel, src/material/tooltip/testing/shared.spec.ts
Currently the tooltip harness won't work on touch devices, because we don't simulate touch events. These changes temporarily disable the tests on unsupported devices until we can update the harness APIs.
=> test(tooltip/testing): disable tests on touch devices

src/cdk-experimental/package.json, src/cdk/package.json, src/google-maps/package.json, src/material-experimental/package.json, src/material-moment-adapter/package.json, src/material/package.json, src/youtube-player/package.json
Due to an outage with the proxy we rely on for publishing, we need
to temporarily directly publish to NPM using our own angular
credentials again.
=> build: remove wombot proxy registry from package.jsons for release

src/dev-app/dev-app/dev-app-layout.ts
Sets the desnity class on the body, rather than the layout element. We'll need this for overlay-based components that implement the density system.
=> build: set dev app density class on body

package.json, src/material-experimental/mdc-chips/chip.ts, src/material-experimental/mdc-helpers/BUILD.bazel, yarn.lock
Updates to the latest canary version of MDC and fixes the following errors:
- The chip foundation was expanded to include some events for editable chips. These are noops for now since we don't support editable chips yet.
- Some new files were added to the table that we hadn't accounted for.
=> build: update to latest MDC canary and fix errors

src/google-maps/google-map/google-map.ts, src/google-maps/map-circle/map-circle.ts, src/google-maps/map-ground-overlay/map-ground-overlay.ts, src/google-maps/map-info-window/map-info-window.ts, src/google-maps/map-marker/map-marker.ts, src/google-maps/map-polygon/map-polygon.ts, src/google-maps/map-polyline/map-polyline.ts, src/google-maps/map-rectangle/map-rectangle.ts, tools/public_api_guard/google-maps/google-maps.d.ts
Currently none of the Google Maps-related directives have an `exportAs` which makes them difficult to reference inside templates.
Fixes #19462.
=> fix(google-maps): add exportAs to all directives

src/material/slider/_slider-theme.scss
Fixes the slider's focus ring always using the accent color, instead of matching the current theme palette.
Fixes #19507.
=> fix(slider): focus ring not matching theme color

src/material/datepicker/date-range-input-parts.ts, src/material/datepicker/datepicker-input-base.ts, src/material/datepicker/datepicker-input.ts, tools/public_api_guard/material/datepicker.d.ts
Fixes a few compilation errors that only happen when the date range picker is compiled with `ViewEngine`.
=> fix(datepicker): compilation errors with ViewEngine

src/material-experimental/mdc-checkbox/checkbox.html, src/material-experimental/mdc-checkbox/checkbox.spec.ts, src/material-experimental/mdc-checkbox/checkbox.ts, src/material/checkbox/checkbox.html, src/material/checkbox/checkbox.spec.ts, src/material/checkbox/checkbox.ts, tools/public_api_guard/material/checkbox.d.ts
Passes the `aria-describedby` attribute value through to the underlying `input` element.
Fixes #19477.
=> fix(checkbox): pass aria-describedby through to input

src/material/checkbox/checkbox.scss
A while ago the `cdk-high-contrast` mixin was changed from using a media query to a class. This seems to have broken one of the selectors that render the focus indication.
Fixes #19443.
=> fix(checkbox): high contrast focus indication not working

goldens/ts-circular-deps.json, src/cdk/overlay/keyboard/overlay-keyboard-dispatcher.ts, src/cdk/overlay/overlay-reference.ts, tools/public_api_guard/cdk/overlay.d.ts
Resolves a circular dependency between a couple of the classes in `cdk/overlay`.
=> fix(overlay): resolve circular dependency

src/material-experimental/mdc-chips/chip-remove.spec.ts, src/material-experimental/mdc-chips/chip-row.ts, src/material-experimental/mdc-chips/chip.ts
Currently the MDC-based chip emits the `remove` event on any key press on the remove button which seems to have regressed in between the various version upgrades and refactors.
=> fix(material-experimental/mdc-chips): removing chip on any key press

src/material-experimental/mdc-radio/radio.ts, src/material/radio/radio.ts, tools/public_api_guard/material/radio.d.ts
Currently the MDC radio button doesn't extend the Material one in order to avoid bringing in unecessary code. The problem is that the MDC button group still has a hard reference to the Material `MatRadioButton` which means that we'll likely end up importing it anyway.
These changes move the button group code into a base class and remove the references to the Material button.
=> fix(material-experimental/mdc-radio): avoid hard references to base material components

WORKSPACE, package.json, test/benchmarks/material/checkbox/BUILD.bazel, test/benchmarks/material/checkbox/app.module.ts, test/benchmarks/material/checkbox/checkbox.perf-spec.ts, yarn.lock
* Set up components repo to use dev-infra benchmarking tools
* Create first set of benchmark tests for mat-checkbox
This change depends on two changes to angular/angular.
1. PR [#36800](https://github.com/angular/angular/pull/36800)
2. The resolution of Issue [#36986](https://github.com/angular/angular/issues/36986)
Until those changes have been made, the current workaround is to
1. Checkout the working branch for PR [#36800](https://github.com/angular/angular/pull/36800)
2. Fix Issue [#36986](https://github.com/angular/angular/issues/36986)
3. Run `yarn bazel build //dev-infra:npm_package.pack` to create a local version of dev-infra
This workaround allows us to change the package.json in angular/components to depend on the files from this locally published version of dev-infra.
=> feat(benchmarks): setup for benchmarking components

src/components-examples/material/menu/menu-nested/menu-nested-example.html, src/components-examples/material/menu/menu-overview/menu-overview-example.html, src/components-examples/material/menu/menu-position/menu-position-example.html, src/components-examples/material/tabs/tab-group-align/tab-group-align-example.html, src/components-examples/material/tabs/tab-group-animations/tab-group-animations-example.html, src/components-examples/material/tabs/tab-group-custom-label/tab-group-custom-label-example.html, src/components-examples/material/tabs/tab-group-dynamic-height/tab-group-dynamic-height-example.html, src/components-examples/material/tabs/tab-group-lazy-loaded/tab-group-lazy-loaded-example.html, src/components-examples/material/tabs/tab-nav-bar-basic/tab-nav-bar-basic-example.html, src/material/chips/chips.md, src/material/menu/menu.md, src/material/tabs/tabs.md
Remove static code snippets in material docs and replace them with embedded examples in compact view.
Add regions in component examples.
=> refactor: update snippets/embedded example comments in material docs md to reflect new API (chips, menu, tabs)

tools/markdown-to-html/docs-marked-renderer.spec.ts, tools/markdown-to-html/docs-marked-renderer.ts
Remove trailing comma in example comment. 
Replace differentiating between new and old API with regex match instead of `.startsWith('{')`
=> fix(markdown-to-html): use regex to match new API

src/material-experimental/mdc-button/_button-base.scss, src/material-experimental/mdc-helpers/_focus-indicators.scss, src/material/core/_core.scss, src/material/core/focus-indicators/_focus-indicators.scss, src/material/datepicker/calendar-body.scss, src/material/expansion/expansion-panel-header.scss, src/material/expansion/expansion-panel.scss, src/material/list/list.scss, src/material/sort/sort-header.scss
* Just as every `.mat-ripple` is [positioned](https://github.com/angular/components/blob/master/src/material/core/ripple/_ripple.scss#L15) in order to create an easy API for developers, every `.mat-focus-indicator` should be positioned. This way, when developers add the class `.mat-focus-indicator` to their own custom focusable elements they do not also need to position the element.
* As a result of positioning every `.mat-focus-indicator`, a few components that set `position: absolute` on the associated element need to have their specificity bumped. 
* In testing this change, I fixed a few bugs as a result of https://github.com/angular/components/pull/19304 (comments inline).
=> bug(focus indicators): Focus indicators are now positioned.

.github/CODEOWNERS, .ng-dev/config.ts, .ng-dev/github.ts, .ng-dev/merge.ts
We recently updated the shared dev-infra package to the latest
version (in order to bring in the benchmark utils), but this
actually broke the merge script because dev-infra landed a change
on how the configuration is loaded.
Previously, the configuration has been loaded from a single file
at project root, but now dev-infra loads it from a dedicated
dev-infra folder. This has been done that way to allow for dedicated
configuration files for individual `ng-dev` command parts.
=> build: switch to dev-infra configuration directory

src/material-experimental/mdc-slide-toggle/slide-toggle.scss
The MDC slide toggle's element with the focus indicator should always be absolutely positioned. Right now, its a race condition whether it is (currently broken in Google) depending on load order since they have the same specificity
=> fix(material-experimental/mdc-slide-toggle): fix focus indictor position

src/material-experimental/mdc-menu/menu.scss
Fixes the MDC menu item not having side padding anymore. It seems like this broke after the update to the latest canary version, because the padding was moved into a different mixin.
=> fix(material-experimental/mdc-menu): missing padding after latest canary release

tools/postinstall/@angular_bazel_ivy_flat_module.patch, tools/postinstall/apply-patches.js
Due to our weird cyclic dependency with the framework repository,
we need to apply changes from https://github.com/angular/angular/pull/36971
before the PR can actually land in framework. This is because the
changes of that PR fail in the components repo job as we apply patches
that conflict with the new changes.
At the same time though, we cannot make the components repo compatible
until the framework PR landed. We work around this as usually done, by
applying the upstream changes through a patch. Then we can resolve
conflicts and the framework PR can land. Eventually we can then
remove the patch again from the components repo.
=> build: apply angular bazel ng_module fix to unblock framework

src/components-examples/material/autocomplete/autocomplete-optgroup/autocomplete-optgroup-example.html, src/components-examples/material/autocomplete/autocomplete-simple/autocomplete-simple-example.html, src/components-examples/material/datepicker/datepicker-overview/datepicker-overview-example.html, src/material/autocomplete/autocomplete.md, src/material/datepicker/datepicker.md
Remove static code snippets in material docs and replace them with embedded examples in compact view.
Add regions in component examples.
=> refactor: update snippets/embedded example comments in material docs md to reflect new API (autocomplete, datepicker, and menu)

src/youtube-player/youtube-player.ts
The logic that lazily binds event listeners to the YouTube player was waiting for the player to be done initializing which is problematic if we want to bind the `onReady` listener since the event has already happened by the time we've bound it. These changes move the event binding logic earlier in the process.
Fixes #19408.
=> fix(youtube-player): binding some event listeners too late

.circleci/config.yml
Surprisingly with the switch to Ivy, we lost our infrastructure
that ensures View Engine AOT compatibility. View Engine compiler
is sometimes slighlty stricter in AOT as its pre-compiled factories
are in external classes. This requires variables to be "public" when
they are referenced in a template. In Ivy, these properties could
actually be `protected` or `private` too.
We already run tests against View Engine, but not in AOT. This is
because View Engine compiler does not process un-exported test classes.
In the future, with Ivy-only, we can run tests in AOT mode.
=> build: add job that ensures view engine AOT compatibility

src/cdk/a11y/a11y.md
Adds a note to the docs mentioning that `cdkFocusInitial` won't do anything inside the focus trap directive, unless `cdkTrapFocusAutoCapture` is enabled.
Fixes #19475.
=> docs(a11y): add note about cdkFocusInitial inside focus trap directive

WORKSPACE, scripts/run-component-tests.js, tools/defaults.bzl
Switches the chromium version provided in the shared dev-infra
package. This gives us better control over used versions, and we
get RBE optimizations that have been applied to these browsers.
This also fixes that there is no Firefox test target for standalone
web test suites that do not rely on Angular. e.g. `coercion`.
Closes #19543.
=> build: switch to chromium provided in dev-infra package

src/cdk/testing/protractor/protractor-element.ts, src/cdk/testing/test-element.ts, src/cdk/testing/testbed/unit-test-element.ts, src/cdk/testing/tests/protractor.e2e.spec.ts, src/cdk/testing/tests/testbed.spec.ts, src/material/input/testing/BUILD.bazel, src/material/input/testing/input-harness.ts, src/material/input/testing/shared.spec.ts, tools/public_api_guard/cdk/testing.d.ts, tools/public_api_guard/cdk/testing/protractor.d.ts, tools/public_api_guard/cdk/testing/testbed.d.ts
The `setValue` method of the input harness is set up so that it types out the value in the input. This won't work for inputs that don't respond to typing (e.g. `color`). These changes add an extra call that also sets the `value` property of the input, on top of typing into it.
Fixes #18790.
Note: not sure whether the change to the `TestElement` signature needs to be made optional first.
=> fix(input/testing): unable to set the value of inputs that don't respond to typing

src/cdk/a11y/focus-monitor/focus-monitor.ts, src/material/button-toggle/button-toggle.ts, src/material/button/button.spec.ts, src/material/button/button.ts, src/material/checkbox/checkbox.ts, src/material/expansion/expansion-panel-header.ts, src/material/input/input.ts, src/material/menu/menu-item.ts, src/material/slider/slider.ts, src/material/sort/sort-header.ts, src/material/stepper/step-header.ts, src/material/tabs/tab-nav-bar/tab-nav-bar.ts, src/material/tooltip/tooltip.ts, tools/public_api_guard/cdk/a11y.d.ts, tools/public_api_guard/material/button-toggle.d.ts, tools/public_api_guard/material/button.d.ts, tools/public_api_guard/material/expansion.d.ts, tools/public_api_guard/material/input.d.ts, tools/public_api_guard/material/menu.d.ts, tools/public_api_guard/material/slider.d.ts, tools/public_api_guard/material/sort.d.ts, tools/public_api_guard/material/stepper.d.ts, tools/public_api_guard/material/tabs.d.ts, tools/public_api_guard/material/tooltip.d.ts
A while ago event delegation was implemented for the focus monitor which has some special behavior where it has to bind its events to the closest shadow root in order for them to work correctly. The problem is that a lot of our `FocusMonitor.focus` calls are very early in the component lifecycle which means that might not have been put into the shadow DOM yet. These changes move the `monitor` calls to `ngAfterViewInit` to resolve the issue.
Fixes #19414.
=> fix: focus monitor-based styles not working in some cases inside shadow dom

WORKSPACE, scripts/run-component-tests.js, src/material-experimental/mdc-menu/menu.scss, tools/defaults.bzl
This reverts commit b4d085240f0b5eca2675cbddc93c405cfd099ded in the `9.2.x` branch. This commit relied on a more recent version of the dev-infra package that is currently not installed in `9.2.x`. i.e. the new browser repositories for the dev-infra package are not configured or available in the installed dev-infra package version.
Also reverts https://github.com/angular/components/commit/771b4ba14d28fd4f8adc65790b566396f3e87b84 as that one relied on a MDC version update that is not part of the patch branch.
=> build: fix ci failures in patch branch

src/material/menu/menu-panel.ts, src/material/menu/menu-trigger.ts, src/material/menu/menu.spec.ts, src/material/menu/menu.ts, tools/public_api_guard/material/menu.d.ts
Required for GMDC, which needs to automatically add a CSS class to the overlay menu using injected options
=> feat(menu): add input to add overlay pane classes

.ng-dev/merge.ts
Updates the merge script temporarily so that `target: patch`
PRs are merged into the RC branch. We are currently revisiting
labeling/branching, and once this is finalized, we can clean
this up. For now though, we want to not put the burden of
manually cherry-picking onto the caretaker.
=> build: update merge script temporarily to merge into rc branch

src/material-experimental/mdc-chips/chip-row.spec.ts, src/material-experimental/mdc-chips/chip-row.ts, src/material-experimental/mdc-chips/chip.ts
Chips are being deleted when the user navigates through an MDC backed MatChipGrid using the arrow keys. Key events on matChipRemove directives are handled within MatChip if the keycode is in a HANDLED_KEYS array. MatChipRow mistakenly overrides that array with all keys that it handles (including the arrow keys), when that field's only actual use is for MatChip to determine what keys should be handled in interactions from matChipRemove.
This PR removes that override and renames HANDLED_KEYS to REMOVE_ICON_HANDLED_KEYS to make it more clear to subclasses what overriding it would mean.
Verified that the fix works in the dev app and with a new test.
=> Fix arrow key navigation deleting mdc-chip-rows.

.bazelrc, scripts/circleci/bazel/setup-remote-execution.sh
By default, we have set up a remote cache for local development that is read-only
This seems like a leftover from our initial http caching where RBE was not enabled yet.
Nowadays, we use a different remote cache when RBE is enabled, so the one that
is configured for local development is actually never updated, except if an Angular
team members has credentials provided, and has the upload of results enabled.
Generally, enabling remote caching has the potential of slowing down local development
(especially when there are lot of misses) and we should only enable it as part of remote
build execution.
This also mitigates a bug in Bazel where restored remote action inputs can break if their
relative execroot path contains a space. This is the case for chromium on macOS, where
the browser test …
=> build: disable stale remote http cache for local development

src/components-examples/material/stepper/stepper-errors/stepper-errors-example.html, src/material/stepper/stepper.md
The `stepper-errors` example was set up using a linear stepper which doesn't allow users to move to a different step if the current one is invalid which means that the user doesn't have a way of seeing the error state.
These changes make the stepper non-linear, expand the example description to explain how the error state works, and add some text so users know what to do in order to see the error state.
Fixes #19407.
=> docs(stepper): error state example not set up correctly

src/material-experimental/mdc-helpers/_focus-indicators.scss
In order to support density scaling, the MDC checkbox and radio button have `border-radius: 50%` on their ripple element which is also used as the strong focus indicator. Since the indicator is a square, it'll be clipped, unless we also make it into a circle.
For reference, here's what the circular indicators look like:
cc @zelliott
=> fix(material-experimental): strong focus indicator clipped in checkbox and radio button

angular-tsconfig.json
Currently our NGC postinstall for Bazel also runs against the
dev-infra package. This results in a small slow-down and is
simply unnecessary given that this does not represent
a dependency of interest for `ng_module` compilations.
=> build: postinstall should not process dev-infra package

tslint.json
Enables license header linting for the benchmark tests
folder. This seems needed because in order to sync these files
into g3, the license header must be correct/added.
Related to #19596.
=> build: enable license header linting for benchmark tests

.circleci/config.yml, scripts/circleci/notify-slack-job-failure.sh
Whenever a CI job fails in a non-PR build, the failure will be
reported to the `#components-ci-failures` Slack channel.
Obviously this can become very verbose as it will report every
individual CI job, but that cannot be improved at the time of
writing, as CircleCI does not support post-workflow logic.
Interestingly there is also a legacy option in the old CircleCI UI
for Slack notifications, but for the sake of not relying on that,
we use the new recommended way of controlling notifications inside
the actual CircleCI configuration.
We want to do this as patch/rc branches can quickly become red due to
an unfortunate composition of cherry-picked commits. In those cases
we need to be notified as those failures should be resolved, so that
releases can be cut without issues, and that the …
=> build: setup slack notifications for circleci jobs

guides/using-component-harnesses.md
`MatSelect` -> `MatSelectHarness` when querying the harness
=> docs: fix MatSelect example

tools/postinstall/apply-patches.js
Sometimes we need to change existing postinstall patches. This
requires a cleanup of the currently installed node modules, but
there is no good warning/messaging. We improve this with this
commit by detecting such stale patches and prompting for
automatic retry with cleaned up node modulesbuild: option to
automatically retry postinstall patches
Sometimes we need to change existing postinstall patches. This
requires a cleanup of the currently installed node modules, but
there is no good warning/messaging. We improve this with this
commit by detecting such stale patches and prompting for automatic
retry with cleaned up node modules.
Note: Please clean up your node modules after this change. This needs to
still happen manually once, so that we can keep track of applied
patch versions and …
=> build: improve postinstall patches with better messaging and prompt

src/components-examples/material/datepicker/date-range-picker-comparison/date-range-picker-comparison-example.html, src/components-examples/material/datepicker/date-range-picker-forms/date-range-picker-forms-example.html, src/components-examples/material/datepicker/date-range-picker-overview/date-range-picker-overview-example.html, src/components-examples/material/datepicker/date-range-picker-selection-strategy/date-range-picker-selection-strategy-example.html, src/dev-app/datepicker/datepicker-demo.html, src/material/datepicker/date-range-input-parts.ts, src/material/datepicker/date-range-input.html, src/material/datepicker/date-range-input.scss, src/material/datepicker/date-range-input.spec.ts, src/material/datepicker/date-range-input.ts, src/material/datepicker/datepicker.md, tools/public_api_guard/material/datepicker.d.ts
- Fixes the date range picker's placeholder not behaving correctly when it's placed inside of a form field with the `legacy` appearance.
- Fixes several range picker examples that were setting `matInput` on `matStartDate` and `matEndDate` which isn't required.
=> fix(datepicker): placeholder not behaving correctly in legacy form field

package.json
The `bazel:format-lint` script was removed, but it's still referenced in the `lint` script.
=> build: remove deleted script from lint

.circleci/config.yml
The path to the Slack notification script seems to be incorrect.
=> build: fix wrong directory for notification script

scripts/circleci/notify-slack-job-failure.sh
Looks like we currently incorrectly skip notifications when the `CIRCLE_PR_NUMBER`
variable is _not_ defined. It should be the other way around though, and we want
to only skip notifications when this variable is defined/not-null (i.e. skip notifications for PRs that don't have access to the webhook secret variable anyway).
=> build: ci failure notifications accidentally skipped

src/dev-app/theme.scss
In #19411 the MDC slider theme was dropped from the all themes mixin since the current slider implementation will be replaced eventually which also broke the MDC slider demo. These changes add back the slider theme only to the dev app so that we can still test it since this is still code that we're releasing to npm.
=> build: fix mdc slider demo

src/material-experimental/mdc-button/_button-theme.scss, src/material-experimental/mdc-checkbox/_checkbox-theme.scss, src/material-experimental/mdc-chips/_chips-theme.scss, src/material-experimental/mdc-radio/_radio-theme.scss, src/material-experimental/mdc-slide-toggle/_slide-toggle-theme.scss, src/material-experimental/mdc-table/_table-theme.scss, src/material-experimental/mdc-tabs/_tabs-theme.scss
Includes a feature target when invoking the MDC density mixins. This is consistent with what we're doing everywhere else and could help us exclude some unwanted styles.
=> refactor(material-experimental): include feature targets in density mixins

src/cdk-experimental/popover-edit/edit-event-dispatcher.ts, src/cdk/a11y/focus-trap/configurable-focus-trap.spec.ts, src/cdk/a11y/focus-trap/event-listener-inert-strategy.spec.ts, src/cdk/overlay/overlay-config.ts, src/cdk/table/sticky-styler.ts, src/google-maps/google-map/google-map.ts, src/material-experimental/mdc-chips/chip-grid.ts, src/material-experimental/mdc-progress-bar/progress-bar.spec.ts, src/material/progress-bar/progress-bar.spec.ts, src/material/select/select.spec.ts, src/material/tooltip/tooltip.spec.ts, tools/public_api_guard/google-maps/google-maps.d.ts, tslint.json
Adds some linting that we consistently use `T[]` instead of `Array<T>`.
=> build: enforce consistent array types

src/material/datepicker/date-range-input-parts.ts, src/material/datepicker/date-range-input.spec.ts, src/material/datepicker/datepicker-input-base.ts
The date range picker inputs are set up so that they only respond to events outside of themselves so that we don't trigger duplicate events. In some cases this can be a problem, because the input can end up ignoring its own call to update the CVA value, causing it to be out of sync. These changes add an extra call that ensures that the model and CVA values are always in sync.
Fixes #19588.
=> fix(datepicker): date range overriding model value if both fields are changed at the same time

goldens/size-test.yaml, integration/size-test/material/radio/BUILD.bazel, integration/size-test/material/radio/without-group.ts, src/material-experimental/mdc-radio/radio.ts, src/material/radio/radio.ts, tools/public_api_guard/material/radio.d.ts
The Angular Material `MatRadioButton` component currently optionally
injects the `MatRadioGroup`. This causes the `MatRadioGroup` implementation
to be always retained in application bundles.
This is problematic as the use of radio groups is not always required.
i.e. it's valid to use a standalone radio button. In those cases, we do
not want to retain the radio group implementation unnecessarily.
This has always been an issue, but the issue became more significant
in Ivy where component factory and definitions are attached directly
to the `MatRadioGroup` class (resulting in a more significant size increase).
We fix this by using a lightweight token for injecting the parent
radio group optionally. This solves the retention issue if a standalone
radio button is used.
=> refactor: use lightweight token for injecting radio group

goldens/size-test.yaml, integration/size-test/material/menu/BUILD.bazel, integration/size-test/material/menu/without-lazy-content.ts, src/material/menu/menu-content.ts, src/material/menu/menu.ts, tools/public_api_guard/material/menu.d.ts
Angular Material supports lazy content for menus. It does this
by querying for the `MatMenuContent` directive in the `MatMenu`
component. This is problematic though as it always causes
`MatMenuContent` to be retained as its used as actual query predicate
token.
To solve this, we use a lightweight injection token for querying
the lazy content (if present). This optimizes applications using
the Angular Material menu without lazy content.
=> refactor: use lightweight token for lazy menu content

goldens/size-test.yaml, integration/size-test/material/datepicker/range-picker/BUILD.bazel, integration/size-test/material/datepicker/range-picker/without-form-field.ts, src/material/datepicker/date-range-input.ts
The date range picker could be used outside the `MatFormField`
component in practice. Right now though, the date-picker input
always has a hard-reference on the `MatFormField` component, causing
it to be retained. This would be the same in View Engine, but with
Ivy this signifies a larger size issue as factories/definitions are
directly attached to the component.
To allow for better tree-shaking / optimizations, we use the form-field
light-weight injection token, so that the date range picker can be used
outside of a form-field with minimal cost.
=> refactor: use light-weight token for form-field in range-picker input

goldens/size-test.yaml, integration/size-test/material/button-toggle/BUILD.bazel, integration/size-test/material/button-toggle/standalone.ts, src/material/button-toggle/button-toggle.ts, tools/public_api_guard/material/button-toggle.d.ts
The `MatButtonToggleGroup` component is not always used in applications. e.g.
it's an optional part, and standalone button toggles are totally valid.
Currently though, we always reference the `MatButtonToggleGroup` component
directly as a value, and it will be retained in applications regardless
of the usage.
We can improve this by providing a light-weight injection token for
the button-toggle group that we can then use DI injection to avoid
full retention of the class.
This obviously was already an issue in View Engine too, but it became
significantly worse in Ivy as factories are now directly attached to
the component class.
=> refactor: provide and use light-weight token for button-toggle group 

goldens/size-test.yaml, integration/size-test/material/autocomplete/BUILD.bazel, integration/size-test/material/autocomplete/without-optgroup.ts, integration/size-test/material/select/BUILD.bazel, integration/size-test/material/select/without-optgroup.ts, src/material/autocomplete/autocomplete.ts, src/material/core/option/optgroup.ts, src/material/core/option/option.ts, src/material/select/select.ts, tools/public_api_guard/material/core.d.ts
The `MatOptgroup` component is not always used in applications. e.g.
it's an optional part of the autocomplete or select. Currently though,
we always reference the `MatOpgroup` component directly at runtime,
and it will be retained in applications regardless of the usage.
We can improve this by providing a light-weight injection token for
the optgroup that we can then use in queries or optional DI injection.
This obviously was already an issue in View Engine too, but it became
significantly worse in Ivy as factories are now directly attached to
the component class.
=> refactor: use light-weight token for optgroup to optimize bundle size

goldens/ts-circular-deps.json, src/cdk-experimental/menu/BUILD.bazel, src/cdk-experimental/menu/menu-bar.spec.ts, src/cdk-experimental/menu/menu-bar.ts, src/cdk-experimental/menu/menu-group.spec.ts, src/cdk-experimental/menu/menu-group.ts, src/cdk-experimental/menu/menu-item-interface.ts, src/cdk-experimental/menu/menu-item.ts, src/cdk-experimental/menu/menu.spec.ts, src/cdk-experimental/menu/menu.ts
The MenuBar and Menu pattern allows for MenuItems which have the
menuitemcheckbox or menuitemradio roles. This implements the grouping
logic for, menuitemradio which ensures that sibling items within a
CdkMenu or CdkMenGroup are logically connected and only one can be
checked. It also implements the logic for menuitemcheckbox. Further it
implements the logic for emitting checked events for elements marked
menuitemcheckbox and menuitemradio from their enclosing groups.
-----
Note that I opted not to allow the disabled property on `CdkMenu` and `CdkMenuGroup` since this follows more in line with `mat-menu`, and how I interpreted the pattern. However if we decide to implement this functionality it can be easily added with a followup pr.
=> feat(cdk-experimental/menu): Implement grouping logic for menuitems

.github/CODEOWNERS, src/cdk-experimental/config.bzl, src/cdk-experimental/listbox/BUILD.bazel, src/cdk-experimental/listbox/index.ts, src/cdk-experimental/listbox/listbox-module.ts, src/cdk-experimental/listbox/listbox.ts, src/cdk-experimental/listbox/public-api.ts
Created directory for listbox in cdk-experimental and created empty files that will eventually contain the listbox and listbox option directives.
=> CdkListbox file skeleton

src/material-experimental/mdc-chips/chips.scss
mat-chip-grid goes inside a mat-form-field, and the 4px margin on the
individual chips is causing the mat-chip-grid element to be too tall,
and thus the form field is also too tall. Give the mat-chip-grid a
negative margin so that it fits in the form field. The same thing was
done for non-mdc chips:
https://github.com/angular/components/blob/master/src/material/chips/chips.scss#L195
=> fix(material-experimental/mdc-chips) adjust margins

src/cdk-experimental/column-resize/resizable.ts, src/material-experimental/column-resize/column-resize.spec.ts, src/material-experimental/column-resize/resizable-directives/default-enabled-resizable.ts, src/material-experimental/column-resize/resizable-directives/resizable.ts
Change detection wasn't triggered when attaching the resize handle inside an `OnPush` component which prevented some event listeners from being bound and broke the resizing completely.
Fixes #19670.
=> fix(cdk-experimental/column-resize): not working inside OnPush component

tsconfig.json
Includes the integration test files under the lint rules so we can catch things like unused imports.
=> build: lint integration test files

src/components-examples/material/datepicker/date-range-picker-comparison/date-range-picker-comparison-example.html, src/components-examples/material/datepicker/date-range-picker-forms/date-range-picker-forms-example.html, src/components-examples/material/datepicker/date-range-picker-overview/date-range-picker-overview-example.html, src/components-examples/material/datepicker/date-range-picker-selection-strategy/date-range-picker-selection-strategy-example.html, src/components-examples/material/datepicker/datepicker-api/datepicker-api-example.html, src/components-examples/material/datepicker/datepicker-color/datepicker-color-example.html, src/components-examples/material/datepicker/datepicker-custom-header/datepicker-custom-header-example.html, src/components-examples/material/datepicker/datepicker-custom-icon/datepicker-custom-icon-example.html, src/components-examples/material/datepicker/datepicker-date-class/datepicker-date-class-example.html, src/components-examples/material/datepicker/datepicker-disabled/datepicker-disabled-example.html, src/components-examples/material/datepicker/datepicker-events/datepicker-events-example.html, src/components-examples/material/datepicker/datepicker-filter/datepicker-filter-example.html, src/components-examples/material/datepicker/datepicker-formats/datepicker-formats-example.html, src/components-examples/material/datepicker/datepicker-locale/datepicker-locale-example.html, src/components-examples/material/datepicker/datepicker-min-max/datepicker-min-max-example.html, src/components-examples/material/datepicker/datepicker-moment/datepicker-moment-example.html, src/components-examples/material/datepicker/datepicker-overview/datepicker-overview-example.html, src/components-examples/material/datepicker/datepicker-start-view/datepicker-start-view-example.html, src/components-examples/material/datepicker/datepicker-touch/datepicker-touch-example.html, src/components-examples/material/datepicker/datepicker-value/datepicker-value-example.html, src/components-examples/material/datepicker/datepicker-views-selection/datepicker-views-selection-example.html
Switches all of the datepicker examples to use the `fill` form field appearance, similarly to what we did in the form field examples a few months ago.
=> docs(datepicker): switch examples to non-deprecated form field appearance

src/material-experimental/mdc-menu/menu.scss
Fixes the MDC menu items not having the proper padding. This was fixed initially in #19548 and reverted by https://github.com/devversion/material2/commit/b2517961098ad93f2bbfa4f2ffe1d9a5085181a7, but it was never re-fixed.
=> fix(material-experimental/mdc-mdc): menu items missing padding

src/cdk-experimental/column-resize/column-resize.ts, src/cdk-experimental/column-resize/overlay-handle.ts, src/cdk-experimental/column-resize/resizable.ts
Replaces some usages of `ReplaySubject` with a plain `Subject` since we don't use ReplaySubject anywhere else in the codebase and in these cases it doesn't provide any benefit. This should lead to less code being imported as a result of the CDK.
=> refactor(cdk-experimental/column-resize): clean up ReplaySubject usages

src/cdk-experimental/popover-edit/lens-directives.ts
We use `keydown` to open the popover edit overlay and `keyup` to close it which can lead to situations where the user opens and closes the popup immediately. Seems to have been introduced by #18194.
For reference:
cc @kseamon
=> fix(material-experimental/popover-edit): closing instantly when opening with enter key

src/components-examples/material/badge/badge-overview/badge-overview-example.html, src/components-examples/material/badge/badge-overview/badge-overview-example.ts, src/components-examples/material/toolbar/toolbar-multirow/toolbar-multirow-example.css, src/components-examples/material/toolbar/toolbar-multirow/toolbar-multirow-example.html, src/components-examples/material/toolbar/toolbar-overview/toolbar-overview-example.html, src/material/badge/badge.md, src/material/toolbar/toolbar.md
Remove static code snippets in material docs and replace them with embedded examples in compact view.
Add regions in component examples.
=> refactor: update snippets/embedded example comments in material docs md to reflect new API (badge, toolbar)

src/components-examples/material-experimental/mdc-form-field/mdc-form-field-custom-control/example-tel-input-example.html, src/components-examples/material/form-field/form-field-custom-control/example-tel-input-example.html
The above issue is resolved directly on https://material.angular.io/components/form-field/examples
=> docs: responsiveness of form examples tab

goldens/size-test.yaml, integration/size-test/cdk/drag-drop/BUILD.bazel, integration/size-test/cdk/drag-drop/all-directives.ts, integration/size-test/cdk/drag-drop/basic.ts, src/cdk/drag-drop/directives/drag-handle.ts, src/cdk/drag-drop/directives/drag-placeholder.ts, src/cdk/drag-drop/directives/drag-preview.ts, src/cdk/drag-drop/directives/drag.ts, src/cdk/drag-drop/directives/drop-list-group.ts, src/cdk/drag-drop/directives/drop-list.ts, tools/public_api_guard/cdk/drag-drop.d.ts
Currently the `CdkDropList` directive always retains the `CdkDropListGroup`
directive. This is not desired as the drop list group is not necessarily
always used in combination with a drop list.
Additionally, the `CdkDrag` directive always retains the `CdkDragHandle`,
`CdkDragPlaceholder` and `CdkDragPreview` directives. This is neither
desired because a handle, placeholder or preview can be consumed
optionally. We should only bring those directives into applications
when actually needed.
Size measurements show that this saves around ~1.3kb if only a drop
list and `cdkDrag` is used. The downside is that we add up ~200b if
_all_ directives of the drag-drop module are used. Given the drag-drop
has a compressed size of around 45kb, the 1.3kb size improvement in
the common case should be good …
=> refactor: use lightweight token in CDK drag-drop

goldens/size-test.yaml, integration/size-test/material/expansion/BUILD.bazel, integration/size-test/material/expansion/without-accordion.ts, src/cdk/accordion/accordion-item.ts, src/cdk/accordion/accordion.ts
The `CdkAccordionItem` currently always brings in the `CdkAccordion`
class. This is not desired as an accordion item could be used
outside of a `<cdk-accordion>`. In those cases, we do not want
to retain the accordion class w/ metadata unnecessarily.
This also affects the `MatExpansionPanel` as it extends
from the `CdkAccordionItem` and therefore always brings in
the `CdkAccordion` list unnecessarily right now.
Related to #19576.
=> refactor: use lightweight token for CDK accordion 

goldens/size-test.yaml, integration/size-test/check-size.ts
Sorts the integration size-test golden lexicographically. This
should make the golden more readable.
=> build: sort integration size test golden lexicographically

src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss, src/material-experimental/mdc-form-field/form-field.ts, src/material-experimental/mdc-input/input.spec.ts
When the form field initializes, it will determine the floating label notch width if it is `outline` appearance. This is done once at initialization.
If the form field initializes with an appearance other than `outline`, it does not determine the correct width.
This change measures the correct width after the appearance is changed to `outline` and provides that input to the notched outline.
=> fix(material-experimental/form-field): fix notch width after appearance change

integration/size-test/cdk/drag-drop/all-directives.ts, integration/size-test/material/autocomplete/without-optgroup.ts, integration/size-test/material/button-toggle/standalone.ts, integration/size-test/material/datepicker/range-picker/without-form-field.ts, integration/size-test/material/menu/without-lazy-content.ts, integration/size-test/material/radio/without-group.ts, integration/size-test/material/select/without-optgroup.ts
The size tests automatically will include a bootstrap module
call. The boostrap calls in those test files are noop and
will be removed by rollup as build optimizer considers it as
a side-effect free call that is unused.
=> build: remove unused bootstrap calls in size tests

src/components-examples/material/badge/badge-overview/badge-overview-example.html
Fixes a syntax error in one of the docs that is breaking the build on master.
=> docs: fix syntax error in doc region

goldens/size-test.yaml, integration/size-test/material-experimental/mdc-chips/BUILD.bazel, integration/size-test/material-experimental/mdc-chips/basic.ts, integration/size-test/material/chips/BUILD.bazel, integration/size-test/material/chips/basic.ts, src/material-experimental/mdc-chips/chip-icons.ts, src/material-experimental/mdc-chips/chip.ts, src/material/chips/chip.ts, tools/public_api_guard/material/chips.d.ts
Currently `MatChip` always causes `MatChipAvatar`, `MatChipRemove` and
`MatChipTrailingIcon` to be retained. These are optional parts of a chip and
shouldn't be retained always. The retention of these classes wasn't noticeable
in View Engine as no factories were generated for directives. With Ivy though,
factories and definitions are generated for these directives and a size increase
is noticeable.
We should use lightweight tokens for querying of those directives. These tokens
can be considered a reference to the actual directives. That allows us to query
for these directives in content queries, or DI without the risk of retaining the
full classes w/ factories/definitions attached. 
That helps with the case where not all of the optional chip parts are used. If all
parts are used, the app …
=> refactor: use lightweight token for chip avatar, remove and trailing icon

src/material/schematics/ng-generate/navigation/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html.template, src/material/schematics/ng-generate/navigation/index.spec.ts, src/material/schematics/ng-generate/navigation/schema.json
~Please do not review as of now~
=> feat(material/schematics/navigation): enable routing option

src/material/datepicker/datepicker-input-base.ts, src/material/datepicker/datepicker.spec.ts
Fixes an issue where the datepicker wouldn't revalidate, if the user typed in something invalid and then selected a value through the calendar. This seems to have regressed after things were moved around to accommodate the date range picker.
=> fix(datepicker): not revalidating after value is changed through the calendar

src/material-experimental/mdc-list/action-list.ts, src/material-experimental/mdc-list/list-base.ts, src/material-experimental/mdc-list/list.ts, src/material-experimental/mdc-list/nav-list.ts, src/material-experimental/mdc-list/selection-list.ts
Note: still need to add support for selection list in a future PR
=> feat(material-experimental/mdc-list): add MDC foundation for action/nav list

src/components-examples/material/expansion/expansion-expand-collapse-all/expansion-expand-collapse-all-example.html, src/components-examples/material/expansion/expansion-overview/expansion-overview-example.html, src/components-examples/material/expansion/expansion-steps/expansion-steps-example.html, src/components-examples/material/stepper/stepper-editable/stepper-editable-example.html, src/components-examples/material/stepper/stepper-label-position-bottom/stepper-label-position-bottom-example.html, src/components-examples/material/stepper/stepper-optional/stepper-optional-example.html, src/components-examples/material/stepper/stepper-states/stepper-states-example.html, src/material/expansion/expansion.md, src/material/stepper/stepper.md
Remove static code snippets in material docs and replace them with embedded examples in compact view.
Add regions in component examples.
=> refactor: update snippets/embedded example comments in material docs md to reflect new API (panel, stepper)

src/components-examples/material/stepper/stepper-editable/stepper-editable-example.html
Fixes an error that's breaking master, because one of the doc regions was misspelled.
=> build: fix syntax error in docs

goldens/size-test.yaml, integration/size-test/material/select/BUILD.bazel, integration/size-test/material/select/basic.ts, integration/size-test/material/tabs/BUILD.bazel, integration/size-test/material/tabs/advanced.ts, integration/size-test/material/tabs/basic.ts, src/material/select/select.ts, src/material/tabs/tab-content.ts, src/material/tabs/tab-label.ts, src/material/tabs/tab.ts, tools/public_api_guard/material/select.d.ts
* See individual commits.
This is the last set of changes for lightweight tokens. I would consider the one for the select trigger a micro-optimization and I don't feel too confident about it, but I it's low-effort to use it there as a custom select trigger is used rarely (compared to using the standard one) I assume.
=> Use lightweight token for tab group and select trigger

.github/CODEOWNERS
Changing codeowner for components-examples/ to @andrewseguin to delegate
some reviews
=> chore: change examples codeowner

.github/CODEOWNERS
Changing codeowners to @devversion to delegate more PR reviews
=> chore: change dev/test app codeowners

src/cdk/schematics/testing/test-case-setup.ts
Angular CLI v10 generates tsconfig files with comments inside it. This
breaks our testing infrastructure for schematics that leverages
the basic `JSON.parse`. To not throw for such tsconfig files that
are parsed by our testing infrastructure, we need to use JSON5.
=> test: fix schematic test infrastructure failing with Angular CLI v10

src/cdk-experimental/menu/menu-bar.ts, src/cdk-experimental/menu/menu-item-checkbox.spec.ts, src/cdk-experimental/menu/menu-item-radio.spec.ts, src/cdk-experimental/menu/menu-item-trigger.spec.ts, src/cdk-experimental/menu/menu-item-trigger.ts, src/cdk-experimental/menu/menu-item.spec.ts, src/cdk-experimental/menu/menu-item.ts, src/cdk-experimental/menu/menu.ts
A menu may be a top level menu or a nested menu (submenu) however in the context of a menu item and
menu trigger it is just a menu. This changes the naming scheme to reflect the fact that a menu is
separate from where it opens.
=> refactor(cdk-experimental/menu): change from submenu to menu naming

src/youtube-player/youtube-player.spec.ts, src/youtube-player/youtube-player.ts, tools/public_api_guard/youtube-player/youtube-player.d.ts
We tried doing this before in #17672, but we never managed to wrap it up. These changes add support for passing in the `playerVars` parameter to the YouTube API which has some settings like autoplay and hiding the video controls.
**Note:** I'm setting it to P2, because it's something that we should've supported from the beginning and it comes up in issues once in a while.
Fixes #19267.
=> feat(youtube-player): support passing in the playerVars parameter

.circleci/config.yml
For the past year, we've had CI failures when multiple PRs
have been merged. Since we run CI for all landed commits, the
snapshot publish job runs multiple times concurrently and could
end up pushing to the snapshot repositories out of order.
This can result in conflicts when multiple jobs push artifacts
at the same time. e.g. https://circleci.com/gh/angular/components/155407.
We intend to fix this by queuing snapshot publishing across CircleCI
builds. This is done using the CircleCI API. We constantly check the
API to check that there are no previous snapshot jobs running.
Instead of implementing this logic our own, we leverage a CircleCI
orb that provides this functionality.
=> build: avoid conflicts when publishing snapshot builds

package.json, src/cdk-experimental/column-resize/column-resize.ts, src/cdk-experimental/column-resize/overlay-handle.ts, src/cdk-experimental/popover-edit/table-directives.ts, tslint.json, yarn.lock
Adds a lint rule to catch unsafe usages of `takeUntil`.
**Note:** marking as merge safe, because all the component code changes are inside `cdk-experimental`.
=> build: add linting around unsafe takeUntil usage

src/components-examples/BUILD.bazel
Syntax/spelling errors when adding comments to components examples to mark out regions aren't caught until after the PR is merged. 
To build `examples-highlighted` and `docs-content` on CI the `docs-package` tag has to be removed as `build_bazel` filters them out.
=> build: bazel_build CI check to also build docs-content and examples-highlighted

scripts/caretaking/resync-caretaker-app-prs.ts, tsconfig.json
The files under `./scripts` were being linted. Also fixes a lint error that got through.
=> build: some scripts not being linted

src/components-examples/material/select/select-custom-trigger/select-custom-trigger-example.html, src/components-examples/material/select/select-disabled/select-disabled-example.html, src/components-examples/material/select/select-error-state-matcher/select-error-state-matcher-example.html, src/components-examples/material/select/select-form/select-form-example.html, src/components-examples/material/select/select-hint-error/select-hint-error-example.html, src/components-examples/material/select/select-initial-value/select-initial-value-example.html, src/components-examples/material/select/select-multiple/select-multiple-example.html, src/components-examples/material/select/select-no-ripple/select-no-ripple-example.html, src/components-examples/material/select/select-optgroup/select-optgroup-example.html, src/components-examples/material/select/select-overview/select-overview-example.html, src/components-examples/material/select/select-panel-class/select-panel-class-example.html, src/components-examples/material/select/select-reactive-form/select-reactive-form-example.html, src/components-examples/material/select/select-reset/select-reset-example.html, src/components-examples/material/select/select-value-binding/select-value-binding-example.html
Changes all of the `mat-select` examples to use a `mat-form-field` appearance that won't be deprecated in the future.
=> docs(select): switch examples to fill appearance

src/cdk-experimental/listbox/BUILD.bazel, src/cdk-experimental/listbox/listbox.spec.ts, src/cdk-experimental/listbox/listbox.ts
Added the basic logic to keep track of a selected state of options and to toggle that state by clicking on them. The selected state of an option is tied to aria-selected. The CdkListbox also handles providing unique optionIds to its child options. Currently, logic to toggle multi-select in the listbox is not yet included, so by default the listbox has multi-select enabled. Tests were included to listbox. Feedback on testing style is appreciated.
=> feat(cdk-experimental/listbox): selection logic and testing for listbox.

src/material/core/focus-indicators/_focus-indicators.scss
For accessibility reasons, it's usually a bad idea to nest interactive elements such as buttons, additional selection controls, form fields, etc inside of Material's selection controls 
(i.e. checkbox, radio, slide toggle). In practice, it's done quite often because it's an easy way to visually align content with the selection controls' labels.
Our previous styles were set up such that if the selection control was focused, all of the focus indicators nested within that selection control would render. Instead, only the focus indicator associated with the particular selection control should be rendered. These new styles do that.
=> fix(focus indicators): Improve styles that determine when focus indicators should render on selection controls.

src/cdk/a11y/interactivity-checker/interactivity-checker.spec.ts, src/cdk/a11y/interactivity-checker/interactivity-checker.ts, tools/public_api_guard/cdk/a11y.d.ts
Adds config object to isFocusable so that it can optionally return true
even when an element is invisible. Example use case: call isFocusable
with ignoreVisibility=true to find a focusable element within a
collapsed element. If isFocusable returns true, expand the collapsed
element and focus the focusable element.
Fixes #6468.
=> feat(cdk/interactivity-checker) add config parameter to isFocusable

src/cdk/tree/control/nested-tree-control.spec.ts, src/cdk/tree/control/nested-tree-control.ts, tools/public_api_guard/cdk/tree.d.ts
The ability to track tree-node expansion via a trackBy function was added to FlatTreeControl in #18708. This PR adds the same functionality to NestedTreeControl to allow nested trees the ability to also specify an alternative method of tracking a node's expansion status.
=> feat(cdk/tree): add trackBy functionality to NestedTreeControl

src/material/tree/data-source/flat-data-source.ts, tools/public_api_guard/material/tree.d.ts
The ability to track tree-node expansion via a `trackBy` function was added to FlatTreeControl in #18708. It's currently not feasible to use this in combination with MatTreeFlattener or MatTreeFlatDataSource, as they don't support the additional type variable in FlatTreeControl. This PR adds the additional type variable to these classes in a similar manner to how they were added to FlatTreeControl.
=> fix(tree): allow use of FlatTreeControl's trackBy function in MatTreeFlatDataSource and MatTreeFlattener

src/material/datepicker/date-range-input.spec.ts, src/material/datepicker/date-range-input.ts
The date range input wasn't emitting to its `stateChanges` stream when typing in the sub-inputs which meant that in some cases the view state was out of sync. These changes add an extra call to ensure that everything is synced up.
The issue manifests itself in one of the live examples:
=> fix(datepicker): label state not being updated in some cases

src/material/datepicker/datepicker-input-base.ts, src/material/datepicker/datepicker.spec.ts
Currently we only mark the datepicker's `ControlValueAccessor` as dirty if the value changed as a result of the user typing something in. The problem is that typing in an invalid value is parsed to `null` which is the same as the default value, causing it not to be marked as dirty. One small complication here that I've added a test for is that we shouldn't be dispatching change events when typing in invalid values.
Fixes #19726.
=> fix(datepicker): not marking as dirty when invalid value is typed in

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/drag-ref.ts
We have some logic to clone the `canvas` elements inside the drag preview, but the process that transfers the content can throw if the canvas is invisible. These changes add a try/catch to prevent the entire process from breaking down.
=> fix(drag-drop): error when cloning 0x0 canvas

src/material/datepicker/date-range-input.scss
We use `color: transparent` to hide the separator text, but browsers will still show it in high contrast mode. These changes use `opacity` instead.
=> fix(datepicker): range input separator not hidden in high contrast mode

src/material/form-field/form-field.ts
Some older versions of Edge will throw an error due to the way we were iterating over an `HTMLCollection`. This is actually something that TS throws a compilation error for, but we didn't catch it, because the variable was being inferred as `any`.
Fixes #17810.
=> fix(form-field): error in older versions of edge

goldens/ts-circular-deps.json, src/material/core/ripple/ripple-ref.ts, src/material/core/ripple/ripple-renderer.ts, src/material/core/ripple/ripple.spec.ts, src/material/core/ripple/ripple.ts, tools/public_api_guard/material/core.d.ts
Moves some types around in order to avoid a circular dependency between the ripple renderer and ripple ref.
=> refactor(core): avoid circular dependency in ripples

src/cdk/a11y/focus-trap/focus-trap.spec.ts, src/cdk/a11y/focus-trap/focus-trap.ts, tools/public_api_guard/cdk/a11y.d.ts
Currently the `cdkTrapFocusAutoCapture` is only checked once on init. These changes make it so that it's respected after initialization as well.
Fixes ##19664.
=> fix(a11y): focus trap directive not capturing focus if auto capture input is set after init

src/cdk/a11y/key-manager/list-key-manager.spec.ts, src/cdk/a11y/key-manager/list-key-manager.ts
Currently we emit the `ListKeyManager.change` event if the active index changes, but the problem is that the list could be swapped out, resulting in a new item at the same index. These changes switch to using the item reference to determine whether we need to emit the event.
Fixes #19661.
=> fix(a11y): list key manager not emitting change event if new item is added to active index

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/drag-ref.ts
Initially we didn't handle updating the item position if scrolling happens during a drag, because dragging was blocked. Eventually we unblocked dragging and added auto scrolling, but we only managed the dragged position when an item is inside a drop list.
These changes add some code to also manage scrolling inside a freely draggable item.
=> fix(drag-drop): update free drag position on scroll

src/material/progress-spinner/testing/progress-spinner-harness.ts, src/material/progress-spinner/testing/shared.spec.ts
The progress spinner has two variations: `mat-progress-spinner` and `mat-spinner`, but the test harness was only accounting for the former.
Fixes #19649.
=> fix(progress-spinner/testing): harness selector not matching mat-spinner selector

src/material/input/_input-theme.scss
The color selectors in the input theme were too broad which means that they won't work correctly if themes are nested. The issue can be reproduced by placing a form field inside a tab group with an `accent` palette. These changes fix the issue by making the selector more specific.
=> fix(input): incorrectly handling nested themes

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/drop-list-ref.ts
The drop list has some logic that doesn't allow a swap to occur if the items being swapped are the same as the ones in the previous swap and the direction of the user's pointer hasn't changed. This is set up so that we don't trigger a swap for every pixel, if the user's pointer lands on a different item after the previous swap is done.
The above-mentioned logic can be problematic if the user takes an item from the middle, drags it out of the list and then inserts it at the end while dragging upwards. In this case the list won't allow the swap, because the item is the same as the one in the previous swap and the pointer's direction hasn't changed.
These changes resolve the issue by preventing the swap only if the user's pointer landed on the same item after the previous swap was finished. …
=> fix(drag-drop): sometimes incorrectly swapping items at the ends of the list

src/cdk/scrolling/fixed-size-virtual-scroll.ts, src/cdk/scrolling/virtual-scroll-viewport.spec.ts
FixedSizeVirtualScroll rendered range is not correct when going from a large list to a smaller list.
I've checked MR #19030 by @crisbeto with the modified test case but it fails anyway.
One of the main problems is in `firstVisibleIndex` that it's not correct anymore when the list shrinks to a size smaller then the current scroll position, in fact the following code causes `newRange.end` < `newRange.start`:
```ts
if (expandEnd > 0) {
newRange.end = Math.min(dataLength, newRange.end + expandEnd);
newRange.start = Math.max(0,
Math.floor(firstVisibleIndex - this._minBufferPx / this._itemSize));
}
```
Unit test changes:
- Removed a wrong `triggerScroll(viewport)` on `should handle dynamic item array`: user doesn't need to scroll the view to see what changed
- Added some style to test cases to …
=> fix(cdk/scrolling): fixed-size-virtual-scroll wrong range and position when items length changes and current scroll is greater than new data length

src/material/sidenav/drawer.spec.ts, src/material/sidenav/drawer.ts, tools/public_api_guard/material/sidenav.d.ts
Currently we do not restore focus properly when a drawer is closed
through backdrop click. This is because we only restore focus when
an element inside the drawer is focused before closing. This is not
the case when the backdrop is clicked, as the focus is usually
redirected to the `document.body` element.
Fixes #17749.
=> fix(sidenav): restore focus if drawer is closed through backdrop click

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/directives/drag.ts, src/cdk/drag-drop/drag-ref.ts
Fixes calling `CdkDrag.getPlaceholderElement` returning undefined if it's called in the `cdkDragStarted` event.
Fixes #19457.
=> fix(drag-drop): placeholder element not available in started event

goldens/ts-circular-deps.json, src/cdk/schematics/testing/test-case-setup.ts
Changes an import in order to avoid a ciruclar dependency.
=> refactor(cdk/schematics): remove circular dependency

goldens/size-test.yaml
Fixes a few size test failures due to the relevant PRs being opened before we had size checks.
=> build: fix failing size tests

src/google-maps/google-map/google-map.spec.ts, src/google-maps/google-map/google-map.ts, tools/public_api_guard/google-maps/google-maps.d.ts
When the Google Map component was first introduced, it had inputs to control the `width` and `height`. This is somewhat inflexible, because it only handles pixel units and can't be controlled by media queries. Since changing the sizing approach now would be a breaking change, these changes allow for the consumer to set the `width` and `height` to `null` and to provide it themselves through CSS.
=> fix(google-maps): allow for dimensions to be controlled through CSS

src/material/progress-spinner/progress-spinner.scss
High contrast mode doesn't invert colors on SVG elements so we have to do it ourselves for the progress spinner. This ensures that the user's color settings are respected.
=> fix(progress-spinner): not respecting user colors in high contrast mode

src/cdk/schematics/update-tool/component-resource-collector.ts, src/cdk/schematics/update-tool/file-system.ts, src/cdk/schematics/update-tool/index.ts, src/cdk/schematics/update-tool/target-version.ts, src/cdk/schematics/update-tool/tsconfig.json, src/cdk/schematics/update-tool/version-changes.ts
In some cases the schematics fail to read a file which results in an error, because we weren't guarding against it properly. We had the correct types in place, but the tsconfig didn't have `strictNullChecks` enabled which prevented the compiler from reporting the errors.
Fixes #19779.
=> fix(cdk/schematics): errors when attempting to read some files

src/components-examples/material/slide-toggle/slide-toggle-forms/slide-toggle-forms-example.html
fixes type for Save Settings button in Slide toggle example
=> docs(slide-toggle): fix typo for mat button

src/material/autocomplete/autocomplete-trigger.ts, src/material/autocomplete/autocomplete.spec.ts
We allow the consumer to set an alternate element that an autocomplete will be attached to, but our logic for closing when the user clicks outside the autocomplete didn't account for it which meant that it was being treated as not being part of the autocomplete.
Fixes #19771.
=> fix(autocomplete): don't close when clicking inside custom origin

src/dev-app/datepicker/datepicker-demo.html, src/material/datepicker/date-range-input-parts.ts, src/material/datepicker/date-range-input.spec.ts, src/material/datepicker/date-range-input.ts, tools/public_api_guard/material/datepicker.d.ts
Currently we always set the `aria-labelledby` on the range inputs which will be invalid if the form field doesn't have a label. These changes add an extra check around it.
=> fix(datepicker): don't set aria-labelledby if form field does not have a label

goldens/ts-circular-deps.json, src/material/datepicker/date-range-input.ts, src/material/datepicker/date-range-picker.ts, src/material/datepicker/datepicker.ts, src/material/datepicker/public-api.ts, tools/public_api_guard/material/datepicker.d.ts
Adjusts a couple of types in order to avoid circular dependencies.
=> refactor(datepicker): remove circular dependencies

src/cdk/scrolling/scrollable.ts, src/cdk/scrolling/virtual-for-of.ts, src/material/snack-bar/snack-bar-container.ts, src/material/tooltip/tooltip.ts, tools/public_api_guard/material/snack-bar.d.ts
In RxJS v7, the type of `Subject.next()` will change from `next(value?: T)` to `next(value: T)` ([change](https://github.com/ReactiveX/rxjs/commit/33561526d2c893fdb2a7c5552a3c86806cb0e9a9#diff-54b18fdea0a03178c258be326d16f566L61)). No runtime behavior is affected, but this change will break users who build from source. This PR corrects types to ensure projects build successfully.
- asserts `T|undefined|null` values to `T` where appropriate.
- refactor instances of `Subject<any>` to `Subject<void>` so the `next()` method can be called without passing an argument.
=> refactor: assert value for RxJS v7 compatibility

package.json, yarn.lock
Backport of #19646 for the patch branch.
**Caretaker note**: please manually merge this into the `10.0.x` branch through the Github UI.
=> build: update to typescript v3.9.5 [patch backport]

src/material/checkbox/checkbox-module.ts, src/material/menu/menu-module.ts, src/material/menu/menu.ts, src/material/radio/radio.ts, src/material/slide-toggle/slide-toggle-module.ts, src/material/tabs/ink-bar.ts, src/material/tabs/tab-body.ts, src/material/tabs/tab-group.ts, src/material/tabs/tab-header.ts, src/material/tabs/tab-nav-bar/tab-nav-bar.ts, tools/tslint-rules/symbolNamingRule.ts, tslint.json
As discussed, we want to prefix some exported class names with an underscore so it's more obvious that they're private. The problem is that our current class naming rule doesn't allow for a class to start with an underscore. These changes add a custom rule that can use a regex to validate the class name. Having our own rule allows us to validate more types of nodes as well (e.g. `type` nodes which tslint doesn't check).
=> build: add custom linting for symbol names

.circleci/config.yml, package.json
Disables the size test integration tests until we have a better concept for reporting size regressions. For now we disable them in the CI but report failures to the #components-ci-failures Slack channel.
=> build: integration size tests should not cause failure in CI

src/cdk/testing/tests/BUILD.bazel, src/cdk/testing/tests/cross-environment.spec.ts, src/cdk/testing/tests/protractor.e2e.spec.ts, src/cdk/testing/tests/test-main-component.html, src/cdk/testing/tests/testbed.spec.ts
Currently there are many duplicated specs for protractor and testbed environment.
Most are equal, some are missplaced, some are slightly different.
Sharing those tests ensures the same tests exists as unit tests and as e2e tests.
Further it reduces code duplication.
Prerequisite #19709 (will need to test equal behavior)
=> refactor: share environment idependent specs

src/material/list/list.scss
We have some extra CSS rules to prevent sticky hover states on touch devices. The problem is that we use the hover style to indicate a selected item in a single selection list and it breaks in a way that prevents the selected state from showing up for touch devices. These changes make the selector more specific to avoid the issue.
Fixes #19876.
=> fix(list): single selection list selected state not shown on touch devices

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/drag-ref.ts
The logic that starts the auto-scrolling sequence was using the pointer position that is constrained within the boundary element which wasn't allowing it to start auto scrolling. These changes also fix some internal issues that I noticed along the way:
* We were using the pointer position at the last direction change to re-sort the element while dragging. This is incorrect since the user might not have changed direction. Now we use the position at the last pointer event.
* The `_getConstrainedPointerPosition` method was mutating the passed in `Point` which can throw things off downstream.
* The logic that updates the `ClientRect` of the boundary element was doing so on any scroll, even if it comes from inside the boundary. Now we only do it if a parent of the boundary was scrolled.
Fixes …
=> fix(drag-drop): not starting auto scroll when inside boundary

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/drag-ref.ts
Fixes a bug in the Angular Material `drag-drop` component where the pointer position is incorrectly calculated for SVG with viewBox. This is because mouse coordinates retrieved using the screen coordinate system, but coordinates must be in SVG space, which is defined by the viewBox attribute.
[Bug demo](https://stackblitz.com/edit/angular-material2-issue-znyrd5?file=app%2Fapp.component.html)
=> fix(cdk/drag-drop): pointer position calculation for SVG with viewBox

src/material/input/input.md
Fixes document link fragment, it was using additional chars like lt-code, gt-code
Fixes #11473
=> docs(input): Broken link fragments in input documentation.

tools/postinstall/apply-patches.js
Since the postinstall patches and the `ngc` call were inside an `async` function, we were getting uncaught promise rejection logs, instead of exiting the process with an error code, which allowed the subsequent scripts in the postinstall chain to run. These changes add a try/catch so we can exit correctly.
=> build: postinstall patches not failing on compilation errors

.stylelintrc.json, src/material/checkbox/checkbox.scss, src/material/grid-list/grid-list.scss
Enables a lint rule that enforces that we have consistent spaces around the colon which prevents things like `display:none`.
=> build: enforce consistent spaces between colons

.circleci/config.yml
We recently added a new step to the snapshot publish job. The step will block
the job until all previous snapshot publish jobs that have been launched before
complete.
This step relies on the CircleCI API which does not always refresh immediately.
This means that we could run into a race condition where the queue does not
detect previous jobs. This has been observed with:
https://app.circleci.com/pipelines/github/angular/components/9618/workflows/52fef2b9-8059-4c00-8c2e-347b83ad1031/jobs/158528/steps
We fix this by increasing the confidence threshold of the queue step, so that
it will perform a second CircleCI request after a delay to avoid the race condition
in the most common cases. It's a trade-off between stability and delay. We could
certainly increase the threshold further, but that …
=> build: increase snapshot publish job queue confidence threshold

tools/release/release-output/check-package.ts, tools/release/release-output/output-validations.ts
In framework, the version placeholder computation was incorrect
in some situations. i.e. the release packages used a version that
indicates local changes like `x.x.x-local-changes`. We should ensure
that the release output matches the expected version.
This is especially becoming relevant when we switch to a shared
Bazel workspace status command from the dev-infra package. The
workspace status command is responsible for determining the version
placeholder value when building with `--config=release`.
=> build: ensure project version is set correctly in NPM package output

src/universal-app/prerender.ts
In the past, Angular removed tsickle from the build pipeline. This meant
that decorators were not downleveled, and executed immediately. This
caused errors in SSR as parameters or input types are accessed on
file load as runtime values. e.g. consider an input that used
`HTMLElement` as type. The TypeScript decorator output would access
`HTMLElement` on file load directly. This breaks on the server as such
DOM specific globals do not exist there.
We worked around this by providing global mocks for these symbols. Now
with Angular v10 though, Angular processes decorators by default without
requiring tsickle. This means that we can remove the workaround.
=> build: remove workaround for decorator metadata in universal-app

src/material/input/input.ts
This is a prerequisite to make landing #10466 easier in g3. Mirrors the native placeholder value in a data attribute so that we can read it even when it has been removed.
=> refactor(input): mirror placeholder in data attribute

src/google-maps/README.md
The readme file for google-maps serves as basic documentation for the
google-maps package. Currently it suggests an invalid template reference
since we switched from a component to a directive.
Directives do not provide the `$implicit` context, so we'd
need to use the explicit directive `exportAs` name.
Fixes #19807.
=> docs: fix incorrect template reference to map marker

src/cdk/schematics/migration.json, src/cdk/schematics/ng-update/index.ts, src/cdk/schematics/update-tool/target-version.ts, src/material/schematics/migration.json, src/material/schematics/ng-update/index.ts
Usually we leave it until the last moment to set up the schematics for a new major version and we inevitably get blocked by the fact that the boilerplate isn't set up. These changes add it ahead of time so we aren't blocked by it in a few months.
=> build: set up boilerplate for v11 schematics

src/components-examples/material/button/button-overview/button-overview-example.css
=> docs(buttons): fix overflow on mobile (#19741)

src/cdk-experimental/listbox/BUILD.bazel, src/cdk-experimental/listbox/listbox.spec.ts, src/cdk-experimental/listbox/listbox.ts
Updated listbox to include disabled logic and keyboard interaction management. The listbox still is by default multi-selectable, and in a future PR that handles multi-select I will update the keyboard logic to deal with this.
=> Cdk listbox key management

.ng-dev/merge.ts, package.json, yarn.lock
Updates to the latest version of the dev-infra package, so
that we could leverage the new caretaker note label prompt.
The script will prompt/warn the caretaker if a note is
set up. This should help with raising awareness for
special attention required by the caretaker.
=> build: set up caretaker note label in merge script

goldens/size-test.yaml, src/cdk/drag-drop/directives/drag-handle.ts, src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/directives/drag.ts, tools/public_api_guard/cdk/drag-drop.d.ts
Currently we only allow the drag handle to be a descendant of the drag element, but this can be inconvenient if the drag root is moved further up the DOM using `cdkDragRootElement`. These changes allow for a handle to be set on the drag element itself, if it has an alternate drag root.
Fixes #19555.
=> fix(drag-drop): allow handle to be set on drag element if there is a different drag root

.ng-dev/merge.ts
Updates the hard-coded branch logic so that minor
label merges into `master`. We continue using our
hard-coded values as we have not finalized the branching
and labeling yet.
=> build: set master as branch for minor label when merging

src/material-experimental/mdc-form-field/BUILD.bazel
Our form field doesn't have an e2e test, probably since all the other components indirectly test it (input, select, etc)
=> test(material-experimental/mdc-form-field): remove e2e file

src/material-experimental/mdc-list/list-base.ts
The MDC-based list was throwing an error on init due to an infinite loop caused by some incorrect syntax. Also gets rid of an unnecessary private method.
=> fix(material-experimental/mdc-list): fix infinite loop on init

package.json, src/material-experimental/mdc-snack-bar/_snack-bar-theme.scss, yarn.lock
Sets up the variables so that we can generate the correct colors for dark themes.
Also updates us to the latest MDC canary which has a relevant fix for `mat-table`.
=> fix(material-experimental/mdc-snack-bar): support dark themes

src/material-experimental/mdc-snack-bar/snack-bar-container.ts, src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.ts
Fixes an error that the MDC snack bar throws during server-side rendering, because MDC is using some browser APIs. Also sets up SSR testing for the new module.
=> fix(material-experimental/mdc-snack-bar): error during server-side rendering

test/benchmarks/material/radio/BUILD.bazel, test/benchmarks/material/radio/app.module.ts, test/benchmarks/material/radio/radio.perf-spec.ts
* Test the render speed of 2 radio buttons
* Test the render speed of 10 radio buttons
* Test the click speed between 2 radio buttons
=> test(radio): add performance tests for mat-radio-button

test/benchmarks/material/table/BUILD.bazel, test/benchmarks/material/table/app.module.ts, test/benchmarks/material/table/basic-table.ts, test/benchmarks/material/table/fake-table-data.ts, test/benchmarks/material/table/table.perf-spec.ts
* Test the render speed of the table for 10, 100, and 1000 rows with 5 cols
* Test the render speed of the table for 5, 10, and 20 cols with 10 rows
=> test(mat-table): add performance tests for mat-table

goldens/ts-circular-deps.json, src/cdk-experimental/popover-edit/edit-event-dispatcher.ts, src/cdk-experimental/popover-edit/edit-ref.ts, src/cdk-experimental/popover-edit/edit-services.ts, src/cdk-experimental/popover-edit/table-directives.ts
Reworks the popover edit module in order to avoid circular references.
=> refactor(popover-edit): remove circular reference

goldens/ts-circular-deps.json, src/cdk/scrolling/public-api.ts, src/cdk/scrolling/virtual-for-of.ts, src/cdk/scrolling/virtual-scroll-repeater.ts, src/cdk/scrolling/virtual-scroll-viewport.ts, tools/public_api_guard/cdk/scrolling.d.ts
I originally refactored `virtualForOf` into an interface as part of some ongoing virtual scroll enhancements. After discovering #16412, I decided to use the existing work since it has already been blessed. Prior attempts to merge this change in #14287 and #16412 have gone stale without any recent updates, so I forked the changes and fixed file conflicts.
=> refactor: add virtual scroll repeater interface

src/material/dialog/BUILD.bazel, src/material/dialog/dialog-container.ts, src/material/dialog/dialog-content-directives.ts, src/material/dialog/dialog-ref.ts, src/material/dialog/dialog.spec.ts, tools/public_api_guard/material/dialog.d.ts
* Restores the trigger focus upon dialog close with the proper focus origin that caused the dialog closing.
For example, a backdrop click leads to a focus restore via `mouse`. Pressing `escape` leads to a focus restore via `keyboard`.
References #8420
=> fix(dialog): restore focus with the proper focus origin

goldens/size-test.yaml, src/cdk/drag-drop/directives/drag.ts
See individual commits. 
Marking as P2 to fix the size regression as soon as possible (low-effort), and since lightweight token work was P2 too.
=> refactor(cdk/drag-drop): do not always retain drag handle directive 

src/material-experimental/mdc-form-field/testing/form-field-harness.ts, src/material/form-field/testing/form-field-harness.ts, src/material/form-field/testing/shared.spec.ts, tools/public_api_guard/material/form-field/testing.d.ts
In general we want to avoid exposing `TestElement` instances in the public harness API. These changes mark `getHarnessLoaderForSuffix` and `getHarnessLoaderForPrefix` as deprecated since they don't do what their names say and they're exposing a `TestElement`. I've added replacements that return the text of the elements since that's what appears to be the main use case.
**Note:** marking as merge safe, because it only adds new APIs without touching existing behavior.
=> refactor(form-field/testing): deprecate methods that return TestElement

src/material-experimental/mdc-card/card.spec.ts
Doesn't exist in the current card since its just a bunch of directives. Any issues should come up from the e2e tests
=> test(material-experimental/mdc-card): remove stub for unit test

src/google-maps/google-map/google-map.spec.ts, src/google-maps/google-map/google-map.ts
If an options object without a `center` is passed to the Google Maps API, it'll render a grey rectangle which looks broken. These changes make sure that we always pass in a `center` so something is rendered.
Fixes #19908.
=> fix(google-maps): rendering blank if custom options with no center are provided

src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.ts
The outside click dispatcher was accessing the clicked element through `event.target` which won't work if the element is inside the shadow DOM.
=> fix(overlay): outside click dispatcher not accounting for shadow DOM

src/cdk/platform/features/scrolling.ts
In Safari on macOS, the RTL scroll axis is determined incorrectly when
scrollbars are set to `Always Display` as per macOS general system
preferences. Our test element for the scroll axis sets a fixed height.
This is resulting in a vertical scroll bar as the horizontal scroll bar
for testing `scrollLeft` exceeds the scroll containers `1px` height. The
vertical scroll bar then unveils a bug in Webkit where space is acquired
on the right side for the scroll bar (while it's displayed on the left).
This space causes our scroll axis detection to break as the horizontal
`scrollLeft` unexpectedly expands to: `[-scrollWidth, 15px]` while
usually `0px` is the right boundary. We fix this by simply ensuring
that no vertical scroll bar is ever displayed. The vertical scrolling
is not needed for …
=> fix(cdk/platform): rtl scroll axis incorrectly determined in Safari macOS

src/material/core/style/_list-common.scss
* use `flex: auto` instead of `width: 100%` to allow `.mat-list-text` element to take up the available space
[stackblitz demonstrating issue](https://stackblitz.com/edit/angular-sawwqj)
**Before**
**After**
=> fix(material/list): use flexbox to size mat-line elements (#19809)

src/cdk/schematics/ng-update/devkit-file-system.ts, src/cdk/schematics/ng-update/devkit-migration-rule.ts, src/cdk/schematics/ng-update/devkit-migration.ts, src/cdk/schematics/ng-update/find-stylesheets.ts, src/cdk/schematics/ng-update/migrations/attribute-selectors.ts, src/cdk/schematics/ng-update/migrations/css-selectors.ts, src/cdk/schematics/ng-update/migrations/element-selectors.ts, src/cdk/schematics/ng-update/test-cases/misc/external-resource-resolution.spec.ts, src/cdk/schematics/ng-update/test-cases/misc/global-stylesheets.spec.ts, src/cdk/schematics/ng-update/test-cases/misc/method-call-checks.spec.ts, src/cdk/schematics/testing/test-case-setup.ts, src/cdk/schematics/update-tool/file-system.ts, src/cdk/schematics/update-tool/index.ts, src/cdk/schematics/update-tool/utils/parse-tsconfig.ts, src/cdk/schematics/update-tool/utils/virtual-host.ts, src/cdk/schematics/utils/project-tsconfig-paths.spec.ts, src/cdk/schematics/utils/project-tsconfig-paths.ts, src/material/schematics/ng-update/migrations/hammer-gestures-v9/hammer-gestures-migration.ts, src/material/schematics/ng-update/migrations/misc-ripples-v7/ripple-speed-factor-migration.ts, src/material/schematics/ng-update/test-cases/misc/class-inheritance.spec.ts, src/material/schematics/ng-update/test-cases/misc/constructor-checks.spec.ts, src/material/schematics/ng-update/test-cases/misc/import-checks.spec.ts, src/material/schematics/ng-update/test-cases/v8/misc/material-imports.spec.ts, src/material/schematics/ng-update/test-cases/v9/misc/hammer-migration-v9.spec.ts, src/material/schematics/ng-update/test-cases/v9/misc/material-imports.spec.ts
In some situations, developers will run `ng update` from a sub directory
of the project. This currently results in a noop migration as file
system paths were computed incorrectly. This is because ng-update
always assumed that the CWD is the workspace root in the real file
system. This is not the case and therefore threw off path resolution.
We fix this by fully relying on the virtual file system now. Previously
we mixed virtual and real file system as TypeScript relied on the
real file system for parsing configuration, matching and reading files.
This commit adds a new compiler host for config parsing and program
creation that works fully with a virtual file system. This is something
we had planned a long time ago as schematics should never deal with
the real file system. We can re-use …
=> fix(ng-update): properly handle update from different working directory

src/cdk/a11y/key-manager/list-key-manager.spec.ts, src/cdk/a11y/key-manager/list-key-manager.ts, tools/public_api_guard/cdk/a11y.d.ts
For some components like menus and listboxes, WAI a11y recommends
that pressing home or end should focus the first or last element
respectively. Add support for home/end to ListKeyManager.
=> feat(a11y): Add optional home/end key support to ListKeyManager

src/cdk/testing/component-harness.ts, src/material/card/testing/card-harness.ts, tools/public_api_guard/cdk/testing.d.ts, tools/public_api_guard/material/card/testing.d.ts
Adds a variant of the `ComponentHarness` base class that implements `HarnessLoader` and allows for child loaders to be queried off of the current harness. Applies it to the card harness to illustrate the consumption.
**Note:** marking as P2, because it's blocking further work on applying this to other harnesses.
=> feat(cdk/testing): add base class for harnesses that may contain other harnesses

src/material/core/focus-indicators/_focus-indicators.scss, src/material/sort/BUILD.bazel, src/material/sort/sort-header-intl.ts, src/material/sort/sort-header.html, src/material/sort/sort-header.scss, src/material/sort/sort-header.ts, src/material/sort/sort.spec.ts, src/material/sort/testing/shared.spec.ts, src/material/sort/testing/sort-header-harness.ts, tools/public_api_guard/material/sort.d.ts
Reworks the sort header to allow for screen readers to read out its sorted state through `aria-sort`, rather than having to declare an `aria-label` inside it. The drawback of the `aria-label` approach is that the label will also be read out as the user is navigating the table's cells.
Fixes #13012, #16952
=> fix(sort): sorted state being read out when navigating cells

src/cdk/overlay/overlay-directives.spec.ts, src/cdk/overlay/overlay-directives.ts
Currently the `ConnectedOverlayDirective` only emits the `detach` event when it _thinks_ that the overlay is detached (escape press, backdrop click etc.), but this won't necessarily be correct (e.g. when it was closed by a scroll strategy). These changes refactor the outputs to always be one-to-one with the `OverlayRef` detachments.
Fixes #16779
=> fix(overlay): overlay directives not emitting when detached externally

goldens/size-test.yaml, src/material/chips/chip-list.ts, src/material/form-field/form-field.ts, src/material/input/input.spec.ts, src/material/input/input.ts, src/material/input/testing/input-harness.ts, tools/public_api_guard/material/input.d.ts
Currently we hide the native placeholder using CSS while we mirror its value in the form field label, however because the value is still in the DOM, some screen readers will read it out twice: once for the label and once for the attribute. These changes remove the attribute from the DOM if it isn't supposed to be shown.
Fixes #9721.
=> fix(input): placeholder being read out twice by some screen readers

src/cdk/a11y/aria-describer/aria-describer.spec.ts, src/cdk/a11y/aria-describer/aria-describer.ts, tools/public_api_guard/cdk/a11y.d.ts
Fixes the messages from the `AriaDescriber` not being read out in Edge or IE, because the message container is `aria-hidden` and has `display: none`.
Fixes #12298.
=> fix(aria-describer): messages not being read out in IE and Edge

src/cdk-experimental/menu/BUILD.bazel, src/cdk-experimental/menu/menu-bar.spec.ts, src/cdk-experimental/menu/menu-bar.ts, src/cdk-experimental/menu/menu-group.spec.ts, src/cdk-experimental/menu/menu-interface.ts, src/cdk-experimental/menu/menu-item-checkbox.spec.ts, src/cdk-experimental/menu/menu-item-checkbox.ts, src/cdk-experimental/menu/menu-item-radio.spec.ts, src/cdk-experimental/menu/menu-item-radio.ts, src/cdk-experimental/menu/menu-item-trigger.spec.ts, src/cdk-experimental/menu/menu-item-trigger.ts, src/cdk-experimental/menu/menu-item.spec.ts, src/cdk-experimental/menu/menu-item.ts, src/cdk-experimental/menu/menu-panel.ts, src/cdk-experimental/menu/menu-stack.ts, src/cdk-experimental/menu/menu.spec.ts, src/cdk-experimental/menu/menu.ts
The aria spec for Menu and MenuBar describes a robust set of instructions for navigating the Menu
using a keyboard. This implements the full aria spec for vertical and horizontal Menus along with
support for left-to-right and right-to-left layouts. Some liberty is taken with handling keyboard
events with modifier keys (home/end and escape) in order to match the existing mat-menu
implementation for those keys.
=> feat(cdk-experimental/menu): add functionality to navigate a Menu and MenuBar with a keyboard

src/material-experimental/mdc-snack-bar/snack-bar.spec.ts
The MDC-based snackbar tests are currently failing because we landed
a change in the non-MDC snackbar that propagates to the MDC-based
snack bar. That is expected, but the test for the MDC-based snackbar
have not been updated accordingly.
See: https://github.com/angular/components/commit/1bbfcf40958b7b31e69dc9e19fc2acd237dde1dd.
=> test: fix failing MDC snackbar test

src/cdk-experimental/listbox/BUILD.bazel, src/cdk-experimental/listbox/listbox.spec.ts, src/cdk-experimental/listbox/listbox.ts
Added support for toggling whether listbox can have multiple options selected. Also added aria active descendant support and the ability to let the user choose whether to use active descendant or to let the focus follow the active item.
=> Cdk listbox: multipleselect support and active descendant

src/material/input/input.spec.ts, src/material/input/input.ts, tools/public_api_guard/material/input.d.ts
The placeholder attribute is set based on a child query which is prone to "changed after checked" errors. These changes switch to assigning it ourselves directly to the DOM manually.
=> fix(input): changed after checked error if input has static placeholder

src/material-experimental/mdc-chips/chip-grid.ts, src/material-experimental/mdc-chips/chip-set.ts
Similar check that was necessitated from PR #10466 - due to changes in the change detection cycle from input, its possible that `empty` is called earlier and should account for when there are no `chips` picked up yet
=> fix(material-experimental/chips): fix empty check when no chips

goldens/ts-circular-deps.json, src/material/grid-list/grid-list.ts, src/material/grid-list/tile-styler.ts, tools/public_api_guard/material/grid-list.d.ts
Changes some types in order to avoid a circular dependency between the grid list and the tile styler.
=> refactor(grid-list): remove circular dependencies

src/cdk-experimental/menu/menu-item.spec.ts, src/cdk-experimental/menu/menu-item.ts
When determining the text to use for a menu item for TypeAhead ensure that text in nested elements
isn't skipped and icons are skipped.
Co-authored-by: Niels Rasmussen <54564567+nielsr98@users.noreply.github.com>
=> refactor(cdk-experimental/menu): add more robust implementation of getLabel for menu item

src/material-experimental/mdc-slider/slider.spec.ts
We've been seeing more test flakes from the MDC slider recently. These changes try to address them by disabling animations and adding an extra change detection after flushing `requestAnimationFrame`.
=> test(material-experimental/mdc-slider): try to reduce test flakes

.bazelrc
We upload build results to Google Cloud `ResultStore`. Sometimes this
seems to fail though and Bazel CI jobs exit red. This could be due to
BES servers being slow, or servers being unreliably. Given that remote
executors from GCP are behaving fine though, we try increasing the
timeout first. We can disable the uploading if it doesn't get better.
For context: We upload to result store / source.cloud.google.com so that
CI builds with Bazel can be debugged better. e.g. 
https://source.cloud.google.com/results/invocations/410a5790-54eb-43e8-96eb-c3cfa0f8960d
=> build: increase timeout for resultstore build uploads

test/karma.conf.js
We keep adding more tests to our codebase, but browsers
on Saucelabs generally run slow. During the last couple of
weeks unit tests on Saucelabs sometimes failed due to the default 10min
timeout. e.g. https://app.saucelabs.com/tests/bfb7ade4b0fc4e7e9ff7237074baac80
We bump the timeout so that tests can complete without us relaunching
another instance of a browser (which might pass; but will increase CI
duration even more). We use the maximum value of 1000seconds.
Ideally we'll fix this in the future by having incremental test runs.
I'm working on this with a Bazel setup as a side project. See:
https://github.com/angular/components/pull/19409
=> build: increase timeout for legacy saucelabs tests

WORKSPACE, scripts/run-component-tests.js, src/cdk-experimental/popover-edit/popover-edit.spec.ts, src/material-experimental/popover-edit/popover-edit.spec.ts, src/material/datepicker/datepicker.spec.ts, tools/defaults.bzl
Updates our Firefox version that is used for Bazel unit tests to v78.0.
Previously we were using v68.
To update the Firefox version, we had to set up a custom Browser target
with repositories as the version for Firefox is usually hard-coded in
`rules_webtesting` and we cannot control that.
See related change in the dev-infra package: https://github.com/angular/angular/pull/38029.
This is an addition to: https://github.com/angular/components/pull/19961
=> build: update firefox to latest version

src/material-experimental/mdc-tabs/ink-bar.ts
Converts the adapter to class object to hopefully reduce memory usage. Adds getters to access private fields.
=> perf(int-bar): Convert MatInkBarFoundation adapter to class object

CHANGELOG.md
These changes were already applied to [the GitHub release](https://github.com/angular/components/releases/tag/10.1.0).
=> chore: move changes to right packages in changelog

src/material-experimental/mdc-tabs/_tabs-common.scss
Fixes the MDC-based tabs not having focus indication in high contrast mode.
=> fix(material-experimental/mdc-tabs): missing focus indication in high contrast mode

src/material-experimental/mdc-snack-bar/snack-bar-container.scss
The MDC snack bar doesn't have a border which causes it to blend in with the background in high contrast mode.
=> fix(material-experimental/mdc-snack-bar): blending in with background in high contrast mode

.bazelrc
We currently always upload build results to `source.cloud.google.com`.
Though past has proven that servers for the Build Event Service are
rather unstable compared to the remote execution workers we acquire
for CI builds. To avoid that these servers and the non-build relevant
result uploading degrades CI stability, we do not run them by default,
unless one explicitly opts-in through a Bazel build configuration.
The uploaded build results were useful to inspect output of individual
targets that ran on CI, but the need for this is limited, and if someone
cannot see given output for an action, he could easily connect to the CI
container and run the command manually. Usually the output for failed
actions is printed to the CI output anyway.
Motivation for this change: As explained, instability …
=> build: do not upload results to cloud result-store by default

src/cdk-experimental/menu/menu-bar.spec.ts, src/cdk-experimental/menu/menu-bar.ts, src/cdk-experimental/menu/menu.ts
If a menu is opened programmatically, subsequent keyboard events to close it out are not handled.
This fixes the issue by tracking the open sub-menu regardless of how it was opened up.
=> fix(cdk-experimental/menu): fix bug preventing keyboard event handling if opened programmatically

package.json, src/material-experimental/mdc-slider/_slider-theme.scss, src/material-experimental/mdc-slider/slider.e2e.spec.ts, src/material-experimental/mdc-slider/slider.html, src/material-experimental/mdc-slider/slider.scss, src/material-experimental/mdc-slider/slider.spec.ts, src/material-experimental/mdc-slider/slider.ts, src/material-experimental/mdc-slider/testing/slider-harness.spec.ts, yarn.lock
Updates to the latest canary version and temporarily disables the MDC-based slider. We have to disable the slider, because MDC have introduced a completely new implementation that will take some work to reintegrate into our current slider and we don't want our CI to fail until then.
I went with this approach of disabling the slider where it's basically a no-op, because we can't simply exclude the build target without modifying a ton of shared files which will be hard to clean up once we start to actually implement it.
=> build: update to latest MDC canary and disable slider

src/material/datepicker/date-range-input-parts.ts, src/material/datepicker/date-range-input.spec.ts, src/material/datepicker/datepicker-input-base.ts, src/material/datepicker/datepicker-input.ts, tools/public_api_guard/material/datepicker.d.ts
Adds some logic to prevent date range inputs from emitting their `dateChange` and `dateInput` events when a value is assigned to the opposite input.
Fixes #19968.
=> fix(datepicker): emitting dateChange event when opposite range input changes

src/cdk/drag-drop/clone-node.ts, src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/drag-ref.ts
We use `cloneNode` to create a preview for an element which clones all of the attributes of an element, but that may not pick up properties like its `value`. These changes add some logic where we clone the value with a similar approach that we use for cloning `canvas` elements. Also generalizes the approach a bit so we don't have to keep repeating the logic.
Fixes #19905.
=> fix(drag-drop): not transferring input value when cloning element for preview

test/benchmarks/mdc/card/BUILD.bazel, test/benchmarks/mdc/card/app.module.ts, test/benchmarks/mdc/card/card.perf-spec.ts
This benchmark is identical to the one in `//src/test/benchmarks/material/card` except that it uses the mdc version of the component.
=> test(mdc-card): add performance tests for mdc-card

src/material/datepicker/date-range-input.ts, src/material/datepicker/datepicker-base.ts, src/material/datepicker/datepicker-input-base.ts, src/material/datepicker/datepicker-toggle.ts, src/material/datepicker/datepicker.spec.ts, tools/public_api_guard/material/datepicker.d.ts
The datepicker was only updating the calendar state that depends on the input when we open and close. I've reworked it so we do it any time one of the input's inputs changes. I also renamed the various `_disabledChange` streams to `_stateChanges` which aligns with what we're doing in other components.
Fixes #19959.
=> fix(datepicker): not updating calendar state if input changes while open

src/cdk/table/table.spec.ts, src/cdk/table/table.ts, src/material-experimental/mdc-table/table.spec.ts, src/material/table/table.spec.ts
There's an early `return` in the function that renders all the rows, including the one that is shown for no data, if there were no changes to the data source. This was preventing the no data row from showing up if the data source starts off as empty.
Fixes #19992.
=> fix(table): no data row not shown if data source is empty on init

src/cdk/scrolling/viewport-ruler.spec.ts, src/cdk/scrolling/viewport-ruler.ts
Fixes the `resize` and `orientationchange` events of the `ViewportRuler` being run inside the `NgZone`, if the subscription comes from inside the zone.
Fixes #18471.
=> fix(scrolling): viewport ruler events being run inside zone

src/cdk-experimental/listbox/listbox.spec.ts
We landed two PRs. One that added a new usage of `createKeyboardEvent`
and another one that changed the signature of `createKeyboardEvent`.
This meant that the first PR adding the new instance does not account
for the new function signature and CI/build is failing.
=> test: fix listbox spec failing due to keyboard event helper update

src/cdk-experimental/selection/BUILD.bazel, src/cdk-experimental/selection/selection.spec.ts
Add unit tests for `CdkSelection` and related components.
Issue #18581
=> feat(cdk-experimental/selection): Add unit tests

README.md
We mention that we're working on the MDC-based versions of the
components, but don't get into the benefits people would expect to see
from this work.
=> docs(readme): expand MDC point to mention benefits

src/cdk-experimental/menu/menu-bar.ts, src/cdk-experimental/menu/menu-item-trigger.ts, src/cdk-experimental/menu/menu-item.ts, src/cdk-experimental/menu/menu-stack.spec.ts, src/cdk-experimental/menu/menu-stack.ts, src/cdk-experimental/menu/menu.ts
When closing a menu from the menu stack this ensures that any sub-menu's are popped off the stack
and closed resulting in a stack which represents the state of the UI.
=> refactor(cdk-experimental/menu): refactor MenuStack to ensure submenus are popped off and closed

src/material/icon/icon.ts, src/material/icon/testing/BUILD.bazel, src/material/icon/testing/icon-harness-filters.ts, src/material/icon/testing/icon-harness.spec.ts, src/material/icon/testing/icon-harness.ts, src/material/icon/testing/public-api.ts, src/material/icon/testing/shared.spec.ts, tools/public_api_guard/material/icon.d.ts, tools/public_api_guard/material/icon/testing.d.ts
Sets up a test harness for `mat-icon`.
=> feat(icon): add test harness

.bazelrc, .circleci/config.yml, scripts/build-packages-dist.js, scripts/deploy/publish-build-artifacts.sh, scripts/deploy/publish-docs-content.sh, tools/bazel-stamp-vars.js, tools/release/check-release-output.ts, tools/release/publish-release.ts, tools/release/release-output/check-package.ts, tools/release/release-output/output-validations.ts
An interesting case that came up in v10.0.0 with the docs-content. The
snapshot release package and docs-content output had various
`@breaking-change` notes in the source code referring to `v10.0.0` as
certain changes are planned to be made at that point.
The snapshot deploy scripts pick up the version from the package.json
file and replace it in the output packages with a more concrete version
that includes the SHA. This meant that we accidentally also overwrote
versions as in the `@breaking-change` notes (ultimately making it
difficult for us to use the latest docs-content for the v10 release as
it was incorrect).
Example snapshot commit: https://github.com/angular/material2-docs-content/commit/e624c7130d90026574b46d12d488e470f0a18c55
We fix this by not including the SHA as part of the …
=> build: snapshot builds incorrectly modify semver versions

src/components-examples/material/table/table-sticky-columns/table-sticky-columns-example.css
Closes https://github.com/angular/material.angular.io/pull/778
=> docs(material/table): fix example overflowing docs site width

src/components-examples/cdk/stepper/cdk-custom-stepper-without-form/example-custom-stepper.css, src/components-examples/cdk/stepper/cdk-linear-stepper-with-form/example-custom-linear-stepper.css
Removed hard-coded colors and replaced with inherit colors.
Used font-weight to show active step.
Fixes #17152
=> docs(stepper): Make CDK stepper example accessible in dark mode.

src/cdk-experimental/menu/menu-item-radio.ts, src/cdk-experimental/menu/menu-item.ts, src/cdk-experimental/menu/menu.ts, src/cdk/overlay/overlay.ts, src/cdk/scrolling/virtual-scroll-viewport.ts, src/cdk/table/text-column.ts, src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.ts, src/material/dialog/dialog-content-directives.ts, src/material/input/input.ts, src/material/menu/menu-trigger.ts, src/material/sort/sort-header.ts, src/material/tabs/tab-nav-bar/tab-nav-bar.ts, tools/public_api_guard/cdk/overlay.d.ts, tools/public_api_guard/cdk/scrolling.d.ts, tools/public_api_guard/material/tabs.d.ts, tools/tslint-rules/lightweightTokensRule.ts, tslint.json
Adds a lint that warns if a DI constructor is discovered for which
parameters optionally inject classes without using the lightweight
token pattern. The rule intends to help with optimized source code
that works well for tree shakers. Read more about this here:
https://next.angular.io/guide/lightweight-injection-tokens.
=> build: add lint rule for lightweight tokens pattern

src/material-experimental/mdc-menu/menu.spec.ts, src/material/menu/menu-errors.ts, src/material/menu/menu-trigger.ts, src/material/menu/menu.spec.ts, src/material/menu/menu.ts
If the consumer puts a trigger inside a menu and passes the menu back to the trigger, we'll go into an infinite loop and throw a cryptic error message. These changes detect such a case and throw a better error. Example of a case that will be flagged:
```
<mat-menu #menu="matMenu">
<button [matMenuTriggerFor]="menu"></button>
</mat-menu>
```
Fixes #19941.
=> fix(menu): throw error if menu contains its own trigger

src/material-experimental/mdc-chips/chip-icons.ts, src/material-experimental/mdc-chips/chip-set.ts, src/material-experimental/mdc-chips/chip.ts, src/material/checkbox/checkbox.ts, src/material/chips/chip.ts, src/material/core/common-behaviors/tabindex.ts, src/material/radio/radio.ts, src/material/select/select.ts, src/material/slide-toggle/slide-toggle.ts, src/material/slider/slider.ts, src/material/tabs/tab-nav-bar/tab-nav-bar.ts, src/material/tree/node.ts, tools/public_api_guard/material/checkbox.d.ts, tools/public_api_guard/material/chips.d.ts, tools/public_api_guard/material/radio.d.ts, tools/public_api_guard/material/select.d.ts, tools/public_api_guard/material/slide-toggle.d.ts, tools/public_api_guard/material/slider.d.ts, tools/public_api_guard/material/tabs.d.ts, tools/public_api_guard/material/tree.d.ts, tslint.json
All the components that were implementing the `HasTabIndex` input weren't allowing coercion.
Fixes #20026.
=> fix: tabindex inputs not supporting coercion

src/material/select/select.spec.ts, src/material/select/select.ts
We were using `ListKeyManager.setActiveItem` to change the active item when a value is assigned through a `FormControl`, in order to have it be highlighted if the user opens the panel. The problem is that `setActiveItem` emits a change event as if it's coming from the user, causing us to dispatch an event object with `isUserInput: true`.
These changes use `updateActiveItem` instead which only updates the item, but doesn't emit any events.
Fixes #19967.
=> fix(select): indicating programmatic value change as user interaction in some cases

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/directives/drop-list.ts
We support connecting two drop lists by their ID, but if the ID is incorrect, we silently ignore it. These changes add a warning so it's easier to debug issues where the ID might be misspelled.
Fixes #20056.
=> fix(drag-drop): warn if connected container ID doesn't exist

src/cdk-experimental/menu/menu-bar.spec.ts, src/cdk-experimental/menu/menu-bar.ts, src/cdk-experimental/menu/menu-group.ts, src/cdk-experimental/menu/menu-item.ts, src/cdk-experimental/menu/menu.ts
Add functionality to close any open menus (and submenus) when a user clicks on an element outside
the open menu tree and the menu bar components.
=> feat(cdk-experimental/menu): add ability to close menus when clicking outside the menu tree

.github/CODEOWNERS, src/dev-app/BUILD.bazel, src/dev-app/dev-app/dev-app-layout.ts, src/dev-app/dev-app/routes.ts, src/dev-app/menubar/BUILD.bazel, src/dev-app/menubar/mat-menubar-demo-module.ts, src/dev-app/menubar/mat-menubar-demo.html, src/dev-app/menubar/mat-menubar-demo.ts, src/material-experimental/config.bzl, src/material-experimental/menubar/BUILD.bazel, src/material-experimental/menubar/index.ts, src/material-experimental/menubar/menubar-item.html, src/material-experimental/menubar/menubar-item.ts, src/material-experimental/menubar/menubar-module.ts, src/material-experimental/menubar/menubar.html, src/material-experimental/menubar/menubar.ts, src/material-experimental/menubar/public-api.ts
Add the material-experimental/menubar component skeletons and the accompanying dev app
and its configuration.
=> feat(material-experimental/menubar): add material menubar skeleton and dev-app

src/material/progress-bar/progress-bar.md
=> docs(progress-bar) : Textual improvements for Buffer & Query modes

src/dev-app/google-map/google-map-demo.html, src/dev-app/google-map/google-map-demo.ts, src/google-maps/google-maps-module.ts, src/google-maps/map-kml-layer/map-kml-layer.spec.ts, src/google-maps/map-kml-layer/map-kml-layer.ts, src/google-maps/public-api.ts, src/google-maps/testing/fake-google-map-utils.ts, tools/public_api_guard/google-maps/google-maps.d.ts
Implement KML layers in @angular/google-maps. This allows users to
specify a .kml file that configures many options that display on a
Google Map. See
https://developers.google.com/maps/documentation/javascript/reference/kml
=> feat(google-maps): Add KML Layer component to Google Maps

src/google-maps/map-info-window/map-info-window.spec.ts, src/google-maps/map-info-window/map-info-window.ts, src/google-maps/testing/fake-google-map-utils.ts
Currently if `open` is called multiple times for the same object, we keep re-initializing the info window. This can be seen in the dev app, because Chrome keeps logging warnings for some event listeners. These changes add a check that keeps the existing info window.
cc @mbehrlich
=> fix(google-maps): avoid re-initializing info window for same marker

src/components-examples/material/tree/tree-checklist/tree-checklist-example.ts
We determine whether a node is selected in the checklist example using `Array.prototype.every`, but the problem is that `every` returns true for empty arrays which looks weird in our example.
Fixes #20085.
=> docs(tree): fix example that shows empty checklists as selected

src/cdk/a11y/aria-describer/aria-describer.ts, src/material/tooltip/tooltip.ts
Rather than greedily at startup.
This builds on top of #19764 so should get merged afterwards.
=> perf(tooltip): Hook up to pointer leave events when pointer enter events fire

src/cdk/testing/testbed/unit-test-element.ts
In 9cd18911d40084b6a01a9c93ec45370f03e3ad76 pointer event simulation was added to `UnitTestElement.click` to closer simulate the events that happen inside the browser. These changes expand the coverage to the `hover` and `mouseAway` methods since they can dispatch pointer events too.
=> fix(cdk/testing): emit pointer events on hover and mouseAway

src/cdk/clipboard/pending-copy.ts
The clipboard module works by creating a `textarea` dynamically, focusing it and copying its content. In order to prevent it from affecting the page layout, we put it at `-999em` off-screen, but the problem is that some browsers will try to move it into the view on focus by scrolling up.
These changes use `position: fixed` and anchor the textarea to the top of the page so vertically it's within the viewport.
=> fix(clipboard): scroll position changing while copying on some browsers

.github/CODEOWNERS, src/material/chips/chip-list.ts, src/material/chips/testing/BUILD.bazel, src/material/chips/testing/chip-harness-filters.ts, src/material/chips/testing/chip-harness.ts, src/material/chips/testing/chip-input-harness.ts, src/material/chips/testing/chip-list-harness.spec.ts, src/material/chips/testing/chip-list-harness.ts, src/material/chips/testing/chip-remove-harness.ts, src/material/chips/testing/index.ts, src/material/chips/testing/public-api.ts, src/material/chips/testing/shared.spec.ts, src/material/config.bzl, tools/public_api_guard/material/chips/testing.d.ts
Adds test harnesses for the Material chips and the related components.
**Note:** I didn't add harnesses for `MatChipAvatar` and `MatChipTrailingIcon` because they don't have any functionality tied to them.
=> feat(chips): add test harness

src/cdk/a11y/aria-describer/aria-describer.ts
https://github.com/angular/components/issues/19949
=> fix (a11y): add parent node check when removing existing aria describe

src/cdk/scrolling/virtual-for-of.ts, src/cdk/scrolling/virtual-scroll-viewport.spec.ts
Currently the `CdkVirtualForOf` determines the size of a rendered range by adding up the heights of all the elements, however this doesn't account for margins between them. These changes switch to doing it by taking the difference between the bottom of the last element and the top of the first. This should be a minor performance improvement as well, because we don't have to measure as many elements anymore.
Fixes #19851.
=> fix(scrolling): virtual scroll not accounting for margin when measuring range

src/cdk/overlay/overlay-directives.ts
The `ConnectedOverlayPositionChange` event can be expensive to calculate since it contains information about the scroll position. We have some logic in the position strategy about not emitting it if there are no observers, but in the `CdkConnectedOverlay` directive we were always subscribing in order to proxy it to the output. These changes add some logic to only subscribe when necessary.
=> fix(overlay): only dispatch position change event if requested

scripts/caretaking/resync-caretaker-app-prs.ts
New fields have been added to the synced information from each PR
in the caretaker application.  This change updates the resync script
to also include these new fields.
=> chore: update caretaker resyncing script to include new fields

src/cdk/table/table.ts
Tested with the dev app, clicking "add table" in the "Table with sticky headers, footers and columns" example.
Before:
100ms scripting + 59ms rendering
After:
75ms scripting + 39ms rendering
The effect is greater in more complex tables. More optimization PRs to come.
=> perf(table): Reduce calls to updateStickyColumnStyles

src/cdk/collections/dispose-view-repeater-strategy.ts, src/cdk/collections/public-api.ts, src/cdk/collections/recycle-view-repeater-strategy.ts, src/cdk/collections/view-repeater.ts, src/cdk/scrolling/virtual-for-of.ts, src/cdk/scrolling/virtual-scroll-viewport.spec.ts, src/cdk/table/BUILD.bazel, src/cdk/table/table-module.ts, src/cdk/table/table.ts, src/material-experimental/mdc-table/table.ts, src/material/table/table.ts, tools/public_api_guard/cdk/collections.d.ts, tools/public_api_guard/cdk/scrolling.d.ts, tools/public_api_guard/cdk/table.d.ts
A `ViewRepeater` implements a strategy for rendering a list of elements inside a common `ViewContainerRef`. It encapsulates all the business logic pertaining to inserting, moving, and deleting embedded views. This PR extracts existing strategies from `virtualForOf` and the CDK table, so we can reuse them in upcoming virtual scroll work.
* Extracts view repeater strategies from `virtualForOf` and CDK table.
* Refactors `virtualForOf` and CDK table to use the strategies.
* With the exception of extracting the view repeater strategies, no behavior has changed.
For now, this API will be internal until we've tested it with enough components to know it's stable.
=> feat(cdk/collections): extract view repeater strategies

src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.spec.ts, src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.ts, src/cdk/overlay/overlay-config.ts, tools/public_api_guard/cdk/overlay.d.ts
This removes the ability to track excluded elements from the overlay and only stops outside
click event notifications if the click event occurred within an overlay element itself. The
overlay should not track elements to be excluded from outside click - this should be up
to the developer. This allows for custom closeout logic to be implemented by the developer leaving
the cdk to be unopinionated.
=> refactor(cdk/overlay): remove logic which tracks excluded elements from outside clicks

src/material/sidenav/drawer.ts
Fixes the timer that we use to debounce the autosize calls being run inside the NgZone.
Fixes #18894.
=> fix(sidenav): run autosize debounce timer outside the NgZone

src/cdk/a11y/BUILD.bazel, src/cdk/a11y/focus-trap/focus-trap.spec.ts, src/cdk/portal/dom-portal-outlet.ts, src/cdk/portal/portal.spec.ts
Currently we run change detection as soon as we create a portal's embedded view and afterwards we transfer its DOM nodes into the portal outlet. This is problematic, because running change detection also executes any lifecycle hooks which means that directives inside the portal, which are looking at the DOM, will be invoked while the element is still at its old location.
**Note:** marking this as a P2, because it's a fairly small change and it's fixing something that's caused other timing-related issues for us in the past.
Fixes #16346.
=> fix(portal): running change detection before nodes have been moved to outlet

src/material/select/select.spec.ts, src/material/select/select.ts
Fixes `mat-select` emitting its change event twice when a reset value is selected, as well as when it's selected twice in a row. This PR covers #10859 which would've introduced another issue.
Fixes #10675.
Fixes #13579.
=> fix(select): emitting change event twice for reset values

src/material-moment-adapter/adapter/moment-date-adapter.spec.ts, src/material/core/datetime/date-adapter.ts, src/material/core/datetime/native-date-adapter.spec.ts, src/material/datepicker/calendar.ts, src/material/datepicker/date-range-input-parts.ts, src/material/datepicker/date-range-input.ts, src/material/datepicker/datepicker-base.ts, src/material/datepicker/datepicker-input-base.ts, src/material/datepicker/datepicker-input.ts, src/material/datepicker/month-view.ts, src/material/datepicker/multi-year-view.ts, src/material/datepicker/year-view.ts, tools/public_api_guard/material/core.d.ts
Several components have identical implementations of a `_getValidDateOrNull` method. This PR reduces code duplication by adding a `getValidDateOrNull` to the `DateAdapter` class for the components to use instead.
=> feat(material/datepicker): add `getValidDateOrNull` method

.github/CODEOWNERS, src/material-experimental/config.bzl, src/material-experimental/mdc-core/BUILD.bazel, src/material-experimental/mdc-core/_core.scss, src/material-experimental/mdc-core/index.ts, src/material-experimental/mdc-core/option/_optgroup-theme.scss, src/material-experimental/mdc-core/option/_option-theme.scss, src/material-experimental/mdc-core/option/index.ts, src/material-experimental/mdc-core/option/optgroup.html, src/material-experimental/mdc-core/option/optgroup.scss, src/material-experimental/mdc-core/option/optgroup.ts, src/material-experimental/mdc-core/option/option.html, src/material-experimental/mdc-core/option/option.scss, src/material-experimental/mdc-core/option/option.spec.ts, src/material-experimental/mdc-core/option/option.ts, src/material-experimental/mdc-core/public-api.ts, src/material-experimental/mdc-theming/BUILD.bazel, src/material-experimental/mdc-theming/_all-theme.scss, src/material/core/option/optgroup.ts, src/material/core/option/option.ts, tools/public_api_guard/material/core.d.ts
- Sets up the MDC-based `mat-option` and `mat-optgroup` which are a prerequisite for the MDC-based `mat-select` and `mat-autocomplete`.
- Adds a new `mdc-core` entry point which is the equivalent of `material/core`. We'll need this in the future for other things like an MDC-based `mat-core-theme` and for the elevation styles.
=> feat(material-experimental): add MDC-based mat-option and mdc-core entry point

src/cdk-experimental/column-resize/resizable.ts, src/cdk-experimental/dialog/dialog.ts, src/cdk/portal/portal-injector.ts, src/material/bottom-sheet/bottom-sheet.ts, src/material/snack-bar/snack-bar.ts
Removes all of the remaining usages of the `PortalInjector` and marks it as deprecated.
=> refactor: remove remaining usages of PortalInjector

guides/creating-a-custom-form-field-control.md, src/components-examples/material-experimental/mdc-form-field/mdc-form-field-custom-control/example-tel-input-example.html, src/components-examples/material-experimental/mdc-form-field/mdc-form-field-custom-control/form-field-custom-control-example.ts, src/components-examples/material/form-field/form-field-custom-control/example-tel-input-example.html, src/components-examples/material/form-field/form-field-custom-control/form-field-custom-control-example.ts, src/material-experimental/mdc-form-field/form-field.ts, src/material/form-field/form-field.ts, src/material/select/select.ts, tools/public_api_guard/material/form-field.d.ts
Currently, the form-field always creates a label element as sibling
to projected form-field controls. For native controls, the label is
associated with the controls using the `for` attribute.
This doesn't work for custom controls which might not be based
on native controls. e.g. the `mat-select`. In those cases, the
appropriate aria attributes need to be applied with `aria-labelledby`
that refers to the label content element.
Since this is a common pattern for custom controls that don't use
native controls, we need to expose the element id for the label content.
Currently we already do this for the select, but just prefixed it with
an underscore. This denotes it as private API while there is obviously a
use-case for exposing this publicly. Best example is how the select _needs_ it. …
=> feat(form-field): expose label content element id for custom controls

src/material/paginator/paginator.html, src/material/paginator/paginator.ts, tools/public_api_guard/material/paginator.d.ts
Adds a new option to the MatPaginatorDefaultOptions that allows users to set the appearance of the page size form field in mat-paginator.
Fixes #16266
=> feat(mat-paginator): Optionally style the mat-paginator form-field

src/material-experimental/mdc-core/option/option.ts
The lint rule for lightweight tokens was introduced in parallel to the MDC option which lead to a failure in master. These changes resolve the failure.
=> build: fix lint failure in MDC option

src/cdk-experimental/menu/BUILD.bazel, src/cdk-experimental/menu/item-pointer-entries.spec.ts, src/cdk-experimental/menu/item-pointer-entries.ts, src/cdk-experimental/menu/menu-bar.spec.ts, src/cdk-experimental/menu/menu-bar.ts, src/cdk-experimental/menu/menu-item-radio.ts, src/cdk-experimental/menu/menu-item-trigger.ts, src/cdk-experimental/menu/menu-item.ts, src/cdk-experimental/menu/menu-stack.ts, src/cdk-experimental/menu/menu.ts
Add the ability to open/close a menu when a user clicks a menu trigger and when a user hovers over
menu items. Additionally, keep track of hovered menu items and sync them with the FocusKeyManager
allowing a user to continue with a keyboard where they left off with their mouse.
=> feat(cdk-experimental/menu): add the ability to open/close menus on mouse click and hover

src/cdk-experimental/menu/public-api.ts
Any third-party wanting to extend CdkMenu or CdkMenuBar will need to update the providers array
with the concrete component to inject for the Menu interface as well as act as a provider for the
MenuStack therefore requiring access to the injection token and MenuStack instance.
=> refactor(cdk-experimental/menu): export Menu interface injection token and MenuStack

src/cdk-experimental/menu/menu-item-trigger.ts
Remove the restriction on the CdkMenuItemTriggers selector forcing it to be placed alongside a
CdkMenuItem. This allows for more customization when the Cdk directives are extended.
=> refactor(cdk-experimental/menu): remove selector restriction on trigger forcing a menu item

src/material/tabs/tabs.md
The tabs overview was referencing an incorrect file name which caused it to break on the docs site.
Fixes #20141.
=> docs(tabs): fix incorrect file reference

src/cdk-experimental/menu/context-menu.spec.ts, src/cdk-experimental/menu/context-menu.ts, src/cdk-experimental/menu/menu-module.ts, src/cdk-experimental/menu/public-api.ts
Add a directive which opens an attached context menu when a user right clicks within the
triggering element. The context menu trigger also considers nested context menu triggers within
an element opting to open the lowest level non-disabled context menu.
=> feat(cdk-experimental/menu): add context menu trigger directive

src/material-experimental/mdc-theming/BUILD.bazel, src/material-experimental/mdc-theming/_all-theme.scss, src/material-experimental/mdc-theming/prebuilt/indigo-pink.scss, test/benchmarks/mdc/button/BUILD.bazel, test/benchmarks/mdc/button/app.module.ts, test/benchmarks/mdc/button/button.perf-spec.ts
* Add performance benchmark for mdc-button (identical to the perf benchmark for mat-button).
* Add `mat-core` and `mat-core-theme` to `mdc-theming/prebuilt/indigo-pink.scss`.
We noticed that the mdc-button's ripples were not working properly and thanks to @andrewseguin we were able to figure out that the mat-core and mat-core-theme mixins were not being included in material-experimental's indigo-pink.scss.
=> test(mdc-button): add performance tests for mdc-button

tools/postinstall/@bazel_typescript_tsc_wrapped_worker_cache_fix.patch, tools/postinstall/apply-patches.js
A very subtle issue has surfaced in our release output. Based on
previous builds that have been performed locally by the caretaker
performing the release, the release output might differ and contain
invalid module imports that break ES2015 output.
Notably the es2015 output is not primarily used by the CLI. It uses
the flat ES2015 output instead.
The issue surfaces because of a bug in `@bazel/typescript` where the
`moduleName` for source files is leaking between TSC worker runs. This
means that source files are incorrectly referenced by module name,
instead of relative path when the prodmode ES2015 output is built.
Deep paths to source files are not supported as per Angular Package format.
We patch the fix that is pending upstream to ensure our release output
works: …
=> build: fix release output containing invalid imports sometimes

src/material/button-toggle/button-toggle.md
The docs for button-toggle were not updated when the control was
switched from using native checkboxes and radio-buttons to button
elements with `aria-pressed`. This change corrects the docs to reflect
the current state of the control.
=> docs(material/button-toggle): update a11y section

src/material/bottom-sheet/bottom-sheet.md, src/material/dialog/dialog.md, test/benchmarks/material/button/app.module.ts, test/benchmarks/material/card/app.module.ts, test/benchmarks/material/checkbox/app.module.ts, test/benchmarks/material/chips/app.module.ts, test/benchmarks/material/form-field/app.module.ts, test/benchmarks/material/radio/app.module.ts, test/benchmarks/material/slide-toggle/app.module.ts, test/benchmarks/material/table/app.module.ts, test/benchmarks/mdc/card/app.module.ts
Passing in `providers: []` isn't necessary so these changes clean up the existing code.
=> chore: clean up unnecessary providers arrays from existing code

src/material-experimental/mdc-dialog/README.md
Adds a readme for the experimental MDC-based dialog
=> docs: add readme for MDC-based experimental dialog

src/cdk/scrolling/scrolling-module.ts
This designates ScrollingModule as the primary module for cdk/scrolling.
Fixes #20112
Screenshot:
=> docs(cdk/scrolling): make ScrollingModule the primary export (#20112)

src/cdk/a11y/focus-trap/focus-trap.spec.ts, src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/portal/portal.md, src/cdk/portal/portal.spec.ts, src/dev-app/portal/portal-demo.ts, src/google-maps/README.md, src/material-experimental/column-resize/column-resize.spec.ts, src/material-experimental/mdc-menu/menu.spec.ts, src/material/expansion/accordion.spec.ts, src/material/menu/menu.spec.ts
For a while we had linting to explicitly specify the `static` flag on queries and we eventually removed it in ece800463a6fdb02cc622e964eccd41599c9b5a0, but there are still some PRs going in that were written while the restriction was in place. These changes clean up the remaining instances.
=> test: clean up remaining dynamic query usages

src/cdk-experimental/dialog/dialog-container.ts, src/cdk-experimental/dialog/dialog.ts
We recently landed the MDC-based dialog. For this one, we changed
how the dialog initializes the focus trap, saves the previously
focused element, focuses the dialog container.
Previously, all of this this has been performed before the content
has been attached. The dialog used `Promise.resolve` to wait for
the content to be attached. This has been cleaned up now so that the
container is initialized properly (without the `Promise.resolve` trick)
after the content has been attached.
We initially did this in the MDC-based dialog PR through the
`ngAfterViewInit` lifecycle hook, but that unveiled issues
in g3 where the focus is moved too early to the container. We
fixed this in the Material dialog by having an explicit
`_initializeWithAttachedContent` method on the container.
The change has …
=> refactor(cdk-experimental/dialog): sync with recent material dialog changes

src/cdk-experimental/menu/menu-bar.spec.ts, src/cdk-experimental/menu/menu-item-trigger.ts
When hovering back over a menu item trigger in a menu bar which was clicked to open then closed, it
opens the submenu. This ensures that a menu attached to a trigger in a menu bar only opens on hover
if it has a sibling open.
=> fix(cdk-experimental/menu): re-open menu on hover after click to close on trigger

src/cdk-experimental/menu/context-menu.spec.ts, src/cdk-experimental/menu/context-menu.ts
By default on both Mac and Windows the context menu keyboard trigger is emitted as a contextmenu
mouse event automatically, eliminating the need to handle keyboard events specifically for context
menus. Therefore, this simply places focus on the first menu item in the opened context menu
relying on the existing menu and menu item keyboard handling logic.
=> feat(cdk-experimental/menu): enable keyboard handling for context menu

src/cdk-experimental/menu/menu-bar.ts, src/cdk-experimental/menu/menu-item-checkbox.ts, src/cdk-experimental/menu/menu-item-radio.ts, src/cdk-experimental/menu/menu.ts
Some of the Cdk directives are expected to be extended by some subclasses (e.g. material). In Ivy
the host metadata will be merged whereas in ViewEngine it will be overridden forcing duplication of
listeners in the host object on the subclass which results in double listeners in Ivy. Moving to
@HostListener prevents having to duplicate them in subclasses.
=> refactor(cdk-experimental/menu): move listeners from host object to host listener decorator

src/cdk-experimental/column-resize/column-resize-directives/column-resize-flex.ts, src/cdk-experimental/column-resize/column-resize-directives/column-resize.ts, src/cdk-experimental/column-resize/column-resize-directives/default-enabled-column-resize-flex.ts, src/cdk-experimental/column-resize/column-resize-directives/default-enabled-column-resize.ts, src/cdk-experimental/column-resize/column-resize-notifier.ts, src/cdk-experimental/column-resize/overlay-handle.ts, src/cdk-experimental/column-resize/resizable.ts, src/cdk-experimental/column-resize/resize-strategy.ts, src/cdk/table/coalesced-style-scheduler.ts, src/components-examples/material-experimental/column-resize/default-enabled-column-resize-flex/default-enabled-column-resize-flex-example.html, src/components-examples/material-experimental/column-resize/default-enabled-column-resize/default-enabled-column-resize-example.html, src/components-examples/material-experimental/column-resize/opt-in-column-resize/opt-in-column-resize-example.html, src/material-experimental/column-resize/BUILD.bazel, src/material-experimental/column-resize/_column-resize.scss, src/material-experimental/column-resize/column-resize.spec.ts, src/material-experimental/column-resize/overlay-handle.ts, src/material-experimental/column-resize/resizable-directives/default-enabled-resizable.ts, src/material-experimental/column-resize/resizable-directives/resizable.ts, src/material-experimental/column-resize/resize-strategy.ts
Coalesces style updates triggered by the column resize system to trigger less layout thrashing. Also updates sticky column styles when resizing a column.
The net effect is a substantial improvement when applying min/max sizes at startup and a bit of a wash when actively resizing. The gains in active resize performance are mostly offset by the additional cost of recomputing sticky styles (but it was a bug before that they were not being recomputed). Should be much better for tables without sticky columns though.
=> fix,perf(column-resize): Coalesce style updates along with sticky styler

src/cdk/table/cell.ts, src/material-experimental/mdc-table/cell.ts, src/material/table/cell.ts, tools/public_api_guard/cdk/table.d.ts, tools/public_api_guard/material/table.d.ts
Should be a slight code size improvement as well.
This is a non-breaking subset of #19743, which will have to wait for the next major version.
=> perf(table): Do column name string interpolation once per column instead of once per cell

src/dev-app/datepicker/datepicker-demo.html, src/dev-app/stepper/stepper-demo.html, src/material/paginator/paginator.html, src/material/select/select.html
Due to a bug in the template type checker, binding expressions that include
`undefined` in their type which are bound to directive inputs that don't accept
`undefined` would not be reported as an error, if the directive declares at
least one coercion member using `ngAcceptInputType`. angular/angular#38273
fixes this bug, which uncovers some template issues.
Long-term, it would be best if the directives would be updated to include
`undefined` in an input's type as appropriate. This would require a larger
effort and is likely to introduce some breaking changes to public API.
=> fix: add non-null assertions for non-nullable input bindings

.github/CODEOWNERS, src/cdk-experimental/combobox/BUILD.bazel, src/cdk-experimental/combobox/combobox-module.ts, src/cdk-experimental/combobox/combobox-panel.ts, src/cdk-experimental/combobox/combobox.ts, src/cdk-experimental/combobox/index.ts, src/cdk-experimental/combobox/public-api.ts, src/cdk-experimental/config.bzl, src/dev-app/BUILD.bazel
Created the skeleton for the combobox directive in cdk-experimental. Also added combobox to code owners.
=> Combobox skeleton

src/cdk/tree/tree.spec.ts, src/cdk/tree/tree.ts, src/material/tree/node.ts, src/material/tree/tree.spec.ts, tools/public_api_guard/cdk/tree.d.ts
Previously, only leaf nodes had aria-level applied.
This is an incremental change since this is an unfamiliar codebase for
me. The main benefit it will have on its own is that it will allow
anyone doing custom dom manipulation to know what level the node is on.
Otherwise by itself there is no change in how NVDA reads nodes with
children. (It currently reads them as literally "grouping"; no
information about the contents is provided).
This change will be necessary for a later change I'm planning, wherein
the role of parent nodes will be changed from "group" to "treeitem", in
accordance with how roles are applied in WAI-ARIA reference examples
such as
https://www.w3.org/TR/wai-aria-practices/examples/treeview/treeview-1/treeview-1b.html
=> fix(material/tree): Apply aria-level to all nodes

src/cdk/table/sticky-styler.ts, src/cdk/table/table.ts, src/material-experimental/mdc-table/BUILD.bazel, src/material-experimental/mdc-table/table.scss, src/material-experimental/mdc-table/table.ts, src/material/core/style/_vendor-prefixes.scss, src/material/table/BUILD.bazel, src/material/table/table.scss, src/material/table/table.ts, tools/public_api_guard/cdk/table.d.ts, tools/public_api_guard/material/table.d.ts
In the longer run, it'd be nice to remove the addition of inline styles entirely (and have some simple CSS attached to CdkTable).
=> perf(table): Slightly improve speed of adding/remvoing sticky styles

src/material/stepper/stepper-horizontal.html, src/material/stepper/stepper-vertical.html, src/material/stepper/stepper.spec.ts
A while ago in #14892 we added a `tabindex` to the content of the current step based on a recommendation from W3C a11y guidelines, however since then we consulted with the a11y team and it looks like adding the `tabindex` there isn't the best approach.
Fixes #16692.
=> fix(stepper): remove tabindex from content

src/cdk/overlay/position/flexible-connected-position-strategy.ts, src/material-experimental/popover-edit/popover-edit.spec.ts
`overflowBottom` is currently calculated with `viewport.bottom` (which could be any number from the height of the viewport to as large as your page is)
calculating the overflow should just be difference between `overlay.height + start.y` and the height of the viewport, not the height of the entire page.
Right now the overlay is pushed out of the view in certain cases.
=> fix(cdk/overlay): fix wrong overflow calculation

src/material-experimental/mdc-theming/BUILD.bazel, test/benchmarks/mdc/chips/BUILD.bazel, test/benchmarks/mdc/chips/app.module.ts, test/benchmarks/mdc/chips/chips.html, test/benchmarks/mdc/chips/chips.perf-spec.ts
=> test(mdc-chips): add performance tests for mdc-chips

test/benchmarks/mdc/slide-toggle/BUILD.bazel, test/benchmarks/mdc/slide-toggle/app.module.ts, test/benchmarks/mdc/slide-toggle/slide-toggle.perf-spec.ts
=> test(mdc-slide-toggle): add performance tests for mdc-slide-toggle

src/material-experimental/mdc-theming/BUILD.bazel, test/benchmarks/mdc/button/button.perf-spec.ts, test/benchmarks/mdc/form-field/BUILD.bazel, test/benchmarks/mdc/form-field/app.module.ts, test/benchmarks/mdc/form-field/form-field.perf-spec.ts
=> test(mdc-form-field): add performance tests for mdc-form-field

src/components-examples/material/stepper/stepper-overview/stepper-overview-example.html
The stepper overview was referring to a doc region that isn't defined which resulted in an error.
Fixes #20262.
=> doc(stepper): add missing doc region

src/material/datepicker/_datepicker-theme.scss, src/material/datepicker/calendar-body.html, src/material/datepicker/calendar-body.spec.ts, src/material/datepicker/calendar-body.ts, tools/public_api_guard/material/datepicker.d.ts
The logic that determines whether we show something as being a range doesn't allow for the start and end to be on the same date, because it increases the CSS complexity a lot. As a result, we aren't able to render ranges that start and end on the same day. This isn't a problem for the main range, because we style its start and end as selected which looks exactly the same as the start/end of a range, however it breaks down for the comparison range since it doesn't have the same selected styling for its start/end cells.
These changes fix the issue by introducing a special class for the case where the comparison range is for a single day. While it's not ideal, it's preferrable to complicating the CSS for the range styling.
Fixes #20100.
=> fix(datepicker): not showing single-day comparison ranges

src/material/datepicker/date-range-picker.ts, src/material/datepicker/date-range-selection-strategy.ts, src/material/datepicker/datepicker-module.ts, src/material/datepicker/public-api.ts
The default date range selection strategy was provided at the module level which meant that it wouldn't pick up custom date adapters down in the DI tree. These changes provide the token at the level of the range picker instead.
Fixes #19902.
=> fix(datepicker): range selection strategy not picking up custom date adapter

src/cdk/stepper/stepper.ts, src/material/stepper/stepper.spec.ts, src/material/stepper/stepper.ts, tools/public_api_guard/cdk/stepper.d.ts, tools/public_api_guard/material/stepper.d.ts
When we initially made some changes to handle Ivy, we made an assumption that people wouldn't nest steppers so we took one shortcut. It looks like that assumption wasn't correct so these changes make it possible to properly nest steppers again.
Fixes #18448.
=> fix(stepper): parent stepper picking up steps from child stepper

src/cdk-experimental/menu/menu-item-checkbox.spec.ts, src/cdk-experimental/menu/menu-item-checkbox.ts, src/cdk-experimental/menu/menu-item-radio.spec.ts, src/cdk-experimental/menu/menu-item-radio.ts
Fixes an issue where clicking a CdkMenuItemRadio or CdkMenuItemCheckbox causes the click handler to
fire twice resulting in toggling state twice and an unchecked checkbox.
=> fix(cdk-experimental/menu): fix double state toggle in radio and checkbox menu items

CODE_REVIEWS.md
The reviews guide was referring to the `lgtm` label which was removed recently.
=> docs: update reviews guide to remove lgtm label

src/cdk-experimental/menu/menu-bar.spec.ts, src/cdk-experimental/menu/menu-bar.ts, src/cdk-experimental/menu/menu.ts
Fixes an issue where clicking an item in an inline menu prevents any open popout menus from closing
out.
=> fix(cdk-experimental/menu): ensure menu is closed out when clicking on an inline menu item

src/cdk-experimental/menu/menu-bar.spec.ts, src/cdk-experimental/menu/menu-item-checkbox.ts, src/cdk-experimental/menu/menu-item-radio.ts, src/cdk-experimental/menu/menu-item.ts
The element under focus has a tab index of 0 while all others are set to -1. As other elements come
into focus, the previous elements tab index is reset to -1 and the newly focused element has a tab
index set to 0.
=> feat(cdk-experimental/menu): add roving tab index to menu items

src/cdk-experimental/menu/context-menu.spec.ts, src/cdk-experimental/menu/context-menu.ts, src/cdk-experimental/menu/menu-bar.spec.ts, src/cdk-experimental/menu/menu-bar.ts, src/cdk-experimental/menu/menu.ts
Fixes an issue which prevents an open context menu from closing out if clicked on a menu bar
element or on an inline menu. Further fixes an issue where opening a context menu does not close
out any open menu.
=> fix(cdk-experimental/menu): ensure context menu is closed out with other menu elements on page

src/components-examples/cdk/tree/cdk-tree-flat/cdk-tree-flat-example.html, src/components-examples/cdk/tree/cdk-tree-nested/cdk-tree-nested-example.html, src/components-examples/material/tree/tree-checklist/tree-checklist-example.html, src/components-examples/material/tree/tree-dynamic/tree-dynamic-example.html, src/components-examples/material/tree/tree-flat-overview/tree-flat-overview-example.html, src/components-examples/material/tree/tree-loadmore/tree-loadmore-example.html, src/components-examples/material/tree/tree-nested-overview/tree-nested-overview-example.html, src/material/schematics/ng-generate/tree/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html.template
A bunch of tree examples were copied off of each other and were referecing a non-existent property which resulted in an incorrect `aria-label`.
Fixes #20216.
=> docs(tree): fix typo in tree template

src/dev-app/cdk-experimental-menu/cdk-menu-demo.css, src/dev-app/cdk-experimental-menu/cdk-menu-demo.html
Refactor the dev-app to include inline menu and nested context menus, and clean up the menu bar
example.
=> refactor(cdk-experimental/menu): refactor the dev-app to include context menu and inline menu

.circleci/config.yml, package.json, scripts/build-docs-content.js, scripts/deploy/publish-docs-content.sh
Creates a script that builds the docs-content. We also use
that script in the our CI setup to reduce duplication.
The script will not pack the package by default, as that is
up to the consumer of the script and we do don't do it
for other release packages. It's totally fine just adding a package
directory to a project (similar to a tarball).
<sup>My concern with packing in those scripts is that it will unnecessarily
slow down builds on CI and packing is not necessarily fast for large packages</sup>
=> build: create script for building docs-content

test/benchmarks/material/tabs/BUILD.bazel, test/benchmarks/material/tabs/app.module.ts, test/benchmarks/material/tabs/fake-tab-data.ts, test/benchmarks/material/tabs/tabs.perf-spec.ts
* Renders a tab group with 3 tabs.
* Renders a tab group with 10 tabs.
* Switches between three tabs.
=> test(tabs): add performance tests for mat-tabs

src/dev-app/dev-app/dev-app-layout.html, src/dev-app/dev-app/dev-app-layout.ts
It's a pain to debug components' dark theme when every time you make a change the site reloads and goes back to light theme. This just makes it remember the previous value when the dev-app loads.
=> chore: store dev-app dark/light theme state in localStorage

src/material/datepicker/datepicker.md
Changes:
```diff
- They work in
+ They work in tandem,
similarly to the `mat-datepicker` and the basic datepicker input.
```
```diff
The `mat-date-range-picker` component acts
- the the
+ as the
pop-up panel for selecting dates.
```
=> docs(datepicker): fix various missing words

src/material/core/option/optgroup.ts, src/material/core/option/option.ts, src/material/dialog/dialog-container.ts, src/material/dialog/dialog.ts, src/material/snack-bar/snack-bar-container.ts
These statements are from PRs that were opened before we added our own rule for validating class names.
=> chore: clean up leftover tslint disable statements

src/cdk-experimental/menu/menu-bar.spec.ts
Fixes a test failure that seems to be due to a couple of overlapping PRs landing at the same time.
cc @andy9775
=> test(cdk-experimental/menu): fix test failure

src/material-experimental/mdc-dialog/dialog.spec.ts, src/material/dialog/dialog-container.ts, src/material/dialog/dialog.spec.ts
We recently refactored the Material dialog so that it can be used
as base class for the MDC based dialog. For this, we slightly changed
how animations are announced to the corresponding dialog ref. This
was done because the MDC dialog does not use Angular animations.
It looks like we slightly regressed in cases where the dialog container view
is destroyed immediately upon dialog close. This is because we accidentally
no longer notify the dialog ref if the dialog animation state goes from `*` to
`void`. Currently we only handle `*` to `exit` while we should also handle the
`void` state.
This issue has not surfaced in any of our tests, in the dev-app but one screenshot
test inside g3 seems flaky after the dialog refactor. This might fix it (given the
diff showing an extra backdrop if we …
=> fix(dialog): backdrop not detaching if container view is destroyed

src/material-experimental/mdc-checkbox/testing/checkbox-harness.ts, src/material-experimental/mdc-chips/chip-option.ts, src/material-experimental/mdc-chips/chip-row.ts, src/material-experimental/mdc-chips/testing/chip-grid-harness.ts, src/material-experimental/mdc-chips/testing/chip-harness.ts, src/material-experimental/mdc-chips/testing/chip-listbox-harness.ts, src/material-experimental/mdc-chips/testing/chip-option-harness.ts, src/material-experimental/mdc-chips/testing/chip-row-harness.ts, src/material-experimental/mdc-chips/testing/chip-set-harness.ts, src/material-experimental/mdc-progress-bar/testing/progress-bar-harness.ts, src/material-experimental/mdc-progress-spinner/testing/progress-spinner-harness.ts, src/material-experimental/mdc-slide-toggle/testing/slide-toggle-harness.ts, src/material-experimental/mdc-slider/testing/slider-harness.ts, src/material/button-toggle/testing/button-toggle-group-harness.ts, src/material/button-toggle/testing/button-toggle-harness.ts, src/material/card/testing/card-harness.ts, src/material/checkbox/testing/checkbox-harness.ts, src/material/divider/testing/divider-harness.ts, src/material/list/testing/action-list-harness.ts, src/material/list/testing/list-harness.ts, src/material/list/testing/list-item-harness-base.ts, src/material/list/testing/nav-list-harness.ts, src/material/list/testing/selection-list-harness.ts, src/material/progress-bar/testing/progress-bar-harness.ts, src/material/progress-spinner/testing/progress-spinner-harness.ts, src/material/radio/testing/radio-harness.ts, src/material/slide-toggle/testing/slide-toggle-harness.ts, src/material/slider/testing/slider-harness.ts, src/material/toolbar/testing/toolbar-harness.ts
We're using element selectors for some of the test harnesses which can conflict between the MDC and non-MDC components. These changes switch them to use class selectors, similarly to what we decided to do for the MDC component styles.
=> fix: remove element selectors from test harnesses

src/material/config.bzl, src/material/datepicker/date-range-input-parts.ts, src/material/datepicker/date-range-input.ts, src/material/datepicker/datepicker-base.ts, src/material/datepicker/datepicker-input.ts, src/material/datepicker/datepicker-toggle.ts, src/material/datepicker/month-view.ts, src/material/datepicker/testing/BUILD.bazel, src/material/datepicker/testing/calendar-cell-harness.ts, src/material/datepicker/testing/calendar-harness-shared.spec.ts, src/material/datepicker/testing/calendar-harness.spec.ts, src/material/datepicker/testing/calendar-harness.ts, src/material/datepicker/testing/date-range-input-harness-shared.spec.ts, src/material/datepicker/testing/date-range-input-harness.spec.ts, src/material/datepicker/testing/date-range-input-harness.ts, src/material/datepicker/testing/datepicker-harness-filters.ts, src/material/datepicker/testing/datepicker-input-harness-base.ts, src/material/datepicker/testing/datepicker-input-harness-shared.spec.ts, src/material/datepicker/testing/datepicker-input-harness.spec.ts, src/material/datepicker/testing/datepicker-input-harness.ts, src/material/datepicker/testing/datepicker-toggle-harness-shared.spec.ts, src/material/datepicker/testing/datepicker-toggle-harness.spec.ts, src/material/datepicker/testing/datepicker-toggle-harness.ts, src/material/datepicker/testing/datepicker-trigger-harness-base.ts, src/material/datepicker/testing/index.ts, src/material/datepicker/testing/public-api.ts, src/material/dialog/dialog-config.ts, tools/public_api_guard/material/datepicker.d.ts, tools/public_api_guard/material/datepicker/testing.d.ts, tools/public_api_guard/material/dialog.d.ts
* Sets up test harnesses for the components in the datepicker module. Includes datepicker input, datepicker toggle, calendar, calendar cell, date range input, date range input start/end sub-inputs.
* Fixes an issue in `mat-calendar` that showed up while adding unit tests for the harnesses. The standalone calendar wasn't picking up changes to the comparison range after init.
* Expands the dialog `backdropClass` signature to allow `string[]`. This was necessary for the harness so that we can tie a harness to a particular backdrop.
=> feat(datepicker/testing): add test harnesses for the datepicker module

src/material/checkbox/checkbox.ts, src/material/core/common-behaviors/color.spec.ts, src/material/core/common-behaviors/color.ts, src/material/core/common-behaviors/tabindex.spec.ts, src/material/core/common-behaviors/tabindex.ts, src/material/datepicker/datepicker-base.ts, tools/public_api_guard/material/core.d.ts
This is something that came up in #18467. Currently the default values in the `mixinColor` and `mixinTabIndex` are set when the mixin class is created, however we have some components where the default color can be configured through an injection token. These changes add a default field on each instance so that it can be updated after the class is instantiated.
**Note:** marking as a P2, because it's blocking another P2 PR (#18467).
=> fix(core): allow for default color and tabindex to be set per instance

.ng-dev/merge.ts, package.json, yarn.lock
We introduced a new shared configuration for merge script
labels that follow the new proposal:
https://docs.google.com/document/d/197kVillDwx-RZtSVOBtPb4BBIAw0E9RT3q3v6DZkykU
These label semantics and the new branching are set up for the Angular
Components repository with this commit. The goal is that labeling and
merging is consistent between all Angular projects and that clear rules
are defined for branching/labeling. This was previously not the case
=> build: use new labeling and branching in merge script

tools/postinstall/apply-patches.js
Currently when Bazel runs the Yarn postinstall, we might
prompt if the postinstall patches have been modified.
This prompt runs forever as there is no input TTY. We fix
this by not prompting if there is no TTY. i.e. always cleaning
up the node modules in that case.
=> build: do not prompt on postinstall in bazel yarn install

src/components-examples/material/stepper/stepper-editable/stepper-editable-example.html, src/components-examples/material/stepper/stepper-label-position-bottom/stepper-label-position-bottom-example.html, src/material/stepper/stepper.md
**Current behavior**:
... with errors on console.
Note that this started after #19680 due to the incorrect file name.
=> docs(stepper): correct file name in markdown

src/material-experimental/config.bzl, src/material-experimental/mdc-radio/testing/BUILD.bazel, src/material-experimental/mdc-radio/testing/index.ts, src/material-experimental/mdc-radio/testing/public-api.ts, src/material-experimental/mdc-radio/testing/radio-harness-filters.ts, src/material-experimental/mdc-radio/testing/radio-harness.spec.ts, src/material-experimental/mdc-radio/testing/radio-harness.ts
Adds test harnesses for the MDC-based radio button and radio button group.
=> feat(material-experimental/mdc-radio): add test harness

src/material-experimental/mdc-theming/BUILD.bazel, test/benchmarks/material/card/app.module.ts, test/benchmarks/material/checkbox/app.module.ts, test/benchmarks/material/chips/app.module.ts, test/benchmarks/material/form-field/app.module.ts, test/benchmarks/material/radio/app.module.ts, test/benchmarks/material/slide-toggle/app.module.ts, test/benchmarks/material/table/app.module.ts, test/benchmarks/mdc/button/app.module.ts, test/benchmarks/mdc/card/app.module.ts, test/benchmarks/mdc/checkbox/BUILD.bazel, test/benchmarks/mdc/checkbox/app.module.ts, test/benchmarks/mdc/checkbox/checkbox.perf-spec.ts
=> test(mdc-checkbox): add performance tests for mdc-checkbox

.github/CODEOWNERS, src/cdk-experimental/combobox/combobox-panel.ts, src/cdk-experimental/combobox/combobox.spec.ts, src/cdk-experimental/combobox/combobox.ts, src/dev-app/BUILD.bazel, src/dev-app/cdk-experimental-combobox/BUILD.bazel, src/dev-app/cdk-experimental-combobox/cdk-combobox-demo-module.ts, src/dev-app/cdk-experimental-combobox/cdk-combobox-demo.html, src/dev-app/cdk-experimental-combobox/cdk-combobox-demo.ts, src/dev-app/cdk-experimental-combobox/panel-content.ts, src/dev-app/dev-app/dev-app-layout.ts, src/dev-app/dev-app/routes.ts
Added simple combobox example to dev app and added a function to set the text of the combobox if the value is a string.
=> Combobox dev app

src/material/icon/icon-registry.ts
Some internal refactoring to improve the performance of the icon registry by avoiding unnecessary work:
* When an icon set is registered as a string literal, we parse it immediately into an SVG element. This is inefficient since the set may not be required immediately. These changes make it so that we store the SVG text and we only parse it when it's required.
* When an icon is requested, we try to find it in all any of the icon sets which requires us to parse them since we don't know which one is supposed to have it. These changes add an inexpensive `indexOf` check before parsing so that we can quickly rule out the sets that absolutely can't have the icon. The check won't exclude 100% of the unnecessary parsing, but it should help with the majority. Once this is in we could make it …
=> perf(icon): avoid unnecessarily parsing icon sets

src/material-experimental/menubar/BUILD.bazel, src/material-experimental/menubar/menubar-item.spec.ts, src/material-experimental/menubar/menubar-item.ts, src/material-experimental/menubar/menubar-module.ts, src/material-experimental/menubar/menubar.spec.ts, src/material-experimental/menubar/menubar.ts
Extends MatMenuBar and MatMenuBarItem from their CdkMenu equivalent directives and adds MenuBar and
MenuItem specific behaviours.
=> feat(material-experimental/menubar): extends components from cdk menu equivalents

src/material-experimental/config.bzl, src/material-experimental/mdc-card/testing/BUILD.bazel, src/material-experimental/mdc-card/testing/card-harness-filters.ts, src/material-experimental/mdc-card/testing/card-harness.e2e.spec.ts, src/material-experimental/mdc-card/testing/card-harness.spec.ts, src/material-experimental/mdc-card/testing/card-harness.ts, src/material-experimental/mdc-card/testing/index.ts, src/material-experimental/mdc-card/testing/public-api.ts, src/material/card/testing/shared.spec.ts
Sets up a test harness for the MDC-based `mat-card`. Also makes some changes to the shared tests since they were hardcoded to the non-MDC selectors.
=> feat(material-experimental/mdc-card): add test harness

src/material/slider/slider.spec.ts, src/material/slider/slider.ts
Currently when the user presses down somewhere on the slider we emit a `change` event, as well as when they release. While we don't emit the same value twice, the timing seems to be unexpected by consumers, because one happens at the begging of the sequence and another one at the end.
These changes make it so that we only emit the change event once the user has released the slider.
Fixes #14363.
**Note:** I'm setting it to P2, because it's a long standing issue that people keep bumping into.
=> fix(slider): don't emit change events on mousedown

src/material/datepicker/testing/calendar-harness-shared.spec.ts
Fixes a test failure that is due to a previous fix getting in around the same time as the datepicker harnesses. The problem is that the fix moved the default range selection strategy from the calendar to the range picker which in turn broke the harness unit tests, because they test a standalone calendar.
These changes fix the issue by providing a strategy manually for the tests.
=> test(datepicker/testing): fix test failure

src/cdk-experimental/combobox/BUILD.bazel, src/cdk-experimental/combobox/combobox-module.ts, src/cdk-experimental/combobox/combobox-panel.ts, src/cdk-experimental/combobox/combobox-popup.ts, src/cdk-experimental/combobox/combobox.spec.ts, src/cdk-experimental/combobox/combobox.ts, src/cdk-experimental/combobox/public-api.ts, src/dev-app/BUILD.bazel
New features include:
- Logic to handle multiple different open actions
- Coercion function for string -> open action
- Many additional tests
=> Combobox open actions

src/cdk-experimental/combobox/combobox.spec.ts, src/cdk-experimental/combobox/combobox.ts, src/cdk-experimental/listbox/BUILD.bazel, src/cdk-experimental/listbox/listbox.spec.ts, src/cdk-experimental/listbox/listbox.ts, src/dev-app/BUILD.bazel
Added logic necessary for CdkListbox to be used inside CdkComboboxPanel and be ready to communicate with its parent panel without any additional directives. Currently some changes exist that are already in another approved PR. Will rebase after that PR is merged.
=> Combobox listbox compatible

src/material-experimental/config.bzl, src/material-experimental/mdc-autocomplete/autocomplete-trigger.ts, src/material-experimental/mdc-autocomplete/testing/BUILD.bazel, src/material-experimental/mdc-autocomplete/testing/autocomplete-harness-filters.ts, src/material-experimental/mdc-autocomplete/testing/autocomplete-harness.spec.ts, src/material-experimental/mdc-autocomplete/testing/autocomplete-harness.ts, src/material-experimental/mdc-autocomplete/testing/index.ts, src/material-experimental/mdc-autocomplete/testing/public-api.ts, src/material-experimental/mdc-core/testing/BUILD.bazel, src/material-experimental/mdc-core/testing/index.ts, src/material-experimental/mdc-core/testing/optgroup-harness-filters.ts, src/material-experimental/mdc-core/testing/optgroup-harness.spec.ts, src/material-experimental/mdc-core/testing/optgroup-harness.ts, src/material-experimental/mdc-core/testing/option-harness-filters.ts, src/material-experimental/mdc-core/testing/option-harness.spec.ts, src/material-experimental/mdc-core/testing/option-harness.ts, src/material-experimental/mdc-core/testing/public-api.ts, src/material/core/testing/option-harness.spec.ts, src/material/core/testing/option-shared.spec.ts, tools/create-system-config.bzl
* Adds test harnesses for the `mdc-core` and `mdc-autocomplete` modules.
* Updates one of the classes on the MDC autocomplete trigger since it was the same as the one on the non-MDC version.
* Fixes a build issue where one `material-experimental` testing package couldn't depend on another one.
=> feat(material-experimental): add test harnesses for mdc-core and mdc-autocomplete

src/material-experimental/config.bzl, src/material-experimental/mdc-tabs/testing/BUILD.bazel, src/material-experimental/mdc-tabs/testing/index.ts, src/material-experimental/mdc-tabs/testing/public-api.ts, src/material-experimental/mdc-tabs/testing/tab-group-harness.spec.ts, src/material-experimental/mdc-tabs/testing/tab-group-harness.ts, src/material-experimental/mdc-tabs/testing/tab-harness-filters.ts, src/material-experimental/mdc-tabs/testing/tab-harness.ts
Adds test harnesses for the MDC-based tabs module.
=> feat(material-experimental/mdc-tabs): add test harnesses

src/material-experimental/config.bzl, src/material-experimental/mdc-card/testing/BUILD.bazel, src/material-experimental/mdc-table/testing/BUILD.bazel, src/material-experimental/mdc-table/testing/cell-harness.ts, src/material-experimental/mdc-table/testing/index.ts, src/material-experimental/mdc-table/testing/public-api.ts, src/material-experimental/mdc-table/testing/row-harness.ts, src/material-experimental/mdc-table/testing/table-harness-filters.ts, src/material-experimental/mdc-table/testing/table-harness.spec.ts, src/material-experimental/mdc-table/testing/table-harness.ts
Sets up test harnesses for the MDC-based table module.
=> feat(material-experimental/mdc-table): add test harnesses

src/cdk-experimental/menu/context-menu.spec.ts, src/cdk-experimental/menu/context-menu.ts, src/cdk-experimental/menu/menu-errors.ts, src/cdk-experimental/menu/menu-item-trigger.spec.ts, src/cdk-experimental/menu/menu-item-trigger.ts, src/cdk-experimental/menu/menu-item.ts, src/cdk-experimental/menu/menu-panel.ts, src/cdk-experimental/menu/menu-stack.ts
Fixes the error where two different menu triggers open the same menu which leads to open menus not
closing out on hover and other inconsistent behaviour. Opt to throw and error and not allow two
triggers to share a menu.
=> fix(cdk-experimental/menu): do not allow two separate triggers to open the same menu

src/components-examples/material/form-field/form-field-custom-control/form-field-custom-control-example.html, src/components-examples/material/form-field/form-field-custom-control/form-field-custom-control-example.ts
The custom input example wasn't showing how to implement the `errorState` getter which means that it can't show error messages.
Also fixes a place where we were using tabs for indentation.
Fixes #20269.
=> docs(form-field): implement error state getter in custom control example

src/material-experimental/menubar/menubar-item.spec.ts
Fixes a test failure that made it into master.
=> test(material-experimental/menubar): fix test failure

src/material/input/testing/input-harness.ts, src/material/input/testing/shared.spec.ts
The types of the `value` and `placeholder` filters allow both a string and a regex, but passing in a regex doesn't actually work because we were comparing the values directly instead of going through `stringMatches`.
=> fix(input/testing): filtering by regex not working

src/cdk/platform/features/scrolling.ts
We use the `supportsScrollBehavior` function to check whether to try and pass in the scroll options object to `Scrollable.scrollTo` since passing it in on a browser that doesn't support it won't do anything. The problem is that the only way to detect if scroll behavior is supported is to look for the `scrollBehavior` property on a DOM element's CSS styles, however this will cause scroll behavior polyfills to be ignored since they only modify `Element.prototype.scrollTo`.
These changes try to detect whether `scrollTo` has been polyfilled, and if it has, we consider it as being supported.
Fixes #17847.
=> fix(platform): detect and ignore scrollBehavior polyfills

src/material/progress-spinner/progress-spinner.html, src/material/progress-spinner/progress-spinner.spec.ts, src/material/progress-spinner/progress-spinner.ts, tools/public_api_guard/material/progress-spinner.d.ts
The spinner diameter is used in the `animation-name` CSS property for the indeterminate spinner `circle` element. If the diameter is a floating point value the animation name will include a period ‘.’ character e.g. `animation-name-90.6`. Period characters are not supported for the animation-name property - see https://developer.mozilla.org/en-US/docs/Web/CSS/animation-name.
Replacing the period character in the diameter string with an underscore fixes this issue e.g. `animation-name-90_6`
Fixes #20158
=> fix(material/progress-spinner): Progress spinner animation fails for floating point diameter values

src/material/datepicker/datepicker-base.ts
=> fix(datepicker): add coercion for opened input

src/cdk/drag-drop/clone-node.ts, src/cdk/drag-drop/directives/drag.spec.ts
We transfer input `value` property while cloning draggable element, but
with several radio inputs that have the same `name` attribute we can face an
issue when checked state moves to cloned radio input element and we can't restore it
when dropping element.
These changes add unique name for all cloned elements: radio inputs
inside preview and placeholder. This makes sure that original input
won't lose its checked state once the clone is inserted in the DOM.
Fixes #20236
=> fix(cdk/drag-drop): preserve checked state for grouped radio inputs

src/cdk/layout/breakpoints-observer.ts, tools/public_api_guard/cdk/layout.d.ts
This PR add support for `readonly string[]` for methods `isMatched` and `observe` as they doesn't accept it currently.
Also, I've refactored it a bit to remove some unnecessary type annotations.
=> fix(cdk/layout): support readonly arrays for public methods

src/components-examples/material/datepicker/datepicker-date-class/datepicker-date-class-example.ts, src/material/datepicker/calendar-body.ts, src/material/datepicker/calendar.html, src/material/datepicker/calendar.ts, src/material/datepicker/datepicker-base.ts, src/material/datepicker/month-view.spec.ts, src/material/datepicker/month-view.ts, src/material/datepicker/multi-year-view.spec.ts, src/material/datepicker/multi-year-view.ts, src/material/datepicker/year-view.spec.ts, src/material/datepicker/year-view.ts, tools/public_api_guard/material/datepicker.d.ts
We have a `dateClass` input that allows consumers to set classes to particular date cells, however currently we only invoke it inside the month view. These changes pass it along to the year and multi-year views too and provide the name of the view that invoked it so that cases like the first date of a month and a month cell can be distinguished.
Fixes #20017.
=> fix(datepicker): support dateClass on year and multi-year views

src/material/table/table.scss
The styles that reset the padding in RTL shouldn't apply to single-cell rows. Also moves a bit of code around so we don't have to repeat top-level selectors as much.
Fixes #20265.
=> fix(table): incorrect padding for single-cell rows in rtl

src/material-experimental/mdc-autocomplete/autocomplete.spec.ts, src/material-experimental/mdc-dialog/dialog.spec.ts
After #20165 the CI:lint started to fail due to these leftover usages.
=> refactor: remove missing asObservable usages

src/material-experimental/mdc-autocomplete/autocomplete-trigger.ts, src/material-experimental/mdc-autocomplete/autocomplete.spec.ts, src/material/autocomplete/autocomplete-trigger.ts, src/material/autocomplete/autocomplete.spec.ts, tools/public_api_guard/material/autocomplete.d.ts
Historically `mat-select` and `mat-autocomplete` have behaved very similarly, because they were written around the same time and they share some logic by depending on `mat-option`. `mat-select` has to know all the option heights ahead of time so that it can position its panel correctly over the trigger. The limitation made its way into `mat-autocomplete`, even though there's no reason for it to be there.
While implementing the MDC-based autocomplete, I refactored some code that makes it easier to support variable-height options so these changes enable the functionality for the non-MDC autocomplete too.
DEPRECATED:
* `AUTOCOMPLETE_OPTION_HEIGHT` is deprecated, because it isn't being used anymore.
* `AUTOCOMPLETE_PANEL_HEIGHT` is deprecated, because it isn't being used anymore.
Fixes …
=> feat(autocomplete): support variable option height

src/cdk/drag-drop/directives/drag-handle.ts, src/cdk/drag-drop/directives/drag.spec.ts
This came up from #19919, although it's not the root cause. We were disabling the native drag interactions on the handle element in two places which is redundant. These changes remove one of them and add a unit test since we were missing coverage.
=> fix(drag-drop): remove redundant style changes from handle directive

src/material/list/BUILD.bazel, src/material/list/selection-list.spec.ts, src/material/list/selection-list.ts, tools/public_api_guard/material/list.d.ts
We have some logic that redirects focus to the first option whenever the list receives focus. The main target for this is tabbing into the list, but because we were using the `focus` event, it was also happening for mouse focus which can cause the page to jump around for long lists. These changes make it so that we only move it on keyboard and programmatic focus.
Fixes #18948.
=> fix(list): don't redirect focus to first option on mouse focus

src/material/badge/badge.spec.ts, src/material/badge/badge.ts, tools/public_api_guard/material/badge.d.ts
Currently the badge's content is limited to `string` which excludes other legitimate use cases like numbers. These changes turn it into an `string | number | undefined | null` since we aren't actually doing anything with the value, apart from forwarding it.
Fixes #20326.
=> fix(badge): allow more data types for badge content

src/material-experimental/mdc-menu/_menu-theme.scss
Button menu items have the default button typography styles applied instead of the inherited typography from `.mat-mdc-menu-content`. You can observe this at https://material2-dev.firebaseapp.com/mdc-menu - see that the menu items are set to `Arial` instead of `Roboto`
=> fix(material-experimental/mdc-menu): apply typography to button menu items

src/material-experimental/mdc-chips/chip-default-options.ts, src/material-experimental/mdc-chips/chip-input.ts, src/material-experimental/mdc-chips/chip.ts, src/material/chips/chip-default-options.ts, src/material/chips/chip-input.ts, tools/public_api_guard/material/chips.d.ts
Currently if I try to pass immutable collections with `strictTemplates` I get an error.
=> fix(chips): support readonly collections in inputs

src/material/list/selection-list.spec.ts, src/material/list/selection-list.ts
When the value of a `mat-list-option` is updated, the `mat-selection-list` `compareWith` function should be used to compare the new value with the old value. This prevents options from being incorrectly unselected when the option value is updated.
=> fix(list): determine if option value changed (#19828)

src/material-experimental/config.bzl, src/material-experimental/mdc-snack-bar/testing/BUILD.bazel, src/material-experimental/mdc-snack-bar/testing/index.ts, src/material-experimental/mdc-snack-bar/testing/public-api.ts, src/material-experimental/mdc-snack-bar/testing/snack-bar-harness-filters.ts, src/material-experimental/mdc-snack-bar/testing/snack-bar-harness.spec.ts, src/material-experimental/mdc-snack-bar/testing/snack-bar-harness.ts, src/material/snack-bar/testing/shared.spec.ts, src/material/snack-bar/testing/snack-bar-harness.spec.ts
Adds a test harness for the MDC-based snack bar. One gotcha here compared to the standard snack bar is that the harness excludes (via a CSS selector) instances that are in the process of being closed. We have to take this approach, because MDC's animations are run outside of Angular and we don't have a way of waiting for them to finish.
=> feat(material-experimental/mdc-snack-bar): add test harness

src/dev-app/menubar/BUILD.bazel, src/dev-app/menubar/mat-menubar-demo-module.ts, src/dev-app/menubar/mat-menubar-demo.html, src/dev-app/menubar/mat-menubar-demo.scss, src/dev-app/menubar/mat-menubar-demo.ts
Fake mat-menu and mat-menu-item in the dev-app in order to aid in development of mat-menubar.
Once mat-menu extends CdkMenu, the fakses should be removed.
=> feat(material-experimental/menubar): update the dev-app to include a fake mat-menu

src/material-experimental/mdc-table/table.scss
MDC applies a `table-layout: fixed` style to their table. This is backwards incompatible with our current table, so this style addition overrides it with a reset
=> fix(material-experimental/mdc-table): reset table layout

integration/ts-compat/BUILD.bazel, package.json, src/cdk-experimental/tsconfig-tests.json, src/cdk/tsconfig-tests.json, src/google-maps/tsconfig-tests.json, src/material-experimental/tsconfig-tests.json, src/material-moment-adapter/tsconfig-tests.json, src/material/tsconfig-tests.json, tools/package-tools/ts-compile.ts, yarn.lock
**build: point to typescript node_modules folder instead of `.bin`**
Since we are installing multiple TS versions https://github.com/angular/components/blob/1f6b90c0a515397526d7c6b35f047827bfaa8652/package.json#L170-L173 yarn will link the last tsc binary which may not be the TSC version we want to use to build/test this reproduction.
Currently with the following package.json packages
```
"typescript": "3.9.5",
"typescript-3.6": "npm:typescript@~3.6.4",
"typescript-3.7": "npm:typescript@~3.7.0",
"typescript-3.8": "npm:typescript@~3.8.0",
```
If we run `npx tsc --v` the output will be `Version 3.8.3` as opposed to `3.9.5`
**build: update tests to use UMD module format**
The current version of system.js used doesn't seem to handle the `exports` correctly for TypeScript 3.9 output and causes …
=> tests: remove unsupported TS integration tests

src/material-experimental/mdc-helpers/_focus-indicators.scss
The MDC-based `mat-option` had the proper strong focus indicator class, but the styles weren't implemented.
=> fix(material-experimental/mdc-core): set up strong focus indication for MDC-based option

src/material-experimental/mdc-menu/testing/menu-harness.spec.ts, src/material-experimental/mdc-menu/testing/menu-harness.ts, src/material/menu/testing/shared.spec.ts
Adds the logic for the methods that weren't implemented for the MDC-based menu harness.
=> fix(material-experimental/mdc-menu/testing): add unimplemented methods

.github/CODEOWNERS, src/dev-app/list/list-demo.html, src/dev-app/mdc-list/BUILD.bazel, src/dev-app/mdc-list/mdc-list-demo-module.ts, src/dev-app/mdc-list/mdc-list-demo.html, src/material-experimental/mdc-checkbox/_checkbox-theme.scss, src/material-experimental/mdc-list/BUILD.bazel, src/material-experimental/mdc-list/_interactive-list-theme.scss, src/material-experimental/mdc-list/_list-option-theme.scss, src/material-experimental/mdc-list/_list-theme.scss, src/material-experimental/mdc-list/action-list.ts, src/material-experimental/mdc-list/interactive-list-base.ts, src/material-experimental/mdc-list/list-base.ts, src/material-experimental/mdc-list/list-item.html, src/material-experimental/mdc-list/list-option.html, src/material-experimental/mdc-list/list-option.scss, src/material-experimental/mdc-list/list-option.ts, src/material-experimental/mdc-list/list.scss, src/material-experimental/mdc-list/list.spec.ts, src/material-experimental/mdc-list/list.ts, src/material-experimental/mdc-list/module.ts, src/material-experimental/mdc-list/nav-list.ts, src/material-experimental/mdc-list/public-api.ts, src/material-experimental/mdc-list/selection-list.spec.ts, src/material-experimental/mdc-list/selection-list.ts, src/material/list/list.ts, src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.html, src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.ts, src/universal-app/kitchen-sink/kitchen-sink.html
Implements the MDC-based selection list. Accessibility and various
other concepts/features of the MDC list have been audited. Issues
have been reported upstream and workarounds where possible and
reasonable have been applied w/ proper comments.
https://github.com/material-components/material-components-web/issues?q=is%3Aissue+author%3Adevversion+mdc-list+.
Also various other remaining tasks for the MDC-based list have
been completed/resolved, except for implementing the dense attribute.
It's unclear yet how that can work out.
=> feat(material-experimental/mdc-list): implement selection list

guides/creating-a-custom-form-field-control.md, src/components-examples/material-experimental/mdc-form-field/mdc-form-field-custom-control/example-tel-input-example.html, src/components-examples/material-experimental/mdc-form-field/mdc-form-field-custom-control/form-field-custom-control-example.ts, src/components-examples/material/form-field/form-field-custom-control/example-tel-input-example.html, src/components-examples/material/form-field/form-field-custom-control/form-field-custom-control-example.ts, src/material-experimental/mdc-form-field/form-field.ts, src/material-experimental/mdc-input/input.spec.ts, src/material-experimental/mdc-input/input.ts, src/material/form-field/form-field-control.ts, src/material/form-field/form-field.ts, src/material/input/input.spec.ts, src/material/input/input.ts, tools/public_api_guard/material/form-field.d.ts, tools/public_api_guard/material/input.d.ts
The form-field notifies controls whenever hints or errors have
been displayed. It does this, so that controls like the input
can refresh their `aria-describedby` value to point to the errors
and hints.
This currently has the downside of overriding existing
`aria-describedby` values that have been manually set by
developers. We could fix this by reading the initial value
and merging it with the ids received from the form-field.
Fixes #19528
=> fix(material/input): do not override existing aria-describedby value

src/dev-app/google-map/google-map-demo.html, src/dev-app/google-map/google-map-demo.ts, src/google-maps/google-maps-module.ts, src/google-maps/map-base-layer.ts, src/google-maps/map-bicycling-layer/map-bicycling-layer.spec.ts, src/google-maps/map-bicycling-layer/map-bicycling-layer.ts, src/google-maps/map-traffic-layer/map-traffic-layer.spec.ts, src/google-maps/map-traffic-layer/map-traffic-layer.ts, src/google-maps/map-transit-layer/map-transit-layer.spec.ts, src/google-maps/map-transit-layer/map-transit-layer.ts, src/google-maps/public-api.ts, src/google-maps/testing/fake-google-map-utils.ts, tools/public_api_guard/google-maps/google-maps.d.ts
Implement components to easily add a traffic, transit or bicycling layer
to an Angular Google Map.
=> feat(google-maps): Add Layer components.

src/cdk-experimental/listbox/listbox.ts, src/cdk/a11y/key-manager/list-key-manager.ts, src/cdk/stepper/stepper.ts, src/material-experimental/mdc-chips/chip-grid.ts, src/material-experimental/mdc-chips/chip-listbox.ts, src/material-experimental/mdc-chips/grid-key-manager.ts, src/material/chips/chip-list.ts, src/material/expansion/accordion.ts, src/material/list/selection-list.spec.ts, src/material/list/selection-list.ts, src/material/menu/menu.ts, src/material/select/select.ts, src/material/tabs/paginated-tab-header.ts, tools/public_api_guard/cdk/a11y.d.ts
Based on top of #19834, changes the places where we were handling home/end to go through the key manager.
Also allows `withHomeAndEnd` to be turned off, similarly to what we're doing with the other methods.
cc @vanessanschmitt
=> refactor: handle home/end presses through key manager

src/material/select/select.html, src/material/select/select.spec.ts, src/material/select/select.ts, src/material/select/testing/select-harness.ts, tools/public_api_guard/material/select.d.ts
Applies some of our recent learnings on how to handle the accessibility of a custom select to `mat-select`. Includes switching the trigger to be a `combobox` and the panel to a `listbox`.
Fixes #11083.
=> fix(select): use combobox pattern for accessibility

src/cdk/coercion/BUILD.bazel, src/cdk/keycodes/BUILD.bazel, src/circular-deps-test.conf.js, src/google-maps/testing/BUILD.bazel, tools/defaults.bzl
Fixes a few places that are inconsistent by using `1` instead of `True`.
Also fixes one place where we were using the incorrect wording in a license header.
=> build: clean up uses of integers as booleans in Bazel files

src/material-experimental/mdc-form-field/form-field.ts, src/material/form-field/form-field.ts, src/material/icon/icon-registry.ts, src/material/icon/icon.ts
Revert the latest change to `src/material/icon/icon-registry.ts` and `src/material/icon/icon.ts` (See PR #20146).
Add a type to `src/material/form-field/form-field.ts` to ensure `userAriaDescribedBy` is a string before calling .split.
These changes resolved internal failures where 1. icons stopped showing up and were caught by a screenshot test, and 2. calling .split was causing an error and it was discovered that `userAriaDescribedBy` was an object.
=> Patch fixes for latest sync

src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.spec.ts, src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.ts
When an event handler listening to the `outsidePointerEvents` observable closes out any open
overlays this removes them from the OverlayOutsideClickDispatcher's array of overlay elements. This
results in an error being thrown since the overlays array in the for-loop is modified (elements are
removed) and the counter not accounting for this. This fix ensures that if the array of overlay
refs is modified we don't get an off by 1 error when fetching an element from the array on
subsequent iterations of the loop.
=> fix(cdk/overlay): ensure error isn't thrown when many overlay items are closed from handler

src/cdk/drag-drop/public-api.ts, tools/public_api_guard/cdk/drag-drop.d.ts
A couple of injection tokens weren't exposed from the `drag-drop` module. Normally these sorts of tokens would be internal, but the code from the `drag-drop` module is meant to be extended so we have to expose them to allow people to reach the same level of functionality.
Fixes #20406.
=> fix(drag-drop): expose some missing injection tokens

src/cdk-experimental/combobox/combobox.spec.ts, src/cdk-experimental/combobox/combobox.ts
The combobox was leaving behind its open overlays when it gets destroyed, because it wasn't calling `OverlayRef.dispose`.
=> fix(cdk-experimental/combobox): not cleaning up overlay on destroy

src/cdk/accordion/accordion.spec.ts, src/cdk/overlay/fullscreen-overlay-container.spec.ts, src/cdk/overlay/overlay-container.spec.ts, src/cdk/portal/portal.spec.ts, src/cdk/text-field/autofill.spec.ts, src/material-experimental/column-resize/column-resize.spec.ts, src/material-experimental/mdc-table/table.spec.ts, src/material-experimental/mdc-tabs/tab-body.spec.ts, src/material/table/table-data-source.spec.ts, src/material/table/table.spec.ts, src/material/tabs/tab-body.spec.ts
When Ivy issues were first being resolved in the repo, we accumulated a lot of static queries in tests which we generally shouldn't be depending on. These changes clean up most of the ones that don't require much refactoring to clean up. I'll make some follow-up changes for the trickier ones once these changes land.
=> test: reduce reliance on static queries

src/material-experimental/mdc-core/option/option.scss
The active option indication wasn't visible in high contrast mode, because it's based on the option's background color.
=> fix(material-experimental/mdc-core): active option not visible in high contrast mode

scripts/approve-api-golden.js, scripts/run-component-tests.js, scripts/util.js
Currently we have to write the full path for the API golden approval script, whereas the `test` script supports shorthands. These changes move the logic that guesses the name of a package out into a separate file so that it can be reused in the `approve-api` script.
=> build: add support for shorthand names in API golden approval script

src/material-experimental/mdc-button/button.scss
The MDC-based FAB don't need an extra outline high contrast mode, because they have one already.
=> fix(material-experimental/mdc-button): double outline for FAB in high contrast mode

src/material-experimental/mdc-dialog/dialog.scss
The MDC dialog was blending in with the page background, because it doesn't have a border or an outline.
=> fix(material-experimental/mdc-dialog): blending in with background in high contrast mode

src/universal-app/kitchen-sink/kitchen-sink.html
A few new layer components were added to the `google-maps` module. These changes add them to the SSR kitchen sink.
=> build(google-maps): add server-side rendering checks for new layers

.circleci/config.yml, package.json, tools/defaults.bzl
Running e2e test targets locally means that Bazel will re-run
them a second time if they fail. This slows-down local development
as there is no way to see the test failure before Bazel completed
the second run. We should not consider e2e tests as flaky locally.
Developers could re-run the test themselves if they see it being
flaky. Also flaky e2e tests only seem to happen if lots of e2e
tests execute concurrently. This is not often the case locally.
=> build: do not consider e2e test targets as flaky locally

src/cdk-experimental/menu/context-menu.spec.ts, src/cdk-experimental/menu/context-menu.ts, src/cdk-experimental/menu/menu-bar.spec.ts, src/cdk-experimental/menu/menu-bar.ts, src/cdk-experimental/menu/menu-item-radio.ts, src/cdk-experimental/menu/menu-item-trigger.spec.ts, src/cdk-experimental/menu/menu-item-trigger.ts, src/cdk-experimental/menu/menu-item.ts
Adds the ability to open a menu from a menu trigger placed outside of a menu or menubar.
=> feat(cdk-experimental/menu): add ability to open menus from a standalone trigger

src/cdk/testing/testbed/unit-test-element.ts
change detection should be triggered before reading element state and after interacting with an element
=> fix(cdk/testing): fix change detection timing in testbed

src/components-examples/cdk/portal/cdk-portal-overview/cdk-portal-overview-example.ts, src/components-examples/material/table/table-overview/table-overview-example.ts, src/components-examples/material/table/table-pagination/table-pagination-example.ts, src/components-examples/material/table/table-sorting/table-sorting-example.ts, src/components-examples/material/table/table-wrapped/table-wrapped-example.ts
Removes (almost) all of the static queries from the live examples since it's something people shouldn't be depending on. There's one place left which can't be removed without changes in the table code.
=> docs: reduce reliance on static queries in live examples

src/material-experimental/mdc-autocomplete/autocomplete.spec.ts, src/material/autocomplete/autocomplete-trigger.ts, src/material/autocomplete/autocomplete.spec.ts, src/material/autocomplete/autocomplete.ts, tools/public_api_guard/material/autocomplete.d.ts
Necessary for implementing the Google Material version internally, which relies on being able to provide options to the autocomplete to automatically apply a Google Material class
=> feat(material/autocomplete): add panelClass default option

package.json, scripts/check-mdc-tests.ts, scripts/tsconfig.json
Adds a script that will find and log out the names of Material unit tests that don't exist in the equivalent MDC component. Note that right now it's something we'd run manually, but the idea is to eventually have it on the CI, once all the tests have been added and we have the ability to exclude some tests that aren't relevant for MDC.
=> build: add a script to flag missing unit tests in MDC packages

src/material-experimental/mdc-chips/chip-row.ts, src/material-experimental/mdc-chips/chip.ts, src/material/chips/chip.ts, src/material/schematics/ng-update/data/constructor-checks.ts, tools/public_api_guard/material/chips.d.ts
Removes the APIs that were marked for deprecation in v11. I also decided to un-deprecate making the `animationMode` parameters required, because there's no good reason for them to be mandatory.
* `_changeDetectorRef` and `_document` parameters of the `MatChip` constructor are now required. Also the order of some constructor parameters has changed.
* `elementRef` parameter of the `MatChipRemove` constructor is now required.
=> refactor(chips): remove deprecated APIs for v11

src/cdk/table/BUILD.bazel, src/cdk/table/sticky-styler.ts, src/cdk/table/table.scss, src/cdk/table/table.ts, src/components-examples/cdk/table/cdk-table-fixed-layout/cdk-table-fixed-layout-example.css, src/components-examples/cdk/table/cdk-table-fixed-layout/cdk-table-fixed-layout-example.html, src/components-examples/cdk/table/cdk-table-fixed-layout/cdk-table-fixed-layout-example.ts, src/components-examples/cdk/table/index.ts, src/dev-app/table/table-demo.html, src/material-experimental/mdc-table/table.ts, src/material/table/table.scss, src/material/table/table.ts, tools/public_api_guard/cdk/table.d.ts
- Adds `fixedColumnWidths` input to the CDK table. When `true`, native tables will display with `table-layout: fixed`. No-op for flex tables.
- Reduces the number of times sticky styles are recalculated for native fixed layout tables and flex tables.
- `fixedLayout` might make a better name for the input. Preferences?
=> feat(cdk/table): fixed table layouts

src/cdk/schematics/ng-update/data/constructor-checks.ts, src/cdk/scrolling/scroll-dispatcher.ts, src/cdk/scrolling/viewport-ruler.ts, src/cdk/scrolling/virtual-scroll-viewport.ts, src/material/autocomplete/autocomplete-trigger.ts, tools/public_api_guard/cdk/scrolling.d.ts
* The `document` parameter of the `ScrollDispatcher` constructor is now required.
* The `document` parameter of the `ViewportRuler` constructor is now required.
* The `viewportRuler` parameter of the `CdkVirtualScrollViewport` constructor is now required.
Also bumps two autocomplete APIs that were only marked as deprecated 10 days ago to v12 instead of v11.
=> refactor(cdk/scrolling): remove deprecated APIs for v11

src/cdk/tree/tree-module.ts
`CdkTreeNodeDef` is a directive and should not be included in the providers
=> fix(cdk/tree): remove CdkTreeNodeDef from CdkTreeModules providers

src/material-experimental/mdc-theming/_all-theme.scss
previously excluded in https://github.com/angular/components/pull/20048 to keep it merge safe
=> fix(progress-spinner) add theme for mdc-progress-spinner

src/material/datepicker/date-range-input.spec.ts, src/material/datepicker/date-range-input.ts, src/material/datepicker/datepicker-base.ts, src/material/datepicker/datepicker-input-base.ts, src/material/datepicker/datepicker-input.ts, src/material/datepicker/datepicker-toggle.ts, src/material/datepicker/datepicker.spec.ts, tools/public_api_guard/material/datepicker.d.ts
If a function is used to provide a new date object for the `min` or `max` of a datepicker input, we currently trigger a revalidation on each change detection, because the input value is technically different. Historically this is something that we haven't fixed on our end, because it masks an anti-pattern on the user's end, however in this case it breaks in a non-obvious way and detecting it would be more code than just handling it.
These changes add checks in several places so that we don't trigger validators or extra change detections if a new date object for the same date is provided.
These changes also clean up the date range input which had both a `stateChanges` and `_stateChanges` streams which are required by two separate interfaces. Now there's a single `stateChanges`.
Fixes …
=> fix(datepicker): don't revalidate if new date object for same date is passed through input

src/material/datepicker/calendar.ts, src/material/datepicker/datepicker-base.ts, src/material/datepicker/datepicker-input.ts, src/material/schematics/ng-update/data/constructor-checks.ts, src/material/schematics/ng-update/data/property-names.ts, tools/public_api_guard/material/datepicker.d.ts
Removes the APIs that were marked as deprecated for v11 in the datepicker module.
* The value emitted by `MatCalendar.selectedChange` can now be null.
* `MatDatepickerInput.getPopupConnectionElementRef` has been removed. Use `getConnectedOverlayOrigin` instead.
* The `_changeDetectorRef`, `_model`, `_dateAdapter` and `_rangeSelectionStrategy` parameters of the `MatDatepickerContent` constructor are now required.
=> refactor(datepicker): remove deprecated APIs for v11

src/material-experimental/mdc-helpers/_focus-indicators.scss, src/material-experimental/mdc-list/list-base.ts, src/material-experimental/mdc-list/list-item.html, src/material-experimental/mdc-list/list-option.html, src/material-experimental/mdc-list/list.scss, src/material-experimental/mdc-list/list.spec.ts, src/material-experimental/mdc-list/selection-list.spec.ts
=> mdc-list: support for strong focus indicators and fix incorrect cursor for non-interactive items

src/google-maps/README.md, src/google-maps/google-map/README.md, src/google-maps/map-bicycling-layer/README.md, src/google-maps/map-circle/README.md, src/google-maps/map-ground-overlay/README.md, src/google-maps/map-info-window/README.md, src/google-maps/map-kml-layer/README.md, src/google-maps/map-marker/README.md, src/google-maps/map-polygon/README.md, src/google-maps/map-polyline/README.md, src/google-maps/map-rectangle/README.md, src/google-maps/map-traffic-layer/README.md, src/google-maps/map-transit-layer/README.md
Add new Google Maps components to documentation, including MapPolygon,
MapPolyline, MapRectangle, MapCircle, MapGroundOverlay, MapKmlLayer,
MapTransitLayer, MapTrafficLayer, and MapBicyclingLayer. Add
instructions on how to lazy load the Google Maps JavaScript API for use
with the @angular/google-maps components.
=> docs(google-maps): Improve documentation for Google Maps.

src/cdk-experimental/column-resize/resize-strategy.ts, src/cdk/table/coalesced-style-scheduler.ts, src/cdk/table/sticky-styler.ts, src/cdk/table/table.ts, src/material-experimental/column-resize/overlay-handle.ts, src/material-experimental/column-resize/resizable-directives/default-enabled-resizable.ts, src/material-experimental/column-resize/resizable-directives/resizable.ts, src/material-experimental/column-resize/resize-strategy.ts, src/material-experimental/mdc-table/table.ts, src/material/table/table.ts, tools/public_api_guard/cdk/table.d.ts
In #19964 and #19750 some breaking constructor changes were made which eventually got released as a part of a patch branch which doesn't follow our breaking changes policy.
These changes make the new constructor parameters optional and add fallbacks to the old behavior.
Fixes #20422.
cc @kseamon @MichaelJamesParsons
=> fix(cdk/table): resolve breaking constructor changes

src/material/menu/menu-animations.ts
This seems to be a remnant of the old menu animation. Previously when a menu was opened, we had a two step animation: scale and fade in the panel and then fade in the items a little bit later.
When the latest Material design spec update was implemented, the animation was simplified to a fade in and scale only, however some of the metadata doesn't seem to have been cleaned up which is causing an issue where we set an `opacity` on the items when we close the panel for the first time, but there's nothing resetting it the next time around which ends up causing the entire animation to be skipped.
Fixes #20379.
**Note:** setting this as a P2, because it's a regression.
=> fix(menu): open animation not working on repeat opens

.github/workflows/lock-closed.yml
Update to the latest lock-closed action to fix the link which is used.
=> build: bump to lastest sha of angular/dev-infra's lock-closed action

guides/using-component-harnesses.md
fix(material/docs): typo "synax" to "syntax"
=> docs(guide/using-component-harnesses): fix typo "synax" to "syntax"

packages.bzl
We've been using the MDC v8.0.0 canary version pipeline for quite
a while now, but our peer dependency was left on v6.0.0. This commit
updates the peer dependency to the current version we use for
development of the experimental MDC components. We cannot guarantee
compatibility with the older canary versions of MDC as there have
been quite a lot of changes and we actively develop with the most
recent canary versions.
Note that the peer dependency can quickly become outdated, but
it's better being on the correct major at least.
**Note**: Marked as `feat` so that it shows up in the changelog as it might
be useful for the experimental package.
=> feat(material-experimental): bump peer dependency to MDC v8.0.0 canary

src/material-experimental/mdc-dialog/README.md
Fixes a missing space in the MDC dialog readme.
=> docs: fix missing space in mdc-dialog readme

src/cdk/testing/protractor/protractor-element.ts, src/cdk/testing/test-element.ts, src/cdk/testing/testbed/unit-test-element.ts, src/cdk/testing/tests/cross-environment.spec.ts, src/cdk/testing/tests/harnesses/main-component-harness.ts, src/cdk/testing/tests/test-main-component.html, src/cdk/testing/tests/test-main-component.ts, src/material-experimental/mdc-input/testing/BUILD.bazel, src/material-experimental/mdc-input/testing/input-harness.spec.ts, src/material-experimental/mdc-input/testing/native-select-harness.spec.ts, src/material-experimental/mdc-input/testing/public-api.ts, src/material/input/testing/BUILD.bazel, src/material/input/testing/input-harness.spec.ts, src/material/input/testing/native-option-harness.ts, src/material/input/testing/native-select-harness-filters.ts, src/material/input/testing/native-select-harness.spec.ts, src/material/input/testing/native-select-harness.ts, src/material/input/testing/public-api.ts, src/material/input/testing/shared-input.spec.ts, src/material/input/testing/shared-native-select.spec.ts, tools/public_api_guard/cdk/testing.d.ts, tools/public_api_guard/cdk/testing/protractor.d.ts, tools/public_api_guard/cdk/testing/testbed.d.ts, tools/public_api_guard/material/input/testing.d.ts
For more info, look at the individual commits. Here's an overview:
* Adds a `selectOptions` method to `TestElement` that allows us to select options within a native `select`. The method is limited to working with indexes, because of some issues with `@angular/forms` that prevent us from using values for the DOM lookup.
* Adds the `MatNativeSelectHarness` and `MatNativeOptionHarness` that are used to work with a `select`, marked with `matNativeControl` inside a `mat-form-field`.
Fixes #20005.
=> feat: native select testing APIs

test/benchmarks/material/menu/menu.html, test/benchmarks/material/menu/menu.perf-spec.ts, test/benchmarks/mdc/menu/BUILD.bazel, test/benchmarks/mdc/menu/app.module.ts, test/benchmarks/mdc/menu/menu.html, test/benchmarks/mdc/menu/menu.perf-spec.ts
* Also cleaned up a small ts error I was getting from the material menu's driver.
=> test(mdc-menu): add performance tests for mdc-menu

src/material-experimental/mdc-chips/testing/chip-harness.spec.ts, src/material-experimental/mdc-chips/testing/chip-harness.ts, src/material-experimental/mdc-chips/testing/chip-option-harness.spec.ts, src/material/chips/testing/chip-harness.ts, src/material/chips/testing/shared.spec.ts
Excludes the text of icons from the result of the `getText` method.
Fixes #20503.
=> fix(chips/testing): exclude icons from getText result

src/material/list/testing/action-list-harness.ts, src/material/list/testing/list-harness.ts, src/material/list/testing/list-item-harness-base.ts, src/material/list/testing/nav-list-harness.ts
Simplifies the harness CSS selectors for list items. They currently are built up based on element
types but could be just using the list-item class that is applied automatically by the component.
Also removes a few of the unnecessary `:not` selectors for the standard `MatList` harness.
=> fix(material/list/testing): avoid element selectors that could conflict with the MDC version

src/google-maps/google-map/google-map.ts, src/google-maps/map-polyline/map-polyline.ts, tools/public_api_guard/google-maps/google-maps.d.ts
Removes the APIs that have been marked as deprecated for v11 from the `google-maps` package.
* `platformId` parameter of the `GoogleMap` constructor is now required.
=> refactor(google-maps): remove deprecated APIs for v11

src/material/datepicker/date-range-input.scss
Firefox automatically adds a red `box-shadow` to invalid inputs. These changes remove it from the inner range inputs since their invalid state is shown through the `mat-form-field`.
Fixes #20483.
=> fix(datepicker): remove red shadow from invalid range inputs in Firefox

src/cdk/drag-drop/directives/drag.ts, src/material-experimental/mdc-autocomplete/autocomplete.ts, src/material-experimental/mdc-chips/chip.ts, src/material-experimental/mdc-form-field/form-field.ts, src/material/autocomplete/autocomplete.ts, src/material/chips/chip.ts, src/material/form-field/form-field.ts, src/material/menu/menu.ts, src/material/select/select.ts, src/material/tabs/tab.ts
Initially when we added light-weight tokens to our components,
the Angular framework was not properly typed to support
injection tokens in the view and content queries.
We fixed this upstream with https://github.com/angular/angular/pull/37506
and can now remove the workaround/cast since this change is available
due to our recent Angular update to a `next` version.
=> refactor: remove light-weight token content-child query cast

src/cdk/stepper/step-header.ts, src/dev-app/stepper/BUILD.bazel, src/dev-app/stepper/stepper-demo-module.ts, src/dev-app/stepper/stepper-demo.html, src/dev-app/stepper/stepper-demo.ts, src/material/stepper/_stepper-theme.scss, src/material/stepper/step-header.ts, src/material/stepper/stepper-horizontal.html, src/material/stepper/stepper-vertical.html, src/material/stepper/stepper.spec.ts, src/material/stepper/stepper.ts, tools/public_api_guard/cdk/stepper.d.ts, tools/public_api_guard/material/stepper.d.ts
Adds `color` inputs to `mat-step`, `mat-vertical-stepper` and `mat-horizontal-stepper` so that their color can be changed from the default `primary`.
Fixes #20416.
=> feat(stepper): add theming support

src/cdk/drag-drop/drag-drop-registry.ts
On touch devices we have to bind the `touchmove` event before dragging has started, because iOS Safari won't allow us to call `preventDefault` on it otherwise. We also bind another `touchmove` listener once dragging starts which is what is used for moving the elements around on the screen.
These changes remove the dynamically-added `touchmove` listener and use the persistent one for everything instead.
=> perf(drag-drop): bind fewer touchmove listeners

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/directives/drop-list.ts, src/cdk/drag-drop/drag-drop.md, src/cdk/drag-drop/drop-list-ref.ts, src/components-examples/cdk/drag-drop/cdk-drag-drop-sort-predicate/cdk-drag-drop-sort-predicate-example.css, src/components-examples/cdk/drag-drop/cdk-drag-drop-sort-predicate/cdk-drag-drop-sort-predicate-example.html, src/components-examples/cdk/drag-drop/cdk-drag-drop-sort-predicate/cdk-drag-drop-sort-predicate-example.ts, src/components-examples/cdk/drag-drop/index.ts, tools/public_api_guard/cdk/drag-drop.d.ts
Adds the `cdkDropListSortPredicate` input that allows consumers to pass in a predicate function that determines whether an item can be sorted into a particular index of the list.
Fixes #19436.
=> feat(drag-drop): add predicate function for whether an item can be sorted into an index

src/material-experimental/mdc-tabs/tab-group.spec.ts, src/material-experimental/mdc-tabs/tab-header.spec.ts, src/material/tabs/paginated-tab-header.ts, src/material/tabs/tab-group.spec.ts, src/material/tabs/tab-header.spec.ts
We were always defaulting the `focusIndex` to 0 on init, rather than taking the index of the selected tab. We actually had tests for this behavior, but they were all testing against 0 so we never caught the issue.
Fixes #20374.
=> fix(tabs): always defaulting focusIndex to 0 on initialization

src/material/datepicker/calendar-header.spec.ts, src/material/datepicker/calendar.ts, src/material/datepicker/datepicker-base.ts, src/material/datepicker/datepicker-content.html, tools/public_api_guard/material/datepicker.d.ts
Adds viewChanged output to calendar so you can react if the view changed between 'month' | 'year' | 'multi-year'.
Fixes #13759.
=> feat(datepicker): add viewChanged output to calendar (#13759)

src/material-experimental/mdc-radio/radio.spec.ts, src/material-experimental/mdc-radio/radio.ts, src/material/radio/radio.spec.ts, src/material/radio/radio.ts, tools/public_api_guard/material/radio.d.ts
This is something that we have everywhere where we deal with `tabindex`, but it was missing on the radio button. Adds some logic that will take the initial `tabindex` value from the attribute through DI.
=> fix(radio): take default tabindex value from attribute

src/material/bottom-sheet/bottom-sheet-ref.ts, src/material/bottom-sheet/bottom-sheet.ts, src/material/schematics/ng-update/data/constructor-checks.ts, tools/public_api_guard/material/bottom-sheet.d.ts
Removes the APIs that were marked as deprecated for v11.
* `_location` parameter has been removed from the `MatBottomSheet` constructor.
* `_location` parameter has been removed from the `MatBottomSheetRef` constructor.
=> refactor(bottom-sheet): remove deprecated APIs for v11

src/cdk/drag-drop/directives/drop-list.ts, src/cdk/drag-drop/drag-ref.ts, src/cdk/drag-drop/drop-list-ref.ts, src/cdk/schematics/ng-update/data/constructor-checks.ts, src/cdk/schematics/ng-update/data/method-call-checks.ts, tools/public_api_guard/cdk/drag-drop.d.ts
Changes the APIs that were marked as deprecated for v11.
* `_scrollDispatcher` parameter of the `CdkDropList` constructor is now required. Also the order of the parameters has changed to accommodate the parameter becoming required.
* `previousIndex` parameter of `DropListRef.drop` is now required. Also the parameter order has changed.
=> refactor(drag-drop): change deprecated APIs for v11

src/material/button-toggle/button-toggle.html
Along the same lines as #20376. Doesn't use divs inside the button toggle.
=> fix(button-toggle): don't use divs inside button template

src/dev-app/checkbox/checkbox-demo.ts, src/dev-app/mdc-checkbox/mdc-checkbox-demo.ts, src/material-experimental/mdc-checkbox/checkbox.spec.ts, src/material-experimental/mdc-checkbox/checkbox.ts, src/material-experimental/mdc-checkbox/public-api.ts, src/material/checkbox/checkbox-config.ts, src/material/checkbox/checkbox.spec.ts, src/material/checkbox/checkbox.ts, src/material/schematics/ng-update/data/constructor-checks.ts, tools/public_api_guard/material/checkbox.d.ts
Removes the checkbox APIs that were marked for removal in v11.
* `MAT_CHECKBOX_CLICK_ACTION` has been removed. Configure `clickAction` through `MAT_CHECKBOX_DEFAULT_OPTIONS` instead.
* `_clickAction` parameter of the `MatCheckbox` constructor has been removed.
=> refactor(checkbox): remove deprecated APIs for v11

src/material-experimental/config.bzl, src/material-experimental/mdc-select/testing/BUILD.bazel, src/material-experimental/mdc-select/testing/index.ts, src/material-experimental/mdc-select/testing/public-api.ts, src/material-experimental/mdc-select/testing/select-harness-filters.ts, src/material-experimental/mdc-select/testing/select-harness.spec.ts, src/material-experimental/mdc-select/testing/select-harness.ts, src/material/select/testing/BUILD.bazel, src/material/select/testing/select-harness.spec.ts, src/material/select/testing/shared.spec.ts
Adds a test harness for the MDC-based `mat-select`.
=> feat(material-experimental/mdc-select): add test harness

src/material-experimental/mdc-tabs/tab-body.ts, src/material-experimental/mdc-tabs/tab-header.ts, src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.ts, src/material/schematics/ng-update/data/constructor-checks.ts, src/material/schematics/ng-update/data/method-call-checks.ts, src/material/tabs/paginated-tab-header.ts, src/material/tabs/tab-body.ts, src/material/tabs/tab-group.ts, src/material/tabs/tab-header.ts, src/material/tabs/tab-nav-bar/tab-nav-bar.ts, src/material/tabs/tab.ts, tools/public_api_guard/material/tabs.d.ts
Removes the APIs that were marked for removal in v11. There are also a few cases of the `_animationMode` parameter that I decided to keep optional since there's no good reason for it to be required.
* The `_element` parameter has been removed from `MatTabNav.updateActiveLink`.
* `_platform` parameter of the `MatPaginatedTabHeader` constructor is now required.
* `_document` parameter of the `MatTabBodyPortal` constructor is now required.
* `platform` parameter of the `MatTabNav` constructor is now required.
* `_closestTabGroup` parameter of the `MatTab` constructor is now required.
=> refactor(tabs): remove deprecated APIs for v11

src/cdk/schematics/ng-update/data/constructor-checks.ts, src/cdk/tree/padding.ts, tools/public_api_guard/cdk/tree.d.ts
Removes the APIs that were marked as deprecated for v11 in the tree module.
* `_renderer` parameter of the `CdkTreeNodePadding` constructor has been removed.
=> refactor(cdk/tree): remove deprecated APIs for v11

package.json, yarn.lock
* Update to the latest version to allow us to use the new
default params set up for runBenchmark.
=> build(dev-infra): update dev-infra version

guides/using-component-harnesses.md
- Remove whitespace that causes an item in the options list of the harness with method to be
rendered as a code block from the [component harness guide](https://material.angular.io/guide/using-component-harnesses). Use an alignment consistent with other lists in the file.
- Fix a typo in the note about change detection.
Linted, built, and tested
- Verified that the docs build output does not include an extra code block
https://imgur.com/jsrfW6W
=> docs: fix the harness with method's options list format in using component harnesses

tools/tslint-rules/validateDecoratorsRule.ts
Remove usage of the term whitelist in commenting for validateDecoratorsRule
=> build: update tslint rules to remove usage of whitelist in comments

test/karma-browsers.json, test/karma.conf.js
Sometimes the legacy Karma tests might fail and one might want
to debug those. Currently the Gulp task can be run for that, but
it's not starting any browser so one needs to launch Chrome manually.
Tests usually fail then because the browser has different dimensions
but our test expectations rely on a specific dimension. i.e. 1024x768
=> build: setup default browser for running legacy tests locally

src/material/paginator/paginator-intl.ts
`MatPaginatorIntl.getRangeLabel` didn't have an explicit type which was causing dgeni to output the entire initializer.
For reference:
=> docs(material/paginator): add explicit type for better formatting in docs

src/cdk-experimental/menu/menu.md, src/components-examples/BUILD.bazel, src/components-examples/cdk-experimental/menu/BUILD.bazel, src/components-examples/cdk-experimental/menu/cdk-menu-context/cdk-menu-context-example.css, src/components-examples/cdk-experimental/menu/cdk-menu-context/cdk-menu-context-example.html, src/components-examples/cdk-experimental/menu/cdk-menu-context/cdk-menu-context-example.ts, src/components-examples/cdk-experimental/menu/cdk-menu-inline/cdk-menu-inline-example.css, src/components-examples/cdk-experimental/menu/cdk-menu-inline/cdk-menu-inline-example.html, src/components-examples/cdk-experimental/menu/cdk-menu-inline/cdk-menu-inline-example.ts, src/components-examples/cdk-experimental/menu/cdk-menu-menubar/cdk-menu-menubar-example.css, src/components-examples/cdk-experimental/menu/cdk-menu-menubar/cdk-menu-menubar-example.html, src/components-examples/cdk-experimental/menu/cdk-menu-menubar/cdk-menu-menubar-example.ts, src/components-examples/cdk-experimental/menu/cdk-menu-standalone-menu/cdk-menu-standalone-menu-example.css, src/components-examples/cdk-experimental/menu/cdk-menu-standalone-menu/cdk-menu-standalone-menu-example.html, src/components-examples/cdk-experimental/menu/cdk-menu-standalone-menu/cdk-menu-standalone-menu-example.ts, src/components-examples/cdk-experimental/menu/cdk-menu-standalone-stateful-menu/cdk-menu-standalone-stateful-menu-example.css, src/components-examples/cdk-experimental/menu/cdk-menu-standalone-stateful-menu/cdk-menu-standalone-stateful-menu-example.html, src/components-examples/cdk-experimental/menu/cdk-menu-standalone-stateful-menu/cdk-menu-standalone-stateful-menu-example.ts, src/components-examples/cdk-experimental/menu/index.ts, src/dev-app/cdk-experimental-menu/BUILD.bazel, src/dev-app/cdk-experimental-menu/cdk-menu-demo-module.ts, src/dev-app/cdk-experimental-menu/cdk-menu-demo.html
I'm not 100% sure if I connected the examples with menu.md correctly. PTAL.
=> docs(cdk-experimental/menu): add examples to menu documentation

src/material-experimental/mdc-snack-bar/snack-bar-container.html, src/material-experimental/mdc-snack-bar/snack-bar-container.ts, src/material-experimental/mdc-snack-bar/snack-bar.spec.ts, src/material-experimental/mdc-snack-bar/testing/BUILD.bazel, src/material-experimental/mdc-snack-bar/testing/snack-bar-harness.ts, src/material/snack-bar/snack-bar-container.html, src/material/snack-bar/snack-bar-container.ts, src/material/snack-bar/snack-bar.spec.ts, src/material/snack-bar/snack-bar.ts, src/material/snack-bar/testing/BUILD.bazel, src/material/snack-bar/testing/shared.spec.ts, src/material/snack-bar/testing/snack-bar-harness.ts, tools/public_api_guard/material/snack-bar.d.ts, tools/public_api_guard/material/snack-bar/testing.d.ts
Fixes a bug where NVDA won't announce polite snack bars and JAWS won't announce any.
This is because the live region (snack-bar-container) was added to the DOM, marked as a live
region, and content was added to it in the same operation. Some screen readers require the live
region to be added to the DOM, some time to pass, then content can be added. Now the snack bar
content is added to an aria-hidden div then, 150ms later, moved to a div with aria-live defined.
This won't cause any visual changes and keeps the snack bar content available immediatly after
opening. Also, no longer using the alert or status roles. Instead just using aria-live as testing
showed that NVDA will double announce with the alert role and JAWS won't announce any button text. …
=> fix(material/snack-bar): flaky screen reader announcements for NVDA/JAWS

src/cdk/testing/protractor/protractor-element.ts, src/cdk/testing/test-element.ts, src/cdk/testing/testbed/unit-test-element.ts, src/cdk/testing/tests/cross-environment.spec.ts, src/material-experimental/mdc-button/testing/button-harness.ts, src/material-experimental/mdc-tabs/testing/tab-harness.ts, src/material/button/testing/button-harness.ts, tools/public_api_guard/cdk/testing.d.ts, tools/public_api_guard/cdk/testing/protractor.d.ts, tools/public_api_guard/cdk/testing/testbed.d.ts, tools/public_api_guard/material/button/testing.d.ts
This PR changes the semantics of `TestElement.click()` when called with
no arguments. Rather than guarantee clicking the center of the element,
the location of the click will be up to the particular
`HarnessEnvironment`. This allows the `TestbedHarnessEnvironment` to
skip the expensive and often unnecessary calculation to determine the
center of the element.
To replace the old behavior of `TestElement.click()`, the PR adds a new
signature, `TestElement.click('center')` that can be used to click the
center of the element. Calling `TestElement.click(x, y)` to click a
point relative to the top left of the element remains unchanged.
I tested the performance gain of these changes by running a unit test to
click 1000 buttons. Prior to this change it took 3000.2ms, with this
change it took …
=> perf(cdk/testing): Improve performance of clicking in unit tests.

src/cdk/table/table.ts
The `_viewRepeater` parameter is currently optional due to our breaking change policy,
however if it isn't provided, the table is basically a no-op. These changes add the old
rendering logic while we have to support both cases.
Fixes #20601.
**Note:** marking as a P2, because it's a regression.
=> fix(cdk/table): add fallback code if view repeater isn't provided

src/material/sidenav/drawer.ts, tools/public_api_guard/material/sidenav.d.ts
Removes the deprecation labels from a constructor parameter since it's tricky to
sync into g3 and is easy to maintain on our end.
=> refactor(material/sidenav): undeprecate constructor signature

src/cdk/overlay/dispatchers/overlay-keyboard-dispatcher.ts, src/cdk/overlay/fullscreen-overlay-container.ts, src/cdk/overlay/overlay-container.ts, src/cdk/overlay/overlay-directives.ts, src/cdk/overlay/overlay-module.ts, src/cdk/overlay/overlay-ref.ts, src/cdk/overlay/overlay.ts, src/cdk/schematics/ng-update/data/constructor-checks.ts, tools/public_api_guard/cdk/overlay.d.ts
Removes most of the deprecated APIs for v11 under `cdk/overlay`. Note that these changes target primarily the breaking changes that should be easier to land. I've left out removing `ConnectedPositionStrategy` which has a separate PR (#17519), and `GlobalPositionStrategy.width` and `GlobalPositionStrategy.height`, because they'll be trickier to land.
* The `OVERLAY_PROVIDERS` constant has been removed. Import `OverlayModule` and use the providers directly instead.
* `_platform` parameter of the `OverlayContainer` constructor is now required.
* `_platform` parameter of the `FullscreenOverlayContainer` constructor is now required.
* `_location` and `_outsideClickDispatcher` parameters of the `OverlayRef` constructor are now required.
* `_location` and …
=> refactor(overlay): remove deprecated APIs for v11

src/cdk/testing/tests/cross-environment.spec.ts, src/cdk/testing/tests/harnesses/main-component-harness.ts, src/cdk/testing/tests/test-main-component.html, src/cdk/testing/tests/test-main-component.ts, test/browser-providers.js, test/karma-browsers.json
Moves the Edge tests to Browserstack to avoid the recent issues with Saucelabs.
=> build: run edge tests on browserstack

src/material-experimental/mdc-checkbox/checkbox.ts
Changes _attrBlacklist symbol to be _medFoundationIgnoredAttrs, which is
more descriptive of what the symbol represents.
=> refactor(material-experimental/mdc-checkbox): remove usage of term blacklist

CHANGELOG.md
add changelog from 10.2.1 to 10.2.3
=> release: update chagelog

src/youtube-player/youtube-player.spec.ts, src/youtube-player/youtube-player.ts
fixes a race condition where window.YT would exist but window.YT.Player would not.
Fixes #20598
=> fix(youtube-player): YT.Player is not a constructor

src/material-experimental/mdc-core/option/option.scss
We use `min-height` on a flex container for the MDC `mat-option` which hits an IE11
bug where centering doesn't work anymore. These changes add a workaround similar
to what we do in `mat-table`.
=> fix(material-experimental/mdc-core): option text not centered on IE11

.github/CODEOWNERS, .ng-dev/commit-message.ts, src/dev-app/BUILD.bazel, src/dev-app/dev-app/dev-app-layout.ts, src/dev-app/dev-app/routes.ts, src/dev-app/mdc-paginator/BUILD.bazel, src/dev-app/mdc-paginator/mdc-paginator-demo-module.ts, src/dev-app/mdc-paginator/mdc-paginator-demo.html, src/dev-app/mdc-paginator/mdc-paginator-demo.scss, src/dev-app/mdc-paginator/mdc-paginator-demo.ts, src/material-experimental/config.bzl, src/material-experimental/mdc-paginator/BUILD.bazel, src/material-experimental/mdc-paginator/README.md, src/material-experimental/mdc-paginator/_paginator-theme.scss, src/material-experimental/mdc-paginator/_paginator-variables.scss, src/material-experimental/mdc-paginator/index.ts, src/material-experimental/mdc-paginator/paginator-module.ts, src/material-experimental/mdc-paginator/paginator.html, src/material-experimental/mdc-paginator/paginator.scss, src/material-experimental/mdc-paginator/paginator.spec.ts, src/material-experimental/mdc-paginator/paginator.ts, src/material-experimental/mdc-paginator/public-api.ts, src/material-experimental/mdc-theming/BUILD.bazel, src/material-experimental/mdc-theming/_all-theme.scss, src/material/paginator/paginator.ts, src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.html, src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.ts, tools/public_api_guard/material/paginator.d.ts
Implements `mat-paginator` on top of MDC Web and the logic from the existing paginator. The structural styles are close to what we have in the current paginator, while the theming and typography are implemented on top of MDC's mixins. Furthermore, we're using the MDC versions of `mat-select` and `mat-button` inside the paginator.
There are the following gotchas in this implementation:
1. The `mat-form-field` inside the paginator is set to always use the densest layout possible. This is necessary, because the MDC form field is too tall by default.
2. We hide one internal element from the form field, because it throws off the vertical alignment and is only used for hints and error messages which the paginator doesn't have.
3. I had to duplicate the `MatPaginatorDefaultOptions` interface, …
=> feat(material-experimental/mdc-paginator): implement MDC-based paginator

src/material-experimental/config.bzl, src/material-experimental/mdc-paginator/testing/BUILD.bazel, src/material-experimental/mdc-paginator/testing/index.ts, src/material-experimental/mdc-paginator/testing/paginator-harness-filters.ts, src/material-experimental/mdc-paginator/testing/paginator-harness.spec.ts, src/material-experimental/mdc-paginator/testing/paginator-harness.ts, src/material-experimental/mdc-paginator/testing/public-api.ts
Sets up a test harness for the MDC-based paginator.
=> feat(material-experimental/mdc-paginator): add test harness

src/components-examples/cdk/tree/cdk-tree-flat/cdk-tree-flat-example.ts
Fixes a bug in the Angular CDK Tree examples where the children nodes
are still visible when the top level node is collapsed. This is because
the `shouldRender()` method of the [cdk-flat-tree-example.ts](https://github.com/angular/components/blob/master/src/components-examples/cdk/tree/cdk-tree-flat/cdk-tree-flat-example.ts) is checking
only the parent of current node.
Fixes #20665
=> fix(cdk/tree): collapse child nodes if top level collapses

src/cdk/schematics/ng-update/data/css-selectors.ts, src/cdk/schematics/ng-update/data/input-names.ts, src/cdk/schematics/ng-update/data/output-names.ts, src/cdk/schematics/ng-update/data/property-names.ts, src/cdk/schematics/ng-update/migrations/class-inheritance.ts, src/cdk/schematics/ng-update/migrations/css-selectors.ts, src/cdk/schematics/ng-update/migrations/input-names.ts, src/cdk/schematics/ng-update/migrations/output-names.ts, src/cdk/schematics/ng-update/migrations/property-names.ts, src/cdk/schematics/ng-update/update-schematic.md, src/material/schematics/ng-update/data/css-selectors.ts, src/material/schematics/ng-update/data/input-names.ts, src/material/schematics/ng-update/data/output-names.ts, src/material/schematics/ng-update/data/property-names.ts
Migrate usages of whitelist in each of the ng-update selector interfaces to
be fileTypeFilter instead.
=> refactor(cdk/schematics): change usages of whitelist in selector interfaces to fileTypeFilter

src/material-experimental/mdc-snack-bar/snack-bar-container.scss
We were hitting a flexbox bug that was causing the snack bar container to collapse on IE11, shifting it off-center when using the `center` alignment and pushing it completely off-screen in the `end` alignment.
=> fix(material-experimental/mdc-snack-bar): not aligned correctly on IE11

src/material-experimental/mdc-button/button-base.ts
Aligns the signature of the `focus` method between the MDC and non-MDC buttons to make updates easier.
=> fix(material-experimental/mdc-button): align public API with material/button

scripts/check-mdc-tests.ts, src/material-experimental/mdc-menu/menu.spec.ts, src/material-experimental/mdc-radio/radio.spec.ts, src/material-experimental/mdc-table/table.spec.ts, src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.spec.ts
Adds tests that were missing from the `mdc-menu`, `mdc-radio`, `mdc-table` and `mdc-tabs` modules.
=> test(material-experimental): add missing test coverage

src/material-experimental/mdc-snack-bar/snack-bar-container.scss
Fixes a regression from #20690 that caused the snack bar button to be pushed outside of the container.
=> fix(material-experimental/mdc-snack-bar): button pushed outside container

src/material/tree/testing/node-harness.ts, tools/public_api_guard/material/tree/testing.d.ts
https://github.com/angular/components/pull/20556 switched some component harnesses to extend `ContentContainerComponentHarness` to allow users to query for harnesses inside the components but MatTreeHarness is not merged yet.
=> refactor(material/tree): change MatNodeHarness to extend ContentContainerComponentHarness

src/cdk/coercion/public-api.ts, src/cdk/coercion/string-array.spec.ts, src/cdk/coercion/string-array.ts, src/material/autocomplete/autocomplete.ts, src/material/datepicker/datepicker-base.ts, src/material/datepicker/datepicker.spec.ts, tools/public_api_guard/cdk/coercion.d.ts, tools/public_api_guard/material/autocomplete.d.ts
redo of https://github.com/angular/components/pull/17523 because there are now too many merge conflicts to merge cleanly
=> feat(cdk/coercion): add coercion for string arrays

src/material/core/datetime/native-date-adapter.spec.ts, src/material/core/datetime/native-date-adapter.ts
We were formatting dates in the years 0 to 99 incorrectly, because we pass it through the `Date` constructor which infers them as 19xx. We already had logic to handle cases like this when creating dates, but the formatting logic didn't go through the same code path. These changes extend the logic to the formatting utilities.
This fix resolves part of #20418, but we'll also have to make some changes to the datepicker calendar so it doesn't generate out-of-bounds years.
=> fix(material/core): incorrectly formatting dates in the years 0 to 99

src/cdk/a11y/focus-monitor/focus-monitor.spec.ts, src/cdk/a11y/focus-monitor/focus-monitor.ts
* Fixes an error thrown when trying to stop monitoring a non-element node. Now `FocusMonitor.monitor` is a noop.
* Fixes an error on init if the `cdkMonitorFocus` directive is placed on a non-element node.
Related to #20632.
=> fix(cdk/a11y): error if FocusMonitor is used on non-element nodes

src/cdk/testing/component-harness.ts, src/material-experimental/mdc-menu/testing/menu-harness.ts, src/material-experimental/mdc-tabs/testing/tab-harness.ts, src/material/menu/testing/menu-harness.ts, src/material/stepper/testing/step-harness.ts, src/material/tabs/testing/tab-harness.ts, tools/public_api_guard/cdk/testing.d.ts, tools/public_api_guard/material/menu/testing.d.ts, tools/public_api_guard/material/stepper/testing.d.ts, tools/public_api_guard/material/tabs/testing.d.ts
We have some test harnesses that extend `ContentContainerComponentHarness`, but have to override all methods, because their content is in a different element.
These changes clean up such usages by having a protected method for retrieving the harness root element that can be overwritten when necessary.
=> refactor(cdk/testing): simplify harnesses extending ContentContainerComponentHarness with a different root element

src/cdk/table/table.spec.ts, src/cdk/table/table.ts, src/components-examples/material/table/table-wrapped/table-wrapped-example.css, src/components-examples/material/table/table-wrapped/table-wrapped-example.html, src/components-examples/material/table/table-wrapped/table-wrapped-example.ts, tools/public_api_guard/cdk/table.d.ts
We have APIs that allow for rows and cells to be registered programmatically for cases where they aren't descendants of the table, but we didn't have something similar for the "no data" row. These changes add a method and update the examples.
Fixes #20560.
=> feat(cdk/table): add API for registering no data row

src/cdk/a11y/live-announcer/live-announcer.spec.ts, src/cdk/a11y/live-announcer/live-announcer.ts
Currently if a cdkAriaLive does not have an `Input` specified defaults
to `off` value. Change default behavior to assign `polite` value to the
directive.
Fixes #11618
=> fix(cdk/a11y): cdkAriaLive default to 'polite'

.circleci/config.yml
Splits out the commit message check so it only runs against pull requests. If an invalid commit has made it into the main branch, we can't do much about it anymore so the failure generates unnecessary noise.
=> build: only run commit message checks on PRs

src/material-experimental/mdc-select/select.spec.ts, src/material/select/select.spec.ts, src/material/select/select.ts
If an option is selected by the user and the value is changed programmatically afterwards, we weren't removing the active state from the previous option. This seems to be a regression from #19970.
These changes resolve the issue and preserve the fix from #19970 by resetting the active styling manually.
=> fix(material/select): option active styling not removed when value is changed programmatically

src/cdk/drag-drop/directives/assertions.ts, src/cdk/drag-drop/directives/drag-handle.ts, src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/directives/drag.ts, src/cdk/drag-drop/directives/drop-list.ts, src/dev-app/drag-drop/drag-drop-demo.html, tools/public_api_guard/cdk/drag-drop.d.ts
Currently if a `cdkDropList` or `cdkDragHandle` is attached to a non-element node, a cryptic error is thrown. These changes add a proper error, similar to the one we have on `cdkDrag`.
Fixes #13540.
=> fix(cdk/drag-drop): throw if drop list or handle are set on a non-element node

src/material/core/datetime/native-date-adapter.spec.ts, src/material/core/datetime/native-date-adapter.ts
This should hopefully fix test flakiness introduced by https://github.com/angular/components/commit/dd49fa69ddaa8106d5d2b9cacc67f45120fdccbc. The previous fix seems to sometimes report an incorrect date based on the time zone the test runs in
=> fix(material/datepicker): fix handling of short years

src/material/slider/slider.spec.ts, src/material/slider/slider.ts
It looks like some screen readers announce the value of a slider by calculating the percentage themselves using the `aria-valuemin`, `aria-valuemax` and `aria-valuenow`. The problem is that they don't round down the decimals so for a slider between 0 and 1 with a step of 0.1, they end up reading out values like 0.20000068. These changes work around the issue by setting `aria-valuetext` to the same value that we shown in the thumb which we truncate ourselves.
Fixes #20719.
=> fix(material/slider): some screen readers announcing long decimal values

src/material-experimental/mdc-autocomplete/autocomplete.spec.ts, src/material/autocomplete/autocomplete-trigger.ts, src/material/autocomplete/autocomplete.spec.ts
Doesn't handle escape key presses if the user is pressing a modifier key. This brings the autocomplete in line with most other components that were changed by #16202.
=> fix(material/autocomplete): don't prevent escape key actions with modifiers

src/material/datepicker/date-range-input-parts.ts, tools/public_api_guard/material/datepicker.d.ts
Lifecycle hooks are not being called in some cases due to a weird
interaction between extending TS mixins, running in view engine, and
transpiling the code with tsickle.
=> fix(material/datepicker): lifecycle hooks not being called

src/material/tooltip/tooltip.ts
This ensures that the Closure Compiler doesn't optimise out the format-string stringification.
I've only changed the setter's argument type, and have left `TooltipComponent.message` to be declared as string, with the reasoning that most users will want a type error if they try to set a non-string type.
I'm trying to maintain the runtime API of this code in the face of type-based optimisations.
Fixes #20684
=> mat-tooltip: ensure message is converted to string

src/material-experimental/mdc-list/selection-list.spec.ts, src/material-experimental/mdc-list/selection-list.ts, src/material/list/selection-list.spec.ts, src/material/list/selection-list.ts, tools/public_api_guard/material/list.d.ts
Fixes that we weren't emitting the `selectionChange` event when the user toggles all options with the ctrl + a shortcut. Also replaces `MatSelectionListChange.option` with `options` which is an array of all options that were changed by the current event.
Fixes #15696.
=> fix(material/list): emit selectionChange event when selecting with ctrl + a

src/material-experimental/mdc-form-field/directives/hint.ts, src/material-experimental/mdc-form-field/form-field.scss, src/material-experimental/mdc-input/input.spec.ts, src/material/form-field/form-field.scss, src/material/form-field/hint.ts, src/material/input/input.spec.ts
Binding to the `align` property of `mat-hint` didn't work, because while we were adding a class, the class wasn't being used. Using a static value works by accident.
Fixes #20629.
=> fix(material/form-field): dynamic hint end alignment not working

src/material/tabs/tab-content.ts, src/material/tabs/tab-nav-bar/tab-nav-bar.ts, tools/public_api_guard/material/tabs.d.ts
Currently there are some missing docs for tabs like this:
<details>
</details>
I'm send this PR to fix **some** of them (some of them can't be fixed there because there's a problem with the docs generator).
Here's the summary:
~**_MatPaginatedTabHeader_/MatTabHeader/MatTabNav**: adds missing `@Input` for `selectedIndex` and `@Output` for `selectFocusedIndex` and `indexFocused`.~
**_MatTabContent_**: document `template`.
**__MatTabLinkBase/MatTabLink_**:
- adds coercion for `active` `@Input`;
- adjust docs.
=> fix(tabs): some bugs with docs and coercion

src/material-experimental/mdc-menu/menu.ts, src/material/menu/menu-module.ts, src/material/menu/menu-trigger.ts, src/material/menu/menu.ts, src/material/menu/public-api.ts, tools/public_api_guard/material/menu.d.ts
Now that we're using lightweight tokens everywhere, we don't have to jump through hoops to prevent the base menu styles from being imported into MDC.
=> refactor: clean up MDC menu inheritance

src/material-experimental/mdc-tabs/tab-group.spec.ts, src/material/tabs/tab-config.ts, src/material/tabs/tab-group.spec.ts, src/material/tabs/tab-group.ts, tools/public_api_guard/material/tabs.d.ts
Makes it possible for consumers to configure the `dynamicHeight` default value through the `MAT_TABS_CONFIG` injection token.
Fixes #19662.
=> feat(tabs): allow for dynamicHeight to be configured through MAT_TABS_CONFIG

src/dev-app/select/BUILD.bazel, src/dev-app/select/select-demo-module.ts, src/dev-app/select/select-demo.html, src/dev-app/select/select-demo.ts, src/material-experimental/mdc-select/select.html, src/material-experimental/mdc-select/select.spec.ts, src/material/select/select.html, src/material/select/select.spec.ts, src/material/select/select.ts
Fixes #20694
@zelliott noted that this issue was caused by `aria-modal` preventing
VoiceOver from accessing the select's listbox overlay. He suggested
using `aria-owns` to re-parent the overlay element to the select
trigger. I tried this and it works great.
=> fix(material/select): make VoiceOver read options for selects in dialogs

src/material/datepicker/datepicker-base.ts, src/material/datepicker/datepicker-content.html, src/material/datepicker/datepicker-content.scss, src/material/datepicker/datepicker-intl.ts, src/material/datepicker/datepicker.spec.ts, tools/public_api_guard/material/datepicker.d.ts
Adds an invisible close button for screen reader users that becomes visible when the user tabs into it.
**Note:** there was a PR did was doing this already (#14429), but the feedback on it was never addressed and there hasn't been any activity on it in nearly 2 years.
Fixes #14379.
=> fix(material/datepicker): add close button for screen readers

src/material/datepicker/datepicker-base.ts, src/material/datepicker/datepicker.spec.ts, src/material/datepicker/month-view.spec.ts, src/material/datepicker/month-view.ts
Aligns the datepicker's escape key handling with the rest of the components where they aren't being handled if the user is pressing a modifier key.
=> fix(material/datepicker): don't handle escape key presses with modifier

src/material/datepicker/datepicker.spec.ts
A PR that changes the DOM structure of the datepicker went in at the same time as a PR that was depending on the old one, causing a test failure.
=> test(material/datepicker): fix test failure

.stylelintrc.json, package.json, yarn.lock
Recently we changed the names of some Stylelint rules, but the linter wasn't updated which leads to several warnings for each file that goes through it.
For reference, Stylelint logs the following on the CI as well, but we didn't notice because it exits with a non-error code.
```
src/material/core/theming/tests/test-theming-api.scss
1:1  ×  Unknown rule function-url-scheme-disallowed-list         function-url-scheme-disallowed-list
1:1  ×  Unknown rule unit-allowed-list                           unit-allowed-list
1:1  ×  Unknown rule declaration-property-value-disallowed-list  declaration-property-value-disallowed-list
src/material/core/theming/tests/test-theming-bundle.scss
1:1  ×  Unknown rule function-url-scheme-disallowed-list         function-url-scheme-disallowed-list
1:1  × …
```
=> build: stylelint not working correctly

.dependabot/config.yml, .github/CODEOWNERS, .github/dependabot.yml
Migrates to the new dependabot config rolled out since dependabot was
moved into Github.
=> build: migrate to new dependabot config

src/cdk/testing/protractor/protractor-element.ts, src/cdk/testing/test-element.ts, src/cdk/testing/testbed/unit-test-element.ts, src/cdk/testing/tests/cross-environment.spec.ts, src/cdk/testing/tests/harnesses/main-component-harness.ts, src/cdk/testing/tests/test-main-component.html, src/cdk/testing/tests/test-main-component.ts, tools/public_api_guard/cdk/testing.d.ts, tools/public_api_guard/cdk/testing/protractor.d.ts, tools/public_api_guard/cdk/testing/testbed.d.ts
Allows for arbitrary events to be dispatched through a `TestElement`. This covers the following use cases:
1. Some events can't be simulated easily without a user interaction (e.g. `change` event on an `input`).
2. Allows for custom DOM event handlers to be triggered.
=> feat(cdk/testing): add the ability to dispatch arbitrary events

.github/dependabot.yml
Add the missing schedule and open-pull-request-limits fields to the
dependabot configuration.
=> build: add required fields to dependabot configuration

src/material/table/table.md
Add a section to material/table documentation about how to retrieve the index of a row when using the `multiTemplateDataRows` directive. This information is only accessible as a comment into the [row.ts file](https://github.com/angular/components/blob/34a7e382144bb63965589002d0ed6bb046ac6054/src/cdk/table/row.ts) of the cdk.
```
Context provided to the row cells when multiTemplateDataRows is true. This context is the same
as CdkCellOutletRowContext except that the single index value is replaced by dataIndex and
renderIndex.
```
Having notifications over time about a related issue i gave an answer 2 years ago.
Issue #12793
=> docs(material/table): add multiTemplateDataRows specification

src/youtube-player/README.md
Adds some extra logic to the asynchronous loading example that illustrates how to avoid adding the API multiple times.
=> docs(youtube-player): update loading example to avoid loading API multiple times

src/material-experimental/mdc-form-field/testing/BUILD.bazel, src/material-experimental/mdc-form-field/testing/form-field-harness.spec.ts, src/material-experimental/mdc-form-field/testing/form-field-harness.ts
The test harness for the MDC form field was referring to the non-MDC versions of `MatInput` and `MatSelect`. Furthermore, we were using the non-MDC input, select and autocomplete in tests.
=> fix(material-experimental/mdc-form-field): test harness referring to non-MDC harnesses

src/material/bottom-sheet/bottom-sheet.ts, src/material/dialog/dialog.ts, tools/public_api_guard/material/dialog.d.ts
* Reworks the `MatDialog.open` method to use overloads, rather than the single signature that has `componentOrTemplateRef: ComponentType<T> | TemplateRef<T>`. This makes the separation clearer and looks nicer in autocompletion.
* Adds docs for the `MatBottomSheet.open` method.
=> refactor(material/dialog): use type overload for open method

src/material/tree/testing/shared.spec.ts, src/material/tree/testing/tree-harness.ts, tools/public_api_guard/material/tree/testing.d.ts
Add a "pretty print" method for the tree harness.
The method is only available at the tree/root level because it is not possible to get children of flat nodes as they are siblings in the DOM.
=> feat(material/tree): add getTreeStructure for tree harness

src/cdk/testing/protractor/protractor-element.ts, src/cdk/testing/test-element.ts, src/cdk/testing/testbed/fake-events/dispatch-events.ts, src/cdk/testing/testbed/unit-test-element.ts, src/cdk/testing/tests/cross-environment.spec.ts, src/cdk/testing/tests/harnesses/main-component-harness.ts, src/cdk/testing/tests/test-main-component.html, src/cdk/testing/tests/test-main-component.ts, tools/public_api_guard/cdk/testing.d.ts, tools/public_api_guard/cdk/testing/protractor.d.ts, tools/public_api_guard/cdk/testing/testbed.d.ts
Adds the ability to right click somewhere within a `TestElement`.
Fixes #20385.
=> feat(cdk/testing): support right clicking on a TestElement

src/material-experimental/mdc-checkbox/checkbox.spec.ts, src/material-experimental/mdc-checkbox/checkbox.ts, src/material-experimental/mdc-list/list-base.ts, src/material-experimental/mdc-list/list-option.ts, src/material-experimental/mdc-list/list-styling.ts, src/material-experimental/mdc-list/list.spec.ts, src/material-experimental/mdc-list/list.ts, src/material-experimental/mdc-list/module.ts, src/material-experimental/mdc-list/public-api.ts, src/material-experimental/mdc-progress-spinner/progress-spinner.spec.ts, src/material-experimental/mdc-snack-bar/snack-bar.spec.ts, src/material/checkbox/checkbox.spec.ts, src/material/list/list.spec.ts
Implements tests that were missing from the `mdc-list` package, as well as the `mdc-checkbox`, `mdc-progress-spinner` and `mdc-snack-bar`. The idea is that once we have parity on the test coverage, we can start to enforce test consistency automatically on the CI.
=> test(material-experimental/mdc-list): add missing test coverage

src/material-experimental/mdc-slide-toggle/BUILD.bazel, src/material-experimental/mdc-slide-toggle/slide-toggle.html, src/material-experimental/mdc-slide-toggle/slide-toggle.spec.ts, src/material-experimental/mdc-slide-toggle/slide-toggle.ts, src/material/slide-toggle/slide-toggle.spec.ts
The focus behavior of the existing `mat-slide-toggle` was changed slightly after the MDC version was implemented. These changes align the behavior and add some missing tests.
=> fix(material-experimental/mdc-slide-toggle): align focus behavior with standard version

src/cdk/drag-drop/clone-node.ts
When we clone the dragged element to generate its preview, we transfer the values of inputs so that they look identical. The problem is that assigning the value of a `file` input will throw an error so we have to skip it.
**Note:** does not include a unit test, because we can't set the of a test element programmatically.
Fixes #20783.
=> fix(cdk/drag-drop): error when cloning file input with value

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/drag-ref.ts
Currently we have a restriction that prevents users from starting a new drag sequence if an item within the same container is being dragged, however they can start one from a connected container and pull the item into the active one and start dragging it there. This can cause an error if it happens while the item's drop animation is running.
These changes add an extra check so that dragging can't be started out of a connected container either.
Relates to #20623.
=> fix(cdk/drag-drop): error if dragging starts from active sibling container

src/material-experimental/mdc-menu/menu.spec.ts, src/material/menu/menu-item.ts, src/material/menu/menu.spec.ts, tools/public_api_guard/material/menu.d.ts
Currently `MatMenuItem.getLabel` only looks at direct descendant text nodes in order to figure out its text while excluding things like icons. This breaks down if there's some kind of wrapper in the menu item.
These changes fix the issue by using `textContent` and excluding icons specifically.
Fixes #20200.
=> fix(material/menu): getLabel not working if text is inside indirect descendant node

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/drag-ref.ts, src/cdk/drag-drop/drag-styling.ts
When we create a drag preview we clone the original element, move it to the bottom of the `body`, set it to `display: none` and clear all `id` attributes from the clone. As a result, SVG references inside the element break, because the source node is invisible.
These changes resolve the issue by moving the original element outside the layout and making it transparent, instead of using `display: none`.
Fixes #20720.
=> fix(cdk/drag-drop): references to SVG not working inside preview

src/components-examples/material/button/BUILD.bazel, src/components-examples/material/button/button-harness/button-harness-example.html, src/components-examples/material/button/button-harness/button-harness-example.spec.ts, src/components-examples/material/button/button-harness/button-harness-example.ts, src/components-examples/material/button/index.ts, tools/example-module/generate-example-module.ts
change `generate-example-modules.ts` to account for .spec files.
=> docs(material/button): add button harness example

src/material-experimental/mdc-slide-toggle/slide-toggle.spec.ts
The changes from #20772 appear to have introduce a flaky test. These changes try to resolve it.
=> test(material-experimental/mdc-slide-toggle): resolve test flakes

src/material-experimental/mdc-tabs/testing/public-api.ts, src/material-experimental/mdc-tabs/testing/tab-group-harness.spec.ts, src/material-experimental/mdc-tabs/testing/tab-harness-filters.ts, src/material-experimental/mdc-tabs/testing/tab-link-harness.ts, src/material-experimental/mdc-tabs/testing/tab-nav-bar-harness.spec.ts, src/material-experimental/mdc-tabs/testing/tab-nav-bar-harness.ts, src/material/tabs/testing/BUILD.bazel, src/material/tabs/testing/public-api.ts, src/material/tabs/testing/tab-group-harness.spec.ts, src/material/tabs/testing/tab-group-shared.spec.ts, src/material/tabs/testing/tab-harness-filters.ts, src/material/tabs/testing/tab-link-harness.ts, src/material/tabs/testing/tab-nav-bar-harness.spec.ts, src/material/tabs/testing/tab-nav-bar-harness.ts, src/material/tabs/testing/tab-nav-bar-shared.spec.ts, tools/public_api_guard/material/tabs/testing.d.ts
Adds test harnesses for the MDC and non-MDC `mat-tab-nav-bar` and `matTabLink`. It seems like they were missing, because they were overlooked during the initial implementation.
=> feat(material/tabs): add test harnesses for tab nav bar

src/material-experimental/mdc-button/button.scss, src/material/button/button.scss
We currently have some focus indication in high contrast mode, but it's very difficult to see. These changes replace the old one with a 3x thicker outline.
Fixes #20820.
cc @mikzat
For reference:
=> fix(material/button): add more prominent focus indication in high contrast mode

package.json, src/material-experimental/mdc-card/card.scss, yarn.lock
Updates to the latest MDC canary and removes the extra outline that we add in high contrast mode since MDC now adds a border themselves.
=> fix(material-experimental/mdc-card): double outline in high contrast mode

src/material/bottom-sheet/bottom-sheet.md, src/material/dialog/dialog.md, src/material/snack-bar/snack-bar.md
Use strong typing for the MAT_DIALOG_DATA, MAT_BOTTOM_SHEET_DATA and MAT_SNACK_BAR_DATA injection token examples. Closes #20759
=> docs: Add types in injection token examples

src/material/chips/testing/chip-harness-filters.ts, src/material/chips/testing/chip-harness.ts, src/material/chips/testing/chip-list-harness.ts
Deprecates the selection-related methods from the test harnesses. They'll be moved into a separate harness in order to make the migration to MDC easier.
=> refactor(material/chips): deprecate selection methods in test harnesses

src/components-examples/material/input/input-error-state-matcher/input-error-state-matcher-example.html, src/components-examples/material/input/input-errors/input-errors-example.html
Adds `type="email"` to examples in Overview and Examples page for inputs.
Fixes #20682
=> docs(material/input): add type="email" to input examples

src/material-experimental/mdc-chips/chip-input.spec.ts, src/material-experimental/mdc-chips/chip-option.spec.ts, src/material-experimental/mdc-chips/chip-remove.spec.ts, src/material-experimental/mdc-chips/chip-row.ts, src/material-experimental/mdc-chips/chip.spec.ts, src/material-experimental/mdc-chips/chip.ts, src/material/chips/chip-input.spec.ts, src/material/chips/chip-remove.spec.ts, src/material/chips/chip.spec.ts
* Adds support for the `MAT_RIPPLE_GLOBAL_OPTIONS` injection token in the MDC-based chips.
* Aligns the tests between the standard and MDC versions so that it's easier to lint them.
=> fix(material-experimental/mdc-chips): add missing functionality and align tests

src/material-experimental/mdc-form-field/_form-field-density.scss, src/material-experimental/mdc-helpers/_focus-indicators.scss, src/material-experimental/mdc-list/_interactive-list-theme.scss, src/material/button/_button-theme.scss, src/material/checkbox/_checkbox-theme.scss, src/material/chips/_chips-theme.scss, src/material/core/density/_index.scss, src/material/core/focus-indicators/_focus-indicators.scss, src/material/core/ripple/_ripple.scss, src/material/core/theming/_check-duplicate-styles.scss, src/material/core/theming/_palette.scss, src/material/core/theming/_theming.scss, src/material/core/theming/tests/test-theming-api.scss, src/material/core/theming/tests/theming-api.spec.ts, src/material/radio/_radio-theme.scss, src/material/slide-toggle/_slide-toggle-theme.scss
We had a bunch of places using the deprecated variants of functions like `map_get`, `map_has_key` and `map_merge`. These changes migrate to the non-deprecated variants.
These changes are also necessary in order for the `sass-migrator` script to migrate the function calls.
=> refactor(material/core): remove usages of deprecated Sass functions

src/cdk/scrolling/virtual-for-of.ts, src/cdk/scrolling/virtual-scroll-viewport.spec.ts
The previous usage of `Array.prototype.slice.call` does not handle `Set`
objects appropriately (since a `Set` does not have a `length` property).
Updated it to use `Array.from`.
Fixes #20210.
=> feat(cdk/scrolling): update CdkVirtualForOf to work with sets.

src/material/dialog/dialog-animations.ts
Fixes a typo in the description of dialog container animations file.
=> docs(material/dialog): fix typo in animation description

src/material/icon/icon.spec.ts, src/material/icon/icon.ts, tools/public_api_guard/material/icon.d.ts
Moves some logic around so the icon can respond to changes in its state through plain property assignments, rather than going through Angular change detection cycle. This makes the component easier to extend.
Fixes #20470.
=> fix(icon): not updating svg icon assigned through setter

src/cdk/testing/protractor/protractor-element.ts, src/cdk/testing/test-element.ts, src/cdk/testing/testbed/unit-test-element.ts, src/cdk/testing/tests/cross-environment.spec.ts, src/cdk/testing/tests/harnesses/main-component-harness.ts, src/cdk/testing/tests/test-main-component.html, src/cdk/testing/tests/test-main-component.ts, tools/public_api_guard/cdk/testing.d.ts, tools/public_api_guard/cdk/testing/protractor.d.ts, tools/public_api_guard/cdk/testing/testbed.d.ts
Allows for data to be attached to an event that is triggered through `TestElement.dispatchEvent`. This is required in order to simulate some events like `animationend`. It is limited to primitive data types, because the data has to be JSON-serializeable for Protractor.
=> feat(cdk/testing): allow for data to be attached to custom event

src/material/list/testing/list-item-harness-base.ts, src/material/list/testing/shared.spec.ts
Excludes icons and avatars from the `MatListItemHarnessBase.getText` result.
Fixes #20812.
=> fix(material/list): exclude icons from harness getText result

src/material/chips/testing/chip-harness-filters.ts, src/material/chips/testing/chip-harness.ts, src/material/chips/testing/chip-list-harness.spec.ts, src/material/chips/testing/chip-list-harness.ts, src/material/chips/testing/chip-listbox-harness.ts, src/material/chips/testing/chip-option-harness.ts, src/material/chips/testing/public-api.ts, src/material/chips/testing/shared.spec.ts, tools/public_api_guard/material/chips/testing.d.ts
Adds alternate test harnesses specifically for selectable chips and chips lists. Note that while these harnesses currently match the same elements as their non-selectable counterparts, they'll match different elements in the MDC chips module.
This is a step towards consolidating the MDC and non-MDC harnesses for #20826.
=> feat(material/chips): add test harnesses for selectable chips

src/google-maps/map-event-manager.spec.ts, src/google-maps/map-event-manager.ts
This came up during the review of #20873. Currently the class that manages events for the Google Maps objects assumes that once a target is assigned, it'll either be maintained or eventually removed which means that the fix from #20873 will cause any existing event listeners to be dropped.
These changes add some code which will preserve the listeners.
Furthermore, I've added a dedicated testing setup for the `MapEventManager` since there's a fair bit of logic encapsulated in it and we've only been testing it by proxy through the various Google Maps components.
=> fix(google-maps): maintain subscriptions across event targets

src/dev-app/select/select-demo.html
`<mat-option>` within the select was missing `[value]`
Fixes: https://github.com/angular/components/issues/20840
=> docs(material/select): fix select within dialog example not selecting option

src/material-experimental/mdc-snack-bar/testing/snack-bar-harness.ts, src/material/snack-bar/testing/snack-bar-harness.ts, tools/tslint-rules/requireBreakingChangeVersionRule.ts
Dgeni was logging a warning, because we had `@deprecated` and `@breaking-change` on the same line in a couple of places, but we didn't notice it since it's not a hard error.
These changes update our lint rule to assert that the tags can only be set at the start of a line.
=> build: assert correct placement in breaking change rule

.gitignore
Ahead of upgrading to husky v5, adding the shell file location
to .gitignore to prevent it from randomly showing up when devs
checkout older branches.
=> build: add husky ignored files to .gitignore

.ng-dev/commit-message.ts, src/material-experimental/mdc-paginator/_paginator-theme.scss, src/material/expansion/_expansion-theme.scss, src/material/stepper/_stepper-theme.scss, src/material/toolbar/_toolbar-theme.scss, src/material/tree/_tree-theme.scss
For some components that don't have a corresponding implementation
in MDC Web, we added density mixins. We prefixed this with an
underscore to prevent premature use. Now we remove the underscore
as we're starting rollout in Google.
=> refactor: remove underscores from non-mdc density mixins

src/material-experimental/mdc-checkbox/_checkbox-theme.scss
This is a re-submit of https://github.com/angular/components/pull/20926 with a fix for the focus state
=> fix(material-experimental/mdc-checkbox): fix broken dark theme

src/material/datepicker/testing/date-range-input-harness-shared.spec.ts, src/material/datepicker/testing/datepicker-input-harness-base.ts, src/material/datepicker/testing/datepicker-input-harness-shared.spec.ts
When the datepicker input harnesses were first introduced, they didn't dispatch the `dateChange` event, because we didn't have a way of triggering the `change` handler.
Now that we have the necessary API, these changes make it so the event is dispatched.
Fixes #20480.
=> fix(material/datepicker): input harness not dispatching dateChange event

src/material/stepper/step-header.ts, src/material/stepper/stepper.spec.ts, tools/public_api_guard/material/stepper.d.ts
=> feat(material/stepper): allow focus origin to be optional input in focus method

src/cdk/stepper/stepper.ts, src/material/stepper/stepper.spec.ts
Fixes an error if an out-of-bounds index is assigned before the steps are available and the user tries to navigate. Usually we have an assertion that prevents invalid indexes from being assigned, but it doesn't run before initialization, because we don't know how many steps there will be yet.
These changes add a check that will revert the index back to 0 if the index is invalid on initialization.
Fixes #20735.
=> fix(cdk/stepper): error if out-of-bounds index is assigned before initialization

src/google-maps/map-ground-overlay/map-ground-overlay.spec.ts, src/google-maps/map-ground-overlay/map-ground-overlay.ts, tools/public_api_guard/google-maps/google-maps.d.ts
Allows for the bounds of the Google Maps ground overlay to be changed after initialization. This case is different from other similar components, because Google Maps doesn't provide an API to change the bounds so we have to recreate the overlay any time they change.
Fixes #20865.
=> fix(google-maps): allow ground overlay bounds to be changed

src/material-experimental/mdc-chips/chip-set.spec.ts, src/material-experimental/mdc-chips/chip-set.ts
The default mat-chip-set role is 'presentation' if chips are
present, and null if there are no chips. Some users want to
specify custom roles, in particular 'list' (they would use
'listitem' for the chips, which have no default role).
Currently this isn't possible, because mat-chip-set overwrites
their custom role with 'presentation'. Add an Input to allow a
custom role.
=> feat(material-experimental/mdc-chips): Allow custom role for chip set

src/cdk/layout/breakpoints.ts
The previous breakpoint upper bounds use `.99` for the
fractional components of upper bounds. However, this seems
to cause browser to round up to the next pixel, creating an overlap
for these values. Changing to `.98` fixes this.
Fixes angular/components#20850
=> fix(cdk/layout): decrease breakpoint upper bounds

src/material/expansion/expansion-panel-header.ts, src/material/expansion/expansion.spec.ts
=> feat(material/expansion): allow focus origin to be optional input in focus method

src/material/dialog/dialog.scss
It's common for apps to set `* { box-sizing: border-box; }` at a global level which ends up breaking the styles of our dialog. These changes set an explicit `box-sizing` to ensure that it still looks consistently. This is in line with what we've done in other similar cases.
Fixes #20887.
=> fix(material/dialog): incorrect action height if box-sizing is configured globally

src/material/button/button.spec.ts, src/material/button/button.ts
=> feat(material/button): allow focus origin to be optional input in focus method

src/material/checkbox/checkbox.spec.ts, src/material/checkbox/checkbox.ts
=> feat(material/checkbox): allow focus origin to be optional input in focus method

src/material/datepicker/date-range-input.ts, src/material/datepicker/date-range-picker.ts, src/material/datepicker/datepicker-base.ts, src/material/datepicker/datepicker-input.ts, src/material/datepicker/datepicker-toggle.ts, tools/public_api_guard/material/datepicker.d.ts
Refactor material datepicker so apps can bind custom picker components to date inputs.
- Renamed the following in `MatDatepickerBase`:
- `_registerInput()` -> `registerInput()`
- `_stateChanges` -> `stateChanges`
- `_datepickerInput` -> `datepickerInput`
- Added `MatDatepickerPanel` interface (recommendations for another name?).
- Refactored `MatDatepickerInput`, `MatDateRangeInput`, and `MatDatepickerToggle` to receive a `MatDatepickerPanel` instead of a specific implementation of `MatDatepickerBase`.
=> feat(material/datepicker) allow custom pickers with date inputs

src/material/menu/menu-item.ts, src/material/menu/menu-trigger.ts, src/material/menu/menu.spec.ts
=> feat(material/menu): allow focus origin to be optional input in focus method

src/material/datepicker/date-range-input-parts.ts, tools/public_api_guard/material/datepicker.d.ts
The `dateChange` and `dateInput` outputs are inherited through a mixin which seems to prevent the language service from picking them up. These changes add extra hints to the component metadata.
Fixes #20932.
=> fix(material/datepicker): range input emitters not picked up by language service

src/material-experimental/mdc-chips/testing/chip-harness-filters.ts, src/material-experimental/mdc-chips/testing/chip-harness.spec.ts, src/material-experimental/mdc-chips/testing/chip-harness.ts
This allows MDC chips to be removed in testing environments.
Note that the harness must not only click on the remove button, but also dispatch a `transitionend` event. Without the dispatch of this event, the chip would not fire it's `removed` output.
This PR also includes a basic MDC ChipRemoveHarness that mirrors the non-MDC version. This was necessary to find the ChipRemove button in the chip harness' `remove` method.
=> feat(material-experimental/mdc-chips): add `remove` method to MDC chip harness

src/material-experimental/README.md, src/material-experimental/mdc-autocomplete/README.md, src/material-experimental/mdc-checkbox/README.md, src/material-experimental/mdc-menu/README.md, src/material-experimental/mdc-paginator/README.md, src/material-experimental/mdc-progress-bar/README.md, src/material-experimental/mdc-progress-spinner/README.md, src/material-experimental/mdc-select/README.md, src/material-experimental/mdc-slide-toggle/README.md, src/material-experimental/mdc-tabs/README.md
Adds the correct import paths for mdc-components guide on scss/css @mixins
Adds the `angular-material-mdc-theme` to a readme versus individual guides on css mixins.
=> docs(material-experimental): css paths in readme

src/material-experimental/mdc-core/option/optgroup.ts, src/material-experimental/mdc-core/option/option.html, src/material-experimental/mdc-core/option/option.spec.ts, src/material-experimental/mdc-core/testing/option-harness.ts, src/material/autocomplete/autocomplete.ts, src/material/core/option/index.ts, src/material/core/option/optgroup.ts, src/material/core/option/option-parent.ts, src/material/core/option/option.html, src/material/core/option/option.spec.ts, src/material/core/option/option.ts, src/material/core/testing/option-harness.ts, tools/public_api_guard/material/autocomplete.d.ts, tools/public_api_guard/material/core.d.ts
We're currently hitting a bug with `mat-autocomplete` that prevents options inside of `mat-optgroup` from being read out by VoiceOver on Safari. These changes implement an alternate accessibility pattern that only applies to options inside an autocomplete since the work correctly in `mat-select`.
=> fix(material/autocomplete): options inside groups not read out with VoiceOver

src/material/progress-spinner/progress-spinner.scss
When the progress spinner is rotating its layout can outside that of the parent which can have an effect on scroll bars. These changes put the rotating animation on the `svg` node and make the component host `overflow: hidden`.
Fixes #16894.
=> fix(progress-spinner): rotating circle changing surrounding layout

src/material/tooltip/tooltip.spec.ts, src/material/tooltip/tooltip.ts, tools/public_api_guard/material/tooltip.d.ts
We depend on the `mouseleave` event to close the tooltip, but it won't fire if the user scrolls away without moving their mouse. These changes add some logic so the tooltip is closed if a `wheel` event resulted in the cursor leaving the trigger.
Fixes #18611.
=> fix(material/tooltip): not closing when scrolling away using mouse wheel

src/material/progress-bar/progress-bar.spec.ts, src/material/progress-bar/progress-bar.ts
Switches to using a 3d transform for the progress bar in order to avoid a rendering issue in `buffer` mode on iOS Safari.
Fixes #19328.
=> fix(progress-bar): buffer not rendering correctly on ios

src/material/slide-toggle/slide-toggle.spec.ts, src/material/slide-toggle/slide-toggle.ts, tools/public_api_guard/material/slide-toggle.d.ts
=> feat(material/slide-toggle): allow focus origin to be optional input in focus method

src/material/radio/radio.spec.ts, src/material/radio/radio.ts, tools/public_api_guard/material/radio.d.ts
=> feat(material/radio): allow focus origin to be optional input in focus method

src/material-experimental/mdc-checkbox/checkbox.scss, src/material/checkbox/checkbox.scss
Currently the host nodes are `display: inline` by default which doesn't allow for things like `margin` and `width` to be set. These changes switch to `inline-block` which is a bit more flexible.
Fixes #20954.
=> fix(material/checkbox): set display on host node

src/material-experimental/mdc-button/fab.scss
Fixes a selector that was targeting all icons on the page, rather than ones inside a button.
=> fix(material-experimental/mdc-button): narrow down overly-broad selector

src/material/button-toggle/button-toggle.spec.ts, src/material/button-toggle/button-toggle.ts
Follow-up from #16938. Clears the aria-* attributes from the host node so that they're not duplicated with the underlying input.
=> fix(button-toggle): clear static aria attributes from host nodes

src/material-experimental/mdc-table/table.spec.ts, src/material/table/table-data-source.ts, src/material/table/table.spec.ts
We had a simple falsy check to determine whether to call the filter predicate. I'm guessing it was written this way so that if somebody were to clear a filter input, all items will be shown. This seems a bit too loose since it could catch things like 0 which technically aren't allowed due to the `string` type, but could still end up inside the data source if values are proxied in directly through the view.
Ideally we'd just call the predicate for all values and let it decide whether or not to filter, but I left in special cases for undefined, null and empty strings, because I expect a lot of apps to be broken if we were to change the behavior.
Fixes #19092.
Fixes #9967.
=> fix(table): filter predicate not called for falsy values

src/material-experimental/mdc-slide-toggle/slide-toggle.scss
Hides the native focus outline from the slide toggle since we use the ripple for focus indication.
This is what it currently looks like for reference. This only happens for a split second when clicking on the label.
=> fix(material-experimental/mdc-slide-toggle): hide native focus outline

src/cdk/a11y/BUILD.bazel, src/cdk/a11y/focus-monitor/focus-monitor.spec.ts, src/cdk/a11y/focus-monitor/focus-monitor.ts, src/material-experimental/mdc-menu/menu.spec.ts, src/material/menu/menu.spec.ts
The way `FocusMonitor.focusVia` works is by calling `focus` on the specified element and waiting for a `focus` event to trigger so the origin is applied. The problem is that if `focusVia` is called on an element that already has focus, the event won't be dispatched and the origin won't be updated which can cause the UI to look stuck.
These changes make it so that if we detect that an element is focused already, we update its classes and dispatch the relevant event without trying to focus it.
Related to #20965.
=> fix(cdk/a11y): allow for origin of already focused element to be changed

src/material-experimental/mdc-menu/menu.spec.ts, src/material/menu/menu.spec.ts
Fixes some test failures that were in master. Also adds some missing tests to the MDC menu.
=> test(material/menu): resolve test failures

package.json, yarn.lock
This PR reverts changes that were accidentally brought in from master branch and include an update to scss-bundle that causes a massive size regression in our sass bundle. It also updates @angular-devkit/build-optimizer to rc3 since that was missed when updating to rc3
=> fix package.json and yarn.lock issues

yarn.lock
This reverts commit b2e2e864192ed5167733df23fb8a5c4406b86cf3.
This PR reverts the update to scss-bundle that causes a massive size regression in our sass bundle.
=> Revert "build: bump scss-bundle from 3.0.2 to 3.1.2 (#20799)"

CHANGELOG.md, package.json, yarn.lock
Also updates @angular-devkit/build-optimizer to rc3 since that was missed when updating to rc3
=> release: bump version to 11.0.0-rc.4 w/ changelog

package.json, src/material/BUILD.bazel, yarn.lock
Updates to the latest version of `scss-bundle` and resolves an issue that was causing the theming bundle to be more than 15mb.
=> build: update to latest scss bundler and resolve file size issue

package.json
The version on the master branch was accidentally lowered from
`11.0.0-next.0` to `11.0.0-rc.2` in 0cd3671a
=> build: correct version for master branch

packages.bzl
Switches the published npm packages to MDC 9.0 canary.
=> build: use MDC 9.0 canary when publishing to npm

.circleci/config.yml, scripts/check-mdc-tests-config.ts, scripts/check-mdc-tests.ts, src/material-experimental/mdc-chips/chip-input.spec.ts, src/material-experimental/mdc-list/selection-list.spec.ts, src/material-experimental/mdc-menu/menu.spec.ts, src/material-experimental/mdc-radio/radio.spec.ts, src/material-experimental/mdc-select/select.spec.ts, src/material-experimental/mdc-slider/slider.spec.ts
Adds a CI check that will fail if a test from a Material package is missing from its MDC equivalent. There's also a config file that allows for tests to be excluded. I've populated the file and added context about why tests have been disabled.
=> build: add CI check to keep MDC tests in line

.circleci/config.yml, package.json, scripts/check-mdc-exports-config.ts, scripts/check-mdc-exports.ts, src/material-experimental/mdc-checkbox/public-api.ts, src/material-experimental/mdc-dialog/public-api.ts, src/material-experimental/mdc-form-field/public-api.ts, src/material-experimental/mdc-input/public-api.ts, src/material-experimental/mdc-list/BUILD.bazel, src/material-experimental/mdc-list/public-api.ts, src/material-experimental/mdc-menu/public-api.ts, src/material-experimental/mdc-progress-spinner/public-api.ts, src/material-experimental/mdc-radio/public-api.ts, src/material-experimental/mdc-slide-toggle/public-api.ts, src/material-experimental/mdc-snack-bar/public-api.ts, src/material-experimental/mdc-tabs/public-api.ts
Adds a new script that checks whether an MDC package exports the same set of symbols as its non-MDC counterpart. Also fixes all of the failures.
=> build: add CI check to ensure consistent exports for MDC packages

src/material/radio/radio.html, src/material/radio/radio.scss
What:
Change `<div>` to `<span>`
Why:
`<div>` elements should not be nested inside `<label>` elements because `<label>` only allows phrasing content
=> feat(material/radio): Avoid nested divs in labels by changing to span instead.

WORKSPACE, package.json, tools/postinstall/sass_worker_async.patch, yarn.lock
Bumps to the latest version of Sass and fixes up our custom patch so that it accounts for some changes in the published files.
=> build: update to latest sass version

src/dev-app/button/button-demo.html, src/dev-app/mdc-button/mdc-button-demo.html, src/material-experimental/mdc-button/button.html, src/material-experimental/mdc-button/button.scss
Here's how it looks with the fix:
=> fix(material-experimental/mdc-button): fix positioning of icons in text buttons

src/components-examples/material/dialog/BUILD.bazel, src/components-examples/material/dialog/dialog-from-menu/dialog-from-menu-example-dialog.html, src/components-examples/material/dialog/dialog-from-menu/dialog-from-menu-example.html, src/components-examples/material/dialog/dialog-from-menu/dialog-from-menu-example.ts, src/components-examples/material/dialog/index.ts, src/material/dialog/dialog.md
Addresses https://github.com/angular/components/issues/17962 by adding a viable workaround in the docs since currently there is no good way to fix it without it being very complicated.
=> docs(material/dialog): add a11y section about manual focus restoration

integration/ts-compat/BUILD.bazel, package.json, scripts/caretaking/firebase-functions/package.json, scripts/caretaking/firebase-functions/yarn.lock, yarn.lock
Removes the TypeScript 3.9 checks since the framework is in the process of removing support (see https://github.com/angular/angular/pull/39313).
Also updates the Firebase functions to TS 4.0.
**Note:** this is merge-safe since it only changes build-related code.
=> build: drop typescript 3.9 checks

src/material/checkbox/checkbox.html, src/material/checkbox/checkbox.scss
What:
Change `<div>` to `<span>`
Why:
`<div>` elements should not be nested inside `<label>` elements because `<label>` only allows phrasing content
=> feat(material/checkbox): Avoid nested divs in labels by changing to span instead.

src/cdk/a11y/aria-describer/aria-describer.spec.ts, src/cdk/a11y/aria-describer/aria-describer.ts, src/material/tooltip/tooltip.ts, tools/public_api_guard/cdk/a11y.d.ts
Includes two separate commits that:
1. Add support for setting a `role` through the `AriaDescriber`.
2. Uses the new option to set a `tooltip` role on the tooltip's description elements.
Fixes #20593.
=> fix: set role on tooltip description element

src/material-experimental/mdc-progress-spinner/progress-spinner.scss
Similar to #16930. Prevents the indeterminate animation from overflowing the host node and affecting the page layout.
The issue can be seen on Windows where the scroll bar is always visible.
=> fix(material-experimental/mdc-progress-spinner): prevent animation from affecting surrounding layout

src/material-experimental/mdc-checkbox/checkbox.spec.ts, src/material-experimental/mdc-checkbox/checkbox.ts, src/material/checkbox/checkbox.spec.ts, src/material/checkbox/checkbox.ts
Fixes an issue where a `mat-checkbox` wouldn't have a `color`, if the `MAT_CHECKBOX_DEFAULT_OPTIONS` was provided without one.
Fixes #21031.
=> fix(material/checkbox): no color assigned if defaults don't have a color

src/google-maps/map-info-window/map-info-window.spec.ts, src/google-maps/map-info-window/map-info-window.ts
Some time ago we added logic to prevent the info window from reopening if the same anchor is passed in. This ended up breaking the use case where a window is opened without an anchor, because the window always starts off without one.
Fixes #21013.
=> fix(google-maps): info window not opening if no anchor is passed in

src/material-experimental/mdc-select/select.scss, src/material/select/select.scss
The panel has a focus outline since it has `tabindex="-1"`. We generally don't keep focus on it so the outline isn't shown, but it can happen if the user clicks on the scroll bar. These changes remove the outline.
=> fix(material/select): remove focus outline on panel

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/drag-ref.ts
Currently we disable native drag interactions on handles once when they're registered, however this can block scrolling on mobile devices if the handle is inactive (either it is disabled or the drag element is disabled).
These changes toggle the state dynamically depending on the active state.
Fixes #20974.
=> fix(cdk/drag-drop): don't disable native dragging on inactive handles

src/material/chips/chip.ts
Fixes that the chip fires ripples even if all animations are disabled.
Fixes #20981.
=> fix(material/chips): ripple not disabled when animations are disabled

src/dev-app/theme.scss, src/material/button-toggle/_button-toggle-theme.scss, src/material/core/BUILD.bazel, src/material/core/_core.scss, src/material/core/density/private/_all-density.scss, src/material/core/density/private/_compatibility.scss, src/material/core/focus-indicators/_focus-indicators.scss, src/material/core/theming/tests/test-theming-api.scss, src/material/core/theming/tests/theming-api.spec.ts, src/material/expansion/_expansion-theme.scss, src/material/form-field/_form-field-fill-theme.scss, src/material/form-field/_form-field-legacy-theme.scss, src/material/form-field/_form-field-outline-theme.scss, src/material/form-field/_form-field-standard-theme.scss, src/material/form-field/_form-field-theme.scss, src/material/paginator/_paginator-theme.scss, src/material/stepper/_stepper-theme.scss, src/material/theming-bundle.scss, src/material/toolbar/_toolbar-theme.scss, src/material/tree/_tree-theme.scss
Resolves the following issues with our Sass that are errors under the Sass module system:
* There were a handful of mixins with underscores in their name which were imported into other files.
* There was a circular dependency between `density/private` and `theming/all-theme`.
=> refactor(material/core): resolve circular dependency and remove underscores from more imported mixins

src/material/datepicker/month-view.ts, tools/public_api_guard/material/datepicker.d.ts
Expose the datepicker month view's `ChangeDetectorRef` as part of its public (internal) API so it can be accessed by other components.
=> refactor(material/datepicker): expose month view change detector ref

src/material/core/datetime/date-formats.ts, src/material/datepicker/month-view.spec.ts, src/material/datepicker/month-view.ts, tools/public_api_guard/material/core.d.ts
- Added `monthLabel` date format
- Updated datepicker month view to use `monthLabel` format if specified
- Added test for `monthLabel`. I grouped the existing tests in a separate `describe` block so I could specify custom providers for the new  test. It's hard to tell from the diff, but aside from shuffling tests around, no existing tests were changed.
=> feat(material/core): add date format for month label

src/cdk/drag-drop/drag-ref.ts
The `DragRef` keeps track of which of its handles have been disabled, but if one of them is destroyed, we still keep its reference until the object is destroyed.
These changes add some extra logic to filter them out.
Fixes #21009.
=> fix(cdk/drag-drop): avoid retaining disabled handles after they've been destroyed

src/google-maps/map-marker/map-marker.ts, tools/public_api_guard/google-maps/google-maps.d.ts
Currently the various Google Maps sub-components are set up so that each input has a setter, a `BehaviorSubject` and a method to watch it for changes. This doesn't scale very well on components with lots of inputs so these changes use an alternate one where we synchronously update the marker state whenever an input changes.
**Note:** This PR is meant to be a proof-of-concept so that we can discuss the approach. If we agree that it's the way forward, it can be applied to the other map components.
=> refactor(google-maps): simplify marker internal setup

src/material-experimental/mdc-chips/testing/BUILD.bazel, src/material-experimental/mdc-chips/testing/chip-grid-harness.spec.ts, src/material-experimental/mdc-chips/testing/chip-grid-harness.ts, src/material-experimental/mdc-chips/testing/chip-harness-filters.ts, src/material-experimental/mdc-chips/testing/chip-harness.spec.ts, src/material-experimental/mdc-chips/testing/chip-harness.ts, src/material-experimental/mdc-chips/testing/chip-input-harness.spec.ts, src/material-experimental/mdc-chips/testing/chip-input-harness.ts, src/material-experimental/mdc-chips/testing/chip-listbox-harness.spec.ts, src/material-experimental/mdc-chips/testing/chip-listbox-harness.ts, src/material-experimental/mdc-chips/testing/chip-option-harness.spec.ts, src/material-experimental/mdc-chips/testing/chip-option-harness.ts, src/material-experimental/mdc-chips/testing/chip-remove-harness.ts, src/material-experimental/mdc-chips/testing/chip-row-harness.spec.ts, src/material-experimental/mdc-chips/testing/chip-set-harness.spec.ts, src/material-experimental/mdc-chips/testing/chip-set-harness.ts, src/material-experimental/mdc-chips/testing/public-api.ts
Aligns the test harnesses of the MDC-based chips module with the ones from the non-MDC version. Overview of the changes:
* `MatChipGridHarness` - `getTextInput` was renamed to `getInput` to match the non-MDC list harness. Also adds a few utility methods to check whether the grid is disabled, required etc.
* `MatChipHarness` - adds support for the same set of filters when querying for the harness. Also adds a method to get the removal button and disabled state.
* `MatChipInputHarness` - adds a bunch of utility methods that we have on the other input-related harnesses. Also implemets the same set of harness filters as the non-MDC harness.
* `MatChipListboxHarness` - Renames `getOptions` to `getChips` for consistency and removes the `getSelected` method in favor of filtering selected chips …
=> fix(material-experimental/mdc-chips): align test harnesses with the non-MDC version

src/google-maps/map-marker/map-marker.ts
* This was causing internal errors because these properties
are not declared on SimpleChanges. According to the error:
'The type has a string index signature, but it is being
accessed using a dotted property access'.
=> fix(google-maps): avoid using dotted property access

guides/theming-your-components.md
The current example on "How to theme your own components" includes an invalid SCSS example. This PR fixed that.
=> docs: use valid SCSS variables for example

src/material/datepicker/datepicker-content.scss
The specificity of the screen reader close button was the same as `.mat-raised-button` which means that if the button styles are loaded after the datepicker styles, they'll be overridden and will make the button look weird. These changes bump up the specificity a bit to work around the issue.
Fixes #21043.
=> fix(material/datepicker): screen reader close button style specificity too low

src/material/datepicker/datepicker-toggle.html, src/material/datepicker/datepicker-toggle.ts, src/material/datepicker/datepicker.spec.ts, tools/public_api_guard/material/datepicker.d.ts
Currently the only way to control the accessible label of a `mat-datepicker-toggle` is globally through the i18n provider. These changes add an input so it can be changed per instance.
Fixes #20590.
=> feat(material/datepicker): allow for datepicker toggle aria-label to be customized

src/material-experimental/mdc-button/_button-base.scss, src/material-experimental/mdc-button/button.scss, src/material-experimental/mdc-button/fab.scss, src/material-experimental/mdc-button/icon-button.scss, src/material-experimental/mdc-checkbox/_checkbox-theme.scss, src/material-experimental/mdc-dialog/_mdc-dialog-structure-overrides.scss, src/material-experimental/mdc-dialog/dialog.scss, src/material-experimental/mdc-form-field/_form-field-density.scss, src/material-experimental/mdc-form-field/_form-field-focus-overlay.scss, src/material-experimental/mdc-form-field/_form-field-native-select.scss, src/material-experimental/mdc-form-field/_form-field-subscript.scss, src/material-experimental/mdc-form-field/_form-field-theme.scss, src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss, src/material-experimental/mdc-form-field/_mdc-text-field-textarea-overrides.scss, src/material-experimental/mdc-form-field/_mdc-text-field-theme-variable-refresh.scss, src/material-experimental/mdc-form-field/form-field.scss, src/material-experimental/mdc-list/_interactive-list-theme.scss, src/material-experimental/mdc-list/_list-option-theme.scss, src/material-experimental/mdc-list/_list-theme.scss, src/material-experimental/mdc-paginator/_paginator-theme.scss, src/material/button-toggle/_button-toggle-theme.scss, tools/stylelint/no-top-level-ampersand-in-mixin.ts, tools/stylelint/theme-mixin-api.ts
* Removes the underscores from the names of mixins that are used in other files. This will become an error when we switch to the Sass module system.
* Renames some mixins that were starting with `mdc-` since they can be confused with mixins actually coming from MDC.
=> refactor(material-experimental/mdc-core): remove underscores from imported mixins

src/material/datepicker/date-range-input.spec.ts, src/material/datepicker/date-range-input.ts, src/material/datepicker/datepicker-input-base.ts, src/material/datepicker/datepicker-input.ts, src/material/datepicker/datepicker.spec.ts
Doesn't invoke the `ControlValueAccessor` change function when a new date filter is assigned, if the result wouldn't have change the validation state.
Fixes #20967.
=> fix(material/datepicker): don't invoke change handler when filter is swapped out if result is the same

src/material-experimental/mdc-paginator/paginator.scss
Fixes that the MDC paginator buttons weren't visible in high contrast mode.
=> fix(material-experimental/mdc-paginator): buttons not visible in high contrast mode

src/material/sidenav/testing/drawer-container-harness.ts, src/material/sidenav/testing/drawer-content-harness.ts, src/material/sidenav/testing/drawer-harness-filters.ts, src/material/sidenav/testing/drawer-harness.ts, src/material/sidenav/testing/public-api.ts, src/material/sidenav/testing/shared.spec.ts, src/material/sidenav/testing/sidenav-container-harness.ts, src/material/sidenav/testing/sidenav-content-harness.ts, src/material/sidenav/testing/sidenav-harness.spec.ts, src/material/sidenav/testing/sidenav-harness.ts, tools/public_api_guard/material/sidenav/testing.d.ts
* Adds test harnesses for `MatDrawerContainer`, `MatDrawerContent`, `MatSidenavContainer` and `MatSidenavContent`. This came up during the original PR review (#16695), but we never followed up on it.
* Fixes that `MatSidenavHarness.with` was returning a `MatDrawerHarness`. I had to move all the common code into a new class called `MatDrawerHarnessBase` so TS doesn't complain that the types don't match up.
=> feat(material/sidenav): add test harnesses for container and content elements

src/google-maps/map-marker-clusterer/map-marker-clusterer.ts, src/universal-app/kitchen-sink/kitchen-sink.html
We have a guard around trying to initialize the clusterer on the server, but there's some more logic in `ngAfterContentInit` that will end up throwing if it hasn't been initialized.
Also adds a server-side rendering check.
=> fix(google-maps): server-side rendering error from map clusterer

src/material-experimental/mdc-menu/_menu-theme.scss, src/material/menu/_menu-theme.scss
Fixes that the icons inside a disabled menu item still have their non-disabled color.
Fixes #20947.
=> fix(material/menu): icons in menu not inheriting disabled color

tools/tslint-rules/ngOnChangesPropertyAccessRule.ts
Follow-up to #21074. We have a lint rule that flags property accesses like `changes.foo` where `changes` is a `SimpleChanges` object, because they'll break under Closure compiler. The rule depends on the TS type checker to identify the objects, but it seems like somewhere along the way, tslint changed how they construct the `Program` which removed the necessary type information.
These changes add a less complicated fallback which looks at whether the name of the receiver of a property access is the same as the name of the first method parameter.
=> build: ngOnChanges property access rule not working

src/components-examples/material/card/card-harness/card-harness-example.spec.ts, src/components-examples/material/chips/chips-harness/chips-harness-example.spec.ts
* Uses `MatChipListboxHarness` for the chip harness example since `MatChipList` harness has some deprecated methods.
* Uses `parallel` instead of `Promise.all` like we do in the test harness code.
=> docs: remove deprecated harness usage and use parallel promise utility

guides/getting-started.md
=> docs: document global typography class prompt

scripts/check-mdc-exports-config.ts
Adds a couple of exceptions to the MDC exports CI check in order to resolve a failure in master.
=> build: fix exports check failure

CHANGELOG.md, package.json
This reverts commit 03b054fc17e00530776b82da100ea1fe54bfcd2d.
=> Revert "release: bump version to 11.0.1 w/ changelog (#21127)"

src/components-examples/material/chips/chips-autocomplete/chips-autocomplete-example.html, src/components-examples/material/chips/chips-input/chips-input-example.html, src/dev-app/chips/chips-demo.html
- add `mat-label`s to dev-app demos as well
- fix demo that doesn't have 100% width
As we discussed in a team meeting a few weeks ago, the docs don't have any examples of using chips in a form field with `mat-label`, which is our recommended approach now that the new appearances are the default.
=> docs(material/chips): add mat-labels to examples

src/cdk/schematics/ng-update/devkit-file-system.ts
=> fix(cdk/schematics): fix resolving modules in ng update

src/cdk/schematics/migration.json, src/cdk/schematics/ng-update/index.ts, src/cdk/schematics/update-tool/target-version.ts, src/material/schematics/migration.json, src/material/schematics/ng-update/index.ts
Sets up the schematics for the next major version so everything is in place once we need to add migrations.
=> build: set up schematics for v12

src/cdk/testing/test-harnesses.md
Add missing documentation for freshly added methods: `setInputValue`, `selectOptions` & `dispatchEvent`.
=> docs(cdk/testing): document TestElement methods

src/material-experimental/mdc-autocomplete/autocomplete.html, src/material-experimental/mdc-autocomplete/autocomplete.spec.ts, src/material/autocomplete/autocomplete-trigger.ts, src/material/autocomplete/autocomplete.html, src/material/autocomplete/autocomplete.spec.ts, src/material/autocomplete/autocomplete.ts, tools/public_api_guard/material/autocomplete.d.ts
Fixes https://github.com/angular/components/issues/20888
=> fix(material/autocomplete): add missing aria-label for autocomplete panel

src/cdk/a11y/focus-trap/focus-trap.ts, src/material/button-toggle/button-toggle.spec.ts, src/material/button-toggle/button-toggle.ts
Fixes focus issue with Chromevox in which you need to hit arrow key twice to move to the next button-toggle.
=> fix(material/button-toggle): fix ChromeVox focus issue on button toggle

src/cdk/observers/observe-content.ts, tools/public_api_guard/cdk/observers.d.ts
Fixes that the `ngAcceptInputType_debounce` was typed as a boolean input, even though it's a number.
Fixes #21101.
=> fix(cdk/observers): incorrect coercion member type

src/material-experimental/mdc-table/testing/cell-harness.ts, src/material/table/testing/cell-harness.ts, tools/public_api_guard/material/table/testing.d.ts
Besides text, table cells can contain other components.
Extending from ContentContainerComponentHarness
exposes more apis to query for children in the table cell.
Closes #21157
=> feat(table): expand cell harness api

src/material-experimental/mdc-select/select.scss
The MDC based form field is based on the MDC text field which doesn't actually have styles to handle select as the outline/text field is styled individually by each component. There are plans for MDC to consolidate text field/select styles but for now styles have to be added manually.
Before: 
After:
Note that floating label for the outline appearance currently has `text-overflow: clip` instead of `text-overflow: ellipsis`. https://github.com/material-components/material-components-web/blob/99cfb6bd53f72240fe76852d0fdaa0b82e7dca39/packages/mdc-notched-outline/_mixins.scss#L96
=> fix(material-experimental/mdc-select): fix long labels being incorrectly cut off

scripts/check-mdc-exports-config.ts, src/material-experimental/mdc-input/autosize.ts, src/material-experimental/mdc-input/module.ts, src/material-experimental/mdc-input/public-api.ts
Adds an equivalent to `MatTextareaAutosize` in the `mdc-input` package for backwards compatibility.
=> fix(material-experimental/mdc-input): add autosize directive

guides/creating-a-custom-form-field-control.md
See https://github.com/angular/components/blob/c68791db9a0b4107d04fa924c27a087cd00a8989/src/material/form-field/form-field.ts#L323
=> docs: fix css class in custom form field control guide

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/drag-ref.ts
By default we create a drag preview by cloning the element and inserting the preview at the document root to avoid issues with `overflow: hidden`. The problem is that the clone won't look correctly if the host styles were encapsulated to the shadow DOM.
These changes make it so that we insert the preview at the closest shadow root if the host is inside the shadow DOM, otherwise we fall back to the `body`.
=> fix(cdk/drag-drop): preview not inheriting styles inside shadow dom

src/material-experimental/mdc-radio/radio.spec.ts, src/material/radio/radio.spec.ts, src/material/radio/radio.ts
Fixes that `MatRadioGroup.selected` wasn't set if the value is assigned on init through a `ControlValueAccessor`.
Fixes #21148.
=> fix(material/radio): group selected button not set for preselected control value

src/material/slider/slider.spec.ts, src/material/slider/slider.ts
We have some logic that trims the value to the same number of decimals as the `step`, in order to avoid assigning long decimal values. The problem is that if the `min` or `max` are more precise than the `step`, we round up just above the `min` or below the `max`, preventing the user from reaching the end values.
These changes add an exception to the rounding for the `min` and `max` values.
Fixes #21147.
=> fix(material/slider): unable to assign min/max values if they are more precise than then step
