angular/components

src/material-experimental/mdc-radio/_radio-theme.scss
This mirrors how they are included in mdc-checkbox. Without this the radio label isn't styled.
=> fix(material-experimental/radio): include form field styles in mdc-radio theme

src/material/bottom-sheet/bottom-sheet-container.ts
In some components, like the dialog and snack bar, we had to remove `OnPush` change detection some time ago, because the views inside the component were being detected at their declaration place.
These changes apply the same fix to the bottom sheet.
Fixes #21141.
=> fix(material/bottom-sheet): some changes not being picked up

src/dev-app/mdc-table/BUILD.bazel, src/dev-app/mdc-table/mdc-table-demo-module.ts, src/dev-app/mdc-table/mdc-table-demo.html, src/dev-app/mdc-table/mdc-table-demo.scss, src/dev-app/mdc-table/mdc-table-demo.ts, src/material-experimental/mdc-table/table.scss
Also adds some demos that show it working and how to work around some of the other
style differences from the original MatTable.
=> fix(material-experimental/mdc-table): Fix sticky scrolling

CHANGELOG.md
We deprecated support for node-sass in v10 with the intent of removing it
in v11, but we did not make this clear in the v11 changelog. This PR
clarifies that node-sass support is ended.
=> docs(changelog): clarify end of support for node-sass

src/material/expansion/accordion.ts, tools/public_api_guard/material/expansion.d.ts
`MatAccordion` has a custom `QueryList` for keeping track of its own headers which we weren't destroying. These changes add a call to destroy it since it has the potential of leaking memory.
=> fix(material/expansion): not clearing custom query list

src/material-experimental/mdc-menu/menu.spec.ts, src/material-experimental/mdc-menu/menu.ts, src/material/menu/menu.spec.ts, src/material/menu/menu.ts
Clears the static `aria-` attributes from the menu host since they're forwarded to the menu overlay panel.
Fixes #21152.
=> fix(material/menu): clear static aria attributes from host node

src/material-experimental/mdc-checkbox/testing/checkbox-harness.ts, src/material/checkbox/checkbox.md, src/material/checkbox/testing/checkbox-harness.ts
updates the documentation and comments of customizing the default option of the checkbox.
the default option value to provide for checkbox is MAT_CHECKBOX_DEFAULT_OPTIONS for version>=10
fixes #21025
=> update on docs and comments for default option value for checkbox

src/material/datepicker/calendar-header.html, src/material/datepicker/calendar-header.spec.ts, src/material/datepicker/calendar.ts, tools/public_api_guard/material/datepicker.d.ts
The button for switching between calendar views has an `aria-label` along the lines of "Choose month" which overrides its default text. This means that the user has no way of knowing what is inside the button.
These changes add a further `aria-describedby` pointing to the content which lets the screen reader announce both pieces of text.
Note that an alternate approach is to concatenate the content into the `aria-label`, but I don't know how well that would work in RTL languages.
=> fix(material/datepicker): screen reader not announcing view switch button value

src/cdk/a11y/aria-describer/aria-describer.spec.ts, src/cdk/a11y/aria-describer/aria-describer.ts, tools/public_api_guard/cdk/a11y.d.ts
Previously searching for AriaDescriber messages in the browser would result in a ctrl-f stop that was invisible. This is because the `cdk-messages-container` had the `cdk-visually-hidden` class but that is not enough to remove the ctrl-f stops.
This fix maintains functionality while preventing extra ctrl-f stops.
Tested with:
macOS/VoiceOver
Windows/NVDA
=> fix(cdk/a11y): set AriaDescriber messages container to visibility:hidden

src/material/select/select.ts
In 17a9ad021b854b52a02c1f5f14347857f234cbec some logic was added that was setting the typeahead debounce interval to 0 if it isn't specified globally. This is incorrect, because we want it to stay undefined so the list key manager can fall back to its default interval.
Fixes #21242.
=> fix(material/select): incorrect default typeahead debounce time

src/material/core/typography/_typography.scss
This was mistakenly made public in https://github.com/angular/components/pull/21059
=> refactor(material/core): make typography normalization function private

src/cdk/testing/protractor/protractor-element.ts, src/cdk/testing/test-element.ts, src/cdk/testing/testbed/fake-events/dispatch-events.ts, src/cdk/testing/testbed/fake-events/event-objects.ts, src/cdk/testing/testbed/unit-test-element.ts, src/cdk/testing/tests/cross-environment.spec.ts, src/cdk/testing/tests/harnesses/main-component-harness.ts, src/cdk/testing/tests/test-main-component.html, src/cdk/testing/tests/test-main-component.ts, tools/public_api_guard/cdk/testing.d.ts, tools/public_api_guard/cdk/testing/protractor.d.ts, tools/public_api_guard/cdk/testing/testbed.d.ts
Adds the ability to provide modifier keys when clicking on a TestElement.
=> feat(cdk/testing): support modifiers for clicking on a TestElement

DEV_ENVIRONMENT.md
Fix link for installing MSYS2 in the Developer guide
=> docs: fix link in DEV_ENVIRONMENT guide

src/material-experimental/mdc-slide-toggle/slide-toggle.html
Required for internal styling so that we can target the `mdc-switch` element without using the `.mdc-switch` target
=> fix(material-experimental/mdc-slide-toggle): add class to mdc-switch element

src/material/dialog/dialog.md
It's currently not stated if and when the notification observables from `MatDialogRef` are closed. This causes questions and discussions both online and offline (in my team at work to be precise).
See different answers and comments in:
- https://stackoverflow.com/questions/58198544/angular-dialogref-unsubscribe-do-i-need-to-unsubscribe-from-afterclosed, 
- https://stackoverflow.com/questions/42343072/how-to-subscribe-to-angularmaterial-dialog-afterclosed/53556855
I think this matter should be mentioned in the documentation.
=> docs(material/dialog): state when notification observables close

src/cdk-experimental/menu/menu.spec.ts, test/benchmarks/cdk/testing/component-harness/protractor-benchmark-utilities.ts, test/benchmarks/material/button/button.perf-spec.ts, test/benchmarks/material/card/card.perf-spec.ts, test/benchmarks/material/checkbox/checkbox.perf-spec.ts, test/benchmarks/material/chips/chips.perf-spec.ts, test/benchmarks/material/form-field/form-field.perf-spec.ts, test/benchmarks/material/menu/menu.perf-spec.ts, test/benchmarks/material/radio/radio.perf-spec.ts, test/benchmarks/material/slide-toggle/slide-toggle.perf-spec.ts, test/benchmarks/material/table/table.perf-spec.ts, test/benchmarks/material/tabs/tabs.perf-spec.ts, test/benchmarks/mdc/button/button.perf-spec.ts, test/benchmarks/mdc/card/card.perf-spec.ts, test/benchmarks/mdc/checkbox/checkbox.perf-spec.ts, test/benchmarks/mdc/chips/chips.perf-spec.ts, test/benchmarks/mdc/form-field/form-field.perf-spec.ts, test/benchmarks/mdc/menu/menu.perf-spec.ts, test/benchmarks/mdc/radio/radio.perf-spec.ts, test/benchmarks/mdc/slide-toggle/slide-toggle.perf-spec.ts, test/benchmarks/mdc/table/table.perf-spec.ts, test/benchmarks/mdc/tabs/tabs.perf-spec.ts
* Replaces usages of the deprecated `browser.rootEl` with `browser.angularAppRoot`.
* Fixes a couple of places that were using `async` instead of `waitForAsync`.
=> build: clean up some internal deprecated API usages

src/material-experimental/mdc-button/button-base.ts
Set the ripple animation to 0ms enter/exit if `NoopAnimationsModule` detected. Since the ripple animation must be passed it, and it overrides the module, we need to manually set this
For discussion: This may be the wrong fix. The ripple's animation input declares this: 
```
/**
* Configuration for the ripple animation. Allows modifying the enter and exit animation
* duration of the ripples. The animation durations will be overwritten if the
* `NoopAnimationsModule` is being used.
*/
@Input('matRippleAnimation') animation: RippleAnimationConfig;
```
However, the logic does not adhere to this, and instead defers preference to the `this.animation` input:
```
animation: {
...this._globalOptions.animation,
...(this._animationMode === 'NoopAnimations' ? {enterDuration: 0, exitDuration: 0} : …
```
=> fix(material-experimental/mdc-button): fix ripple noop animation

src/dev-app/mdc-table/mdc-table-demo.html, src/material-experimental/mdc-table/BUILD.bazel, src/material-experimental/mdc-table/cell.ts, src/material-experimental/mdc-table/row.ts, src/material-experimental/mdc-table/table.scss, src/material-experimental/mdc-table/table.ts, src/material/table/BUILD.bazel, src/material/table/_table-flex-styles.scss, src/material/table/table.scss
Have consistent selectors between original MatTable and MDC-based MatTable.
Note that the mat-table tag is used for users that are styling tables with flex as per the MatTable documentation: https://material.angular.io/components/table/overview#tables-with-display-flex:~:text=Tables%20with%20display%3A%20flex,-The
=> feat(material-experimental/mdc-table): add mat-table selector

src/material-experimental/mdc-select/select.scss
If an MDC-based `mat-menu` is opened after a `mat-select`, the select will lose its `max-height`, because its selector specificity is too low and it gets overwritten by the menu which uses the same set of mixins.
These changes resolve the issue by increasing the specificity.
=> fix(material-experimental/mdc-select): panel losing max-height if menu is opened after select

src/cdk/scrolling/BUILD.bazel, src/cdk/scrolling/virtual-for-of.ts, src/cdk/scrolling/virtual-scroll-viewport.spec.ts
The virtual scroll only creates its `IterableDiffer` once, which means that if the `trackBy` function comes in at a later point (e.g. the input changed or the initialization order is different), it won't be picked up.
These changes make it so the differ always has a `trackBy` which then delegates to the user-provided one or falls back to the default.
Fixes #21281.
=> fix(cdk/scrolling): virtual scroll not picking up trackBy function when items come in after init

src/material/sort/sort-header.ts, tools/public_api_guard/material/sort.d.ts
The sort header arrow animation wasn't working correctly when it was triggered as a result of a focus/blur.
I'm marking this as a potential accessibility issue, because it prevents keyboard users from seeing what their potential sorted state would be.
Here's what it looks like at the moment:
=> fix(material/sort): animation not working correctly when activated on focus

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/drop-list-ref.ts, tools/public_api_guard/cdk/drag-drop.d.ts
Currently we set a class when a container is able to receive the dragged item, however we add this class to all connected containers without accounting for other things that could prevent the item from entering, like `enterPredicate`.
These changes add some logic to account for the predicate when setting the class.
Fixes #21171.
=> fix(cdk/drag-drop): account for enterPredicate when setting receiving class

src/material/table/table-data-source.spec.ts, src/material/table/table-data-source.ts, tools/public_api_guard/material/table.d.ts
* Fixes that the table data source wasn't unsubscribing from sorting, pagination etc. when it is disconnected.
* Adds a bit of logic to properly support re-connecting the same date source again.
* Fixes up a couple of issues in the unit test setup which could cause state to leak between tests.
Fixes #21270.
=> fix(material/table): unsubscribe from source when disconnecting

src/material-experimental/mdc-progress-spinner/progress-spinner.scss
Animations were still being shown because the selector `:not(._mat-animation-noopable)` by itself matched plenty of parent elements. This specifies the right parent element that should be checked.
Also, this forces the spinner to be a complete circle when there are no animations, rather than some odd looking broken spinner shape
=> fix(material-experimental/mdc-progress-spinner): fix noop animation

src/components-examples/material/autocomplete/autocomplete-auto-active-first-option/autocomplete-auto-active-first-option-example.html, src/components-examples/material/autocomplete/autocomplete-filter/autocomplete-filter-example.html, src/components-examples/material/autocomplete/autocomplete-optgroup/autocomplete-optgroup-example.html, src/components-examples/material/autocomplete/autocomplete-overview/autocomplete-overview-example.html, src/components-examples/material/autocomplete/autocomplete-simple/autocomplete-simple-example.html
Update form field related examples to use `<mat-label>` where appropriate
=> docs(material/autocomplete): add mat-label to examples

src/components-examples/material/form-field/form-field-overview/form-field-overview-example.css, src/components-examples/material/form-field/form-field-overview/form-field-overview-example.html, src/components-examples/material/form-field/form-field-overview/form-field-overview-example.ts
* Fixes an example that was referring to the `example-container` class, but wasn't actually using it.
* Uses flexbox to layout the example, instead of `br` tags which are an anti-pattern.
Fixes https://github.com/angular/material.angular.io/issues/889.
=> docs: fix form field example styles

scripts/check-mdc-exports-config.ts, scripts/check-mdc-exports.ts, src/material-experimental/mdc-button/testing/public-api.ts, src/material-experimental/mdc-checkbox/testing/public-api.ts, src/material-experimental/mdc-menu/testing/public-api.ts, src/material-experimental/mdc-progress-bar/testing/public-api.ts, src/material-experimental/mdc-progress-spinner/testing/public-api.ts, src/material-experimental/mdc-slide-toggle/testing/public-api.ts, src/material-experimental/mdc-slider/testing/public-api.ts
Expands the `check-mdc-exports` script to also check the `/testing` packages for consistency. Also exports the missing symbols that were caught by the script.
=> build: check MDC testing exports and add missing symbols

src/material-experimental/mdc-menu/menu.spec.ts, src/material/menu/menu-trigger.ts, src/material/menu/menu.spec.ts, tools/public_api_guard/material/menu.d.ts
Fixes that we were setting the `program` focus origin on the first menu item, even though the user opened it using the keyboard.
Fixes #21241.
=> fix(material/menu): set correct focus origin on item when opened via keyboard

src/material/datepicker/year-view.ts, tools/public_api_guard/material/datepicker.d.ts
Open up the mat year view's `ChangeDetectorRef`  so it can be accessed by other components. This is necessary to align with an internal Google datepicker spec.
=> refactor(material/datepicker): expose year view change detector ref

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/directives/drag.ts, src/cdk/drag-drop/drag-ref.ts, tools/public_api_guard/cdk/drag-drop.d.ts
Some time ago we added logic to stop event propagation so that nested drag items don't trigger multiple sequences. Stopping propagation for all events seems to interfere multiple other use cases so these changes add some logic so that we only stop propagation when items are nested.
There was something similar in #19334, but I decided not to move forward with it, because it required consumers to know the internals of the `drag-drop` module, whereas this approach can do it automatically.
Fixes #19333.
=> fix(cdk/drag-drop): don't stop event propagation unless nested

src/material/datepicker/calendar-body.scss, src/material/datepicker/datepicker-base.ts, src/material/datepicker/datepicker-content.html
Resolves the following accessibility issues when the datepicker is in touch UI mode:
* Focus was going directly to the close button, because that's the first element that the dialog's focus trap was running into. I've disabled the automatic focus redirection since the calendar has its own.
* The calendar close button for screen readers was off-screen, because the dialog container has `position: static` and `overflow: auto`.
Apart from the two issues above, I've also made it so the screen reader button's theme color matches the one of the calendar. This is mostly so the button doesn't look out of place if the calendar has a different theme and the user tabs into it.
=> fix(material/datepicker): a couple of accessibility issues in touch UI mode

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/drag-drop-registry.spec.ts, src/cdk/drag-drop/drag-drop-registry.ts, src/cdk/drag-drop/drag-ref.ts, tools/public_api_guard/cdk/drag-drop.d.ts
The `DragRef` has the ability to add a delay to the dragging so that scrolling isn't blocked on touch devices. Currently this doesn't really work, because we always block the native event as a result of a949db30c7554c32df77b81d163fe7d8cbb83c97.
These changes move some code around so that we only block the events if the item considers itself as being in a "dragged" state (the delay has elapsed and the user is past the drag threshold).
Fixes #17923.
=> fix(cdk/drag-drop): don't block scrolling if it happens before delay has elapsed

src/material-experimental/mdc-progress-spinner/progress-spinner.scss
Seems like a regression from #21359. We can't use `:not` to apply the animation styles, because MDC's mixins target `.mdc-progress-spinner`, rather than `&`.
These changes use the same manual approach as other components to disable the animations.
For reference, the circle looks like this in master:
=> fix(material-experimental/mdc-progress-spinner): indeterminate animation not working

src/cdk/table/table.ts, src/material-experimental/mdc-table/BUILD.bazel, src/material-experimental/mdc-table/table.spec.ts, src/material-experimental/mdc-table/table.ts, tools/public_api_guard/cdk/table.d.ts
The MDC-based table tries to add a class to its internal `tbody` element and it assumes that it's always going to find it. The assumption used to be correct since we only supported native `table` elements for the MDC implementation, however as of #20994 we also support flexbox-based ones which throw an error, because they don't have a `tbody`.
These changes add a check to prevent the error and include a couple of sanity tests to catch issues like this in the future.
I've also reworked the tests so that they use the MDC-based `MatPaginator` and `MatTableDataSource`, instead of the base ones.
=> fix(material-experimental/mdc-table): error when flexbox-based table is initialized

src/cdk/overlay/scroll/block-scroll-strategy.ts, src/cdk/platform/features/scrolling.ts
To avoid a scrolling animation when we disable scrollig, we remove and re-set the `scroll-behavior` property on the body without feature checking it. The problem is that since we've set the property to *something*, our `scrollBehaviorSupported` feature check will be thrown off because it checks for `'scrollBehavior' in document.documentElement.style`.
Fixes #17221.
=> fix(cdk/overlay): block scroll strategy throwing off scroll behavior feature detection

src/material-experimental/mdc-autocomplete/autocomplete.scss
Along the same lines as #21341. If an MDC-based mat-menu is opened after a mat-autocomplete, the autocomplete will lose its max-height, because its selector specificity is too low and it gets overwritten by the menu which uses the same set of mixins.
These changes resolve the issue by increasing the specificity.
=> fix(material-experimental/mdc-autocomplete): panel losing max-height if menu is opened after autocomplete

src/dev-app/dev-app/dev-app-layout.html, src/dev-app/dev-app/dev-app-layout.ts
Our dev app is set up so that the density styles are set on the `body` while the `dir` is set only around the content. The problem is that MDC's mixins output density styles for RTL in the format `[dir='rtl'] .density .foo` which means that the directionality has to be a level above the density class or we won't get an accurate representation of how the components look. This threw me off for a while earlier today, because I noticed that the MDC slide toggle didn't behave correctly in RTL.
These changes fix the issue by moving the `dir` a level up and applying the density class in a couple of places.
=> build: fix not being able to test MDC density in RTL

src/components-examples/material/icon/icon-svg/icon-svg-example.ts
The SVG icon examples 404s when opened on Stackblitz due to an old issue with static assets. These changes switch to using an icon literal so that we don't have to fetch the icon.
Fixes #16484.
=> docs: fix SVG icon example on Stackblitz

guides/typography.md, src/dev-app/index.html, src/e2e-app/index.html, src/material/schematics/ng-add/fonts/material-fonts.ts, src/material/schematics/ng-add/index.spec.ts, src/universal-app/index.html
Switches the schematics, guides and internal dev apps to use the second version of the Google Fonts loading snippet.
Fixes #21478.
=> feat(material/schematics): use newer Google Fonts version

tools/dev-server/dev-server.ts, tools/release/changelog.ts, tools/release/release-output/check-package.ts
Fixes a few compilation errors in some utility scripts that haven't been caught by the CI.
=> build: fix compilation errors in utility scripts

src/material/slider/slider.md
In the tick marks section of the slider the word between is repeated.
=> docs(material/slider): updated slider documentation.

.github/CODEOWNERS, .ng-dev/commit-message.ts, src/cdk-experimental/config.bzl, src/cdk-experimental/table-scroll-container/BUILD.bazel, src/cdk-experimental/table-scroll-container/index.ts, src/cdk-experimental/table-scroll-container/public-api.ts, src/cdk-experimental/table-scroll-container/table-scroll-container-module.ts, src/cdk-experimental/table-scroll-container/table-scroll-container.spec.ts, src/cdk-experimental/table-scroll-container/table-scroll-container.ts, src/cdk/table/public-api.ts, src/cdk/table/sticky-position-listener.ts, src/cdk/table/sticky-styler.ts, src/cdk/table/table.spec.ts, src/cdk/table/table.ts, src/dev-app/BUILD.bazel, src/dev-app/dev-app/dev-app-layout.ts, src/dev-app/dev-app/routes.ts, src/dev-app/table-scroll-container/BUILD.bazel, src/dev-app/table-scroll-container/table-scroll-container-demo-module.ts, src/dev-app/table-scroll-container/table-scroll-container-demo.html, src/dev-app/table-scroll-container/table-scroll-container-demo.scss, src/dev-app/table-scroll-container/table-scroll-container-demo.ts, src/dev-app/theme.scss, tools/public_api_guard/cdk/table.d.ts
Adds the CdkTableScrollContainer and some hooks in CdkTable for it.
For Webkit/Blink browsers, this sizes the scroll bars in coordinating with
sticky rows/columns in the table to create the user experience that a lot of
commenters in #5885 seemed to want but without the accessibility problems of
other approaches.
=> feat(cdk-experimental/table-scroll-container): Create directive and demo

src/material/datepicker/date-range-input-parts.ts, src/material/datepicker/date-range-input.spec.ts, src/material/datepicker/datepicker-input-base.ts, src/material/datepicker/datepicker-input.ts, tools/public_api_guard/material/datepicker.d.ts
Fixes that the date range input controls were marking each other as dirty on initialization. This seems like an easy fix on the surface, but it's somewhat tricky, because while we usually don't want the inputs to respond each other's events, we still want it to happen if an end date before the start date is assigned.
These changes resolve the issue by not having the inputs respond to any events from inside the input, but notify each other when a value is assigned programmatically.
I've also cleaned up some unnecessary code and added more test cases for things that tripped me up while fixing the issue.
Fixes #20213.
=> fix(material/datepicker): range input controls dirty on init

src/material-experimental/mdc-snack-bar/_snack-bar-theme.scss
This matches the styles found in our current snack bar, which causes the button to be accent in light theme and inherit in dark. Otherwise, MDC colors it according to their default button color
=> fix(material-experimental/mdc-snack-bar): simple snack button should be accent

src/components-examples/material/datepicker/datepicker-actions/datepicker-actions-example.css, src/components-examples/material/datepicker/datepicker-actions/datepicker-actions-example.html, src/components-examples/material/datepicker/datepicker-actions/datepicker-actions-example.ts, src/components-examples/material/datepicker/index.ts, src/dev-app/datepicker/datepicker-demo.html, src/dev-app/datepicker/datepicker-demo.ts, src/material/datepicker/BUILD.bazel, src/material/datepicker/date-range-picker.ts, src/material/datepicker/date-selection-model.ts, src/material/datepicker/datepicker-actions.scss, src/material/datepicker/datepicker-actions.spec.ts, src/material/datepicker/datepicker-actions.ts, src/material/datepicker/datepicker-base.ts, src/material/datepicker/datepicker-content.html, src/material/datepicker/datepicker-content.scss, src/material/datepicker/datepicker-module.ts, src/material/datepicker/datepicker.md, src/material/datepicker/datepicker.ts, src/material/datepicker/public-api.ts, tools/public_api_guard/material/datepicker.d.ts
Adds support for projecting in "Cancel" and "Apply" buttons in `mat-datepicker` and `mat-date-range-picker`. Doing so will change the behavior of the datepicker so that the user has to explicitly accept a value after they've clicked on it. The consumption is as follows:
```
<mat-datepicker>
<mat-datepicker-actions>
<button mat-button matDatepickerCancel>Cancel</button>
<button mat-raised-button color="primary" matDatepickerApply>Apply</button>
</mat-datepicker-actions>
</mat-datepicker>
```
The result looks like this:
=> feat(material/datepicker): add support for cancel/apply buttons

src/cdk/a11y/focus-monitor/focus-monitor.spec.ts, src/cdk/a11y/focus-monitor/focus-monitor.ts
In #20966 some logic was added so that calling `focusVia` on an element that already has focus would change the origin to the passed-in one. The problem is that the new logic doesn't account for when a parent element is monitored and `focusVia` is called on a child.
These changes add some more logic that will look through all the monitored elements that have `checkChildren: true` and will switch the origin accordingly.
Fixes #21500.
cc @zelliott
=> fix(cdk/a11y): focusVia not accounting for focused child node

src/material/datepicker/date-range-input-parts.ts, src/material/datepicker/date-range-input.spec.ts, tools/public_api_guard/material/datepicker.d.ts
Fixes that the `errorStateMatcher` on the date range inputs wasn't marked as an `Input` which made it impossible to change.
Fixes #21205.
=> fix(material/datepicker): unable to pass in errorStateMatcher through binding on range input

src/material-experimental/mdc-autocomplete/autocomplete.spec.ts, src/material/autocomplete/autocomplete-trigger.ts, src/material/autocomplete/autocomplete.spec.ts
Fixes that the autocomplete panel doesn't close when the user presses outside using the middle or right mouse button.
=> fix(material/autocomplete): not closing when clicking outside using auxiliary button

src/material/datepicker/calendar-body.scss
Fixes that users in high contrast mode aren't able to distinguish between enabled and disabled calendar cells.
=> fix(material/datepicker): unable to distinguish disabled calendar cells in high contrast mode

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/directives/drop-list.ts, src/cdk/drag-drop/drop-list-ref.ts, tools/public_api_guard/cdk/drag-drop.d.ts
Adds the ability for the scrolling speed of a drop list to be configured.
Fixes #19401.
=> feat(cdk/drag-drop): support configurable scroll speed

src/material-experimental/mdc-table/table.scss, src/material/core/style/_vendor-prefixes.scss, src/material/table/table.scss
The sticky styles were switched to a class in #19823 which has a very low specificity. As a result, there's a high chance of it being overwritten by some user styles.
These changes use `!important` so that we get a similar specificity as when the styles were being set inline before #19823.
Fixes #20558.
cc @kseamon
=> fix(material/table): increase specificity on sticky selector

src/material/icon/icon-registry.ts, src/material/icon/icon.spec.ts, src/material/icon/testing/fake-icon-registry.ts, tools/public_api_guard/material/icon.d.ts, tools/public_api_guard/material/icon/testing.d.ts
Currently all of the ways to register icons (e.g. via URL or literal) require the developer to know the list of icons ahead of time or to fetch more icons than the user needs. These changes aim to address this issue by adding the ability to register an icon resolver function which will construct the URL at runtime, depending on the requested icon.
Fixes #18607.
=> feat(material/icon): add support for registry resolver function

src/material/menu/menu-trigger.ts
Currently the menu only shrinks if the users scrolls after it has been opened, but
if they scroll back to a place where there's enough place to fit the content, the menu
will stay collapsed.
These changes adjust the config so the menu can grow after it was opened.
Fixes #18168.
Fixes #13988.
=> fix(material/menu): allow menu height to grow after open

src/material-experimental/mdc-list/list-option.html, src/material-experimental/mdc-list/list-option.scss, src/material-experimental/mdc-list/list-option.ts
Due to how MDC's checkbox styles are set up, we always have to keep an `input` inside the `mat-list-option`, however our current setup where we only set `tabindex="-1"` on it is invalid, because the input is still interactive either through clicking on it, or by using a screen reader's forms mode.
These changes completely remove the input from the accessibility model by setting it to `display: none`.
=> fix(material-experimental/mdc-list): make internal input non-interactive

src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss
The outline of the `fill` appearance is done through a background color which will blend in with the background in high contrast mode. These changes add an outline to replace it.
=> fix(material-experimental/mdc-form-field): fill appearance blending in with the background in high contrast mode

src/material/core/option/option.scss
Fixes that disabled `mat-option` instances cannot be distinguished from enabled ones in high contrast mode.
=> fix(material/core): unable to distinguish disabled mat-option in high contrast mode

src/material/datepicker/datepicker-content.scss
The screen reader close button is rendered outside the dialog which seems to cause a scrollbar to be shown while the animation is running. These changes fix the issue by hiding the button while the dialog is animating.
Slowed down video for reference:
=> fix(material/datepicker): remove scroll bar while animating in touch UI mode

src/cdk/scrolling/fixed-size-virtual-scroll.ts
When firstVisibleIndex divides by zero, which can happen when the page is built and loaded dynamically; the NaN result will be used in other calculations.
This then throws off things like the `newRange.start` value also returning NaN, breaking the plugin.
=> fix(cdk/scrolling): Prevents NaN being returned as firstVisibleIndex.

README.md
We're still working on the same set of projects for Q1 2021 as we were for Q4 2020.
The bulk of our effort is going into rolling out our MDC-based components to our users
inside Google. This is the first phase of our MDC-component rollout; the second phase
will involve moving the components to our stable npm packages.
Fixes #21538
=> docs: update readme for Q1 2021

src/material/tree/node.ts
- also update TODO comments since the related issue was closed as a duplicate,
point to the new issue
The mat docs for this seem to loose some context
That is in the CDK docs
=> docs(material/tree): add a description of the when predicate

src/cdk/table/table.ts, src/material-experimental/mdc-table/BUILD.bazel, src/material-experimental/mdc-table/table.spec.ts, src/material-experimental/mdc-table/table.ts, tools/public_api_guard/cdk/table.d.ts, yarn.lock
This reverts commit aade5d130e9d04a16464666fe42cf61ad26e772f.
Original change broke the build, reverting for patch branch.
=> Revert "fix(material-experimental/mdc-table): error when flexbox-based table is initialized (#21428)"

src/material-experimental/mdc-snack-bar/snack-bar-container.scss
Fixes that the MDC-based snack bar gets centered, but it doesn't stretch to the full viewport width on the handset breakpoint.
=> fix(material-experimental/mdc-snack-bar): not stretching to full width on handset

src/material/core/typography/_typography.scss
2018 style typography configs.
This is part of a plan to reconcile how typography is handled in the
different versions of Material Design (both external versions and
Google's internal spec).
=> refactor(material/core): add functions for normalizing to 2014 and

src/material-experimental/mdc-table/table.scss
MDC flex table rows have a bottom border from legacy styles, and a top border for MDC styles. This means each row has two borders between them. This removes the bottom border and leaves the top
One option could have been to pass a flag to the mixin `mat-private-table-flex-styles` that says not to put in the border. However, this won't help in the case for apps that want to load both old and new table styles.
=> fix(material-experimental/mdc-table): remove bottom border for flex table

.github/CODEOWNERS
Correct the misindented entry for husky files in CODEOWNERS.
=> ci: fix indentation of CODEOWNERS entries

src/material-experimental/mdc-list/list-base.ts, src/material-experimental/mdc-list/list-option.ts, src/material-experimental/mdc-list/list.ts
Fixes that the MDC-based list doesn't disable its ripples when they have been disabled globally.
=> fix(material-experimental/mdc-list): not accounting for global ripple options

src/material-experimental/mdc-autocomplete/autocomplete.spec.ts, src/material/autocomplete/autocomplete-trigger.ts, src/material/autocomplete/autocomplete.spec.ts
Currently the autocomplete trigger will activate the first option when `autoActiveFirstOption`, no matter whether it is disabled. These changes use a different API which will allow us to pick the first enabled option.
Fixes #21498.
=> fix(material/autocomplete): activate first enabled option with autoActiveFirstOption

src/material-experimental/mdc-menu/menu.scss, src/material/menu/menu.scss
Firefox seems to have an issue where the items cut off each other's outline in high contrast mode. These changes work around the issue by introducing a slight margin.
Note that this isn't ideal, because the whole point of using an outline is so that the layout isn't different on high contrast mode. The alternate approach is to use a `border`, but it will cause the element to move around as the user is navigating.
Fixes #21524.
=> fix(material/menu): focus indication rendering partially in high contrast mode

src/material-experimental/mdc-tabs/_tabs-theme.scss, src/material/tabs/_tabs-theme.scss
Fixes that setting a `backgroundColor` on a top-level tab group ends up being inherited to all grounds nested within it. The problem was that our selectors were too broad and they were targeting all descendants.
Fixes #14819.
Fixes #21530.
=> fix(material/tabs): background color inherited to nested groups

src/material-experimental/mdc-core/option/option.scss, src/material/core/option/option.scss
We had an override to make the option ripple semi-transparent in high contrast mode. This hasn't been necessary for a while, because we've been setting `display: none` on all ripples for high contrast users.
=> refactor(material/core): remove unnecessary styles from mat-option

src/material/datepicker/datepicker-base.ts, src/material/datepicker/datepicker.spec.ts
Adds the ability to disable focus restoration in the datepicker, similar to what we have in the dialog.
Fixes #20750.
=> feat(material/datepicker): allow for focus restoration to be disabled

src/material/button/button.scss
Fixes misaligning anchor element with mat-icon-button applied. This also fixes misaligning on other elements like div.
Fixes #20949
=> fix(material/button): anchor mat-icon-button as matSuffix focus misaligned

src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts, src/cdk/overlay/position/flexible-connected-position-strategy.ts
If the browser is zoomed in beyond the default level, it may report numbers with sub-pixel deviations to `getBoundingClientRect` (e.g. 100.09 vs 100) which can throw off our logic when comparing against the viewport size which is always a whole number.
These changes fix the issue by rounding down the numbers that we get from `getBoundingClientRect`.
Fixes #21350.
=> fix(cdk/overlay): sub-pixel deviations throwing off positioning in some cases

.circleci/config.yml, package.json, tools/tsconfig-ci.json, tools/tslint-rules/noUnescapedHtmlTagRule.ts
A lot of the scripts under `tools` are only run manually which means that it's easy for compilation errors to slip by when dependencies are updated.
These changes add another CI check to ensure that the scripts compile.
=> build: check tooling scripts for compilation errors

.github/angular-robot.yml, .ng-dev/caretaker.ts, .ng-dev/config.ts
Create the configuration for the caretaker check command in the repo.
Makes available a check of the state of repository for caretakers via `yarn ng-dev caretaker check`
```
$ yarn ng-dev caretaker check
fatal: couldn't find remote ref g3
Github Tasks
Merge Queue   0
Triage Queue  3
https://github.com/angular/components/issues?q=is:open%20label:%22needs%20triage%22
- https://github.com/angular/components/issues/21593
- https://github.com/angular/components/issues/21592
- https://github.com/angular/components/issues/21583
Service Statuses
Saucelabs ✅
Npm       ✅
CircleCi  ✅
Github    ✅
CI
releaseCandidate (11.1.x) ✅
latest (11.0.x)           ✅
next (master)             ✅
```
=> build: configure the ng-dev caretaker check command

src/material-experimental/mdc-radio/radio.spec.ts, src/material-experimental/mdc-radio/radio.ts, src/material/radio/radio.spec.ts, src/material/radio/radio.ts
Removes the `tabindex` from the host node, because it causes some a11y issues. We had it there before so that things like `cdkFocusInitial` would work, but after #21046 it isn't necessary anymore.
Fixes #21266.
=> fix(material/radio): remove tabindex from host node

src/material-experimental/mdc-chips/chip-grid.spec.ts, src/material-experimental/mdc-chips/chip-grid.ts, src/material-experimental/mdc-chips/chip-remove.spec.ts, src/material-experimental/mdc-chips/chip-row.spec.ts, src/material-experimental/mdc-chips/chip-row.ts, src/material-experimental/mdc-chips/chip.spec.ts, src/material-experimental/mdc-chips/chip.ts, src/material-experimental/mdc-chips/chips.scss, src/material-experimental/mdc-chips/testing/chip-harness.ts
Currently the MDC chips automatically trigger an animation that collapses the chip to 0x0 dimensions, but it still keeps it in the DOM unless the consumer updates their data source. This is misleading and there's no way for the consumer to see it.
These changes bring the chip in line with our current behavior where we only dispatch the remove event and then it's up to the consumer to remove the chip.
Making these changes also revealed some tests that were passing by accident and weren't actually testing the things they were supposed to, because the `animationend` event wasn't being dispatched. I've tweaked them in order to get them to work as expected.
Fixes #21561.
=> fix(material-experimental/mdc-chips): decouple removal from animation

src/material/tooltip/tooltip.spec.ts, src/material/tooltip/tooltip.ts
Similar to #21397. Fixes that the tooltip doesn't close when the user presses outside using the middle or right mouse button.
=> fix(material/tooltip): not closing when clicking outside using auxiliary button

src/cdk-experimental/column-resize/event-dispatcher.ts, src/cdk-experimental/dialog/dialog-ref.ts, src/cdk/scrolling/virtual-for-of.ts, src/cdk/scrolling/virtual-scroll-viewport.ts, src/material-experimental/mdc-paginator/paginator.spec.ts, src/material-experimental/mdc-tabs/tab-body.ts, src/material/dialog/dialog-ref.ts, src/material/expansion/expansion-panel.ts, src/material/form-field/form-field.ts, src/material/paginator/paginator.spec.ts, src/material/tabs/tab-body.ts, src/youtube-player/youtube-player.ts, tools/public_api_guard/material/tabs.d.ts
Cleans a handful of usages of deprecated APIs.
=> refactor(material/core): clean up deprecated API usages

package.json, src/material-experimental/mdc-progress-bar/progress-bar.ts, yarn.lock
=> refactor(material-experimental/mdc-progress-bar): update mdc-progress-bar to be compatible with API changes in MDC

src/material-experimental/mdc-slider/slider-adapter.ts, src/material-experimental/mdc-slider/slider.ts
* add method stubs for MDCSliderAdapter implementation
* add basic setup for MDCSliderFoundation in MatSlider
=> feat(material-experimental/mdc-slider): add skeleton code for MDCSliderFoundation

scripts/check-mdc-exports-config.ts, src/material-experimental/mdc-checkbox/testing/BUILD.bazel, src/material-experimental/mdc-checkbox/testing/checkbox-harness.ts, src/material/checkbox/testing/checkbox-harness.ts, tools/public_api_guard/material/checkbox/testing.d.ts
Refactors the MDC checkbox harness so that it extends the non-MDC one directly, because most of the logic is identical.
=> refactor(material-experimental/mdc-checkbox): de-duplicate test harness logic

src/material-experimental/mdc-menu/testing/BUILD.bazel, src/material-experimental/mdc-menu/testing/menu-harness.ts, src/material/menu/testing/menu-harness.ts, tools/public_api_guard/material/menu/testing.d.ts
De-duplicates the test harness logic between the base and MDC menu test harnesses.
=> refactor(material-experimental/mdc-menu): de-duplicate test harness logic

src/material-experimental/mdc-autocomplete/testing/BUILD.bazel, src/material-experimental/mdc-autocomplete/testing/autocomplete-harness.ts, src/material/autocomplete/testing/autocomplete-harness.ts, src/material/autocomplete/testing/shared.spec.ts, tools/public_api_guard/material/autocomplete/testing.d.ts
De-duplicates the test harness logic between the base and MDC autocomplete test harnesses.
=> refactor(material-experimental/mdc-autocomplete): de-duplicate test harness logic

src/material-experimental/mdc-select/testing/BUILD.bazel, src/material-experimental/mdc-select/testing/select-harness.ts, src/material/select/testing/select-harness.ts, tools/public_api_guard/material/select/testing.d.ts
Reworks the `MatSelectHarness` in order to de-duplicate the logic between the base and MDC implementations.
=> refactor(material-experimental/mdc-select): de-duplicate test harness logic

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/directives/drag.ts, src/cdk/drag-drop/drag-ref.ts, tools/public_api_guard/cdk/drag-drop.d.ts
Some logic was added in #21227 which would only `stopPropagation` when dragging if a parent drag item is detected. The problem is that we resolve the parent using DI which won't work if the item is projected through something like `ngTemplateOutlet`.
These changes resolve the issue by falling back to resolving the parent through the DOM.
=> fix(cdk/drag-drop): not detecting parent when projected using ngTemplateOutlet

src/material/datepicker/date-range-input.spec.ts, src/material/datepicker/date-range-input.ts, src/material/datepicker/datepicker-input.ts, src/material/datepicker/datepicker.spec.ts, tools/public_api_guard/material/datepicker.d.ts
Currently we mark the date input model as touched when it is blurred or the user types something in, however opening and closing the calendar is also an indicator that the user has interacted with it.
These changes add some logic to mark the inputs as touched when the calendar is closed as well.
Fixes #21643.
=> fix(material/datepicker): mark date input as touched when calendar is closed

src/material/form-field/form-field.scss
Fixes some flickering in all adjacent form fields that happens when a specific form field is in its invalid state and the user hovers over it.
Fixes #21612.
=> fix(material/form-field): flickering when hovering invalid input on chrome

src/material-experimental/mdc-autocomplete/autocomplete.scss, src/material/autocomplete/autocomplete.scss
Similar to #21246. Prevents the inert host node for `mat-autocomplete` from affecting the layout around it.
=> fix(material/autocomplete): prevent inert host node from affecting surrounding layout

scripts/check-mdc-exports-config.ts
Fixes a few lint failures that got through, because the related PRs were opened before the check was introduced.
=> build: fix lint failures

src/cdk/overlay/overlay-ref.ts, src/cdk/overlay/overlay.spec.ts
We set `pointer-events: auto` on the overlay when it is attached and then `none` while it's detaching which ends up overriding any other styles the user might have. These changes reset to `''` instead.
Fixes #21656.
=> fix(cdk/overlay): overriding pointer-events style

src/material/datepicker/datepicker-toggle.ts, src/material/datepicker/datepicker.spec.ts
Similar to #21280. Removes the `tabindex` from the `mat-datepicker-toggle` host since it can caused accessibility issues. It was only there as a workaround which isn't required after #21046.
=> fix(material/datepicker): clear tabindex from host node

package.json, yarn.lock
Update to the latest version of the ng-dev toolset, bringing in support for the
`--[no-]branch-prompt` flag.
=> build: update to the latest version of @angular/dev-infra-private

src/material-experimental/mdc-helpers/_mdc-helpers.scss
It looks like there was a bug in the logic that converts mat- configs to mdc- configs. It caused the mdc-level to always be null. This fixes it, though we'll have to see what the visual effects will be
=> fix(material-experimental/mdc-typography): fix always using mat-level

src/material-experimental/mdc-autocomplete/README.md, src/material-experimental/mdc-checkbox/README.md, src/material-experimental/mdc-menu/README.md, src/material-experimental/mdc-paginator/README.md, src/material-experimental/mdc-progress-bar/README.md, src/material-experimental/mdc-progress-spinner/README.md, src/material-experimental/mdc-select/README.md, src/material-experimental/mdc-slide-toggle/README.md, src/material-experimental/mdc-tabs/README.md
Fixes the error
```
Error: ./src/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Missing argument $config-or-theme.
┌──> src\styles.scss
14 │ @include mat-mdc-select-typography();
│ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ invocation
╵
┌──> node_modules\@angular\material-experimental\mdc-select\_select-theme.scss
82 │ @mixin mat-mdc-select-typography($config-or-theme) {
│        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ declaration
╵
src\styles.scss 14:1  mat-mdc-select-typography()
```
Note: the same problem also occurs in 
```
src\material-experimental\mdc-autocomplete  (1 usage found)
README.md  (1 usage found)
73 @include …
```
=> docs(material-experimental): fix scss examples

src/cdk/collections/recycle-view-repeater-strategy.ts
When the `_RecycleViewRepeaterStrategy` is destroyed, it destroys all views in its cache, but it still retains references to them. These changes clear the references and do some minor internal cleanup.
=> fix(cdk/collections): recycle repeater strategy retaining references to destroyed views

package.json, src/material/grid-list/public-api.ts, tools/public_api_guard/generate-guard-tests.bzl, tools/public_api_guard/material/grid-list.d.ts, yarn.lock
Updates to `ts-api-guardian` 0.6.0 and fixes a newly-introduced build error.
=> build: update to latest ts-api-guardian and fix error

scripts/check-mdc-tests-config.ts, src/material/select/select.spec.ts, src/material/select/select.ts
Fixes a the overlay offset calculation for grouped option values if `disableOptionCentering` is true.
The overlay should not have double offset value for any selected option to keep it under the
trigger element.
Fixes #21570
=> fix(material/select): overlay offset calculation for disabled option centering

src/material-experimental/mdc-dialog/dialog-container.ts, src/material-experimental/mdc-dialog/dialog.spec.ts, src/material/dialog/dialog.spec.ts
Fixes that all of the callbacks tied to animations within the MDC-based dialog were being run outside of the `NgZone`.
Fixes #21696.
=> fix(material-experimental/mdc-dialog): afterClosed being run outside of NgZone

src/material/sort/sort.spec.ts, src/material/sort/sort.ts, tools/public_api_guard/material/sort.d.ts
- Adds `MAT_SORT_DEFAULT_OPTIONS` injection token so apps can configure default behavior of `mat-sort` for the entire app.
- Adds tests to verify default options. Existing tests were grouped into a separate `describe()` block. This messed with github's diff view, but existing tests were not changed.
=> feat(material/sort): Add default configuration options

src/material/datepicker/month-view.spec.ts, src/material/datepicker/month-view.ts
Currently the preview range stays there until the user moves their pointer into another date cell which looks glitchy. These changes add a couple of extra calls so the range is removed immediately.
This wasn't noticeable until now since the calendar was closed immediately, but that's no longer the case when datepicker actions are projected.
=> fix(material/datepicker): reset preview range after selecting a date

src/material-experimental/mdc-menu/menu.spec.ts, src/material/menu/menu-trigger.ts, src/material/menu/menu.spec.ts, src/material/menu/menu.ts, tools/public_api_guard/material/menu.d.ts
Fixes that navigating back from a nested menu using the keyboard doesn't restore focus to the previous trigger, breaking the interaction since it ends up going back to the `body`. This used to work, but seems to have regressed at some point.
**Note:** marking as a P2, because the current behavior completely breaks the keyboard navigation between nested menus.
=> fix(material/menu): nested menu trigger not restoring focus

src/dev-app/mdc-input/mdc-input-demo.html, src/dev-app/theme.scss, src/material-experimental/mdc-core/option/_option-theme.scss, src/material-experimental/mdc-form-field/_form-field-sizing.scss, src/material-experimental/mdc-form-field/_form-field-subscript.scss, src/material-experimental/mdc-form-field/_form-field-theme.scss, src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss, src/material-experimental/mdc-form-field/directives/error.ts, src/material-experimental/mdc-form-field/directives/hint.ts, src/material-experimental/mdc-form-field/form-field.html, src/material-experimental/mdc-helpers/_mdc-helpers.scss, src/material-experimental/mdc-menu/_menu-theme.scss, src/material-experimental/mdc-paginator/_paginator-theme.scss, src/material-experimental/mdc-select/_select-theme.scss, src/material-experimental/mdc-typography/_all-typography.scss, src/material/form-field/form-field-animations.ts
This PR contains several change that bring the MDC-based components in line with the spec w.r.t typography.
1. It adds a new typography config generation function that creates a config based on values from MDC itself. This results in changes to some typography levels, most noticeable the `body-1` and `body-2` levels. Since the config is based on MDC's values it contains `rem` measurements rather than `px` measurements that Angular Material as traditionally used. In this PR the new config is used in the dev-app **only for the MDC-based components**. The MDC-based config is currently not compatible with the old components, but it will be made compatible in a followup PR.
2. Switches all the MDC components to read 2018 typography levels if they are available in the config. If they are not …
=> fix(material-experimental/mdc-typography): update mdc components typography to match spec

src/material/schematics/ng-add/setup-project.ts
Fixes a typo in one of the warnings and adds a link with more info.
Fixes #21705.
=> fix(material/schematics): fix typo in warning

src/material-experimental/mdc-select/select.html, src/material-experimental/mdc-select/select.scss, src/material/select/select.html, src/material/select/select.scss
We have some inline elements inside `mat-select` which may collapse if their text bindings are empty. To work around it we replace the content with a blank space. The problem is that VoiceOver seems to read out this text.
These changes fix the issue by keeping the height of the elements using CSS instead.
Fixes #21725.
=> fix(material/select): VoiceOver reading out blank space

src/google-maps/map-ground-overlay/README.md
I was confused at first. The link is correct, the text about the underlying JS class is wrong.
=> Update MapGroundOverlay doc for class reference error

src/cdk/table/sticky-position-listener.ts, src/cdk/table/sticky-styler.ts, src/cdk/table/table.spec.ts, tools/public_api_guard/cdk/table.d.ts
Updates the `StickyUpdate` interface to optionally include the list of HTML elements that were updated. This is necessary to improve the performance of an upcoming PR that enables virtual scroll for tables.
=> feat(cdk/table): add HTML elements to sticky styler state

src/material/expansion/_expansion-mixins.scss, src/material/expansion/_expansion-theme.scss, src/material/expansion/expansion-panel-header.scss
The expansion panel header changes its background color when it receives focus which isn't visible in high contrast mode. These changes add an outline around it which is more visible.
Fixes #21544.
=> fix(material/expansion): add focus indication in high contrast mode

src/google-maps/map-marker-clusterer/map-marker-clusterer.ts, tools/public_api_guard/google-maps/google-maps.d.ts
Cleans up the internals of the `MapMarkerClusterer` to avoid having to declare and subscribe to an observable for every input.
=> refactor(google-maps): clean up clusterer internal setup

src/cdk/a11y/focus-trap/focus-trap.spec.ts, src/cdk/a11y/focus-trap/focus-trap.ts, tools/public_api_guard/cdk/a11y.d.ts
Allows for an optional `FocusOptions` object to be passed into the various focus trap methods.
Fixes #21767.
=> feat(cdk/a11y): allow focus options to be passed in to focus trap

src/cdk/a11y/focus-monitor/focus-monitor.ts, src/cdk/drag-drop/drag-ref.ts, src/cdk/drag-drop/drop-list-ref.ts, src/cdk/platform/features/shadow-dom.ts, src/material/progress-spinner/progress-spinner.spec.ts, tools/public_api_guard/cdk/platform.d.ts
The return type for `_getShadowRoot` is actually a `ShadowRoot`, not a `Node`.
=> fix(cdk/platform): adjust return type for _getShadowRoot

.gitignore, src/dev-app/BUILD.bazel, src/dev-app/google-map/google-map-demo.html, src/dev-app/google-map/google-map-demo.ts, src/dev-app/index.html, src/google-maps/README.md, src/google-maps/google-maps-module.ts, src/google-maps/map-directions-renderer/README.md, src/google-maps/map-directions-renderer/map-directions-renderer.spec.ts, src/google-maps/map-directions-renderer/map-directions-renderer.ts, src/google-maps/map-directions-renderer/map-directions-service.spec.ts, src/google-maps/map-directions-renderer/map-directions-service.ts, src/google-maps/public-api.ts, src/google-maps/testing/fake-google-map-utils.ts, tools/public_api_guard/google-maps/google-maps.d.ts
Add the MapDirectionsService which wraps google.maps.DirectionsService
to calculate routes between two points and the MapDirectionsRenderer
component which allows these routes to be displayed on the Google Map.
=> feat(google-maps): Add MapDirectionsRenderer and MapDirectionsService

src/material-experimental/mdc-list/selection-list.spec.ts, src/material-experimental/mdc-list/selection-list.ts, src/material/list/selection-list.spec.ts, src/material/list/selection-list.ts, tools/public_api_guard/material/list.d.ts
Returns an array of the changed options from the list's `selectAll` and `deselectAll`. This is information we have already so exposing it is trivial and makes some use cases slightly easier.
Fixes #21356.
=> feat(material/list): return selected options from selection list selectAll/deselectAll

src/material-experimental/mdc-tabs/_tabs-theme.scss, src/material/tabs/_tabs-theme.scss
`mat-tab-group` has the ability to theme both the foreground and background. When the background color is different from the default, the strong focus indicator blends into it, making it invisible.
These changes invert the color of the indicator so it stands out.
cc @zelliott
=> fix(material/tabs): strong focus indicator not visible when tab header has a background

src/cdk/table/table-module.ts, src/cdk/table/table.ts, src/components-examples/cdk/table/cdk-table-recycle-rows/cdk-table-recycle-rows-example.css, src/components-examples/cdk/table/cdk-table-recycle-rows/cdk-table-recycle-rows-example.html, src/components-examples/cdk/table/cdk-table-recycle-rows/cdk-table-recycle-rows-example.ts, src/components-examples/cdk/table/index.ts, src/components-examples/material/table/index.ts, src/components-examples/material/table/table-recycle-rows/table-recycle-rows-example.css, src/components-examples/material/table/table-recycle-rows/table-recycle-rows-example.html, src/components-examples/material/table/table-recycle-rows/table-recycle-rows-example.ts, src/dev-app/table/table-demo.html, src/material-experimental/mdc-table/module.ts, src/material-experimental/mdc-table/table.ts, src/material/table/table-module.ts, src/material/table/table.ts, tools/public_api_guard/cdk/table.d.ts, tools/public_api_guard/material/table.d.ts
The CDK and Material tables use the dispose view repeater strategy, which creates new rows from scratch when the dataset changes. This PR adds directives that enable the recycle view repeater, which caches disposed rows and reuses them when the dataset changes. This strategy reduces rendering latency for most tables, but may not be compatible with tables that animate rows.
=> feat(cdk/table) add directive to enable recycle view repeater

src/dev-app/mdc-button/mdc-button-demo.html, src/material-experimental/mdc-button/button.spec.ts, src/material-experimental/mdc-button/fab.scss, src/material-experimental/mdc-button/fab.ts, src/material-experimental/mdc-button/module.ts
Add extended FAB to align with MDC https://material.io/components/buttons-floating-action-button#extended-fab
=> feat(material-experimental/mdc-button): add extended fab

guides/creating-a-custom-form-field-control.md
- without this, it's black on dark grey
This knocks 2 points off of the LH a11y audit for the guide.
=> docs: fix input text color to match theme in custom form guide

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/drag-ref.ts
In #21382 the `preventDefault` call was moved further down so it doesn't prevent events until the dragging threshold has been reached. The problem is that it'll only start calling `preventDefault` from the first event __after__ the threshold has been reached which can be enough time for the device to start scrolling.
These changes add an extra call as soon as dragging has been considered as "started".
Fixes #21749.
=> fix(cdk/drag-drop): not blocking initial move event

src/material-experimental/mdc-menu/menu.spec.ts, src/material/menu/menu-trigger.ts, src/material/menu/menu.spec.ts
We move focus inside the menu after we've dispatched the `menuOpened` event which means that we'll override any focus that the consumer may have set inside the handler. These changes fix the issue by changing the order.
Fixes #20965.
=> fix(material/menu): unable to move focus from inside opened event

src/material-experimental/mdc-tabs/_tabs-theme.scss
Fixes that the MDC-based `mat-tab-nav-bar` doesn't support a `backgroundColor`. This is something we support on the non-MDC version, but it didn't make it into the MDC one for some reason.
=> fix(material-experimental/mdc-tabs): support backgroundColor on nav bar

scripts/check-mdc-exports-config.ts, src/material-experimental/mdc-slide-toggle/testing/BUILD.bazel, src/material-experimental/mdc-slide-toggle/testing/slide-toggle-harness.ts, src/material/slide-toggle/testing/slide-toggle-harness.ts, tools/public_api_guard/material/slide-toggle/testing.d.ts
De-duplicate the test harness logic between the MDC and non-MDC harnesses.
=> refactor(material-experimental/mdc-slide-toggle): de-duplicate test harness logic

guides/bidirectionality.md, guides/creating-a-custom-form-field-control.md, guides/creating-a-custom-stepper-using-the-cdk-stepper.md, guides/customizing-component-styles.md, guides/duplicate-theming-styles.md, guides/elevation.md, guides/getting-started.md, guides/schematics.md, guides/theming-your-components.md, guides/theming.md, guides/typography.md, guides/using-component-harnesses.md, guides/v9-hammerjs-migration.md, tools/markdown-to-html/docs-marked-renderer.ts
- Lighthouse's a11y audit wants page headers to progress in order
- https://web.dev/heading-order/
- Go through all guides and make the headers consistent
- and ordered to pass the a11y audit
- fix grammar issues and typos
=> docs: create anchors for all header elems & fix a11y in guides

src/dev-app/dev-app/dev-app-layout.html, src/dev-app/dev-app/dev-app-layout.scss
Makes the following quality of life improvements to the dev app:
* Removes the horizontal scrolling on smaller screens which is caused by all the buttons in the toolbar.
* Removes some extra spacing at the top of the page on IE.
=> build: a couple of minor improvements to the dev app

goldens/ts-circular-deps.json, src/cdk/testing/private/e2e/actions.ts, src/cdk/testing/private/e2e/asserts.ts, src/cdk/testing/private/e2e/query.ts
Moves an interface in order to resolve a circular dependency.
=> build: resolve circular dependencies in e2e code

src/material-experimental/mdc-menu/menu.scss, src/material/menu/menu.scss
Fixes https://github.com/angular/components/issues/21182
=> fix(material/menu): prevent mat-menu from affecting flex layout

src/components-examples/material/stepper/index.ts, src/components-examples/material/stepper/stepper-lazy-content/stepper-lazy-content-example.css, src/components-examples/material/stepper/stepper-lazy-content/stepper-lazy-content-example.html, src/components-examples/material/stepper/stepper-lazy-content/stepper-lazy-content-example.ts, src/material/stepper/public-api.ts, src/material/stepper/step-content.ts, src/material/stepper/step.html, src/material/stepper/stepper-module.ts, src/material/stepper/stepper.md, src/material/stepper/stepper.spec.ts, src/material/stepper/stepper.ts, tools/public_api_guard/material/stepper.d.ts
Adds the `matStepContent` directive that allows consumers to defer rendering the content of a step until it is opened for the first time.
Fixes #12339.
=> feat(material/stepper): allow for content to be rendered lazily

package.json, src/dev-app/google-map/google-map-demo.html, src/dev-app/google-map/google-map-demo.ts, src/dev-app/index.html, src/google-maps/README.md, src/google-maps/google-maps-module.ts, src/google-maps/map-heatmap-layer/README.md, src/google-maps/map-heatmap-layer/map-heatmap-layer.spec.ts, src/google-maps/map-heatmap-layer/map-heatmap-layer.ts, src/google-maps/package.json, src/google-maps/public-api.ts, src/google-maps/testing/fake-google-map-utils.ts, src/universal-app/kitchen-sink/kitchen-sink.html, tools/public_api_guard/google-maps/google-maps.d.ts, yarn.lock
Adds support for rendering heatmaps on the `google-map` component using the `map-heatmap-layer` directive. The directive is mostly a direct wrapper around the `google.maps.visualization.HeatmapLayer` class, except for the fact that it also accepts a `LatLngLiteral`, whereas the Google Maps class only accepts `LatLng` objects. I decided to add some logic to convert them automatically, because creating `LatLng` requires the Maps API to have been loaded which can lead to race conditions if it's being loaded lazily.
=> feat(google-maps): add heatmap support

src/cdk/testing/test-element.ts, src/cdk/testing/tests/cross-environment.spec.ts, src/material/datepicker/testing/datepicker-input-harness-base.ts, src/material/input/testing/input-harness.ts, src/material/input/testing/native-select-harness.ts, tools/public_api_guard/cdk/testing.d.ts
Changes the APIs that were marked as deprecated for v12.0.0.
* `TestElement.rightClick` is now a required method.
* `TestElement.setInputValue` is now a required method.
* `TestElement.selectOptions` is now a required method.
* `TestElement.dispatchEvent` is now a required method.
=> refactor(cdk/testing): change deprecated APIs for v12

src/material/select/select.spec.ts, src/material/select/select.ts
Fixes `mat-select` not marking all of the options as selected, when an array with duplicate values is assigned programmatically.
Fixes #13179.
=> fix(select): not marking options as selected correctly when setting value with duplicates

src/material/tabs/tab-group.html, src/material/tabs/tab-group.spec.ts, src/material/tabs/tab-group.ts, tools/public_api_guard/material/tabs.d.ts
Fixes the `focusChange` output not emitting when the user tabs into a tab header which is different from the previously-focused one.
Fixes #14142.
=> fix(tabs): focusChange not being emitted when tabbing into a tab header

src/material/tabs/tab-body.html, src/material/tabs/tab-body.spec.ts
Since the tab body content can be scrollable and consumers don't have access to the DOM element, we have to mark it as a CdkScrollable in order to allow for overlays inside the tabs to reposition.
Fixes #8405.
This is a resubmit of #8962 which was getting very stale.
=> fix(tabs): mark tab body as a scrollable container

src/cdk/stepper/stepper.ts, src/material/stepper/stepper.spec.ts
Fixes the last step in the stepper never being marked as `interacted`. Also fixes some weird logic where we were changing the step state inside `_anyControlsInvalidOrPending` which is a getter method.
Fixes #17974.
=> fix(material/stepper): last step not being marked as interacted

src/google-maps/google-map/google-map.ts, tools/public_api_guard/google-maps/google-maps.d.ts
Reworks the internal setup of the `google-map` component so that we don't have to declare observables for each input.
=> refactor(google-maps): clean up internal setup

src/material/tooltip/testing/BUILD.bazel, src/material/tooltip/testing/shared.spec.ts, src/material/tooltip/testing/tooltip-harness.ts
`MatTooltip` binds either a mouse or a touch event, depending on whether it's on a touch device or not. In the harnesses we were limited to dispatching only mouse events which meant that tests couldn't be run against touch devices.
Now that we can fake any sort of event, we're able to support touch devices too.
=> fix(material/tooltip): handle touch devices in test harness

src/material/form-field/form-field-input.scss
It's common for apps to set `box-sizing: border-box` on all elements in the app which ends up causing unnecessary scroll bars on auto-resizing textareas. These changes explicitly set `box-sizing: content-box` to fix it.
Note that ideally we'd do this at the `cdk/text-field` level since it is the one responsible for resizing the textarea, but we generally try to avoid changing the user's layout through the CDK.
Fixes #21560.
=> fix(material/input): uncessary scroll bar on auto-resize textarea in some cases

src/material/datepicker/BUILD.bazel, src/material/datepicker/datepicker-base.ts, src/material/datepicker/datepicker.spec.ts
Our focus restoration works by checking `document.activeElement` before the panel is opened and restoring to that element on close. The problem is that `activeElement` will return the shadow root, if the focused element is inside one.
These changes add some extra logic to account for it.
Fixes #21785.
=> fix(material/datepicker): focus restoration not working inside shadow dom

src/material/form-field/form-field-standard.scss
There was a syntax error which prevented the focus indication from rendering in high contrast mode.
Fixes #21780.
=> fix(material/form-field): focus indication not working for standard appearance in high contrast mode

.gitignore, src/dev-app/BUILD.bazel, src/dev-app/index.html, tools/dev-server/dev-server.ts
Currently we have a one-off way of passing the Google Maps API key to the dev app. These changes rework the approach so that we have a single `variables.json` file which can be used for the Google Maps key, as well as any other variables in the future.
=> build: set up generic way of passing in environment variables to dev app

src/material-experimental/mdc-select/select.spec.ts, src/material-experimental/mdc-tabs/tab-body.html, src/material-experimental/mdc-tabs/tab-body.spec.ts, src/material-experimental/mdc-tabs/tab-group.html, src/material-experimental/mdc-tabs/tab-group.spec.ts, src/material/tabs/tab-group.spec.ts
Fixes some CI issues which were caused by older PRs being merged. The PRs were opened before we had the extra checks for MDC.
=> build: fix test failures and add missing tests

src/material-experimental/mdc-select/select.spec.ts, src/material/select/select.spec.ts, src/material/select/select.ts
`mat-select` has an internal check that doesn't re-assign a value if the reference is the same. This was meant primarily for primitives, but it ends up breaking the behavior for a multi-select where the value is always an array.
These changes skip the check for a multi-select receiving a new array value.
Fixes #21583.
=> fix(material/select): value not updated if the same array is updated and re-assigned

src/material-experimental/mdc-input/input.spec.ts, src/material-experimental/mdc-input/input.ts, src/material/input/input.spec.ts, src/material/input/input.ts
Only sets `aria-invalid` on a `MatInput` if it is invalid and it has a value, otherwise it'll likely overlap with `aria-required` and cause more noise for users. Furthermore, it may be confusing if the user lands on an input that they haven't interacted with, but it's already invalid.
Fixes #18140.
=> fix(material/input): only set as aria-invalid if the input isn't empty

src/material-experimental/mdc-tooltip/tooltip.spec.ts, src/material/tooltip/tooltip.md, src/material/tooltip/tooltip.spec.ts, src/material/tooltip/tooltip.ts
Adds a class on the tooltip overlay element that indicates the current position of the tooltip. This allows for the it to be customized to add position-based arrows or box shadows.
Fixes #15216.
=> feat(material/tooltip): add class to tooltip element based on the current position

src/material-experimental/mdc-tooltip/tooltip.spec.ts, src/material/tooltip/tooltip.spec.ts, src/material/tooltip/tooltip.ts, tools/public_api_guard/material/tooltip.d.ts
Currently we fire off some timers when a tooltip is shown or hidden, however if it gets destroyed before the timer has elapsed, we still end up executing some logic (change detection in this case). These changes clear the timers so that we don't end up triggering errors by accident.
=> fix(material/tooltip): clear pending timers on destroy

src/cdk/drag-drop/directives/drag.ts
Fixes a memory leak in `CdkDrag` which prevented it from being cleaned up. The problem is that we keep track of all the instances in an array, but there was a typo in the cleanup logic which meant that the items would never be removed from the array.
Fixes #21818.
=> fix(cdk/drag-drop): destroyed items not being cleaned up correctly

scripts/check-mdc-exports-config.ts, src/material-experimental/config.bzl, src/material-experimental/mdc-tooltip/testing/BUILD.bazel, src/material-experimental/mdc-tooltip/testing/index.ts, src/material-experimental/mdc-tooltip/testing/public-api.ts, src/material-experimental/mdc-tooltip/testing/tooltip-harness.spec.ts, src/material-experimental/mdc-tooltip/testing/tooltip-harness.ts, src/material/tooltip/testing/tooltip-harness.ts, tools/public_api_guard/material/tooltip/testing.d.ts
Sets up a test harness for the MDC-based tooltip.
=> feat(material-experimental/mdc-tooltip): add test harness

src/cdk/drag-drop/directives/config.ts, src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/directives/drag.ts, src/cdk/drag-drop/drag-drop.md, src/cdk/drag-drop/drag-ref.ts, src/cdk/drag-drop/public-api.ts, src/dev-app/drag-drop/drag-drop-demo.scss, tools/public_api_guard/cdk/drag-drop.d.ts
Currently we always insert the drag preview at the `body`, because it allows us to avoid dealing with `overflow` and `z-index`. The problem is that it doesn't allow the preview to retain its inherited styles.
These changes add a new input which allows the consumer to configure the place into which the preview will be inserted.
Fixes #13288.
=> feat(cdk/drag-drop): allow for preview container to be customized

src/google-maps/README.md, src/google-maps/map-geocoder/README.md, src/google-maps/map-geocoder/map-geocoder.spec.ts, src/google-maps/map-geocoder/map-geocoder.ts, src/google-maps/public-api.ts, src/google-maps/testing/fake-google-map-utils.ts, tools/public_api_guard/google-maps/google-maps.d.ts
Adds a wrapper around the Google Maps Geocoder API. Also exports `MapDirectionsResponse` which wasn't exposed in a previous PR.
Fixes #21665.
=> feat(google-maps): add geocoder wrapper

src/material/stepper/stepper-animations.ts
The CSS `visibility` allows for a child element to become visible, even though its parent is hidden. This becomes a problem for an expanded stepper inside a collapsed sidenav, because it allows the user to tab into the stepper.
These changes resolve the issue by transitioning to `visibility: ''` which allows it to be inherited.
Fixes #21831.
=> fix(material/stepper): don't allow focus inside a hidden element

src/material/datepicker/datepicker-toggle.html, src/material/datepicker/datepicker-toggle.ts
Currently the datepicker toggle's `click` listener is on the inner `button` element and we call `stopPropagation` on it in order to prevent the form field from focusing the input. The problem is that doing so will also prevent any custom `click` handler that the user might have added to the `mat-datepicker-toggle`.
These changes resolve the issue by moving the listener directly onto the toggle host which will invoke any external listeners while still allowing us to stop its propagation.
Fixes #21836.
=> fix(material/datepicker): avoid interfering with external click listener

src/google-maps/map-marker-clusterer/map-marker-clusterer.spec.ts, src/google-maps/map-marker-clusterer/map-marker-clusterer.ts, src/google-maps/map-marker-clusterer/marker-clusterer-types.ts, src/google-maps/testing/fake-google-map-utils.ts, tools/public_api_guard/google-maps/google-maps.d.ts
Adds support for an `options` input to the marker clusterer, similar to the other Google Maps directives.
Fixes #21763.
=> feat(google-maps): support options object on marker clusterer

guides/theming.md, guides/typography.md, src/material-experimental/README.md
also recommend the mdc typography for the mdc components
=> docs(material/core): show typography as part of the theme

src/material/core/theming/_theming.scss
fixes the comments by updating color-map with palette in material theming
fixes angular#21803
=> fix(material/theming): change to update comments in theming

src/material/table/table.md
docs(table): additional details on table data sources
Provides additional documentation and clarification on extending the base DataSource class with custom data sources either by extending or implementing.
Fixes #21887
=> docs(material/table): additional details on table data sources

guides/creating-a-custom-form-field-control.md
`FocusMonitor`'s `monitor`/`stopMonitoring` methods accept `ElementRef<HTMLElement>` as parameter.
So there's no need to call `ElementRef.nativeElement`
https://material.angular.io/cdk/a11y/api#FocusMonitor
=> docs: pass ElementRef<HTMLElement> as is into FocusMonitor methods

guides/creating-a-custom-form-field-control.md
`this` should implement `ControlValueAccessor` because
`valueAccessor` has type `ControlValueAccessor | null`
in the `this.ngControl.valueAccessor = this;` (line 216)
Affected URL: https://material.angular.io/guide/creating-a-custom-form-field-control#ngcontrol
=> docs: implement ControlValueAccessor in the code snippet

src/material-experimental/mdc-helpers/_mdc-helpers.scss
with null value
This fixes an issue with MDC emitting CSS variables with no fallback value.
=> fix(material-experimental/mdc-typography): strip typography properties

src/cdk/schematics/ng-update/data/constructor-checks.ts, src/cdk/table/sticky-styler.ts, src/cdk/table/table.ts, src/material-experimental/mdc-table/table.ts, src/material/table/table.ts, tools/public_api_guard/cdk/table.d.ts
Changes the APIs that were marked as deprecated for v12.
* `_viewRepeater`, `_coalescedStyleScheduler` and `_viewportRuler` parameters of the `CdkTable` constructor are now required.
* `_coalescedStyleScheduler` parameter of the `StickyStyler` constructor is now required.
=> refactor(cdk/table): change deprecated APIs for v12

src/material-experimental/mdc-tooltip/tooltip.ts, src/material/schematics/ng-update/data/constructor-checks.ts, src/material/tooltip/tooltip.ts, tools/public_api_guard/material/tooltip.d.ts
Changes the APIs that were marked as deprecated for v12.
* The `_document` parameter of the `MatTooltip` constructor is now required.
=> refactor(material/tooltip): change deprecated APIs for v12

src/google-maps/google-map/google-map.spec.ts, src/google-maps/google-map/google-map.ts
Fixes a regression where the `mapTypeId` from the `options` object wasn't being preserved when combining the options with the input values.
Fixes #21903.
**Note:** setting as a P2, because it's a regression.
=> fix(google-maps): mapTypeId not being set from options

src/material-experimental/mdc-core/option/optgroup.html, src/material-experimental/mdc-select/select.spec.ts, src/material/core/option/optgroup.html, src/material/select/select.spec.ts
Fixed by adding aria-hidden="true" to the <label> elements, so that while screenreaders will still announce the label text for the group (due to the aria-labelledby property on mat-optgroup), they will skip over the actual label element. Additionally, changed the label to a span to make it clear that the text is visual only and not carrying any special semantic meaning for the a11y tree.
Fixes #21857
=> fix(material/core): mat-optgroup labels are read twice during screen-reader page navigation

CODING_STANDARDS.md, src/cdk/overlay/BUILD.bazel, src/cdk/overlay/_overlay.scss
The backdrop styles were never switches to the `cdk-high-contrast` mixin which means that they won't work on Firefox. These changes switch to using the mixin and update the docs.
Fixes #21890.
=> fix(cdk/overlay): not setting correct opacity in high contrast mode on Firefox

src/material-experimental/mdc-paginator/BUILD.bazel, src/material-experimental/mdc-paginator/paginator-module.ts, src/material-experimental/mdc-paginator/testing/BUILD.bazel, src/material-experimental/mdc-table/BUILD.bazel
Switches the MDC-based paginator to use the MDC tooltip.
=> fix(material-experimental/mdc-paginator): use MDC-based tooltip

scripts/check-mdc-exports-config.ts, src/material-experimental/mdc-form-field/testing/form-field-harness.ts, src/material/form-field/testing/form-field-harness.ts, tools/public_api_guard/material/form-field/testing.d.ts
De-duplicates the test harness logic between the MDC and non-MDC implementations.
=> refactor(material-experimental/mdc-form-field): de-duplicate test harness logic

src/material-experimental/mdc-button/button.scss
Add appropriate class to mat-icon when it is within a MDC button to receive the correct styles.
(This is technically a fix for material-experimental/mdc-button but the change is in material/icon)
Before
After
=> fix(material-experimental/mdc-button): use mdc mixins to style icons within buttons

package.json, src/material-experimental/mdc-autocomplete/_autocomplete-theme.scss, src/material-experimental/mdc-autocomplete/autocomplete.scss, src/material-experimental/mdc-core/option/_optgroup-theme.scss, src/material-experimental/mdc-core/option/_option-theme.scss, src/material-experimental/mdc-core/option/optgroup.scss, src/material-experimental/mdc-core/option/option.scss, src/material-experimental/mdc-list/_list-option-theme.scss, src/material-experimental/mdc-list/_list-theme.scss, src/material-experimental/mdc-list/list.scss, src/material-experimental/mdc-menu/_menu-theme.scss, src/material-experimental/mdc-menu/menu.scss, src/material-experimental/mdc-select/_select-theme.scss, src/material-experimental/mdc-select/select.scss, yarn.lock
CARETAKER NOTE: This PR corresponds to cl/358197074 - it should be merged once the CL is submitted
=> fix(material-experimental/mdc-list): update mixin and variable names after MDC's deprecation

src/dev-app/mdc-slider/mdc-slider-demo.html, src/material-experimental/mdc-slider/_slider-theme.scss, src/material-experimental/mdc-slider/slider.scss, src/material-experimental/mdc-slider/slider.ts
* implement _MatSliderMixinBase
* add color input to MatSlider
* extend _MatSliderMixinBase from MatSlider
* use without-ripple mixin for slider.scss
* @include all other mdc-slider mixins except thumb-ripple-color in _slider-theme.scss
* implement primary, accent, and warn colors in _slider-theme.scss
=> feat(material-experimental/mdc-slider): add slider styles

.circleci/config.yml
The mdc_snapshot_test_cronjob needs to yarn install to ensure
that the bazel binary is available before attempting to reference it.
=> build: update mdc_snapshot_test_cronjob to yarn install before bazel setup

src/material/select/select.ts
The fallback seems to have been removed with #20082
=> docs(material/select): remove placeholder fallback from aria-label docs

src/material/select/select.spec.ts
Without fixing the class name, the assertion would be useless
=> test(material/select): fix form field class name in assertion

src/material-experimental/mdc-select/select.spec.ts, src/material/select/select.spec.ts
The existing test would not work without using mat-form-field wrapper because the trigger.click() propagates to onContainerClick of FormField which calls select.open() a second time.
With this change, the logic does not base on propagating/onContainerClick but on specific open and close commands of the panel.
=> test(material/select): remove form-field dependency in deselection test

src/material-experimental/mdc-select/select.spec.ts, src/material/select/select.spec.ts
The existing test would not work without using mat-form-field wrapper
because when the click() method in the trigger is called, the event
propagates to onContainerClick of FormField which calls focus() of select.
With this addition, the logic does not base on propagating/onContainerClick
but on a specific focus instruction.
=> test(material/select): remove form-field dependency in focus test

src/cdk/clipboard/copy-to-clipboard.ts, tools/public_api_guard/cdk/clipboard.d.ts
There was a typo in the name of the `CDK_COPY_TO_CLIPBOARD_CONFIG` token.
Fixes #21976.
=> fix(cdk/clipboard): typo in injection token name

src/material/bottom-sheet/BUILD.bazel, src/material/bottom-sheet/bottom-sheet-container.ts, src/material/bottom-sheet/bottom-sheet.spec.ts
Related to #21796. The bottom sheet focus restoration works by grabbing `document.activeElement` before the sheet is opened and restoring focus to the element on destroy. This won't work if the element is inside the shadow DOM, because the browser will return the shadow root. These changes add a workaround.
=> fix(material/bottom-sheet): focus restoration not working inside shadow dom

src/material/datepicker/date-selection-model.ts, src/material/datepicker/datepicker-base.ts, src/material/schematics/ng-update/data/constructor-checks.ts, tools/public_api_guard/material/datepicker.d.ts
Changes the APIs that were marked as deprecated for v12.
* `MatDateSelectionModel.clone` is now a required abstract method.
* The `intl` parameter of the `MatDatepickerContent` constructor is now required.
=> refactor(material/datepicker): remove deprecated APIs for v12

src/cdk/stepper/stepper.ts, src/material/stepper/BUILD.bazel, src/material/stepper/stepper.spec.ts, src/material/stepper/stepper.ts, tools/public_api_guard/cdk/stepper.d.ts, tools/public_api_guard/material/stepper.d.ts
Currently we have a limitation on the Material stepper that doesn't allow its orientation to be changed dynamically, because we have two different components for it.
The CDK stepper doesn't have this limitation and people may end up extending it to implement their own steppers which support changing orientations.
These changes add some logic to ensure that changing the orientation works as expected and to ensure that the orientation of the Material stepper doesn't change.
Fixes #21874.
=> feat(cdk/stepper): allow for orientation to be changed

src/cdk/table/sticky-position-listener.ts, src/cdk/table/sticky-styler.ts, src/cdk/table/table.spec.ts, tools/public_api_guard/cdk/table.d.ts
Adds the offsets of sticky elements to the `StickyUpdate` interface. This change is necessary for the virtual scroll table to compute the relative position of sticky header/footers (https://github.com/angular/components/pull/21708).
=> feat(cdk/table): add element offsets to sticky styler state

src/material-experimental/mdc-slider/BUILD.bazel, src/material-experimental/mdc-slider/_slider-theme.scss, src/material-experimental/mdc-slider/module.ts, src/material-experimental/mdc-slider/slider-thumb.html, src/material-experimental/mdc-slider/slider-thumb.scss, src/material-experimental/mdc-slider/slider.html, src/material-experimental/mdc-slider/slider.scss, src/material-experimental/mdc-slider/slider.ts
=> feat(material-experimental/mdc-slider): implement slider thumb ripples

src/cdk/portal/portal.md, src/material/bottom-sheet/bottom-sheet.md, src/material/dialog/dialog.md
https://angular.io/guide/deprecations#entrycomponents-and-analyze_for_entry_components-no-longer-required
=> docs: mention `entryComponents` is no longer necessary

src/google-maps/map-directions-renderer/README.md
MapDirectionsService should be imported to be injected in the constructor
=> docs: missing import in map-directions-render

src/material/expansion/_expansion-theme.scss, tools/stylelint/theme-mixin-api.ts
Reworks the `theme-mixin-api` lint rule to account for the Sass module changes.
=> build: fix theming api lint rule

src/material-experimental/mdc-button/button-base.ts, src/material-experimental/mdc-button/button.html, src/material-experimental/mdc-button/fab.ts
MDC button and MDC FAB are 2 different components but MDC based button and FAB share the same template. 
Add `mdc-fab__ripple` to the mdc-button ripple element to receive MDC's FAB ripple styles.
=> fix(material-experimental/mdc-button): add mdc ripple class for fab

src/dev-app/mdc-card/mdc-card-demo.html, src/dev-app/mdc-card/mdc-card-demo.ts, src/material-experimental/mdc-card/card.ts
Add appearance input to support outline variant of card
Fixes https://github.com/angular/components/issues/21548
=> feat(material-experimental/mdc-card): add appearance input

src/material/datepicker/date-selection-model.ts, tools/public_api_guard/material/datepicker.d.ts
* Hides some symbols related to the date selection model from the public API docs.
* Fixes that `MatDateSelectionModel` was marked as a directive, rather than an injectable.
Fixes #21985.
=> fix(material/datepicker): hide date selection model from docs

src/cdk/accordion/accordion.spec.ts, src/cdk/accordion/accordion.ts
Currently `CdkAccordion.closeAll` only works if `multi` is set to false, however it makes sense when a single item is expanded as well.
These changes also fix that `_openCloseAllActions` wasn't being completed and they include more unit tests.
Fixes #22003.
=> fix(cdk/accordion): allow for closeAll to be used when multiple mode is disabled

src/material-experimental/mdc-autocomplete/public-api.ts, src/material/autocomplete/autocomplete-trigger.ts, tools/public_api_guard/material/autocomplete.d.ts
Removes the APIs that were marked for removal in v12.
* `AUTOCOMPLETE_OPTION_HEIGHT` has been removed.
* `AUTOCOMPLETE_PANEL_HEIGHT` has been removed.
=> refactor(material/autocomplete): remove deprecated APIs for v12

src/material-experimental/mdc-slide-toggle/slide-toggle-config.ts, src/material-experimental/mdc-slide-toggle/slide-toggle.spec.ts, src/material-experimental/mdc-slide-toggle/slide-toggle.ts, src/material/slide-toggle/slide-toggle-config.ts, src/material/slide-toggle/slide-toggle.spec.ts, src/material/slide-toggle/slide-toggle.ts, tools/public_api_guard/material/slide-toggle.d.ts
Allows for the `color` of a slide toggle to be configured through a provider.
Fixes #22012.
=> feat(material/slide-toggle): allow for default color to be configured globally

src/dev-app/mdc-button/mdc-button-demo.html, src/material-experimental/mdc-button/_button-base.scss, src/material-experimental/mdc-button/_button-theme.scss, src/material-experimental/mdc-button/fab.ts
Make sure to target the right ripple/state target now that the `mdc-button__ripple`/`mdc-fab__ripple` class is conditionally applied.
=> fix(material-experimental/mdc-button): apply appropriate focus/actives styles to FAB

src/cdk/a11y/_a11y.scss, src/cdk/overlay/_overlay.scss
Fixes a regression caused by #21896 where importing the overlay styles through `~@angular/cdk/overlay` would result in a compilation error.
=> fix(cdk/overlay): resolve regression when overlay is imported through shorthand path

src/material-experimental/mdc-form-field/form-field.ts, src/material-experimental/mdc-input/input.spec.ts, src/material/input/input.spec.ts
Doesn't appear to be any reason why this was an `else if` - the legacy form field does not do this. Reported internally by Googler
=> fix(material-experimental/mdc-form-field): always check hideRequiredMarker

src/dev-app/mdc-checkbox/mdc-checkbox-demo.html, src/material-experimental/mdc-checkbox/_checkbox-theme.scss, src/material-experimental/mdc-checkbox/checkbox.html, src/material-experimental/mdc-checkbox/checkbox.scss
MDC recently made a change so that the checkbox state styles (hover, focus, active) should be on their ripple element. This adds that ripple element and reconciles the styles between it and our existing MatRipple element.
=> fix(material-experimental/mdc-checkbox): remove background state styles

src/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template, src/material/schematics/ng-generate/address-form/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template, src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__-datasource.ts.template, src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html.template, src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template, src/material/schematics/ng-generate/tree/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
- fix `strictNullChecks` errors
- fix `strictPropertyInitialization` errors
- default to smaller paginator rows so that paging works out of the box
- fix tslint errors from default CLI settings
Fixes #21981
=> fix(material/schematics): generate code that works in strict CLI projects

src/components-examples/material/table/table-http/table-http-example.css, src/components-examples/material/table/table-http/table-http-example.html, src/components-examples/material/table/table-http/table-http-example.ts
- remove usages of `subscribe()`
- fix jank and spinner covering table headers
Related to a [GDE Slack question](https://angular-team.slack.com/archives/C08M4JKNH/p1611360900019500) about teaching "using the "declarative" approach to RxJS. That means no subscribing in the component".
=> docs(material/table): use declarative idiomatic RxJS in table-http-example

src/material-experimental/mdc-chips/chip-grid.spec.ts, src/material-experimental/mdc-form-field/directives/error.ts, src/material-experimental/mdc-input/input.spec.ts, src/material/chips/chip-list.spec.ts, src/material/form-field/error.ts, src/material/input/input.spec.ts, tools/public_api_guard/material/form-field.d.ts
Make the "politeness" of mat-error "polite" by default (instead of "assertive") and also make this configurable via an input binding.
Fixes #21781
=> feat(material/form-field): make mat-errors more polite

src/cdk/schematics/ng-update/data/constructor-checks.ts, src/cdk/stepper/stepper.ts, src/material/schematics/ng-update/data/constructor-checks.ts, src/material/stepper/stepper.ts, tools/public_api_guard/cdk/stepper.d.ts, tools/public_api_guard/material/stepper.d.ts
Removes the APIs that have been marked for removal in v12.
* `MAT_STEPPER_GLOBAL_OPTIONS` has been renamed to `STEPPER_GLOBAL_OPTIONS`.
* The type of `CdkStepper._stepHeader` has been changed to `QueryList<CdkStepHeader>` from `QueryList<FocusableOption>` to better reflect the actual value.
* The value of `CdkStepper.selected` can now be `undefined`.
* The `_elementRef` and `_document` parameters of the `CdkStepper` constructor are now required.
* The `_elementRef` and `_document` parameters of the `MatVerticalStepper` constructor are now
required.
* The `_viewContainerRef` parameter of the `MatStep` constructor is now required.
=> refactor(material/stepper): remove deprecated APIs for v12

src/material-experimental/mdc-autocomplete/animations.ts
Changes the panel animation to only animate vertically, rather than along both x and y axis.
For reference, this is the before:
This is after:
=> fix(material-experimental/mdc-autocomplete): only animate along y axis

src/material-experimental/mdc-dialog/BUILD.bazel, src/material-experimental/mdc-dialog/dialog.spec.ts, src/material/dialog/BUILD.bazel, src/material/dialog/dialog-container.ts, src/material/dialog/dialog.spec.ts
Related to #21796. The dialog focus restoration works by grabbing `document.activeElement` before the dialog is opened and restoring focus to the element on destroy.  This won't work if the element is inside the shadow DOM, because the browser will return the shadow root. These changes add a workaround.
=> fix(material/dialog): focus restoration not working inside shadow dom

src/material-experimental/mdc-progress-bar/progress-bar.ts
Runs the `ResizeObserver` from the progress bar outside of the `NgZone` so that it doesn't trigger change detection.
=> fix(material-experimental/mdc-progress-bar): run resize observer outside zone

src/material-experimental/mdc-tabs/tab-group.spec.ts, src/material/tabs/tab-group.spec.ts, src/material/tabs/tab-group.ts, tools/public_api_guard/material/tabs.d.ts
Adds a method that allows for focus to be moved to a particular tab. This is usually tricky, because all of the DOM elements are hidden away inside the tab group template.
Fixes #15007.
=> feat(material/tabs): add method for programmatically setting focus

src/material-experimental/mdc-snack-bar/BUILD.bazel, src/material-experimental/mdc-snack-bar/_snack-bar-theme.scss, src/material-experimental/mdc-snack-bar/module.ts, src/material-experimental/mdc-snack-bar/snack-bar.spec.ts, src/material-experimental/mdc-snack-bar/testing/BUILD.bazel
Switches the MDC-based snack bar to use the MDC-based button. In general we should be using the MDC versions of components together, when possible.
Fixes #22024.
=> fix(material-experimental/mdc-snack-bar): use MDC-based button

src/material/sort/sort-header.ts, src/material/sort/sort.spec.ts
Fixes the visible state of the sort header not being updated if it gets changed through the `matSortActive` binding.
Fixes #19467.
=> fix(material/sort): view not updated when sort state is changed through binding

src/material/card/card.scss
We have some styles that clear the margin from the first button, but we didn't apply the same to the last button if the card actions are aligned towards the end.
Fixes #20024.
=> fix(material/card): not clearing margin on last button in end alignment

src/material-experimental/mdc-select/select.html, src/material-experimental/mdc-select/select.scss
The MDC select uses a CSS triangle for its down arrow which renders as a rectangle in high contrast mode. These changes switch it to an SVG arrow.
These changes are identical to #14219 which had some trouble landing due to screenshot diffs. The MDC select shouldn't have such issues.
Relates to #21263.
=> fix(material-experimental/mdc-select): arrow not rendering in high contrast mode

src/cdk/a11y/a11y.md, src/cdk/a11y/focus-trap/focus-trap.md
- while the guides were updated to support a wider set of headers,
component docs are still limited to `h3` and `h4` in the TOC
- this fixes a regression to these docs [introduced in v6](https://github.com/angular/components/commit/c407cc8cfd9b99af67d52820d13f5cbcc1739eb3)
Fixes #22133
=> docs(cdk/a11y): fix overview table of contents

src/material-experimental/mdc-chips/chip-icons.ts
Fixes an issue in the `mdc-chip` component where clicking the remove
icon would select the chip before removing it.
=> fix(material-experimental/mdc-chips): click interaction of remove icon

src/material/table/table-data-source.spec.ts, src/material/table/table-data-source.ts
The data source was changed in #21338 so that it unsubscribes while it's disconnected. The problem is that the subscription has a side effect which updates `filteredData` as well.
These changes add some logic so that `filteredData` is updated even if the source is disconnected.
Fixes #21984.
=> fix(material/table): data source filteredData not updating while disconnected

src/material-experimental/mdc-form-field/_form-field-sizing.scss, src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss, src/material-experimental/mdc-form-field/directives/prefix.ts, src/material-experimental/mdc-form-field/directives/suffix.ts, src/material-experimental/mdc-form-field/form-field.html, src/material-experimental/mdc-form-field/form-field.scss, src/material-experimental/mdc-form-field/form-field.ts
Demo: https://mmalerba-demo-1.web.app/mdc-input
Open question: when a mat-icon-button is placed in the prefix/suffix area the padding is wrong. This is because the spec expects the icon-button to take up a 24px square in the layout. However, in reality the button takes up a 48px square because of its touch target. Should we add custom CSS to add some negative margin around icon buttons in this case? In that case it would look right, but if people tried to put an icon-button plus something else in the prefix/suffix it would look broken. (cc @jelbourn)
=> fix(material-experimental/mdc-form-field): fix prefix/suffix padding

src/material/grid-list/grid-list.scss, src/material/grid-list/grid-tile.html
Removes the built-in `figure` element inside the grid tile since it isn't always desirable from an accessibility perspective.
Fixes #21775.
=> fix(material/grid-list): remove internal figure element

src/cdk/testing/testbed/fake-events/dispatch-events.ts, src/cdk/testing/testbed/fake-events/event-objects.ts, src/material-experimental/mdc-slider/BUILD.bazel, src/material-experimental/mdc-slider/slider-thumb.html, src/material-experimental/mdc-slider/slider.spec.ts, src/material-experimental/mdc-slider/slider.ts, src/material-experimental/mdc-theming/_all-theme.scss
* implement unit tests for the standard slider, standard range slider, and for the slider ripple states
* add mdc-slider theme to all-theme
* make MatSliderVisualThumb ripple refs public so their states can be checked & tested
* make MatSlider child component and html element getters default thumbPosition to the end thumb
=> feat(material-experimental/mdc-slider): implement some basic unit tests

src/material/select/select.spec.ts, src/material/select/select.ts
Historically we've only floated the `mat-select` label if a value is selected or the panel is open, because we wouldn't otherwise have anything to show. These changes make it so that we also float it on focus, if there's `placeholder` text that can be shown. This behavior is consistent with `MatInput`.
Fixes #19514.
=> fix(material/select): float label on focus if there's a placeholder

src/dev-app/mdc-select/mdc-select-demo.html
This was leftover from the legacy form-field appearance, which no longer
exists in MDC. Selects don't have a "placeholder" their equivalent would
be a null option
=> docs(dev-app): remove references to mdc-select placeholder

src/cdk-experimental/column-resize/column-resize-notifier.ts, src/cdk/table/cell.ts, src/components-examples/material/tooltip/tooltip-disabled/tooltip-disabled-example.html, src/material-experimental/mdc-autocomplete/autocomplete.scss, src/material/menu/menu.ts
Harmonize the use of the word programmatically like it is in dictionary.
Also see https://en.wiktionary.org/wiki/programatically
=> docs: replace programatically by programmatically

src/material-experimental/mdc-progress-bar/_progress-bar-theme.scss
Addresses #22130 on the MDC-side of things. Need to consider solutions for legacy progress bar
BEFORE:
AFTER:
=> fix(material-experimental/mdc-progress-bar): improve buffer color

src/material-experimental/mdc-checkbox/_checkbox-theme.scss
I think this was missed in https://github.com/angular/components/pull/22045. Marking it `merge safe` as I've already made the change in the internal sync
=> fix(material-experimental/mdc-checkbox): fix mdc function name

src/dev-app/theme.scss, src/material-experimental/mdc-slider/_slider-theme.scss
* remove mdc-slider theme from theme.scss since it is already included in all-theme now
* avoid using deprecated mdc-theme prop-value function in _slider-theme.scss
=> fix(material-experimental/mdc-slider): dedup mdc-slider styles

package.json, src/material-experimental/mdc-core/option/_option-theme.scss, src/material-experimental/mdc-core/option/optgroup.html, src/material-experimental/mdc-core/option/option.html, src/material-experimental/mdc-core/option/option.scss, src/material-experimental/mdc-core/option/option.ts, src/material-experimental/mdc-core/testing/option-harness.ts, src/material-experimental/mdc-list/_interactive-list-theme.scss, src/material-experimental/mdc-list/_list-option-theme.scss, src/material-experimental/mdc-list/_list-theme.scss, src/material-experimental/mdc-list/action-list.ts, src/material-experimental/mdc-list/list-base.ts, src/material-experimental/mdc-list/list-item.html, src/material-experimental/mdc-list/list-option.html, src/material-experimental/mdc-list/list-option.ts, src/material-experimental/mdc-list/list-styling.ts, src/material-experimental/mdc-list/list.scss, src/material-experimental/mdc-list/list.spec.ts, src/material-experimental/mdc-list/list.ts, src/material-experimental/mdc-list/nav-list.ts, src/material-experimental/mdc-list/selection-list.spec.ts, src/material-experimental/mdc-list/selection-list.ts, src/material-experimental/mdc-list/testing/list-item-harness-base.ts, src/material-experimental/mdc-list/testing/selection-list-harness.ts, src/material-experimental/mdc-menu/menu.html, src/material-experimental/mdc-select/select.spec.ts, yarn.lock
caretaker note: merge when corresponding change cl/361202374 is submitted
=> fix(material-experimental/mdc-list): rename mdc-list-* classes

.stylelintrc.json, src/material/core/theming/tests/test-theming-bundle.scss, tools/stylelint/no-import.ts
Adds a custom lint rule that doesn't allow for `@import` to be used.
=> build: add lint rule to prevent @import usage

.circleci/config.yml
We recently had some lint failures slip into the main branch, because they had both commit message failures and other lint failures. The problem was that we sometimes ignore commit message failures since they can be fixed by the caretaker, but if the commit check fails, it prevents the other lint checks from running.
These changes move the commit message check to be last in the `lint` job so that if it fails, we know that everything else is in a mergeable state.
=> build: run commit message check after other lint checks

.ng-dev/config.ts, .ng-dev/merge.ts, .ng-dev/release.ts, scripts/build-packages-dist.js
Configure the release tooling from ng-dev.
=> build: lay foundation for migrating to ng-dev release tooling

src/material/button-toggle/button-toggle.ts
Adds an explicit type to `MatButtonToggleGroup` so that it can show up in the docs. This change is merge safe, because the type is the same as the inferred type that was in place already.
Fixes #22026.
=> docs(material/button-toggle): add missing type on public API

guides/theming.md, tools/package-tools/gulp/build-scss-pipeline.ts
Removes a couple of references to `node-sass` which doesn't support `@use`.
=> docs: remove node-sass references

.github/workflows/lock-closed.yml
Please read https://github.com/angular/dev-infra/pull/82#issuecomment-758198930.
CC @gkalpak
=> fix the warning on lock-closed gh-actions: Warning: Unexpected input(s) 'lock-bot-key'

.github/angular-robot.yml
Enable the `requireReviews` option for the Angular Github robot checks,
requiring reviews to be completed before a passing status is provided.
=> build: require reviews to be completed for all PRs before merging

.ng-dev/commit-message.ts
Similar to https://github.com/angular/angular/pull/41157, removes the limit on commit message lines.
=> build: remove commit message line length limit

tools/defaults.bzl
With Bazel NodeJS rules 3.0.0 the require patching was removed by default,
which was addressed in the upgrade to 3.2.1. However this was missed for
jasmine_node_test, which now silently fails. This PR adds the bazel patch for
the module resolver, which ensures spec files are found.
=> build: fix jasmine_node_test

package.json, tools/package-tools/gulp/build-scss-pipeline.ts, yarn.lock
We no longer use `node-sass`, but we were still installing it, because `gulp-sass` depends upon it. These changes switch to a fork of `gulp-sass` that depends on the Dart version of Sass.
=> build: avoid installing node-sass

src/material-experimental/mdc-progress-bar/progress-bar.html, src/material-experimental/mdc-progress-bar/progress-bar.spec.ts, src/material/progress-bar/progress-bar.html, src/material/progress-bar/progress-bar.spec.ts
ChromeVox couldn't read a progress bar element without `aria-hidden` attributes set on child elements of `mat-progress-bar`.
Fixes #22165.
=> fix(material/progress-bar): Support ChromeVox

src/cdk/a11y/focus-trap/focus-trap.ts, tools/dgeni/templates/macros.html
- fix invalid usage of `@breaking-change`
- update breaking change dgeni template to add 'or later' 
- fix a couple of API doc typos
Relates to #18201. Relates to #22136.
Tooltip: "Will be deleted in vfor 11.0.0 Remove this class."
Verified via `yarn build-docs-content` that it generates this output now:
```html
<div class="docs-api-class-deprecated-marker" title="Will be removed in v11.0.0 or later">
Deprecated
</div>
```
While this fixes the tooltip to render properly. It still states that the `FocusTrap` class will be removed in `v11.0.0`, but that didn't happen and it may not be removed in `v12.0.0` either. Should we update this (to what release?) or leave it as is?
=> fix(cdk/a11y): FocusTrap deprecation docs don't render correctly

src/material-experimental/mdc-autocomplete/autocomplete.spec.ts, src/material/autocomplete/autocomplete-trigger.ts, src/material/autocomplete/autocomplete.spec.ts, src/material/autocomplete/autocomplete.ts, tools/public_api_guard/material/autocomplete.d.ts
* Fixes that we assign `aria-labelledby` even if there is no label.
* Fixes that we don't trim the value of `aria-labelledby` when there is no label, but there is a custom `aria-labelledby`.
Fixes #22256.
=> fix(material/autocomplete): avoid assigning invalid aria-labelledby values

src/cdk/platform/features/scrolling.ts
Fixes an error that can be thrown by the `supportsScrollBehavior` helper if the global `document` variable is stubbed out.
Fixes #22259.
=> fix(cdk/platform): avoid error during server-side rendering if document is stubbed out

src/material-experimental/mdc-select/select.spec.ts, src/material/select/select.spec.ts, src/material/select/select.ts
If the form field doesn't have a label, we can end up with an `aria-labelledby` which has a leading space. This appears to be flagged as invalid by some a11y tools.
Fixes #22192.
=> fix(material/select): trim aria-labelledby

src/material-experimental/mdc-progress-spinner/progress-spinner.html, src/material-experimental/mdc-progress-spinner/progress-spinner.spec.ts, src/material/progress-spinner/progress-spinner.html, src/material/progress-spinner/progress-spinner.spec.ts
Along the same lines as #22166. Marks all the root nodes in the progress spinner as `aria-hidden` in order to work around an issue in ChromeVox.
=> fix(material/progress-spinner): resolve accessibility issue in ChromeVox

src/material-experimental/mdc-button/_button-theme.scss
Icon buttons already have a `color: inherit` which works well for the unthemed case, specifically it helps adapt it to colored backgrounds, e.g. mat-toolbar
=> fix(material-experimental/mdc-button): remove unthemed icon color

scripts/check-mdc-tests-config.ts, src/cdk/text-field/autosize.spec.ts, src/cdk/text-field/autosize.ts, src/material/input/input.spec.ts, tools/public_api_guard/cdk/text-field.d.ts
Fixes a bug with CdkTextareaAutosize where the textarea would not be autosized when using long placeholders
Fixes #22042
=> fix(cdk/text-field): autosize text areas using the placeholder

src/dev-app/screen-type/screen-type-demo.scss, src/material/grid-list/grid-tile.html
Remove `mat-figure` class now that internal references have been removed.
(Follow up to https://github.com/angular/components/pull/21826)
=> fix(material/grid-list): remove mat-figure class

src/google-maps/map-geocoder/map-geocoder.spec.ts, src/google-maps/map-geocoder/map-geocoder.ts
Currently we instantiate the `Geocoder` when the `MapGeocoder` provider is instantiated which may be too early if the Google Maps API is loaded lazily.
These changes switch to creating it only when `geocode` is called.
Fixes #22148.
=> fix(google-maps): instantiate geocoder lazily

src/material-experimental/mdc-radio/radio.scss, src/material/radio/radio.scss
* Adds focus indication in high contrast mode to the non-MDC radio button.
* Makes the focus indication on the MDC radio button more prominent.
=> fix(material/radio): add high contrast focus indication

scripts/check-mdc-tests-config.ts, src/cdk/text-field/autosize.spec.ts, src/cdk/text-field/autosize.ts, src/material/input/input.spec.ts, tools/public_api_guard/cdk/text-field.d.ts
This was merged but had test failures. Reverting - @jermowery can open up the PR again
This reverts commit 476a90b083532add4b1343c83e6bf4d105094050.
=> Revert "fix(cdk/text-field): autosize text areas using the placeholder

.stylelintrc.json, src/dev-app/virtual-scroll/virtual-scroll-demo.scss, src/material-experimental/mdc-button/fab.scss, src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss, src/material-experimental/mdc-helpers/_focus-indicators-theme.scss, src/material-experimental/mdc-helpers/_mdc-helpers.scss, src/material/autocomplete/autocomplete.scss, src/material/core/focus-indicators/_focus-indicators-theme.scss, src/material/core/ripple/_ripple-theme.scss, src/material/core/style/_menu-common.scss, src/material/core/style/_vendor-prefixes.scss, src/material/core/typography/_typography.scss, src/material/expansion/expansion-panel-header.scss, src/material/progress-spinner/progress-spinner.scss, src/material/slide-toggle/slide-toggle.scss, src/material/snack-bar/snack-bar-container.scss, src/material/table/_table-flex-styles.scss, src/material/table/table.scss, src/material/toolbar/toolbar.scss, tools/stylelint/single-line-comment-only.ts
Adds a custom stylelint rule that will prevent multi-line comments (`/* */`) from being used in .scss files. The problem with such comments is that they are preserved by Sass and will show up in the user's output, whereas single-line comments (`//`) will not.
**Note:** while Stylelint has a `comment-pattern` rule already, we can't use it because the rule works on the comment text which doesn't include the syntax.
=> build: enforce that we use comments that won't show up in the generated output

src/material/slider/slider.scss
* added color-adjust to mat-slider-wrapper to display slider correctly while printing
=> feat(slider): show background-color in print stylesheet (#11364)

src/material/stepper/stepper-animations.ts
Setting empty string for visibility is an invalid css property value.
Which leads to error "Failed to execute 'animate' on 'Element' : Partial keyframes are not supported" in old browser.
=> fix(material/stepper): setting invalid value for visibility

src/material-experimental/mdc-form-field/form-field.ts
Boolean input should be set to true with `<mat-form-field hideRequiredMarker>`
Also changed constructor logic to match original form field
=> fix(material-experimental/mdc-form-field): use coercion for boolean input

scripts/check-mdc-tests-config.ts, src/material-experimental/mdc-select/select.spec.ts, src/material-experimental/mdc-select/select.ts
This is the equivalent of #19517 for the MDC-based select.
Historically we've only floated the `mat-select` label if a value is selected or the panel is open, because we wouldn't otherwise have anything to show. These changes make it so that we also float it on focus, if there's `placeholder` text that can be shown. This behavior is consistent with `MatInput`.
=> fix(material-experimental/mdc-select): float label on focus if there's a placeholder

src/google-maps/map-directions-renderer/map-directions-service.spec.ts, src/google-maps/map-directions-renderer/map-directions-service.ts
Similar to #22159. Only initializes the Google Maps `DirectivesService` when calling `route`, because doing so in the constructor might be too early.
=> fix(google-maps): initialize directions service lazily

guides/getting-started.md, guides/theming.md
This change completely rewrites the theming guide to be more complete, correct, and concise.
Summary of changes:
* Explain the concepts of palettes, hues, and themes.
* Ensure all content is conceptual and not task-based.
* Use the new Sass `@use` API introduced in #22173
* Document usage of the theming system with shadow dom
* Document the fact that CSS overrides are strongly discouraged
* Be more explicit about which palettes we provide
* Consolidate on a single approach to including theme CSS in an app (assuming Angular CLI)
I will send follow-up PRs for the typography, theming-your-components, and customizing-component-styles guides.
=> docs(material/theming): rewrite theming guide for `@use`

src/google-maps/google-map/google-map.spec.ts, src/google-maps/google-map/google-map.ts
We pass in `mapTypeId` as undefined if the provided options don't have it. This seems to trigger a bug in Google Maps where it stops loading map tiles.
These changes fix the issue by always providing a `mapTypeId`.
Fixes #22082.
=> fix(google-maps): ensure that a mapTypeId is always passed in

src/material-experimental/mdc-menu/menu.spec.ts, src/material/menu/menu-trigger.ts, src/material/menu/menu.spec.ts, tools/public_api_guard/material/menu.d.ts
On document changes the menu may not be located in the correct location anymore. This exposes the `OverlayRef`'s `updatePosition` on the trigger so a user can call it without relying on the private variable `_overlayRef`.
=> feat(material/menu): allow updating menu position a la autocomplete

package.json, yarn.lock
Patch branch is failing to build due to `rollup` update - this does not affect master, perhaps due to other dep updates like Typescript.
=> build: revert rollup to 1.25.0

src/cdk/_index.scss, src/material/schematics/collection.json, src/material/schematics/ng-generate/theming-api/index.spec.ts, src/material/schematics/ng-generate/theming-api/index.ts, src/material/schematics/ng-generate/theming-api/migration.ts, src/material/schematics/ng-generate/theming-api/schema.json, src/material/schematics/ng-generate/theming-api/schema.ts
Adds an `ng-generate` schematic that will switch over existing stylesheets to the new `@use`-based API. Furthermore, the migration code is set up in a way that should allow us to run it in g3 if necessary.
=> feat(material/schematics): add migration to switch to the new theming API

src/material-experimental/mdc-checkbox/checkbox.spec.ts, src/material-experimental/mdc-checkbox/checkbox.ts, src/material/checkbox/checkbox.spec.ts, src/material/checkbox/checkbox.ts
Fixes that the state of the native checkbox might be out of sync if the `checked` property is changed inside the `changed` output.
Fixes #22149.
=> fix(material/checkbox): native input not in sync if checked state is changed inside event

packages.bzl
The required version for MDC was 2 major versions behind the one we're using for development.
Fixes #22320.
=> build: align MDC version requirement

src/dev-app/BUILD.bazel, src/dev-app/theme.scss, src/e2e-app/BUILD.bazel, src/e2e-app/theme.scss, src/material-experimental/BUILD.bazel, src/material-experimental/_index.scss, src/material-experimental/column-resize/_column-resize-theme.scss, src/material-experimental/column-resize/_column-resize.import.scss, src/material-experimental/mdc-core/_core-theme.scss, src/material-experimental/mdc-core/option/_optgroup-theme.scss, src/material-experimental/mdc-core/option/_option-theme.import.scss, src/material-experimental/mdc-core/option/_option-theme.scss, src/material-experimental/mdc-helpers/_mdc-helpers.scss, src/material-experimental/mdc-typography/_all-typography.import.scss, src/material-experimental/mdc-typography/_all-typography.scss, src/material-experimental/popover-edit/_popover-edit-theme.scss, src/material-experimental/popover-edit/_popover-edit.import.scss, tools/stylelint/theme-mixin-api.ts
Implements an `_index.scss` file in `material-experimental` similar to the one in `material`.
Also fixes a couple of theme files that weren't named correctly and some mixins whose prefixes weren't removed by the migration script.
=> refactor(material-experimental/mdc-core): expose new @use-based Sass API

src/google-maps/map-marker-clusterer/map-marker-clusterer.spec.ts, src/google-maps/map-marker-clusterer/map-marker-clusterer.ts, tools/public_api_guard/google-maps/google-maps.d.ts
Adds an event that emits when a cluster has been clicked.
Fixes #22020.
=> feat(google-maps): add clusterer click event

src/cdk/_index.scss, src/cdk/overlay/_overlay-deprecated.scss, src/cdk/overlay/_overlay.import.scss, src/cdk/overlay/_overlay.scss, src/material/schematics/ng-generate/theming-api/index.spec.ts, src/material/schematics/ng-generate/theming-api/migration.ts
This is follow-up from the PR that introduced the theming API migration (https://github.com/angular/components/pull/22304#discussion_r598258575). It renames a few variables in the CDK to align them with the new API.
=> refactor(cdk/overlay): clean up variable names

src/material/progress-spinner/progress-spinner.scss
Fixes that progress spinner blends in with the background, because `currentColor` doesn't work as expected on SVGs on Chromium browsers in high contrast mode.
=> fix(material/progress-spinner): not visible in high contrast mode on chromium browsers

src/material-experimental/mdc-checkbox/checkbox.scss, src/material/checkbox/checkbox.scss, src/material/radio/radio.scss
* added color-adjust for radio background-color
* added color-adjust for checkbox background-color
=> feat(radio/checkbox): show background-color in print stylesheet (#22298)

.github/angular-robot.yml
This setting has been causing friction on PRs, requiring reviewers to be
manually approved. The "merge ready" label should only be applied once
a PR is approved.
@josephperrott similar to the discussion the framework team had last week, people are running into friction with applying "merge ready" as a type of auto-submit. This PR disables the setting for requiring all reviewers; we want to keep the "merge ready" label explicitly as meaning approved and ready to be merged, not that the PR will be ready to merge after review.
=> build: don't require all reviewers to approve PRs

guides/typography.md
This change completely rewrites the typography guide to be more
complete, correct, and concise.
Summary of changes:
* Explain the concepts of "typography level" and "typography config".
* Ensure all content is conceptual and not task-based.
* Use new Sass `@use` API introduiced in #22173
* Split up level descriptions from CSS classes
* Clarify that the system currently uses the 2014-era typography levels
This is the second PR in a series, following #22268. After this will be
PRs for theming-your-components, customizing-component-styles, and new
docs for strong focus indicators.
=> docs(material/theming): rewrite typography guide for `@use`

src/material-experimental/mdc-progress-bar/progress-bar.ts, src/material-experimental/mdc-progress-spinner/progress-spinner.ts, src/material/progress-bar/progress-bar.ts, src/material/progress-spinner/progress-spinner.ts
Fixes issue with NVDA/FIreFox not reading out aria-label (when set)
Fixes https://github.com/angular/components/issues/15017
Note that this does not fix the issue for JAWS/FireFox (https://github.com/FreedomScientific/VFO-standards-support/issues/354)
=> fix(material/progress-bar): fix screenreader not reading aria-label

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/directives/drag.ts, src/cdk/drag-drop/directives/drop-list.ts, src/cdk/drag-drop/drag-events.ts, src/cdk/drag-drop/drag-ref.ts, src/cdk/drag-drop/drop-list-ref.ts, tools/public_api_guard/cdk/drag-drop.d.ts
I need to be able to determine the exact point where the mouse pointer was when the Item was dropped. This is not possible to calculate from the distance, because it depends on the position where the item was grabbed at drag start.
_CdkDragDrop_.item.getFreeDragPosition(); does also not work because it gives the position of the element top/left corner at drag start.
=> feat(cdk/drag-drop): added dropPoint to dropped event

src/material/datepicker/BUILD.bazel, src/material/datepicker/datepicker-toggle.scss
Fixes an issue where the datepicker toggle icon blends in with the background in high contrast mode on Chromium-based browsers (Edge and Chrome).
=> fix(material/datepicker): toggle icon not visible in high contrast mode on Chromium browsers

src/cdk/portal/dom-portal-outlet.ts, src/cdk/portal/portal-directives.ts, src/cdk/portal/portal.spec.ts
Fixes that the `DomPortalOutlet.hasAttached` doesn't return the correct information when the portal has been attached through the specific portal methods (e.g. `attachComponentPortal`, `attachTemplatePortal`).
Fixes #22370.
=> fix(cdk/portal): not marked as attached when going through specific portal methods

src/cdk-experimental/popover-edit/popover-edit.spec.ts, src/cdk-experimental/selection/selection.ts, src/cdk/collections/array-data-source.ts, src/cdk/collections/data-source.ts, src/cdk/drag-drop/drop-list-ref.ts, src/cdk/drag-drop/parent-position-tracker.ts, src/cdk/schematics/update-tool/utils/decorators.ts, src/cdk/scrolling/virtual-for-of.ts, src/cdk/scrolling/virtual-scroll-repeater.ts, src/cdk/table/sticky-position-listener.ts, src/cdk/table/table.ts, src/cdk/tree/tree.ts, src/components-examples/material/chips/chips-input/chips-input-example.ts, src/material-experimental/column-resize/column-resize.spec.ts, src/material-experimental/popover-edit/popover-edit.spec.ts, src/material/tooltip/tooltip.ts, tools/public_api_guard/cdk/collections.d.ts, tools/public_api_guard/cdk/drag-drop.d.ts, tools/public_api_guard/cdk/scrolling.d.ts, tools/public_api_guard/cdk/table.d.ts, tools/public_api_guard/cdk/tree.d.ts, tslint.json
Relates to:
- #19640
- https://github.com/angular/angular/issues/33135
- https://github.com/angular/components/pull/20252#discussion_r467832026
This PR brings normalization on the form of write readonly arrays: `readonly TYPE []`.
Note that for some cases, specifically truly constants, I've opted out to use `as const` as it's shorter and fully immutable without the need of declaring the type.
=> build: enforce consistent readonly array type

src/google-maps/map-marker/map-marker.spec.ts, src/google-maps/map-marker/map-marker.ts, tools/public_api_guard/google-maps/google-maps.d.ts
Currently the only way to control the icon of a marker is through the `options` object which can be cumbersome. These changes add a dedicated `icon` input which can be used to only change the icon.
Fixes #22097.
=> feat(google-maps): add icon input to marker

src/material-experimental/mdc-form-field/form-field.scss
Sets an explicit `text-align` on the MDC form field so that it isn't affected by the surrounding `text-align`. The issue can be seen by placing an MDC-based `mat-select` in a container with `text-align: center`. We have something similar in the existing form field already.
=> fix(material-experimental/mdc-form-field): set explicit text-align

src/material-experimental/mdc-list/list.scss
Adds similar high contrast mode treatment to the non-MDC list since the MDC implementation suffers from the same issues we had resolved before.
=> fix(material-experimental/mdc-list): add high contrast mode treatment

src/material/sort/sort-header-intl.ts, src/material/sort/sort-header.ts, src/material/sort/testing/sort-header-harness.ts, tools/public_api_guard/material/sort.d.ts, tools/public_api_guard/material/sort/testing.d.ts
Cleans up the deprecated APIs that were marked for removal in v12.
* `MatSortHeaderIntl.sortButtonLabel` has been removed.
* `MatSortHeaderHarness.getAriaLabel` has been removed.
=> refactor(material/sort): remove deprecated APIs for v12

src/material/sidenav/drawer.html, src/material/sidenav/drawer.spec.ts
Marks the sidenav's inner scrollable element as `cdkScrollable` so any overlays placed inside of it can update.
Fixes #19846.
Fixes #18453.
=> fix(material/sidenav): mark sidenav content as scrollable

src/material/_index.scss, src/material/core/theming/tests/BUILD.bazel, src/material/core/theming/tests/test-legacy-theming-bundle.scss
Sets up a build check to verify that the new theming API works.
=> build: add check for new theming bundle

src/material/radio/radio.scss
Fixes that the persistent radio button ripple was being offset if it's placed inside an element with `text-align: center`.
Fixes #22389.
=> fix(material/radio): ripple not positioned correctly inside parent with centered text

src/material-experimental/mdc-list/BUILD.bazel, src/material-experimental/mdc-list/list-base.ts, src/material-experimental/mdc-list/testing/BUILD.bazel
Uses the ripple timing values from MDC for our implementation so that it's consistent with the spec.
=> fix(material-experimental/mdc-list): align ripple timings with MDC

.circleci/config.yml
Limits the various snapshot tests to only run against the main branch. They are very likely to fail against the older branches, because by definition Angular's latest changes at HEAD might not be backwards-compatible.
=> build: only run snapshot tests against main branch

CODING_STANDARDS.md
* Naming conventions for the selectors of components & directives
* The tests & public APIs for MDC components should mirror the non-MDC version
* Public properties should use coercion
=> docs: add missing standards for building components

.ng-dev/commit-message.ts
As discussed, adds a new `multiple` scope for commits that cover more than one area.
=> build: add commit message scope for multiple components

src/material/form-field/form-field.ts
Removes the `mat-accent` and `mat-warn` host bindings from the `mat-form-field` since they're already handled by the `Color` mixin.
=> refactor(form-field): remove unnecessary bindings

src/material/tree/data-source/flat-data-source.ts, src/material/tree/data-source/nested-data-source.ts, src/material/tree/tree.spec.ts, tools/public_api_guard/material/tree.d.ts
The `MatTreeFlatDataSource` has an `initialData` parameter which doesn't work, because it only assigns the data to one of the three streams used to render the tree.
These changes also make some underscored properties private.
Fixes #22282.
=> fix(material/tree): not rendering initial data from flat data source

src/material-experimental/mdc-form-field/_form-field-native-select.scss, src/material-experimental/mdc-select/select.scss
mat-select and native select
fixes the native select arrow color and vertical alignment and removes extra padding from the mat-select arrow
=> fix(material-experimental/mdc-select): correct some differences between

src/material/schematics/ng-add/index.spec.ts, src/material/schematics/ng-add/theming/create-custom-theme.ts
Reworks the custom theme schematic to go through the new theming API.
=> fix(material/schematics): switch custom theme schematic to `@use`

guides/theming.md
This adds documentation for strong focus indicators as part of the
theming guide. This feature has been "soft launched" inside Google, but
hasn't been documented for widespread adoption. At this stage, I'm
confident enough in the stability of the feature to document it for
public usage.
=> docs(material/theming): document strong focus indicators

package.json, yarn.lock
`browser-sync` version 2.26.14 appears to be shipping a client script that uses ES2015 syntax which throws an error on IE and breaks live reloading. These changes lock down the version to 2.26.13 until the issue is resolved. See https://github.com/BrowserSync/browser-sync/issues/1845.
=> build: local live reload not working on IE

WORKSPACE, tools/BUILD.bazel, tools/rbe_cross_platform_workaround.patch
Adds a workaround for `bazel-toolchains` that allows us to
use RBE on macOS or Windows. This no longer works with the
recent upgrades to `bazel-toolchains`.
t
It seems like we can remove this workaround once `bazel-toolchains`
supports cross-compilation, or if we start generating the
toolchain configurations our own (needs more investigation).
=> build: add workaround to support RBE on macOS and windows

src/dev-app/mdc-slider/mdc-slider-demo.html, src/dev-app/mdc-slider/mdc-slider-demo.ts, src/material-experimental/mdc-slider/slider.ts
* add exportAs: matSliderThumb to MatSliderThumb
* create focus and blur methods in MatSliderThumb to match the old demo
=> feat(material-experimental/mdc-slider): rebuild the mdc-slider demo

src/dev-app/theme.scss, src/material-experimental/mdc-autocomplete/_autocomplete-theme.scss, src/material-experimental/mdc-button/_button-theme.scss, src/material-experimental/mdc-card/_card-theme.scss, src/material-experimental/mdc-checkbox/_checkbox-theme.scss, src/material-experimental/mdc-chips/_chips-theme.scss, src/material-experimental/mdc-core/option/_optgroup-theme.scss, src/material-experimental/mdc-core/option/_option-theme.scss, src/material-experimental/mdc-dialog/_dialog-theme.scss, src/material-experimental/mdc-form-field/_form-field-theme.scss, src/material-experimental/mdc-helpers/_mdc-helpers.scss, src/material-experimental/mdc-input/_input-theme.scss, src/material-experimental/mdc-list/_list-theme.scss, src/material-experimental/mdc-menu/_menu-theme.scss, src/material-experimental/mdc-paginator/_paginator-theme.scss, src/material-experimental/mdc-radio/_radio-theme.scss, src/material-experimental/mdc-select/_select-theme.scss, src/material-experimental/mdc-slide-toggle/_slide-toggle-theme.scss, src/material-experimental/mdc-slider/_slider-theme.scss, src/material-experimental/mdc-snack-bar/_snack-bar-theme.scss, src/material-experimental/mdc-table/_table-theme.scss, src/material-experimental/mdc-tabs/_tabs-theme.scss, src/material-experimental/mdc-theming/prebuilt/indigo-pink.scss, src/material-experimental/mdc-tooltip/_tooltip-theme.scss, src/material/core/typography/_typography.scss, tools/stylelint/theme-mixin-api.ts
This is split off of #21778 which covers non-MDC conmponents as well
=> refactor(material/theming): normalize config in all typography mixins for mdc components

src/cdk/testing/protractor/protractor-element.ts, src/cdk/testing/protractor/protractor-harness-environment.ts, src/cdk/testing/test-element.ts, src/cdk/testing/testbed/testbed-harness-environment.ts, src/cdk/testing/testbed/unit-test-element.ts, src/cdk/testing/webdriver/webdriver-element.ts, src/cdk/testing/webdriver/webdriver-harness-environment.ts, tools/public_api_guard/cdk/testing/protractor.d.ts, tools/public_api_guard/cdk/testing/testbed.d.ts, tools/public_api_guard/cdk/testing/webdriver.d.ts
On our docs site, the docs are not inherited from the base class. This
PR also marks our ProtractorHarnessEnvironment as deprecated
=> docs(cdk/testing): copy over doc comments from base class to subclasses

src/cdk/schematics/ng-add/schema.json, src/cdk/schematics/ng-generate/drag-drop/schema.json, src/material/schematics/ng-add/schema.json, src/material/schematics/ng-generate/address-form/schema.json, src/material/schematics/ng-generate/dashboard/schema.json, src/material/schematics/ng-generate/navigation/schema.json, src/material/schematics/ng-generate/table/schema.json, src/material/schematics/ng-generate/theming-api/schema.json, src/material/schematics/ng-generate/tree/schema.json
In Angular CLI version 12, JSON Schema `draft-04` will no longer be supported. Therefore `id` will need to be updated to `$id`.
- We replace id with $id, this no longer valid in draft-07.
- Replace all $schemas to http://json-schema.org/draft-07/schema, this is needed to "pin" the schema to draft-07.
More information about this draft can be found https://json-schema.org/draft-07/json-schema-release-notes.html
Note: This change is backwards compatible.
=> refactor: update `$schema` and `id` keyword

src/material/schematics/ng-generate/theming-api/index.spec.ts, src/material/schematics/ng-generate/theming-api/migration.ts
I noticed this while trying out the theming migration against the docs site. The way the `theming-api` migration is set up means that we'll drop the Material imports as soon as we see them, but that doesn't guarantee that they're actually used further down in the file.
These changes rework the logic so that we drop the imports after we've migrated the symbols.
=> fix(material/schematics): don't drop imports in files that do not use theming APIs

src/e2e-app/mdc-slider/mdc-slider-e2e.ts, src/material-experimental/mdc-slider/BUILD.bazel, src/material-experimental/mdc-slider/slider.e2e.spec.ts
* create basic tests for standard, disabled, and range sliders
=> test(material-experimental/mdc-slider): create e2e tests

guides/elevation.md, src/material/_index.scss, src/material/button/_button-base.scss, src/material/card/card.scss, src/material/checkbox/checkbox.scss, src/material/chips/chips.scss, src/material/core/style/_elevation.import.scss, src/material/core/style/_elevation.scss, src/material/expansion/expansion-panel.scss, src/material/schematics/ng-generate/theming-api/migration.ts
We were mentioning the `mat-elevation-transition` mixin, but the new API wasn't exposing it. Also updates the imports to the new API.
=> fix(material/core): expose mixin mentioned in the elevation guide

src/material-experimental/mdc-list/list-option.ts, src/material-experimental/mdc-list/selection-list.spec.ts, src/material/list/selection-list.spec.ts, src/material/list/selection-list.ts
Fixes that the MDC-based list dispatches its `ngModelChange` event multiple times when the value changes in single selection mode.
Fixes #22276.
=> fix(material/list): dispatching model change event multiple times in single selection mode

src/cdk/keycodes/keycodes.ts, src/cdk/testing/testbed/fake-events/type-in-element.ts, src/cdk/testing/tests/cross-environment.spec.ts, src/cdk/testing/tests/harnesses/main-component-harness.ts, src/cdk/testing/tests/test-components-module.ts, src/cdk/testing/tests/test-main-component.html, src/cdk/testing/tests/test-main-component.ts, tools/public_api_guard/cdk/keycodes.d.ts
Currently the `UnitTestElement` simulates typing into an input by assigning the value character-by-character and dispatching fake events along the way. The problem is that for input types that require the value to be in a particular format (e.g. `number`, `color`, `date`) doing so will temporarily assign an invalid value which will be rejected by the browser with a warning like `The specified value "12." cannot be parsed, or is out of range.`.
This can become a problem for some common use cases like the `ReactiveFormsModule` where a directive might be keeping track of the value by looking at the DOM inside of an `input` event (e.g. the `FormControl` directive does this).
These changes resolve the issue by looking at the type of the input, and if it's a type that requires a specific …
=> fix(cdk/testing): unable to assign value to number inputs using sendKeys

src/material-experimental/_index.scss, src/material-experimental/mdc-core/_core-theme.scss, src/material-experimental/mdc-core/_elevation.scss
Sets up elevation utilities based on top of MDC, similar to the ones we currently have.
=> feat(material-experimental/mdc-core): set up MDC-based elevation

src/cdk/stepper/stepper.ts, src/material/stepper/stepper.spec.ts, tools/public_api_guard/cdk/stepper.d.ts
Adds an `interacted` event that will emit when the user tries to move away from a step.
Fixes #19918.
=> feat(cdk/stepper): emit event when the user interacts with a step

src/material-experimental/mdc-progress-spinner/progress-spinner.spec.ts, src/material-experimental/mdc-progress-spinner/progress-spinner.ts
Previously the aria-valuenow on mat-progress-spinner was being set through the mdc foundation which deals with values from 0 to 1. This caused the aria-valuenow to be incorrect (eg. 0.6 instead of 60).
Solution: Use `mat-progress-spinner` as a wrapper element instead and have the different circle containers under a separate `mdc-circular-progress` div instead of right under `mat-progress-spinner`. This way the mdc foundation can interact with the underlying `mdc-circular-progress` div instead of the overall `mat-progress-spinner` selector.
=> fix(material-experimental/mdc-progress-spinner): fix aria-valuenow

src/material/tabs/paginated-tab-header.ts
The tab header pagination wasn't updating when the page is resized, because the resize listener runs outside of Angular.
Fixes #22399.
=> fix(material/tabs): pagination not updating on resize

src/cdk/testing/change-detection.ts
If the actual subscription provided by the environment comes after the first batched function call, the default function is installed and without this change it'll stay installed forever, even if another handler is installed afterwards.
I looked for a location to add a test for this, but I don't think it's currently possible to test this. The only harness environment in this repo that supports the change detection status is the TestBed variant, and that environment registers its change detection status handler eagerly.
=> fix(cdk/testing): prevent duplicate subscription

packages.bzl, src/cdk/package.json, src/google-maps/package.json, src/material/package.json, src/youtube-player/package.json
Adds a peer dependency to `rxjs` to all packages since not having it can mess with Yarn 2's PnP feature.
=> build: add peer dependency to rxjs

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/drag-ref.ts, src/cdk/drag-drop/drag-styling.ts, src/cdk/drag-drop/drop-list-ref.ts
We have some logic that tries to preserve the original `transform` of an element, but we only apply it while standalone dragging. These changes expand the support to include elements inside a drop list, as well as the preview and placeholder.
Fixes #22407.
=> fix(cdk/drag-drop): preserve initial transform inside drop list

src/material-experimental/mdc-core/_elevation.scss
I left an `@debug` by accident and now it's spamming the logs.
=> build: clean up leftover debug log

guides/theming-your-components.md, src/material/_index.scss
This change completely rewrites the theming-your-components guide to be
more complete, correct, and concise.
Summary of changes:
* Start document with some explanatory content before diving into
step-by-step tutorial.
* Use new Sass `@use` API introduced in #22173
* Document (and expose) `get-color-config` and `get-typography-config`
=> docs(material/theming): rewrite theming-your-components guide

.github/CODEOWNERS, src/cdk/a11y/focus-monitor/focus-monitor.spec.ts, src/cdk/a11y/focus-monitor/focus-monitor.ts, src/cdk/a11y/input-modality/input-modality-detector.spec.ts, src/cdk/a11y/input-modality/input-modality-detector.ts, src/cdk/a11y/public-api.ts, src/dev-app/BUILD.bazel, src/dev-app/dev-app/dev-app-layout.ts, src/dev-app/dev-app/routes.ts, src/dev-app/input-modality/BUILD.bazel, src/dev-app/input-modality/input-modality-detector-demo-module.ts, src/dev-app/input-modality/input-modality-detector-demo.html, src/dev-app/input-modality/input-modality-detector-demo.ts, tools/public_api_guard/cdk/a11y.d.ts
*Note: This is a first-stab at an input modality detection service and I expect there to be some churn regarding its exact behavior, so feel free to leave many comments.*
In our app, we conditionally render strong focus styles on elements if the element is determined to have been focused via keyboard. This is done by attaching a global `FocusMonitor` to the `document.body`. One problem with this approach is that we can only detect input modality changes when focus also changes (see https://github.com/angular/components/issues/21555 for why this is a problem with `aria-activedescendant` elements). The purpose of the `InputModalityDetector` service is to allow users to detect a broader array of input modality changes, regardless of whether focus changes.
The `InputModalityDetector` attempts …
=> feat(cdk/a11y): Add a new InputModalityDetector service to detect the user's current input modality.

src/material-experimental/mdc-slider/slider.e2e.spec.ts, src/material-experimental/mdc-slider/slider.spec.ts
* also removed two forgotten `console.log`s
=> test(material-experimental/mdc-slider): add input handler tests

src/material-experimental/mdc-snack-bar/snack-bar.spec.ts, src/material/snack-bar/snack-bar-ref.ts, src/material/snack-bar/snack-bar.spec.ts
This is very similar to #4860 where a programmatic dismiss
cancelled the timeout. This patch is for a manual dismiss via
clicking on the snackbar action.
It is especially useful in e2e tests with Protractor, because
Protractor always wait for Angular to become stable. With this patch
Protractor does not need to wait if the action is clicked, saving
potentially a lot of time in repetitive e2e tests.
=> fix(material/snack-bar): clear timeout upon dismiss with action

tools/dgeni/common/dgeni-definitions.ts, tools/dgeni/templates/method.template.html, tools/dgeni/templates/property.template.html
Fixes that some inherited class members didn't have descriptions in the generated docs. The problem seems to be that we were using the `description` field, whereas the text was in the `content` field. I don't have the context behind why we were using `description`, but the field doesn't exist in Dgeni's typings and `content` seems to work in all the cases I tried.
=> build: some public API docs missing descriptions

src/google-maps/map-marker/map-marker.spec.ts, src/google-maps/map-marker/map-marker.ts, tools/public_api_guard/google-maps/google-maps.d.ts
Currently the marker visibile can only be controlled through the `options` object. These changes add a dedicated input for convenience.
Fixes #22488.
=> feat(google-maps): add visible input to marker

src/material-experimental/mdc-list/list-option.scss
When a list option is selected in single selection mode, it changes its background color to stand out. This doesn't work in high contrast mode so these changes port over the workaround that we have from the non-MDC list.
=> fix(material-experimental/mdc-list): add selected indication in high contrast mode

src/material-experimental/mdc-paginator/paginator.scss, src/material/paginator/BUILD.bazel, src/material/paginator/paginator.scss
Setting `fill: currentColor` on an SVG element causes it to blend in with the background on Chromium-based browsers. These changes add a fallback color.
=> fix(material/paginator): button icons blending in with background in high contrast mode on Chromium browsers

src/material-experimental/mdc-progress-spinner/progress-spinner.scss
The colors in the SVG used for the MDC progress spinner won't be re-mapped automatically in high contrast mode. These changes add the same treatment that we have for the non-MDC version.
=> fix(material-experimental/mdc-progress-spinner): apply correct color in high contrast mode

src/material/paginator/paginator.scss
Fixes a path that is wrong, because the PR was opened before we renamed the file.
=> build: fix wrong import path

src/material/schematics/ng-generate/theming-api/config.ts, src/material/schematics/ng-generate/theming-api/index.spec.ts, src/material/schematics/ng-generate/theming-api/migration.ts
The new Sass API removes some variables that had been previously exported by accident. These changes expand the migration so that usages of those variables are replaced with the values. The replacement doesn't cover variable assignments, because migrating them is impossible.
=> fix(material/schematics): replace removed variables with their values in sass api migration

src/material-experimental/mdc-autocomplete/autocomplete.spec.ts, src/material/autocomplete/autocomplete-trigger.ts, src/material/autocomplete/autocomplete.spec.ts
Fixes an error that is thrown if a `keydown` event is dispatched before the autocomplete panel has been initialized.
Fixes #22511.
=> fix(material/autocomplete): error if keydown is dispatched too early

src/cdk/a11y/a11y.md
This change updates the Sass documentation for cdk/a11y to reflect the
new `@use`-based API. Additionally, it adds documentation for the
parameters to `cdk.high-contrast`.
=> docs(cdk/a11y): update Sass docs for new theming API

guides/elevation.md
This change updates the elevation guide to be more clear, concise, and
complete. The changes include:
* Drop content about the general concept of elevation, deferring that to
the Material Design spec.
* Document the `overridable-elevation` mixin
* Mention that the elevation CSS classes are emitted by `core-theme`.
* Switch to `@use`
=> docs(material/theming): rewrite elevation guide

guides/customizing-component-styles.md
This change updates the customizing-component-styles doc to give more
specific guidance on overriding component styles. In particular:
* Much stronger language to make it clear that this is not supported or
recommended.
* Reorganize content such that topics have a bit more cohesion/flow
* Call out that layout/positioning styles on host elements are the only
safe styles to apply.
* Emphasize the perils of overrides in general
=> docs(material/theming): revise customizing-component-styles

src/material/expansion/expansion-panel-header.ts, src/material/expansion/expansion.spec.ts, tools/public_api_guard/material/expansion.d.ts
Adds the ability to assign a custom `tabindex` to the expansion panel header.
Fixes #22521.
=> fix(material/expansion): unable to assign custom tabindex on header

src/material/datepicker/date-range-input.scss, src/material/form-field/form-field-input.scss
Fixes that the placeholders in the date range picker and form field were visible behind the label in high contrast mode.
=> fix: form field placeholders not hidden in contrast mode

src/material-experimental/mdc-slider/slider.spec.ts, src/material-experimental/mdc-slider/slider.ts
* fix bug where setting the disabled state on the overall
slider was not disabling the individual slider thumbs
control value accessor disabled state.
=> test(material-experimental/mdc-slider): add custom form control tests

src/material-experimental/mdc-tabs/tab-group.spec.ts, src/material/tabs/tab-group.spec.ts, src/material/tabs/tab-group.ts
Adds min-height to the mat-tab-group wrapper, so page height is preserved
as tabs change, and page doesn't scroll up.
Fixes #9592
=> fix(material/tabs): stop scrolling on tab change

src/material-experimental/mdc-progress-bar/progress-bar.html, src/material-experimental/mdc-progress-bar/progress-bar.scss, src/material-experimental/mdc-progress-bar/progress-bar.spec.ts, src/material-experimental/mdc-progress-bar/progress-bar.ts
refactor progress bar to have same structure as progress spinner (without wrapper element)
related: https://github.com/angular/components/pull/22429
=> refactor(material-experimental/mdc-progress-bar): remove wrapper element for progress bar

src/cdk/stepper/stepper.ts, src/material/stepper/public-api.ts, src/material/stepper/stepper.spec.ts, tools/public_api_guard/cdk/stepper.d.ts
Currently we have a feature where a step can be forced into an error state using the `hasError` input. The problem is that doing so won't actually change anything by default, because the `showError` option also has to be provided through an injection token.
These changes add some logic so that the error will be shown automatically, if it was set explicitly through `hasError`.
Fixes #22539.
=> fix(cdk/stepper): show error state if explicitly enabled

src/cdk/text-field/text-field.md, src/material-experimental/README.md, src/material-experimental/mdc-autocomplete/README.md, src/material-experimental/mdc-card/README.md, src/material-experimental/mdc-checkbox/README.md, src/material-experimental/mdc-chips/README.md, src/material-experimental/mdc-dialog/README.md, src/material-experimental/mdc-menu/README.md, src/material-experimental/mdc-paginator/README.md, src/material-experimental/mdc-progress-bar/README.md, src/material-experimental/mdc-progress-spinner/README.md, src/material-experimental/mdc-radio/README.md, src/material-experimental/mdc-select/README.md, src/material-experimental/mdc-slide-toggle/README.md, src/material-experimental/mdc-slider/README.md, src/material-experimental/mdc-snack-bar/README.md, src/material-experimental/mdc-table/README.md, src/material-experimental/mdc-tabs/README.md, src/material-experimental/mdc-tooltip/README.md
Updates all of the remaining docs to go through the new `@use` API instead of `@import`.
**Note:** does not include the `mdc-button` readme, because the necessary mixins aren't exported yet. See #22449.
=> docs: switch remaining docs to @use

.circleci/config.yml
We used to copy the minified UMD bundles so that their size could be checked by the size bot. Since we haven't been running the bot for a long time, these changes remove the copying logic.
=> build: disable copying the minified umd bundles

src/material/datepicker/date-range-input.html, src/material/datepicker/date-range-input.ts, tools/public_api_guard/material/datepicker.d.ts
Resolves a few issues that were preventing the use of the range picker with an MDC-based `mat-form-field`. Including:
1. Conditionally setting the `mat-mdc-input-element` class so that the input is sized correctly.
2. Triggering a state change event when the focus state changes so that the floating label is up-to-date.
3. Fixing an error being thrown inside `_shouldHideSeparator`.
=> fix(material/datepicker): support for date range input in MDC-based form field

src/cdk-experimental/combobox/combobox-panel.ts, src/cdk-experimental/menu/context-menu.ts, src/cdk-experimental/menu/menu-bar.ts, src/cdk-experimental/menu/menu-stack.ts, src/cdk-experimental/menu/menu.ts, src/components-examples/cdk-experimental/selection/cdk-selection-column/cdk-selection-column-example.ts, src/components-examples/cdk-experimental/selection/cdk-selection-list/cdk-selection-list-example.ts, src/components-examples/material-experimental/selection/mat-selection-column/mat-selection-column-example.ts, src/components-examples/material-experimental/selection/mat-selection-list/mat-selection-list-example.ts, src/material/datepicker/datepicker-toggle.ts, src/material/menu/menu-trigger.ts, src/material/menu/menu.ts, src/material/tabs/paginated-tab-header.ts, src/material/tree/data-source/nested-data-source.ts
Fixes a few places that will become compilation errors in rxjs version 7. All of the changes are backwards-compatible so we can merge them now so that we have less issues to resolve once we make the switch.
**Note:** I'm marking this as merge safe, because all of the changes are internal and they only affect type information. There are a couple of extra null checks, but they're in `cdk-experimental` which is also merge safe.
=> refactor(multiple): resolve rxjs 7 compilation errors

src/material-experimental/mdc-slider/slider.spec.ts, src/material-experimental/mdc-slider/slider.ts
* The MDC Foundation stores the bounding client rect when layout is first called.
This means that if the position of the slider changes after the initial layout,
the slider will break. To fix this broken behavior, we just call layout on
pointerdown
=> fix(material-experimental/mdc-slider): sync ui on pointerdown

src/cdk/a11y/high-contrast-mode/high-contrast-mode-detector.ts
I noticed this in the profiler while working on https://github.com/angular/material.angular.io/pull/961. The `_applyBodyHighContrastModeCssClasses` method is called in the constructor of the `A11yModule` and `MatCommonModule` which means that it'll be invoked whenever a new root injector is created for a module importing any Material module (e.g. lazy-loaded route or dynamically-created component). Since it calls into `getHighContrastMode` and it touches the class list of `document.body`, it has the potential of causing some some slow layouts. This can be observed either when switching pages in the dev app or by profiling the example creation on material.angular.io.
These changes resolve the issue by ensuring that we only run the logic once.
=> perf(cdk/a11y): only check for high contrast mode once

src/material-experimental/mdc-chips/chip.ts, src/material/chips/chip.ts, src/material/core/common-behaviors/color.ts, src/material/core/common-behaviors/constructor.ts, src/material/core/common-behaviors/disable-ripple.ts, src/material/core/common-behaviors/disabled.ts, src/material/core/common-behaviors/error-state.ts, src/material/core/common-behaviors/tabindex.ts, tools/public_api_guard/material/core.d.ts
Reworks the mixin functions in order to remove a workaround where we had to cast to `unknown`. The cast was causing some issues with Closure compiler.
=> fix(material/core): update mixin functions to avoid unknown cast

src/material/core/ripple/ripple-renderer.ts, src/material/core/ripple/ripple.spec.ts, src/material/core/ripple/ripple.ts, tools/public_api_guard/material/core.d.ts
When button becomes disabled after the ripple initiated and before the
ripple animation is completed, it will somestimes not fire the
`mat-ripple-element` correctly. Adding the `fadeOutAll()` method when
set to disable will fix this issue.
Fixes #22520
=> fix(material/core): `mat-ripple-element` is not fired on disable

src/components-examples/material/form-field/form-field-harness/form-field-harness-example.spec.ts, src/material-experimental/mdc-form-field/testing/BUILD.bazel, src/material-experimental/mdc-form-field/testing/form-field-harness.spec.ts, src/material-experimental/mdc-form-field/testing/form-field-harness.ts, src/material/datepicker/testing/BUILD.bazel, src/material/datepicker/testing/datepicker-input-harness-base.ts, src/material/form-field/testing/BUILD.bazel, src/material/form-field/testing/form-field-harness.spec.ts, src/material/form-field/testing/form-field-harness.ts, src/material/form-field/testing/shared.spec.ts, tools/public_api_guard/material/form-field/testing.d.ts
Resolves a TODO about supporting datepicker inputs in the form field harness.
Also fixes an error that is thrown when the date range input is combined with an MDC-based form field.
=> fix(material/form-field): handle datepicker inputs in harness

scripts/check-mdc-tests-config.ts, src/material-experimental/mdc-core/_core-theme.scss, src/material-experimental/mdc-menu/menu.html, src/material-experimental/mdc-menu/menu.spec.ts, src/material-experimental/mdc-menu/menu.ts, src/material/menu/menu.ts, tools/public_api_guard/material/menu.d.ts
Previously we didn't implement the feature where nested menus increase their elevation for each level, because we didn't have elevation classes based on MDC. Now that we do, we can implement the feature.
Also adds an extra elevation class that allows us to increase the specificity over the default one from MDC.
=> fix(material-experimental/mdc-menu): implement increasing elevation

src/material/datepicker/date-range-input-parts.ts, src/material/datepicker/date-range-input.spec.ts, src/material/datepicker/date-selection-model.ts, tools/public_api_guard/material/datepicker.d.ts
Changes date selection to only update controls when value has changed. This is a fix for part of #21847
=> fix(material/datepicker): Only update selection when value changed (#21847)

src/material/schematics/ng-generate/theming-api/config.ts, src/material/schematics/ng-generate/theming-api/index.spec.ts, src/material/schematics/ng-generate/theming-api/index.ts, src/material/schematics/ng-generate/theming-api/migration.ts
Includes the following improvements to the `themingApi` schematic:
1. No longer runs against files in the `node_modules`. This was happening by accident.
2. Remove the quotes around the values of `$mat-small` and `$mat-xsmall` since they were causing Sass syntax errors.
3. Migrates Material/CDK symbols, even if there are no imports for the old theming bundle. This allows us to handle symbols that were imported transitively.
4. Reverts the logic from #22438 that doesn't drop imports if there are no Material/CDK symbol usages within the file. I think that we want to do this after all, because the old import could slow down build times and we can be relatively certain that any usages have been migrated.
Fixes #22599.
=> fix(material/schematics): migrate more cases in the theming API schematic

src/material-experimental/_index.scss
This adds an mdc- prefix in the `_index.scss` public API for material experimental. Without the prefix, this collides with the older elevation mixins. This collision is a problem in Google where we export both APIs through a combined entry-point.
=> fix(material-experimental/theming): prefix elevation mixins with mdc

src/material-experimental/mdc-progress-spinner/progress-spinner.scss
This matches legacy styles and helps users migrate without adding this explicit style (especially when trying to use auto margin on the spinner).
Caretaker: This has been presubmitted with screenshot fixes in cl/371687399
=> fix(material-experimental/mdc-progress-spinner): set to display block

src/material-experimental/mdc-chips/chip-input.spec.ts, src/material-experimental/mdc-chips/chip-input.ts, src/material-experimental/mdc-form-field/_form-field-native-select.scss, src/material-experimental/mdc-form-field/_form-field-theme.scss, src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss, src/material-experimental/mdc-input/input.spec.ts, src/material-experimental/mdc-input/input.ts, src/material/input/input.ts, tools/public_api_guard/material/input.d.ts
Currently `mat-form-field` brings in the styles for `MatInput`. but the problem is that they target a class that is applied even to inputs that aren't inside a form field.
These changes aim to prevent CSS from bleeding out by only styling inputs inside a `mat-form-field`.
Fixes #21871.
=> fix(material-experimental/mdc-input): only apply styling when inside a form field

src/material-experimental/mdc-paginator/paginator.spec.ts, src/material-experimental/mdc-paginator/paginator.ts, src/material/paginator/paginator.md, src/material/paginator/paginator.spec.ts, src/material/paginator/paginator.ts
In testing `<mat-paginator>` with VoiceOver, I found that the interaction was much nicer when the paginator controls were semantically grouped with `role="group"`. This change adds the role and updates the documentation to explicitly instruct users to apply a meaningful label.
I was on the fence about adding a default label (something like "Pagination control"). I settled on this approach because it's the most consistent with our other controls that require developers to specify a label for host elements, even though we do have `MatPaginatorIntl` for the labels for child components within the control.
=> fix(material/paginator): add `role="group"` to host

package.json, yarn.lock
With typicode/husky#890, the recommended way to install husky is in the
`prepare` script instead of the `postinstall`. This commit moves
the husky installation to the `prepare` script to align with the new
recommendation.
=> build: update to husky@6

angular-tsconfig.json
Currently if a package like `@angular/cdk` is used locally within a
Bazel NodeJS action (e.g. when using with `rollup_bundle`), the Bazel
NodeJS rules link the build output into the local `node_modules/` folder.
This is problematic because later if `yarn` is executed, the linked
packages are incorrectly included in the `angular-tsconfig.json` project
(which is used for summary generation to allow for Bazel View Engine tests)
We fix this by explicitly excluding our local packages to avoid errors
such as:
```
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
(warning Resolution field "typescript@4.2.3" is incompatible with requested version "typescript@^3.2.2"
node_modules/@angular/components-examples/material/chips/chips-harness/chips-harness-example.d …
```
=> build: fix yarn install error if `rules_nodejs` linked local packages

integration/size-test/BUILD.bazel, integration/size-test/check-size.ts, integration/size-test/index.bzl, integration/size-test/rollup.config.js
Even though the size integration tests do not run
in a blocking way on CI, we should ensure they
can be run and do not fail. The tests are still
useful for local debugging and comparisons.
This commit fixes that NodeJS throws about `webpack`
not being found. The build optimizer imports from webpack
if we go through the public entry-point. Also simplifies the
logic for finding the `angular_ivy_enabled.js` file.
```
Error: Cannot find module 'webpack'
Require stack:
- /b/f/w/node_modules/@angular-devkit/build-optimizer/src/build-optimizer/webpack-loader.js
- /b/f/w/node_modules/@angular-devkit/build-optimizer/src/index.js
- /b/f/w/bazel-out/k8-fastbuild/bin/integration/size-test/cdk/drag-drop/_all-directives_bundle.rollup_config.js
- /b/f/w/node_modules/rollup/dist/shared/loadConfigFile.js …
```
=> build: fix size-test integration tooling

src/cdk/testing/tests/webdriver-test.bzl
Removes an unnecessary dependency being added to the
webdriver test. The NPM dependency doesn't seem to
be needed and increases the runfile tree by accident.
=> build: remove unnecessary dependency in webdriver test

src/cdk/a11y/focus-trap/focus-trap.spec.ts, src/cdk/a11y/focus-trap/focus-trap.ts
The focus trap directive has the ability to restore focus to the previously-focused element on destroy automatically, however the logic doesn't account for the fact that `document.activeElement` will point to the shadow root if the element is inside the shadow DOM.
=> fix(cdk/a11y): not restoring focus to elements inside the shadow DOM

src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.spec.ts, src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.ts
Similar to #21397. Fixes that the `OverlayOutsideClickDispatcher` doesn't emit when the user presses outside using the middle or right mouse button.
Also fixes some formatting.
=> fix(cdk/overlay): not emitting for auxiliary button clicks

src/cdk/testing/component-harness.ts, src/cdk/testing/tests/cross-environment.spec.ts, src/cdk/testing/tests/harnesses/compound-selector-harness.ts, src/cdk/testing/tests/harnesses/main-component-harness.ts, src/cdk/testing/tests/harnesses/quoted-comma-selector-harness.ts, src/cdk/testing/tests/test-main-component.html
Currently the component harness handles the `ancestor` option by prepending it to the `hostSelector` of the harness. This breaks down if the `hostSelector` is a compound selector, because we end up with something like `.parent .a, .b`, rather than `.parent .a, .parent .b`.
These changes resolve the issue and add a bit of extra logic to account for the case where the selector might include commas inside quotes which will break us, because we split compound selectors on the comma. The logic is loosely based on my changes from https://github.com/angular/angular/pull/38716.
Fixes #22475.
=> fix(cdk/testing): incorrectly handling ancestor of compound selector

src/material/datepicker/date-range-input.spec.ts, src/material/datepicker/date-range-input.ts, src/material/datepicker/datepicker-base.ts, src/material/datepicker/datepicker-input.ts, src/material/datepicker/datepicker.spec.ts, tools/public_api_guard/material/datepicker.d.ts
Fixes that the datepicker overlay element doesn't have a label which causes screen readers to read out "dialog". These changes point the overlay's `aria-labelledby` either to the label of the form field or the `aria-labelledby` of the input.
=> fix(material/datepicker): add label to dialog overlay

src/material-experimental/mdc-tabs/_tabs-common.scss, src/material-experimental/mdc-tabs/_tabs-theme.scss, src/material-experimental/mdc-tabs/tab-header.scss, src/material/tabs/_tabs-theme.scss
Resolves several issues related to the color of icons and ripples in the tab header, when it has a non-default `backgroundColor`.
Fixes #22587.
=> fix(material/tabs): coloring issues when a backgroundColor is set

src/dev-app/dev-app/dev-app-layout.html, src/dev-app/dev-app/dev-app-layout.ts, src/dev-app/main-module.ts
Adds a button that allows us to test noop animations without having to make code changes.
=> build: add animations toggle to the dev app

src/material-experimental/mdc-slider/testing/BUILD.bazel, src/material-experimental/mdc-slider/testing/public-api.ts, src/material-experimental/mdc-slider/testing/slider-harness-filters.ts, src/material-experimental/mdc-slider/testing/slider-harness.spec.ts, src/material-experimental/mdc-slider/testing/slider-harness.ts, src/material-experimental/mdc-slider/testing/slider-thumb-harness.ts
Adds test harnesses for the MDC-based slider components.
=> feat(material-experimental/mdc-slider): add test harnesses

src/components-examples/material/table/table-selection/table-selection-example.ts
Documentation update
scope: table selection example
replace ternary operator by if statement with early return
replace redundant forEach statement with neat spread operator
=> docs(material/table): refactor table selection master toggle

src/material-experimental/mdc-table/public-api.ts, src/material-experimental/mdc-table/table-data-source.ts, src/material/table/table-data-source.ts, tools/public_api_guard/material/table.d.ts
Modify the `MatTableDataSource` interface so that instead of expecting either the legacy `MatPaginator` or MDC-based `MatPaginator`, it accepts something with the right API interface and defaults to that.
This change enables users to migrate from the legacy table to the MDC-based table without requiring them to also migrate the pagintor (which then also includes select, thus all form field elements, and button and tooltip).
=> fix(material/table): Make table data source interface generic

packages.bzl
- `11.0.0-canary.3201cae47.0` is required due to the use of
the `mdc-list-deprecated-item-disabled-text-color` mixin
Fixes #22409. Related to #21968.
=> fix(material-experimental/mdc-core): update the required MDC version

src/material-experimental/mdc-progress-spinner/progress-spinner.scss
When the line-height is much larger than the diameter, the spinner breaks. 
Example: https://stackblitz.com/edit/angular-rgtfre-k7iryu?file=src/app/progress-spinner-overview-example.html
This explicitly sets it to 0 rather than whatever it would inherit.
Filed an issue with MDC: https://github.com/material-components/material-components-web/issues/7118
=> fix(material-experimental/mdc-progress-spinner): set line-height

src/material-experimental/mdc-progress-bar/progress-bar.scss, src/material-experimental/mdc-progress-bar/progress-bar.ts
On the first iteration of the MDC progress bar we had to use JS to change the direction in RTL, but a few months ago in #21650 we switched to a different API that no longer depends on it. The problem with the changes in #21650 is that they set the `dir` on the progress bar in order to flip its direction for the `query` mode.
These changes simplify the setup by relying only on CSS to determine the direction.
Fixes #22609.
=> fix(material-experimental/mdc-progress-bar): don't rely on JS to change directionality

src/material/datepicker/date-range-input-parts.ts
We have a call to `Injector.get` in the date range input which is supposed to fall back to `null` if the value doesn't resolve, however we're missing the `Optional` flag. It works by accident at the moment, because the inject flags aren't actually being passed through by the framework.
https://github.com/angular/angular/pull/41592 is supposed to fix the framework issue, but their CI will break due to our usage.
These changes fix our usage in order to unblock the framework PR.
=> fix(material/datepicker): pass correct inject flags to injector

src/material-experimental/mdc-tooltip/BUILD.bazel, src/material-experimental/mdc-tooltip/tooltip.spec.ts, src/material/tooltip/BUILD.bazel, src/material/tooltip/tooltip.spec.ts, src/material/tooltip/tooltip.ts
Fixes that the tooltip won't update its position config if the directionality changes after it has been initialized.
=> fix(material/tooltip): not updating position after direction changes

src/material/schematics/ng-update/migrations/theming-api-v12/migration.ts, src/material/schematics/ng-update/migrations/theming-api-v12/theming-api-migration.ts, src/material/schematics/ng-update/test-cases/v12/misc/theming-api-v12.spec.ts
Currently the theming API migration drops any imports starting with `~@angular/material/`, assuming that they're Sass APIs. This can result in prebuilt style imports being removed by mistake.
These changes add a regex based on which we'll exclude some imports from the migration.
Fixes #22697.
=> fix(material/schematics): don't drop prebuilt imports in theming API migration

src/material/core/focus-indicators/_focus-indicators.scss, src/material/stepper/step-header.html, src/material/stepper/step-header.ts, src/material/stepper/stepper.spec.ts
The strong focus indicator renders using a `::before` selector which is also used for styling a stepper header with a `below` label position. This results in broken styles when strong focus indication is enabled.
These changes move the indicator to a different element.
Fixes #22677.
=> fix(material/stepper): strong focus indicator not working for below label position

src/material-experimental/mdc-progress-bar/progress-bar.scss
Fixes that the buffer bar in the MDC-based `mat-progress-bar` still animates when animations are disabled.
=> fix(material-experimental/mdc-progress-bar): buffer animation not disabled under noop animations module

src/material-experimental/mdc-radio/radio.scss, src/material-experimental/mdc-radio/radio.ts
Fixes that the MDC-based radio button didn't disable its animations when noop animations were turned on.
=> fix(material-experimental/mdc-radio): not removing animations when noop animations are enabled

WORKSPACE
The minimum bazel version to use with this repo is v4.0.0.
=> build: update the comment of workspace for bazel version

src/google-maps/package.json, src/youtube-player/package.json
Currently if developers run `ng update` without specifying a package,
the CLI will analyze the current workspace and find packages that
provide migrations and need to be updated. For the `youtube-player`
and `google-maps` package we do not provide any migrations, so
`ng update` will not report this package.
Since these packages are part of the `@angular` scope, we
want these packages to be highlighted when users run `ng update`.
There aren't any migrations for these packages yet, but we are setting
up the integration with `ng update` in order to make these packages
visible to the CLI.
Fixes #22689.
=> feat(multiple): add ng-update entry for `google-maps` and `youtube-player` package

src/material/sort/sort-header.ts, tools/public_api_guard/material/sort.d.ts
This commit fixes hard crash that results from accessing undefined object's property. https://github.com/angular/components/issues/22210
=> fix(material/sort): fix undefined object access

src/material-experimental/_index.scss, src/material-experimental/mdc-button/_button-theme-private.scss, src/material-experimental/mdc-button/_button-theme.import.scss, src/material-experimental/mdc-button/_button-theme.scss, src/material-experimental/mdc-button/_fab-theme.scss, src/material-experimental/mdc-button/_icon-button-theme.scss, src/material-experimental/mdc-color/_all-color.import.scss, src/material-experimental/mdc-density/_all-density.import.scss, src/material-experimental/mdc-theming/_all-theme.import.scss, src/material-experimental/mdc-theming/_all-theme.scss, src/material-experimental/mdc-typography/_all-typography.import.scss
When I was setting up the new theming API for MDC, I assumed that the button theme would include the icon button and fab themes as well, but that's not the case.
These changes reorganize the button theming styles into separate files so that we can easily expose the missing mixins under the correct prefix.
=> refactor(material-experimental/mdc-button): reorganize styles and expose all themes

src/material-experimental/mdc-table/_table-theme.scss, src/material-experimental/mdc-table/table.scss
The MDC-based table does not handle sticky columns. Cells overlap their text since they do not have a background color. Fixed by adding a background color to the table like we do with the legacy table, and inheriting the background down through the component.
Hover styles have been disabled. They break this fix since they include opacity, introducing the same issue. MDC should change their default hover color to be a solid color rather than one with an alpha channel.
=> fix(material-experimental/mdc-table): add background color; disable hover styles; fix sticky columns

src/material/tabs/tab-group.ts, src/material/tabs/tab.ts, tools/public_api_guard/material/tabs.d.ts
Fixes an error that is thrown when tabs are projected in from another component into a `mat-tab-group`.
Fixes #21770.
=> fix(material/tabs): projected tabs not being picked up

src/material-experimental/mdc-slide-toggle/slide-toggle.ts, src/material/slide-toggle/slide-toggle.html, src/material/slide-toggle/slide-toggle.ts, tools/public_api_guard/material/slide-toggle.d.ts
Fixes that the ripples of the slide toggle weren't being disabled when all animations are disabled.
=> fix(material/slide-toggle): disable ripples when animations are disabled

src/cdk/testing/testbed/fake-events/event-objects.ts, src/material/slider/slider.ts
`mat-slider` is set up so that it binds global `touchmove` and `touchend` events after dragging starts so that the user can drag while not keeping their finger right on top of the slider. The problem is that currently we only use the first touch from the list of touches which means that if the user is dragging more than one slider on a multi-touch device, they'll all have the same value.
These changes add some logic that attributes the events to the slider that started the dragging sequence.
**Note:** I haven't included unit tests for this, because we don't seem to have any tests for touch events on the slider (not sure if there are historical reasons for this). I've been testing the fix against a real touch device.
Fixes #22614.
=> fix(material/slider): incorrectly attributing touches for multiple touch events

src/material/checkbox/checkbox.html
Fixes that the checkbox doesn't disable its ripple animation when the noop animations module is enabled.
=> fix(material/checkbox): disable ripple animation under noop animations module

src/cdk/a11y/focus-trap/focus-trap.ts, src/cdk/platform/features/shadow-dom.ts, src/material/bottom-sheet/BUILD.bazel, src/material/bottom-sheet/bottom-sheet-container.ts, src/material/datepicker/BUILD.bazel, src/material/datepicker/datepicker-base.ts, src/material/dialog/BUILD.bazel, src/material/dialog/dialog-container.ts, tools/public_api_guard/cdk/a11y.d.ts, tools/public_api_guard/cdk/platform.d.ts
Based on a discussion on an earlier PR, these changes move the logic for resolving the `activeElement` while piercing through the shadow DOM into a common helper. Furthermore, they expand the logic to pierce through multiple layers of shadow DOM.
=> refactor(cdk/platform): add common utility for resolving focused element

src/components-examples/material/input/input-clearable/input-clearable-example.html
Remove the extraneous `mat-button` directive.
=> docs: use icon button in input clear example

src/cdk/testing/change-detection.ts
The `parallel` function docs weren't showing up in the docs site, likely because the base signature didn't have a doc string.
Fixes #22013.
=> docs: add doc string to base signature of `parallel` function

src/components-examples/material/table/table-selection/table-selection-example.ts
The example label for the select all/deselect all checkbox is reversed.  The select all state is labeled "deselect all" and vice versa.  This will correct those labels.
=> docs(material/table): Correct checkbox label on select all checkbox

tools/dgeni/common/dgeni-definitions.ts, tools/dgeni/processors/merge-inherited-properties.ts, tools/dgeni/templates/method.template.html, tools/dgeni/templates/property.template.html
In #22482 some changes were made that switched the doc rendering from `description` to `content` in an attempt to expose the descriptions for inherited class members. It turns out that `content` is actually the description of the member including `@param` and `@returns` tags which we don't want to show either.
After some investigation, it turns out that the root cause of the descriptions not being shown is that dgeni won't assign a `description` if the base class isn't exported.
These changes resolve the issue by falling back to `content` if there is no `description` and stripping out the JSDoc tags from it manually.
=> docs: incorrect descriptions for inherited class members

src/material/core/ripple/ripple.ts
The doc string on `RippleGlobalOptions.animation` was incorrect, because the `matRippleAnimation` input takes precedence over the `NoopAnimationsModule`.
Fixes #21541.
=> docs: update documentation for `RippleGlobalOptions.animation`

src/components-examples/material/table/table-http/table-http-example.css, src/components-examples/material/table/table-http/table-http-example.ts
There are currently three issues with the `table-http-example`:
1. If a user hits the rate limit within this example, an overlay
will be displayed mentioning the rate limit issue. This overlay
intends to overlap the whole table, except for the paginator. Right
now this is broken as there is a minium height throwing off the
assumption that the paginator is at the bottom of the example.
2. If a user hits the rate limit, the paginator length is reset to
zero. This means that the user is unable to trigger new requests
as the previous/next page buttons become disabled.
3. Due to incorrect error handling, the observable will be
replaced by a new one that will always return an empty list.
The rate limit/API errors should be caught within the switch
map to not prevent future API requests on …
=> docs: improve API rate-limit error handling in table-http-example

src/material/core/core.md
This will allow us to publish a section on the docs site for `@angular/material/core`.
Related to #8790
=> docs(material/core): Add a brief overview that refers users to the API docs

package.json, packages.bzl, scripts/check-rollup-globals.ts, src/components-examples/material/paginator/BUILD.bazel, src/components-examples/material/paginator/index.ts, src/components-examples/material/paginator/paginator-intl/paginator-intl-example.html, src/components-examples/material/paginator/paginator-intl/paginator-intl-example.ts, src/components-examples/private/BUILD.bazel, src/components-examples/private/localize-types.d.ts, src/dev-app/BUILD.bazel, src/dev-app/main.ts, tools/system-config-tmpl.js, yarn.lock
Adds an example for providing a custom `MatPaginatorIntl`. The
example also show-cases the use with `@angular/localize`.
Fixes #8239.
=> docs: add example for providing custom `MatPaginatorIntl`

guides/theming-your-components.md
docs(material): Code specified in documentation will not compile
The code as written in step 4 won't compile, since $theme is not defined.
Should pass $my-theme instead.
=> Fixed incorrect theme variable used in theme file

src/material/input/input.ts
`MatInput` has a `keyup` listener which calls `setSelectionRange` in order to work around an issue in iOS. The problem is that some input types don't allow the selection range to be updated and they throw an error if somebody tries to do it.
These changes avoid the errors by detecting whether the input supports setting the selection range.
Fixes #22726.
=> fix(material/input): error for some input types on iOS

src/material/datepicker/datepicker-intl.ts
Fixes that the `aria-label` of the navigation buttons in the year view said "20 years", even though we're showing 24 years.
Fixes #22758.
=> fix(material/datepicker): incorrect year count in aria label

src/material/_index.scss
Fixes that the `typography-hierarchy` mixin wasn't exposed in the new theming index file.
Fixes #22737.
=> fix(material/core): typography-hierarchy mixin not exposed

src/material-experimental/mdc-slider/slider.scss, src/material-experimental/mdc-slider/slider.ts
Fixes that the MDC-based slider wasn't disabling its animations when noop animations are enabled.
Also removes some unused styles.
=> fix(material-experimental/mdc-slider): disable animations when noop module is included

src/material/core/BUILD.bazel
I forgot to make this change in #22773, so the new overview isn't currently being outputted in the docs content package
=> build: build the core overview file as part of the docs content

tools/dgeni/processors/categorizer.ts, tools/dgeni/templates/method.template.html, tools/dgeni/templates/property.template.html
Exposes information about static members/properties in the API docs.
Fixes #20270.
=> build: expose static methods and properties in docs

src/components-examples/material/table/index.ts, src/components-examples/material/table/table-column-styling/table-column-styling-example.css, src/components-examples/material/table/table-column-styling/table-column-styling-example.html, src/components-examples/material/table/table-column-styling/table-column-styling-example.ts, src/components-examples/material/table/table-row-binding/table-row-binding-example.css, src/components-examples/material/table/table-row-binding/table-row-binding-example.html, src/components-examples/material/table/table-row-binding/table-row-binding-example.ts, src/material/table/table.md
Fixes #9697
TableColumnStylingExample: https://stackblitz.com/edit/angular-ytf7dh?file=src/app/table-basic-example.css
TableRowBindingExample: https://stackblitz.com/edit/angular-bjscs4?file=src%2Fapp%2Ftable-basic-example.ts
=> docs(material/table): add docs on row/column styles and bindings

src/components-examples/material/form-field/form-field-prefix-suffix/form-field-prefix-suffix-example.html
https://github.com/angular/components/issues/21846
Note: MDC form field should hide text prefix/suffix when label is floating
=> docs(material/form-field): add placeholder to prefix/suffix example for better alignment

src/material-experimental/_index.scss, src/material-experimental/mdc-button/README.md
* Fixes that the MDC slider wasn't exposing its theming mixins publicly.
* Updates the docs for the MDC button to the new theming API.
=> fix(material-experimental/mdc-slider): expose theming mixins

src/components-examples/material/table/table-footer-row/table-footer-row-example.ts, src/components-examples/material/table/table-http/table-http-example.css, src/components-examples/material/table/table-multiple-header-footer/table-multiple-header-footer-example.css, src/components-examples/material/table/table-multiple-header-footer/table-multiple-header-footer-example.ts, src/components-examples/material/table/table-overview/table-overview-example.html, src/components-examples/material/table/table-overview/table-overview-example.ts
Fixes https://github.com/angular/material.angular.io/issues/910
- Fix a11y contrast issues with examples with colors
- Fix import for https://stackblitz.com/angular/ayoxxodjkbl?file=src%2Fapp%2Ftable-multiple-header-footer-example.ts (can't import from other examples in stackblitz)
=> docs(material/table): fix table examples

src/material/input/input.md
=> docs(material/input): Add information about error messages and color to accessibility section

src/cdk/a11y/focus-monitor/focus-monitor.ts, src/cdk/a11y/input-modality/input-modality-detector.ts, tools/public_api_guard/cdk/a11y.d.ts
https://github.com/angular/components/pull/22489 purposefully introduced a regression into `FocusMonitor` when touch events are quickly followed by programmatic focus events (read the PR for more details). It was thought this regression was fine because (1) it allowed us to remove a bunch of specialized touch logic from `FocusMonitor`, (2) it allows us to easily integrate `InputModalityDetector`, and (3) we didn't believe that mixing up touch/program attribution was that big of a deal, as not many consumers would style things differently between the two cases.
It turns out that many components display focus overlays on program focus and not on touch focus (these are styles that are built-in to AM). This regression thus led to failures when testing in g3 where tests would open popups via …
=> fix(cdk/a11y): Fix the touch/program origin regression introduced in the recent FocusMonitor refactor.

src/components-examples/material/chips/BUILD.bazel, src/components-examples/material/chips/chips-form-control/chips-form-control-example.css, src/components-examples/material/chips/chips-form-control/chips-form-control-example.html, src/components-examples/material/chips/chips-form-control/chips-form-control-example.ts, src/components-examples/material/chips/index.ts
This clarifies how a chip-list can be used with a form control.
It highlights how a chip list can be disabled. The form control
is placed on the chip input is some cases while it should be
on the chip list, as otherwise the disabled styling does not
apply to the containing form field.
Fixes #19118.
=> docs: add example for using chip-list with form control

src/material/select/select.md
=> docs(material/select): clarify that `MatInputModule` is needed for `matNativeControl`

src/cdk/coercion/coercion.md
Companion PR to https://github.com/angular/material.angular.io/pull/994. Expands the overview of the coercion package so that we have more than one sentence to show.
=> docs(cdk/coercion): expand overview

src/cdk/scrolling/viewport-ruler.ts
=> docs(cdk/scrolling): note that ViewportRuler.change emits outside the zone

src/components-examples/material/form-field/form-field-harness/form-field-harness-example.html, src/material/form-field/form-field.md
=> docs(material/form-field): update documentation about the form-field appearances

tools/dgeni/common/private-docs.ts, tools/dgeni/processors/docs-private-filter.ts, tools/dgeni/templates/property.template.html
* Fixes that there's no space between `static` and the property name.
* Filters out the `ngAcceptInputType_` properties from the docs.
Fixes #22816.
=> build: fix formatting for static properties and filter out coercion members

src/components-examples/material/table/table-generated-columns/table-generated-columns-example.html
Fix table example that is mixing the table and flex table selectors plus using cdk instead of mat - switch to use the native table selectors
=> docs(material/table): fix table example tags

src/cdk/layout/layout.md
I'm copying the actual breakpoints here for reference because it's much
easier to parse than looking at the archived Material Design site.
I'm also working on a follow-up to add an overview example for
`BreakpointObserver`.
Fixes #11788
=> docs(cdk/layout): better explain how layout breakpoints work

src/cdk/a11y/_index.scss, src/cdk/overlay/_index.scss, src/material/core/theming/_theming.scss, src/material/core/typography/_typography-utils.scss, src/material/core/typography/_typography.scss
This adds "correct" SassDoc for the core theming APIs, including
parameters and return values with types.
It doesn't look like either WebStorm or VS Code actually _support_
SassDoc, but this at least makes our source a bit more documented.
=> docs(material/theming): add SassDoc for public theming APIs

src/material/core/ripple/ripple.ts
It was never clearly specified whether the coordinates for `MatRipple.launch`
should be relative to the trigger, ripple container or viewport, or even absolute.
This commit clarifies this by explicitly mentioning the viewport.
Fixes #16613.
=> docs: clarify coordinate parameters for `MatRipple.launch` method.

src/material/datepicker/datepicker.md
Clarifies that the moment date adapter lives in its own npm package.
Also removes language about _recommending_ the moment adapter.
Fixes #18539
=> docs(material/datepicker): clarify moment adapter package

.github/CODEOWNERS, src/cdk/layout/layout.md, src/components-examples/BUILD.bazel, src/components-examples/cdk/layout/BUILD.bazel, src/components-examples/cdk/layout/breakpoint-observer-overview/breakpoint-observer-overview-example.css, src/components-examples/cdk/layout/breakpoint-observer-overview/breakpoint-observer-overview-example.html, src/components-examples/cdk/layout/breakpoint-observer-overview/breakpoint-observer-overview-example.ts, src/components-examples/cdk/layout/index.ts, src/dev-app/BUILD.bazel, src/dev-app/dev-app/dev-app-layout.ts, src/dev-app/dev-app/routes.ts, src/dev-app/layout/BUILD.bazel, src/dev-app/layout/layout-demo-module.ts, src/dev-app/layout/layout-demo.html, src/dev-app/layout/layout-demo.ts
Also adds a layout page to the dev-app since it didn't have one
=> docs(cdk/layout): add BreakpointObserver example

src/material/snack-bar/snack-bar.spec.ts
- Refactor variables in snack-bar component unit tests to have constant type instead of let as this variables are not getting re-initialize during the test life-time.
- All tests within a spec should be consistent with all other tests in file.
=> refactor(material/snack-bar): refactor variable type to const in snack-bar component unit tests

src/material-experimental/mdc-table/table.scss
MDC explicitly sets a color on the header cells - this aligns all cells to be inheriting from the table element itself (which uses background card by default)
=> fix(material-experimental/mdc-table): add background inherit to header cells

src/material/slider/slider.spec.ts
- Refactor variables in slider component unit tests to have constant type instead of let as this variables are not getting re-initialize during the test life-time.
- All tests within a spec should be consistent with all other tests in file.
=> refactor(material/slider): refactor variable type to const in slider component unit tests

src/material/progress-spinner/progress-spinner.spec.ts
- Refactor variables in progressive-spinner component unit tests to have constant type instead of let as this variables are not getting re-initialize during the test life-time.
- All tests within a spec should be consistent with all other tests in file.
=> refactor(material/progress-spinner): refactor variable type to const in progress-spinner component unit tests

src/material-experimental/mdc-autocomplete/autocomplete.ts, src/material/autocomplete/autocomplete.ts
Currently the `options` and `optionGroups` properties are showing up
in the docs even though they are marked as `@docs-private` in the
base class. This happens because they are declared in the derived
autocomplete implementations (both non-MDC and MDC). Given these
properties not being prefixed with an underscore anyway, we should
start documenting these.
=> docs(material/autocomplete): add descriptions for properties showing up in API docs

src/material/button-toggle/button-toggle.ts
Developers can specify a default appearance for button toggles
using the `MatButtonToggleDefaultOptions`. The appearance property
within these default options is not documented. This commit adds
a description.
=> docs(material/button-toggle): add description for appearance property in default options

src/material/checkbox/checkbox-config.ts
Developers can specify a color, or click action for all checkboxes using
`MatCheckboxDefaultOptions`. The properties for the default options are
currently not documented. This commit adds the missing descriptions.
=> docs(material/checkbox): add description for properties in default options

src/components-examples/material/stepper/stepper-editable/stepper-editable-example.html, src/components-examples/material/stepper/stepper-errors/stepper-errors-example.html, src/components-examples/material/stepper/stepper-harness/stepper-harness-example.html, src/components-examples/material/stepper/stepper-intl/stepper-intl-example.html, src/components-examples/material/stepper/stepper-label-position-bottom/stepper-label-position-bottom-example.html, src/components-examples/material/stepper/stepper-lazy-content/stepper-lazy-content-example.html, src/components-examples/material/stepper/stepper-optional/stepper-optional-example.html, src/components-examples/material/stepper/stepper-overview/stepper-overview-example.html, src/components-examples/material/stepper/stepper-states/stepper-states-example.html, src/components-examples/material/stepper/stepper-vertical/stepper-vertical-example.html, src/dev-app/stepper/stepper-demo.html, src/material/input/input.spec.ts, src/material/stepper/stepper.e2e.spec.ts, src/material/stepper/stepper.md, src/material/stepper/stepper.spec.ts, src/material/stepper/testing/shared.spec.ts, src/universal-app/kitchen-sink/kitchen-sink.html
The `mat-horizontal-stepper` and `mat-vertical-stepper` were deprecated after we introduced the `orientation` input on `mat-stepper`. These changes update all docs and tests to use the new approach.
=> refactor(material/stepper): remove all usages of deprecated selectors

src/material/dialog/dialog-content-directives.ts, src/material/dialog/dialog-ref.ts, tools/public_api_guard/material/dialog.d.ts
Adds descriptions for public properties showing up in the
API docs. Deprecates the `dialogRef` member of `MatDialogClose`.
All other content directives do not expose the dialog ref, and users
should just inject the `MatDialogRef` if needed, instead of accessing
it through a `MatDialogClose` instance.
DEPRECATED: `MatDialogClose#dialogRef` class member to become private.
=> docs(material/dialog): add missing descriptions

src/cdk/accordion/BUILD.bazel, src/cdk/accordion/accordion.md, src/components-examples/BUILD.bazel, src/components-examples/cdk/accordion/BUILD.bazel, src/components-examples/cdk/accordion/cdk-accordion-overview/cdk-accordion-overview-example.css, src/components-examples/cdk/accordion/cdk-accordion-overview/cdk-accordion-overview-example.html, src/components-examples/cdk/accordion/cdk-accordion-overview/cdk-accordion-overview-example.ts, src/components-examples/cdk/accordion/index.ts
Adds an overview doc for the `cdk/accordion` package, including a sample implementation of an accordion using the CDK.
Fixes #14298.
=> docs(cdk/accordion): add overview

tools/dgeni/templates/entry-point.template.html
Currently we show something like `import {} from '@angular/cdk/coercion'` for imports that don't have a primary export. These changes remove the line if there is no primary export.
=> build: don't show import path if there is no primary export

src/material/form-field/form-field.ts, tools/public_api_guard/material/form-field.d.ts
With the recent changes to the mixins, a typo has sneaked into the
form-field mixin logic. This commit fixes that.
=> refactor(material/form-field): fix incorrectly named mixin base constant

src/material-experimental/mdc-radio/radio.ts, src/material/radio/radio.html, src/material/radio/radio.ts, tools/public_api_guard/material/radio.d.ts
Fixes that we weren't disabling the radio button ripples when the `NoopAnimationsModule` is used.
=> fix(material/radio): disable ripples under noop animations module

src/material/schematics/ng-update/migrations/theming-api-v12/migration.ts, src/material/schematics/ng-update/test-cases/v12/misc/theming-api-v12.spec.ts
In the case where a file has mixed legacy and new theming API usage, the script would
add an extra duplicate `@use` statement.
=> fix(material/schematics): don't insert duplicate `@use` statements in themingApi

src/material/slider/slider.spec.ts, src/material/slider/slider.ts, tools/public_api_guard/material/slider.d.ts
The slider is currently set up to "slide" either with the keyboard or the pointer, but we don't dinstinguish between the two. This means that when a `keyup` fires, it'll interrupt pointer scrolling as well.
These changes add some logic to prevent the two from interfering with each other.
Fixes #22719.
=> fix(material/slider): don't interrupt pointer dragging when keyboard is pressed

src/material-experimental/mdc-button/_button-base.scss, src/material-experimental/mdc-button/button.html, src/material-experimental/mdc-button/button.scss, src/material-experimental/mdc-button/fab.scss, src/material-experimental/mdc-button/icon-button.scss
Adds some styles to ensure that the MDC-based button always has a touch target of at least 48px. Note that I decided against using MDC's built-in touch target class, because it would've added a margin on the button host node.
Fixes #22799.
For reference, here's what the touch targets look like at different densities:
=> fix(material-experimental/mdc-button): set proper touch target

package.json, packages.bzl, yarn.lock
The Angular framework dependencies will soon start to use
tslib 2.2.0 as dependency. We want to also update our
dependencies to tslib v2.2.0 as otherwise multiple versions
of tslib would end up in application bundles. The v2.2.0
version of tslib is backwards compatible, so we can update
even though we do not use TS 4.3 in the project yet.
=> build: update to tslib 2.2.0

tools/dgeni/common/class-inheritance.ts, tools/dgeni/common/private-docs.ts, tools/dgeni/docs-package.ts, tools/dgeni/processors/entry-point-grouper.ts, tools/dgeni/processors/merge-inherited-properties.ts, tools/dgeni/processors/resolve-inherited-docs.ts
We recently landed a couple of improvements in the Dgeni pipeline, so
that descriptions of inherited members show up. To achieve this, we
applied a workaround that basically meant we are parsing the API docs'
string content manually to a JSDoc description (this also involved
manually stripping any JSDoc annotations).
This commit replaces the workaround with a solution that allows us
to still run necessary default Dgeni processors on the inherited API
docs, such as the offical `jsdoc` processors. These solve the problem
of manually extracting the JSDoc description, and also fix more
down-the-line problems where e.g. `@docs-private` is not respected
for inherited members. It also fixes cases where the JSDoc annotations
are still showing up in the docs.
=> docs: fix inherited docs-private members showing up

src/material/button/button.spec.ts
- Refactor variables in button component unit tests to have constant type instead of let as this variables are not getting re-initialize during the test life-time.
- All tests within a spec should be consistent with all other tests in file.
-  Refactor variable name as per best coding practices.
=> test(material/button): refactor variable type to const in button component unit tests

src/material/button-toggle/button-toggle.spec.ts
- Refactor variables in button-toggle component unit tests to have constant type instead of let as this variables are not getting re-initialize during the test life-time.
=> test(material/button-toggle): refactor variable type to const in button-toggle component unit tests

src/material/checkbox/checkbox.spec.ts
- Refactor variables in checkbox component unit tests to have constant type instead of let as this variables are not getting re-initialize during the test life-time.
=> test(material/checkbox): refactor variable type to const in checkbox component unit tests

guides/duplicate-theming-styles.md
Updates the duplicate theme guide to use the new Sass API.
Fixes #22857.
=> docs: switch duplicate theme guide to new API

src/material/chips/chip-input.spec.ts, src/material/chips/chip-list.spec.ts, src/material/chips/chip-remove.spec.ts
- Refactor variables in chips component unit tests to have constant type instead of let as this variables are not getting re-initialize during the test life-time.
=> test(material/chips): refactor variable type to const in chips component unit tests

src/material-experimental/mdc-input/input.spec.ts, src/material-experimental/mdc-input/input.ts, src/material/input/input.spec.ts, src/material/input/input.ts
Updates the logic for setting `aria-invalid` on `matInput` to not set
the attribute at all if the input is `required` and has no value.
Prior to this PR `matInput` sets `aria-invalid="false"` for any empty
`matInput`, including `required` ones.  This suppresses screen readers'
announcement to users that such inputs are in an invalid state.
Fixes #22777
=> fix(material/input): Do not set `aria-invalid` on empty`matInput`s

src/material-experimental/mdc-menu/menu.spec.ts, src/material/menu/menu.spec.ts, src/material/menu/menu.ts
For historical reasons, `mat-menu` doesn't use the same keyboard event dispatcher as the other overlays. To work around it, previously we added a dummy subscription so that the menu would still show up in the overlay keyboard stack.
This works for most events, but it breaks down for the escape key, because closing the menu removes it from the stack immediately, allowing the event to bubble up to the document and be dispatched to the next overlay in the stack.
These changes resolve the issue by adding a `stopPropagation` call.
Fixes #22694.
=> fix(material/menu): not interrupting keyboard events to other overlays

src/material-experimental/mdc-menu/menu.spec.ts, src/material/menu/menu.spec.ts, src/material/menu/menu.ts
This reverts commit aeecb3ccbde1e679766c7bcc2ba4b2e483c27ac2.
Unfortunately this broke an obscure test that may be difficult to debug. The test appeared as passing because it was already failing at the time we tested.
=> Revert "fix(material/menu): not interrupting keyboard events to other overlays

src/material-experimental/mdc-button/_button-base.scss, src/material-experimental/mdc-button/button.html, src/material-experimental/mdc-button/button.scss, src/material-experimental/mdc-button/fab.scss, src/material-experimental/mdc-button/icon-button.scss
This reverts commit 793e1f1310c0d5e38d7fb0766d07292c1ed83522.
This has to be reverted from Google because the RTL icon buttons are breaking layout. See screenshot where there an outline around the touch targets.
Looks like we need to switch the transform to `transform: translate(50%, -50%)` in RTL
=> Revert "fix(material-experimental/mdc-button): set proper touch target

src/material-experimental/mdc-chips/chip-input.spec.ts, src/material/chips/chip-input.spec.ts
In 'MatChipInput' test, `MatInputModule` was not imported and therefore the `matInput` directive was not interpreted.
If importing `MatInputModule` into the testing module, the `matInput` directive gets applied and the test '_MatChipInput basic behavior should be aria-required if the list is required_' would fail because of side effects by setting the `aria-required`  attribute. Obviously, `matInput` does not remove the `aria-required` attribute, while the chips implementation is doing so (chips is interpreting false as null, while `matInput` leaves 'false' as-is).
=> test(material/chips): prevent unintentional test success

src/material/autocomplete/autocomplete.spec.ts
- Refactor variables in autocomplete component unit tests to have constant type instead of let as this variables are not getting re-initialize during the test life-time.
=> test(material/autocomplete): refactor variable type to const in autocomplete component unit tests

src/material-experimental/mdc-tabs/_tabs-common.scss
Fixes an issue where, in some cases, the load order can re-enable the ink bar animation that was disabled via the `NoopAnimationsModule`. This is noticeable by landing on the MDC input demo page with disabled animations and navigating to the MDC tabs demo page.
The issue seems to be caused by the fact that the two demos are in separate modules which causes Angular to insert the tab styles again when the user switches between them. Since the styles that disable the animation had the same specificity as the animation definition, swapping the loading order could cause them to be overwritten.
=> fix(material-experimental/mdc-tabs): ink bar animation not always disabled

src/material-experimental/mdc-slider/testing/slider-harness.spec.ts, src/material-experimental/mdc-slider/testing/slider-thumb-harness.ts
* delete the isRequired function from the MatSliderThumbHarness since
the 'required' attribute is ignored on range inputs
=> fix(material-experimental/mdc-slider): delete isRequired function

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/drag-ref.ts
When an item enters a new drop container, we dispatch an event and run some logic afterwards. The problem is that if the item is destroyed as a result of the event, the logic after the event will throw because dragging was interrupted.
Also fixes that `isDragging` returns `boolean | undefined` rather than the specified `boolean`.
Fixes #22813.
=> fix(cdk/drag-drop): error if dragged item is destroyed as a result of the `entered` event

src/material/slider/slider.ts, tools/public_api_guard/material/slider.d.ts
Makes the value of the slider a `number`, rather than `number | null` in order to make it easier to use.
Fixes #22444.
=> fix(material/slider): make value non-nullable

src/material-experimental/mdc-slider/slider.ts
* Delete the unused 'change' and 'input' event emitters.
=> fix(material-experimental/mdc-slider): remove unused event emitters

src/cdk-experimental/dialog/dialog.ts, src/material/bottom-sheet/bottom-sheet.ts, src/material/dialog/dialog.ts
Fixes a few more cases like #22665 where we were injecting something optionally, but we weren't passing the optional injector flag.
=> fix(multiple): add inject flags to manual injector calls

src/cdk/overlay/overlay-container.ts
We have some logic in the overlay container that tries to prevent overlays from leaking between tests. The logic is currently limited to Jasmine tests and it happened to work by accident for Jest. Jest has made some changes that will break our check so these changes rework the logic to detect Jest and Mocha correctly.
Fixes #22926.
=> fix(cdk/overlay): expand test environment check

src/material-experimental/mdc-slide-toggle/slide-toggle.scss
Increases the contrast of disabled slide toggles in high contrast mode make them easier to see.
Fixes #22941.
=> fix(material-experimental/mdc-slide-toggle): increase contrast in high contrast mode

WORKSPACE
We no longer use any browsers from `rules_webtesting`, so
the TODO in the `WORKSPACE` file is outdated. This commit
removes the comment.
=> build: remove outdated todo from bazel workspace file

src/cdk/schematics/migration.json, src/cdk/schematics/ng-update/index.ts, src/cdk/schematics/update-tool/target-version.ts, src/material/schematics/migration.json, src/material/schematics/ng-update/index.ts
Sets up the boilerplate for v13 schematics so that it's in place once we start making breaking changes.
=> build: set up schematics for v13

src/material/dialog/dialog.spec.ts, src/material/icon/icon.spec.ts, src/material/input/input.spec.ts, src/material/menu/menu.spec.ts, src/material/radio/radio.spec.ts, src/material/select/select.spec.ts, src/material/sidenav/drawer.spec.ts
- Refactor variables in various component unit tests to have constant type instead of let as this variables are not getting re-initialize during the test life-time.
- Added type annotations to variables instead of any.
- Renamed variables.
=> test(multiple): refactor unit tests of several components

src/dev-app/BUILD.bazel, tools/es5-module-output.bzl
The `@angular/localize` package does not contain any `.metadata.json`
files, or an `ANGULAR_PACKAGE` marker file. This results in the NodeJS
bazel rules not capturing the UMD files within the `NamedModule` provider.
We fix this by using the standard module provider for extracting JS
sources from TS targets and its transitive dependencies. This is more
long-term proof as the hard-coded Angular package logic within Rules
NodeJS is most likely not a long-term solution.
see: https://github.com/bazelbuild/rules_nodejs/blob/stable/internal/npm_install/generate_build_file.ts#L1080-L1081
Fixes #22943.
=> build: fix firebase deployment of dev-app

src/material-experimental/mdc-checkbox/checkbox.html, src/material-experimental/mdc-checkbox/checkbox.scss
Sets up a larger touch target for checkboxes in order to meet the 48px minimum.
=> fix(material-experimental/mdc-checkbox): add larger touch target

src/material-experimental/mdc-slider/testing/slider-harness.spec.ts, src/material-experimental/mdc-slider/testing/slider-harness.ts, src/material-experimental/mdc-slider/testing/slider-thumb-harness.ts
Currently the test harness for a thumb assumes that its direction is `start` unless explicitly specified. This is incosistent with the component itself which assues the opposite.
=> fix(material-experimental/mdc-slider): align test harness inferred position with component

src/cdk/schematics/ng-update/devkit-file-system.ts, src/cdk/schematics/ng-update/test-cases/misc/module-resolution.spec.ts, src/cdk/schematics/update-tool/component-resource-collector.ts, src/cdk/schematics/update-tool/file-system.ts, src/cdk/schematics/update-tool/utils/virtual-host.ts, src/material/schematics/ng-update/migrations/hammer-gestures-v9/hammer-gestures-migration.ts
TypeScript resolves modules using a rather complicated module
resolution algorithm. The algorithm tries various paths to
determine a possible entry-point for a module. e.g. it also
respects a containing `package.json` file, or respects the closest
`node_modules` parent directory.
In some situations, TypeScript could end up trying a path where
a parent directory segment resolves to an existent file. e.g.
consider the following directory structure:
```
node_modules/my-pkg/package.json
node_modules/my-pkg/styles.css
```
TypeScript could end up trying paths like: `node_modules/my-pkg/styles.css/package.json` or
`node_modules/my-pkg/styles.css/a/b/package.json`. This depends on how
the module resolution executes, and how the module is referenced.
In the example above though, TypeScript checks …
=> fix(cdk/schematics): avoid runtime errors thrown by devkit tree when TypeScript tries non-existent path

src/material/badge/_badge-theme.scss, tools/stylelint/no-ampersand-beyond-selector-start.ts
I noticed this while working on something else. The ampersand selector mixin looks for one `&` instance and then gives up, but there might be other ampersands inside the same selector which are invalid.
These changes update the logic to be a bit more robust and remove the limitation where failures weren't reported on private mixins.
=> build: ampersand selector lint rule not catching some cases

src/material/bottom-sheet/bottom-sheet.spec.ts
- Refactor variables in bottom-sheet component unit tests to have constant type instead of let as this variables are not getting re-initialize during the test life-time.
=> test(material/bottom-sheet): refactor variable type to const in bottom-sheet component unit tests

src/material-experimental/mdc-snack-bar/_snack-bar-theme.scss
Currently the order of the button theme vs the snackbar theme matters,
this will make the snackbar theme always take precedence
=> fix(material-experimental/mdc-snack-bar): increase the specificity of styles targeting the action buttons

src/cdk/scrolling/fixed-size-virtual-scroll.ts, src/cdk/scrolling/scrolling.md, src/cdk/scrolling/virtual-scroll-viewport.spec.ts, src/cdk/scrolling/virtual-scroll-viewport.ts, src/components-examples/cdk/scrolling/cdk-virtual-scroll-append-only/cdk-virtual-scroll-append-only-example.css, src/components-examples/cdk/scrolling/cdk-virtual-scroll-append-only/cdk-virtual-scroll-append-only-example.html, src/components-examples/cdk/scrolling/cdk-virtual-scroll-append-only/cdk-virtual-scroll-append-only-example.ts, src/components-examples/cdk/scrolling/index.ts, src/dev-app/virtual-scroll/virtual-scroll-demo.html, tools/public_api_guard/cdk/scrolling.d.ts
This PR adds an `appendOnly` input to `cdk-virtual-scroll-viewport`, which disables view recycling so items remain in the DOM even after they scroll out of view. This can be more performant for scroll viewports that render complex components that may be expensive to remove or insert at the beginning of the list while scrolling up.
- Should the viewport throw if `appendOnly` changes after initialization? For example, if a user scrolls to the bottom of a list containing 2k items, then enables `appendOnly`, the viewport will render all 2k items.
=> feat(cdk/scrolling): add input to enable append-only mode in virtual scroll viewport

src/material/datepicker/calendar.ts
TypeScript inferred the return type of `_getCurrentViewComponent` as the type of the month view only. Tsickle propagates that to the JavaScript compiler which optimizes the code as `monthView._init` was the only method that could be called. This causes runtime errors.
Fixed #22996
=> fix(material/datepicker): Return union of view component types

src/components-examples/material/chips/chips-form-control/chips-form-control-example.html, src/components-examples/material/chips/chips-form-control/chips-form-control-example.ts
We recently added an example for chips with a form control. This example
should clarify how the chip list can interact with a form control.
It seems like it is not quite clear what value the form control
represents, or how a chip can be "selected". This has been improved
as per this commit.
Fixes #22933.
=> docs: clarify value of the form control in the chips-form-control example

src/components-examples/material/paginator/paginator-intl/paginator-intl-example.html
We recently added a new example for paginator with internationalization.
For testing, the paginator has been set to `length = 0`. The example
paginator should have some items so that the various labels can be
seen in the paginator (currently there are no pages to iterate through).
=> docs: improve paginator-intl example

src/cdk/schematics/ng-update/test-cases/misc/module-resolution.spec.ts, src/material/schematics/ng-update/test-cases/misc/class-inheritance.spec.ts, src/material/schematics/ng-update/test-cases/v12/misc/theming-api-v12.spec.ts, src/material/schematics/ng-update/test-cases/v9/misc/hammer-migration-v9.spec.ts, src/material/schematics/ng-update/test-cases/v9/misc/material-imports.spec.ts, tsconfig.json, tslint.json
The linting setup was excluding all of the code under `schematics/test-cases`, however we only need to do it for the `_input` and `_expected_output` files.
These changes allow the files to be linted and fixes some errors that went undetected.
=> build: allow for some schematics code to be linted

src/material-experimental/mdc-tooltip/tooltip.ts
…satisfy noImplicitOverride
Given we merged the `noImplicitOverride` PR together with a couple of
other PRs, new methods could have been introduced that did not use
the `override` keyword. This is the case for the MDC tooltip `_onShow`
method. This commit adds the necessary `override` keyword.
=> refactor(material-experimental/mdc-tooltip): add override keyword to satisfy noImplicitOverride check

src/material-experimental/mdc-helpers/_focus-indicators-theme.scss, src/material-experimental/mdc-helpers/_focus-indicators.import.scss, src/material/core/focus-indicators/_focus-indicators-theme.scss, src/material/core/focus-indicators/_focus-indicators.import.scss
As described in https://material.angular.io/guide/theming#customizing-strong-focus-indicators, the focus indicator theme and color mixins should allow the user to pass in a basic CSS color. This PR updates the mixins to allow this.
Alternatively, we could update the documentation to disallow this. I disabled the stylelint checks for these mixins because their new implementations aren't compatible with the checks.
=> fix(material/core): Focus indicator theme and color mixins should accept a basic color as well.

src/material/datepicker/calendar-body.ts, src/material/datepicker/calendar.scss, src/material/datepicker/month-view.html, src/material/datepicker/month-view.spec.ts, src/material/datepicker/multi-year-view.html, src/material/datepicker/multi-year-view.spec.ts, src/material/datepicker/year-view.html, src/material/datepicker/year-view.spec.ts
Previously, the grid in mat-datepicker was not strictly following the structure expected for the grid role. Additionally, this change adds an `<abbr>` element to the column headers such that VoiceOver can correctly read column headers.
Fixes #21357
=> fix(material/datepicker): correct structure for grid role

src/material-experimental/mdc-checkbox/_checkbox-theme.scss, src/material-experimental/mdc-radio/_radio-theme.scss, src/material-experimental/mdc-radio/radio.html, src/material-experimental/mdc-radio/radio.scss, src/material/radio/radio.html, src/material/radio/radio.ts, tools/public_api_guard/material/radio.d.ts
Sets up accessible touch targets on the MDC-based radio button.
Also hides the touch targets on the two lowest densities. This is something I forgot to do in #22892.
Fixes #22991.
=> fix(material-experimental/mdc-radio): add accessible touch targets

src/material/datepicker/date-range-input.ts
We were missing the `mat-mdc-form-field-control` class on the date range input which caused its start input to disappear, because it didn't have a line height.
=> fix(material/datepicker): incorrect appearance when used in MDC form field

src/material/schematics/ng-update/migrations/theming-api-v12/migration.ts, src/material/schematics/ng-update/test-cases/v12/misc/theming-api-v12.spec.ts
Adds some logic that escapes comments so that the theming API migration doesn't pick them up.
=> fix(material/schematics): don't migrate commented code in theming API migration

src/material-experimental/mdc-menu/_menu-theme.scss, src/material-experimental/mdc-menu/menu-item.html, src/material-experimental/mdc-menu/menu.scss, src/material-experimental/mdc-menu/menu.spec.ts, src/material/core/style/_menu-common.scss, src/material/menu/_menu-theme.scss, src/material/menu/menu-item.html, src/material/menu/menu.scss, src/material/menu/menu.spec.ts
Currently the submenu icon is rendered as a CSS triangle which turns into a rectangle in high contrast mode. These changes resolve the issue by using SVG for the icon instead.
Fixes #22944.
=> fix(material/menu): submenu icon not working in high contrast mode

src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.spec.ts, src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.ts, src/material/tabs/tab-nav-bar/tab-nav-bar.spec.ts, src/material/tabs/tab-nav-bar/tab-nav-bar.ts, tools/public_api_guard/material/tabs.d.ts
The tab nav bar allows navigation both through tabbing and keyboard events. This introduces a problem when the user tabs into it and then starts using the arrow keys, because the `ListKeyManager` state isn't up-to-date.
These changes add some logic to update the index when the tabs receives focus.
Fixes #22576.
=> fix(material/tabs): update tab nav bar focused index on direct focus

src/material/slide-toggle/slide-toggle.scss
Since checkbox labels aren't user-selectable, I've thought it would be a more consistent behavior if slide toggles aren't either.
=> Made slide-toggle label non user selectable

src/dev-app/google-map/google-map-demo.html, src/dev-app/google-map/google-map-demo.ts, src/google-maps/google-map/google-map.spec.ts, src/google-maps/google-map/google-map.ts, tools/public_api_guard/google-maps/google-maps.d.ts
Emit event from the `GoogleMap` component when the `gm_authFailure` callback is called.
Fixes #22163
=> feat(google-maps): add event emitter for gm_authFailure callback

src/material/core/common-behaviors/error-state.ts
This is the first commit from https://github.com/angular/components/pull/22875 so that we can fix the missing documentation without introducing a "technically" breaking change. The other PR will remain open for discussion & potentially for a new major if we agree on changing how `stateChanges` is defined.
=> docs: add missing documentation for error state properties

src/material/badge/_badge-theme.scss
The badge structural styles are currently in the theme, because the badge is a directive and Angular doesn't support associating styles with directives. The problem is that it'll cause the same structural styles to be emitted multiple times unnecessarily.
These changes add some logic that will try to prevent the structural styles from being emitted more than once.
**Disclaimer:** this change might not work across multiple compilation units, however I still think it's worthwhile, because the apps that only have one global stylesheet for their theme will get the benefit, while everybody else will work the same as before. These changes shave off more than 4kb of minified CSS.
=> fix(material/badge): avoid emitting the structural styles more than once

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/drag-drop-registry.spec.ts, src/cdk/drag-drop/drag-drop-registry.ts, src/cdk/drag-drop/drag-ref.ts, src/cdk/drag-drop/drop-list-ref.ts, src/cdk/drag-drop/parent-position-tracker.ts, tools/public_api_guard/cdk/drag-drop.d.ts
The `drag-drop` module depends on a single document-level `scroll` listener in order to adjust itself when the page or an element is scrolled. The problem is that the events won't be picked up if they come from inside a shadow root.
These changes add some logic to bind an extra event at the shadow root level. Furthermore, they fix several places where we were reading the `Event.target` while not accounting for shadow DOM.
Fixes #22939.
=> fix(cdk/drag-drop): resolve various event tracking issues inside the shadow dom

tools/system-config-tmpl.js
Fixes that the datepicker live examples didn't load locally, because there were some 404s for the Moment locale files.
=> build: datepicker examples not working locally

src/cdk/a11y/input-modality/input-modality-detector.spec.ts
Currently the `InputModalityChecker` tests construct the object manually which is brittle. These changes switch using DI to construct it automatically.
=> test(cdk/a11y): use DI to construct modality checker

src/material-experimental/mdc-autocomplete/_autocomplete-theme.scss, src/material-experimental/mdc-autocomplete/autocomplete.scss, src/material-experimental/mdc-autocomplete/autocomplete.spec.ts, src/material-experimental/mdc-core/option/_optgroup-theme.scss, src/material-experimental/mdc-core/option/_option-theme.scss, src/material-experimental/mdc-core/option/optgroup.html, src/material-experimental/mdc-core/option/optgroup.scss, src/material-experimental/mdc-core/option/option.html, src/material-experimental/mdc-core/option/option.scss, src/material-experimental/mdc-core/option/option.ts, src/material-experimental/mdc-core/testing/option-harness.ts, src/material-experimental/mdc-menu/_menu-theme.scss, src/material-experimental/mdc-menu/menu-item.html, src/material-experimental/mdc-menu/menu.html, src/material-experimental/mdc-menu/menu.scss, src/material-experimental/mdc-select/_select-theme.scss, src/material-experimental/mdc-select/select.scss, src/material-experimental/mdc-select/select.spec.ts
Switches the components in `mdc-autocomplete`, `mdc-core`, `mdc-menu` and `mdc-select` to the non-deprecated MDC list styles.
**Note for reviewer:** merging this is currently blocked, because it depends on one change that isn't in the latest canary version. Once the change is released, I'll bump the version and unblock merging. The code can still be reviewed.
=> refactor(multiple): switch to non-deprecated MDC list styles

src/material-experimental/mdc-menu/menu.scss
A couple of conflicting PRs were merged in at the same time which is causing a build error, because an import was removed.
=> build: fix wrong variable reference

.bazelrc
Update to use remote instance name, primary_instance, for RBE
=> build: update to new remote instance name for RBE

.bazelrc
Update to use remote instance name, primary_instance, for RBE
=> build: update to new remote instance name for RBE [11.2.x lts backport]

scripts/check-mdc-exports-config.ts
We had disabled the public API check on the MDC slider while it was being rewritten, but now it can be re-enabled.
=> build: enable public API verification on the MDC slider

src/cdk/stepper/BUILD.bazel, src/cdk/stepper/stepper.ts, src/material/stepper/BUILD.bazel, src/material/stepper/stepper.spec.ts, tools/public_api_guard/cdk/stepper.d.ts
The CDK stepper focus management checks against the document to find the focused element which won't work if the stepper is inside the shadow DOM. These changes use our shadow DOM helper to resolve the element instead.
=> fix(cdk/stepper): focus management not working with shadow dom encapsulation

src/cdk/overlay/overlay-container.ts
The previous approach of using `declare const` was causing collisions with the real test environment types inside Google.
=> fix(cdk/overlay): use interface for test environment globals

src/material/datepicker/calendar-body.scss
Fixes that the date ranges are invisible in high contrast mode.
Fixes #23034.
=> fix(material/datepicker): date ranges not visible in high contrast mode

src/material-experimental/mdc-slider/slider.ts
* Fixes that the `mouseenter` and `mouseleave` handlers on the slider were leaking. It was `Function.bind` returns a new function and we weren't passing the same function in when the component is destroyed.
* Fixes that slider was calling `unsubscribe` on subjects that belong to the slider thumbs. `Subject.unsubscribe` will drop all subscriptions to the observable, including ones that come from the outside. The correct thing to do is to either complete the observables or save a reference to the `Subscription` and call `unsubscribe` on it.
* Removes the `*Ctor` interfaces from the mixin class since it isn't necessary anymore.
=> fix(material-experimental/mdc-slider): event handling fixes and cleanup

src/cdk/drag-drop/directives/drag.spec.ts
A recent change (#23026) appears to have introduced flakiness in our unit tests on Firefox. These changes apply a similar workaround to some of the other scrolling tests.
=> test(cdk/drag-drop): avoid flakes in scrolling tests

src/material-experimental/mdc-slider/slider.ts
Noop animations shouldn't disable ripples completely, but rather make them appear immediately.
=> fix(material-experimental/mdc-slider): don't disable ripples for noop animations

src/material-experimental/mdc-chips/chip-input.spec.ts, src/material-experimental/mdc-chips/chip-input.ts
Adds missing 'required' attribute to chips input. Currently, chips add
'aria-required' only, which is for backwards compatibility.
The addision also fixes a bug for axe tests that check for the same
value fort 'required' and 'aria-required' attributes.
=> fix(material-experimental/mdc-chips): add 'required' to chips input

src/material-experimental/mdc-menu/BUILD.bazel, src/material-experimental/mdc-menu/menu-item.html, src/material-experimental/mdc-menu/menu-item.ts, src/material-experimental/mdc-menu/testing/BUILD.bazel
Aligns the timings for the MDC-based menu item with MDC.
=> fix(material-experimental/mdc-menu): align ripple timings with MDC

src/material-experimental/mdc-button/fab.scss
mdc-fab.extended_ was being called without a query meaning it brought in lots of additional overrides including typography making typography mixins for mdc-fabs ineffective.
=> Calling mdc-fab.extended_ with $mat-base-styles query by default.

package.json, yarn.lock
Fixes that we were depending on a few `next` versions of the build tooling.
=> build: use stable versions of a couple of build dependencies

src/material/datepicker/_datepicker-theme.scss, src/material/datepicker/calendar-header.html, src/material/datepicker/calendar.scss
Fixes that the calendar arrow was rendering as a rectangle in high contrast mode.
=> fix(material/datepicker): correctly render calendar arrow in high contrast mode

src/material-experimental/mdc-button/button.scss, src/material-experimental/mdc-button/fab.scss, src/material-experimental/mdc-button/icon-button.scss
Fixes that the MDC-based buttons weren't disabling their animations when noop animations are enabled.
=> fix(material-experimental/mdc-button): not disabling animations under noop animations module

src/cdk/a11y/fake-event-detection.ts, src/cdk/a11y/focus-monitor/focus-monitor.spec.ts, src/cdk/a11y/input-modality/input-modality-detector.spec.ts, src/cdk/testing/testbed/fake-events/event-objects.ts, src/material/core/ripple/ripple.spec.ts
Our approach to detecting fake `mousedown` events from screen readers doesn't appear to work with a recent version of NVDA. These changes switch to using `offsetX` and `offsetY` instead.
Fixes #22549.
=> fix(cdk/a11y): fake mousedown detection not working

src/material-experimental/mdc-form-field/BUILD.bazel, src/material-experimental/mdc-form-field/_form-field-density.scss, src/material-experimental/mdc-form-field/_form-field-high-contrast.scss, src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss, src/material-experimental/mdc-form-field/form-field.scss, src/material/form-field/form-field-fill.scss, src/material/form-field/form-field-outline.scss
Here are examples for the non-MDC form field:
**Not focused outline**
**Focused outline**
=> fix(material/form-field): missing focus indicator for outline appearance in high-contrast

src/cdk/testing/protractor/protractor-element.ts, src/cdk/testing/selenium-webdriver/selenium-web-driver-element.ts, src/cdk/testing/test-element.ts, src/cdk/testing/testbed/unit-test-element.ts, src/cdk/testing/tests/cross-environment.spec.ts, src/material-experimental/mdc-chips/testing/chip-input-harness.ts, src/material-experimental/mdc-slider/testing/slider-harness.ts, src/material-experimental/mdc-slider/testing/slider-thumb-harness.ts, src/material/autocomplete/testing/autocomplete-harness.ts, src/material/checkbox/testing/checkbox-harness.ts, src/material/datepicker/testing/datepicker-input-harness-base.ts, src/material/input/testing/input-harness.ts, src/material/input/testing/native-option-harness.ts, src/material/input/testing/native-select-harness.ts, src/material/radio/testing/radio-harness.ts, src/material/slide-toggle/testing/slide-toggle-harness.ts, tools/public_api_guard/cdk/testing-protractor.d.ts, tools/public_api_guard/cdk/testing-selenium-webdriver.d.ts, tools/public_api_guard/cdk/testing-testbed.d.ts, tools/public_api_guard/cdk/testing.d.ts
Allows for the return value of `TestElement.getProperty` to be typed strongly through a generic parameter.
=> fix(cdk/testing): strongly type return value of TestElement.getProperty

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/drag-ref.ts, src/cdk/drag-drop/drag-styling.ts
The Material table with sticky headers sets its `position` as `!important` which ends up overriding the dragging styles. These changes rework the internals to use `setProperty` instead of `element.style.position` which allows us to set the `position` as `!important` as well. It also has the advantage that we can write the properties as dash case, instead of having to guess whether the vendor-prefixed properties are camel case or pascal case.
Fixes #22781.
=> fix(cdk/drag-drop): avoid conflicts with sticky table headers

src/material-experimental/mdc-helpers/_focus-indicators.scss, src/material-experimental/mdc-slider/slider-thumb.html, src/material-experimental/mdc-slider/slider.spec.ts
Fixes that the MDC-based slider didn't have a strong focus indicator.
=> fix(material-experimental/mdc-slider): add strong focus indication

src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss
Fixes that the `color` type inputs didn't work due to a style override we had on top of MDC.
For reference:
=> fix(material-experimental/mdc-form-field): color inputs not working

src/material-experimental/mdc-slide-toggle/slide-toggle.html, src/material-experimental/mdc-slide-toggle/slide-toggle.spec.ts, src/material-experimental/mdc-slide-toggle/slide-toggle.ts, src/material/slide-toggle/slide-toggle.html, src/material/slide-toggle/slide-toggle.spec.ts, src/material/slide-toggle/slide-toggle.ts, tools/public_api_guard/material/slide-toggle.d.ts
Similarly to other input-based components, these changes add an `aria-describedby` input to the slide toggle.
Fixes #23094.
=> feat(material/slide-toggle): add aria-describedby input

src/material-experimental/mdc-menu/menu.scss
Fixes that we didn't have any styles that would differentiate a disabled item from an enabled one.
=> fix(material-experimental/mdc-menu): add disabled item styles

src/cdk-experimental/combobox/combobox.ts, src/cdk/a11y/focus-monitor/focus-monitor.ts, src/cdk/a11y/input-modality/input-modality-detector.ts, src/cdk/drag-drop/drag-ref.ts, src/cdk/drag-drop/parent-position-tracker.ts, src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.ts, src/cdk/platform/features/shadow-dom.ts, src/material/autocomplete/autocomplete-trigger.ts, tools/public_api_guard/cdk/platform.d.ts
We were repeating the logic for resolving the event target while accounting for shadow DOM in a few places. These changes add a common utility instead.
=> refactor(cdk/platform): add utility for resolving event targets in shadow dom

src/cdk/scrolling/viewport-ruler.ts
We don't need to re-measure the viewport any time it is resized, we just need to clear the cache so that it is re-measured next time somebody requests it.
=> perf(cdk/scrolling): don't re-measure viewport on resize

src/material-experimental/mdc-list/list-option.ts, src/material-experimental/mdc-list/selection-list.spec.ts, src/material/list/selection-list.spec.ts, src/material/list/selection-list.ts, tools/public_api_guard/material/list.d.ts
Adds support for two-way data binding on the `selected` property of `mat-list-option`.
Fixes #23122.
=> feat(material/list): support two-data binding on list option selected

src/cdk/drag-drop/drag-drop.md
There was a typo in the `cdkDragPreviewContainer` input name in the docs.
=> docs: fix typo in drag-drop docs

src/cdk/schematics/ng-update/devkit-migration-rule.ts, src/cdk/schematics/ng-update/html-parsing/elements.ts, src/cdk/schematics/ng-update/typescript/base-types.ts, src/cdk/schematics/tsconfig.json, src/cdk/schematics/update-tool/migration.ts, src/cdk/schematics/utils/build-component.ts, src/material/schematics/ng-update/migrations/hammer-gestures-v9/hammer-template-check.ts, src/material/schematics/tsconfig.json
Makes the schematics code compliant with the `strictFunctionTypes` compiler option.
=> build: enable strictFunctionTypes in schematics

scripts/check-mdc-exports-config.ts, scripts/check-mdc-exports.ts
Most of the exports we've excluded from the exports config are underscored APIs. These changes add an option that allows us to exclude exports based on on a regex and removes the underscored APIs from the config since they're private anyway.
=> build: clean up MDC exports config

src/components-examples/material/paginator/paginator-configurable/paginator-configurable-example.html, src/components-examples/material/paginator/paginator-harness/paginator-harness-example.html, src/components-examples/material/paginator/paginator-intl/paginator-intl-example.html, src/components-examples/material/paginator/paginator-overview/paginator-overview-example.html, src/components-examples/material/table/table-http/table-http-example.html, src/components-examples/material/table/table-overview/table-overview-example.html, src/components-examples/material/table/table-pagination/table-pagination-example.html, src/dev-app/mdc-paginator/mdc-paginator-demo.html, src/dev-app/paginator/paginator-demo.html, src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html.template, src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.html, src/universal-app/kitchen-sink/kitchen-sink.html
Under the Accessibility section of the mat-paginator it's written that
a `<mat-paginator>` must have an aria-label.
But actually none of the found examples does provide an aria-label.
https://github.com/angular/components/blob/master/src/material/paginator/paginator.md#accessibility
=> docs(material/paginator): add aria-label to `<mat-paginator>` usages

src/material-experimental/mdc-list/list-base.ts, src/material-experimental/mdc-list/list-option.scss, src/material-experimental/mdc-list/list-option.ts, src/material-experimental/mdc-list/list.ts
Fixes that the list animations weren't being disabled with the `NoopAnimationsModule`.
=> fix(material-experimental/mdc-list): support noop animations

src/components-examples/material/table/table-expandable-rows/table-expandable-rows-example.css, src/material-experimental/mdc-table/table.scss, src/material/table/_table-flex-styles.scss, src/material/table/_table-theme.scss, src/material/table/table.scss
In an earlier PR we switched the flex-based table styles to target the tag names, rather than classes in order to support flex tables in MDC. The problem with targeting tag names is that it doesn't allow our styles to be applied to other elements within the table. E.g. in #22349 the user isn't able to target the "no data" row.
These changes switch back to targeting classes and add some styles to prevent the flex-specific styles from bleeding into the table-based ones.
Fixes #22349.
=> fix(material/table): switch back to class-based styling for flex tables

src/cdk/table/cell.ts, src/cdk/table/table.spec.ts, src/cdk/table/table.ts, src/material-experimental/mdc-table/cell.ts
- remove setting role in mat-cell as it is already set in the cdk
- future: look into adding an option for `role="grid"` with appropriate keyboard interactions
=> fix(cdk/table): set default role of table to 'table'

src/material-experimental/mdc-chips/testing/BUILD.bazel, src/material-experimental/mdc-chips/testing/chip-avatar-harness.ts, src/material-experimental/mdc-chips/testing/chip-harness-filters.ts, src/material-experimental/mdc-chips/testing/chip-harness.spec.ts, src/material-experimental/mdc-chips/testing/chip-harness.ts, src/material/chips/testing/BUILD.bazel, src/material/chips/testing/chip-avatar-harness.ts, src/material/chips/testing/chip-harness-filters.ts, src/material/chips/testing/chip-harness.ts, src/material/chips/testing/chip-list-harness.spec.ts, src/material/chips/testing/shared.spec.ts, tools/public_api_guard/material/chips-testing.d.ts
- add `MatChipAvatarHarness`
- add `getAvatar` method to `MatChipHarness`
- make `MatChipHarness` extend `ContentContainerComponentHarness`
- to allow getting a `MatIconHarness` inside a chip
=> feat(material/testing): MatChipHarness getAvatar

src/material/radio/radio.scss
We transition the circle of a radio button to `scale(0.001)` in order to hide it and to work around an animation in IE. It seems that on higher system zoom levels (e.g. 125%+) the browser approximates the size to 1x1 which can be visible.
These changes work around the issue by also setting `opacity: 0` while the circle is inactive and isn't animating.
Fixes #22036.
=> fix(material/radio): hidden circle visible on some zoom levels

src/cdk/drag-drop/BUILD.bazel, src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/drag-ref.ts
Fixes that the CDK drag&drop could be triggered by fake `mousedown` or `touchstart` events dispatched by a screen reader.
=> fix(cdk/drag-drop): don't start dragging on fake screen reader events

src/material-experimental/mdc-chips/chip-grid.spec.ts, src/material-experimental/mdc-chips/chip-input.ts, src/material/chips/chip-input.ts, src/material/chips/chip-list.spec.ts
In #19700 a flag was introduced whose purpose was to indicate whether focus should be moved from the input to the chips when pressing backspace. The problem is that the flag was only being updated on key presses and on init which means that the state will be incorrect if the value changes programmatically after init.
Fixes #23128.
=> fix(material/chips): restoring focus to last chip when pressing backspace

src/material-experimental/mdc-tooltip/_tooltip-theme.scss, src/material-experimental/mdc-tooltip/tooltip.scss
* due to a11y concerns surrounding the 0.6 background color opacity of the
mdc-tooltip, we are switching to using our own custom background color
instead of the one defined in the MDC styles.
=> fix(material-experimental/mdc-tooltip): make background color opaque

src/material-experimental/mdc-select/select.spec.ts, src/material-experimental/mdc-select/select.ts, src/material/select/select.spec.ts, src/material/select/select.ts
We have some logic in `mat-autocomplete` that scrolls the list to the top when the user moves to the first option in the first option group. This is slightly better UX, because it shows the group label, rather than stopping just below it.
These changes port over the same logic to `mat-select`.
=> fix(material/select): scroll to top on last option before option group

src/components-examples/material/table/table-generated-columns/table-generated-columns-example.html
Fixes a bug in the example of Angular Material `mat-table` with columns generated via ngFor.
The fix changes the tags over to native table selectors, which brings the example into alignment
with other examples of `mat-table` usage and allows for Angular Material formatting to apply.
=> docs(material/table): fix table formatting in ngFor example

.gitignore
Adds vim swamp files to .gitignore. This aligns us with the framework repo: https://github.com/angular/angular/blob/master/.gitignore#L21
=> build: add vim swamp files to .gitignore

src/components-examples/material-experimental/mdc-table/BUILD.bazel
Removes a remaining instance of the Bazel `module_name`
property being set.
=> build: remove leftover manual `module_name` definition

src/material-experimental/mdc-input/input.spec.ts, src/material/input/input.spec.ts, src/material/input/input.ts
A long time ago we disabled focus indication on `readonly` inputs in order to mimic the native browser behavior. It looks like the native behavior has changed to show the focus indication now so these changes remove the old logic and the associated unit tests.
Fixes #22783.
=> fix(material/input): show focus indication for readonly inputs

src/material-experimental/mdc-select/select.scss, src/material/select/select.scss
* Fixes that a small rectangle is rendered over the select placeholder text.
* Fixes that the dropdown arrow wasn't visible.
For reference:
=> fix(material-experimental/mdc-select): resolve a couple of visual issues in high contrast mode

src/material-experimental/mdc-core/option/optgroup.scss, src/material-experimental/mdc-core/option/option.scss, src/material-experimental/mdc-menu/menu.scss
The MDC option, option group and menu share some styles with the MDC list, but deliberately exclude others in order to allow the text to wrap. The problem is that if an MDC list is seen first on the page, its styles will conflict with the others.
These changes add an explicit override to avoid the conflict.
=> fix(multiple): incosistent item text truncation when used together with MDC list

src/material-experimental/mdc-menu/menu.spec.ts, src/material/menu/menu.spec.ts
Attempts to fix the recent flakiness in menu tests. It seems like we were destroying and recreating an overlay container at one point, but we were referring to the element of the previous.
=> test(material/menu): referring to wrong overlay element

src/material-experimental/mdc-tooltip/tooltip.ts, src/material/tooltip/tooltip.ts
Switches the tooltip to the outside click tracking from the `OverlayRef`, rather than having to maintain its own. This also results in fewer listeners on the `body`.
=> refactor(material/tooltip): use overlay outside click tracking

src/material/slider/_slider-theme.scss
Stackblitz repro of original bug: https://stackblitz.com/edit/angular-yrsz1m?file=src/app/slider-overview-example.html
=> fix(material/slider): Track fill style should only be applied when slider is focused, as opposed to when any ancestor is focused.

src/material-experimental/mdc-button/BUILD.bazel, src/material-experimental/mdc-button/button-high-contrast.scss, src/material-experimental/mdc-button/button.scss, src/material-experimental/mdc-button/button.ts, src/material-experimental/mdc-button/icon-button.ts
The high-contrast style for all buttons was previously defined in
`button.scss`, but icon-buttons load `icon-button.scss`. This means that
the high contrast style for icon buttons was only loaded when another
type of button was on the page. This change moved the icon-button high-contrast
style to `icon-button.scss`.
cc @zarend @amysorto FYI
=> fix(material-experimental/button): high contrast outline for solitary icon-buttons

src/material-experimental/mdc-paginator/paginator.html, src/material-experimental/mdc-paginator/paginator.spec.ts, src/material-experimental/mdc-paginator/paginator.ts
See commit message for description.
Original bug is filed internally at http://b/188218083
From the bug report:
ENVIRONMENT
OS | Browser | Assistive Technology    
Windows version 20H2,  Firefox version 88.0.1 (64-bit)
JAWS 2021 Version 2021.2102.34 ILM,
NVDA version 2020.4
PREREQUISITES
Turn on screen reader
STEPS TO REPRODUCE
Open Mozilla Firefox
Navigate to https://xap-gallery.googleplex.com/embed/a11y/mdc-paginator
Tab to the number of items combo box.  
Notice the announcement.
EXPECTED RESULT(S)
the value of the combo box should be announced by the screen reader.
ACTUAL RESULT(S)
The screen reader announces the role of the combo box, but not the value .  e.g. “Items per page: Combo box, To change the selection use the Arrow keys”.
ADDITIONAL NOTE(S)
This issue is only reproducible …
=> fix(material-experimental/mdc-paginator): target page size label with `aria-labelledby`

src/cdk/testing/protractor/protractor-element.ts, src/cdk/testing/tests/cross-environment.spec.ts, src/cdk/testing/tests/harnesses/main-component-harness.ts, src/cdk/testing/tests/test-main-component.html, src/material-experimental/mdc-card/testing/card-harness.e2e.spec.ts, src/material/card/testing/card-harness.e2e.spec.ts, src/material/toolbar/testing/toolbar-harness.e2e.spec.ts
We use Protractor's `getText` method to extract text, but the problem is that it's likely based on `HTMLElement.innerText` which excludes text from hidden elements.
These changes switch to using `textContent` to bring the behavior in-line with the `UnitTestElement`.
=> fix(cdk/testing): protractor element not extracting hidden text

scripts/circleci/setup-mdc-canary.js
Uses Yarn to resolve the latest canary version of MDC in an attempt to avoid flakes due to mismatches.
=> build: resolve latest MDC version through yarn

src/e2e-app/start-devserver.js
Fixes that e2e tests cannot be run locally on Windows right now.
This happens because there is no sandbox on Windows w/ Bazel and
the `start-devserver.js` utility accidentally resolves to a `.mjs`
file due to the patched NodeJS module resolution. We specify an
explicit file extension to avoid resolving an ESM module.
Also simplifies the server launching because the Protractor utils
now expose a method for starting the server.
=> build: fix being unable to run e2e tests locally on windows

src/cdk/testing/selenium-webdriver/selenium-web-driver-element.ts
In #21540 we added support for extracting text from hidden elements in Protractor, but before the PR could be merged, we introduced the WebDriver environment which didn't include the fix and is failing the e2e tests.
These changes port over the fix.
=> fix(cdk/testing): extract hidden text in web driver element

src/material/tabs/tab-group.ts
When a header is scrollable, we scroll a tab into view whenever it receives focus. The problem is that if focus is moved as a result of a mouse/touch event, the tab can be moved out from under the pointer, interrupting the click.
These changes work around the issue by not scrolling the header on mouse/touch focus.
Fixes #21898.
=> fix(material/tabs): avoid interrupting click event when scrolling the header

src/material-experimental/mdc-menu/menu-item.ts, src/material/menu/menu-item.ts, src/material/menu/menu-trigger.ts, tools/public_api_guard/material/menu.md
`matMenuContent` is declared as an `ng-template` and stamped out inside the menu which means that its change detection tree is actually in the declaration place, rather than the insertion place. This can result in the `highlighted` state not being updated when inside an `OnPush` component.
Fixes #23175.
**Note:** I didn't include any tests, because reproducing this in a test is tricky.
=> fix(material/menu): item highlighted state not updating in time when using lazy content

src/material/core/typography/_typography-utils.scss, src/material/form-field/_form-field-fill-theme.scss, src/material/form-field/_form-field-legacy-theme.scss, src/material/form-field/_form-field-outline-theme.scss, src/material/form-field/_form-field-theme.scss, src/material/input/_input-theme.scss, src/material/select/_select-theme.scss
Our typography mixins for form-field related components coerce line-height to `em` units in several places. If a user provides a `line-height` via typography config with a unit specified, this results in an error as the result with be em squared. This fix changes the coercion to only occur if the line-height is unitless.
=> fix(material/form-field): safely coerce line-height to em

src/material-experimental/mdc-list/list.scss
MDC currently supports three-line list items in a way where
they assume that the second list line should wrap into
a third line. This is not suitable for our MDC-based list
because it would result in an incompatibility with the non-MDC
list and as per Material Design spec it is a supported case
to have a third list line that is decoupled from the second line.
The spec describes multiple variants for a three-line list, and
MDC is not off the spec here, but just doesn't support our
three-line list variant yet. It is planned to continue discussion
with the MDC team to push forward on the other three-line variants.
**Note for team**: I've added a new item to the agenda. I've been chatting
with Brandon from the MDC a little about this. They are open in supporting
the variant we need for our …
=> fix(material-experimental/mdc-list): fix secondary line accidentally wrapping text

src/material-experimental/mdc-list/list-option.scss
We have some special handling for single selection lists in high contrast mode which wasn't switched to the non-deprecated list styles.
=> fix(material-experimental/mdc-list): fix selected indication in high contrast mode

package.json, test/browser-providers.js, test/karma-browsers.json, test/karma.conf.js, tools/package-tools/ts-compile.ts, yarn.lock
=> ci: fix saucelabs browser crashing due to idle timeout

src/material/expansion/expansion.spec.ts, test/bazel-karma-local-config.js
An expansion test seems to be flaky/failing in Safari on iOS14
because the `visibility: hidden` style from the expansion panel
content is not applied immediately. We fix this by enforcing
a style recalculation like we do in the ripple. An alternative
would have been to switch the test to actual async/await where
we then need to wait at least until the next tick. It seems more
idiomatic to stick with `fakeAsync` here though.
Example failing build: https://app.circleci.com/pipelines/github/angular/components/27478/workflows/76466fd9-9f92-40a7-8626-58a99351d018/jobs/296976
=> test(material/expansion): fix failing unit test on iOS14 safari

scripts/circleci/setup-mdc-canary.js
Reworks the MDC canary script to use `yarn install` instead of going through `yarn add` in an attempt to avoid flakes on the CI.
=> build: install MDC canary dependencies through yarn

src/components-examples/material-experimental/mdc-table/index.ts, src/components-examples/material-experimental/mdc-table/table-flex-large-row/table-flex-large-row-example.css, src/components-examples/material-experimental/mdc-table/table-flex-large-row/table-flex-large-row-example.html, src/components-examples/material-experimental/mdc-table/table-flex-large-row/table-flex-large-row-example.ts, src/dev-app/mdc-table/mdc-table-demo.html, src/material-experimental/mdc-table/table.scss
Row layout breaks when flex cells have a lot of content - the cell will grow but the row will not because rows have an explicit height. If the explicit height is removed, the row will expand but the other cells do not, causing their borders to be all over the place.
This lets rows grow with the cells, and lets the surrounding cells also grow
=> fix(material-experimental/mdc-table): flex tables should stretch cells

src/cdk-experimental/dialog/dialog-config.ts, src/cdk-experimental/dialog/dialog-container.ts, src/cdk-experimental/dialog/dialog.spec.ts, src/cdk/a11y/focus-trap/focus-trap.ts, src/material-experimental/mdc-dialog/dialog-container.ts, src/material-experimental/mdc-dialog/dialog.spec.ts, src/material-experimental/mdc-dialog/public-api.ts, src/material/bottom-sheet/bottom-sheet-config.ts, src/material/bottom-sheet/bottom-sheet-container.ts, src/material/bottom-sheet/bottom-sheet.spec.ts, src/material/dialog/dialog-config.ts, src/material/dialog/dialog-container.ts, src/material/dialog/dialog.spec.ts, src/material/sidenav/drawer.spec.ts, src/material/sidenav/drawer.ts, tools/public_api_guard/material/bottom-sheet.md, tools/public_api_guard/material/dialog.md, tools/public_api_guard/material/sidenav.md
Before this PR, autoFocus was a boolean that allowed users to specify whether the container element or the first tabbable element is focused on dialog open. Now you can also specify focusing the first header element or use a CSS selector and focus the first element that matches that. If these elements can't be focused, then the container element is focused by default.
This applies to other components that are similar to dialog and also have a autoFocus field.
=> feat(multiple): add options to autoFocus field for dialogs

src/cdk/a11y/interactivity-checker/interactivity-checker.ts
As of v13, we no longer support IE11. Related to #7374
=> refactor(cdk/a11y): remove InteractivityChecker ie11 special case

src/cdk/overlay/overlay-directives.spec.ts, src/cdk/overlay/overlay-directives.ts, src/material-experimental/mdc-select/select.ts, tools/public_api_guard/cdk/overlay.md
`CdkConnectedOverlay` directive's input `cdkConnectedOverlayOrigin` only supports `CdkOverlayOrigin`.
`FlexibleConnectedPositionStrategy` supports a lot more types. Add support for them.
Fixes #23252
=> feat(cdk/overlay): Extend `cdkConnectedOverlayOrigin` to support more types.

package.json, tools/highlight-files/highlight-code-block.ts, yarn.lock
Fixes the following deprecation warning that is logged by `highlightjs`:
```
Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
Deprecated as of 10.7.0. Please use highlight(code, options) instead.
https://github.com/highlightjs/highlight.js/issues/2277
```
=> build: fix deprecation warning from highlightjs

guides/theming.md
Fixes that the light/dark state of a couple of themes was mixed up.
Fixes https://github.com/angular/material.angular.io/issues/1031.
=> docs: prebuilt themes incorrectly listed as dark

.stylelintrc.json, package.json, src/material-experimental/mdc-helpers/_mdc-helpers.scss, src/material/core/typography/_typography.scss, src/material/sidenav/drawer.scss, yarn.lock
Bumps Stylelint to the latest version and turns on an option to flag unnecessary disable clauses.
=> build: flag unnecessary stylelint disable clauses

src/cdk/text-field/autosize.ts
When we measure the size of the autosize `textarea`, we make it temporarily smaller which can cause the scroll position to shift on Firefox. These changes add a workaround that assign a temporary `margin-bottom` while measuring.
Fixes #23233.
=> fix(cdk/text-field): avoid page jump on firefox

src/cdk/drag-drop/directives/drag.spec.ts, src/cdk/drag-drop/directives/drag.ts, src/cdk/drag-drop/drag-ref.ts, src/cdk/drag-drop/drop-list-ref.ts, src/cdk/drag-drop/parent-position-tracker.ts
Cleans up the various workarounds that were put in place for IE.
=> refactor(cdk/drag-drop): clean up IE workarounds

src/material/progress-spinner/progress-spinner.html, src/material/progress-spinner/progress-spinner.scss, src/material/progress-spinner/progress-spinner.spec.ts, src/material/progress-spinner/progress-spinner.ts, tools/public_api_guard/material/progress-spinner.md
Cleans up the various workarounds for IE from the progress spinner.
=> refactor(material/progress-spinner): clean up IE workarounds

src/cdk/drag-drop/directives/drag.ts
The `CdkDrag` directive subscribes to `NgZone.onStable` on init and then unsubscribes after the first emit. This is usually fine, but it can cause change detections if the app is using `zone-patch-rxjs`.
These changes explicitly run a few sensitive calls outside the zone.
Fixes #23248.
=> perf(cdk/drag-drop): avoid excessive change detections with zone-patch-rxjs

src/cdk/overlay/overlay-reference.ts
We have an interface called `OverlayReference` which is meant to mimic `OverlayRef` while allowing us to break the circular dependency of `ScrollStrategy -> OverlayRef -> OverlayConfig -> ScrollStrategy`. The problem is that it currently doesn't expose some useful members.
These changes expand the interface to cover more of the `OverlayRef` API surface.
Fixes #23234.
=> fix(cdk/overlay): expand `OverlayReference` interface to cover more properties

src/material/core/theming/_theming.scss
We have some hues that start with a number (e.g. `700-contrast`), which can break the map lookup in `get-color-from-palette`, because Sass infers them as numbers.
These changes make it so that the key is cast to a string before we do the lookup.
Fixes #23230.
=> fix(material/core): handle hues inferred as numbers

packages.bzl
The release tool will require us to update the peer dependencies to no longer
allow for v12 when cutting v13 major pre-releases.
=> build: update peer dependency for angular framework dependencies

CHANGELOG.md
The luxon adapter didn't go into minor, this updates the CHANGELOG to reflect that.
Using `target: patch` label so this will go into both the `master` and `12.2.x` branches.
=> release: remote luxon adapter from changelog

CHANGELOG.md
This reverts commit b922846ed7b8f678ca85b3addf4ffc04c5e24cb1, which
remote material luxon adapter from the changelog. That was removed by
mistake because I thought the package did not publish correctly. I
confirmed on npmjs.com that we published
@angular/material-luxon-adapter@12.2.0. Since it was published, we add
it to the CHANGELOG.
=> release: add luxon adapter back to the changelog.

CHANGELOG.md
This reverts commit b922846ed7b8f678ca85b3addf4ffc04c5e24cb1, which
remote material luxon adapter from the changelog. That was removed by
mistake because I thought the package did not publish correctly. I
confirmed on npmjs.com that we published
@angular/material-luxon-adapter@12.2.0. Since it was published, we add
it to the CHANGELOG.
=> release: add luxon adapter back to the changelog. (#23324)

src/material/core/common-behaviors/common-module.ts
Looks like when the granular sanity checks were introduced, some of the logic that determines whether a check should run wasn't written correctly which means that it isn't running at all.
These changes move the check logic into a separate method in order to make it less prone to mistakes.
=> fix(material/core): sanity checks not running

src/material-experimental/mdc-tabs/tab-group.scss, src/material/tabs/tab-group.scss
Fixes that the tab header doesn't collapse inside a flex container which prevents it from showing the pagination.
Fixes #23157.
=> fix(material/tabs): pagination not working inside flex container

scripts/check-mdc-tests-config.ts, src/e2e-app/protractor.conf.js, src/material-experimental/mdc-helpers/_focus-indicators.scss, src/material-experimental/mdc-slide-toggle/_slide-toggle-theme.scss, src/material-experimental/mdc-slide-toggle/slide-toggle.e2e.spec.ts, src/material-experimental/mdc-slide-toggle/slide-toggle.html, src/material-experimental/mdc-slide-toggle/slide-toggle.scss, src/material-experimental/mdc-slide-toggle/slide-toggle.spec.ts, src/material-experimental/mdc-slide-toggle/slide-toggle.ts, src/material-experimental/mdc-slide-toggle/testing/BUILD.bazel, src/material-experimental/mdc-slide-toggle/testing/slide-toggle-harness.ts, src/material/slide-toggle/slide-toggle.spec.ts, src/material/slide-toggle/testing/shared.spec.ts, src/material/slide-toggle/testing/slide-toggle-harness.ts, tools/public_api_guard/material/slide-toggle-testing.md
Switches the MDC-based slide toggle to the non-deprecated MDC styles.
Notable changes:
* New markup which uses a `button` instead of an `input` for the interaction.
* New icons inside the slide toggle's thumb. Technically we could opt out of them, but I think that they look better and they help with accessibility for color-blind users.
* New theming system that uses a flat list of variables. There is a fallback for IE11, but I decided not to include it for now, because of the upcoming deprecation and the fact that the component is in experimental.
* The component has some slightly different colors and it supports more states (e.g. hover).
* Due to the switch from `input` to `button`, the `required` input is basically a noop now.
Here's what it looks like now:
=> feat(material-experimental/mdc-slide-toggle): switch to non-deprecated styles

src/cdk/drag-drop/drag-events.ts, tools/public_api_guard/cdk/drag-drop.md
Fixes that the `CdkDragDrop` event didn't have a way of typing the item.
Fixes #23208.
=> fix(cdk/drag-drop): add generic parameter for item type in CdkDragDrop

packages.bzl
In https://github.com/angular/angular/pull/42991 which went out in version 12.2.0 we made it possible to opt into rxjs 7, however the change only affects the core packages. These changes apply the same version range to the Components packages.
=> build: update peerDependencies to allow rxjs 7

src/material-experimental/mdc-slide-toggle/slide-toggle.spec.ts, src/material/slide-toggle/slide-toggle.spec.ts
Attempts to fix some of the recent slide toggle test flakes by making all tests `fakeAsync` and adding the missing flushes.
**Note:** while we don't technically need `fakeAsync` everywhere now that we know which tests are problematic, I did it anyway for consistency.
=> test(material/slide-toggle): fix test flakes

test/browser-providers.js, test/karma-browsers.json
Since Edge is based on Chromium now, we don't get much out of running unit tests against it.
=> build: don't run tests against edge

.ng-dev/release.ts, package.json, tools/release-checks/index.js
Currently the new release tool hacks around the ng-dev publish
tool in order to run staging sanity checks. The logic is
currently running in the same Node process that started
the publish process from `master`. This results in the
sanity checks accidentally receiving a cached list of
release packages, instead of the one local to the publish
branch (like `12.2.x`build: fix staging sanity release checks picking up
incorrect packages
Currently the new release tool hacks around the ng-dev publish
tool in order to run staging sanity checks. The logic is
currently running in the same Node process that started
the publish process from `master`. This results in the
sanity checks accidentally receiving a cached list of
release packages, instead of the one local to the publish
branch (like …
=> build: fix staging sanity release checks picking up incorrect packages

CHANGELOG.md
=> docs: release notes for the v12.2.1 release

guides/getting-started.md
Fixes some weird formatting and a few minor content issues in the "Getting started" guide.
=> docs: fix up getting started guide

src/material/expansion/expansion-panel.ts
Fixes a typo in one of the doc strings.
Fixes #23339.
=> docs(material/expansion): fix typo in doc string

src/material-experimental/mdc-dialog/dialog.spec.ts, src/material-experimental/mdc-dialog/dialog.ts, src/material/dialog/dialog-container.ts, src/material/dialog/dialog.spec.ts, src/material/dialog/dialog.ts, tools/public_api_guard/material/dialog.md
- notify screen reader users that they have entered a dialog
- previously only the focused element would be read
  i.e. "Close Button Press Search plus Space to activate"
- now the screen reader user gets the normal dialog behavior, which is to
  read the dialog title, role, content, and then tell the user about the
  focused element
  - this matches the guidance here:
    https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/dialog.html
- Avoid opening multiple of the same dialog before animations complete by returning
  the previous `MatDialogRef`
- update material/dialog API golden file
Fixes #21840
=> fix(material/dialog): improve screen reader support when opened

.github/workflows/dev-infra.yml
Automatically add/remove `breaking changes` label to PRs as needed based on whether
the PR contains a commit with a breaking change.
=> ci: add breaking changes auto labeling action

package.json, yarn.lock
Updates to the latest version of the `ng-dev` tool so that
the upcoming releases can benefit from the recent changes
that have been made for the release tool.
=> build: update to the latest version of `@angular/dev-infra-private`

package.json, yarn.lock
Updates to the latest version of the `ng-dev` tool so that
the upcoming releases can benefit from the recent changes
that have been made for the release tool.
=> build: update to the latest version of `@angular/dev-infra-private` (#23383)

src/material-experimental/mdc-progress-bar/progress-bar.spec.ts, src/material-experimental/mdc-progress-bar/progress-bar.ts, src/material-experimental/mdc-progress-bar/public-api.ts, src/material/progress-bar/progress-bar.spec.ts, src/material/progress-bar/progress-bar.ts, tools/public_api_guard/material/progress-bar.md
Adds an injection token that allows for the progress bar defaults to be configured.
Fixes #23329.
=> feat(material/progress-bar): add default options injection token

src/material/datepicker/calendar-body.html
The first row of cells has a cell with the month label which also has a `colspan` and `aria-hidden`. It looks like hiding the cell causes screen readers to ignore the cell competely and consider the cells after it to be first. This results in the wrong day of the week being read out for each date.
=> fix(material/datepicker): wrong day of week read out for dates in first row

src/material-experimental/mdc-card/BUILD.bazel, src/material-experimental/mdc-card/card.spec.ts, src/material-experimental/mdc-card/card.ts
Adds a new DI token to the MDC-based card that allows consumers to set the default appearance.
Also sets up unit tests for the card.
Fixes #23298.
=> feat(material-experimental/mdc-card): add DI token for configuring appearance

src/material-experimental/mdc-checkbox/checkbox.html, src/material-experimental/mdc-checkbox/checkbox.spec.ts, src/material-experimental/mdc-list/list-option.html, src/material-experimental/mdc-list/selection-list.spec.ts, src/material/checkbox/checkbox.html, src/material/checkbox/checkbox.spec.ts
Fixes that the `svg` node inside of the checkbox might be read out by some screen readers.
Fixes #23338.
=> fix(material/checkbox): hide svg from assistive technology

src/cdk/a11y/focus-trap/event-listener-inert-strategy.ts
We seem to hitting an error on Firefox when calling `closest` inside a unit test. These changes add a null check to work around the issue.
=> fix(cdk/a11y): error on firefox

CHANGELOG.md
=> docs: release notes for the v12.2.2 release

guides/typography.md
Fixes that the `letter-spacing` helper function wasn't mentioned in the docs.
Fixes #23297.
=> docs: mention letter-spacing helper

src/components-examples/material/button-toggle/button-toggle-mode/button-toggle-mode-example.html, src/components-examples/material/button-toggle/button-toggle-mode/button-toggle-mode-example.ts, src/components-examples/material/button-toggle/index.ts, src/material/button-toggle/button-toggle.md
Adds a new example showing a button toggle in multiple selection mode.
Fixes #23344.
=> docs(material/button-toggle): add selection mode example

src/cdk/clipboard/copy-to-clipboard.ts, tools/public_api_guard/cdk/clipboard.md
Cleans up the APIs that were marked for removal for v13.
* `CKD_COPY_TO_CLIPBOARD_CONFIG` has been removed. Use `CDK_COPY_TO_CLIPBOARD_CONFIG` instead.
=> refactor(cdk/clipboard): clean up deprecated APIs for v13

src/cdk/a11y/fake-event-detection.ts, src/cdk/testing/testbed/fake-events/dispatch-events.ts, src/cdk/testing/testbed/fake-events/element-focus.ts, src/cdk/testing/testbed/fake-events/event-objects.ts
Switches from the legacy `init<..>Event` calls to the Event constructors
given that IE11 no longer is supported.
=> refactor(cdk/testing): switch to event constructor for creating fake events

src/material/core/datetime/native-date-adapter.spec.ts, src/material/core/datetime/native-date-adapter.ts, tools/public_api_guard/material/core.md
Cleans up the code needed to support IE, Edge and Safari 9 since we don't support either of them as of version 13.
=> refactor(material/core): cleanup unsupported browser workarounds

src/material/datepicker/calendar.spec.ts, src/material/datepicker/datepicker.spec.ts, src/material/datepicker/month-view.html, src/material/datepicker/month-view.spec.ts, src/material/datepicker/month-view.ts, src/material/datepicker/multi-year-view.html, src/material/datepicker/multi-year-view.ts, src/material/datepicker/year-view.html, src/material/datepicker/year-view.ts, tools/public_api_guard/material/datepicker.md
Fixes that the Material calendar was reopening immediately when a date is selected using the spacebar on Firefox.
Fixes #23305.
=> fix(material/datepicker): calendar reopening on spacebar selection

src/material-experimental/mdc-tabs/testing/tab-harness.ts, src/material/tabs/testing/tab-harness.ts, tools/public_api_guard/material/tabs-testing.md
Removes the APIs that were marked for removal in v13.
* `MatTabHarness.getHarnessLoaderForContent` has been removed. Use `MatTabHarness.getRootHarnessLoader` instead.
=> refactor(material/tabs): remove deprecated APIs for v13

src/material/form-field/form-field.html, src/material/form-field/form-field.ts, src/material/form-field/testing/form-field-harness.ts, src/material/schematics/ng-update/data/constructor-checks.ts, tools/public_api_guard/material/form-field-testing.md, tools/public_api_guard/material/form-field.md
* `MatFormFieldHarness.getHarnessLoaderForPrefix` has been removed. Use `MatFormFieldHarness.getPrefixText` instead.
* `MatFormFieldHarness.getHarnessLoaderForSuffix` has been removed. Use `MatFormFieldHarness.getSuffixText` instead.
* The `_labelOptions` parameter of the `MatFormField` constructor has been removed.
* `MatFormField.underlineRef` has been removed.
=> refactor(material/form-field): remove deprecated APIs for version 13

src/material-experimental/mdc-button/BUILD.bazel, src/material-experimental/mdc-button/button-base.ts, src/material-experimental/mdc-button/button.html, src/material-experimental/mdc-checkbox/BUILD.bazel, src/material-experimental/mdc-checkbox/checkbox.html, src/material-experimental/mdc-checkbox/checkbox.ts, src/material-experimental/mdc-chips/BUILD.bazel, src/material-experimental/mdc-chips/chip-option.html, src/material-experimental/mdc-chips/chip-row.html, src/material-experimental/mdc-chips/chip.html, src/material-experimental/mdc-chips/chip.ts, src/material-experimental/mdc-list/BUILD.bazel, src/material-experimental/mdc-list/list-base.ts, src/material-experimental/mdc-menu/BUILD.bazel, src/material-experimental/mdc-menu/menu-item.html, src/material-experimental/mdc-menu/menu-item.ts, src/material-experimental/mdc-radio/BUILD.bazel, src/material-experimental/mdc-radio/radio.html, src/material-experimental/mdc-radio/radio.ts, src/material-experimental/mdc-slide-toggle/BUILD.bazel, src/material-experimental/mdc-slide-toggle/slide-toggle.html, src/material-experimental/mdc-slide-toggle/slide-toggle.ts
Now that the default ripple timings have been aligned to MDC, we don't have to make any overrides in the various MDC components.
=> refactor(multiple): clean up ripple overrides in MDC components

src/material/tabs/_tabs-theme.scss
When a background color is set on a tab group, we reset the tab header's bottom border. The problem is that the selector was too broad which made it apply to nested tabs as well.
These changes fix the issue by making the selector more specific.
Fixes #23432.
=> fix(material/tabs): tab header border reset when parent has a background color

src/material-luxon-adapter/adapter/luxon-date-adapter.spec.ts, src/material-luxon-adapter/adapter/luxon-date-adapter.ts
Cleans up some code that is no longer necessary now that we don't support IE and Edge.
=> refactor(material-luxon-adapter): clean up unsupported browser workarounds

src/components-examples/material/card/BUILD.bazel, src/components-examples/material/card/card-actions/card-actions-example.html, src/components-examples/material/card/card-actions/card-actions-example.ts, src/components-examples/material/card/card-footer/card-footer-example.css, src/components-examples/material/card/card-footer/card-footer-example.html, src/components-examples/material/card/card-footer/card-footer-example.ts, src/components-examples/material/card/card-media-size/card-media-size-example.css, src/components-examples/material/card/card-media-size/card-media-size-example.html, src/components-examples/material/card/card-media-size/card-media-size-example.ts, src/components-examples/material/card/card-subtitle/card-subtitle-example.css, src/components-examples/material/card/card-subtitle/card-subtitle-example.html, src/components-examples/material/card/card-subtitle/card-subtitle-example.ts, src/components-examples/material/card/index.ts
Introduce more examples with actions, footer, image size, and subtitles.
Demo: https://stackblitz.com/edit/angular-ivy-zanf7t?file=src%2Fmain.ts
Close Issue: https://github.com/angular/components/issues/22844
=> docs(material/card): add more examples

src/cdk/stepper/stepper.md
The "Accessibility' section of the stepper docs was talking about the stepper having built-in accessibility treatment, even though it doesn't have any, because we don't have control over the component's markup.
These changes reword the section to make it more accurate.
Fixes #23044.
=> docs(cdk/stepper): change misleading documentation

.ng-dev/release.ts
Currently the new release tooling groups changes in the
changelog based on their commit scope. This is the default
behavior that works well for FW and the CLI repo.
For the components repository, we also include secondary entry-point
information in commit messages. This currently results in
many unnecessary groups, while ideally we'd want to group
based on the package name in the scope. This commit implements
that.
=> build: group commits by package name in changelog

CHANGELOG.md
=> docs: release notes for the v12.2.4 release

src/material/icon/icon-registry.ts, src/material/icon/trusted-types.ts
When Angular Material is used in an environment that enforces [Trusted Types](https://web.dev/trusted-types/), the icon registry raises a Trusted Types violation due to its use of `element.innerHTML` when initializing SVG icons.
To make the icon registry compatible with Trusted Types, `SvgIconConfig.svgText` is changed to a `TrustedHTML`, and its users updated to either produce `TrustedHTML` (making sure to only do so in cases where its security can be readily assessed) or pass such values along.
To facilitate this, add a module that provides a Trusted Types policy, `angular#components`, for use internally by Angular Material. The policy is created lazily and stored in a module-local variable. This is the same as the approach taken by Angular proper in …
=> fix(material/icon): make icon-registry compatible with Trusted Types

src/material-experimental/mdc-button/testing/button-harness.ts, src/material/button/testing/button-harness.ts
Uses a static string for the selector of the button harness since the `join` call we had previously was showing up in the docs.
For reference:
=> refactor(material/button): use static string for selector

src/cdk/schematics/ng-update/data/index.ts, src/cdk/schematics/ng-update/data/symbol-removal.ts, src/cdk/schematics/ng-update/devkit-migration-rule.ts, src/cdk/schematics/ng-update/migrations/symbol-removal.ts, src/cdk/schematics/ng-update/upgrade-data.ts, src/material/schematics/ng-update/data/index.ts, src/material/schematics/ng-update/data/symbol-removal.ts, src/material/schematics/ng-update/test-cases/misc/symbol-removal.spec.ts, src/material/schematics/ng-update/test-cases/misc/symbol-removal_input.ts, src/material/schematics/ng-update/upgrade-data.ts
Sets up a new migration that will log a message for symbols that have been removed from a specific module.
Relates to #23529.
=> feat(cdk/schematics): add migration for removed symbols

WORKSPACE
Updates the version of `rules_sass` to the latest version
so that we can remove our `@bazel/worker` workaround now
that we have landed the Bazel worker v4.x compatibility fix
upstream.
=> build: update version of rules_sass to remove workaround

src/material-experimental/mdc-paginator/paginator.spec.ts, src/material/paginator/paginator.spec.ts
Refactored tests of the Angular Material `paginator` component. Removed comments and instead extracted tested behaviours into separate test cases, to keep them simple and isolated.
=> refactor(material/paginator): refactor tests for paginator texts

src/material-experimental/mdc-chips/chip-grid.spec.ts, src/material-experimental/mdc-chips/chip-grid.ts, src/material/chips/chip-list.spec.ts, src/material/chips/chip-list.ts, tools/public_api_guard/material/chips.md
Similar to #23362. Fixes that the required asterisk wasn't being shown when a chip list is required.
=> fix(material/chips): show required asterisk when using required validator

src/material/tabs/tab-group.ts, tools/public_api_guard/material/tabs.md
MatTabGroup's property `contentTabIndex` specifies its type as `number |
null`. However, the `ngAcceptInputType` is specified as `BooleanInput`.
Fixes the input type to be `NumberInput` to align with property type.
=> fix(material/tabs): fix contentTabIndex input type

src/material-experimental/mdc-autocomplete/autocomplete.spec.ts, src/material/autocomplete/autocomplete-trigger.ts, src/material/autocomplete/autocomplete.spec.ts, src/material/autocomplete/autocomplete.ts
Fixes that we were emitting the `optionActivated` event when the option is reset programmatically when the panel closes. The intent was to only emit the event as a result of a user action.
Fixes #23430.
=> fix(material/autocomplete): don't emit optionActivated event when option is reset

.stylelintrc.json, src/components-examples/material/core/ripple-overview/ripple-overview-example.css, src/dev-app/menubar/mat-menubar-demo.scss, src/dev-app/virtual-scroll/virtual-scroll-demo.scss, src/material-experimental/mdc-form-field/_form-field-native-select.scss, src/material/core/style/_vendor-prefixes.scss, src/material/datepicker/date-range-input.scss, src/material/form-field/_form-field-legacy-theme.scss, src/material/form-field/form-field-input.scss, src/material/form-field/form-field-legacy.scss
Cleans up the styles specifically for IE and Edge.
=> refactor(multiple): clean up IE vendor prefixes

src/material/chips/chip-list.spec.ts, src/material/chips/chip-list.ts
Similar issue to #23378. The chip list will throw an error if the `selected` value is accessed before the selection model has been initialized.
=> fix(material/chips): error if selected value is accessed too early

src/material/sidenav/drawer.ts
Currently when a sidenav is closed, we restore the focus origin as when it was focused because we don't know what kind of event closed it, however if it happens through the backdrop, we can be fairly certain that it was via mouse.
These changes pass in the `mouse` origin when closing through the backdrop.
Fixes #23484.
=> fix(material/sidenav): restore focus with correct origin when closing via the backdrop

CHANGELOG.md
=> docs: release notes for the v12.2.5 release

src/cdk/stepper/stepper.ts, src/material/stepper/stepper.spec.ts
The Material stepper's template is set up such that we have a single `ng-template` at the bottom declaring the header which is then rendered out with an `ngTemplateOutlet` inside an `ngFor`. We do this in order to reduce duplication, because a lot of properties and attributes have to be set on `mat-step-header`.
Then problem with this approach is that because the header is outside the `ngFor`, it may not appear in the correct order in the `ngFor` if the list changes. This results in incorrect navigation order when using the next/previous buttons or the keyboard.
These changes add some logic that will sort the headers based on their position in the DOM in order to work around the issue. Alternatively, we could fix this by inlining the `mat-step-header` template, but that'll result in some …
=> fix(material/stepper): incorrect navigation order when steps are added later on

src/components-examples/material/chips/chips-autocomplete/chips-autocomplete-example.html, src/components-examples/material/chips/chips-input/chips-input-example.html, src/dev-app/chips/chips-demo.html, src/dev-app/mdc-chips/mdc-chips-demo.html, src/material-experimental/mdc-chips/README.md, src/material-experimental/mdc-chips/chips.scss, src/material/chips/chips.scss
Fixes that `matChipRemove` looked off when it's set on a `button` element. Also updates all the examples to use buttons.
Note that we don't need any extra logic, because the `MatChipRemove` directive already sets `type="button"` when it's applied to a `button` element.
Fixes #23463.
=> fix(material/chips): handle matChipRemove set on a button

src/material/form-field/form-field-input.scss
By default we hide all browser decorations from the input, because they don't usually work well with Material.
These changes exclude the password autofill from password inputs, because it has some UX and security implications, and password inputs don't have any other decorations anyway.
Fixes #20639.
=> fix(material/input): preserve password autofill icon

src/material-experimental/mdc-button/fab.scss, src/material-experimental/mdc-button/icon-button.scss
Fixes that the width of the FAB and icon button can collapse. We have something similar in the existing buttons already.
=> fix(material-experimental/mdc-button): avoid shrinking FAB and icon button

src/cdk/a11y/input-modality/input-modality-detector.spec.ts, src/cdk/a11y/input-modality/input-modality-detector.ts
Fixes that we weren't completing the event streams from the `InputModalityDetector` when it is destroyed.
=> fix(cdk/a11y): complete input modality streams on destroy
