angular/components

rollup-globals.bzl
src/material-experimental/mdc-slider/BUILD.bazel
src/material-experimental/mdc-slider/global-change-and-input-listener.ts
src/material-experimental/mdc-slider/slider.ts

Fixes a couple of deep imports in the `mdc-slider` package that were causing the CLI to log a warning when the package is installed.

fix(material-experimental/mdc-slider): remove deep imports

---

package.json
yarn.lock

Updates to the latest version of the `@angular/dev-infra-private`
package. The latest changes include sorting of commits in the
release notes, preparation for M1 Mac browser testing support and
a fix for the release tool where an older tag used for release
notes generation is not fetched properly.
Note: We need downgrade the TS version used by the dev-infra-private
package as it results in some hoísting issues with Yarn where tslint
incorrectly picks up the 4.4.x version as peer dependency. This does
not seem to be overwritable through a Yarn resolution for tslint.

build: update version of @angular/dev-infra-private package

---

src/material/datepicker/_datepicker-theme.scss

Fixes that the color contrast of the calendar header's text was too low.
Fixes #23511.

fix(material/datepicker): improve color contrast in calendar header

---

src/material-experimental/mdc-menu/directives.ts
src/material-experimental/mdc-menu/module.ts
src/material-experimental/mdc-menu/public-api.ts
src/material-experimental/mdc-menu/testing/menu-harness.ts
src/material/menu/menu-content.ts
src/material/menu/menu-module.ts
src/material/menu/menu-trigger.ts
src/material/menu/public-api.ts
tools/public_api_guard/material/menu.md

The MDC menu trigger had `.mat-menu-trigger` class because it was using
the same directive as the non-MDC menu. This PR refactors the trigger
and content directives to extend a common base class.

fix(material-experimental/mdc-menu): ensure mat-mdc- prefix on all classes

---

CHANGELOG.md

docs: release notes for the v12.2.6 release

---

src/material/autocomplete/autocomplete.md
src/material/bottom-sheet/bottom-sheet.md
src/material/button-toggle/button-toggle.md
src/material/card/card.md
src/material/checkbox/checkbox.md
src/material/datepicker/datepicker.md
src/material/dialog/dialog.md
src/material/divider/divider.md
src/material/expansion/expansion.md
src/material/form-field/form-field.md
src/material/list/list.md
src/material/menu/menu.md
src/material/progress-bar/progress-bar.md
src/material/progress-spinner/progress-spinner.md
src/material/radio/radio.md
src/material/slide-toggle/slide-toggle.md
src/material/slider/slider.md
src/material/snack-bar/snack-bar.md
src/material/table/table.md
src/material/tabs/tabs.md
src/material/tooltip/tooltip.md

This change updates the accessibility docs for 21 components for
correctness, comprehensiveness, and clarity.
I have intentionally omitted several other components either because
they're being worked on by someone else or have significant changes
pending.
cc @zarend @amysorto

docs(multiple): revise and expand a11y docs

---

src/material/datepicker/datepicker-base.ts
src/material/schematics/ng-update/data/constructor-checks.ts
tools/public_api_guard/material/datepicker.md

Removes the APIs that were marked for removal in v13.
* The `_document` and `_dialog` parameters have been removed from the `MatDatepicker` and `MatDateRangePicker` constructors.

refactor(material/datepicker): remove deprecated APIs for v13

---

src/cdk/layout/media-matcher.ts

There appears to be a bug in Chrome, where if we try to use `matchMedia` on a media query that doesn't match anything on the page and a style recalculation is triggered on the `body`, the `matchMedia` callback stops firing which in turn breaks `BreakpointObserver`.
These changes expand an existing workaround that we had for WebKit browsers involving inserting a dummy `style` tag on the page so that there's always at least one matching element.
Fixes #23546.

fix(cdk/layout): breakpoint observer not firing callback on chrome in specific cases

---

src/material-experimental/mdc-snack-bar/testing/BUILD.bazel
src/material-experimental/mdc-snack-bar/testing/snack-bar-harness.spec.ts
src/material-experimental/mdc-snack-bar/testing/snack-bar-harness.ts
src/material/snack-bar/testing/BUILD.bazel
src/material/snack-bar/testing/shared.spec.ts
src/material/snack-bar/testing/snack-bar-harness.spec.ts
src/material/snack-bar/testing/snack-bar-harness.ts
tools/public_api_guard/material/snack-bar-testing.md

of mdc-snack-bar with custom content

fix(material-experimental/mdc-snack-bar): add harness support for getting label and actions

---

src/cdk/drag-drop/directives/drag.spec.ts
src/cdk/drag-drop/drop-list-ref.ts

Fixes that the `sorted` event was being emitted when the item wasn't actually being sorted when it's inside of a list with a single item.
Fixes #23575.

fix(cdk/drag-drop): sorted event emitted multiple times for single-item list

---

src/youtube-player/youtube-player.ts
tools/public_api_guard/youtube-player/youtube-player.md

Removes the APIs that were marked for removal in v13 in the `youtube-player` package.
* `YouTubePlayer.createEventsBoundInZone` has been removed.

refactor(youtube-player): remove deprecated APIs for v13

---

src/material-experimental/mdc-tabs/public-api.ts
src/material-experimental/mdc-tabs/tab-group.spec.ts
src/material-experimental/mdc-tabs/tab.ts
src/material/tabs/public-api.ts
src/material/tabs/tab-group.spec.ts
src/material/tabs/tab-label.ts
src/material/tabs/tab.ts
tools/public_api_guard/material/tabs.md

We use `ContenChild` to get a hold of the projected `mat-tab-label` inside a tab, but the problem is that this will also pick up label inside of nested tabs.
These changes add some safeguards so the labels don't get mixed up.
Fixes #23558.

fix(material/tabs): picking up mat-tab-label from child tabs

---

src/cdk/layout/media-matcher.spec.ts

Fixes a test failure that seems to have snuck into master because of #23571.

test(cdk/layout): fix test failure

---

src/cdk/stepper/stepper.md
src/material/autocomplete/autocomplete.md
src/material/button/button.md
src/material/datepicker/datepicker.md
src/material/menu/menu.md
src/material/select/select.md
src/material/stepper/stepper.md

Individual commits for your convenience
```
docs(multiple): table format keyboard shortcuts
Reformats all keyboard shortcut sections to tables and changes all
`<kbd>` elements to stop using ALL CAPS, which can be read by
screen-readers one letter at a time.
```
```
docs(material/select): expand a11y section
Expands the select's a11y section with additional guidance and background on its ARIA treatment.
```
```
docs(material/button): expand a11y section
Expands the buttons accessibility section with additional information on
disabling anchors, icons, and toggle buttons.
```
cc @zarend @amysorto

docs(button, select): update a11y sections

---

src/material-experimental/mdc-select/select.spec.ts
src/material/select/select.spec.ts
src/material/select/select.ts

Fixes that the select throws if the `selected` value is accessed before everything is initialized.
Fixes #23371.

fix(material/select): error if selected value is accessed too early

---

src/cdk/overlay/overlay-ref.ts
src/cdk/overlay/overlay.spec.ts

The `OverlayRef.dispose` method is meant to destroy the overlay immediately, without waiting on any events, which is useful for tests or when the overlay has already animated away. The problem is that we use the `detachBackdrop` method which will animate the backdrop away and trigger a `setTimeout` in case the backdrop didn't animate.
These changes avoid timeouts by removing the backdrop immediately on destroy. This reduces the number of `flush` calls that we need to be done by the consumer.

fix(cdk/overlay): avoid unnecessary timeouts when disposing of overlay

---

src/cdk/overlay/overlay-container.ts
src/cdk/platform/features/test-environment.ts
src/cdk/platform/public-api.ts
src/material/core/common-behaviors/common-module.ts
tools/public_api_guard/cdk/platform.md

Fixes that the sanity checks were running on some testing environments like Jest.
These changes also move the test environment check into a centralized place so that it's easier to keep up to date.
Fixes #23365.

fix(material/core): avoid running sanity checks on some test environments

---

src/material-experimental/mdc-menu/_menu-theme.scss

The spec and MDC implementation use the text color for the icon as well. This changes our MDC-based menu implementation to be in line with those.

fix(material-experimental/mdc-menu): use primary text color for menu icons

---

CHANGELOG.md

docs: release notes for the v12.2.7 release

---

src/dev-app/badge/badge-demo.html
src/material/badge/badge.spec.ts
src/material/badge/badge.ts
tools/public_api_guard/material/badge.md

Previously, `MatBadge` was applying the provided description as an `aria-label` to the badge content element, which is a child element of the badge host. Then it was _also_ applying an `aria-describedby` to that same content element. The end result is that the badge was being treated mainly as text content for a control, which isn't really the best way to convey its complementary nature. This behavior was causing problems in NVDA, where the badge content was overriding the host button's label.
This change makes the badge content itself `aria-hidden` and applies the badge description to the badge's _host_ element via `aria-describedby` and completely removes any setting of `aria-label`. It also makes a handful of minor cleanup refactorings.
cc @zarend @amysorto

fix(material/badge): correctly apply badge description

---

src/cdk/drag-drop/directives/drag.spec.ts
src/cdk/drag-drop/directives/drag.ts

Makes possible to use the following syntax to make dialogs draggable:
```html
<ng-container cdkDrag cdkDragRootElement=".cdk-overlay-pane">
<h1 mat-dialog-title class="dialog-draggable" cdkDragHandle>Title</h1>
<div mat-dialog-content>Content</div>
</ng-container>
```
Because of `ng-container` renders to comment and HTML comment doesn't have `.closest()` method we can use `element.parentElement.closest` for `rootElementSelector` searching.
**P.S.:** provided HTML code was working till cdk **v12.2.6** and stopped working on **>= v13.0.0-next.2**. Not sure what was changed.

fix(cdk/drag-drop): allow using cdkDragRootElement w/ comment tag

---

src/universal-app/DEBUG.md
src/universal-app/prerender.ts

Server side rendered kitchen sync app was written inside the test sandbox execution directory, which is deleted after test execution when the is executed without `--sandbox_debug` option thus we couldn't retrieve the `index-prendered.html` file using the command `echo $(bazel info bazel-bin)/src/universal-app/index-prerendered.html`

test: write pre-rendered univeral html file to bazel bin dir

---

CHANGELOG.md

docs: release notes for the v12.2.8 release

---

src/material-experimental/mdc-menu/_menu-theme.scss

We already fixed this for menu items, but MDC also sets the wrong
typography level on the menu content element, which can bleed through
into people's custom menu content.

fix(material-experimental/mdc-menu): Use body1 typography for menu content

---

src/cdk/a11y/focus-monitor/focus-monitor.ts
src/cdk/a11y/live-announcer/live-announcer.ts
src/cdk/overlay/overlay-ref.ts
src/cdk/platform/BUILD.bazel
src/cdk/platform/features/test-environment.ts
src/cdk/tsconfig-tests.json
src/material-experimental/mdc-chips/chip-row.ts
src/material-experimental/mdc-dialog/dialog-container.ts
src/material-experimental/mdc-snack-bar/snack-bar-container.ts
src/material/bottom-sheet/bottom-sheet-ref.ts
src/material/dialog/dialog-ref.ts
src/material/snack-bar/snack-bar-container.ts
src/material/snack-bar/snack-bar-ref.ts
src/material/tooltip/tooltip.ts
tools/public_api_guard/material/tooltip.md

In #23374 we expanded the logic that checks for test environments to cover Jest and Mocha. The problem is that we were checking against the `window` which won't work in a Node environment, because the global variables are attached to the `global` object, not the `window`, even though there may be a fake `window` declared by the test tooling.
These changes resolve the issue by first checking against `global` before falling back to `window`.
Fixes #23365.

fix(material/core): sanity checks not disabled for node-based test environments

---

src/cdk/drag-drop/drag-ref.ts

https://github.com/angular/components/issues/23655

fix(cdk/drag-drop): error when preview is destroyed before animation completes

---

src/material/select/select.spec.ts

Fixes a unit test that started failing, because it tries to scroll the page down, but there isn't enough content for it to scroll.

test(material/select): fix failing unit test

---

DEV_ENVIRONMENT.md
src/dev-app/index.html

The `index.html` of the dev app assumes that the `DEV_APP_VARIABLES` global variable will always be present, but that's not the case when it is deployed. This causes an error which prevents the Google Maps script from loading.
These changes add a null check, as well as some docs about the `variables.json`.

build: fix error when dev app is deployed

---

.prettierrc
integration/linker/link-packages-test.mjs
integration/npm-packages-from-runfiles.mjs
integration/ts-compat/helpers.mjs
scripts/create-legacy-tests-bundle.mjs
scripts/github/fetch-workflow-artifact.mjs
tools/angular/create_linker_esbuild_plugin.mjs
tools/angular/esbuild.config.mjs
tools/esbuild/esbuild-amd-config.mjs
tools/spec-bundling/esbuild.config-tmpl.mjs

Updates to the latest version of the `dev-infra` package and fixes that we weren't enforcing formatting on `.mjs` files.

build: update dev-infra package and format mjs files

---

src/cdk/a11y/_index.scss

fix `assitive` -> `assistive`. 
There are no same typo in public API documentation. https://material.angular.io/cdk/a11y/overview

docs(a11y): fix typo

---

CHANGELOG.md

docs: release notes for the v13.0.0-rc.3 release

---

packages.bzl

Updates the peer dependency ranges for the v13 stable version:
* v13.0.0 of Angular Components requires at minimum a stable v13 version
of Angular framework (no pre-releases allowed once we hit stable)
* For RxJS v7, minimum `7.4.0` is needed as that version comes with a
ES2015 distibution wired up in the `package.json`, allowing for better
optimized applications. This matches with `@angular/core` and the CLI.
https://github.com/angular/angular/commit/48aa0039ea75693f751b26474029efdb6c22377://github.com/angular/angular/commit/48aa0039ea75693f751b26474029efdb6c223770

build: update peer dependency ranges for v13 stable release

---

CHANGELOG.md

docs: release notes for the v13.0.0 release

---

.github/actions/yarn-install/action.yml
.github/workflows/build-dev-app.yml

This commit fixes that the Github actions currently may cache undesired
files. e.g. when Bazel runs the `dist/` folder is populated and
symlinked with the execroot, where another clone of the `node_modules`
would be cached accidentally then. We use an explicit path instead of a
pattern as it has been recommended by the Github action documentation.
Additionally, we fix that the dev-app building on RBE occurs with 2
concurrent jobs due to the host containers only having 2 cores. We can
run more jobs in the RBE containers.

build: do not accidentally cache undesired files in github action

---

src/components-examples/material/sidenav/sidenav-disable-close/sidenav-disable-close-example.ts
src/components-examples/material/sidenav/sidenav-fixed/sidenav-fixed-example.ts
src/components-examples/material/sidenav/sidenav-mode/sidenav-mode-example.ts
src/components-examples/material/sidenav/sidenav-open-close/sidenav-open-close-example.ts
src/components-examples/material/sidenav/sidenav-overview/sidenav-overview-example.ts
src/components-examples/material/sidenav/sidenav-position/sidenav-position-example.ts
src/components-examples/material/sidenav/sidenav-responsive/sidenav-responsive-example.ts

Fixes that examples do not properly recognize webcontainer Stackblitz
instances. This causes some sidenav examples to not even work within
Stackblitz as a message `Please open on Stackblitz` is displayed.
Fixes #23895.

refactor: fix examples not recognizing webcontainer stackblitz instances

---

CHANGELOG.md

Adds a detailed breaking change note for the Sass tilde change,
and cleans up some other auto-generated notes.

docs: add detailed breaking change note for Sass tilde change

---

src/cdk/a11y/focus-monitor/focus-monitor.ts
src/cdk/a11y/live-announcer/live-announcer.ts
src/cdk/overlay/overlay-ref.ts
src/cdk/platform/BUILD.bazel
src/cdk/platform/features/test-environment.ts
src/material-experimental/mdc-chips/chip-row.ts
src/material-experimental/mdc-dialog/dialog-container.ts
src/material-experimental/mdc-snack-bar/snack-bar-container.ts
src/material/bottom-sheet/bottom-sheet-ref.ts
src/material/dialog/dialog-ref.ts
src/material/snack-bar/snack-bar-container.ts
src/material/snack-bar/snack-bar-ref.ts
src/material/tooltip/tooltip.ts
src/tsconfig-legacy.json
tools/public_api_guard/material/tooltip.md

In #23636 the test environment check was changed so that it looks for the test objects either on `window` or `global`, however it looks like this isn't enough to pick up Jest which isn't published on either.
These changes simplify the setup by looking up the value globally and disabling the type checking error with `@ts-ignore`. We can't use `declare const` for it, because it causes issues in g3.
I've also reverted some of the `any` types that had to be added in #23636.
Fixes #23365.

fix(material/core): test environment check not picking up jest

---

src/google-maps/google-map/google-map.spec.ts
src/google-maps/google-map/google-map.ts
tools/public_api_guard/google-maps/google-maps.md

Added mapInitialized event which is emitted when the map is initialized and returns the map instance.
For #23703

feat(google-maps): Getting google.maps.Map instance

---

src/material-experimental/mdc-chips/chip-input.ts
src/material/chips/chip-input.ts

It is initialized in the constructor, so there is no chance of it being
undefined.

fix(material/chips): Declare that MatChipInput.inputElement is always defined

---

src/material/form-field/form-field.html

The position of the outline gap depends on the size of the prefix, but we weren't set up to update it when that happens.
Fixes #23863.

fix(material/form-field): update outline gap when prefix changes

---

src/cdk-experimental/dialog/dialog-container.ts
src/cdk-experimental/menu/menu-bar.ts
src/cdk-experimental/menu/menu-item.ts
src/cdk-experimental/menu/menu.ts
src/cdk-experimental/popover-edit/lens-directives.ts
src/cdk-experimental/popover-edit/table-directives.ts
src/cdk/coercion/coercion.md
src/cdk/stepper/stepper-button.ts
src/cdk/text-field/autosize.ts
src/cdk/tree/nested-node.ts
src/cdk/tree/toggle.ts
src/cdk/tree/tree.ts
src/material-experimental/mdc-button/button-base.ts
src/material-experimental/mdc-chips/chip.ts
src/material-experimental/mdc-list/interactive-list-base.ts
src/material-experimental/mdc-list/list-base.ts
src/material/input/input.ts
src/material/menu/menu-item.ts
src/material/menu/menu-trigger.ts
src/material/sidenav/drawer.ts
src/material/tree/node.ts
src/material/tree/tree.ts
tools/public_api_guard/cdk/stepper.md
tools/public_api_guard/cdk/tree.md
tools/public_api_guard/material/menu.md
tools/public_api_guard/material/sidenav.md
tools/public_api_guard/material/tree.md

We had some workarounds with `HostListener` and `HostBinding` which go against our conventions. They were used to support ViewEngine, but they are no longer necessary.

refactor(multiple): clean up host decorator workarounds

---

src/cdk/a11y/focus-monitor/focus-monitor.ts
src/cdk/a11y/live-announcer/live-announcer.ts
src/cdk/overlay/overlay-ref.ts
src/cdk/platform/BUILD.bazel
src/cdk/platform/features/test-environment.ts
src/cdk/tsconfig-tests.json
src/material-experimental/mdc-chips/chip-row.ts
src/material-experimental/mdc-dialog/dialog-container.ts
src/material-experimental/mdc-snack-bar/snack-bar-container.ts
src/material/bottom-sheet/bottom-sheet-ref.ts
src/material/dialog/dialog-ref.ts
src/material/snack-bar/snack-bar-container.ts
src/material/snack-bar/snack-bar-ref.ts
src/material/tooltip/tooltip.ts
tools/public_api_guard/material/tooltip.md

**Note:** this is the 12.2.x version of #23722.
In #23636 the test environment check was changed so that it looks for the test objects either on `window` or `global`, however it looks like this isn't enough to pick up Jest which isn't published on either.
These changes simplify the setup by looking up the value globally and disabling the type checking error with `@ts-ignore`. We can't use `declare const` for it, because it causes issues in g3.
I've also reverted some of the `any` types that had to be added in #23636.
Fixes #23365.

fix(material/core): test environment check not picking up jest (#23722)

---

src/material-experimental/mdc-slide-toggle/slide-toggle.spec.ts
src/material-experimental/mdc-slide-toggle/slide-toggle.ts
src/material/slide-toggle/slide-toggle.spec.ts
src/material/slide-toggle/slide-toggle.ts

The `tabindex="-1"` on the host node was causing VoicerOver to read out the slide toggle as a group and to read out the label twice. These changes remove the `tabindex` like we've done for `mat-radio` and `mat-checkbox` in the past.

fix(material/slide-toggle): remove tabindex from host node

---

src/material-experimental/mdc-chips/chip-option.ts
src/material-experimental/mdc-chips/chips.scss
src/material/chips/chips.scss

Currently the single-selection chip shows that it's selected by changing its background color, but that doesn't work in high contrast mode. These changes add a thicker outline when the chip is selected.

fix(material/chips): add selected indication in high contrast mode

---

src/cdk/overlay/position/connected-position.ts

fix(cdk/overlay): remove Optional decorator in ConnectedOverlayPositionChange constructor

fix(cdk/overlay): remove Optional decorator in ConnectedOverlayPositionChange constructor

---

package.json
yarn.lock

Update to the latest package which properly checks if the running version of ng-dev is the version
described in yarn lock.

build: update to latest @angular/dev-infra-private to address issues related to verifying environment

---

CHANGELOG.md
package.json

Reverts angular/components#23942
I'll redo the release after this PR is reverted

Revert "Bump version to "v12.2.13" with changelog."

---

CHANGELOG.md

docs: release notes for the v12.2.13 release

---

CHANGELOG.md

docs: release notes for the v13.0.1 release

---

src/cdk/bidi/bidi.md
src/cdk/bidi/dir.ts
src/cdk/bidi/directionality.ts
tools/public_api_guard/cdk/bidi.md

Adds support for the `auto` value of the `dir` attribute. The value gets resolved to `ltr` or `rtl` based on browser's locale.
Fixes #10186.
**Note:** I didn't include a test, because mocking `navigator.language` is difficult.

feat(cdk/bidi): support `auto` direction value

---

src/material/datepicker/calendar-body.html
src/material/datepicker/calendar-body.spec.ts

feat(material/datepicker): Add aria-current="date" to current date

---

src/cdk-experimental/dialog/dialog-module.ts
src/cdk/drag-drop/directives/drag.spec.ts
src/cdk/portal/portal.md
src/dev-app/main-module.ts
src/material-experimental/column-resize/column-resize-module.ts
src/material-experimental/mdc-button/fab.ts
src/material-experimental/mdc-dialog/module.ts
src/material-experimental/mdc-snack-bar/module.ts
src/material-experimental/mdc-tooltip/module.ts
src/material-experimental/selection/row-selection.ts
src/material-experimental/selection/selection-toggle.ts
src/material/bottom-sheet/bottom-sheet-module.ts
src/material/bottom-sheet/bottom-sheet.md
src/material/datepicker/date-range-input-parts.ts
src/material/datepicker/datepicker-module.ts
src/material/dialog/dialog-module.ts
src/material/dialog/dialog.md
src/material/snack-bar/snack-bar-module.ts
src/material/tooltip/tooltip-module.ts
src/material/tree/toggle.ts
src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.ts
src/universal-app/kitchen-sink/kitchen-sink.ts
tools/public_api_guard/material/datepicker.md
tools/public_api_guard/material/tree.md

Cleans up a bunch of workarounds and docs that were specific to ViewEngine. There are still more places to clean up, but I'm trying to make it easier to track down any potential failures.

refactor(multiple): clean up more ViewEngine-specific code

---

src/material-experimental/mdc-helpers/_mdc-helpers.scss
src/material-experimental/mdc-radio/radio.scss
src/material-experimental/mdc-slide-toggle/slide-toggle.scss
src/material-experimental/mdc-tabs/_tabs-common.scss

Reworks the theming for the MDC-based components so that it doesn't emit fallback values for CSS variables. This trims ~27kb from the dev app theme.
Also wraps the structural styles of the MDC-based radio button and slide toggle who have been converted to the new MDC theming API.

perf(multiple): don't emit fallbacks for CSS variables in experimental components

---

src/cdk/drag-drop/directives/drag.spec.ts
src/cdk/drag-drop/drag-ref.ts
src/cdk/testing/testbed/fake-events/event-objects.spec.ts
src/cdk/testing/testbed/fake-events/event-objects.ts

Includes the following fixes:
**fix(cdk/testing): fake events not propagating through shadow DOM**
Adds the `composed` flag to the fake event objects so that they can propagate through a `mode: 'open'` shadow root.
**fix(cdk/drag-drop): handle not working when it has a child inside shadom DOM**
Fixes that the children of the drag handle inside a shadow root weren't being detected. The problem was that we were using `_getEventTarget` to resolve the actual event target and using `contains` to verify that it's inside the handle. Since `contains` doesn't descend into shadow root, the call failed. These changes remove the `_getEventTarget` call since we can use the event `target` directly.
Fixes #23680.

Fix fake events inside shadow DOM and drag handles with shadow DOM children

---

src/material-experimental/mdc-tabs/tab-header.html
src/material-experimental/mdc-tabs/tab-header.ts
src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.html
src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.ts
src/material/tabs/paginated-tab-header.ts
src/material/tabs/tab-header.html
src/material/tabs/tab-header.ts
src/material/tabs/tab-nav-bar/tab-nav-bar.html
src/material/tabs/tab-nav-bar/tab-nav-bar.ts
tools/public_api_guard/material/tabs.md

Currently if one of the end tabs is selected and the user zooms in, we may end up showing the pagination unnecessarily. The issue comes from the fact that there's a transition on the ink bar which can cause the parent overflow while it is being measured.
These changes resolve the issue by measuring a different element.
Fixes #23724.

fix(material/tabs): pagination sometimes incorrectly shown after zoom

---

src/material-experimental/mdc-list/_interactive-list-theme.scss

Fixes that the `:hover` styles were overriding the `:focus` and selected effects of the MDC-based `mat-list-option`.

fix(material-experimental/mdc-list): don't override focus styles with hover

---

src/cdk/testing/test-element.ts
src/cdk/testing/testbed/unit-test-element.ts

This change is in response to feedback that it's not obvious that `TestElement.sendKeys` may behave differently in different environments. To help a tiny bit, we expand the JsDoc for `sendKeys` to mentions that it cannot reproduce native keyboard shortcuts in all environments.

docs(cdk/testing): expand JsDoc for sendKeys with limitations

---

tsconfig.json

Enables Angular strict template type checking for the IDE tsconfig,
matching with the flag set within the Bazel compilations.

build: enable angular strict template checking for IDE tsconfig

---

src/cdk/tree/tree.ts
src/material-experimental/mdc-slider/slider.ts
src/material/menu/menu.ts

Angular's QueryList first and last can actually be `undefined`,
although this is not reflected by their type
(this is a current bug in Angular: angular/angular#42563)
this commit adds non-null assertions to first and last references within the codebase
in preparation for solving the Angular bug without causing too many breaking changes
For more information see: angular/angular#43604

refactor(multiple): add non-null assertions first and last

---

.github/angular-robot.yml

Remove `cla: yes` from the require labels for merging as the CLACheck
tool no longer relies on labels.
Enforcement of the CLA being signed is still enforced by the status check
which is visible both in Github as well as checked by merge tooling.

ci: remove `cla: yes` from required labels

---

integration/size-test/index.bzl
tools/esbuild/index.bzl

Fixes the source-maps in the dev-app due to missing source contents
which could not be easily loaded through relative paths as the Bazel
execroot is not known to the e.g. Chrome devtools.

build: fix source maps in dev-app due to missing source contents

---

CHANGELOG.md
package.json

Bump version to "v13.0.2" with changelog.

---

src/material/core/common-behaviors/common-module.ts
tools/public_api_guard/material/core.md

Now that we don't need to think about ViewEngine, we can use `ngDevMode` to tree shake the sanity check messages.

perf(material/core): tree shake sanity checks

---

src/cdk/drag-drop/directives/drag.ts

When the boundaries were added to the `drag-drop` module, I assumed that users would always want the element to be contained inside the boundary, but it looks like there are some cases where that's not the case. These changes remove the error.
Fixes #23767.

fix(cdk/drag-drop): remove boundary error

---

src/material/bottom-sheet/bottom-sheet-container.ts

Currently, Angular runs change detection each time the microtask is resolved within the `_savePreviouslyFocusedElement`. It runs `element.focus()` after the microtask is resolved, which is a native DOM API and doesn't require Angular to run `tick()`.

perf(material/bottom-sheet): do not run change detection when focusing element

---

src/material-experimental/mdc-slider/_slider-theme.scss
src/material/core/theming/_theming.scss

Fixes a couple of places where we were using the deprecated `map-get` function from Sass.

refactor(material-experimental/mdc-slider): clean up leftover deprecated function usage

---

CONTRIBUTING.md

Looks like commit message types and scopes are outdated.

docs: update commit message guidelines

---

src/cdk-experimental/menu/menu.ts
src/material-experimental/mdc-form-field/form-field.ts
src/material-experimental/mdc-list/list-option.ts
src/material-experimental/mdc-list/selection-list.ts

Fixes a few cases where we weren't destroying the MDC foundation in our own components. There's also a case where we were overriding the `ngOnDestroy` from a parent component, but we weren't calling it from the override.

fix(multiple): some experimental components not cleaned up completely

---

CHANGELOG.md

docs: release notes for the v13.0.3 release

---

src/material-experimental/mdc-checkbox/_checkbox-theme.scss

We were adding the ripple variables to the MDC checkbox theme, even though we weren't actually using it. These changes remove the variables which shaves off ~30kb from the theme.

fix(material-experimental/mdc-checkbox): reduce amount of emitted theme css

---

src/cdk/drag-drop/directives/drag.spec.ts
src/cdk/drag-drop/drop-list-ref.ts

Fixes a regression caused by #19116 where dragging the last item into another container and returning it back to the initial one would insert the item into the first index of the list, rather than the last one. The issue was caused by the fact that we relied on the item to always be inserted at the end of the list of there is no position reference, but the condition was superseded by the condition that inserts it at the beginning of the list.
Fixes #23865.

fix(cdk/drag-drop): last item not returned at initial index when sorting is disabled

---

src/material/core/error/error-options.ts
tools/public_api_guard/material/core.md

To be able to use the `ErrorStateMatcher` also for determining the state of `FormGroups`, I think the signature might be changed to accept `AbstractForm` instead of `FormControl`. The relevant properties are all part of the `AbstractForm`, so I don't expect any breaking behavior.

feat(material/core): change ErrorStateMatcher to accept AbstractForm

---

tools/dgeni/templates/method.template.html

The 'parameter.description' => 'parameter.content' change was made earlier, but as I see now there is no documentation for method parameters on material.angular.io site.
I found that the information for method parameters are stored in the 'description' field.

Fix missing method parameter documentation

---

src/material-luxon-adapter/adapter/luxon-date-adapter.spec.ts
src/material-luxon-adapter/adapter/luxon-date-adapter.ts

Add firstDayOfWeek option to be able to change first day of week behaviour through MAT_LUXON_DATE_ADAPTER_OPTIONS

feat(material-luxon-adapter): add option to set first day of week

---

src/material-experimental/mdc-slider/slider.ts

Adds a proper error when the MDC slider is missing a thumb. Currently we eventually hit a runtime error which isn't easy to debug.
Fixes #24057.

fix(material-experimental/mdc-slider): throw error when thumb is missing

---

guides/theming.md

Fix typo:
- pink-bluegray.css > pink-bluegrey.css

docs(material/prebuilt-themes): fix wrong theme filename

---

src/components-examples/material/datepicker/datepicker-inline-calendar/datepicker-inline-calendar-example.html

Fixes the calendar UI not updating on selection

docs(material/datepicker): use two-way data-binding

---

src/components-examples/material/chips/chips-autocomplete/chips-autocomplete-example.html
src/components-examples/material/chips/chips-autocomplete/chips-autocomplete-example.ts
src/components-examples/material/chips/chips-input/chips-input-example.html
src/components-examples/material/chips/chips-input/chips-input-example.ts

Do not set the `selectable` and `removable` default values explicitly in the examples.

docs(material/chips): use defaults for input bindings

---

src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.ts

Fixes a build failure due to an unformatted file.

build: fix formatting failure

---

CHANGELOG.md

docs: release notes for the v13.0.4 release

---

CHANGELOG.md
package.json

Also this PR cherry-picks the changelog for v13.1.0-rc.0 into the master branch so that the changelog is up to date.

Update next branch to reflect new release-train "v13.2.0-next.0".

---

CHANGELOG.md

Cherry-picks the changelog from the "13.1.x" branch to the next branch (master).

docs: release notes for the v13.1.0 release

---

src/material-experimental/mdc-snack-bar/snack-bar.spec.ts
src/material/snack-bar/snack-bar.spec.ts

The snack bar tests were logging `'dir-with-view-container' is not a known element` errors, because the component wasn't added to the `declarations` after the `entryComponents` cleanup. This didn't break the CI, because Angular uses `console.error` for unknown element errors.

test(material/snack-bar): fix error logs in tests

---

src/material-experimental/mdc-tabs/_tabs-common.scss
src/material/tabs/_tabs-common.scss

Removes the `content` declaration from the tab chevrons. Usually it doesn't have an effect, but according to the discussion on #24085, it may cause an unnecessary tab stop.

fix(material/tabs): remove CSS content from chevron element

---

src/material/stepper/step-header.html
src/material/stepper/stepper.spec.ts

Fixes that the text inside the icon was being read out when the user interacts with the stepper header using assistive technology.

fix(material/stepper): assistive technology reading out stepper icon

---

src/material/schematics/ng-update/migrations/theming-api-v12/migration.ts
src/material/schematics/ng-update/test-cases/v12/misc/theming-api-v12.spec.ts

Fixes that the theming API migration would replace the `$swift-ease-in` inside a variable like `$swift-ease-in-duration`, because the regex would partially match the name.
Fixes #24013.

fix(material/schematics): don't replace variables contained within the names of other variables in theming API migration

---

src/material/schematics/ng-update/migrations/hammer-gestures-v9/import-manager.ts

Cleans up a temporary workaround that was used to land support for TS 4.5.

refactor(material/schematics): clean up workaround for TS 4.5

---

src/material-experimental/mdc-slide-toggle/slide-toggle.html
src/material-experimental/mdc-slide-toggle/slide-toggle.spec.ts

Both are equally valid to mark the control as not required, but setting
it to false generates a bunch of false-positive lint errors in google3

fix(material-experimental/mdc-slide-toggle): remove aria-required rather than setting to false

---

.bazelrc
integration/ng-add/BUILD.bazel
integration/ng-add/karma.conf.js
integration/ng-add/package.json
integration/ng-add/yarn.lock
integration/ng-update-v13/BUILD.bazel
integration/ng-update-v13/package.json
integration/ng-update-v13/yarn.lock
tools/defaults.bzl

Runs the integration tests in sandbox and with RBE. This should
improve the stability of the integration tests significantly. i.e.
solving the issue/conflicts with a system-global Yarn cache.

build: run integration tests in sandbox and with RBE

---

src/material/datepicker/calendar-body.html

Fixes double nav stops when navigating the calendar-body with voiceover
. Fixes this by putting `aria-hidden="true"` on the
`.mat-calendar-body-cell-preview`, since that element is only visual,
and is not for giving semantic info to the a11y tree.
fixes #24082

fix(material/datepicker): fix duplicate nav stop with Voiceover

---

src/material-experimental/mdc-table/_table-theme.scss
src/material-experimental/mdc-tooltip/_tooltip-theme.scss

These imports internally are not meant to be visible to us. Changing to be the intended MDC-approved import path for getting theme files
CARETAKER NOTE: Patch this change with cl/413151231 to correct the dependencies and enable strict dependency checks for the future.

fix(multiple): correct tooltip and table MDC style import paths

---

guides/theming.md

docs(theming): fix seprate typo

---

src/material-experimental/package.json
src/material/package.json

* Adds `@angular/platform-browser` to the `material` package.json since we have dependencies on it in a lot of modules.
* Adds several missing dependencies (`animations`, `cdk`, `common`, `forms` and `platform-browser`) to the package.json in `material-experimental`.
Fixes #24146.

build: add unlisted dependencies to package.json

---

src/material-experimental/mdc-theming/BUILD.bazel
src/material-experimental/mdc-theming/prebuilt/deeppurple-amber.scss
src/material-experimental/mdc-theming/prebuilt/pink-bluegrey.scss
src/material-experimental/mdc-theming/prebuilt/purple-green.scss
src/material-experimental/package.json

Adds the same set of prebuilt themes to experimental as in the stable package.

build: add all prebuilt themes to experimental

---

src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
src/cdk/overlay/position/flexible-connected-position-strategy.ts

Currently, when zooming in Safari in macOS and iOS the overlay is positioned
at the wrong place, offset by the zoom offset (left / top).
This fix corrects this by adding/subtracting the corresponding offset.
Screenshot in Safari 15.1 on macOS with activated zoom:

fix(cdk/overlay): fix positioning when zooming in Safari

---

src/cdk/text-field/autosize.spec.ts
src/cdk/text-field/autosize.ts

Fixes that the string "undefined" would be used as the placeholder of an autosize `textarea` if the value is `undefined`.
Fixes #24154.

fix(cdk/text-field): handle undefined placeholder

---

src/material/stepper/step-header.scss

Fixes that the icon in the step header was being rendered outside of the circle of the page direction changes. This seems to be a browser rendering issue due to the fact that we were applying a `position: absolute` and a `transform` both on the icon and its parent. Since this is unnecessary, I've removed the styles from the icon and added an extra `display: flex` to fix the centering.
Fixes #24046.

fix(material/stepper): icon not centered in header if direction changes

---

src/cdk/testing/harness-environment.ts
src/cdk/testing/selenium-webdriver/selenium-web-driver-harness-environment.ts
src/cdk/testing/testbed/testbed-harness-environment.ts
tools/public_api_guard/cdk/testing.md

Any time we were creating a new test element, we were giving it a new stabilization callback. These changes reuse the same one between all elements in order to reduce the amount of memory for each element.

refactor(cdk/testing): reuse stabilize callback when creating test element

---

src/cdk/schematics/ng-update/migrations/tilde-import-v13/tilde-import-migration.ts
src/cdk/schematics/ng-update/test-cases/v13/misc/tilde-import-v13.spec.ts

Expands the tilde migration to also drop the `.scss` file extensions.
Fixes #24162.

fix(cdk/schematics): remove file extensions in tilde migration

---

.gitignore

Adds .vimrc and .nvrc to the .gitignore file. This aligns components with how
angular/angular does it
https://github.com/angular/angular/blob/master/.gitignore.

build: add .vimrc to gitignore

---

src/components-examples/material/tabs/index.ts
src/components-examples/material/tabs/tab-nav-bar-with-panel/tab-nav-bar-with-panel-example.css
src/components-examples/material/tabs/tab-nav-bar-with-panel/tab-nav-bar-with-panel-example.html
src/components-examples/material/tabs/tab-nav-bar-with-panel/tab-nav-bar-with-panel-example.ts
src/dev-app/mdc-tabs/mdc-tabs-demo.html
src/dev-app/tabs/tabs-demo.html
src/material-experimental/mdc-tabs/module.ts
src/material-experimental/mdc-tabs/public-api.ts
src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.spec.ts
src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.ts
src/material-experimental/mdc-tabs/testing/tab-harness-filters.ts
src/material-experimental/mdc-tabs/testing/tab-nav-bar-harness.ts
src/material-experimental/mdc-tabs/testing/tab-nav-panel-harness.ts
src/material/tabs/public-api.ts
src/material/tabs/tab-nav-bar/tab-nav-bar.spec.ts
src/material/tabs/tab-nav-bar/tab-nav-bar.ts
src/material/tabs/tabs-module.ts
src/material/tabs/testing/tab-harness-filters.ts
src/material/tabs/testing/tab-nav-bar-harness.ts
src/material/tabs/testing/tab-nav-bar-shared.spec.ts
src/material/tabs/testing/tab-nav-panel-harness.ts
tools/public_api_guard/material/tabs-testing.md
tools/public_api_guard/material/tabs.md

Fixes https://github.com/angular/components/issues/23706.
* Adds a new `MatTabNavPanel` component that is intended to be used with `MatTabNav`. `MatTabNavPanel` renders the `tabpanel`, `MatTabNav` renders the `tablist`.
* Adds a new optional `[tabPanel]` input to `MatTabNav` that accepts a `MatTabNavPanel`. Allows `MatTabNav` to make changes to `MatTabNavPanel` (i.e. `aria-labelledby`).
* If `[tabPanel]` is provided, `MatTabNav` acts as an ARIA tabs. Otherwise, it continues to act as links within a navigation landmark (no change from status quo).
* Adds unit tests for new behavior.
* Change made in both non-MDC and MDC tabs.

Refactor MatTabNav as ARIA tabs with a new MatTabNavPanel component and [tabPanel] input.

---

src/material-experimental/mdc-checkbox/_checkbox-theme.scss
src/material-experimental/mdc-checkbox/checkbox.scss
src/material-experimental/mdc-list/_list-option-theme.scss
src/material-experimental/mdc-list/_list-theme.scss
src/material-experimental/mdc-list/list-option.scss

Switches the MDC-based checkbox to the non-deprecated styles.

fix(material-experimental/mdc-checkbox): switch to non-deprecated styles

---

src/material-experimental/mdc-dialog/dialog.scss

MDC have started including their own `border` in high contrast mode so our `outline` isn't necessary anymore.

fix(material-experimental/mdc-dialog): remove extra outline in high contrast mode

---

src/material-experimental/mdc-select/select.scss
src/material-experimental/mdc-select/select.spec.ts

Increases the maximum height of the MDC-based select panel in order to partially show the next option so that it is easier to see when the panel is scrollable.
Related to b/211518654.

fix(material-experimental/mdc-select): change max height to show scrollability

---

src/material-experimental/mdc-select/_select-theme.scss

Cleans up the MDC-based select's theme by removing the dependency on `@material/select` and the variable overrides since we weren't including any of MDC's mixins.

refactor(material-experimental/mdc-select): remove dependency on @material/select

---

src/cdk/table/cell.ts
src/material/table/_table-flex-styles.scss
src/material/table/table.md

Cleans up the workarounds for IE in the table module.

refactor(material/table): clean up IE workarounds

---

.github/CODEOWNERS

Updating this to shuffle more code reviews from myself to @andrewseguin

build: reduce jelbourn presence in code owners

---

src/components-examples/material/radio/radio-ng-model/radio-ng-model-example.css

Fixes that the radio button width spans the entire page in one of the live examples.
Fixes #24158.

docs(material/radio): fix button width

---

src/material-experimental/mdc-helpers/_focus-indicators.scss
src/material/core/focus-indicators/_focus-indicators.scss

Most components have special handling for high contrast mode which can cause double focus indication when strong focus indication is disabled.
These changes remove the strong focus indicators if such a case is detected.
Fixes #24097.
cc @zelliott

fix(material/core): disable strong focus indicators in high contrast mode

---

src/material/menu/menu-content.ts
src/material/menu/menu-item.ts
src/material/menu/menu-trigger.ts
tools/public_api_guard/material/menu.md

Moves the constructor deprecations out into a separate signature in order to make it easier to remove later on and to make the autocompletion in IDEs more accurate.
This is something we've wanted to do for a while, but ViewEngine didn't support multiple constructor signatures.
Also this is meant as a test to check if anything comes up during the presubmit. If it passes, we can roll this approach out to all constructors.

refactor(material/menu): use separate signature for deprecated constructor parameters

---

src/material-experimental/mdc-list/selection-list.spec.ts
src/material-experimental/mdc-list/selection-list.ts

Leverages the new selection change event that we landed upstream
in MDC. The notify action adapter method was not suitable for the
event notification as it did not fire for e.g. CTRL + A selections
and was generally, semantically not guaranteed to fire on actual
interactive selections (like native controls emit the change event).

fix(material-experimental/mdc-list): ensure selection change event fires properly

---

tools/defaults.bzl

Currently when using a `*` inside css code (e.g. `calc(... * ...)` in the typography) it will be expanded to files in the current directory (e.g. `calc ... bazel-out external ...`), which will break the tests. This PR fixes this by wrapping the variable usage with quotes.

build: prevent * expansion for static css content in ng_web_test_suite

---

src/material-experimental/mdc-button/fab.ts

Fixes that the FAB anchor was using the button inputs instead of the anchor ones.
Fixes #24145.

fix(material-experimental/mdc-button): incorrect metadata for fab anchor

---

src/material/core/selection/index.ts
src/material/core/selection/pseudo-checkbox/pseudo-checkbox-module.ts

Move the module definition next to the component definition so that the BUILD can be correctly defined (and enable taze). 
Caretaker note: Must patch cl/417987200 with this change

fix(material/core): move pseudo-checkbox module to same directory

---

CHANGELOG.md

Cherry-picks the changelog from the "13.1.x" branch to the next branch (master).

docs: release notes for the v13.1.2 release

---

package.json
yarn.lock

Update shelljs dependencies to ^0.8.5 to fix a vulnerability reported to shelljs.

build: update shelljs dependencies to "^0.8.5"

---

src/material-experimental/mdc-checkbox/_checkbox-theme.scss

Fixes that the MDC checkbox density styles were emitting fallbacks for CSS variables.

fix(material-experimental/mdc-checkbox): emitting fallback values for density CSS variables

---

src/material-experimental/mdc-tooltip/tooltip.spec.ts
src/material/tooltip/tooltip.spec.ts
src/material/tooltip/tooltip.ts

Currently the tooltip's `keydown` handler is on the trigger, which means that it won't fire if the trigger doesn't have focus. This could happen when a tooltip was opened by hovering over the trigger. These changes use the `OverlayKeyboardDispatcher` to handle the events instead.
Fixes #14278.

fix(material/tooltip): not closing if escape is pressed while trigger isn't focused

---

src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
src/material/autocomplete/autocomplete-trigger.ts
src/material/autocomplete/autocomplete.spec.ts

Fixes the `MatAutocompleteTrigger.optionSelections` stopping to emit when the list options has been swapped out.
Fixes #14777.

fix(material/autocomplete): optionSelections not emitting when the list of options changes

---

src/material/sidenav/drawer.ts
src/material/sidenav/sidenav-container.html
src/material/sidenav/sidenav.ts

When the consumer doesn't provide a `mat-sidenav-content`, we create one implicitly for them. The implicit content element has a `cdkScrollable` on it, which means that the it'll be registered on the `ScrollDispatcher` as a `CdkScrollable`, however since `MatSidenavContent` also extends `CdkScrollable`, it'll be registered again as a `MatSidenavContent`. These changes remove the extra `cdkScrollable` from the view in order to avoid the issue.
These changes also provide the sidenav content as a `CdkScrollable` for DI purposes.

fix(sidenav): implicit content element being registered twice with scroll dispatcher

---

src/material/core/common-behaviors/common-module.ts

Cleans up an extra `VERSION` constant that was put in place for something that shouldn't be an issue anymore.

refactor(material/core): remove extra version constant

---

src/dev-app/mdc-snack-bar/mdc-snack-bar-demo.ts
src/material-experimental/mdc-snack-bar/module.ts
src/material-experimental/mdc-snack-bar/public-api.ts
src/material-experimental/mdc-snack-bar/simple-snack-bar.ts
src/material-experimental/mdc-snack-bar/snack-bar.spec.ts
src/material-experimental/mdc-snack-bar/snack-bar.ts
src/material-experimental/mdc-snack-bar/testing/snack-bar-harness.spec.ts
src/material/snack-bar/snack-bar.ts
tools/public_api_guard/material/snack-bar.md

The MDC snack bar was set up to extend the base `MatSnackBar` directly which has a reference to the base snack bar components. This means that the code and styles from the base components will be pulled in, even though it isn't being used.
These changes move the snack bar logic into a base class that is extended by the default and MDC implementations.
While working on these changes, I also noticed that the simple snack bar components was called `SimpleSnackBar` in the default implementation and `MatSimpleSnackBar` for MDC. I've aligned the naming in order to make it easier to migrate.

fix(material-experimental/mdc-snack-bar): avoid hard reference to base components and align API

---

src/google-maps/map-info-window/map-info-window.spec.ts
src/google-maps/map-info-window/map-info-window.ts
src/google-maps/testing/fake-google-map-utils.ts
tools/public_api_guard/google-maps/google-maps.md

Allows for the `shouldFocus` flag to be passed when opening the info window.
Fixes #23829.

feat(google-maps): allow for info window focus behavior to be customized

---

src/material/core/theming/_theming.scss

Currently if an invalid hue is passed into `define-palette`, we silently emit nothing which can lead to confusion. These changes add an error to make it easier to debug.
Related to #23605.

fix(material/core): throw error if hue does not exist

---

src/material/datepicker/calendar-body.scss

Fixes that selected dates in the calendar didn't have focus indication in high contrast mode.
Fixes #22873.

fix(material/datepicker): add focus indication to calendar selected date in high contrast mode

---

src/material/slider/slider.spec.ts
src/material/slider/slider.ts

We allow for an out-of-bounds value to be assigned to a `mat-slider` programmatically, however our key press logic didn't account for it. This meant that it might appear as if the first key press is ignored if such a value is assigned by the user.
Fixes #23817.

fix(material/slider): first keypress ignored if out-of-bounds value is assigned

---

src/material/slider/slider.spec.ts
src/material/slider/slider.ts

Fixes that the slider was throwing errors on some non-cancelable `touchstart` events.
Fixes #23820.

fix(material/slider): avoid error on some touchstart events

---

src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
src/material/autocomplete/autocomplete-trigger.ts
src/material/autocomplete/autocomplete.spec.ts

Doesn't handle `ENTER` key presses and doesn't prevent their default action, if they have a modifier, in order to avoid intefering with any OS-level shortcuts.

fix(material/autocomplete): don't handle enter events with modifier keys

---

src/material-experimental/mdc-input/input.ts
src/material/input/input.ts
src/material/input/testing/shared-input.spec.ts
tools/public_api_guard/material/input.md

If an input has a `name` binding and an `ngModel`, the input harness won't be able to read the name from the DOM, because `ngModel` doesn't proxy it. These changes add the proxy behavior to the `MatInput` directive, similarly to what we we're doing for `required`, `placeholder`, `readonly` etc.
Fixes #18624.

fix(material/input): inconsistently reading name from input with ngModel

---

src/material-experimental/mdc-core/option/option.ts
src/material/core/option/option.ts
tools/public_api_guard/material/core.md

Makes `MatOption` generic so that consumers can type its `value` to something different from `any`.
Fixes #19456.

fix(material/core): make MatOption generic

---

src/material/slider/_slider-theme.scss

The slider theme selectors were a bit too broad which meant that it would automatically inherit the colors from a parent component, if the Material theming classes were used somewhere up the chain (e.g. a slider inside a tab group).
These changes use more specific selectors to avoid the issue.
Fixes #21271.

fix(material/slider): incorrectly inheriting color when nested inside component with theme

---

src/material/tabs/tab-group.ts
tools/public_api_guard/material/tabs.md

We try to update the pagination state of the tab group very sparingly, because it has performance implications. This means that we may miss some updates.
These changes expose a method so that consumers can trigger a recalculation on their own.
Fixes #23206.

feat(material/tabs): add API to update the pagination

---

src/material-experimental/mdc-progress-bar/progress-bar.spec.ts
src/material/progress-bar/progress-bar.spec.ts
src/material/progress-bar/progress-bar.ts
tools/public_api_guard/material/progress-bar.md

Fixes the progress bar not updating when its value is changed through the setter. Normally we don't really handle cases like this, but I decided to do it in this one, because:
1. We were already paying the payload price for the setter anyway so adding the `markForCheck` call won't be too expensive.
2. The progress bar is a bit of a special case where it might make sense not to go through the view to change a value. E.g. for something like a file upload where everything is being done in memory.
Fixes #18676.

fix(material/progress-bar): unable to change value through property setter

---

src/material/progress-spinner/BUILD.bazel
src/material/progress-spinner/progress-spinner.html
src/material/progress-spinner/progress-spinner.scss
src/material/progress-spinner/progress-spinner.ts
tools/public_api_guard/material/progress-spinner.md

Fixes that the progress spinner animation was broken on Safari on non-default zoom levels. The problem seems to be that the `transform-origin` was being offset by the amount of zoom. These changes work around it by setting the origin based on the zoom level.
Fixes #23668.

fix(material/progress-spinner): animation not working on some zoom levels in Safari

---

src/material-experimental/mdc-tabs/tab-body.ts
src/material-experimental/mdc-tabs/tab-group.html
src/material-experimental/mdc-tabs/tab-group.spec.ts
src/material-experimental/mdc-tabs/tab-group.ts
src/material-experimental/mdc-tabs/tab-header.ts
src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.ts
src/material-experimental/mdc-tabs/tab.ts
src/material/tabs/tab-group.html
src/material/tabs/tab-group.spec.ts
src/material/tabs/tab.ts
tools/public_api_guard/material/tabs.md

feat(material/tabs): label & body classes

---

src/cdk/layout/breakpoints-observer.ts

Fixes a workaround where we cast the MediaQueryList event listener to any because TypeScript didn't have proper types before TS 3.1.

chore: improve type safety in breakpoint observer

---

src/material/select/select.spec.ts
src/material/select/select.ts

Fixes the `MatSelect.value` property not being in sync with the `ControlValueAccessor` initial value on init.
Fixes #18423.

fix(select): component value not in sync with control value on init

---

src/material-experimental/mdc-select/select.spec.ts

Fixes a failure in the lint check due to a missing unit test.

build: add missing test

---

src/material-experimental/mdc-paginator/paginator.spec.ts
src/material/paginator/paginator.spec.ts
src/material/paginator/paginator.ts
tools/public_api_guard/material/paginator.md

Adds `readonly` support for paginator `pageSizeOptions`.
closes #24050

fix(material/paginator): allow readonly options (#24050)

---

src/material-experimental/mdc-list/testing/list-harness.spec.ts
src/material-experimental/mdc-list/testing/list-item-harness-base.ts
src/material-experimental/mdc-list/testing/selection-list-harness.ts
src/material/list/testing/list-item-harness-base.ts
src/material/list/testing/selection-list-harness.ts
src/material/list/testing/shared.spec.ts
tools/public_api_guard/material/list-testing.md

Currently only the selection list option has an `isDisabled` method, even though all item variants can be disabled. These changes move the method to the base class.
Fixes #24200.

fix(material/list): add isDisabled to all list item harnesses

---

src/material/core/theming/_palette.scss
src/material/list/_list-theme.scss

Fixes a couple of issues with the list item's disabled styles:
- In dark themes we were setting the disabled styles to black. This looks out of place since it's not how other components style themselves under dark themes.
- The disabled styles are somewhat similar to the selected styles. These changes also set the text color to the disabled text color to make it easier to distinguish.
Before and after for reference:

fix(material/list): fix up disabled list item styles

---

scripts/check-mdc-tests-config.ts
src/material/form-field/form-field.ts
src/material/input/input.spec.ts

We had a condition where `updateOutlineGap` wouldn't do anything if the label is empty. The problem is that the label could start off with content and then switch to being empty.
These changes set the gap labels to zero width if the gap element is empty.
Fixes #23943.

fix(material/form-field): outline gap not recalculated when switching to empty label

---

src/material/card/card.scss

Fixes that setting `mat-card-image` on a `picture` element doesn't work correctly.
Fixes #23649.

fix(material/card): handle picture element as mat-card-image

---

src/cdk/a11y/fake-event-detection.ts
src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
src/cdk/a11y/input-modality/input-modality-detector.spec.ts

A few months ago we changed the fake `mousedown` detection to use coordinates instead of the `buttons` property. This seems to have broken the detection on NVDA + Firefox on Windows where `buttons === 0`, but `offsetX` and `offsetY` are simulated to non-zero numbers.
These changes re-add the `buttons` check and keep the `offsetX` and `offsetY` checks for Webkit-based browsers.
Previous PR for reference: https://github.com/angular/components/pull/23029

fix(cdk/a11y): not detecting fake mousedown on firefox

---

src/material/autocomplete/autocomplete-trigger.ts
src/material/autocomplete/autocomplete.spec.ts

Currently we restore focus to the input and then we emit the change event, but we have a report that it may be making some use cases more difficult. From what I can tell, this shouldn't have much of an impact on existing users so these changes swap the order so that the focus event is last. This also feels more natural since we want focus restoration to happen after everything else.
Fixes #18650.

fix(autocomplete): restore focus after emitting option selected event

---

src/cdk/table/table.ts
tools/public_api_guard/cdk/table.md

With Release 13.1.2 a breaking change was introduced in cdk/table.
If a consumer has a class which extends CdkTable, compilation breaks
due to the newly introduced required constructor parameter _ngZone.
See PR: https://github.com/angular/components/pull/23885

fix(cdk/table): revert breaking change of CdkTable constructor

---

src/material/sidenav/drawer.html
src/material/sidenav/drawer.spec.ts
src/material/sidenav/drawer.ts
tools/public_api_guard/material/sidenav.md

We project all sidenavs before the content in the DOM since we can't know ahead of time what their position will be. This is problematic when the drawer is in the end position, because the visual order of the content no longer matches the tab order. These changes fix the issue by moving the sidenav after the content manually when it's set to `end` and then moving it back if it's set to `start` again.
A couple of notes:
1. We could technically do this with content projection, but it would only work when the `position` value is static (e.g. `position="end"`). I did it this way so we can cover the case where it's data bound.
2. Currently the focus trap anchors are set around the sidenav, but that's problematic when we're moving the element around since the anchors will be left at their old …

fix(material/sidenav): end position sidenav tab order not matching visual order

---

src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
src/cdk/table/table.ts
src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
src/material/autocomplete/autocomplete.spec.ts
src/material/select/select.spec.ts

The formatting CI check only verifies changed files which means that some failures snuck in when we merged a passing commit after them. I also fixed a couple of deprecated signature usages in tests.

build: fix unformatted files

---

src/cdk/a11y/key-manager/list-key-manager.spec.ts
src/cdk/a11y/key-manager/list-key-manager.ts
src/material-experimental/mdc-menu/menu.spec.ts
src/material/menu/menu.spec.ts

Fixes the `activeItem` on the `ListKeyManager` not matching the item at the `activeItemIndex`, if the `activeItem` is removed from the list.
Fixes #14345.
**Note:** this is a resubmit of #14407.

fix(cdk/a11y): activeItem out of date if active index is removed from ListKeyManager

---

src/cdk/a11y/key-manager/list-key-manager.ts

Follow-up to #14471. Uses `setActiveItem` instead of `updateActiveItem` which was missed when addressing the feedback.

refactor(cdk/a11y): use correct method when updating active item

---

src/cdk/a11y/key-manager/list-key-manager.spec.ts
src/cdk/a11y/key-manager/list-key-manager.ts
src/material-experimental/mdc-menu/menu.spec.ts
src/material/menu/menu.spec.ts

Reverting #14471
This reverts commit e61c2fa18cd855b8fafa0ef279de67d6ea33d8bc.

Revert "fix(cdk/a11y): activeItem out of date if active index is removed from ListKeyManager

---

src/material-experimental/mdc-button/_button-base.scss
src/material-experimental/mdc-button/_button-theme-private.scss
src/material-experimental/mdc-button/_button-theme.scss
src/material-experimental/mdc-button/_fab-theme.scss
src/material-experimental/mdc-button/_icon-button-theme.scss
src/material-experimental/mdc-button/button-base.ts
src/material-experimental/mdc-button/button.html
src/material-experimental/mdc-button/button.scss
src/material-experimental/mdc-button/fab.scss
src/material-experimental/mdc-button/icon-button.scss
src/material-experimental/mdc-button/icon-button.ts

Switches the MDC-based buttons to the new token-based theming API.

refactor(material-experimental/mdc-button): switch to new theming API

---

src/material-experimental/mdc-chips/chip-grid.ts

Fixes that the MDC chip grid was causing a "changed after checked" error when the last chip is removed, if it is used together with `mat-autocomplete`. The problem is that the chip grid focuses the input when the last chip is removed which then opens the autocomplete panel, resulting in an error.

fix(material-experimental/mdc-chips): fix changed after checked error when restoring focus to input

---

src/material-experimental/mdc-core/option/_option-theme.scss
src/material-experimental/mdc-core/option/option.scss

Related to internal b/215585751. Currently the typography styles for an option are set on `.mdc-list-item__primary-text` which is going to break existing overrides and may violate some linter checks. These changes restore the old behavior.

fix(material-experimental/mdc-core): make mat-option typography easier to override

---

src/material/list/list-item.html
src/material/list/list.scss

For the list component, fix chromevox screenreader bug where it
duplicated focus on each item in the action list. After focusing on a
`button` in the action list, linearly navigating forward moved focus to
the `.mat-list-item-content` of the same item.
Fixes this by change the list item content from a `div` to `span`, since
we're generally not supposed to use div's inside buttons.

fix(material/list): fix duplicate focus with chromevox on action-list items

---

src/material/expansion/expansion-panel-header.scss

Fixes the expansion panel's title not being centered vertically if the description is taller.
For reference from the docs:

fix(expansion-panel): title text not centered with taller description

---

src/material-experimental/mdc-form-field/form-field.scss

This came up in an internal discussion. The alignment of the prefix/suffix breaks if an app has `* { box-sizing: border-box }` which is fairly common.

fix(material-experimental/mdc-form-field): incorrect alignment with border-box alignment

---

src/material/core/ripple/_ripple.scss
src/material/core/ripple/ripple-renderer.ts

Fixes that sometimes the ripples weren't being clipped to the host element when they're inside a component with shadow DOM encapsulation on Safari.
Fixes #24028.

fix(material/core): ripples not being clipped on safari in shadow dom

---

renovate.json

Sets up renovate so that we stay up-to-date with the frequently
changing dev-infra changes in `angular/dev-infra`. For this dependency
it would be painful managing it manually since we consume it through
snapshot builds being pushed to a Github builds repo.
@josephperrott I think we would need to add this repo to the configured repositories
for the org-wide renovate application. I tested the config in my fork.

build: setup renovate to update shared dev-infra code

---

src/material-experimental/mdc-radio/_radio-theme.scss
src/material-experimental/mdc-radio/radio.html
src/material-experimental/mdc-radio/radio.scss

Reduces the bundle size of the MDC-based radio button by excluding styles we don't need. This shaves off ~15kb from the dev app bundle, although I believe that the styles are duplicated there so the real reduction is likely ~7.5kb.

perf(material-experimental/mdc-radio): reduce bundle size

---

src/material-experimental/mdc-checkbox/BUILD.bazel
src/material-experimental/mdc-checkbox/_checkbox-theme.scss
src/material-experimental/mdc-checkbox/checkbox.html
src/material-experimental/mdc-checkbox/checkbox.scss
src/material-experimental/mdc-checkbox/checkbox.ts
src/material-experimental/mdc-checkbox/module.ts

Reduces the bundle size of the MDC-based checkbox by:
* Excluding the ripple styles since we weren't using them.
* Disabling CSS variable fallbacks.
* Using the non-deprecated `static-styles` mixin instead of `core-styles`.
I've also reworked the checkbox not to depend on `@angular/common`. This likely won't have an effect on bundles since most apps include it, but we were barely using it.
These changes reduced the base component styles by about 14kb and the dev app theme styles by 4kb.

perf(material-experimental/mdc-checkbox): reduce bundle size

---

src/material/datepicker/calendar-body.html
src/material/datepicker/calendar-body.scss
src/material/datepicker/calendar-body.spec.ts
src/material/datepicker/calendar-body.ts
src/material/datepicker/testing/calendar-cell-harness.ts

Please see commit message for description of this change.
We can ignore the first commit for the build, that's from another PR. The diff is easier to read with `?w=1` (.e.g.  https://github.com/angular/components/pull/24171/files?w=1)

Put buttons in calendar cells

---

src/material/slide-toggle/slide-toggle.html
src/material/slide-toggle/slide-toggle.scss

We made similar adjustments to other components that had `div` elements inside the control `label` (#20990, #20986), but we never fixed it for the slide toggle.

fix(material/slide-toggle): remove divs nested inside label

---

src/material-experimental/mdc-tabs/_tabs-common.scss
src/material-experimental/mdc-tabs/_tabs-theme.scss

Reworks the MDC-based tabs to reduce their bundle size. In total, the JS bundle has decreased by ~10kb and the dev app theme by ~50kb. The changes include:
* Not using MDC's tab theme since we were basically only styling the tab label color. I've switched us over to the mixins for styling the label instead.
* Using the `static-styles` mixin instead of `without-ripple`.

perf(material-experimental/mdc-tabs): reduce bundle size

---

src/material/chips/chip.ts

Historically we've had to stop propagation on clicks so that clicking on a chip won't move focus to the first chip once the event bubbles up to the list. This isn't necessary as of #12856 which changes how we detect clicks from inside a chip. These changes remove the call since it can prevent people's global click listeners from firing.
Fixes #19759.

fix(material/chips): don't stop propagation on all click events

---

src/material/datepicker/datepicker.md

Changed link for Luxon Adapter Dependencies from https://momentjs.com/ to https://moment.github.io/luxon/

docs(material/datepicker): luxon link

---

src/material-experimental/mdc-checkbox/BUILD.bazel
src/material-experimental/mdc-checkbox/_checkbox-private.scss
src/material-experimental/mdc-checkbox/_checkbox-theme.scss
src/material-experimental/mdc-checkbox/checkbox.scss
src/material-experimental/mdc-list/_list-option-theme.scss
src/material-experimental/mdc-list/_list-option-trailing-avatar-compat.scss
src/material-experimental/mdc-list/_list-theme.scss
src/material-experimental/mdc-list/list-option.scss
src/material-experimental/mdc-list/list.scss

Reduces the amount of CSS generated by the MDC-based list by:
* Uses a similar approach to #24256 to reduce the amount of CSS for the internal checkbox. These changes reduce the styles even more, because we can exclude the hover/focus/pressed styles. This shaved off ~15kb.
* Disabling CSS variable fallbacks. This shaved off another 1-2kb.

perf(material-experimental/mdc-list): reduce bundle size

---

src/components-examples/material/tabs/index.ts
src/components-examples/material/tabs/tab-group-preserve-content/tab-group-preserve-content-example.html
src/components-examples/material/tabs/tab-group-preserve-content/tab-group-preserve-content-example.ts
src/material-experimental/mdc-tabs/tab-body.scss
src/material-experimental/mdc-tabs/tab-group.html
src/material-experimental/mdc-tabs/tab-group.spec.ts
src/material/tabs/tab-body.scss
src/material/tabs/tab-body.ts
src/material/tabs/tab-config.ts
src/material/tabs/tab-group.html
src/material/tabs/tab-group.spec.ts
src/material/tabs/tab-group.ts
src/material/tabs/tabs-animations.ts
src/material/tabs/tabs.md
tools/public_api_guard/material/tabs.md

Adds the `preserveContent` input which allows consumers to opt into keeping the content of off-screen tabs inside the DOM. This is useful primarily for edge cases like iframes and videos where removing the element from the DOM will cause it to reload.
One gotcha here is that we have to set `visibility: hidden` on the off-screen content so that users can't tab into it.
Fixes #19480.

feat(material/tabs): add the ability to keep content inside the DOM while off-screen

---

src/material/slider/slider.spec.ts
src/material/slider/slider.ts

When we get equal min & max value for the slider then we can get division by zero which leads to an improper style value for the background-size (Infinity%). This fix introduces a tiny function that checks if we deal with finite numbers during calculations where potentially division by zero may occur.
Fixes #23913

fix(material/slider): Ticks updated wrongly if the max property 0

---

src/material/datepicker/datepicker-content.html
src/material/datepicker/datepicker-content.scss

Contents of the datepicker is overflowing outside the boundary when a custom header with large height is provided. This is because of the fixed height provided for the _mat-calendar_ is not enough when custom headers height is big, so added a new class which will override the height of _mat-calendar_ to auto when custom header is given.

fix(material/datepicker): content overflowing when large custom header is provided

---

scripts/check-entry-point-setup.js
src/cdk/config.bzl
src/cdk/testing/protractor/README.md

This commit removes the deprecated protractor harness environment from the
public NPM package. Keeping the code in the repository until it can be removed
internally as well.
BREAKING CHANGE: The deprecated `angular/cdk/testing/protractor` entry-point has been removed.

refactor(cdk/testing): remove deprecated protractor harness environment from public API

---

renovate.json

Sub-projects do not necessarily have valid `package.json` files
because they might reference local-built packages through `file:<..>`
Renovate does not install dependencies on the top-level workspace
first, neither does it perform a build. We want to ignore such nested
sub-projects as these should be updated manually, ideally even kept
up-to-date by pointing from the sub-workspace to the root workspace
(using e.g. `file:/../../node_modules/rxjs`).
Relevant issue: https://github.com/angular/components/pull/24318

build: ignore integration test sub-projects within renovate

---

tools/dgeni/common/decorators.ts
tools/dgeni/common/private-docs.ts
tools/dgeni/common/tags.ts
tools/dgeni/docs-package.ts
tools/dgeni/processors/error-unknown-jsdoc-tags.ts
tools/dgeni/processors/resolve-inherited-docs.ts

This happened due to: https://github.com/angular/components/commit/9973f1df6457bef6720ce4faf2c24df37e638de3
Recently we added logic to exclude resolved external API docs from the Dgeni
pipeline, preventing them from being processed by the Dgeni JSDoc processor.
This was necessary due to a bug in Dgeni which resulted in runtime errors for
unknown JSDoc tags. Some tags from external API docs were unknown because
the framework repository uses different sets of annotations/tags.
At this point, it seemed reasonable to never add such external API docs to the
Dgeni pipeline, while also working around this runtime exception that way.
Now after seeing the results, it became clear that we still want to continue
processing external API docs as some of our public-facing API docs might end
up merging …

build: fix docs-content missing some inherited member description

---

src/material/tabs/_tabs-common.scss
src/material/tabs/tab-nav-bar/tab-nav-bar.html

Uses `button` elements, rather than styled `div`-s for the paginator buttons. This has the advantage of being more semantic and accessible, if we decided to make them focusable, and it stops calling the click listeners when the button is disabled (currently we do some expensive checks in them when we don't have to).

fix(material/tabs): use buttons for paginator

---

src/material-experimental/mdc-button/_button-theme.scss

The spec has a grey outline for outlined buttons, but we currently set it to the theme color.

fix(material-experimental/mdc-button): align outline color with spec

---

src/cdk/a11y/aria-describer/aria-describer.spec.ts
src/cdk/a11y/aria-describer/aria-describer.ts
tools/public_api_guard/cdk/a11y.md

Currently the `AriaDescriber` is set up to clear all description containers whenever it is instantiated, in order to avoid duplicates coming in from the server. The problem is that there are legitimate use cases where we could have multiple containers (e.g. multiple CDK instances in a micro frontend architecture).
These changes rework the internal setup of the `AriaDescriber` so that it only clears containers from server and it doesn't touch containers coming from other describer instances.
Fixes #23499.

fix(cdk/a11y): allow for multiple browser-generated description containers

---

WORKSPACE
package.json
yarn.lock

Updates to the latest version of `rules_sass` in order to fix an error that is currently breaking the build.

build: fix rules_sass error

---

src/cdk/overlay/position/flexible-connected-position-strategy.ts
src/material-experimental/mdc-menu/menu.spec.ts
src/material/menu/menu-trigger.ts
src/material/menu/menu.spec.ts
src/material/menu/menu.ts
tools/public_api_guard/material/menu.md

Currently we lock the menu into a position after it is opened so that it doesn't jump around when the user scrolls, but this means that if the amount of items changes, it might not be the optimal position anymore.
These changes add some code to re-calculate the position if the amount of items changes.
Fixes #21456.

fix(material/menu): adjust overlay size when amount of items changes

---

src/material-experimental/mdc-tabs/tab-body.scss

When `preserveContent` is enabled we add an extra `display: none` to prevent users from tabbing into hidden content. The selector was placed on the wrong element for the MDC-based tabs.

fix(material-experimental/mdc-tabs): CSS applied to wrong element when preserveContent is enabled

---

src/cdk/overlay/dispatchers/overlay-keyboard-dispatcher.spec.ts
src/cdk/overlay/dispatchers/overlay-keyboard-dispatcher.ts
src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.spec.ts
src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.ts
tools/public_api_guard/cdk/overlay.md

The `OverlayKeyboardDispatcher` adds a `keydown` event listener, which causes Angular to run change detections on any `keydown` event, tho its listener may behave as a "noop" (e.g. if there're no `keydownEvents` observers).
With these changes, the Angular zone will be re-entered only if there're any `keydownEvents` listeners.

perf(cdk/overlay): add event listeners for overlay dispatchers outside of zone

---

src/material/datepicker/calendar.scss
src/material/datepicker/month-view.html

Removes the `abbr` tag that is nested inside the cells of the day of the
week header. This is to fix #23477 where VoiceOver reads day of week
three times: 'Sunday, Sunday, Sunday...'
I tested this change on VoiceOverAfter this change and sometimes it read
the day of week twice and sometimes it read it once. When navigating
from a day on the calendar to the header it reads: "row 1 of 7 Sunday
S". When navigating from Sunday to Monday, it reads "Monday Monday M
Column 2 of 7".
Tested on macos 12.0.1 (21A559) with chrome Version 96.0.4664.110 (Official Build) (x86_64).
I'll leave this as a draft until I can at least test it on other
screenreaders.
fixes #23477

fix(material/datepicker): remove abbr from day of week header

---

src/material-experimental/mdc-chips/chip-input.ts
src/material/chips/chip-input.ts
tools/public_api_guard/material/chips.md

BREAKING CHANGE: `MatChipInputEvent.chipInput` is now a required property.

fix(material/chips): Make `MatChipInputEvent.chipInput` required.

---

renovate.json

With this change we group all the scorecard action dependencies so that Renovate opens a single PR.

ci: group all scorecard action dependencies

---

src/material-experimental/mdc-input/input.spec.ts
src/material/button/testing/shared.spec.ts
src/material/grid-list/BUILD.bazel
src/material/grid-list/grid-list.spec.ts
src/material/input/input.spec.ts
src/material/select/BUILD.bazel
src/material/select/select.spec.ts
src/material/sidenav/BUILD.bazel
src/material/sidenav/drawer.spec.ts

The workarounds shouldn't be necessary since we don't run tests against IE and legacy Edge anymore.

test: clean up IE/Edge test workarounds

---

src/material/datepicker/calendar-body.html
src/material/datepicker/calendar-body.ts
src/material/datepicker/month-view.html
src/material/datepicker/month-view.spec.ts
src/material/datepicker/month-view.ts
src/material/datepicker/multi-year-view.html
src/material/datepicker/multi-year-view.spec.ts
src/material/datepicker/multi-year-view.ts
src/material/datepicker/year-view.html
src/material/datepicker/year-view.spec.ts
src/material/datepicker/year-view.ts
tools/public_api_guard/material/datepicker.md

Please see commit message for description.
Would probably make the most sense to reviewers to look at code changes in this order:
1. `MatCalendarBody._scheduleFocusActiveCellAfterViewChecked` (used for refactoring handing `keydown` events without changing existing behavior)
2. `Tests added to src/material/datepicker/month-view.spec.ts` (the behavior change this PR creates)
3. `MatCalendarBody._cellFocused`
4. `MatMonthView._dateBecomesActive`

Listen for focus event on calendar cells

---

src/cdk/scrolling/virtual-scroll-viewport.spec.ts
src/cdk/scrolling/virtual-scroll-viewport.ts

Hi,
This fixes https://github.com/angular/components/issues/23577
The rendered content offset is incorrectly set in appendOnly; it should not change. This causes a weird behavior where the list jumps to the top
CC: @MichaelJamesParsons as you added the appendOnly flag in 8f052cc,, and @mmalerba as ( I think ) your are the main author for the virtual-scrolling

fix(cdk/scrolling): fix scrolling in appendOnly mode

---

src/material/datepicker/date-range-input.spec.ts
src/material/datepicker/datepicker-base.ts
src/material/datepicker/datepicker-content.html
src/material/datepicker/datepicker.spec.ts
tools/public_api_guard/material/datepicker.md

see commit message for description

Datepicker focus trap

---

src/material/datepicker/calendar-body.html
src/material/datepicker/calendar-body.ts
src/material/datepicker/month-view.html
src/material/datepicker/month-view.spec.ts
src/material/datepicker/month-view.ts
src/material/datepicker/multi-year-view.html
src/material/datepicker/multi-year-view.spec.ts
src/material/datepicker/multi-year-view.ts
src/material/datepicker/year-view.html
src/material/datepicker/year-view.spec.ts
src/material/datepicker/year-view.ts
tools/public_api_guard/material/datepicker.md

Reverts angular/components#24279
Rolling this back as it caused an [internal issue](http://cl/427216488).

Revert "Listen for focus event on calendar cells"

---

src/components-examples/material/datepicker/datepicker-date-class/datepicker-date-class-example.css

The changes in #24171 added a `background: none` to the datepicker cell which broke one of the examples, because it increased the specificity. I don't think that there's a good way to reduce the specificity without moving the entire cell template around again so these changes update the example to be more specific.
Fixes #24383.

docs(material/datepicker): fix custom class example

---

src/cdk/a11y/a11y-module.ts
src/cdk/scrolling/scrolling-module.ts
src/cdk/text-field/text-field-module.ts
src/components-examples/cdk/platform/index.ts
src/dev-app/platform/platform-demo-module.ts
src/material/core/datetime/index.ts
src/material/core/ripple/index.ts
src/material/sidenav/sidenav-module.ts
tools/public_api_guard/cdk/a11y.md
tools/public_api_guard/cdk/scrolling.md
tools/public_api_guard/cdk/text-field.md
tools/public_api_guard/material/core.md
tools/public_api_guard/material/sidenav.md

The `PlatformModule` is a noop so we don't need to import it.

refactor(multiple): remove PlatformModule usages

---

src/material-experimental/mdc-progress-spinner/progress-spinner.spec.ts
src/material-experimental/mdc-progress-spinner/progress-spinner.ts
src/material/progress-spinner/progress-spinner.spec.ts
src/material/progress-spinner/progress-spinner.ts
tools/public_api_guard/material/progress-spinner.md

Allows default color settings for spinner component.
closes #24352

feat(material/progress-spinner): add color to default options

---

src/material-experimental/mdc-menu/menu.spec.ts
src/material-experimental/mdc-menu/menu.ts
src/material/menu/menu-trigger.ts
src/material/menu/menu.spec.ts
src/material/menu/menu.ts
tools/public_api_guard/material/menu.md

Relates to internal bug b/218602349. We were calling `MatMenu.setPositionClasses` in order to set the classes if the position changes, but the call was outside of the `NgZone` so nothing was happening. These changes bring the call back into the `NgZone`.

fix(material/menu): position classes not updated when window is resized

---

src/material/chips/chip-list.ts
tools/public_api_guard/material/chips.md

Updates MatChipList to be consistent with MatInput, and fixes ExpressionChangedAfterItHasBeenCheckedError that occurs when chip-lists are content-projected into a mat-form-field, e.g.
```ts
<mat-form-field>
<ng-content select="mat-chip-list"></ng-content>
<mat-hint>foo</mat-hint>
</mat-form-field>
```
My use-case was creating a wrapper around `mat-form-field` to house various Mat-* formcontrol types.
MatSelect could use the same update.

feat(material/chips): update chip-list describedby to match input

---

src/material/datepicker/calendar-body.html
src/material/datepicker/calendar-body.ts
src/material/datepicker/month-view.html
src/material/datepicker/month-view.spec.ts
src/material/datepicker/month-view.ts
src/material/datepicker/multi-year-view.html
src/material/datepicker/multi-year-view.spec.ts
src/material/datepicker/multi-year-view.ts
src/material/datepicker/year-view.html
src/material/datepicker/year-view.spec.ts
src/material/datepicker/year-view.ts
tools/public_api_guard/material/datepicker.md

When a a date cell on the calendar recieves focus, set the active date
to that cell. This ensures that the active date matches the date with
browser focus.
Previously, we set the active date on keydown and click, but that was
problematic for screenreaders. That's because many screenreaders trigger
a focus event instead of a keydown event when using screenreader
specific navigation (VoiceOver, Chromevox, NVDA).
Note that this is the second attempt at this. First attempt was #24279,
which was reverted in #24380 due to an internal issue.
Fixes #23483

fix(material/datepicker): update active date on focusing a cell

---

src/material/datepicker/multi-year-view.spec.ts

This change only affects the unit tests and doesn't not affect
application code. It's a small improvement to the unit tests in the
multi-year view to use Jan 3 instead of Jan 1. This can catch more bugs
because we could catch that we're setting a date to the first of the
month when we're not supposed to.

refactor(material/datepicker): unit test with not the first of the month

---

packages.bzl
tools/release-checks/check-framework-peer-dependency.ts

Our current peer dependency for Angular CDK/Material v13 also allows
for Angular `v14.0.0-0`. This might work practically since Angular FW
v14 is usually compatible with Angular N-1 versions.
Although this peer dependency version is currently a little ambiguous since
it does not allow for all v14 pre-releases. Rather as per NPMs definition, the
current range does only allow for `v14.x.y` and `v14.0.0-(next|rc).X`
(excluding pre-releases for other minors)
It seems like it would be best to avoid this pre-release "range extension" in general
to avoid this ambiguity/inconsistency, while also fixing https://github.com/angular/angular-cli/issues/22654.
In general, it seems reasonable to say that Angular CDK v13 is compatible
with Angular FW v13, and Angular FW v14 (both of these ranges …

build: use less ambiguous peer dependency to Angular framework

---

CHANGELOG.md

docs: release notes for the v13.2.3 release

---

src/material-experimental/mdc-form-field/_form-field-high-contrast.scss
src/material-experimental/mdc-select/select.scss
src/material/form-field/form-field-fill.scss
src/material/form-field/form-field-legacy.scss
src/material/form-field/form-field-outline.scss
src/material/form-field/form-field.scss

Fixes that we weren't using the correct colors for disabled form field in high contrast mode on Windows.

fix(material/form-field): use correct color for form fields in high contrast mode

---

src/material-experimental/mdc-table/_table-theme.scss
src/material-experimental/mdc-table/table.scss

Uses a mixin from MDC that excludes some styles we don't need in order to reduce the bundle size. This shaves off ~3.3kb from the bundle and base component styles.

perf(material-experimental/mdc-table): reduce bundle size

---

src/cdk/drag-drop/directives/drag.spec.ts
src/cdk/drag-drop/drag-ref.ts

Removes the pointer events from the drag placeholder so that the user can't interact with it while the preview is animating.
Fixes #24403.

fix(cdk/drag-drop): stop pointer events on placeholder

---

src/material-experimental/mdc-chips/chip-grid.ts
src/material/chips/chip-list.ts
src/material/core/common-behaviors/error-state.ts
src/material/datepicker/date-range-input-parts.ts
src/material/input/input.ts
src/material/select/select.ts
tools/public_api_guard/material/core.md

The error state mixin provided in `@angular/material/core` currently
defines the `stateChanges` class member as part of the mixin. This
is unexpected as consumers might deal with the `stateChanges` member
differently. e.g. in some components the `stateChanges` field is
intended to show up in the docs, or the JSDoc descripton varies. e.g.
the observable could emit whenever form-field state changes, and it
should be updated, or it emits always when something changes (e.g.
even a component input which is not relevant for the form-field
control).
In general we want to avoid this member being defined in the mixin
as the mixin is rather about the error state, and not defining a
subject that can emit whenever "state" changes.

refactor(material/core): no longer define stateChanges in `mixinErrorState`

---

src/material-experimental/mdc-card/card.scss
src/material-experimental/mdc-dialog/dialog.scss
src/material-experimental/mdc-form-field/form-field.scss
src/material-experimental/mdc-menu/menu.scss
src/material-experimental/mdc-progress-bar/progress-bar.scss
src/material-experimental/mdc-progress-spinner/progress-spinner.scss
src/material-experimental/mdc-slider/slider.scss
src/material-experimental/mdc-snack-bar/snack-bar-container.scss

Since we don't support IE, we don't have to include a fallback for CSS variables in the MDC components.

refactor(multiple): disable CSS variable fallbacks in MDC components

---

guides/theming.md

We used to have this note in the old theming guide, but it looks like it was lost in-between the rewrites.
Fixes #24090.

docs: add note about mat-app-background to theming guide

---

src/material/sort/sort-header.html
src/material/sort/sort-header.ts
src/material/sort/sort.spec.ts
src/material/sort/sort.ts
tools/public_api_guard/material/sort.md

feat(material/sort): default arrow position in MatSortDefaultOptions

---

src/material-experimental/mdc-chips/chip-grid.spec.ts
src/material-experimental/mdc-form-field/_form-field-density.scss
src/material-experimental/mdc-form-field/_form-field-theme.scss
src/material-experimental/mdc-form-field/_mdc-text-field-structure-overrides.scss
src/material-experimental/mdc-form-field/directives/floating-label.ts
src/material-experimental/mdc-form-field/form-field.html
src/material-experimental/mdc-input/input.spec.ts
src/material-experimental/mdc-select/select.scss
src/material-experimental/mdc-select/select.spec.ts

Aligns the floating label setup of the MDC-based form field with the non-MDC version for better accessibility and to allow for easier customization. Includes:
* Moving the required asterisk into its own element.
* Reducing the specificity of the label typography.

refactor(material-experimental/mdc-form-field): align label setup with non-MDC version

---

src/material/radio/radio.html
src/material/radio/radio.scss

Currently the native `input` inside the radio button is collapsed down to 1px by 1px and moved to the bottom of the element which causes browsers to scroll the window down, rather than change the value, on the first click when the input is partially hidden. These changes fix the issue by having the input cover the entire button and hiding it with `opacity`. From my testing, using `opacity` versus `cdk-visually-hidden` doesn't make a difference for screen readers.
Fixes #19397.

fix(material/radio): not checked on first click if partially visible

---

src/material/button-toggle/_button-toggle-theme.scss
src/material/button-toggle/button-toggle.scss

* Fixes not being able to override the elevation of a button toggle. Similar to #7909, but avoids issues with the new appearance.
* Fixes some of the styles that are only intended to be applied in high contrast mode being active all the time. Seems like an issue while rebasing.
Fixes #14721.

fix(material/button-toggle): unable to override elevation and high contrast styling applied incorrectly

---

src/material-experimental/mdc-dialog/dialog-container.ts

The non-MDC dialog container uses `Default` change detection while the MDC one uses `OnPush` which causes issues for users trying to migrate. These changes align the behavior to make things easier.

fix(material-experimental/mdc-dialog): align change detection with non-MDC version

---

src/material/schematics/ng-update/migrations/hammer-gestures-v9/hammer-gestures-migration.ts
src/material/schematics/ng-update/migrations/hammer-gestures-v9/import-manager.ts
src/material/schematics/ng-update/migrations/package-imports-v8/secondary-entry-points-migration.ts

Replaces all of our usages of deprecated `ts.create*` and `ts.update*` APIs with their non-deprecated counterparts.

refactor(material/schematics): replace usages of deprecated TypeScript APIs

---

.circleci/config.yml
scripts/bazel/setup-remote-execution.sh

Fixes the stamping for snapshot builds and the artifact deployment job.

ci: fix stamping for builds performed in CI

---

src/material/radio/radio.scss

Fixes a regression caused by #19505 where clicking directly on the `input` element will prevent the click from reaching custom `click` listeners outside the radio button.

fix(material/radio): clicks not propagating to wrapper elements

---

scripts/circleci/setup-angular-snapshots.js

Our snapshot build jobs should also install the snapshots for the devkit
and schematics packages (owned by the tooling team). These need to match
up with the CLI package that is currently already updated by the snapshot
setup script.

build: install snapshot builds for angular-devkit and schematics

---

src/material-experimental/mdc-checkbox/checkbox.spec.ts
src/material-experimental/mdc-checkbox/checkbox.ts
src/material/checkbox/checkbox.spec.ts
src/material/checkbox/checkbox.ts

Follow-up from #16938. Clears the aria-* attributes from the host node so that they're not duplicated with the underlying input.

fix(material/checkbox): clear static aria attributes from host nodes

---

src/cdk/tree/tree.ts
tools/public_api_guard/cdk/tree.md

This is currently unimplemented and will allow a more reactive API for
the tree.

feat(cdk/tree): Add levelAccessor and childrenAccessor to CDK tree API 

---

src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
src/material/autocomplete/autocomplete-trigger.ts
src/material/autocomplete/autocomplete.spec.ts

Each autocomplete has a `click` listener on the body that closes the panel when the user has clicked somewhere outside of it. This breaks down if the panel is opened through a click outside of the form field, because we bind the listener before the event has bubbled all the way to the `body` so when it does get there, it closes immediately.
These changes fix the issue by taking advantage of the fact that focus usually moves on `mousedown` so for "real" click the input will have already lost focus by the time the `click` event happens.
Fixes #3106.

fix(material/autocomplete): closing immediately when input is focused programmatically

---

src/material/select/select.scss

Fixes the color of the select arrow not updating correctly when focusing and blurring in Safari. It seems like Safari wasn't recalculating the styles, for some reason.
Fixes #16522

fix(material/select): arrow highlighted state not updating in Safari

---

src/material-experimental/mdc-form-field/form-field.ts
src/material-experimental/mdc-input/input.spec.ts
src/material/form-field/form-field.ts
src/material/input/input.spec.ts
src/material/input/input.ts
tools/public_api_guard/material/form-field.md

feat(material/form-field): add color to default options (#24438)

---

src/cdk/drag-drop/directives/drag.spec.ts
src/cdk/drag-drop/drag-ref.ts
src/cdk/drag-drop/drop-list-ref.ts
src/cdk/drag-drop/parent-position-tracker.ts

We use the `ViewportRuler` to determine how much a page has been scrolled in order to compensate for it in some of the `ClientRect`-related calculations. This breaks down when the drop list is inside a dialog with blocked scrolling, because scroll blocking works by offsetting the `html` node which in turn throws off the `ViewportRuler`. These changes switches to reading the values off the `window` which won't be thrown off.
Fixes #14280.

fix(cdk/drag-drop): incorrectly sorting element inside dialog with blocked scrolling

---

src/material-experimental/mdc-list/list.spec.ts
src/material-experimental/mdc-list/selection-list.spec.ts
src/material-experimental/mdc-slider/slider.spec.ts
src/material-experimental/mdc-tabs/tab-group.spec.ts
src/material/core/ripple/ripple-ref.ts
src/material/core/ripple/ripple-renderer.ts
src/material/core/ripple/ripple.spec.ts
src/material/list/list.spec.ts
src/material/list/selection-list.spec.ts
src/material/tabs/tab-group.spec.ts
tools/public_api_guard/material/core.md

* Makes the ripple animations no longer dependent on `setTimeout` that does not always fire properly / or within the specified duration. (related chrome issue: https://bugs.chromium.org/p/chromium/issues/detail?id=567800)
* Fix indentation of a few ripple tests and that the speed factor tests are basically not checking anything (even though they will be removed in the future; they need to pass right now)
Fixes #12470

fix(ripple): not fading out on touch devices

---

src/material-experimental/mdc-select/_select-theme.scss

Targets the MDC select host node instead of just the value with the typography mixin. The previous approach would've broken any overrides and it didn't cover the select placeholder.

fix(material-experimental/mdc-select): target correct element with typography

---

src/material-experimental/mdc-autocomplete/autocomplete-trigger.ts
src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
src/material/autocomplete/autocomplete-trigger.ts
src/material/autocomplete/autocomplete.spec.ts

[Based on the spec](https://www.w3.org/TR/wai-aria-1.1/#aria-haspopup), `aria-haspopup` can be set to indicate what kind of popup the element has. These changes update the autocomplete one to show that it opens a listbox.

fix(material/autocomplete): use narrow value for aria-haspopup

---

CHANGELOG.md

docs: release notes for the v13.2.4 release

---

src/cdk/drag-drop/directives/drag.spec.ts
src/cdk/drag-drop/directives/drag.ts
src/cdk/drag-drop/directives/drop-list.ts
src/cdk/drag-drop/drag-events.ts
src/cdk/drag-drop/drag-ref.ts
src/cdk/drag-drop/drop-list-ref.ts
tools/public_api_guard/cdk/drag-drop.md

Exposes the native `MouseEvent` and `TouchEvent` objects in the various drag&drop events since they can contain useful information like which keys were pressed while dragging.
Fixes #17032.

feat(cdk/drag-drop): expose native event objects in custom events

---

src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
src/material/autocomplete/autocomplete-trigger.ts
src/material/autocomplete/autocomplete.spec.ts

Currently we hijack all up/down arrow key events, however this interferes with keyboard shortcuts such as shift + up arrow for marking all of the text. These changes stop intercepting the arrow keys, if they're used with a modifier.
These changes also fix an issue where all the mocked out key events had the `metaKey` set to `true` on some browsers.

fix(material/autocomplete): don't block default arrow keys when using modifiers

---

src/cdk-experimental/menu/context-menu.spec.ts
src/cdk-experimental/menu/menu-bar.spec.ts
src/cdk-experimental/menu/menu.spec.ts
src/cdk/table/table.spec.ts
src/cdk/testing/testbed/unit-test-element.ts
src/material-experimental/menubar/menubar.spec.ts
src/material/checkbox/testing/BUILD.bazel
src/material/checkbox/testing/shared.spec.ts
src/material/radio/testing/BUILD.bazel
src/material/radio/testing/shared.spec.ts
src/material/slide-toggle/testing/BUILD.bazel
src/material/slide-toggle/testing/shared.spec.ts
test/browser-providers.js
test/karma-browsers.json

See individual commits.
TL;DR: Updates us to the latest available Safari for iOS and macOS. Adjusts tests as needed, _and_ removed some test filter that disabled certain tests in `Firefox` that actually were hiding an underlying issue in `cdk/testing`.

ci: update remote browsers in saucelabs and browserstack

---

src/material-experimental/mdc-progress-spinner/progress-spinner.spec.ts
src/material/progress-spinner/progress-spinner-module.ts
src/material/progress-spinner/progress-spinner.spec.ts
src/material/progress-spinner/progress-spinner.ts
src/material/progress-spinner/public-api.ts
tools/public_api_guard/material/progress-spinner.md

Currently we have the `mat-spinner` directive which is a shortcut to a `mat-progress-spinner` with `mode="indeterminate"`. Since the spinner inherits all of the inputs from the progress spinner, there's nothing stoping people from changing the mode back to `determinate`, however the element will look half-broken because the host bindings assume that the mode won't change. These changes update the host bindings to allow switching between modes.
Fixes #14511.

fix(material/progress-spinner): unable to change mode on spinner directive

---

src/material/icon/icon.spec.ts
src/material/icon/icon.ts
tools/public_api_guard/material/icon.md

feat(material/icon): add default options

---

src/components-examples/material/slider/slider-configurable/slider-configurable-example.css
src/components-examples/material/slider/slider-configurable/slider-configurable-example.html

modify CSS of configurable slider example to adjust according to device

docs(material/slider): adjust CSS of configurable slider example

---

src/material-experimental/mdc-autocomplete/autocomplete-trigger.ts
src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
src/material/autocomplete/autocomplete-trigger.ts
src/material/autocomplete/autocomplete.spec.ts
tools/public_api_guard/material/autocomplete.md

Currently if the user clicks an autocomplete to open it, selects an option and then clicks again, the panel won't open, because we use `focus` and the input was focused already. These changes add an extra `click` listener so the panel can reopen.
Fixes #15177.

fix(material/autocomplete): reopen panel on input click

---

src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
src/material/autocomplete/autocomplete-trigger.ts
src/material/autocomplete/autocomplete.spec.ts
src/material/autocomplete/autocomplete.ts
tools/public_api_guard/material/autocomplete.md

Adds the `autoSelectActiveOption` input to `mat-autocomplete` which allows the consumer to opt into the behavior where the autocomplete will assign the active option value as the user is navigating through the list. The value is only propagated to the model once the panel is closed.
There are a couple of UX differences when the new option is enabled:
1. If the user presses escape while there's a pending auto-selected option, the value is reverted to the last text they typed before they started navigating.
2. If the user clicks away, tabs away or presses enter while there's a pending option, it will be selected.
The aforementioned UX differences are based on the Google search autocomplete and one of the examples from the W3C here: …

feat(material/autocomplete): add the ability to auto-select the active option while navigating

---

.github/CODEOWNERS
src/e2e-app/BUILD.bazel
src/e2e-app/e2e-app/e2e-app-layout.ts
src/e2e-app/main-module.ts
src/e2e-app/routes.ts
src/e2e-app/select/select-e2e-module.ts
src/e2e-app/select/select-e2e.ts
src/material/core/ripple/ripple-renderer.ts
src/material/core/ripple/ripple.spec.ts
src/material/select/BUILD.bazel
src/material/select/select.e2e.spec.ts

Follow-up to 65fb5f44911b3839c1f40ab87cf380381e030434.
We recently changed how animations are handled in the ripple. As part of this change
we accidentally broke the select <> ripple interaction. The select is special because
the option panel is removed from the DOM as soon as an option got clicked.
An option click will trigger a ripple that will usually still fade-in when the
panel is removed. Currently such ripples never will complete because the `transitionend`
event does not fire once removed from DOM. We should destroy the ripples when the
transition is canceled (e.g. through DOM removal).

fix(material/core): ripples persisting when container is removed from DOM while fading-in

---

src/material-experimental/mdc-menu/menu.spec.ts
src/material/menu/menu-errors.ts
src/material/menu/menu-trigger.ts
src/material/menu/menu.spec.ts
tools/public_api_guard/material/menu.md

Adds support for conditionally removing the menu from a menu trigger by passing in `null`.
Fixes #24030.

feat(material/menu): allow for menu to be conditionally removed from trigger

---

src/material-experimental/mdc-tooltip/tooltip.scss
src/material-experimental/mdc-tooltip/tooltip.spec.ts
src/material-experimental/mdc-tooltip/tooltip.ts
src/material/tooltip/tooltip.scss
src/material/tooltip/tooltip.spec.ts
src/material/tooltip/tooltip.ts
tools/public_api_guard/material/tooltip.md

Currently we hide the tooltip as soon as the pointer leaves the trigger element which may be problematic with larger cursors that partially obstruct the content.
These changes allow hover events on the tooltip and add extra logic so that moving to it doesn't start the hiding sequence.
Fixes #4942.

fix(material/tooltip): don't hide when pointer moves to tooltip

---

renovate.json

Sometimes Renovate proposes an update and we need to add some
manual fixups, like updating a size golden. For this we push to
same upstream branch.
Renovate will update the PR though when another new revision/version
becomes available, overriding the fixup and discarding it.
This happened quite often now and causes significantly more
work required by the dev-infra time.

ci: instruct renovate to not update/override merge ready PRs

---

src/material-experimental/mdc-menu/menu.spec.ts
src/material/menu/menu-trigger.ts
src/material/menu/menu.spec.ts

Currently we set `aria-haspopup` correctly on the menu trigger, however [according to the spec](https://www.w3.org/TR/wai-aria-1.1/#aria-haspopup) we can narrow the value down so that it indicates what kind of popup will be opened.

fix(material/menu): use narrower value for aria-haspopup on trigger element

---

src/material/datepicker/datepicker-input-base.ts
src/material/datepicker/datepicker.spec.ts

Fixes the datepicker not adding the `matDatepickerParse` error if the user enters an invalid string as their first value. The issue comes from the fact that we don't call the function from the `ControlValueAccessor` if the value hasn't changed, which means that the validator won't be re-run.
Fixes #11523.

fix(material/datepicker): matDatepickerParse error not being added on first invalid value

---

src/cdk/a11y/live-announcer/live-announcer.spec.ts
src/cdk/a11y/live-announcer/live-announcer.ts
tools/public_api_guard/cdk/a11y.md

Adds an input that allows the consumer to control how long it takes before the messages that are announced by `CdkAriaLive` to be cleared from the DOM.

feat(cdk/a11y): add input to control the duration of the aria live directive

---

src/material-experimental/mdc-paginator/paginator.html
src/material-experimental/mdc-paginator/paginator.spec.ts
src/material-experimental/mdc-paginator/public-api.ts
src/material/paginator/paginator.html
src/material/paginator/paginator.md
src/material/paginator/paginator.spec.ts
src/material/paginator/paginator.ts
tools/public_api_guard/material/paginator.md

Since we hide the underlying `MatSelect` inside the `MatPaginator`, the user doesn't have the ability to configure some of the inputs. These changes introduce an input that proxy some of the supported properties to the select.
Fixes #13646.

feat(material/paginator): add input for configuring the underlying select

---

src/material/schematics/ng-add/index.spec.ts
src/material/schematics/ng-add/schema.json
src/material/schematics/ng-add/schema.ts
src/material/schematics/ng-add/setup-project.ts

Adds a third option to the `ng-add` schematic that allows users to opt out of including any of the animations modules.

feat(material/schematics): add option not to include animations module in ng-add

---

src/cdk/overlay/position/global-position-strategy.spec.ts
src/cdk/overlay/position/global-position-strategy.ts
tools/public_api_guard/cdk/overlay.md

* Makes some things easier to follow in the `GlobalPositionStrategy`.
* Adds the ability to position a global overlay to the start and end of the viewport, based on its layout direction.
* Fixes the offset in the `center` position always being from the left.
* Adds better docs for the various methods.

feat(cdk/overlay): add start and end positions to GlobalPositionStrategy

---

src/material-experimental/mdc-menu/menu.scss
src/material-experimental/mdc-menu/menu.spec.ts
src/material/menu/menu-trigger.ts
src/material/menu/menu.scss
src/material/menu/menu.spec.ts
tools/public_api_guard/material/menu.md

Currently we use the hardcoded value of the menu padding to offset the panel so the two menu triggers align. Since the value is in TS, the logic breaks down if the user has set their own padding. These changes add some logic to compute the padding the first time a sub-menu is opened.
Fixes #16167.

fix(material/menu): account for menu padding different from the default

---

src/material-experimental/mdc-menu/menu.spec.ts
src/material/menu/menu-item.ts
src/material/menu/menu.spec.ts
src/material/menu/menu.ts
tools/public_api_guard/material/menu.md

Fixes the user's focus being lost if the active item is destroyed while a menu is open.
Fixes #14028.

fix(material/menu): focus lost if active item is removed

---

src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
src/material/autocomplete/autocomplete-trigger.ts
src/material/autocomplete/autocomplete.spec.ts

Fixes the first option not appearing as highlighted if the consumer has set `floatLabel="never"` and `autoActiveFirstOption`. It looks like we were depending on the `transitioned` event from the label to kick off the change detection that shows the highlight.
Fixes #13734.
**Note:** this is a resubmit of #14414.

fix(material/autocomplete): auto-highlighted first option not display correctly if the floating label is disabled

---

src/material/checkbox/_checkbox-theme.scss

The checkbox was using `secondary` text when it's disabled which is inconsistent and incorrect, because all other components use `disabled`.
Fixes #23081.

fix(material/checkbox): inconsistent disabled color

---

src/material/icon/icon-registry.ts
src/material/icon/icon.spec.ts
src/material/icon/icon.ts
src/material/icon/testing/fake-icon-registry.ts
tools/public_api_guard/material/icon-testing.md
tools/public_api_guard/material/icon.md

Allows for the consumer to pass in multiple classes to `MatIconRegistry.setDefaultFontSetClass`.
Fixes #10471.

feat(material/icon): allow multiple classes in setDefaultFontSetClass

---

scripts/generate-schematic-imports-map.ts
tools/tslint-rules/noHostDecoratorInConcreteRule.ts
tools/tslint-rules/noLifecycleInvocationRule.ts
tools/tslint-rules/noNestedTernaryRule.ts
tools/tslint-rules/noPrivateGettersRule.ts
tools/tslint-rules/noUndecoratedBaseClassDiRule.ts
tools/tslint-rules/noUndecoratedClassWithAngularFeaturesRule.ts
tools/tslint-rules/noUnescapedHtmlTagRule.ts
tools/tslint-rules/preferConstEnumRule.ts
tools/tslint-rules/requireBreakingChangeVersionRule.ts
tools/tslint-rules/settersAfterGettersRule.ts
tools/tslint-rules/symbolNamingRule.ts

Cleans up a few leftovers that were accidentally missed in:
0f8d5296cef49b5b7300b9523e350db2a151c5e5
FYI: I will set up a lint rule (we have on in dev-infra) once schematics are also migrated. For now this
is not really critical and the lint rule does not support globbing yet.

build: cleanup leftover from `esModuleInterop` in `tools`

---

src/material/expansion/expansion-panel-base.ts
src/material/expansion/expansion-panel-content.ts
src/material/expansion/expansion-panel.ts
src/material/expansion/expansion.spec.ts
src/material/expansion/public-api.ts
tools/public_api_guard/material/expansion.md

We use a `ContentChild` to determine what lazy content to render inside an expansion panel. When the lazy content is nested further down inside another expansion panel, all ancestor panels up the tree will pick up the lowest lazy content from the lowest level. These changes add a check to ensure that the lazy content is rendered out by the closest panel.
Fixes #14365.

fix(material/expansion): picking up lazy content from child component

---

src/cdk/drag-drop/drag-ref.ts

Fixes a null pointer exception that can happen if the page is scrolled before the user has scrolled the minimum distance. The problem was that we were expecting for the dimensions to be defined by the time the user has had the chance to scroll, but in some cases that can be circumvented.
These changes move the measurement to a getter method so that they're guaranteed to be available when they are requested.
Fixes #24497.

fix(cdk/drag-drop): error if preview dimensions are accessed too early

---

src/material/dialog/dialog.ts

Currently the `ComponentFactoryResolver` from the dialog config is only used for the dialog container. These changes switch to also use it for the dialog content component.
Fixes #17702.

fix(material/dialog): use passed in ComponentFactoryResolver to resolve dialog content

---

src/material/schematics/ng-add/index.spec.ts

As `addModuleImportToRootModule` is a void function, the test expectations in its result (value undefined) using '.not' would always be true. This change reads the file content and therefore gives the test its sense.

test(material/schematics): fix ng-add animations test

---

src/material-experimental/mdc-chips/testing/public-api.ts

This harness was missing from the export list - I assume it was done unintentionally

fix(material-experimental/mdc-chips): expose avatar harness

---

src/material/button-toggle/_button-toggle-theme.scss
src/material/core/theming/_theming.scss

Usually the theme divider color is rgba, which means that it can look differently, depending on the color behind it. As a result, the border of a selected button toggle is different from a deselected one, because its background color is darker. These changes switch to using a solid color to ensure that we have always have a consistent border.
These changes also add a new theming utility function that converts an rgba color to hex, if the consumer knows the background. We've been using it in a couple of places already, but now it's being moved out into a reusable function.
For reference:

fix(material/button-toggle): use solid border color

---

src/material-experimental/mdc-chips/chip-grid.spec.ts
src/material-experimental/mdc-chips/chip-grid.ts
src/material-experimental/mdc-chips/chip-listbox.spec.ts
src/material-experimental/mdc-chips/chip-listbox.ts
src/material-experimental/mdc-chips/chip-option.spec.ts
src/material-experimental/mdc-chips/chip-row.spec.ts
src/material-experimental/mdc-chips/chip-set.ts
src/material/chips/chip-list.spec.ts
src/material/chips/chip-list.ts
src/material/chips/chip.spec.ts
src/material/chips/chip.ts
tools/public_api_guard/material/chips.md

Allows for the ARIA `role` of the `mat-chip-list` and `mat-chip` to be overwritten.
Fixes #15787.

fix(material/chips): allow for role to be overwritten on chip list and chip

---

src/material/checkbox/_checkbox-theme.scss

This is along the same lines as #18742. The checkbox inherits its text color from the closest parent which may not be correct once the element is moved out into an overlay.

fix(material/checkbox): incorrect text color when placed inside an overlay with a dark theme

---

src/cdk/testing/protractor/protractor-element.ts
src/cdk/testing/public-api.ts
src/cdk/testing/selenium-webdriver/selenium-web-driver-element.ts
src/cdk/testing/test-element-errors.ts
src/cdk/testing/test-element.ts
src/cdk/testing/testbed/fake-events/type-in-element.ts
src/cdk/testing/tests/cross-environment.spec.ts
tools/public_api_guard/cdk/testing.md

Previously, calling `sendKeys` without any keys resulted in a runtime
exception `Cannot read X of undefined` error being thrown. This is because
the first element of the passed arguments to `sendKeys` has been considered
always truthy. This assumption is wrong since arbitrary amount of arguments
can be passed due to the spread parameter.
To ensure consistent and reasonable behavior of this function, we fix
the runtime exception mentioned above, but throw if no keys have been
determined (not necessarily only if the arguments length is zero).

fix(cdk/testing): TestElement sendKeys method should throw if no keys have been specified

---

src/material-experimental/mdc-dialog/_dialog-theme.scss
src/material-experimental/mdc-dialog/dialog.scss

Applied the values for the theming by isolating the theme color/typography styles included in the current mixin. Should match the existing styles, and I'll run an internal presubmit to double-check this is a no-op

feat(material-experimental/mdc-dialog): switch to new theming api

---

src/material-experimental/mdc-button/_button-theme.scss
src/material-experimental/mdc-button/_icon-button-theme.scss

The button's density styles currently have the same specificity as the structural styles which means that they'll usually be overwritten, unless they're nested inside another selector.
These changes add more specificity so that the density always has precedence.
Fixes #22728.

fix(material-experimental/mdc-button): density styles being overwritten by structural styles

---

.ng-dev/release.ts

Fixes the standalone release checks running outside of the `.ng-dev` config load (which
comes with the `global.ReleaseAction`). In standalone checks this variable is not
defined and therefore currently causes errors like:
```
/.ng-dev/release.ts:14
const actionProto = (global as any).ReleaseAction.prototype;
^
TypeError: Cannot read properties of undefined (reading 'prototype')
at Object.<anonymous>
```
We can fallback to the imported `ReleaseAction` constructor object if the global reference
is not provided. In such cases the monkey-patching is a noop anyway.

build: fix standalone release checks failing due to missing global `ReleaseAction` instance

---

src/dev-app/mdc-card/mdc-card-demo.html
src/material-experimental/mdc-card/card.scss

The card header margin was set up assuming that there would always be an avatar element, but that's not always the case. These changes add an extra check to avoid the extra margin.
Fixes #19069.

fix(material-experimental/mdc-card): remove extra margin if header doesn't have an avatar

---

src/material-experimental/mdc-select/select.spec.ts
src/material/select/select.spec.ts
src/material/select/select.ts

Fixes the disabled state of a `mat-select` falling out of sync with its form control if the control's group is swapped out with one that is disabled on init.
Fixes #17860.

fix(material/select): disabled state out of sync when swapping form group with a disabled one

---

src/cdk/table/text-column.ts
tools/public_api_guard/cdk/table.md

Allows for the text inside a text column to be centered.
Fixes #23920.

feat(cdk/table): allow text column to be centered

---

src/cdk/schematics/ng-update/devkit-migration-rule.ts

Previously the message was not very clear about what happened if reading the warning. The new wording states that a project is skipped during migrations which should be clearer to users.

docs(cdk/schematics): more precise warning for inexistent tsconfig

---

src/material-experimental/mdc-button/button-base.ts
src/material-experimental/mdc-button/button.spec.ts
src/material/button/button.spec.ts
src/material/button/button.ts

Fixes that the button component was always setting a `tabindex="0"` when it's placed on a link element. This is unnecessary, because links are in the tab order by default.
We actually had a test that has an assertion against this, but it was passing by accident because we weren't running change detection before making the assertion.

fix(material/button): avoid setting a tabindex on all link buttons

---

src/material/checkbox/_checkbox-theme.scss

This reverts commit f20122a4998f65c46452dc680adaec49cea7c0f5 which has some internal issues.

Revert "fix(material/checkbox): incorrect text color when placed inside an overlay with a dark theme (#19054)"

---

src/cdk/testing/testbed/unit-test-element.ts
src/cdk/testing/tests/cross-environment.spec.ts
src/cdk/testing/tests/test-main-component.html
src/cdk/testing/tests/test-main-component.ts

Fixes that the `UnitTestElement` wasn't dispatching `mouseover` and `mouseout` on `hover`/`mouseAway` like the browser would.
Fixes #24486.

fix(cdk/testing): dispatch mouseover and mouseout events in UnitTestElement

---

src/material/list/list.ts
src/material/list/selection-list.ts
src/material/list/testing/list-item-harness-base.ts
src/material/schematics/ng-update/data/constructor-checks.ts
src/material/schematics/ng-update/data/css-selectors.ts
tools/public_api_guard/material/list-testing.md
tools/public_api_guard/material/list.md

Removes the APIs that were marked for removal in version 13 in the `material/list` package.
* `mat-list-item-avatar` CSS class has been renamed to `mat-list-item-with-avatar`.
* `MatSelectionListChange.option` has been removed. Use `MatSelectionListChange.options` instead.
* `MatSelectionList.tabIndex` input has been removed.
* `tabIndex` parameter of the `MatSelectionList` constructor has been removed.
* `_focusMonitor` parameter of the `MatSelectionList` constructor is now required.
* `getHarnessLoaderForContent` has been removed from the various test item harnesses. Use `getChildLoader(MatListItemSection.CONTENT)` instead.

refactor(material/list): remove deprecated APIs for version 13

---

src/material-experimental/mdc-dialog/testing/BUILD.bazel
src/material-experimental/mdc-dialog/testing/dialog-opener.spec.ts
src/material-experimental/mdc-dialog/testing/dialog-opener.ts
src/material-experimental/mdc-dialog/testing/public-api.ts
src/material/dialog/testing/BUILD.bazel
src/material/dialog/testing/dialog-opener.spec.ts
src/material/dialog/testing/dialog-opener.ts
src/material/dialog/testing/public-api.ts
tools/public_api_guard/material/dialog-testing.md

This makes it trivial for users to open components in a dialog, avoiding the need to mock or inject dialog properties. See tests for how users could apply it

test: provide a test component that opens components in a dialog

---

src/cdk-experimental/dialog/dialog-container.ts
src/material/bottom-sheet/bottom-sheet-animations.ts
src/material/dialog/dialog-animations.ts

Reworks several components that usually contain projected content not to block animations within that content. This prevents things like expansion panels from appearing as open.
These changes are identical to #13888 which had to be reverted in the past.
Fixes #13870.

fix(multiple): don't block child component animations on open

---

src/material-experimental/mdc-dialog/dialog.spec.ts
src/material-experimental/mdc-dialog/dialog.ts
src/material/dialog/dialog-config.ts
src/material/dialog/dialog-container.ts
src/material/dialog/dialog.spec.ts
src/material/dialog/dialog.ts
tools/public_api_guard/material/dialog.md

For a long time we used to move focus into the dialog after the opening animation was finished, because it allowed for the content to settle in case something like an autocomplete needed to open. This approach has caused us accessibility issues in the past, because we've had to find ways to prevent the user from interacting with content behind the dialog while the opening animation is running.
Initially we used to move focus to the dialog container before transferring it into the dialog, but that ended up interrupting the screen reader. In a later change we started returning the previous dialog ref if the same kind of dialog is opened while the animation is still running. The problem with this approach is that it doesn't allow for multiple dialog to be opened quickly (see #24037).
These …

fix(material/dialog): don't wait for animation before moving focus

---

src/cdk/testing/harness-environment.ts

Currently locator functions accept a spread argument which technically allows for zero selectors to be passed in. This can result in weird runtime errors.
These changes add a runtime error if no selectors are passed in. 
Note that a previous iteration of these changes tried to enforce this with typings, but it resulted in breaking changes.

fix(cdk/testing): require at least one argument for locator functions

---

src/material/autocomplete/testing/autocomplete-harness.ts

The autocomplete harness has methods for retrieving the options of an
autocomplete. When this method is invoked, the options are determined
from the overlay DOM element, if available. If the panel is not in the DOM
(due to the autocomplete not being focused), the method will just return
an empty array, indicating that there are no options.
This is confusing for test authors and currently not well-defined, potentially
causing invalid tests that just pass by coincidence.
We want to throw when the panel is not open, raising awareness for such invalid
tests. In the future we may want to auto-focus the autocomplete to open the
panel (like `selectOption`).

feat(material/autocomplete): test harness should throw when options are requested but panel is closed

---

src/dev-app/mdc-tabs/mdc-tabs-demo.html
src/material-experimental/mdc-tabs/tab-group.scss
src/material-experimental/mdc-tabs/tab-group.ts
src/material-experimental/mdc-tabs/tab-nav-bar/tab-link.scss
src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.ts

Defaults the MDC tabs to stretch in order to align closer with the spec. A new `stretchTabs` input can be used to opt out.
Fixes #23295.

feat(material-experimental/mdc-tabs): default to stretched tabs

---

src/material-experimental/mdc-slider/slider.spec.ts
src/material-experimental/mdc-slider/slider.ts

Fixes a few null pointer errors if:
1. `setDisabledState` is called too early. This can't happen at the moment, but it showed up when trying to fix something in `@angular/forms` and it may become an issue in the future.
2. The component is destroyed before the initialization is complete. This showed up while investigating the first error.

fix(material-experimental/mdc-slider): fix a few null pointer exceptions

---

src/material/schematics/ng-generate/mdc-migration/BUILD.bazel
src/material/schematics/ng-generate/mdc-migration/rules/template-migration.ts
src/material/schematics/ng-generate/mdc-migration/rules/tree-traversal.spec.ts
src/material/schematics/ng-generate/mdc-migration/rules/tree-traversal.ts

* created tree-traversal.ts for storing tree operation helper fns
* moved visitElements to the new file
* created helper fns for parseTemplate, and tag name changes
* added unit tests which don't need to call the whole schematic

feat(material/schematics): tree operation helper functions

---

src/material/schematics/ng-generate/mdc-migration/rules/tree-traversal.spec.ts
src/material/schematics/ng-generate/mdc-migration/rules/tree-traversal.ts

* create and unit test addAttribute fn

feat(material/schematics): add fn for adding attrs to templates

---

src/material-experimental/mdc-slide-toggle/slide-toggle.spec.ts
src/material-experimental/mdc-slide-toggle/slide-toggle.ts
src/material/slide-toggle/slide-toggle.spec.ts
src/material/slide-toggle/slide-toggle.ts

Along the same lines as #15422 and #15368. Clears the static `name` attribute from the slide toggle's host node in order to prevent both the underlying input and the host from showing up in `document.getElementsByName` or `By.name`.

fix(material/slide-toggle): clear name from host node

---

src/cdk/overlay/_index.scss
src/cdk/overlay/overlay-ref.ts
src/cdk/overlay/overlay.spec.ts

When we start the detach sequence of a backdrop, we bind a `transitionend` event as well as a 500ms timeout in case the event doesn't fire. If the event fires before 500ms, we clear the timeout so users don't have to flush it in tests, however we had the following problems:
1. Transparent backdrops don't have a transition so they were always being cleaned up after the 500ms timeout.
2. We weren't clearing the timeout if the overlay was disposed while the backdrop transition is running. This meant that the timeout would still be in memory, even though the element was removed from the DOM.
3. We had a memory leak where the `click` and `transitionend` events weren't being removed from the backdrop if the overlay is disposed while detaching.
Basically all Material components had one of these …

fix(cdk/overlay): backdrop timeouts not being cleared in some cases

---

CHANGELOG.md

docs: release notes for the v13.2.6 release

---

src/material/datepicker/datepicker.md

docs(material/datepicker): require confirmation buttons for a11y
For the datepicker accessiblity documentation, add instructions to always
provide confirmation buttons. This prevents an accessibility issue where
selecting a date on the calendar gives no audio feedback of the selected date
(https://github.com/angular/components/issues/23568).
This commit only affects the docs and does not change source code.
Addresses https://github.com/angular/components/issues/23568

docs(material/datepicker): require confirmation buttons for a11y 

---

src/material-experimental/mdc-tabs/ink-bar.ts
src/material-experimental/mdc-tabs/tab-header.spec.ts
src/material/tabs/ink-bar.ts
src/material/tabs/paginated-tab-header.ts
src/material/tabs/tab-header.spec.ts

The tabs have a couple of `requestAnimationFrame` calls when checking for the size/position of elements which can cause tests to hang when they're in a background tab. The problem is that browsers block `requestAnimationFrame` when the browser is out of focus and test harnesses will wait for the call to resolve.
These changes switch to `NgZone.onStable` in an attempt to resolve the issue.
Fixes #23964.

fix(material/tabs): avoid timeouts in background tabs

---

src/material/icon/icon.scss

Clips any elements that are overflowing an icon. This avoids issues where parts of the icon could stick out and layouts.
Fixes #11826.
`mat-icon` elements now have `overflow: hidden`.

fix(material/icon): clip overflowing icon elements

---

scripts/check-mdc-tests-config.ts
src/dev-app/mdc-tabs/mdc-tabs-demo.html
src/material-experimental/mdc-tabs/README.md
src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.spec.ts
src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.ts
src/material/tabs/tab-nav-bar/tab-nav-bar.spec.ts
src/material/tabs/tab-nav-bar/tab-nav-bar.ts
src/universal-app/kitchen-sink-mdc/kitchen-sink-mdc.html
src/universal-app/kitchen-sink/kitchen-sink.html

This PR updates MDC nav tabs to throw an error if the `[tabPanel]` input is not provided. Note that no such logic is added to the non-MDC tabs.
Additionally:
* Update Material test cases to reflect that tab panel existing is the default case, while tab panel not existing is an exceptional/separate case.
* Update MDC test cases to reflect that tab panel existing is the default case, and remove tests for tab panel not existing entirely (as we now throw an error if a tab panel isn't provided).
* Updated MDC demos.
* Updated README with new delta between Material and MDC tabs.
* Fixed a minor bug in tabs (caught by unit tests) where an active and disabled tab would still have a tabindex of 0 (it should be -1).

feat(material/tabs): Throw error in MDC tabs if [tabPanel] input is not provided

---

src/material/schematics/ng-generate/mdc-migration/rules/components/card/card-template.spec.ts
src/material/schematics/ng-generate/mdc-migration/rules/components/card/card-template.ts
src/material/schematics/ng-generate/mdc-migration/rules/index.ts
src/material/schematics/ng-generate/mdc-migration/rules/template-migration.ts

* implement TemplateMigrator for mat-card
* add unit tests for card template migrations
* implement migration updates in TemplateMigration
* added CardTemplateMigrator to list of MIGRATORS

feat(material/schematics): impl card template migration

---

src/cdk/overlay/overlay-ref.ts

Cleans up a `console.log` that was accidentally left in as a part of bbe63555560df252b8f98cfa87adf443201e4cb5.

build: remove leftover log

---

src/cdk/drag-drop/directives/drag.spec.ts
src/cdk/drag-drop/drag-ref.ts

Currently we block the `dragstart` event on the entire drag element which doesn't account for its disabled state and for any existing handles.
Fixes #24533.

fix(cdk/drag-drop): only block dragstart event on event targets

---

src/components-examples/material/stepper/index.ts
src/components-examples/material/stepper/stepper-header-position/stepper-header-position-example.css
src/components-examples/material/stepper/stepper-header-position/stepper-header-position-example.html
src/components-examples/material/stepper/stepper-header-position/stepper-header-position-example.ts
src/material/stepper/stepper.html
src/material/stepper/stepper.md
src/material/stepper/stepper.scss
src/material/stepper/stepper.spec.ts
src/material/stepper/stepper.ts
tools/public_api_guard/material/stepper.md

Allows users to control where the header of a horizontal stepper is rendered. In some cases it might make more sense to have the buttons be under the content so that the user doesn't have to go back in the page layout in order to continue to the next step.

feat(material/stepper): add the ability to control the position of the header in a horizontal stepper

---

src/components-examples/material/dialog/dialog-animations/dialog-animations-example-dialog.html
src/components-examples/material/dialog/dialog-animations/dialog-animations-example.css
src/components-examples/material/dialog/dialog-animations/dialog-animations-example.html
src/components-examples/material/dialog/dialog-animations/dialog-animations-example.ts
src/components-examples/material/dialog/index.ts
src/dev-app/dialog/dialog-demo.html
src/dev-app/dialog/dialog-demo.ts
src/material/dialog/dialog-animations.ts
src/material/dialog/dialog-config.ts
src/material/dialog/dialog-container.ts
src/material/dialog/dialog.md
src/material/dialog/dialog.spec.ts
tools/public_api_guard/material/dialog.md

Since the dialog animation is on the `MatDialogContainer`, consumers aren't able to disable the animation. These changes add properties to the dialog config that allow consumers to set the duration of the dialog's enter and exit animations.
Fixes #3616.

feat(material/dialog): add the ability to control the animation duration

---

src/material/datepicker/calendar-body.ts
src/material/datepicker/calendar.spec.ts
src/material/datepicker/date-range-input.spec.ts
src/material/datepicker/datepicker-actions.spec.ts
src/material/datepicker/datepicker.spec.ts

Please see commit message for description.

Voiceover pagedown

---

src/material/dialog/dialog-animations.ts
src/material/dialog/dialog-config.ts
src/material/dialog/dialog-container.ts
src/material/dialog/public-api.ts

Even though we provide defaults when we construct the animation object, some internal cases break because there are no defaults in the animation definition itself. These changes provide the defaults in the animation definition as well.

fix(material/dialog): provide defaults for dialog animation

---

.github/workflows/build-dev-app.yml

We can remove the `GITHUB_ENV` sourcing since we changed how
RBE is configured: 26fc03e76c57c330afa0e460d18cbd602809db9b

build: cleanup preview dev-app github action workflow

---

.bazelrc

Switches the bazelrc away from deprecated options. See:
https://docs.bazel.build/versions/main/command-line-reference.html

build: switch bazelrc away from deprecated options

---

src/cdk/schematics/BUILD.bazel
src/cdk/schematics/update-tool/BUILD.bazel
src/material/schematics/BUILD.bazel

As part of v13, we manually added the prodmode/devmode target to schematic
build targets and set it to `es2015`. This was done since we still supported
NodeJS v12. This is no longer the case with v14 and we already removed the
NodeJS v12 integration test, so we can also remove the target override.

build: ship schematics as `es2020` similar to rest of the APF

---

scripts/docs-deploy/monitoring/index.ts

We can speed up the docs deployment & monitor jobs by not running the
rather slower a11y audit tests. These should just be run in the docs
repo. The standard audit lighthouse tests should be a sufficient
indicator of whether the page is up-and-running properly.
Ideally in the future we would have proper e2e tests for the docs
site, but even those will never guarantee a 100%-working page.

build: speed up docs deployment by not running a11y audit tests

---

src/material/datepicker/datepicker.md

Adds a note about how locale data should be provided for users that consume the `date-fns` adapter.
Fixes #24026.

docs(material/datepicker): add note about locale data in date-fns

---

src/components-examples/material/stepper/index.ts
src/components-examples/material/stepper/stepper-animations/stepper-animations-example.css
src/components-examples/material/stepper/stepper-animations/stepper-animations-example.html
src/components-examples/material/stepper/stepper-animations/stepper-animations-example.ts
src/material/stepper/public-api.ts
src/material/stepper/stepper-animations.ts
src/material/stepper/stepper.html
src/material/stepper/stepper.md
src/material/stepper/stepper.spec.ts
src/material/stepper/stepper.ts
tools/public_api_guard/material/stepper.md

Adds a new input called `animationDuration` that allows users to control the animation duration of a stepper, similarly to other components.
Fixes #17130.

feat(material/stepper): add input for controlling the animation duration

---

src/material/schematics/ng-generate/mdc-migration/rules/components/card/card-template.ts
src/material/schematics/ng-generate/mdc-migration/rules/template-migration.ts
src/material/schematics/ng-generate/mdc-migration/rules/template-migrator.ts

* simplify TemplateMigrator logic
* update CardTemplateMigrator impl
* changed from using a two-pass strategy for gathering context
then applying updates to using a one-pass approach which
stores updates, sorts them in reverse order, then applies
updates in one go
* all existing unit tests pass

refactor(material/schematics): change strategy for applying updates

---

src/material-experimental/mdc-radio/_radio-theme.scss
src/material-experimental/mdc-radio/radio.scss
src/material-experimental/mdc-radio/radio.ts

Fixes that the MDC-based radio button doesn't have hover indication, because it usually comes from the MDC ripple which we don't use.

fix(material-experimental/mdc-radio): add hover indication

---

.github/CODEOWNERS

Hi Kristiyan, though you might want to be a code owner for datepicker because you've been reviewing PRs for it.

build: add Kristiyan to datepicker code owners

---

src/material/datepicker/month-view.html

Use cdk-visually-hidden to announce the days of the week on the calendar header in screenreaders. Previously, this was done with an `aria-label` on the `th` element, but NVDA does not read aria-labels on table elements and well as some other static content.
Fix NVDA incorrectly announcing the days of the week as "M", "T",
etc. instead of "Monday".

fix(material/datepicker): use cdk-visually-hidden on calendar header

---

src/material/dialog/dialog-content-directives.ts
src/material/dialog/dialog.ts

Previously we had to walk the DOM in order to figure out which dialog ref belonged to a specific template dialog. We no longer need to do that if we provide an injector to the template portal.

refactor(material/dialog): use embedded injector to provide ref to template dialogs

---

src/material-experimental/mdc-core/_core-theme.scss

Adds a `mat-mdc-app-background` utility class similar to `mat-app-background`.

fix(material-experimental/mdc-core): add app background color

---

src/material/badge/_badge-theme.scss

This regression was introduced when the icon changed styles to be overflow hidden. This makes sure the host element always allows the badge to fully render outside of the host's bounding box

fix(material/badge): ensure overflow visible

---

src/material/card/card.scss

Fixes that the card targets all dividers which may include ones placed inside child components.
Fixes #23524.

fix(material/card): use more specific selector for divider override

---

CHANGELOG.md

docs: release notes for the v13.3.0 release

---

src/material-experimental/mdc-select/select.scss
src/material/select/select.scss

The `mat-select` trigger element has an `aria-owns` pointing to the overlay and `display: inline-table` in its CSS. The combination of these two causes Chrome to infer the element as a `table` which results in NVDA reading out "table" any time a select is opened.
These changes resolve the issue by using flexbox to lay out the select trigger instead.
Fixes #21480.

fix(material/select): NVDA reading out table when opening select on Chrome

---

src/cdk/a11y/focus-monitor/focus-monitor.ts

This is a resubmit of #14964.
Currently we have an `NgZone.run` call on each `focus` and `blur` event of a monitored event in order to bring its subscribers into the `NgZone`, however this means that we're also triggering change detection to any consumers that aren't subscribed to changes (e.g. `mat-button` only cares about the classes being applied). These changes move around some logic so that the `NgZone.run` is only hit if somebody has subscribed to the observable.
**Caretaker note:** this PR had to be reverted before (#15076) because there was an app that depended on the extra change detections. We may have to investigate further before we can merge this in again.

perf(cdk/a11y): avoid triggering change detection if there are no subscribers to stream

---

src/material/input/input.ts

We were adding `keyup` event listener on iOS platforms, but never removed it.

fix(material/input): resolve memory leak on iOS

---

src/material/autocomplete/autocomplete-trigger.ts

The `NgZone.onStable` always emits outside of the Angular zone, but the zone has not been
re-entered. This leads to change detection being called outside of the Angular zone and the
`autocomplete.opened` also was emitting values outside of the Angular zone.

fix(material/autocomplete): re-enter the Angular zone when the `NgZone.onStable` emits

---

src/cdk-experimental/dialog/dialog-container.ts
src/material/bottom-sheet/bottom-sheet-container.ts
src/material/dialog/dialog-container.ts
src/material/sidenav/drawer.ts

When we force focus on an element, we were adding a couple of event listeners that were never removed.

fix(multiple): memory leak when forcing focus

---

src/material/icon/icon.spec.ts
src/material/icon/icon.ts

Removes an IE-specific workaround that had some minor performance implications.

perf(material/icon): remove IE workaround

---

src/material-experimental/mdc-table/table.scss
src/material/core/style/_vendor-prefixes.scss
src/material/slider/slider.scss
src/material/table/table.scss

Removes some vendor prefixes that shouldn't be necessary anymore.

refactor(multiple): clean up vendor prefixes

---

src/material-experimental/mdc-input/input.spec.ts
src/material/datepicker/date-range-input.scss
src/material/form-field/form-field-input.scss
src/material/input/input.spec.ts
src/material/input/input.ts

The `legacy` form field appearance has a feature where it promotes the input placeholder to the form field label which introduces a problem where screen readers will read out the placeholder twice. Some time ago we added logic to clear the placeholder, but it seems to be a bit too aggressive since it also clears the placeholder for other appearances.
These changes scope the workaround only to the case when a placeholder would be promoted to a label.
Fixes #20903.

fix(material/input): preserve native placeholder on non-legacy appearances

---

scripts/create-legacy-tests-bundle.mjs
src/circular-deps-test.conf.js
tools/markdown-to-html/docs-marked-renderer.ts
tools/region-parser/region-parser.ts

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

refactor: replace deprecated String.prototype.substr()

---

WORKSPACE

The `16.14.0` NodeJS version is not provided in the Bazel NodeJS
rules and we cannot update since FW is blocked on the rules_nodejs
v5 update..

build: downgrade bazel nodejs version to work with m1

---

src/cdk/scrolling/virtual-scroll-viewport.spec.ts

Adds a test to the scrolling module for the case where the amount of data is reduced.

test(cdk/scrolling): add test for contracting range

---

integration/ts-compat/BUILD.bazel
package.json
src/material/schematics/ng-update/migrations/hammer-gestures-v9/import-manager.ts
yarn.lock

Removes our tests and compatibility code for TypeScript less than 4.6.

build: drop support for TypeScript 4.4 and 4.5

---

src/material-experimental/mdc-select/select.spec.ts
src/material/select/select.spec.ts
src/material/select/select.ts

Fixes values set through the `value` property not being propagated to the `value` in the `ControlValueAccessor`.
Fixes #10214.

fix(material/select): value set through property not being propagated to value accessor

---

integration/harness-e2e-cli/angular.json
integration/ng-add/angular.json
integration/ng-update-v13/angular.json
src/cdk/schematics/ng-generate/drag-drop/index.spec.ts
src/cdk/schematics/utils/get-project.ts
src/material/schematics/ng-add/index.spec.ts

The CLI has deprecated the `defaultProject` option which is causing errors in the snapshot check. These changes fix up our usages.

fix(material/schematics): remove usages of deprecated defaultProject option

---

src/cdk-experimental/menu/context-menu.ts
src/cdk-experimental/menu/menu-item-trigger.spec.ts
src/cdk-experimental/menu/menu-item-trigger.ts
src/cdk-experimental/menu/menu-item.spec.ts
src/cdk-experimental/menu/menu-item.ts
src/cdk/overlay/position/flexible-connected-position-strategy.ts
src/cdk/overlay/public-api.ts
src/dev-app/cdk-experimental-menu/cdk-menu-demo-module.ts
src/dev-app/cdk-experimental-menu/cdk-menu-demo.css
src/dev-app/cdk-experimental-menu/cdk-menu-demo.html
src/dev-app/cdk-experimental-menu/cdk-menu-demo.ts
src/material-experimental/menubar/menubar-item.ts
tools/public_api_guard/cdk/overlay.md

Addresses several TODOs that were left after the original implementation

feat(cdk-experimental/menu): allow configuration of typeahead and menu position

---

src/material/form-field/form-field.md

Fixes a typo under Form field appearance variants overview.
Fixes #24379.

docs(material/form-field): fix typo in form-field overview

---

src/material-experimental/mdc-chips/chip-edit-input.ts

The chip edit input was using innerText to set the text of an element. This change was prompted by a Google-internal check that warns about `innerText`, but we generally want to use `textContent` anyway as it is more standard.

fix(material-experimental/chips): replace innerText w/ textContent

---

scripts/docs-deploy/clone-docs-repo.ts
scripts/docs-deploy/utils.ts

Also needs to re-configure domain DNS and wire up the new service key
for the `material-angular-io` GCP project.

build: point automatic docs deployment to production firebase sites

---

CHANGELOG.md

docs: release notes for the v13.3.1 release

---

.github/workflows/build-dev-app.yml
.github/workflows/deploy-dev-app.yml
.github/workflows/dev-infra.yml

- Pinned actions by SHA https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
>Pin actions to a full length commit SHA
>Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload.
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
Also, dependabot supports upgrading based on SHA.
Signed-off-by: naveensrinivasan …

Pin actions to a full length commit SHA

---

src/material/core/typography/_typography.scss

Currently we've got two sets of typography selectors: some that target tags under `.mat-typography` (e.g. `.mat-typography h1`) and others that target a specific class (e.g. `.mat-title`). The intention with the class selectors was also to allow for the styles of a tag to be replaced (e.g. having an `h3` look like an `h2` if necessary), however that wasn't possible while inside `.mat-typography`, because the tag selectors were more specific. These changes update the class selectors to make it possible to override the tag selectors.
Fixes #14597.

fix(material/core): unable to override tag selectors inside .mat-typography

---

src/material/checkbox/checkbox.html

It seems that it was accidentally added in the first version of the component. unneeded attribute `xml:space` is removed.
Info about `xml:space`: http://www.xmlplease.com/xml/xmlspace/

refactor(material/checkbox): remove xml:space attr from svg checkmark

---

src/components-examples/material/datepicker/datepicker-views-selection/datepicker-views-selection-example.html
src/components-examples/material/datepicker/datepicker-views-selection/datepicker-views-selection-example.ts

Fix issue #24230 in the Datepicker Views Selection code demo. When selecting a month, set the year
on the form value to the active year on the datepicker.
Previously, this demo would only set the year when clicking on a year in the datepicker, but this
did not account for changing the year with the next/previous year buttons.
Fixes #24230

docs: fix bug in datepicker-views-selection demo

---

src/material/stepper/stepper.md

Fix a small typo error at Material Stepper documentation.
Fixes #24613

docs(material/stepper): fix typo into stepper documentation

---

src/material-experimental/mdc-chips/_chips-theme.scss
src/material-experimental/mdc-chips/chip.scss

Moves the typography styles of the chip to the root of the component so that it's easier to customize, similar to the non-MDC version.

fix(material-experimental/mdc-chips): make it easier to customize chip typography

---

src/cdk-experimental/dialog/dialog-config.ts
src/cdk-experimental/dialog/dialog.ts
src/material-experimental/mdc-dialog/dialog.spec.ts
src/material/dialog/dialog-config.ts
src/material/dialog/dialog.spec.ts
src/material/dialog/dialog.ts
tools/public_api_guard/material/dialog.md

Dialog components can be loaded asynchronously through the dynamic import, and they might be declared in the module that lives in the same file. The component might depend on the providers declared in this module. Currently, the `MatDialog` does not allow providing a custom injector. It only allows to pass the `viewContainerRef` and takes its injector if provided.
The real use case from our app:
```ts
export class SomeComponent {
constructor(private dialog: MatDialog, private injector: Injector) {}
openDialog(): void {
import('./dialog').then((m) => {
const ngModuleRef = createNgModuleRef(
m.DialogModule,
this.injector
);
this.dialog.open(m.DialogComponent, {
injector: ngModuleRef.injector,
});
});
}
}
```

feat(material/dialog): add support for explicit injector

---

src/cdk/accordion/accordion.ts

Fixes a bug in accordian/api documentation in CdkAccordian where `id` property is not loosley defined.
This is because `id` property is not explicitly defined as `string`.
Fixes #24639

docs(cdk/accordion): define string type for cdkaccordion property `id`

---

src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
src/material/autocomplete/autocomplete-trigger.ts
src/material/autocomplete/autocomplete.spec.ts

Currently, the autocomplete does not emit a `closed` event if the user clicks outside the input field after having entered a string that did not match any option. Moreover, when entering a valid string after an invalid one, the `opened` event is emitted again without a previous `closed` event. 
https://user-images.githubusercontent.com/3184240/159493351-e232864b-2f32-4c54-aa1f-d465209c4daa.mp4
Demo: https://stackblitz.com/edit/angular-dvitxy?file=src/app/autocomplete-auto-active-first-option-example.html
This PR ensures that a closed event is emitted every time the panel is closed.

fix(material/autocomplete): always emit closed event

---

src/cdk/testing/testbed/fake-events/type-in-element.ts
src/cdk/testing/tests/cross-environment.spec.ts

We were entering negative values into number inputs character-by-character which doesn't appear to work with Angular's reactive forms. These changes switch to entering the entire value all at once.
Fixes #24414.

fix(cdk/testing): entering negative number values not working with reactive forms

---

src/material-experimental/mdc-tabs/tab-group.spec.ts
src/material/tabs/tab-group.spec.ts
src/material/tabs/tab-group.ts

Fixes that when the selected tab is swapped out, we weren't marking the new tab as active and emitting the `selectedTabChange` event.
Fixes #24147.

fix(material/tabs): update tab state when active tab is swapped out

---

src/cdk/portal/dom-portal-outlet.ts
tools/public_api_guard/cdk/portal.md

Most of the constructor parameters of `DomPortalOutlet` are only used for component portals. These changes make them optional in order to simplify the constructor. If we hit a code path that does require them, we'll throw a runtime error.
Related to the discussion in #24334.

refactor(cdk/portal): simplify DomPortalOutlet constructor

---

src/material/button-toggle/button-toggle.scss

Fixes the ripples on buttons and button toggles not being clipped to the border radius in Safari.
Relates to #12244.

fix(material/button-toggle): ripples not clipping correctly in safari

---

src/material/chips/chips.scss

Fixes that the chip ripple wasn't being clipped to the border radius on Safari. This was fixed initially in #12244, but it seems to have regressed. Moving the `transform` to the ripple container seems to fix it.

fix(material/chips): ripple not clipped on safari

---

src/material-experimental/mdc-chips/chip-grid.spec.ts
src/material-experimental/mdc-chips/chip-grid.ts
src/material-experimental/mdc-chips/chip-input.spec.ts
src/material-experimental/mdc-chips/chip-input.ts
src/material-experimental/mdc-chips/chip-set.ts
src/material-experimental/mdc-chips/chip-text-control.ts

Updates mat-chip-grid to associate any ids set for aria-describedby to the matChipInput instance within the grid, if one exists.  See #24542 for information on why this is necessary.
Currently this PR creates a `setAriaDescribedBy` method on `matChipInput` and calls it from `mat-chip-grid` whenever `mat-chip-grid`'s `setAriaDescribedBy` method is called.  The internal logic mirrors that of `mat-chip-grid`.  This may not be the best way to go about this change; let me know if there's a better way to do it!
Fixes #24542

fix(material-experimental/mdc-chips): Mirror aria-describedby to matChipInput

---

src/cdk/scrolling/virtual-scroll-viewport.spec.ts

Fixes an error in one of the test files that is breaking the CI.

build: fix formatting error

---

src/material-experimental/mdc-slider/slider.ts

Currently the layout of the slider can look broken, because the thumb positions don't update when the size of the container changes.
These changes add some extra logic to trigger the resize in such cases.
Fixes #24590.

fix(material-experimental/mdc-slider): update layout when container resizes

---

tools/tslint-rules/noTypeOnlyImportExportRule.ts
tslint.json

Type-only imports and exports don't work with Closure so we can't use them.

build: add lint rule to disallow type-only imports/exports

---

src/material-experimental/mdc-button/fab.scss

Fixes that the extended FAB touch target was square which meant that it didn't cover the entire button.

fix(material-experimental/mdc-button): extended fab touch target not covering entire button

---

src/material/core/ripple/ripple-renderer.ts

We were adding `transitionend` and `transitioncancel` event listeners, but never removed it. I didn't want to touch the `RippleRef` class since that would be a change to the public API.

fix(material/core): resolve memory leak by removing event listeners from the ripple element

---

src/material-experimental/mdc-radio/radio.html
src/material-experimental/mdc-radio/radio.spec.ts
src/material/radio/radio.html
src/material/radio/radio.spec.ts
src/material/radio/radio.ts
tools/public_api_guard/material/radio.md

Currently all radio buttons inside a radio group have a `tabindex` of 0, unless they're disabled, and we leave it up to the browser to focus the proper button based on its selected state when the user is tabbing. This works for the most part, but it breaks down with something like our focus trap which determines which element to focus based on its `tabindex` since all buttons have the same `tabindex`. These changes fix the issue by setting a `tabindex` of 0 only on the selected radio button.
Fixes #17876.

fix(material/radio): set tabindex based on selected state

---

src/material-experimental/mdc-tabs/tab-group.spec.ts
src/material/tabs/tab-group.spec.ts
src/material/tabs/tab-group.ts
tools/public_api_guard/material/tabs.md

Currently the `tabindex` of each of the tab labels is determined by the selected index. This means that if the user tabbed into the header, pressed the right arrow and then pressed shift + tab, their focus would end up on the selected tab. These changes switch to basing the `tabindex` on the focused index which is tied both to the selected index and the user's keyboard navigation.

fix(material/tabs): focus wrapping back to selected label when using shift + tab

---

src/material-experimental/mdc-menu/menu.scss
src/material/menu/menu.scss

Adds an overlay on top of the content of a disabled menu item in order to capture clicks and prevent the menu from closing when clicking on it.
Fixes #19173.

fix(material/menu): clicks on disabled item closing the menu

---

scripts/circleci/notify-slack-job-failure.js

We want to skip CI failure Slack notifications for upstream branches
which are not actual publish branches.
Please enter the commit message for your changes. Lines starting

ci: skip ci failure slack notifications for renovate branches

---

scripts/docs-deploy/github-versioning.ts
scripts/docs-deploy/utils.ts

We recently seemed to hit the rate limit in the docs site monitoring
job. We can use a Github access token to avoid these rate limit failures.
We move the token extraction to a common location where the GCP key is
also extracted, and we use a more granular variable name to make sure it's
obvious where the key is used (when added to CircleCI)

build: use github access token for docs site monitoring

---

src/material-experimental/mdc-snack-bar/snack-bar-container.ts
src/material/snack-bar/snack-bar-container.ts

Adds an extra call to ensure that the snack bar is inside the NgZone. This is something that has come up several times in internal tests where some API call is stubbed out, pulling the snack bar outside the zone and causing tests to fail when we remove a change detection somewhere.
**Note:** I had a hard time reproducing this in our own tests, presumably because the fixture ends up pulling it back into the zone.

fix(material/snack-bar): ensure that the snack bar always runs inside the NgZone

---

src/cdk-experimental/menu/menu-bar.ts
src/cdk-experimental/menu/menu-base.ts
src/cdk-experimental/menu/menu-group.ts
src/cdk-experimental/menu/menu-interface.ts
src/cdk-experimental/menu/menu-item-trigger.ts
src/cdk-experimental/menu/menu-item.ts
src/cdk-experimental/menu/menu-stack.spec.ts
src/cdk-experimental/menu/menu-stack.ts
src/cdk-experimental/menu/menu.ts
src/dev-app/cdk-experimental-menu/cdk-menu-demo.css
src/dev-app/cdk-experimental-menu/cdk-menu-demo.html
src/dev-app/cdk-experimental-menu/cdk-menu-demo.ts
src/material-experimental/menubar/menubar.spec.ts
src/material-experimental/menubar/menubar.ts

Added TODOs for a couple questions I had as I was going. I can address them in this PR or a followup

fix(cdk-experimental/menu): move shared menu logic to base class

---

src/cdk/a11y/live-announcer/live-announcer.spec.ts
src/cdk/a11y/live-announcer/live-announcer.ts

We return a promise that indicates when we've added the live announcer content to the DOM, however the promise will never be resolved if a new message comes in during the 100ms that it takes for us to make the announcement.
These changes add some extra logic to ensure it is always resolved.
Note that I was also considering rejecting the old promise instead, but that may be a poor experience for users since they may not have control over messages that are coming in from other places in the app.
Fixes #24686.

fix(cdk/a11y): live announcer promise never resolved if new announcement comes in

---

src/cdk/overlay/_index.scss
src/cdk/overlay/overlay-ref.ts
src/cdk/overlay/overlay.spec.ts
src/cdk/overlay/overlay.ts
tools/public_api_guard/cdk/overlay.md

Fixes that we weren't disabling the CDK backdrop transition when the noop animations module is used. This has caused test flakes in the past.

fix(cdk/overlay): disable backdrop animation when noop animations are enabled

---

src/material/datepicker/calendar.spec.ts
src/material/datepicker/calendar.ts

Avoid re-rendering <mat-calendar/> when the [minDate] or [maxDate]
Input change to a different time on the same day.
In `ngOnChanges`, do not call `init` if the previous and current value for
minDate/maxDate are on the same day. This makes #24384 a non-breaking
code change.
Fixes #24435

fix(material/datepicker): avoid rerender when min/maxDate changes to different time on the same day

---

src/cdk/a11y/_index.scss

We had a `position: absolute` on the visually-hidden element, but it didn't have an actual position which can cause unnecessary scrolling in some cases.
Fixes #24597.

fix(cdk/a11y): visually hidden element affecting scrolling

---

src/material-experimental/mdc-core/option/option.scss
src/material-experimental/mdc-menu/menu.scss

Fixes a couple of cases where the MDC list styles will override the styles of other components if they're loaded after them.

Resolve style conflicts with MDC-based list

---

src/material-experimental/mdc-dialog/dialog-container.ts
src/material/dialog/dialog-container.ts
tools/public_api_guard/material/dialog.md

When I added the `delayFocusTrap` option in #24121, I assumed that it would be inherited into the MDC dialog. Since it looks like that's not actually the case, these changes implement it.

fix(material-experimental/mdc-dialog): implement delayFocusTrap option

---

src/components-examples/material/datepicker/date-range-picker-comparison/date-range-picker-comparison-example.html
src/components-examples/material/datepicker/date-range-picker-forms/date-range-picker-forms-example.html
src/components-examples/material/datepicker/date-range-picker-overview/date-range-picker-overview-example.html
src/components-examples/material/datepicker/date-range-picker-selection-strategy/date-range-picker-selection-strategy-example.html
src/components-examples/material/datepicker/datepicker-actions/datepicker-actions-example.html
src/components-examples/material/datepicker/datepicker-api/datepicker-api-example.html
src/components-examples/material/datepicker/datepicker-color/datepicker-color-example.html
src/components-examples/material/datepicker/datepicker-custom-header/datepicker-custom-header-example.html
src/components-examples/material/datepicker/datepicker-custom-icon/datepicker-custom-icon-example.html
src/components-examples/material/datepicker/datepicker-date-class/datepicker-date-class-example.html
src/components-examples/material/datepicker/datepicker-disabled/datepicker-disabled-example.html
src/components-examples/material/datepicker/datepicker-events/datepicker-events-example.html
src/components-examples/material/datepicker/datepicker-filter/datepicker-filter-example.html
src/components-examples/material/datepicker/datepicker-formats/datepicker-formats-example.html
src/components-examples/material/datepicker/datepicker-locale/datepicker-locale-example.html
src/components-examples/material/datepicker/datepicker-locale/datepicker-locale-example.ts
src/components-examples/material/datepicker/datepicker-min-max/datepicker-min-max-example.html
src/components-examples/material/datepicker/datepicker-moment/datepicker-moment-example.html
src/components-examples/material/datepicker/datepicker-overview/datepicker-overview-example.html
src/components-examples/material/datepicker/datepicker-start-view/datepicker-start-view-example.html
src/components-examples/material/datepicker/datepicker-touch/datepicker-touch-example.html
src/components-examples/material/datepicker/datepicker-value/datepicker-value-example.html
src/components-examples/material/datepicker/datepicker-views-selection/datepicker-views-selection-example.html
src/components-examples/material/datepicker/index.ts
src/material/datepicker/datepicker.md

In the accessibility section of the datepicker documentation, require communicating the date format
string (e.g. 'MM/DD/YYYY'). Update datepicker examples to show the date format string via
`<mat-hint>` and use 'en-US' as the locale.
This commit only changes examples and does not affect source code.
Addresses #11127

docs(material/datepicker): require communicating date format for a11y

---

src/material-experimental/mdc-list/list-option.ts
src/material/list/selection-list.ts

Fixes a bug in Angular Material `selection-list` component where the order of arguments passed to a custom compareWith function was mixed up during initialization of a MatListOption.
Expected order based on documentation is:
1. value of the respective option
2. value of the selection

fix(material/list): wrong order of arguments when calling custom compareWith function

---

src/material/snack-bar/snack-bar.ts
tools/public_api_guard/material/snack-bar.md

Add a generic for MatSnackBarConfig inside openFromComponent method

fix(material/snack-bar): update generic types for openFromComponent

---

src/material-experimental/mdc-chips/chip-action.ts
src/material-experimental/mdc-chips/chip-remove.spec.ts
src/material/chips/chip-remove.spec.ts
src/material/chips/chip.ts

Adds a `preventDefault` call to the `click` handlers of the chip remove icon in order to avoid things like form submissions and link navigations.
Fixes #24436.

fix(material/chips): prevent default behavior on remove button

---

src/material-experimental/mdc-select/select.scss
src/material/select/select.scss

We use an empty space to prevent the select from collapsing when it doesn't have a value, but the approach we were using was being read out as a blank space by VoiceOver on Chrome. These changes switch to using `visibility: hidden` so that it isn't read out.
Fixes #24731.

fix(material/select): empty space read out by VoiceOver on Chrome

---

src/material-experimental/mdc-slide-toggle/testing/slide-toggle-harness.ts
src/material/slide-toggle/testing/shared.spec.ts
src/material/slide-toggle/testing/slide-toggle-harness-filters.ts
src/material/slide-toggle/testing/slide-toggle-harness.ts
tools/public_api_guard/material/slide-toggle-testing.md

- Add `disabled` predicate to MatSlideToggleHarness

feat(material/slide-toggle): Add `disabled` predicate to MatSlideToggleHarness

---

src/material/schematics/ng-generate/mdc-migration/rules/components/card/card-template.ts
src/material/schematics/ng-generate/mdc-migration/rules/components/chips/chips-template.spec.ts
src/material/schematics/ng-generate/mdc-migration/rules/components/chips/chips-template.ts
src/material/schematics/ng-generate/mdc-migration/rules/index.ts
src/material/schematics/ng-generate/mdc-migration/rules/template-migration.ts
src/material/schematics/ng-generate/mdc-migration/rules/template-migrator.ts

* impl ChipsTemplateMigrator and added it to list of migrators
* remove unnecessary class vars from TemplateMigrator
* added onComplete callback to TemplateMigrator to make
handling state in TemplateMigrators simpler
* unit tested

feat(material/schematics): add chips template migrator

---

src/cdk/portal/dom-portal-outlet.ts

This commit adds a check that ensures that the `ApplicationRef.detachView` is only called when there are some registered views in the `ApplicationRef` instance (thus the instance is not destroyed).
Calling `ApplicationRef` APIs on destroyed instance will result in an error after https://github.com/angular/angular/pull/45624. This commit makes the code forward-compatible with the upcoming changes. The error was discovered in g3 while running a TGP for https://github.com/angular/angular/pull/45624.

fix(cdk/portal): prevent calling `ApplicationRef.detachView` on destroyed instance

---

renovate.json

We found renovate lock file maintenance to be non-ideal for our
branching in Angular. Going forward we will disable this and start
managing the lock file manually like in the past.

build: disable renovate lock file maintenance

---

src/material/chips/chip-list.ts
src/material/chips/chip.ts

Fixes that we were referring to `MatChip` as a component even though it's a directive.
Fixes #24779.

docs(material/chips): use correct terminology

---

src/material/paginator/testing/paginator-harness.ts
src/material/paginator/testing/shared.spec.ts
tools/public_api_guard/material/paginator-testing.md

I have some tests that assert this behavior and ran into this when migrating over to component harnesses.

feat(material/paginator): Add `isNextPageEnabled` and `isPreviousPageEnabled` to `MatPaginatorHarness`

---

src/cdk/table/table.ts
tools/public_api_guard/cdk/table.md

Exposes the `CdkTableDataSourceInput` type since it can be useful for people implementing their own tables.
Fixes #24518.

refactor(cdk/table): expose data source type

---

.github/CODEOWNERS
goldens/ts-circular-deps.json
src/cdk-experimental/dialog/BUILD.bazel
src/cdk-experimental/dialog/dialog-config.ts
src/cdk-experimental/dialog/dialog-container.scss
src/cdk-experimental/dialog/dialog-container.ts
src/cdk-experimental/dialog/dialog-injectors.ts
src/cdk-experimental/dialog/dialog-module.ts
src/cdk-experimental/dialog/dialog-ref.ts
src/cdk-experimental/dialog/dialog.spec.ts
src/cdk-experimental/dialog/dialog.ts
src/dev-app/BUILD.bazel
src/dev-app/cdk-dialog/BUILD.bazel
src/dev-app/cdk-dialog/dialog-demo-module.ts
src/dev-app/cdk-dialog/dialog-demo.html
src/dev-app/cdk-dialog/dialog-demo.scss
src/dev-app/cdk-dialog/dialog-demo.ts
src/dev-app/dev-app/dev-app-layout.ts
src/dev-app/routes.ts

Rewrites most of the CDK experimental dialog to prepare it for public release. The changes were largely informed by implementing `material/dialog`, `material-experimental/mdc-dialog` and `material/bottom-sheet` using the new API, however the API can be used directly without having to be wrapped. Overview of the changes:
* The classes for the dialog container, dialog config and dialog data aren't provided using DI anymore. The previous approach could've been a problem for apps that use multiple different versions of a CDK-based dialog.
* Several fixes from the Material dialog that were never backported to the CDK version have been incorporated.
* All animations and styles have been removed from the CDK dialog since they were going to be difficult to override by users. Custom animations can …

refactor(cdk-experimental/dialog): rewrite experimental dialog

---

src/material-experimental/mdc-select/select.spec.ts
src/material-experimental/mdc-select/select.ts
src/material/select/select.spec.ts
src/material/select/select.ts
tools/public_api_guard/material/select.md

Based on #24292.
Further fixes #16209.

feat(material/select): allow user-defined aria-describedby

---

CHANGELOG.md

docs: release notes for the v13.3.4 release

---

src/material-experimental/mdc-snack-bar/snack-bar-container.ts

Currently the MDC snack bar container is querying the DOM on each change detection in order to apply the correct class to the content. We don't need to do this so frequently since everything is set after the portal content has been attached.

fix(material-experimental/mdc-snack-bar): avoid querying the DOM on each change detection

---

src/cdk/drag-drop/directives/drag.spec.ts
src/cdk/drag-drop/directives/drag.ts
tools/public_api_guard/cdk/drag-drop.md

Adds method `setFreeDragPosition` in Cdk `DragDrop` directive to set position in pixel on a drop container.
Also corrects some inaccurate types on a couple of freeDragPosition methods of the `DragDrop` directive.
Fixes #18530

feat(cdk/drag-drop): adding method to set drag position

---

.circleci/config.yml
.circleci/rebase-pr.js

Preparation for the components repo as outlined our planning
document.

[12.x]: build: preparation for primary branch rename in the Angular repos

---

WORKSPACE
package.json
yarn.lock

Updates to the latest version of the Sass Bazel rules. We landed
a fix upstream, allowing us to provide a vendored Yarn script, instead
of needing a separate download of Yarn (with a warning polluting the
Bazel output)

build: update sass bazel rules and fix yarn repository Bazel warning

---

src/cdk/clipboard/clipboard.md

Standalone `Clipboard` samples have been missing imports, which can confuse some devs.
I added them.

docs(cdk/clipboard): Add imports to samples

---

src/cdk/overlay/overlay-ref.ts

When an overlay is detached, we remove it from the change detection tree and the DOM, but we don't destroy it completely so that it can be re-attached. Re-attachment is the same process, but in reverse: we re-add the element to the DOM and the change detection tree. The problem is that we were attaching the element to the change detection tree before re-inserting it into the DOM which caused the Angular animations package not to animate the element since it's not in the DOM yet.
These changes resolve the issue by attaching the element to the DOM first.
Fixes #24749.
**Note:** writing a unit test for this is tricky, because the content is never actually destroyed so we can't use lifecycle hooks for assertions.

fix(cdk/overlay): animations interrupted on repeat insertions

---

src/material-experimental/mdc-autocomplete/autocomplete.spec.ts
src/material/autocomplete/autocomplete-trigger.ts
src/material/autocomplete/autocomplete.spec.ts

Fixes a bug in Angular Material `autocomplete` when outside click doesn't trigger `changeDetection`.
Fixes #24811

fix(material/autocomplete): outside click in Angular zone.

---

src/material/sort/sort-header.ts
src/material/sort/sort.ts
tools/public_api_guard/material/sort.md

Not sure if that is really needed.
Just it feels like it is more consistent with existing `SortDirection`. 🙂

refactor(material/sort): explicit sort direction

---

.github/workflows/dev-infra.yml
.github/workflows/feature-requests.yml
.github/workflows/lock-closed.yml

Updates the Github actions now that https://github.com/angular/dev-infra/commit/c9d0bf5e5facaf816f0af90547728fb8752ef97e has landed.

build: fix github actions breaking due to symlink in dev-infra repository

---

src/cdk/schematics/testing/test-case-setup.ts
src/material/schematics/ng-update/migrations/hammer-gestures-v9/gesture-config.template
src/material/schematics/ng-update/migrations/hammer-gestures-v9/hammer-gestures-migration.ts

All links on git.io will stop redirecting after April 29, 2022: https://github.blog/changelog/2022-04-25-git-io-deprecation/
---
Alternative solution: should angular provide its own redirection under the domain `angular.io`?

chore: replace all git.io link

---

CHANGELOG.md

docs: release notes for the v13.3.5 release

---

src/cdk/dialog/dialog-config.ts
src/cdk/dialog/dialog-container.ts
src/cdk/dialog/dialog-ref.ts
src/cdk/dialog/dialog.spec.ts
src/cdk/dialog/dialog.ts
src/dev-app/cdk-dialog/dialog-demo.ts
tools/public_api_guard/cdk/dialog.md

Adjusts the public API of the CDK dialog based on a recent feedback session by:
* Expanding `DialogRef.restoreFocus` to allow CSS selectors and DOM nodes.
* Changing `Dialog.openDialogs`, `DialogRef.componentInstance` and `DialogRef.containerInstance` to be readonly.
* Allowing for numbers to be passed in to `DialogRef.updateSize`.
* Updating the doc string of `DialogRef.updateSize`.

refactor(cdk/dialog): expand and clean up API

---

tools/release-checks/check-migration-collections.ts

We recently started auto-generating the material-experimental
package.json file to avoid duplicating the MDC version/deps
across multiple places.
The staging checks assume a `package.json` file to be visible in the
source files. For our checks it is sufficient to use the handwritten
base package.json file.
Note: We do have actual generated `package.json` tests, but these tests
are quick sanity checks that run before actually releasing (giving a quick
heads-up before doing too much unnecessary work)

build: fix staging release checks after auto-generating `material-experimental`  package json

---

.circleci/config.yml

See: https://github.com/eddiewebb/circleci-queue/issues/79.

build: temporarily disable queue orb causing snapshot deployment failures

---

src/material/autocomplete/autocomplete.ts

Hi! I removed 'using the keyabord' since it's not correct.
btw, I'm not sure the current description is accurate enough. Perhaps we should include some information about the active index logic.
Fixes #24799

docs(material/autocomplete): change documentation for the optionActivated event

---

guides/typography.md

The `typography-hierarchy` mixin was missing from the documentation. This adds a couple of sentences mentioning that it exists.

docs(material/theming): document `typography-hierarchy`

---

.circleci/rebase-pr.js
.ng-dev/github.ts
renovate.json
scripts/deploy/publish-build-artifacts.sh
scripts/deploy/publish-docs-content.sh

Changes of the `DIRECT` phase for the "renaming master to
main" migration/planning doc.

build: changes for renaming primary branch to `main`

---

.circleci/rebase-pr.js
.ng-dev/github.ts
scripts/deploy/publish-build-artifacts.sh
scripts/deploy/publish-docs-content.sh

Changes of the `DIRECT` phase for the "renaming master to
main" migration/planning doc.
Note the version of ng-dev used in this LTS branch does not properly
support custom primary branches, but this should be non-relevant here
because this commit will only land in a version branch (11.2.x)

build: changes for renaming primary branch to `main` [11.2.x]

---

.circleci/rebase-pr.js
.ng-dev/github.ts
scripts/deploy/publish-build-artifacts.sh
scripts/deploy/publish-docs-content.sh

Changes of the `DIRECT` phase for the "renaming master to
main" migration/planning doc.

build: changes for renaming primary branch to `main` [12.2.x]

---

src/material/autocomplete/testing/autocomplete-harness.ts
src/material/autocomplete/testing/shared.spec.ts
tools/public_api_guard/material/autocomplete-testing.md

Adds a `clear` method to the autocomplete harness, because currently it's only possible to enter text into it.
Fixes #24751.

feat(material/autocomplete): add clear method to test harness

---

src/components-examples/material/button/button-harness/button-harness-example.spec.ts

We were declaring the harness being used as a variable unecessarily. These changes align the example closer with the other harness examples.
Fixes #24732.

docs(material/button): fix button harness example test

---

src/material/menu/menu-content.ts
src/material/menu/menu-item.ts
src/material/menu/menu-trigger.ts
src/material/menu/menu.ts
tools/public_api_guard/material/menu.md

In #24116 I explored using constructor overload for deprecations, but I forgot to add an overload for the non-deprecated signatures.
Fixes #24740.

fix(material/menu): add constructor overloads for non-deprecated signatures

---

src/cdk/dialog/dialog-config.ts
src/cdk/dialog/dialog-container.ts
src/cdk/dialog/dialog.ts
src/material-experimental/mdc-dialog/BUILD.bazel
src/material-experimental/mdc-dialog/dialog-container.ts
src/material-experimental/mdc-dialog/dialog-ref.ts
src/material-experimental/mdc-dialog/dialog.spec.ts
src/material-experimental/mdc-dialog/dialog.ts
src/material-experimental/mdc-dialog/module.ts
src/material-experimental/mdc-dialog/public-api.ts
src/material/dialog/BUILD.bazel
src/material/dialog/dialog-container.ts
src/material/dialog/dialog-content-directives.ts
src/material/dialog/dialog-module.ts
src/material/dialog/dialog-ref.ts
src/material/dialog/dialog.ts
tools/public_api_guard/cdk/dialog.md
tools/public_api_guard/material/dialog.md

Switches the Material dialog to be based on the CDK dialog.

refactor(material/dialog): switch to CDK dialog internally

---

package.json
src/components-examples/material/chips/chips-harness/chips-harness-example.ts
src/google-maps/map-marker-clusterer/map-marker-clusterer.spec.ts
src/google-maps/map-marker-clusterer/map-marker-clusterer.ts
src/google-maps/map-marker-clusterer/marker-clusterer-types.ts
src/google-maps/public-api.ts
src/google-maps/testing/fake-google-map-utils.ts
tools/public_api_guard/google-maps/google-maps.md
yarn.lock

Updating `@angular/bazel` to `14.0.0-next.15` reveals some issues with type bundling. These changes aim to resolve the issues by moving some code around.

build: resolve type bundling issues

---

src/material-experimental/mdc-table/table.scss

I think this used to be present in MDC but is no longer there. This causes the background to be inherited down so that elements share the same background set on the table. This fixes the sticky headers

fix(material-experimental/mdc-table): add inherit background to rows

---

src/material-experimental/mdc-snack-bar/snack-bar-container.ts
src/material-experimental/mdc-snack-bar/snack-bar.spec.ts
src/material/snack-bar/snack-bar-ref.ts
src/material/snack-bar/snack-bar.spec.ts

Fixes an issue where opening a snack bar while the previous one was being animated caused the former to remain in the DOM. The problem was that MDC always waits for an animation, even if it is interrupted.
Caretaker note: Fixes internal issue b/225379279

fix(material-experimental/mdc-snack-bar): avoid multiple snack bars on the page if opened in quick succession

---

CHANGELOG.md

Cherry-picks the changelog from the "13.3.x" branch to the next branch (main).

docs: release notes for the v13.3.6 release

---

src/material/expansion/expansion-panel.scss

Fixes that the expansion panel was applying the margin only to `mat-button` set on a `button` node.

fix(material/expansion): inconsistent spacing for anchor buttons

---

src/material/datepicker/datepicker-input-base.ts
src/material/datepicker/testing/datepicker-input-harness-shared.spec.ts

fix(material/datepicker): add ability to have numeric zero value in input
Shows valid formatted value for 'falsy' values (exp 0)
Custom DateAdapter (exp TimestampDateAdapter) can have valid numeric 0 value (for timestamp it is 1/1/1970), but datepicker input doesn't show formatted value

fix(material/datepicker): add ability to have numeric zero value in input

---

src/material/menu/menu.ts

When opening the menu using the iOS VoiceOver screen reader, focus the first item in the menu.
Previously, the first menu item would focus on other screen readers like desktop VoiceOver but
not with iOS VoiceOver.
Waiting until `onStable` seems to fix this.
Fixes #24735

fix(material/menu): focus the first item when opening menu on iOS VoiceOver

---

.github/actions/yarn-install/action.yml

With Angular v14, and the CLDR update one of the files got renamed
just in casing. Yarn 1.x. does not seem to prune the old files
causing two files to have the same name (ignoring casing). This throws
off Bazel and we need to prune the cache like we did for CircleCI.

build: invalidate github action cache to prune old files

---

src/google-maps/map-marker-clusterer/map-marker-clusterer.ts

In #24865 the access of the global `MarkerClusterer` class changed to go through the `window`. This causes a runtime error for apps minified through Closure, because the name is no longer minified and it doesn't align with the minified class name on the `window`. These changes move around our code so that we reference the clusterer without going through the `window`.

fix(google-maps): error when minified through closure

---

src/google-maps/public-api.ts
tools/public_api_guard/google-maps/google-maps.md

Exposes the `MapEventManager` that we use to bind events in the Google Maps package so that users implementing their own components can consume it as well.

refactor(google-maps): expose event manager

---

src/cdk/dialog/BUILD.bazel
src/cdk/dialog/dialog-container.scss
src/cdk/dialog/dialog-container.ts
src/dev-app/cdk-dialog/dialog-demo.scss
src/dev-app/cdk-dialog/dialog-demo.ts

Currently the CDK dialog container doesn't come with any styles which means that it's `display: inline`, making it difficult to change its size. These changes add a handful of styles to make it match the specified size in the config.

fix(cdk/dialog): add container structural styles

---

src/material/core/style/_private.scss
src/material/progress-spinner/progress-spinner.scss

The way the `private-animation-noop` mixin was written meant that if it was included in a list of selectors, it would only be applied to the first selector in the list. This caused some animations in the MDC button not to be disabled.
These changes simplify the mixin, because the old approach was only relevant for on case in the progress spinner that we can write out manually instead.

fix(material/core): noop animations not applying to selector lists

---

CHANGELOG.md

Cherry-picks the changelog from the "13.3.x" branch to the next branch (main).

docs: release notes for the v13.3.7 release

---

src/cdk/dialog/dialog.md
src/components-examples/cdk/dialog/BUILD.bazel
src/components-examples/cdk/dialog/cdk-dialog-data/cdk-dialog-data-example-dialog.css
src/components-examples/cdk/dialog/cdk-dialog-data/cdk-dialog-data-example-dialog.html
src/components-examples/cdk/dialog/cdk-dialog-data/cdk-dialog-data-example.html
src/components-examples/cdk/dialog/cdk-dialog-data/cdk-dialog-data-example.ts
src/components-examples/cdk/dialog/cdk-dialog-overview/cdk-dialog-overview-example-dialog.css
src/components-examples/cdk/dialog/cdk-dialog-overview/cdk-dialog-overview-example-dialog.html
src/components-examples/cdk/dialog/cdk-dialog-overview/cdk-dialog-overview-example.html
src/components-examples/cdk/dialog/cdk-dialog-overview/cdk-dialog-overview-example.ts
src/components-examples/cdk/dialog/cdk-dialog-styling/cdk-dialog-styling-example-dialog.css
src/components-examples/cdk/dialog/cdk-dialog-styling/cdk-dialog-styling-example-dialog.html
src/components-examples/cdk/dialog/cdk-dialog-styling/cdk-dialog-styling-example.html
src/components-examples/cdk/dialog/cdk-dialog-styling/cdk-dialog-styling-example.ts
src/components-examples/cdk/dialog/index.ts
src/components-examples/config.bzl
src/material/dialog/dialog.md

Adds docs and live examples for the CDK dialog. Also removes the section about `entryComponents` from the Material dialog.

CDK dialog docs

---

src/material-experimental/mdc-radio/radio.html
src/material-experimental/mdc-radio/radio.ts

Removes the dependency on the MDC radio adapter from the radio button component.

refactor(material-experimental/mdc-radio): remove adapter usage

---

src/material-experimental/mdc-checkbox/checkbox.html
src/material-experimental/mdc-checkbox/checkbox.spec.ts
src/material-experimental/mdc-checkbox/checkbox.ts
src/material/checkbox/checkbox.ts
tools/public_api_guard/material/checkbox.md

Moves all of the checkbox logic into a base class which is used to replace the MDC checkbox adapter.

refactor(material-experimental/mdc-checkbox): remove usage of MDC adapter

---

src/material/tabs/paginated-tab-header.ts

This should fix #6130 and also #4648?. It uses `ResizeObserver` to ensure we get notifications about the dimensions of the tabs when they change. The layout change will fire synchronously. 
It may also fix #3048.

fix(material/tabs): ensure the ink bar realigns when the tab header changes dimensions

---

src/material-experimental/mdc-slide-toggle/slide-toggle.html
src/material-experimental/mdc-slide-toggle/slide-toggle.spec.ts
src/material-experimental/mdc-slide-toggle/slide-toggle.ts
src/material/slide-toggle/slide-toggle.html
src/material/slide-toggle/slide-toggle.ts
tools/public_api_guard/material/slide-toggle.md

Bases the MDC slide toggle on top of the non-MDC one, instead of the MDC adapter.

refactor(material-experimental/mdc-slide-toggle): remove usage of MDC adapter

---

src/material-experimental/mdc-tabs/BUILD.bazel
src/material-experimental/mdc-tabs/ink-bar.ts
src/material-experimental/mdc-tabs/tab-label-wrapper.ts
src/material-experimental/mdc-tabs/tab-nav-bar/tab-nav-bar.ts

Reworks the MDC tab ink bar so that it doesn't depend upon the MDC adapter and foundation.

refactor(material-experimental/mdc-tabs): remove usage of MDC adapter

---

src/material-experimental/mdc-checkbox/checkbox.html
src/material-experimental/mdc-checkbox/checkbox.spec.ts
src/material-experimental/mdc-checkbox/checkbox.ts
src/material/checkbox/checkbox.spec.ts
src/material/checkbox/checkbox.ts
tools/public_api_guard/material/checkbox.md

In the mdc checkbox component, removes the click handler on <label/>
and handles stoping propgation of clicks on the label in the label's
parent. This removes the extra a11y tree node on the label and fixes
TalkBack having an extra navigation stop (https://github.com/angular/components/issues/14385).
A11y tree before this commit. It has an un-necessary node, which
corresponds to the `<label>` element.
```
- Generic
- Checkbox, "Field A"
- Textlabel, "Field A"
```
A11y tree with this commit applied
```
- Generic
- Checkbox, "Field A"
```
fixes https://github.com/angular/components/issues/14385

fix(material-experimental/mdc-checkbox): remove extra a11y tree node …   …for the <label/>

---

src/material-experimental/mdc-progress-spinner/BUILD.bazel
src/material-experimental/mdc-progress-spinner/progress-spinner.ts

Removes our usage of the MDC adapter from the MDC-based progress spinner component.

refactor(material-experimental/mdc-progress-spinner): remove MDC adapter usage

---

src/material/bottom-sheet/BUILD.bazel
src/material/bottom-sheet/bottom-sheet-container.ts
src/material/bottom-sheet/bottom-sheet-module.ts
src/material/bottom-sheet/bottom-sheet-ref.ts
src/material/bottom-sheet/bottom-sheet.ts
tools/public_api_guard/material/bottom-sheet.md

Switches the internals of the bottom sheet to use the CDK dialog.

refactor(material/bottom-sheet): use CDK dialog internally

---

.github/workflows/dev-infra.yml

This action will enforce that all pull requests receive an approval from
at least one googler on the final commit for the pull request. Historically,
we have allowed all post approval changes regardless of authorship. Moving
forward, with this change, we will only allow known googlers to perform
post approval changes.
When a post approval change occurs by a non-googler, the action will
automatically rerequest a review from the latest googler who provided
an approval on the change.

[14.0.x] build: set up post approval changes commit action (#24957)

---

CHANGELOG.md

Cherry-picks the changelog from the "13.3.x" branch to the next branch (main).

docs: release notes for the v13.3.8 release

---

src/cdk/schematics/ng-generate/drag-drop/schema.json
src/material/schematics/ng-generate/address-form/schema.json
src/material/schematics/ng-generate/dashboard/schema.json
src/material/schematics/ng-generate/navigation/schema.json
src/material/schematics/ng-generate/table/schema.json
src/material/schematics/ng-generate/tree/schema.json

The Angular CLI, handles options with both name and format `path` as a special case. This behaviour has been deprecated and instead the `workingDirectory` smart provider should be used instead. Currently, when not using the provider a deprecation warning will be issue.
See: https://github.com/angular/angular-cli/pull/23212

Schematics: use `workingDirectory` smart provider in path option

---

src/cdk/menu/menu.md

Fixes that the docs were referring to an example that was renamed.

docs(cdk/menu): fix wrong example name

---

src/cdk/a11y/aria-describer/aria-describer.ts

Adds the unique application ID to the ARIA describer ID so that it's unique even if Angular is loaded multiple times.
Fixes #24917.

fix(cdk/a11y): ensure that aria describer ID is unique

---

tools/postinstall/apply-patches.js

Removing the locale files will help us reduce Bazel action inputs and
therefore speed up compilations/type bundling because the bazel sandbox
would not need as much files to be sandboxed/symlinked.
More info can be found here: https://github.com/angular/angular/pull/46187
cc. @mmalerba (here as well -- along with the actual PR fix in Angular Bazel)

build: speed up TS compilations and type bundling by removing locale files

---

CHANGELOG.md

Cherry-picks the changelog from the "14.0.x" branch to the next branch (main).

docs: release notes for the v14.0.0-rc.2 release

---

src/material/icon/icon.md

docs(material/icon): update the FontAwesome link.
Update the FontAwesome link example.
The FontAwesome link was broken.
Fixes #24954

docs(material/icon): update the FontAwesome example link

---

src/material/datepicker/datepicker-base.ts
src/material/datepicker/datepicker.spec.ts

In an earlier change we introduced a timeout between when the datepicker is opened and when focus is moved into the current view. This means that the browser has some time to fire another keyboard event before we start preventing their default actions from inside the calendar, potentially allowing the page to be scrolled.
These changes fix the issue by always preventing the default action of navigation keys at the overlay level.
Fixes #24969.

fix(material/datepicker): page scrolling for fast keyboard repeat

---

src/material-experimental/mdc-progress-bar/BUILD.bazel
src/material-experimental/mdc-progress-bar/progress-bar.html
src/material-experimental/mdc-progress-bar/progress-bar.spec.ts
src/material-experimental/mdc-progress-bar/progress-bar.ts

Reworks the MDC progress bar so that it doesn't use MDC's adapter anymore.

refactor(material-experimental/mdc-progress-bar): remove usage of MDC adapter

---

CHANGELOG.md

Cherry-picks the changelog from the "13.3.x" branch to the next branch (main).

docs: release notes for the v13.3.9 release

---

.ng-dev/release.ts
package.json
src/material-experimental/mdc-form-field/testing/public-api.ts
src/material/form-field/testing/public-api.ts
tools/public_api_guard/BUILD.bazel
tools/public_api_guard/generate-guard-tests.bzl
tools/public_api_guard/material/form-field-testing.md
tools/release-checks/check-framework-peer-dependency.ts
tools/release-checks/check-migration-collections.ts
tools/release-checks/npm-package-output/index.ts
yarn.lock

* build: update angular shared dev-infra package
Updates the shared dev-infra package.
* build: use new release prechecks for validating release before publish
Uses the new release precheck feature for validating release output
and other inputs.
Co-authored-by: Renovate Bot <bot@renovateapp.com>
Co-authored-by: Paul Gschwendtner <paulgschwendtner@gmail.com>
(cherry picked from commit 2740e988d05e0e2992d52adc67f7a166e85395e7)
Also backports commits from https://github.com/angular/components/pull/24683

[13.3.x] build: update angular shared dev-infra code to 932b9d5 (#25000)

---

src/material/datepicker/datepicker-intl.ts
tools/public_api_guard/material/datepicker.md

Add i18n strings for "Start Date" and "End Date". Add `formatYearRangeLabel` to format a year of
dates in a screen reader friendly way (e.g. "2019 to 2020"). The existing method, `formatYearRange`,
uses a dash character which does not read well on screen readers.
These three new strings are not used in this commit. They will be used in future commits as aria
labels and descriptions to fix accessibility bugs.

fix(material/datepicker): add i18n strings

---

src/cdk/scrolling/public-api.ts
src/cdk/scrolling/scrollable.ts
src/cdk/scrolling/scrolling-module.ts
src/cdk/scrolling/virtual-scroll-viewport.scss
src/cdk/scrolling/virtual-scroll-viewport.spec.ts
src/cdk/scrolling/virtual-scroll-viewport.ts
src/cdk/scrolling/virtual-scrollable-element.ts
src/cdk/scrolling/virtual-scrollable-window.ts
src/cdk/scrolling/virtual-scrollable.ts
src/dev-app/virtual-scroll/virtual-scroll-demo.html
tools/public_api_guard/cdk/scrolling.md

Decouples the scroller from the virtual-scroll-viewport which allows library consumers
to use any parent element as a scroller. This is especially helpful when building SPAs
with a single global scrollbar.
Closes #13862
@mmalerba this is first draft, test and docs updates are missing. But I would like to have your feedback regarding certain points.
1. WDYT about the API changes in general?
2. There are a couple of lines, only to maintain backward compatibility. I am not sure if it's worth it, as I would expect that the required changes on applications could be done using schematics.  Changing `<cdk-virtual-scroll-viewport ...` to `<cdk-virtual-scroll-viewport cdk-virtual-scrollable-element ...` should be sufficient.
3. I had some problems linking it to the global-scrollbar. As commented …

feat(cdk/scrolling): make scroller element configurable for virtual scrolling

---

src/material-experimental/mdc-list/list-base.ts

Moves the `MatListBase` class up so that it isn't being referenced before it is used which seems to cause issues with Jest.
Fixes #25008.

fix(material-experimental/mdc-list): don't access class before initialization

---

.circleci/config.yml
package.json
scripts/circleci/notify-slack-job-failure.mts

TS node is no longer automatically registering in the `ng-dev` tool, so
the config cannot be loaded anymore. Callers of `getConfig()` are
required to manually wire up TS-Node, mostly now because ESM ts-node
**cannot** be registered at runtime anymore. So, the fix here is to
either run the slack notify script with `node --loader ts-node/esm` or
just run it using `ts-node` directly, while writing it in TS.
The latter one seems the most reasonable.

ci: fix slack notification script failing due to missing `ts-node`

---

package.json
scripts/circleci/notify-slack-job-failure.mts

build: replace dynamic require with import statement for ESM

---

src/cdk/drag-drop/directives/drag.spec.ts
src/cdk/drag-drop/directives/drag.ts
src/cdk/drag-drop/drag-ref.ts
tools/public_api_guard/cdk/drag-drop.md

Fixes that the `constrainPosition` input wasn't constraining the position as described in the docs. This may have worked at some point, but it's definitely broken now. Our tests didn't catch it, because they were looking at the `transform` which was wrong, instead of the position the element ended up at.
I've also added the current element dimensions to the callback since they could be useful.
Fixes #25046.

fix(cdk/drag-drop): constrainPosition not working as expected

---

src/material/select/select.md

Update documentation to include ReactiveForms use case
Fixes #24762

docs(material/select): Disabling the select or individual options

---

src/cdk/testing/testbed/fake-events/dispatch-events.ts
src/cdk/testing/testbed/fake-events/event-objects.ts
src/cdk/testing/testbed/unit-test-element.ts
src/cdk/testing/tests/test-main-component.ts
src/material-experimental/mdc-menu/menu.spec.ts
src/material-experimental/mdc-tabs/tab-header.spec.ts
src/material/menu/menu.spec.ts
src/material/slider/slider.spec.ts
src/material/tabs/tab-header.spec.ts

See individual commits for more info. Top-level changes:
* Simulates `offsetX` and `offsetY` in fake mouse events.
* Uses `offsetX` and `offsetY` in one of our flaky tests.

Simulate offsetX/offsetY and attempt to reduce test flakes

---

src/material-experimental/mdc-chips/chip.scss

Fixes that the checkmark on the MDC chips was blending into the background for high contrast mode users.
Fixes #25071.

fix(material-experimental/mdc-chips): checkmark blending into background in high contrast mode

---

src/cdk/dialog/dialog.md

fix(docs/dialog.md): fix typo
Fixes a typo in dialog.md file. Replaces 'contaier' with 'container'

fix(docs/typography-guide): Update dialog.md typo

---

src/material-experimental/mdc-list/list-base.ts

fix(docs/typography-guide): Defining a level
Fixes a bug in the Topography Guide where a function was incorrectly named. Replaces 'define-topography-config' with 'define-topography-level'
Fixes https://github.com/angular/components/issues/25030

fix(docs/typography-guide): Defining a level

---

src/dev-app/theme.scss
src/material-experimental/mdc-button/button.scss
src/material-experimental/mdc-button/fab.scss
src/material-experimental/mdc-checkbox/BUILD.bazel
src/material-experimental/mdc-chips/chip.scss
src/material-experimental/mdc-core/BUILD.bazel
src/material-experimental/mdc-helpers/_focus-indicators-theme.scss
src/material-experimental/mdc-helpers/_focus-indicators.scss
src/material-experimental/mdc-list/list.scss
src/material-experimental/mdc-radio/BUILD.bazel
src/material-experimental/mdc-radio/radio.scss
src/material-experimental/mdc-slide-toggle/BUILD.bazel
src/material-experimental/mdc-tabs/BUILD.bazel
src/material/_index.scss
src/material/button/button.scss
src/material/chips/chips.scss
src/material/core/_core.scss
src/material/core/focus-indicators/_focus-indicators-theme.scss
src/material/core/focus-indicators/_focus-indicators.scss
src/material/core/focus-indicators/_private.scss
src/material/core/theming/tests/test-theming-bundle.scss
src/material/datepicker/calendar.scss
src/material/expansion/BUILD.bazel
src/material/sort/sort-header.scss

I skipped over some of the feedback on #25039 in order to get the focus indicator changes merged in quicker. This is a follow-up to address the remaining feedback.

refactor(material/core): clean up focus indicators

---

src/cdk/scrolling/virtual-scroll-viewport.spec.ts
src/cdk/scrolling/virtual-scroll-viewport.ts

We were creating the `transform` string before adjusting the offset for `appendOnly` mode which was causing the list to jump down before being reset on the next scroll event.
These changes resolve the issue by moving the offset adjustment up to before the `transform`.
Fixes #25077.

fix(cdk/scrolling): content jumping in appendOnly mode

---

package.json

Apparently the `ng-dev` command does not work with Git Bash on windows
because of the environment variable being set. We should use `ts-node`
directly to avoid this issue, and also avoid the `$PWD` access which
might not work depending on the shell.
Also on the dev-infra side we would need to remove the ts-node shebang
and leave the responsibility to the consumer project.

build: ensure ng-dev command works on windows

---

package.json
tools/defaults.bzl

We can directly use `ts-node` to avoid printing errors twice when
the nested execution fails.
e.g.
```
Not enough non-option arguments: got 0, need at least 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

build: avoid use of `yarn ts-node` to avoid nested yarn execution

---

src/material/button-toggle/button-toggle.scss

It looks like at some point we regressed to where the selected indication in high contrast mode became transparent.

fix(material/button-toggle): selected state not visible in high contrast mode

---

test/benchmarks/cdk/testing/component-harness/BUILD.bazel
test/benchmarks/cdk/testing/component-harness/testbed.perf-spec.ts
test/benchmarks/material/button/BUILD.bazel
test/benchmarks/material/card/BUILD.bazel
test/benchmarks/material/checkbox/BUILD.bazel
test/benchmarks/material/chips/BUILD.bazel
test/benchmarks/material/form-field/BUILD.bazel
test/benchmarks/material/menu/BUILD.bazel
test/benchmarks/material/radio/BUILD.bazel
test/benchmarks/material/slide-toggle/BUILD.bazel
test/benchmarks/material/table/BUILD.bazel
test/benchmarks/material/tabs/BUILD.bazel
test/benchmarks/mdc/button/BUILD.bazel
test/benchmarks/mdc/card/BUILD.bazel
test/benchmarks/mdc/checkbox/BUILD.bazel
test/benchmarks/mdc/chips/BUILD.bazel
test/benchmarks/mdc/form-field/BUILD.bazel
test/benchmarks/mdc/menu/BUILD.bazel
test/benchmarks/mdc/radio/BUILD.bazel
test/benchmarks/mdc/slide-toggle/BUILD.bazel
test/benchmarks/mdc/table/BUILD.bazel
test/benchmarks/mdc/tabs/BUILD.bazel

Fixes the benchpress test build errors due to an old change
where the driver utilities have been moved.
Note that most benchpress-tests are still failing currently at runtime as it seems,
mostly because `@angular/core` imports from `rxjs/operators` without an
explicit extension, breaking runtime ESM resolution. We would need to consider
bundling tests in benchmark tests, similar to how we do it in the CLI or elsehwere.
(or we wait until we eventually use the new node resolution in Angular framework as well..)

build: fix benchpress build errors

---

src/material/datepicker/datepicker-actions.spec.ts
src/material/datepicker/datepicker-base.ts
tools/public_api_guard/material/datepicker.md

Fixes that we were only refreshing the actions while the calendar is closed.
Fixes #25122.

fix(material/datepicker): actions not re-rendering if swapped out while calendar is open

---

package.json
yarn.lock

`ts-node` spawns a custom node launcher script and has a brotli-base64
encoded configuration that will point to the user-provided entry-point.
This breaks child process forking as we wouldn't be able to specify our
custom build worker and basically `ng-dev` would run inside `ng-dev`
again.

build: avoid use of ts-node wrapper script as it breaks child process forking

---

.ng-dev/pull-request.mts
package.json
scripts/docs-deploy/deploy-ci-push.mts
yarn.lock

Important notes:
1. `main` will temporarily not deploy to `next.material.angular.io`. We will just deploy to v15.material.angular.io
2. The v15 docs site is based on the `material.angular.io` repo `15.x` branch (preparation can land there)
3. Exceptional minors are published to `next.material.angular.io` and `rc.material.angular.io`.

build: prepare for v15 and exceptional minors for v14

---

src/material/core/common-behaviors/error-state.ts
src/material/stepper/stepper.ts
tools/public_api_guard/material/stepper.md

fix(material/stepper): isErrorState accepts AbstractControl instead of UntypedFormControl to avoid compiler errors when strict typing is enabled

---

scripts/docs-deploy/install-built-packages.mts

We were adding a `resolutions` field to the package.json of the docs site when deploying it from the main repo to try and control the version that is installed. This appears to be causing an issue where Yarn duplicates the dependencies which in turn causes Webpack to bundle them once for the main site and another for the lazy-loaded chunks with the examples. These changes resolve the issue by not adding the `resolutions` field.
For reference, currently the docs package depends on `@angular/cdk@14.1.0-next.1+sha-7d87068-with-local-changes` whereas the docs site depends on `@angular/cdk@file://path/to/repo/dist/releases/cdk`.
Fixes #24992.

build: dependencies duplicated when deploying snapshots

---

src/components-examples/material-experimental/mdc-table/table-selection/table-selection-example.html
src/components-examples/material-experimental/mdc-table/table-selection/table-selection-example.ts
src/components-examples/material/table/table-selection/table-selection-example.html
src/components-examples/material/table/table-selection/table-selection-example.ts
src/material/core/style/_variables.scss
src/material/table/table.md

Rename master to main in misc docs examples and code comments.

fix(docs): rename master to main

---

src/dev-app/google-map/google-map-demo.html
src/dev-app/google-map/google-map-demo.ts
src/dev-app/index.html
src/dev-app/youtube-player/youtube-player-demo.ts

Only loads the Google Maps and YouTube APIs when they are necessary in the dev app. This will make the app load quicker and reduce the amount of logs in the console.

build: load Google Maps and YouTube APIs on demand in dev app

---

src/components-examples/material/autocomplete/autocomplete-display/autocomplete-display-example.ts

The example code is highly trusted and sometimes
taken as is (copy-paste), so it is important to
have it optimised if possible.
Each map means an iteration over the array items.
By using single map, an iteration is saved, and
an approximate performance of about 38% is won.
I measured the performance here: https://jsbench.me/dbl4wkw3r9/1

docs(material/autocomplete): use single map instead of two maps in a row

---

src/material-experimental/mdc-chips/chip-row.html

Fixes that we didn't have a `role="gridcell"` around the trailing action of a `mat-chip-row`.

fix(material-experimental/mdc-chips): missing role for trailing actions container

---

src/components-examples/material/icon/icon-harness/icon-harness-example.html
src/components-examples/material/icon/icon-harness/icon-harness-example.spec.ts
src/components-examples/material/icon/icon-overview/icon-overview-example.html
src/dev-app/icon/icon-demo.html
src/material/icon/icon-registry.ts
src/material/icon/icon.scss
src/material/icon/icon.spec.ts
src/material/icon/icon.ts
src/material/icon/testing/shared.spec.ts
tools/public_api_guard/material/icon.md

The new way to use ligature icons, via the `fontIcon` attribute, allows to hide
the font name from search engine results. Otherwise, the font name, which was
never intended to be read by any end-users, would appear in the middle of legit
sentences in search results, thus making the search result very confusing to read.
New recommended usage is:
```diff
- <mat-icon>home</mat-icon>
+ <mat-icon fontIcon="home"></mat-icon>
```
To also enable this for custom font, include the special `mat-ligature-font` class
when registering the font alias. So like this:
```ts
iconRegistry.registerFontClassAlias('f1', 'font1 mat-ligature-font');
```
And use like this:
```html
<mat-icon fontSet="f1" fontIcon="home"></mat-icon>
```
Fixes https://github.com/angular/components/issues/23195
Fixes …

feat(material/icon): SEO friendly ligature icons

---

package.json

Renovate incorrectly is fine using Yarn 2+ for the components
repo because our enignes field is too loose.

build: fix loose yarn engine range

---

src/cdk/portal/dom-portal-outlet.ts
src/cdk/portal/portal-directives.ts
src/cdk/portal/portal.spec.ts
src/cdk/portal/portal.ts
tools/public_api_guard/cdk/portal.md

Allows for the `projectableNodes` parameter to be used with a component portal.
Fixes #9045.

feat(cdk/portal): support projectableNodes in component portal

---

CHANGELOG.md

Cherry-picks the changelog from the "14.0.x" branch to the next branch (main).

docs: release notes for the v14.0.4 release

---

CHANGELOG.md

Cherry-picks the changelog from the "14.1.x" branch to the next branch (main).

docs: release notes for the v14.1.0-next.3 release

---

CONTRIBUTING.md

We just renamed the Angular code of conduct repository default branch
to `main`. This repository was not part of the large migration and is
now handled separately as a little clean-up.

build: account for rename of angular/code-of-conduct default branch

---

src/material-experimental/mdc-checkbox/checkbox.scss
src/material/checkbox/checkbox.scss

Fixes that the checkbox looked broken when placed in some CSS grid layouts.
Fixes #25153.

fix(material/checkbox): broken appearance in some grid layouts

---

.github/workflows/build-dev-app.yml
.github/workflows/deploy-dev-app.yml
.github/workflows/lock-closed.yml

We have changed the default permissions for Github actions as it seems,
and the PR comment cannot be created in actions without having the
necessary write permission. This commit fixes this.

build: fix dev-app preview action permissions

---

src/material-experimental/mdc-form-field/_form-field-density.scss
src/material-experimental/mdc-form-field/_form-field-theme.scss
src/material-experimental/mdc-form-field/directives/notched-outline.ts
src/material-experimental/mdc-form-field/form-field.html
src/material-experimental/mdc-form-field/form-field.scss
src/material-experimental/mdc-form-field/form-field.ts

This allows the value to be shared across CSS & JS.
Fixes b/229434440

fix(material-experimental/mdc-form-field): use a CSS var for the floating label scale

---

CONTRIBUTING.md

In CONTRIBUTING.md there are two broken links:
1)  `full list` that should point to the renamed `commit-message.mts` file
2) `gitter` that probably should point to `https://gitter.im/angular/material2`

docs: Fix two links in CONTRIBUTING.md

---

src/material-experimental/mdc-paginator/BUILD.bazel
src/material-experimental/mdc-paginator/_paginator-theme.scss
src/material-experimental/mdc-paginator/paginator.scss

MDC recently added support for -5 form-field density (b/217245308). The paginator should respect that if requested.

fix(material-experimental/mdc-paginator): allow form-field density to go lower than -4

---

integration/harness-e2e-cli/BUILD.bazel
integration/harness-e2e-cli/e2e/radio-harness.spec.ts
integration/harness-e2e-cli/package.json
integration/harness-e2e-cli/src/app/app.component.html
integration/harness-e2e-cli/src/app/app.module.ts
integration/harness-e2e-cli/yarn.lock

Tries to de-flake the harness e2e integration test by swapping out `mat-select` with `mat-selection-list`. `mat-select` has been causing flakes in its own Firefox tests too so it's possible that it may be the reason for the integration test flakes as well.
The component being tested doesn't really matter since the integration test is primarily verifying our npm packages.

build: attempt to de-flake harness integration test

---

integration/harness-e2e-cli/e2e/radio-harness.spec.ts

Increases the Jasmine timeout interval for the harness integration tests to try and reduce the CI flakes.

build: increase timeout for harness integration test

---

src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
src/cdk/a11y/focus-monitor/focus-monitor.ts

In most cases focus moves during `mousedown` so all of our detection uses `mousedown` events to track it. It breaks down for the common use case where a `label` is connected to an `input`, because there focus moves on the `click` event instead. This has been a long-standing issue with the `FocusMonitor` that has caused problems for `mat-checkbox`, `mat-radio-button` and `mat-slide-toggle`.
These changes add special handling for the `input` + `label` case that checks if the previous mouse interaction was with a label belonging to the current `input` receiving focus.
Fixes #25090.

fix(cdk/a11y): correctly detect focus from input label

---

src/material-experimental/mdc-core/option/option.scss
src/material/core/option/option.scss

Currently we don't indicate which `mat-option` is selected in single-selection mode to high contrast users. These changes add a small indicator similar to the one in `mat-selection-list`.

fix(material/select): add selected indication in high contrast mode

---

src/material-experimental/mdc-form-field/_form-field-theme.scss
src/material-experimental/mdc-form-field/directives/notched-outline.ts
src/material-experimental/mdc-form-field/form-field.scss
src/material/_index.scss
src/material/core/style/_vendor-prefixes.scss

fix(material-experimental/mdc-form-field): fix notch visual artifact

---

renovate.json

We always want to pin to the versions we use, and not rely on
version ranges. This is an attempt to fix that the Bazel workspace
file has not been updated.
https://github.com/angular/dev-infra/runs/7289796990?check_suite_focus=true.

build: use `pin` instead of `replace` range strategy

---

src/material-experimental/mdc-checkbox/_checkbox-theme.scss
src/material-experimental/mdc-radio/_radio-theme.scss
src/material-experimental/mdc-slide-toggle/_slide-toggle-theme.scss

MDC does not set the disabled text color on the label for the checkbox,
radio, or switch. This change applies it on the Angular Material side.
Fixes b/224789079

fix(multiple): fix disabled label style

---

src/cdk/clipboard/pending-copy.ts

Fixes the page jump when copying to the clipboard on newer versions of iOS by making the temporary `textarea` readonly.
Fixes #25169.

fix(cdk/clipboard): page jumping on iOS

---

src/material/core/theming/tests/test-legacy-theming-bundle.scss
src/material/core/theming/tests/theming-api.spec.ts

When we switched to the `@use` API we did not update some of the tests.
https://github.com/angular/components/pull/22173

test: fix incorrect usage in theming tests

---

src/material/tabs/ink-bar.ts

In #24000 the ink bar was switched from `requestAnimationFrame` to `NgZone.onStable` in order to avoids timeouts when the browser is in the background. The problem is that if the zone is already stable, it may take some user interaction before it becomes unstable again and emits to `onStable`.
These changes wrap the call in `NgZone.run` to guarantee that it'll be unstable.
Fixes #25117.

fix(material/tabs): ink bar not shown in some cases

---

src/material-experimental/mdc-button/button-base.ts
src/material-experimental/mdc-button/button.html
src/material-experimental/mdc-button/icon-button.html
src/material-experimental/mdc-button/icon-button.ts

fix(material-experimental/mdc-button): always treat icon-button content as an icon

---

src/material-experimental/mdc-core/option/option.scss
src/material-experimental/mdc-form-field/form-field.scss

Import of CDK was duplicated in https://github.com/angular/components/commit/25ce8e775c8344407159381fdb61066d216e054e
Material import was missing in https://github.com/angular/components/commit/4727c8b5e4cf8a30ed782262559c42e641911b26

ci: fix incorrect style imports

---

scripts/docs-deploy/snapshot-deploy.mts

This makes it easier to spot where the docs deploy job deploys to.

build: improve logging for docs deployment targets

---

src/cdk-experimental/listbox/BUILD.bazel
src/cdk-experimental/listbox/listbox.spec.ts
src/cdk-experimental/listbox/listbox.ts
src/cdk/collections/selection-model.ts
src/dev-app/cdk-experimental-listbox/cdk-listbox-demo.html
src/dev-app/cdk-experimental-listbox/cdk-listbox-demo.ts
tools/public_api_guard/cdk/collections.md

This PR addresses:
- Stop using a stream of `SelectionModel` in favor of just using a single `SelectionModel`
- Fix value binding test
- Add missing keyboard support & tests for new keys
- Remove `CdkCombobox` dependency
**Deprecation Note:**
The `select`, `deselect`, `setSelection`, `toggle`, and `clear` methods on `SelectionModel` from `@angular/cdk/collections` now return a boolean indicating whether the selection changed as a result  of the call. For backwards compatibility the methods are typed as `boolean | void`, but this will be changed to `boolean` in version 16.

fix(cdk-experimental/listbox): clean up some TODOs

---

CHANGELOG.md

Cherry-picks the changelog from the "14.0.x" branch to the next branch (main).

docs: release notes for the v14.0.5 release

---

guides/elevation.md

The Link in [guides/elevation.md](https://material.angular.io/guide/elevation) is broken. 
This PR fixes that by introducing the missing link handle.

docs: Fix link to theming-guide in guides/elevation.md

---

src/material-experimental/mdc-snack-bar/_snack-bar-theme.scss
src/material-experimental/mdc-snack-bar/snack-bar-container.scss

Reworks the MDC-based snack bar to use the new CSS-variable-based theming APIs.

refactor(material-experimental/mdc-snack-bar): switch to new theming API

---

src/material-experimental/mdc-snack-bar/_snack-bar-theme.scss

Fixes some code that is out of sync with the code we have internally. I added the extra `@if` when I was resolving issues with #25273.

refactor(material/snack-bar): fix out-of-sync code

---

src/material/slider/slider.ts

Adds checks to ensure that `touchmove` and `touchend` events are cancelable before we call `preventDefault` on them.
Fixes #25272.

fix(material/slider): add cancelable checks to touchmove and touchend events

---

src/dev-app/mdc-card/mdc-card-demo.html
src/material/card/card.scss

Note: This change is for the MDC-based card (now called material/card)
The card demo page forgot to include mat-card-header which caused many
of the cards to look strange. At some point it looks like padding was
added to mat-card-title-group to compensate in some cases. This PR
removes that padding and adds the missing mat-card-header blocks
instead.

fix(material/card): don't add extra padding around mat-card-title-group

---

scripts/check-mdc-tests-config.ts
src/material/checkbox/checkbox.spec.ts
src/material/checkbox/checkbox.ts

Fixes that we weren't setting the correct animation class when the checkbox goes from being pre-checked to indeterminate.
Fixes #25289.

fix(material/checkbox): incorrect animation state when going from pre-checked to indeterminate

---

src/material-experimental/mdc-tabs/_tabs-common.scss

Fixes that the transition of the tab label color wasn't being disabled when all animations are disabled.

fix(material/tabs): disable tab label color transition when animations are disabled

---

CHANGELOG.md

Cherry-picks the changelog from the "14.0.x" branch to the next branch (main).

docs: release notes for the v14.0.6 release

---

src/cdk/overlay/overlay-ref.ts
src/cdk/overlay/overlay.spec.ts

Fixes that some of the overlay elements were left behind when the portal is destroyed without going through the overlay API. We need to handle this case, because in many cases users don't have access to the `OverlayRef` (e.g. `MatDialog`) so that they can call `dispose` themselves.
Fixes #25163.

fix(cdk/overlay): detach overlay when portal is destroyed from the outside

---

src/material-experimental/mdc-paginator/paginator.scss
src/material/paginator/paginator.scss

Some CSS resets like [Tailwind's Preflight](https://unpkg.com/tailwindcss@3.1.4/src/css/preflight.css) set the `display` value of the SVG element to `block` which break the design
of the mat-paginator-icon by making it not properly centered inside the button.

refactor: explicitly set the display of the mat-paginator-icon to inline

---

src/dev-app/mdc-chips/mdc-chips-demo.html
src/material-experimental/mdc-chips/chip-row.html
src/material-experimental/mdc-chips/chip-row.spec.ts
src/material-experimental/mdc-chips/chip-row.ts

Currently we always use a `button` element inside the `mat-chip-row` which can be confusing for users if the row isn't editable, because the button won't do anything.
These changes switch to using a `span` whose `role` we toggle based on whether it's editable.
The change ended up trickier than expected, because:
1. The focus behavior of the `span` is slightly different from the button we had before.
2. The focus restoration after an edit is finished is currently working by accident. When editing starts, we set `isInteractive = false` on the primary action which clears its `tabindex`. When editing is finished, we reset the flag, but change detection hasn't had the chance to run so the element won't actually have a `tabindex` at the moment when we try to restore focus. It worked by accident …

fix(material-experimental/mdc-chips): don't use button element if chip row isn't editable

---

.github/CODEOWNERS

We should just use the explicit names since there aren't a lot
of instances, and this is not changing very often.
The change back then did not bring a lot of benefits but rather made
reviews more annoying since irrelevant PRs had to be unassigned twice
to disappear in the `Requested reviews` view. This is because I'm
sometimes requested explicitly through other ownerships, but then also
through the dev-infra group.
Also changed the owners of `goldens/` away from dev-infra since I don't know that
this is correct. Codeowners are not super strictly needed in this repo anyway..

build: avoid use of github team for dev-infra codeowner

---

src/cdk/drag-drop/directives/drag.spec.ts
src/cdk/drag-drop/directives/drag.ts
src/cdk/drag-drop/drag-ref.ts
tools/public_api_guard/cdk/drag-drop.md

Exposes the pickup position within the element to the `constrainPosition` callback so that users can account for it in their calculations.
Relates to #25154.

fix(cdk/drag-drop): expose pickup position in constrainPosition callback

---

src/cdk/schematics/update-tool/component-resource-collector.ts

We have some code to strip BOM from TS files when running a migration, but it doesn't apply to migrations of Sass files.
These changes reuse the same code for Sass migrations, because the BOM can cause errors in the Sass compiler (see https://github.com/angular/components/issues/24227#issuecomment-1200934258).

fix(cdk/schematics): strip bom from sass files

---

src/material/legacy-select/BUILD.bazel
src/material/select/BUILD.bazel
src/material/select/select.e2e.spec.ts

In a previous PR I assumed that a timeout in the select e2e tests was a flake, but it was actually a failure, because the test is running against the docs examples which were switched over to MDC.

build: fix select e2e tests

---

src/material/schematics/ng-update/BUILD.bazel

Fixes the build error in the snapshots check by applying a similar fix to #25303.

build: fix snapshot tests failure

---

CHANGELOG.md

docs: release notes for the v14.2.0-next.1 release

---

src/material/form-field/directives/error.ts
src/material/form-field/form-field.html
src/material/form-field/testing/shared.spec.ts
tools/public_api_guard/material/form-field.md

Adds an ability to use custom error components tagged with [matError] attributes inside a form field. This is useful when a reusable custom error message template is needed for form fields.
Example:
```html
<mat-form-field>
<mat-label>Label</mat-label>
<input matInput>
<custom-error matError>Error message</custom-error>
</mat-form-field>
```

feat(material/form-field): Ability to support custom error message components inside a form field

---

src/material/dialog/_dialog-theme.scss
src/material/dialog/dialog.scss

The MDC dialog was using the `core-styles` mixin instead of the `static-styles` which is supposed to be used together with the new theming API. I've also removed the `container-elevation` and `container-shadow-color` variables from the theme since they weren't doing anything.

fix(material/dialog): using incorrect mixin for structural styles

---

src/material/legacy-input/_input-theme.scss

Fixes https://github.com/angular/components/issues/25346
https://user-images.githubusercontent.com/25158423/182974344-aa0471f4-c5c3-4335-ba7b-29767830b069.mov

fix(material/input): fix input prefix & suffix disabled color

---

src/material/_index.scss
src/material/core/selection/pseudo-checkbox/_pseudo-checkbox-common.scss
src/material/core/selection/pseudo-checkbox/pseudo-checkbox.scss
src/material/core/style/_checkbox-common.scss

This PR does not change the pseudo-checkbox styles. That will be done in a follow-up where the size is changed from 16px to 18px to match the MDC version.
This moves the pseudo-checkbox size styles into a mixin that can be given a size. This can be used in a follow-up PR to switch from $legacy-size to $size once all affected internal clients call the legacy size mixin.

feat(material/checkbox): refactor pseudo-checkbox size styles

---

src/material/legacy-checkbox/checkbox.scss

This is a no-op change since both `$size` and `$legacy-size` are `16px`

feat(material/checkbox): use $legacy-size for legacy checkbox

---

src/material/chips/chip-listbox.spec.ts
src/material/legacy-chips/chip-list.spec.ts
src/material/legacy-chips/chip-list.ts

fix(material/chips): `selectable="false"` doesn't work on initial assignment

---

src/cdk/overlay/position/flexible-connected-position-strategy.ts
src/components-examples/material/tooltip/index.ts
src/components-examples/material/tooltip/tooltip-position-at-origin/tooltip-position-at-origin-example.css
src/components-examples/material/tooltip/tooltip-position-at-origin/tooltip-position-at-origin-example.html
src/components-examples/material/tooltip/tooltip-position-at-origin/tooltip-position-at-origin-example.ts
src/dev-app/tooltip/tooltip-demo.html
src/material/legacy-tooltip/tooltip.spec.ts
src/material/tooltip/tooltip.md
src/material/tooltip/tooltip.spec.ts
src/material/tooltip/tooltip.ts

Add an input option `matTooltipPositionAtOrigin` to display the tooltip relative to the mouse or touch event that triggered it.
Fixes #8759

feat(material/tooltip): add option to open tooltip at mouse position

---

CHANGELOG.md

Cherry-picks the changelog from the "14.1.x" branch to the next branch (main).

docs: release notes for the v14.1.2 release

---

CHANGELOG.md

docs: release notes for the v14.2.0-next.2 release

---

src/material/core/selection/pseudo-checkbox/pseudo-checkbox.scss
src/material/core/style/_checkbox-common.scss

- Pseudo checkbox is now 18px height/width instead of 16px. Import the mat.pseudo-checkbox-legacy-size() to apply the legacy size styles

feat(material/checkbox): update pseudo-checkbox size

---

src/material/card/_card-theme.scss
src/material/card/card.scss
src/material/card/card.ts

Reworks the card component to use the new CSS-variable-based theming API from MDC.

refactor(material/card): switch to new theming API

---

src/cdk/dialog/dialog.spec.ts
src/cdk/dialog/dialog.ts

In #24570 the template dialog was changed so that the dialog ref is resolved from the template injector, rather than the DOM. The problem is that existing logic for constructing the injector was reused which means that the lookup path for a token starting from inside the `ng-template` would be `start -> node injector -> template injector -> app injector` instead of `start -> node injector -> template injector -> node injector -> app injector`. This has caused some regressions for users of `@angular/router` like https://github.com/angular/angular/issues/46500.
These changes resolve the issue by not providing a fallback injector so that the framework automatically falls back to the node injector.

fix(cdk/dialog): fall back to node injector token doesn't exist in template injector

---

src/components-examples/material/expansion/expansion-expand-collapse-all/expansion-expand-collapse-all-example.css
src/components-examples/material/expansion/expansion-steps/expansion-steps-example.css
src/material/expansion/expansion-panel-header.html
src/material/expansion/expansion-panel-header.scss
src/material/expansion/expansion.spec.ts

* Add margin to `.mat-content` element to account for consumer using
`mat-expansion-panel` components with the toggle hidden alongside
`mat-expansion-panel` components where the toggle is visible
* Adjust sizing of `.mat-expansion-panel-header-title` and
`.mat-expansion-panel-header-description` elements so that the width
of each respective element is uniform across multiple adjacent
`mat-expansion-panel` elements
* Fixes #20002
**LTR**
**RTL**
Caretaker Note (andrewseguin, 2022-04): Breaks ~50 screenshot tests. Text in expansion panels are getting shifted over maybe 10 - 15px

fix(expansion): fix expansion `.mat-expansion-panel-header` styles

---

src/material/button-toggle/button-toggle.html
src/material/button-toggle/button-toggle.spec.ts
src/material/button-toggle/button-toggle.ts
tools/public_api_guard/material/button-toggle.md

Currently we assign the group name to each individual toggle on init or when the group name changes, but that doesn't account for when the toggle's name changes independently.
These changes switch to using a getter which will update automatically if anything changes.
Fixes #24666.

fix(material/button-toggle): toggle name falling out of sync if name changes

---

src/dev-app/youtube-player/BUILD.bazel
src/dev-app/youtube-player/youtube-player-demo.html
src/dev-app/youtube-player/youtube-player-demo.ts
src/youtube-player/youtube-player.spec.ts
src/youtube-player/youtube-player.ts
tools/public_api_guard/youtube-player/youtube-player.md

Adds a `disableCookies` input that puts the player into "no cookie" mode.
Fixes #19681.

feat(youtube-player): support no cookie mode

---

guides/creating-a-custom-form-field-control.md

not defined `elRef` was changed on defined `_elementRef`

docs(material/custom-form-field): fixed propname

---

src/material/legacy-table/testing/cell-harness.ts
src/material/table/testing/cell-harness.ts

some users are extending the harnesses, and passing the concrete class broke them
CARETAKER NOTE: already submitted in g3

feat(material/table): pass `this` rather than concrete classes in the harnesses

---

src/cdk/overlay/overlay-directives.ts
tools/public_api_guard/cdk/overlay.md

The type of backdropClass in overlay-directives.ts was not matching that in overlay-config.ts, which prevented string[] inputs from being passed through with strict templates enabled.

fix(cdk/overlay): backdropClass type mismatch

---

CHANGELOG.md

Cherry-picks the changelog from the "14.1.x" branch to the next branch (main).

docs: release notes for the v14.1.3 release

---

CHANGELOG.md

docs: release notes for the v14.2.0-rc.0 release

---

.circleci/config.yml

Yarn 1.x has a bug where it keeps nested unused node modules and doesn't
delete them automatically. This throws off Bazel in some scenarios when
the lock file is updated. This commit invalidates the cache to get a
fresh clean node modules cache without any unused nested directories.

build: invalidate circleci cache to prune unused nested node modules

---

src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
src/cdk/a11y/focus-monitor/focus-monitor.ts
tools/public_api_guard/cdk/a11y.md

feat(cdk/a11y): add named export and public property to CdkMonitorFocus directive

---

src/cdk/scrolling/virtual-scroll-viewport.ts

Fixes that an error was being thrown by the virtual scroller during server-side rendering. It wasn't failing the SSR check, because the error happens inside of a promise callback.

fix(cdk/scrolling): error during server-side rendering

---

src/dev-app/table-scroll-container/BUILD.bazel
src/dev-app/table-scroll-container/table-scroll-container-demo.scss
src/dev-app/table-scroll-container/table-scroll-container-demo.ts
src/material/legacy-table/testing/BUILD.bazel
src/material/legacy-table/testing/table-harness.spec.ts
src/material/table/testing/BUILD.bazel
src/material/table/testing/shared.spec.ts
src/material/table/testing/table-harness.spec.ts

Cleanup various places where the legacy table was still present - Swapped where the harness tests were located (previously still in legacy)

fix(material/table): cleanup legacy usage

---

.ng-dev/pull-request.mts
scripts/docs-deploy/deploy-ci-push.mts

We no longer have an exceptional minor and can remove the logic we put
in place given the release tool not supporting exceptional minors well yet.

build: remove exceptional minor logic

---

src/cdk/collections/data-source.ts

The `isDataSource` function determines that something is a data source by checking if it has a `connect` method. The problem is that rxjs has a `ConnectableObservable` which also has a `connect` method and which gets incorrectly identified as a data source.
Fixes #25483.

fix(cdk/collections): ConnectableObservable incorrectly inferred as data source

---

src/material/datepicker/aria-accessible-name.spec.ts
src/material/datepicker/aria-accessible-name.ts
src/material/datepicker/calendar-body.html
src/material/datepicker/calendar-body.scss
src/material/datepicker/calendar-body.ts
src/material/datepicker/calendar.html
src/material/datepicker/calendar.ts
src/material/datepicker/date-range-input-parts.ts
src/material/datepicker/date-range-input.spec.ts
src/material/datepicker/date-range-input.ts
src/material/datepicker/date-range-picker.ts
src/material/datepicker/datepicker-base.ts
src/material/datepicker/datepicker-content.html
src/material/datepicker/month-view.html
src/material/datepicker/month-view.ts
tools/public_api_guard/material/datepicker.md

For date ranges, add aria-descriptions to the cell of the current start
date and also for end date.
Popuplate aria descriptions with the expected value of the ARIA accessible name of the
`matStartDate` and `matEndDate` inputs. Introduces `_computeAriaAccessibleName` function to
implement ARIA acc-name-1.2 specificiation.
Fixes https://github.com/angular/components/issues/23442 and https://github.com/angular/components/issues/23445

fix(material/datepicker): calendar aria-descriptions start/end date

---

src/material/button-toggle/button-toggle.ts
tools/public_api_guard/material/button-toggle.md

Removes some logic that was trying to incorrectly match the button toggle being clicked with the model value. The logic wasn't necessary since we already know which toggle the user interacted with.
Fixes #25489.

fix(material/button-toggle): incorrect event source in some cases

---

src/cdk/testing/tests/cross-environment.spec.ts

This is needed by some downstream custom angular harnesses that use this set of tests but also do not rely on Angular framework stabilization.

test(cdk/testing): add includeAsyncTests flag

---

src/material/dialog/dialog-animations.ts
src/material/dialog/dialog-config.ts
src/material/dialog/dialog-container.ts
src/material/dialog/dialog.scss
src/material/dialog/dialog.ts
src/material/dialog/public-api.ts
src/material/legacy-dialog/dialog-config.ts
src/material/legacy-dialog/dialog-container.ts
src/material/legacy-dialog/dialog.ts
src/material/legacy-dialog/public-api.ts
tools/public_api_guard/material/dialog.md
tools/public_api_guard/material/legacy-dialog.md

- Passing strings for `MatDialogConfig.enterAnimationDuration` and
`MatDialogConfig.exitAnimationDuration` is deprecated, pass numbers
in ms instead

fix(material/dialog): allow customizing animation duration

---

src/material/datepicker/public-api.ts
tools/public_api_guard/material/datepicker.md

These have been used internally but required special importing since they were not exported

feat(material/datepicker): expose datepicker symbols

---

scripts/check-public-api-formats.js

* check that all exports from public-api.ts are  explicit exports
* check that all exported symbols contain 'legacy'

build: add checks for public-api.ts formats

---

CHANGELOG.md

docs: release notes for the v14.2.1 release

---

src/material/paginator/paginator.ts

docs: fix material paginator comment style by adding missing periods.

---

src/cdk/listbox/listbox.spec.ts
src/cdk/listbox/listbox.ts
tools/public_api_guard/cdk/listbox.md

The CDK listbox had a subscription to its model changes in the constructor which fires immediately due to the `startsWith` and which was attempting to sort the selected values when in multiple selection mode. The problem is that the options aren't available until `ngAfterContentInit` which was causing an error when we tried to do the sorting.
These changes move the change event subscription to `ngAfterContentInit` so that options are guaranteed to be defined when it fires.
Fixes #25611.

fix(cdk/listbox): error with multiple preselected values

---

src/cdk/menu/menu-item.spec.ts
src/cdk/menu/menu-item.ts
src/cdk/menu/menu-trigger.spec.ts
src/cdk/menu/menu-trigger.ts
tools/public_api_guard/cdk/menu.md

Fixes that the CDK menu trigger and menu item were preventing the default action on enter and space key presses. Presumably this was done to avoid form submissions, but it can also prevent anchors from being used as menu items. These changes avoid submissions by setting the `type` attribute on `button` elements.
Fixes #25584.

fix(cdk/menu): don't prevent default enter and space actions

---

src/material/legacy-menu/menu.spec.ts
src/material/menu/menu-item.ts
src/material/menu/menu-trigger.ts
src/material/menu/menu.spec.ts
tools/public_api_guard/material/menu.md

In #24437 we added the ability to conditionally remove a menu from a menu trigger. The problem is that the flag that determines if the menu item has the small triangle indicator is only set in the constructor. These changes move the logic to the setter and add a `markForCheck` to ensure that the view is in sync.

fix(material/menu): update submenu indication when menu is assigned

---

src/material/core/typography/_all-typography.scss

Fixes a deprecation warning, because we were using a slash for division instead of `math.div`.

refactor(material/core): fix deprecation warning

---

src/cdk/a11y/high-contrast-mode/high-contrast-mode-detector.ts

Windows 11 has different built in high contrast themes which weren't being picked up by the detector.
Fixes #25580.

fix(cdk/a11y): account for Windows 11 high contrast themes in detector

---

src/material/datepicker/datepicker-base.ts

Currently the datepicker restores focus when the closing sequence starts, but in some cases that can cause focus to be lost. When the calendar view changes, we delay moving focus for a while in order to work around a VoiceOver issue. This means that if a closing sequence is kicked off while there's an in-progress view change, focus may end up being restored, then moved back into the calendar which then gets destroyed. This can be seen in the "Datepicker emulating a Year and month picker" example.
These changes resolve the issue by moving the focus restoration all the way to the end of the closing sequence.
Fixes #25564.

fix(material/datepicker): restore focus after closing animation

---

src/material/core/theming/_theming.scss

Warn users when creating a theme using the legacy API (passing palettes). Users should switch to the new theming config API. Legacy API support will be removed in v16. This warning can be converted to an error internally to make it easy to remove in v16

fix(material/core): warn when legacy theme is created

---

.circleci/config.yml

We had to temporarily disable the CircleCI orb command that helps ensuring snapshot jobs
do not conflict when running concurrently.
It seems like the CircleCI API has been fixed to no longer cause issues with the Orb. This commit
attempts to re-enable the command.

ci: re-enable until front of line blocking in publish snapshot job

---

src/material/form-field/_form-field-native-select.scss
src/material/select/select.scss

fix(material/select): fix arrow alignment

---

CHANGELOG.md

docs: release notes for the v14.2.2 release

---

src/material/core/theming/_theming.scss

Add a flag that can be transformed to "true" internally that produces an error if users call a theming function with an incomplete map.
For example, calling `mat.button-typography($theme)` that doesn't have `typography` will error. 
Another example, calling `mat.button-theme($theme)` without color, typography, and density will error.
For cases where users do not want to include certain styles, e.g. typography, they should directly call "-color()" and "-density()" and skip "-typography()"
The intent of this is to standardize theming configurations internally so that all apps explicitly declare what they want to include in their theming, making it more clear what they are not including as well. All apps will default to `typography: null` or `density: 0` if it is missing in their theme …

fix(material/core): add optional warning for incomplete themes

---

src/material/core/theming/prebuilt/deeppurple-amber.scss
src/material/core/theming/prebuilt/indigo-pink.scss
src/material/core/theming/prebuilt/pink-bluegrey.scss
src/material/core/theming/prebuilt/purple-green.scss
src/material/legacy-core/theming/prebuilt/deeppurple-amber.scss
src/material/legacy-core/theming/prebuilt/indigo-pink.scss
src/material/legacy-core/theming/prebuilt/pink-bluegrey.scss
src/material/legacy-core/theming/prebuilt/purple-green.scss

Add typography and density keys to the prebuilt theming files. 
While it's probably safe to default typography to `typography.define-typography-config()`, this is a good intermediate step to enable strict theme configs internally. If it can be proven safe to add a real typography config, we can change it.

fix(material/core): use full theme config definitions to prebuilt themes

---

src/material/datepicker/calendar-header.html
src/material/datepicker/calendar-header.spec.ts
src/material/datepicker/calendar.scss
src/material/datepicker/calendar.ts
tools/public_api_guard/material/datepicker.md

fix(material/datepicker): announce the "to" when reading year range
Create period button's `aria-description` using `formatYearRangeLabel`
method. Format year range in a TTS friendly way (e.g. "2019 to 2020").
Previously, some screen readers would announce the range as "2019 2020".
Fixes #23467.

fix(material/datepicker): announce the "to" when reading year range

---

src/dev-app/dev-app/BUILD.bazel
src/dev-app/dev-app/dev-app-404.ts
src/dev-app/dev-app/dev-app-layout.html
src/dev-app/dev-app/dev-app-layout.scss
src/dev-app/dev-app/dev-app-layout.ts

Switches the dev app layout to use the MDC versions of the components and fixes a couple of visual issues.

build: switch dev app layout to use MDC

---

src/cdk/stepper/stepper.md
src/material/stepper/stepper.html
src/material/stepper/stepper.md
src/material/stepper/stepper.scss
src/material/stepper/stepper.spec.ts

We have an `aria-expanded` attribute on the `tabpanel` which is invalid. See https://w3c.github.io/aria/#aria-expanded.
Fixes #25637.

fix(material/stepper): remove invalid aria attribute

---

src/cdk/schematics/utils/project-tsconfig-paths.spec.ts

The CLI started throwing an error if a projects doesn't have a `root` property. These changes update a few of our tests that were failing because of it.

test(cdk/schematics): account for breaking change in CLI

---

src/cdk/a11y/key-manager/list-key-manager.ts
src/material/select/select.spec.ts
src/material/select/select.ts
tools/public_api_guard/cdk/a11y.md

Hello,
small PR on adding some functionality according to (https://github.com/angular/components/issues/3549) and implemented to fit the standard.
- Page-Down focuses the last element in the select
- Page-Up focus the first element in the select
- It's done in open and closed state (https://w3c.github.io/aria-practices/examples/combobox/combobox-select-only.html there it is only in closed state, but for example in Chrome a native select is working cloed and open this way)
Best regards,
Martin

feat(material/select): add page down/up button functionality

---

src/material/schematics/ng-update/migrations/legacy-components-v15/constants.ts
src/material/schematics/ng-update/migrations/legacy-components-v15/index.ts
src/material/schematics/ng-update/test-cases/v15/legacy-components-v15.spec.ts

Some of the imports from @angular/material/core (the ones related to
MatOption) need to be migrated to import from
@angular/material/legacy-core. However, the remaining symbols should
still import from @angular/material/core. This PR changes the ng update
script to separate them into separate import statements.

fix(material/schematics): split core imports in ng update

---

src/dev-app/theme.scss
src/material/core/theming/_theming.scss

Introduce a flag that can prevent colors from being copied to the top-level keys of the theme config. This can be transformed internally to prevent google3 applications from relying on the backwards compat values.

fix(material/core): add flag whether to copy color theme values

---

src/cdk/dialog/dialog-config.ts
src/material/bottom-sheet/bottom-sheet-config.ts
src/material/bottom-sheet/bottom-sheet-container.ts
src/material/bottom-sheet/bottom-sheet.spec.ts
src/material/dialog/dialog-config.ts
src/material/dialog/dialog.spec.ts
src/material/legacy-dialog/dialog.spec.ts
tools/public_api_guard/material/bottom-sheet.md
tools/public_api_guard/material/dialog.md

Fixes that the dialog and bottom sheet weren't setting `aria-modal` anymore. We had data bindings for it, but they didn't work and we hadn't noticed because host bindings aren't being type checked. This regression likely happened during the switch to the CDK dialog.
Fixes #25676.

Dialog and bottom sheet not setting aria-modal

---

src/material/legacy-tooltip/tooltip.spec.ts
src/material/tooltip/tooltip.spec.ts
src/material/tooltip/tooltip.ts
tools/public_api_guard/material/tooltip.md

After the tooltips were switched to CSS animations, a regression was introduced where the opposite animation is shown even if the tooltip didn't actually reach its target state.
These changes are an alternate take on the fix from #24652 which had to be reverted due to internal failures.
Fixes #24614.

fix(material/tooltip): animations running when timeouts haven't elapsed

---

guides/v15-mdc-migration.md

Also kept the Prettier formatting recommendations-omitting the trailing whitespace. Should be good to keep.

docs: fix double `will` in list mdc migration snippet

---

src/material/form-field/testing/error-harness.ts
src/material/form-field/testing/form-field-harness.spec.ts
src/material/form-field/testing/form-field-harness.ts
src/material/form-field/testing/public-api.ts
src/material/form-field/testing/shared.spec.ts
src/material/legacy-form-field/testing/BUILD.bazel
src/material/legacy-form-field/testing/error-harness.ts
src/material/legacy-form-field/testing/form-field-harness.spec.ts
src/material/legacy-form-field/testing/form-field-harness.ts
src/material/legacy-form-field/testing/public-api.ts
tools/public_api_guard/material/form-field-testing.md
tools/public_api_guard/material/legacy-form-field-testing.md

Add an error harness for client tests checking whether there are certain errors on the page. This is very common internally for tests checking validation. 
The harness can be retrieved directly or through the form field.
I tried to check the right inheritance structure of other harnesses - might have gotten something mixed up on the way. Would appreciate a review making sure I've got the right inheritance of things. The harness tests passed so that's a good sign.

feat(material/form-field): add error harness

---

src/material/input/input.md

The link to the `cdkTextareaAutosize` directive in the "Auto-resizing <textarea> elements" section on the overview page links to that section on the same page, have changed it to correctly point to that section within the `cdk/text-field` overview page.

docs(material/input): Fix cdkTextareaAutosize link

---

src/material/core/_core.scss
src/material/legacy-core/_core.scss

Adds an optional flag to the `core` mixin that can controls whether typography styles are emitted. This is planned to be a temporary addition before the v15 launch in order to migrate google3. Once all clients use this flag, it can be removed and the typography can be removed. For backwards compatibility, the `ng update` script will take care of external clients when they upgrade so that `mat.core()` will turn into `mat.all-component-typographies(); mat.core()`.

feat(material/core): add option to disable core typography

---

.github/CODEOWNERS
src/dev-app/BUILD.bazel
src/dev-app/dev-app/dev-app-layout.ts
src/dev-app/legacy-datepicker/BUILD.bazel
src/dev-app/legacy-datepicker/custom-header.html
src/dev-app/legacy-datepicker/custom-header.scss
src/dev-app/legacy-datepicker/datepicker-demo.html
src/dev-app/legacy-datepicker/datepicker-demo.scss
src/dev-app/legacy-datepicker/datepicker-demo.ts
src/dev-app/routes.ts
src/material/datepicker/BUILD.bazel
src/material/datepicker/_datepicker-legacy-compat.scss
src/material/datepicker/_datepicker-theme.scss
src/material/datepicker/calendar.scss
src/material/datepicker/date-range-input.scss
src/material/datepicker/date-range-input.spec.ts
src/material/datepicker/date-range-input.ts
src/material/datepicker/datepicker-actions.scss
src/material/datepicker/datepicker-actions.spec.ts
src/material/datepicker/datepicker-input.ts
src/material/datepicker/datepicker-module.ts
src/material/datepicker/datepicker-toggle.scss
src/material/datepicker/datepicker-toggle.ts
src/material/datepicker/datepicker.spec.ts
src/material/legacy-button/BUILD.bazel
src/material/legacy-button/_button-theme.scss
src/material/legacy-button/button.scss
src/material/legacy-form-field/BUILD.bazel
src/material/legacy-form-field/form-field.scss
tools/public_api_guard/material/datepicker.md

Buttons inside the datepicker popup and datepicker toggle now use the
MDC-based button implementation. They have different CSS classes and
styles, so custom style overrides may need to be updated

feat(material/datepicker): make compatible with MDC & legacy components

---

src/cdk/a11y/key-manager/list-key-manager.spec.ts
src/cdk/a11y/key-manager/list-key-manager.ts
src/cdk/listbox/listbox.ts
src/cdk/menu/menu-base.ts
src/cdk/stepper/stepper.ts
src/material/autocomplete/autocomplete.ts
src/material/chips/chip-set.ts
src/material/expansion/accordion.ts
src/material/legacy-chips/chip-list.ts
src/material/legacy-list/selection-list.ts
src/material/list/selection-list.ts
src/material/menu/menu.ts
src/material/select/select.ts
src/material/tabs/paginated-tab-header.ts
tools/public_api_guard/cdk/a11y.md

Historically we haven't needed to do any cleanup for the `ListKeyManager`, because it didn't contain any rxjs subscriptions. Over time we've accumulated more functionality which now needs to be cleaned up.
These changes introduce a `destroy` method and calls it in all the relevant places. I also removed any places where we previously had to do manual cleanup.
Fixes #25537.

fix(cdk/a11y): clean up list key manager on destroy

---

src/material/core/_core.scss
src/material/legacy-core/_core.scss

All internal clients include typography in their theme files and this can be safely removed. This assumes the `ng update` script will be updated to add `mat.all-component-typographies` before all `mat.core` calls.
The parameter must remain until all cases internally no longer pass the param as an argument
- `core()` mixin no longer provides typography styles. Applications must call component `typography` mixins to apply typography styles, or call `theme` mixins with a theme config containing typography.

feat(material/core): remove typography styles from core mixin

---

src/material/button/_button-theme-private.scss
src/material/button/button-base.ts
tools/public_api_guard/material/button.md

Fixes a bug in the Angular Material `button` component where cdk-focused, cdk-keyboard-focused, cdk-mouse-focused were not being applied upon respective focus. This is because there was no FocusManager set up with the MDC buttons like the legacy button did.
Fixes #25618

fix(material/button): cdk-focus classes not being applied

---

src/dev-app/list/list-demo.ts
src/material/list/BUILD.bazel
src/material/list/_list-item-hcm-indicator.scss
src/material/list/list-option.scss
src/material/list/list.scss

For anchor tags inside of a list, draw a circle in HCM mode to indicate the active link item. This fixes an a11y issue where active list-items had no visual indication of being active in HCM.

fix(material/list): visually indicate active links in HCM

---

src/material/core/theming/prebuilt/deeppurple-amber.scss
src/material/core/theming/prebuilt/indigo-pink.scss
src/material/core/theming/prebuilt/pink-bluegrey.scss
src/material/core/theming/prebuilt/purple-green.scss
src/material/legacy-core/theming/prebuilt/deeppurple-amber.scss
src/material/legacy-core/theming/prebuilt/indigo-pink.scss
src/material/legacy-core/theming/prebuilt/pink-bluegrey.scss
src/material/legacy-core/theming/prebuilt/purple-green.scss

Add typography hierarchy back to the prebuilt themes. 
They used to rely on `mat.core` calling `all-component-typographies`, which is equal to `all-component-themes` (with typography in the config) + `typography-hierarchy`.

fix(material/core): add typography hierarchy to prebuilt

---

src/material/tooltip/tooltip.ts
tools/public_api_guard/material/tooltip.md

We ignore `mouseleave` events that go into the tooltip which meant that some animations weren't being cancelled correctly after the fix in #25699. These changes resolve the issue by skipping all animations if the tooltip isn't fully shown yet.
Fixes #24614.

fix(material/tooltip): animation not cancelled when mouseleave goes through tooltip

---

src/material/tooltip/BUILD.bazel
src/material/tooltip/tooltip.ts

In a recent change MDC introduced a top-level reference to `window` which broke our server-side rendering check. These changes remove our dependency on MDC completely in order to fix the error.

fix(material/tooltip): resolve server-side rendering error

---

src/material/chips/chip-listbox.spec.ts
src/material/chips/chip-option.ts

When the chip listbox is in single selection mode, it needs to remove `aria-selected` from the selected option and move it to the newly-selected one. The listbox was doing this already, but change detection wasn't being triggered which meant that the DOM was out of date.

fix(material/chips): aria-selected not reflecting selection state

---

guides/theming.md

In theming guide the mat.get-color-from-palette is shown with a number identifier in quotes, unlike the theming-your-components guide which shows it without quotes.
Fixes #25598

docs(material/theming): fix typo in theming guide

---

guides/typography.md

`mat.core` no longer emits typography styles - users should be putting their typography in the theme config and allowing `theme` mixins to emit the correct styles

docs(material/core): update typography guide

---

src/material/schematics/ng-generate/mdc-migration/rules/tree-traversal.spec.ts
src/material/schematics/ng-generate/mdc-migration/rules/tree-traversal.ts

Fixes that the MDC migration schematic was always adding new attributes, instead of replacing the values of the ones that are already there.

fix(material/schematics): replace pre-existing attribute values

---

CHANGELOG.md

docs: release notes for the v14.2.4 release

---

integration/mdc-migration/golden/src/broken.css
integration/mdc-migration/golden/src/dont-migrate-me.css.skip
integration/mdc-migration/sample-project/src/broken.css
integration/mdc-migration/sample-project/src/dont-migrate-me.css.skip
src/cdk/schematics/ng-update/find-stylesheets.ts
src/material/schematics/ng-generate/mdc-migration/BUILD.bazel
src/material/schematics/ng-generate/mdc-migration/rules/theming-styles.ts
src/material/schematics/ng-generate/mdc-migration/rules/ts-migration/runtime-migration.ts
src/material/schematics/ng-update/migrations/legacy-components-v15/index.ts

also don't treat files like something.css.map as a CSS file.

fix(material/schematics): gracefully skip broken css files

---

src/cdk/drag-drop/drag-ref.ts

Fixes a bug where native event was always an empty object because it was not passed to the container drop function and the default `{}` object was always used.

fix(cdk/drag-drop): native event not passed as parameter to drop container

---

src/material/button/testing/button-harness-filters.ts
src/material/button/testing/button-harness.ts
src/material/button/testing/shared.spec.ts
src/material/legacy-button/testing/button-harness.ts
src/material/legacy-button/testing/public-api.ts
tools/public_api_guard/material/button-testing.md
tools/public_api_guard/material/legacy-button-testing.md

Adds the ability to get the variant of a button harness and to filter by it.
Fixes #25755.

feat(material/button): add variant to button harness

---

src/material/chips/chip-listbox.spec.ts
src/material/chips/chip-option.spec.ts
src/material/chips/chip-option.ts

For chip-listbox, set `aria-selected="false"` on deselected options that are selectable. Conforms with [WAI ARIA Listbox authoring practices guide]( https://www.w3.org/WAI/ARIA/apg/patterns/listbox/), which says to always include aria-selected attribute on options that are selectable. Fix issue where voiceover reads every option as "selected" (#25736).
Fix #25736

fix(material/chips): don't remove aria-selected from deselected options

---

src/components-examples/material/badge/badge-overview/badge-overview-example.css
src/components-examples/material/badge/badge-overview/badge-overview-example.html
src/components-examples/material/badge/badge-overview/badge-overview-example.ts

The badge docs were saying that badges might not work on inline elements while the example was still using inline elements itself. These changes update the example to use `div` elements instead.
Fixes #25751.

docs(material/badge): don't use inline elements in badge demo

---

src/cdk/schematics/update-tool/component-resource-collector.ts
src/material/schematics/ng-update/migrations/hammer-gestures-v9/hammer-gestures-migration.ts

Cleans up some workarounds that were put in place to support version of TypeScript earlier than 4.8.

refactor: remove workaround for TS versions earlier than 4.8

---

src/material/icon/icon.spec.ts
src/material/icon/icon.ts

In #24578 we added the ability to set font icons using the `fontIcon` input, however it was never forwarded to the `fontIcon` attribute which means using a data binding won't work.
Fixes #25759.

fix(material/icon): forward fontIcon attribute to element

---

src/material/legacy-chips/chip-list.spec.ts

Fixes that we had some tests where we were testing user selection of a chip, but the chip wasn't set as selectable.
Setting this as a P2, because it's blocking https://github.com/angular/angular/pull/47576.

test(material/legacy-chips): fix selectable chips tests

---

src/material/checkbox/checkbox.scss

Fixes that disabled checkboxes aren't distinguishable from enabled ones in high contrast mode. I also fixed an issue where the checkmark wasn't visible, but I suspect that it's only a problem when emulating on a Chromium browser.

fix(material/checkbox): disabled state not distinguishable in high contrast mode

---

src/material/core/mdc-helpers/_mdc-helpers.scss
src/material/core/typography/_all-typography.scss

The `define-typography-config` function was set up so that if a level doesn't have a `font-family`, it would pick up the one that was passed into the function. The problem is that after we switched the typography over to MDC, we started using the `typography-config-level-from-mdc` function which provides a default `font-family` which meant that the default passed into `define-typography-config` was being ignored.
These changes add some logic that allows us to take the default font family, if it is specified.
Fixes #25780.

fix(material/core): default font family not picked up in define-typography-config

---

src/material/datepicker/datepicker-intl.ts
tools/public_api_guard/material/datepicker.md

Remove two unused i18n strings from datepicker. Remove `startDateLabel` and `endDateLabel`.
DEPRECATED
* startDateLabel is deprecated because it is not used
* endDateLabel is deprecated because it is not used

feat(material/datepicker): deprecate unused i18n string

---

src/material/slide-toggle/_slide-toggle-theme.scss

Note: the disabled state still isn't 100% right. There seems to be some opacity interaction going on that prevents matching the spec perfectly.

fix(material/slide-toggle): align colors with spec

---

CHANGELOG.md

docs: release notes for the v14.2.5 release

---

CHANGELOG.md
package.json

Also this PR cherry-picks the changelog for v15.0.0-next.5 into the main branch so that the changelog is up to date.

Update next branch to reflect new release-train "v15.1.0-next.0".

---

src/material/chips/chip-icons.ts

Removes the `@docs-private` tag from the chip avatar and trailing icon since they are public APIs. Internally the tag gets transformed into something which implies that they are private.

docs(material/chips): remove docs-private from avatar and trailing icon

---

src/dev-app/chips/chips-demo.html
src/material/chips/chip-action.ts
src/material/chips/chip-listbox.ts
src/material/chips/chip-option.html
src/material/chips/chip-option.ts
src/material/chips/chip-set.ts
tools/public_api_guard/material/chips.md

allow focusing to disabled listbox options

fix(material/chip): allow focusing to disabled listbox options

---

WORKSPACE
package.json
yarn.lock

We were a few minor versions behind on Sass which include some breaking changes. These changes update us to the latest version so that we can sure that we won't be broken.

build: update to the latest version of Sass

---

src/material/legacy-menu/menu.spec.ts
src/material/menu/menu.spec.ts
src/material/menu/menu.ts

A while ago we added an `NgZone.onStable` wrapper around the logic that moves focus in `MatMenu.focusFirstItem` in order to work around an issue with VoiceOver. Since focus is now delayed, calling `focusFirstItem` in quick succession with different origins may not work as expected.
These changes unsubscribe from the previous `onStable` callback if a new one comes in before it has finished.
Fixes #25658.

fix(material/menu): custom origin in focusFirstItem not respected on open

---

src/cdk/a11y/key-manager/list-key-manager.spec.ts
src/cdk/a11y/key-manager/list-key-manager.ts
src/material/legacy-select/select.spec.ts
src/material/select/select.spec.ts
src/material/select/select.ts
tools/public_api_guard/cdk/a11y.md

Fixes that the select would assign the value triggered by the typeahead even if the select doesn't have focus anymore.
Fixes #25452.

fix(material/select): don't assign typeahead value after blur

---

src/cdk/listbox/listbox.ts
src/cdk/menu/context-menu-trigger.ts
src/cdk/menu/menu-base.ts
src/cdk/menu/menu-item.ts
src/cdk/menu/menu-trigger.ts
src/cdk/menu/menu.ts
src/material/datepicker/date-range-input-parts.ts
src/material/legacy-input/input.ts

Cleans up the usages of the deprecated signature of the `inject` function that were passing in `InjectFlags` instead of an object literal.

refactor(multiple): remove usages of the deprecated signature of inject

---

src/material/schematics/ng-update/migrations/hammer-gestures-v9/hammer-gestures-migration.ts

Replaces a call to a deprecated function that was logging a warning.

refactor(material/schematics): remove usage of deprecated function

---

src/material/slide-toggle/slide-toggle.scss

Fixes that the animations of the slide toggle weren't disabled when using the `NoopAnimationsModule`.

fix(material/slide-toggle): animations not disabled with NoopAnimationsModule

---

src/cdk/listbox/listbox.spec.ts

The `compileComponents` calls don't need to be `await`-ed unless the component has an external template or stylesheet. These changes remove all of the async/await, as well as the `waitForAsync` wrappers since they're likely the source of some of the deprecation warnings that are being logged.

test(cdk/listbox): remove unnecessary async from tests

---

src/material/tabs/tab-header.html

Fixes that there was a typo on the disabled class for the "Next" button in the tab header.

fix(material/tabs): wrong disabled class on tab pagination button

---

src/material/schematics/ng-generate/address-form/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template
src/material/schematics/ng-generate/address-form/index.spec.ts
src/material/schematics/ng-generate/address-form/index.ts
src/material/schematics/ng-generate/dashboard/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template
src/material/schematics/ng-generate/dashboard/index.spec.ts
src/material/schematics/ng-generate/dashboard/index.ts
src/material/schematics/ng-generate/navigation/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template
src/material/schematics/ng-generate/navigation/index.spec.ts
src/material/schematics/ng-generate/navigation/index.ts
src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__-datasource.ts.template
src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template
src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
src/material/schematics/ng-generate/table/index.spec.ts
src/material/schematics/ng-generate/table/index.ts
src/material/schematics/ng-generate/tree/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template
src/material/schematics/ng-generate/tree/index.spec.ts
src/material/schematics/ng-generate/tree/index.ts

Fixes that the various `ng generate` schematics were based on top of the legacy components.

fix(material/schematics): switch away from legacy components

---

src/material/datepicker/datepicker-base.ts
tools/public_api_guard/material/datepicker.md

Fixes that if the user triggers a closing sequence while the datepicker isn't finished opening, we end up triggering a "changed after checked" error.
Fixes #25837.

fix(material/datepicker): changed after checked error during overlapping open/close sequence

---

guides/v15-mdc-migration.md
src/dev-app/slide-toggle/slide-toggle-demo.html
src/dev-app/slide-toggle/slide-toggle-demo.ts
src/material/slide-toggle/slide-toggle.md

Update migration guide for MDC Slide Toggle to give more detail on form validation. Remove form validation from slide-toggle example as it does not seem to be appropriate for switch role. Update slide toggle overview documentation to reflect changes for the MDC-based slide toggle.

docs(material/slide-toggle): update changes from legacy

---

src/material/legacy-radio/BUILD.bazel
src/material/legacy-radio/radio.spec.ts
src/material/radio/BUILD.bazel
src/material/radio/radio.spec.ts
src/material/radio/radio.ts

Fixes that radio buttons weren't being preselected correctly when they have an `ngIf` and a static `value`. It appears that the issue was because we were subscribing to the `UniqueSelectionDispatcher` before the name of the radio button is assigned.
Fixes #25831.

fix(material/radio): radio not preselected with static value and an ngIf

---

src/cdk/listbox/listbox.spec.ts
src/cdk/listbox/listbox.ts
tools/public_api_guard/cdk/listbox.md

Currently the CDK listbox is providing itself as a validator so that it can validate that programmatically-assigned values are valid. This is incorrect, because validators are meant to check user-assigned values and the checks that are currently being performed can't happen purely through the UI.
These changes remove the `Validator` implementation and replace the checks with runtime errors.

fix(cdk/listbox): remove incorrect usage of validator

---

src/cdk/listbox/listbox.spec.ts
src/cdk/listbox/listbox.ts

`CdkOption` can be placed on any element which means that it could cause a `form` to be submitted if it's placed on a `button`. These changes add a `preventDefault` to avoid the submission.

fix(cdk/listbox): prevent form submission on click

---

integration/ng-update-v13/src/test.ts
integration/yarn-pnp-compat/angular.json
integration/yarn-pnp-compat/package.json
integration/yarn-pnp-compat/src/test.ts
integration/yarn-pnp-compat/yarn.lock
src/material/schematics/ng-add/index.spec.ts
src/material/schematics/ng-add/theming/theming.ts
yarn.lock

The Angular CLI supports resolving node modules without the need of specifying `node_modules` directory. This also needed to add support for Yarn PNP which doesn't create a `node_modules` directory.
Closes #25242

fix(material/schematics): remove `node_modules` prefix from prebuilt theme
