src/material/datepicker/datepicker-toggle.scss

We support the case where the form field is disabled, but the datepicker isn't. Currently this is broken, because MDC sets `pointer-events: none` on the entire form field when it is disabled. These changes add `pointer-events: auto` only on the toggle to enable clicking.

fix(material/datepicker): unable to click datepicker toggle when form field is disabled

---

CHANGELOG.md

docs: release notes for the v14.2.6 release

---

src/material/list/selection-list.spec.ts
src/material/list/selection-list.ts

When entire list is disabled, avoid adding list options to the tab order in the following situations:
- focusin event is triggered on an option. This can happen when the end user clicks on a list option.
- ngOnInit happens when list is disabled
- updating selection state
When list is disabled tabindex of every option should always be -1. Tabindex was set to 0 mainly because `_resetActionOption` only considered when list options where disabled, but didn't consider when the list itself is disabled.
Fix issues by setting tabindex to -1 when disabled and making `_handleFocusin` a noop when disabled.

fix(material/list): fix tabindex="-1" not being maintained when disabled

---

src/cdk/listbox/listbox.spec.ts
src/cdk/listbox/listbox.ts

In #25856 the check that verifies the validity of the form control value was moved into `writeValue`. This works as expected for assignments after initialization, but it throws an error incorrectly if there is a preselected value, because `writeValue` will be called before the options are available.
These changes resolve the issue by checking that the options have been initialized before throwing the error.

fix(cdk/listbox): incorrectly validating preselected value

---

src/material/chips/_chips-theme.scss
src/material/chips/chip.scss

Reworks the chips to use the new theming API from MDC.

refactor(material/chips): switch to new theming API

---

src/cdk/dialog/dialog.ts
src/material/datepicker/date-range-input-parts.ts

Removes all of the remaining usages of the deprecated `InjectFlags` symbol.

refactor(multiple): remove final usages of InjectFlags

---

src/cdk/menu/context-menu-trigger.ts
src/cdk/menu/menu-aim.ts
src/cdk/menu/menu-bar.ts
src/cdk/menu/menu-group.ts
src/cdk/menu/menu-item-checkbox.ts
src/cdk/menu/menu-item-radio.ts
src/cdk/menu/menu-item.ts
src/cdk/menu/menu-module.ts
src/cdk/menu/menu-trigger.ts
src/cdk/menu/menu.ts
tools/public_api_guard/cdk/menu.md

Converts all of the `@angular/cdk/menu` directives to `standalone` so that they can be used as host directives.
cc @jelbourn

refactor(cdk/menu): convert all directives to standalone

---

src/cdk/overlay/overlay.ts

Switches the `Overlay` injectable to be provided at the root.

fix(cdk/overlay): provide Overlay in root

---

CHANGELOG.md

docs: release notes for the v15.0.0-rc.1 release

---

src/components-examples/material/autocomplete/autocomplete-overview/autocomplete-overview-example.html

An `alt` attribute is required for an upcoming extended diagnostic, and from my understanding is desirable over `aria-hidden` since it maintains `role="img"` while also indicating that the image is decorative.
See CI failures from: https://app.circleci.com/pipelines/github/angular/angular/52667/workflows/3d58122f-0257-4b79-9ab9-90475590a3f2/jobs/1249004

refactor: replaces `aria-hidden` with `alt=""`

---

src/material/core/density/private/_all-density.scss
src/material/core/theming/_all-theme.scss
src/material/core/theming/tests/test-css-variables-theme.scss
src/material/core/typography/_all-typography.scss
src/material/legacy-core/density/private/_all-density.scss
src/material/legacy-core/theming/_all-theme.scss
src/material/legacy-core/typography/_all-typography.scss

Some mixins were introduced during the MDC migration to make it easier to distinguish which components were migrated and which ones were pending. These changes remove the mixins now that the migration is finished.

refactor(material/core): clean up temporary mixins from MDC migration

---

src/material/chips/chip-option.ts

For mat-chip-listbox, use the checkmark component for single-selection. Fixes issue where selected state is communicated visually only using color (#25886).

fix(material/chips): use checkmark graphic for single-selection

---

src/material/tabs/tab-nav-bar/tab-nav-bar.ts

Moves the `_MatTabNavBase` class a bit further up in the file to try and avoid a reference error in some test setups.
Fixes #25918.

fix(material/tabs): avoid reference error

---

src/material/checkbox/_checkbox-private.scss
src/material/radio/_radio-theme.scss

The global `map-get` function is deprecated. We should be using the namespaced `map.get` instead.

refactor(multiple): clean up map-get usages

---

src/material/stepper/stepper.scss

Fixes an issue where the content of a stepper that is nested inside of a `<mat-tab-group>` becomes invisible after the first navigation. This appears to be some sort of a bug where the `visibility: inherit` that we have on the stepper doesn't get recalculated so it stays `hidden`.
Fixes #25925.

fix(material/stepper): content not visibile on first navigation when nested in tabs

---

src/material-experimental/mdc-tabs/tab-header.scss
src/material/stepper/step-header.scss

* fix(material/stepper): add HCM disabled styles
This adds disabled styles for stepper header in high contrast mode
* fix(material/tabs): add HCM disabled styles
This adds disabled styles for tab labels in high contrast mode

Add HCM disabled styles for stepper and tabs (#25393)

---

src/cdk/scrolling/virtual-scroll-viewport.spec.ts
src/cdk/scrolling/virtual-scroll-viewport.ts

In an earlier change we started providing the `CdkVirtualScrollable` through the `VIRTUAL_SCROLLABLE` token, but the change wasn't reflected in the `CdkVirtualScrollViewport` which was causing an error.
Fixes #25917.

fix(cdk/scrolling): error when querying for CdkVirtualScrollViewport as CdkScrollable

---

.github/CODEOWNERS

Add Zach (zarend) to code owners for chips.

build: add Zach to chips codeowners

---

guides/typography.md

Updates the typography guide to be based on the 2018 spec terminology.

docs: update typography guide to new terminology

---

src/cdk/menu/menu-item.ts
src/cdk/menu/menu-trigger-base.ts
src/cdk/menu/menu-trigger.spec.ts
src/cdk/menu/menu-trigger.ts
tools/public_api_guard/cdk/menu.md

This PR fixes issue #25782 and allows to set `[cdkMenuTriggerFor]='null'`

feat(cdk/menu): Allow setting cdkMenuTriggerFor null

---

src/material/chips/chip-option.html
src/material/chips/chip-option.ts
tools/public_api_guard/material/chips.md

Fixes that chips that were selected programmatically, but were set as `selectable="false"` weren't showing the checkmark as intended in https://github.com/angular/components/pull/25890. Also removes some of the logic now that we can assume that the checkmark will always be present.

fix(material/chips): show checkmark for selected non-selectable chips

---

CHANGELOG.md

docs: release notes for the v14.2.7 release

---

CHANGELOG.md

docs: release notes for the v15.0.0-rc.2 release

---

src/material/schematics/ng-generate/mdc-migration/rules/components/slider/slider-template.spec.ts
src/material/schematics/ng-generate/mdc-migration/rules/components/slider/slider-template.ts

* remove tickInterval, valueText, defaultColor, defaultTabIndex, onTouched, and displayValue for slider template migrations

fix(material/schematics): add handling for several api changes

---

src/material/schematics/ng-generate/mdc-migration/rules/components/typography-config.spec.ts
src/material/schematics/ng-generate/mdc-migration/rules/components/typography-hierarchy/constants.ts
src/material/schematics/ng-generate/mdc-migration/rules/theming-styles.ts

Expands the logic in the MDC theming migration to be able to discern both keys and values of named Sass function parameters. The new logic is used to correctly migrate users away from the `input` typography level which doesn't have an equivalent in the new system.

fix(material/schematics): handle input level in typography migration

---

integration/mdc-migration/golden/src/app/components/chips/chips.component.html
src/material/schematics/ng-generate/mdc-migration/rules/components/chips/chips-template.spec.ts
src/material/schematics/ng-generate/mdc-migration/rules/tree-traversal.spec.ts
src/material/schematics/ng-generate/mdc-migration/rules/tree-traversal.ts

The MDC migration wasn't traversing into template elements which meant that it wouldn't migrate elements with an `*ngIf` or an `*ngFor` on them.
Fixes #25824.

fix(material/schematics): not migrating elements with template directives

---

src/material/slider/slider.scss
src/material/slider/slider.ts

* fixes an issue where the slider track active would flicker when switching between thumbs on a range slider

fix(material/slider): fix track animation

---

src/material/schematics/ng-generate/mdc-migration/rules/tree-traversal.ts

The `visitElements` function was calling `reverse` on the node's `children` which reverses it in place. We shouldn't be mutating the AST just to traverse it in reverse order.
These changes switch to using a reverse loop instead.

fix(material/schematics): avoid mutating the AST when traversing

---

src/components-examples/material/list/index.ts
src/components-examples/material/list/list-variants/list-variants-example.css
src/components-examples/material/list/list-variants/list-variants-example.html
src/components-examples/material/list/list-variants/list-variants-example.ts

@mmalerba @crisbeto I thought we may want to show the different variants of lists since that is
very unclear from the docs right now, especially showing some cases of the API.
The example is more of a "documentation as code", show-casing some ways of rendering stuff
and the given markup. Let me know what you think
Note: Notice how there is an additional space when a line is in unscoped content and not part of e.g. a `<span>`. I wanted to keep this though as it shows that the last line doesn't necessarily need to be part of a `matListItemLine`/Title and was hoping this would make it more clear. Happy to remove these though.

docs: add example for variants of mdc list

---

packages.bzl

Before being able to cut v15 stable, the peer dependency needs to be updates so that Angular
framework v15 stable can be used.

build: update peer dependency to angular framework

---

src/cdk/a11y/BUILD.bazel
src/cdk/a11y/live-announcer/live-announcer.spec.ts
src/cdk/a11y/live-announcer/live-announcer.ts

When an `aria-modal="true"` element is present, some browsers exclude all the content outside of them from the a11y tree which breaks the `LiveAnnouncer`.
These changes add some logic to set an `aria-owns` on the modals so that the announcement is made.
Fixes #22733.

fix(cdk/a11y): live announcer not working with aria-modal element

---

src/material/datepicker/date-range-input-parts.ts
src/material/datepicker/date-range-input.html
src/material/datepicker/date-range-input.scss
src/material/datepicker/date-range-input.ts
tools/public_api_guard/material/datepicker.md

Currently we use two different approaches to align the start and end parts of the date range. The start is absolutely-positioned while the end is `relative` which ends up misaligning on some browsers and typography configurations.
These changes make both positioned absolutely since some browsers don't handle `line-height` on inputs reliably.
Fixes #25955.

fix(material/datepicker): date range inputs not aligning in some cases

---

src/material/chips/chip.scss

Fixes issue where state layer interfers with color of the text. Give the text label a higher z-index than the focus overlay.

fix(material/chips): fix state layer interferring with text color

---

src/material/slider/slider.ts

* Fixes an issue where the value indicator ui is not initialized when toggling discrete on

fix(material/slider): update VI when toggling discrete

---

src/dev-app/autocomplete/autocomplete-demo.html
src/dev-app/autocomplete/autocomplete-demo.ts
src/material/autocomplete/autocomplete-trigger.ts
src/material/autocomplete/autocomplete.spec.ts
src/material/autocomplete/autocomplete.ts
tools/public_api_guard/material/autocomplete.md

Apply the theme of the autocomplete's parent form field to its panel. Fix issue where theme color only applies to the input, and does not affect the panel.

fix(material/autocomplete): apply theme of parent form field to panel

---

src/material/list/list.scss

MDC applies `pointer-events: none` around different sections of the list item which breaks interactivity. As evidenced by the dev app demos, we support interactive content in them so these changes reset the `pointer-events` back to `auto`.
Fixes #26010.

fix(material/list): pointer events disabled around content

---

src/components-examples/cdk/listbox/cdk-listbox-disabled/cdk-listbox-disabled-example.html

docs(cdk/listbox): fix a11y of example

---

src/material/list/list.scss

Fixes that the overlay we use for focus/hover events was blocking users from interacting with the list item content.
Fixes #26011.

fix(material/list): hover indication blocking interactions

---

src/components-examples/material/chips/chips-input/chips-input-example.html
src/components-examples/material/chips/chips-input/chips-input-example.ts
src/material/chips/chip-option.html
src/material/chips/chip-option.spec.ts
src/material/chips/chip-option.ts
src/material/chips/chip-row.html
src/material/chips/chip-row.spec.ts
src/material/chips/chip-row.ts
src/material/chips/chip.ts
tools/public_api_guard/material/chips.md

Add support for aria-description on mat-chip, mat-chip-option and mat-chip-row. mat-chip-option and mat-chip-row put aria-desciprtion on the same element that already has the aria-label.
aria-description is needed for when developers need to provide more information that in the aria-label. This is especially needed for chip-row when [editable]="true". That's because it gives a way to communicate to screen reader users how to begin editing a chip.

fix(material/chips): add support for aria-description

---

src/material/core/style/_elevation.scss

During the switch to MDC the opacity parameter to the `elevation` mixin was removed which is a breaking change. It also isn't possible to achieve the same result by providing an `rgba` color, because MDC changes the color's opacity.
Fixes #26004.

fix(material/core): reintroduce opacity in elevation mixin

---

src/material/schematics/ng-generate/mdc-migration/schema.json

by adding missing `"multiselect": true` in the x-prompt for the `components` property

fix(material/schematics): ensure mdc migration compatibility with nx

---

src/dev-app/list/list-demo.html
src/dev-app/list/list-demo.ts
src/material/legacy-list/selection-list.ts
src/material/list/BUILD.bazel
src/material/list/_list-option-theme.scss
src/material/list/list-item-sections.ts
src/material/list/list-option-types.ts
src/material/list/list-option.html
src/material/list/list-option.scss
src/material/list/list-option.ts
src/material/list/public-api.ts
src/material/list/selection-list.spec.ts
src/material/list/testing/list-harness.spec.ts
src/material/list/testing/selection-list-harness.ts
src/material/radio/BUILD.bazel
src/material/radio/_radio-private.scss
src/material/radio/_radio-theme.scss
src/material/radio/radio.scss
tools/public_api_guard/material/list-testing.md
tools/public_api_guard/material/list.md

[fix(material/list): add radio toggles](https://github.com/angular/components/pull/25933/commits/884e6b5ded0e3e7c44bd16f4c138fc31b366304c) 
Add radio toggles for single selection. Fix a11y issue where selected
state is visually communicated with color alone.
Rename `checkboxPosition` Input to `togglePosition` and deprecate
`checkboxPosition`. `togglePosition` configures the position of both the
radio and checkbox indicators. `checkboxPosition` also configures the
position of both.
Summary of API and behavior changes:
- MDC List displays radio indicators for single-selection
- rename `checkboxPosition` Input to `togglePosition`
- rename `type MatListOptionCheckboxPosition` to `type
MatListOptionTogglePosition`
DEPRECTED:
* `checkboxPosition` is deprecated because `togglePosition` replaces …

fix(material/list): add radio toggles

---

src/cdk/menu/menu-item.spec.ts
src/cdk/menu/menu-item.ts
src/cdk/menu/menu-trigger.spec.ts
src/cdk/menu/menu-trigger.ts

Fixes that the CDK menu wasn't calling `preventDefault` on the enter key presses which caused it to immediately close, because it would allow the click handler to fire as well.
Fixes #26033.

fix(cdk/menu): prevent default selection key actions

---

guides/v15-mdc-migration.md

Fixes the following incorrect information in the migration guide:
* The density was being specified in pixels which is incorrect. It doesn't have a unit.
* There is no -5 density.

docs: address incorrect density in migration guide

---

guides/theming.md

Fix broken link to anchor 'customizing-density'.

docs(material/theming): fix customizing-density link

---

src/material/core/ripple/ripple-renderer.ts

Fixes that the ripples weren't being removed if the ripple container has `display: none` on it. This is a bit of an edge case that I hit while working on a different task, but it's easy to guard against since we have all the information to know when it happens.

fix(material/core): ripples not being removed if container is hidden

---

src/material/list/list-base.ts
src/material/list/list.scss
src/material/list/list.spec.ts
src/material/list/list.ts
tools/public_api_guard/material/list.md

In the MDC-based list having a `MatListItem` outside of a list throws a DI error, whereas in the legacy version it didn't. These changes make injecting the list optional and try to gracefully handle the absence of a list.
I've also removed the `mat-mdc-list-non-interactive` class since the same can be achieved without it.
Fixes #26013.

fix(material/list): allow mat-list-item outside list

---

src/material/input/input.spec.ts
src/material/input/input.ts

Fixes that the form field wasn't visually disabled if the consumer disables it using `emitEvents: false`.
Fixes #26057.

fix(material/form-field): not visually disabled if form control is disabled without emitting an event

---

src/dev-app/dev-app/dev-app-layout.scss
src/material/toolbar/toolbar.scss

Fixes that MDC-based buttons placed inside a toolbar weren't inheriting its text color like the non-MDC buttons.
Fixes #26063.

fix(material/toolbar): inherit toolbar color in flat buttons

---

src/material/button/_button-base.scss
src/material/checkbox/checkbox.scss
src/material/chips/chip.scss
src/material/core/option/option.scss
src/material/list/list.scss
src/material/radio/radio.scss
src/material/slide-toggle/slide-toggle.scss
src/material/tabs/_tabs-common.scss

Removes the touchscreen device tap highlights from the various components where we have similar indication.
Fixes #26068.

fix(multiple): remove touch tap highlights

---

src/material/legacy-menu/menu.spec.ts
src/material/menu/menu-trigger.ts
src/material/menu/menu.spec.ts

In the context of a submenu trigger it is useful for a screen reader user to
know whether a submenu is open or closed. By specifying the
`aria-expanded` attribute as either true or false it provides an
additional "collapsed" announcement to the user informing them of the
state of the menu trigger when closed.

refactor(material/menu): explicitly set aria-expanded to true/false

---

src/cdk/menu/context-menu-trigger.ts
src/cdk/menu/menu-trigger.ts

Fixes that the CDK menu wasn't closing on outside clicks when the trigger is inside the shadow DOM. The problem is that reading the `Event.target` doesn't work as expected in the shadow DOM and we have to go through a helper.
Fixes #26107.

fix(cdk/menu): not closing when inside shadow DOM

---

src/material/core/option/option.ts
src/material/legacy-select/select.spec.ts
src/material/select/select.spec.ts
src/material/select/select.ts

Fixes a "changed after checked" error that is thrown if the label of a selected option changes dynamically.
This is alternate approach to #14797 which was tricky to land, because it introduced an extra timeout.
Fixes #14793.
**Note:** I'm bumping this to a P2, because the related issue has been getting activity consistently for a long time now.

fix(material/select): changed after checked error if option label changes

---

src/material/slide-toggle/slide-toggle.ts

Fixes that the focus indication wasn't showing up when the slide toggle is placed inside of an `OnPush` component.

fix(material/slide-toggle): focus indication not showing inside OnPush parent

---

src/material/chips/chip-grid.ts
src/material/chips/chip-input.ts
src/material/chips/chip-set.ts
tools/public_api_guard/material/chips.md

* Fixes that the chip grid was triggering a bunch of change detections on initialization through a `setTimeout` inside `setDescribedByIds`.
* Replaces most of the remaining timeouts in the chips with `Promise.resolve`.
Fixes #25325.

perf(material/chips): reduce amount of macro tasks

---

src/material/form-field/_form-field-density.scss

Fixes that one of the form field density selectors was targeting `.mat-mdc-form-field` which prevents users from setting density classes directly on the form field.
Fixes #26062.

fix(material/form-field): change selector to allow density class on form field

---

src/material/autocomplete/autocomplete-trigger.ts
tools/public_api_guard/material/autocomplete.md

In autocomplete-trigger.ts, add `| null` to the typing of optionally injected properties. This improves code health because the compiler can detect possible type errors with `null`.

refactor(material/autocomplete): declare injected properties as nullable

---

src/cdk/keycodes/modifiers.ts
src/material/datepicker/datepicker-base.ts
src/material/datepicker/datepicker-input-base.ts
src/material/datepicker/datepicker.spec.ts
tools/public_api_guard/cdk/keycodes.md

Fixes a bug in the Angular Material `datepicker` component where the datepicker should open/close only on alt+down and alt+up respectively but using shift + ctrl + alt + down or ctrl + alt + down the datepicker was opening, and same happens for closing the date picker added a condition to check if ctrl, shift or meta keys are present and if it is present restricting datepicker to not to open/close.
Fixes #25868

fix(material/datepicker): fix date picker shortcuts

---

packages.bzl

Fix typo in a code comment in packages.bzl. Replace "it's" with "its".

docs(build): fix typo in code comment

---

src/material/core/option/option.html
src/material/core/option/option.scss
src/material/core/option/option.ts
src/material/legacy-core/option/option.html
tools/public_api_guard/material/core.md

Fixes that icons projected inside an MDC-based `mat-option` weren't centered and didn't have the correct margin like the non-MDC version.
Fixes #26024.

fix(material/core): icons not aligned inside mat-option

---

src/components-examples/material/form-field/form-field-theming/form-field-theming-example.html
src/components-examples/material/form-field/form-field-theming/form-field-theming-example.ts
src/material/form-field/form-field.md

We don't support having the form field inherit the font size with the MDC version. These changes remove the example from the docs.
Fixes #26091.

docs(material/form-field): remove font size example

---

src/material/button/icon-button.scss

Fixes that SVG icons sometimes weren't centered in an icon button.
Fixes #26126.

fix(material/button): ensure svg icon is centered

---

src/material/core/ripple/ripple-event-manager.ts
src/material/core/ripple/ripple-renderer.ts
tools/public_api_guard/material/core.md

Ripples are used a lot throughout our components which makes them very performance-sensitive. These changes aim to reduce the cost of setting them up by delegating the `mousedown` and `touchstart` handlers. This shaved off 15 to 20 percent of the creation cost from buttons.
I decided to only delegate the `mousedown` and `touchstart` events, rather than all ripple-related events, because ripples listen to some very frequent events like `mouseleave` and the cost of matching events to their targets would've offset any gains we would've gotten from delegating them. The code is written in a way where we can easily delegate them later if we change our minds.

perf(material/core): delegate trigger events

---

src/material/list/selection-list.ts
tools/public_api_guard/material/list.md

In #21974 the `MatSelectionChange.option` property was removed, but we accidentally re-added it during the MDC switch. These changes re-remove the property.
Fixes #26005.

fix(material/list): remove previously removed API

---

src/material/chips/chip-action.ts

We were always setting the `mdc-evolution-chip__action--presentational` class on the primary chip action to avoid some very specific `:hover` styles from MDC, but the side effect was the correct cursor wasn't being applied to the action anymore.
With the new token-based API we don't generate the `:hover` styles at all so we can re-add the class and fix the cursor.
Fixes #26050.

fix(material/chips): set correct cursor on interactive chips

---

src/cdk/drag-drop/directives/drag-handle.ts
src/cdk/drag-drop/directives/drag-placeholder.ts
src/cdk/drag-drop/directives/drag-preview.ts
src/cdk/drag-drop/directives/drag.ts
src/cdk/drag-drop/directives/drop-list-group.ts
src/cdk/drag-drop/directives/drop-list.ts
src/cdk/drag-drop/drag-drop-module.ts
tools/public_api_guard/cdk/drag-drop.md

This work converts all of the `@angular/cdk/drag-drop` directives to `standalone`. With these changes, `drag-drop` directives can be used as host directives.

refactor(cdk/drag-drop): convert all directives to standalone

---

src/cdk/listbox/listbox.spec.ts
src/cdk/listbox/listbox.ts
tools/public_api_guard/cdk/listbox.md

Fixes that the listbox was setting the initial focus on a deselected option when a selected one was available.
**Note:** this fix is a bit more convoluted than it needs to be. E.g. ideally we would just focus the selected option when the listbox receives focus. We can't do that, because the listbox supports two different focus management modes: focus and `aria-activedescendant`. The former doesn't allow tabbing to the listbox.
Fixes #25833.

fix(cdk/listbox): set initial focus to selected option

---

src/components-examples/material/tabs/tab-group-theme/tab-group-theme-example.html
src/material/tabs/_tabs-common.scss
src/material/tabs/_tabs-theme.scss
src/material/tabs/tab-group.scss
src/material/tabs/tab-group.ts
src/material/tabs/tab-nav-bar/tab-nav-bar.scss
src/material/tabs/tab-nav-bar/tab-nav-bar.ts

We were generating more than 15kb of selectors to support the background colors for tabs. These changes move the selectors into the base styles and use variables to set the colors.

perf(material/tabs): reduce amount of CSS generated for background color

---

src/material/tabs/_tabs-common.scss

Fixes that icons projected into a tab were centered anymore.
Relates to https://github.com/angular/components/issues/26024#issuecomment-1320335400.

fix(material/tabs): icons not centered inside tab

---

src/material/tabs/_tabs-common.scss

Fixes an internal regression after #26186 which broke the ability to have something like a primary background and an accent foreground.

fix(material/tabs): allow both foreground and background colors to be set

---

src/material/chips/chip-option.html
src/material/chips/chip-option.spec.ts
src/material/chips/chip-row.html
src/material/chips/chip-row.spec.ts
src/material/chips/chip.ts
tools/public_api_guard/material/chips.md

For the `ariaDescription` Input, implement with aria-describedby rather than aria-description. aria-description is still in W3C Editor's Draft for ARIA 1.3.

fix(material/chips): implement ariaDescription with aria-describedby

---

src/material/schematics/ng-generate/mdc-migration/rules/tree-traversal.spec.ts
src/material/schematics/ng-generate/mdc-migration/rules/tree-traversal.ts

fixes https://github.com/angular/components/issues/26038

fix(material/schematics): fix card tmpl migration

---

src/cdk/stepper/stepper.ts

Fixes that we weren't setting the focus origin in the stepper when navigating with the keyboard, causing it to be inferred as programmatic focus.
Fixes #26210.

fix(cdk/stepper): set focus origin when navigating with keyboard

---

src/material/slider/slider-input.ts
src/material/slider/slider.spec.ts
tools/public_api_guard/material/slider.md

fix(material/slider): avoid manual fixing values on pointer up

---

src/material/card/_card-theme.scss
src/material/chips/_chips-theme.scss
src/material/core/mdc-helpers/_mdc-helpers.scss
src/material/core/theming/tests/test-css-variables-theme.scss
src/material/form-field/_mdc-text-field-theme-variable-refresh.scss
src/material/progress-bar/_progress-bar-theme.scss
src/material/snack-bar/_snack-bar-theme.scss

Technically we don't support theming using CSS variables, but the community has started depending on it anyway since it happened to work. This was broken during the switch to MDC which is blocking users from updating to v15.
These changes make a best effort to avoid all the errors and reduce the amount of warnings as much as possible.
A couple of disclaimers:
* All the places where we were manipulating colors are going to compile now, but they might not look great. This is only going to affect some MDC components though, the legacy components will work as expected.
* One warning might be logged from the themes for components based on MDC's list. They will compile and look acceptable, but I couldn't find a good way to avoid the warning with our current setup. We will be able to avoid the …

fix(material/core): better handling of css variables in theme palettes

---

renovate.json

The `merge safe` label is no longer used in the components repo. Declaring the label in the renovate config results in the label being created all the time.

build: update renovate to not apply `merge safe` label

---

src/material/snack-bar/_snack-bar-theme.scss

We were setting the snack bar action color to `currentColor` on dark themes which might not work as expected if there is a `color` on the `body`. These changes set it to an explicit color.
Fixes #26247.

fix(material/snack-bar): set explicit color on action in dark themes

---

guides/v15-mdc-migration.md

Fixes an invalid usage of the legacy SCSS module system in the migration guide.

docs: fix invalid SCSS in migration guide

---

src/dev-app/list/list-demo.html
src/dev-app/list/list-demo.ts
src/material/list/_interactive-list-theme.scss
src/material/list/list-base.ts
src/material/list/list-option.ts
src/material/list/public-api.ts
src/material/list/selection-list.spec.ts
src/material/list/selection-list.ts
src/material/list/tokens.ts
tools/public_api_guard/material/list.md

Add an opt-out for radio indicators for single-selection. Adds both an Input and DI token to specify if radio indicators are hidden. By default, display radio indicators. If both DI token and Input are specified, the Input wins.
PR #25933 added radio toggles for single-selection. Add an opt-out to provide a way to have same appearance as before #25933.
API changes
- add `@Input hideSingleSelectionIndicator` to specify if radio indicators are displayed
- add MAT_LIST_CONFIG token to specify default value for `hideSingleSelectionIndicator`

fix(material/list): add opt-out for radio indicators

---

src/material/slider/slider-input.ts

The `dragStart` and `dragEnd` events were being emitted in the `_fixValue` method, however the call to `_fixValue` was removed from the ending sequence in #26215. This meant that the `dragEnd` event was no longer being emitted.
These changes move the `dragStart` and `dragEnd` events into the pointer down/up handlers instead since emitting them has nothing to do with fixing the value.
Fixes #26285.

fix(material/slider): dragEnd not being emitted

---

src/cdk/overlay/overlay-directives.ts
src/cdk/overlay/overlay-module.ts
tools/public_api_guard/cdk/overlay.md

Converts the overlay directives to standalone so that they can be used as host directives.
Fixes #26326.

refactor(cdk/overlay): switch directives to standalone

---

src/cdk/menu/menu-item.spec.ts
src/cdk/menu/menu-item.ts
src/cdk/menu/menu-trigger.spec.ts
src/cdk/menu/menu-trigger.ts
tools/public_api_guard/cdk/menu.md

In #26051 a couple of `preventDefault` calls were added, because we were moving focus within an enter key `keydown` event which was causing the menu to close immediately after it opens. The problem is that the calls also prevent links from navigating.
These changes remove the `preventDefault` calls and resolve the initial issue by ignoring clicks initiated by the keyboard.
Fixes #26291.

fix(cdk/menu): don't prevent default selection key actions

---

src/material/menu/menu-trigger.ts
src/material/menu/menu.spec.ts

Fixes that the value for `aria-expanded` wasn't being updated when the menu is closed inside an OnPush parent.
Fixes #26262.

fix(material/menu): aria-expanded not updating in an OnPush component

---

scripts/circleci/setup-angular-snapshots.js

Angular Bazel has switched to no longer generate devmode outputs but instead be ESM only. These changes are not yet released, and also they rely on `ts_library` being patched.
Until our components setup works with it, we cannot update `@angular/bazel`.

build: fix snapshot jobs by not updating `@angular/bazel`

---

src/material/menu/menu.scss

Ports over a fix from the legacy menu to the MDC-based one. Disables pointer events on a menu that is still animating in order to prevent wrong taps.
Fixes #26306.

fix(material/menu): prevent pointer events on animating menu

---

src/material/slider/slider.scss

It's common for apps to set `box-sizing: border-box` on all elements to make layouts more consistent, however this ended up offsetting the native slider inside `mat-slider` which was causing the value to jump after dragging and the 100% value to happen around the 95% mark.
Fixes #26246.

fix(material/slider): value jumping after drag with box-sizing: border-box

---

src/material/tabs/tab-nav-bar/tab-nav-bar.ts

The touch gestures for holding the pagination buttons weren't working in the tab nav bar, because we were overriding the `ngAfterViewInit` method without invoking the `super` implementation.

fix(material/tabs): touch gestures not working on tab nav bar

---

src/material/snack-bar/snack-bar-container.scss

MDC has some built in breakpoints where the snack bar container becomes `min-width: 100%`. They didn't work correctly, because the container wasn't set up to be 100% wide.
Fixes #26290.

fix(material/snack-bar): incorrect width at some breakpoints

---

src/dev-app/chips/chips-demo.html
src/dev-app/chips/chips-demo.ts
src/material/chips/chip-listbox.ts
src/material/chips/chip-option.html
src/material/chips/chip-option.spec.ts
src/material/chips/chip-option.ts
src/material/chips/tokens.ts
tools/public_api_guard/material/chips.md

Add an opt-out for checkmark indicators for single-selection. Add both and Input and DI token to specify if checkmark indicators are hidden for single-select. By default display checkmark indicators for single-selection. If both DI token and Input are specified, the Input wins.
PR #25890 adds checkmork indicator for single selection. Add an opt-out to provide a way to have same appearance as before #25890.
Does not affect multiple-selection.
Does not affect behavior when avatar is provided. When avatar is provided, display checkmark indicator when selected. This is the same behavior as before #25890.
API Changes
- Add `@Input hideSingleSelectionIndicator` to specify if checkmark indicator is displayed for single-selection
- Add `hideSingleSelectionIndicator` property to …

fix(material/chips): add opt-out for single-select checkmarks

---

src/material/chips/chip.html

For `MatChip` component, change the `<div/>` element for the primary action to a span element. Fix problem where the div is nested inside a span. A span is a container for phrasing content and is not supposed to contain flow content. This could also potentialy cause accessibility issue. Correct the semantics by nesting a span inside another span.

fix(material/chips): change div to span

---

src/cdk/drag-drop/directives/drag.spec.ts
src/cdk/drag-drop/directives/drop-list.ts
src/cdk/drag-drop/drop-list-ref.ts
tools/public_api_guard/cdk/drag-drop.md

Fixes that the `cdk-drop-list-receiving` class wasn't being updated when two lists are connected across components boundaries that are using OnPush change detection.
Fixes #26362.

fix(cdk/drag-drop): receiving class not updated in OnPush component

---

.ng-dev/github.mts

Enable the authentication service for merging rather than using PATs

build: enable ng-dev auth service

---

src/material/chips/chips.md

Update the accessibility section on checkmark indicators for single-selection. Add instructions to always communicate selection with icon indicators. Fulfill documentation needs as follow-up for #25890 and
#26338.

docs(material/chips): update a11y documention on checkmark indicators

---

src/material/list/list.md

Update the accessibility section on radio indicators for single-selection. Add instructions to always communicate selection with icon indicators. Fulfill documentation needs as follow-up for #25933 and
#26283.

docs(material/list): update a11y documention on radio indicators

---

src/material/legacy-tabs/_tabs-theme.scss
src/material/legacy-tabs/tab-group.html
src/material/legacy-tabs/tab-header.spec.ts
src/material/tabs/_tabs-theme.scss
src/material/tabs/paginated-tab-header.ts
src/material/tabs/tab-group.html
src/material/tabs/tab-group.scss
src/material/tabs/tab-group.ts
src/material/tabs/tab-header.spec.ts
tools/public_api_guard/material/tabs.md

According to the WCAG best practices focus should be allowed on disabled tabs (see https://w3c.github.io/aria-practices/#kbd_disabled_controls). These changes update our tabs to be in line with the recommendation.
Fixes #26395.

fix(material/tabs): allow focus on disabled tabs

---

src/material/legacy-select/select.spec.ts
src/material/select/select.spec.ts
src/material/select/select.ts

Fixes that we weren't removing the active class from a reset option when a new value is assigned through a `FormControl`. The problem was that we were removing the active classes only from selected options, but a reset option is never selected.
Fixes #26390.

fix(material/select): active class not removed from reset option when new value is assigned through form control

---

src/cdk/schematics/ng-add/index.spec.ts
src/cdk/schematics/ng-generate/drag-drop/index.spec.ts
src/cdk/schematics/testing/test-case-setup.ts
src/material/schematics/ng-add/index.spec.ts
src/material/schematics/ng-generate/address-form/index.spec.ts
src/material/schematics/ng-generate/dashboard/index.spec.ts
src/material/schematics/ng-generate/mdc-migration/rules/components/test-setup-helper.ts
src/material/schematics/ng-generate/navigation/index.spec.ts
src/material/schematics/ng-generate/table/index.spec.ts
src/material/schematics/ng-generate/tree/index.spec.ts

The `runSchematicAsync` API has been replaced by `runSchematic`. These changes clean up all of our usages.

test(material/schematics): clean up deprecated API usage

---

src/cdk/testing/protractor/protractor-element.ts
src/cdk/testing/selenium-webdriver/selenium-web-driver-element.ts
src/cdk/testing/test-element.ts
src/cdk/testing/testbed/unit-test-element.ts
src/cdk/testing/tests/cross-environment.spec.ts
src/cdk/testing/tests/harnesses/main-component-harness.ts
src/cdk/testing/tests/test-main-component.html
src/material/chips/testing/chip-edit-input-harness.ts
src/material/chips/testing/chip-grid-harness.spec.ts
src/material/chips/testing/chip-harness-filters.ts
src/material/chips/testing/chip-row-harness.ts
src/material/chips/testing/public-api.ts
tools/public_api_guard/cdk/testing-selenium-webdriver.md
tools/public_api_guard/cdk/testing-testbed.md
tools/public_api_guard/cdk/testing.md
tools/public_api_guard/material/chips-testing.md

Includes a couple of commits necessary to support editing a chip row through harnesses.
The first commit adds a `setText` method to `TestElement`. It is required, because the chip's edit input is a `contenteditable` span and we currently don't have a way of setting its text.
The second commit adds `startEditing` and `finishEditing` methods to the chip row harness, as well as a `MatChipEditInputHarness` to support the entire editing flow in a test.
Fixes https://github.com/angular/components/issues/26419.

Chip harness editing support

---

src/material/schematics/ng-generate/mdc-migration/rules/theming-styles.ts
src/material/schematics/ng-generate/mdc-migration/rules/ts-migration/runtime-migration.ts
src/material/schematics/ng-update/migrations/legacy-components-v15/index.ts

Fixes that we were trying to parse stylesheets that we don't support (e.g. `.sass`).
Fixes #26396.

fix(material/schematics): don't migrate unknown stylesheet formats

---

src/dev-app/autocomplete/BUILD.bazel
src/dev-app/autocomplete/autocomplete-demo.html
src/dev-app/autocomplete/autocomplete-demo.ts
src/dev-app/checkbox/checkbox-demo.html
src/dev-app/select/BUILD.bazel
src/dev-app/select/select-demo.html
src/dev-app/select/select-demo.scss
src/dev-app/select/select-demo.ts
src/material/autocomplete/autocomplete.spec.ts
src/material/autocomplete/autocomplete.ts
src/material/core/option/option-parent.ts
src/material/core/option/option.html
src/material/core/option/option.scss
src/material/core/option/option.ts
src/material/core/selection/pseudo-checkbox/_pseudo-checkbox-common.scss
src/material/core/selection/pseudo-checkbox/_pseudo-checkbox-theme.scss
src/material/core/selection/pseudo-checkbox/pseudo-checkbox.scss
src/material/core/selection/pseudo-checkbox/pseudo-checkbox.ts
src/material/select/select.spec.ts
src/material/select/select.ts
tools/public_api_guard/material/autocomplete.md
tools/public_api_guard/material/core.md
tools/public_api_guard/material/select.md

Add checkmark to mat-option for single-select. Fix a11y issues where selected state is visually communicated with color alone. Communicate selection with both color and a checkmark indicator. Affect components that use mat-option for single-selection, which include select and autocomplete.
Add an `appearance` Input to mat-pseudo-checkbox. "full" appearance renders a checkbox, which is the current behavior. Render "full" appearance by default. "minimal" apperance renders only a checkmark.
Summary of API and behavior changes:
- Add an `@Input appearance` to pseudo-checkbox with options for "full" and "minimal".
- mat-option renders "minimal" appearance for single-select, which looks like a checkmark.
- Select and autocomplete components display checkmark on selected option.
What's not …

fix(material/core): add checkmark for single-select

---

src/material/menu/public-api.ts
tools/public_api_guard/material/menu.md

Exposes the `MenuCloseReason` type since it's used in the `closed` event of `MatMenu` which is a public API.
Fixes #26416.

refactor(material/menu): expose MenuCloseReason type

---

src/material/core/typography/_typography.scss

Fixes that our functions for converting between the 2014 and 2018 typography formats weren't copying over the top-level font family.
Fixes #26446.

fix(material/core): top-level font family not copied when converting between typography formats

---

src/material/schematics/ng-generate/mdc-migration/rules/ts-migration/runtime-migration.ts

fix(material/schematics): improve logging of mdc-migration ts migrator

---

CHANGELOG.md

docs: release notes for the v15.1.2 release

---

src/cdk/collections/selection-model.ts
src/cdk/collections/selection.spec.ts

Fixed bug in SelectionModel where compareWith function was not consistently respected in deselect method.
Fixes #25878

fix(cdk/collections): SelectionModel does not always respect the compareWith function

---

src/cdk/a11y/aria-describer/aria-reference.ts

By restricting the type of the parameter of `addAriaReferencedId`, make sure it only sets `aria-` attributes.
This makes it easier for Google security reviewers to reason about the safety of the code, granting the confidence that it will never set any security-sensitive attribute.

refactor(cdk/a11y): restrict setAttribute fanout capability

---

src/google-maps/map-event-manager.spec.ts
src/google-maps/map-event-manager.ts

When the Google Maps API fails to initialize (e.g. when the API key is invalid), it returns dummy objects which return `undefined` from `addListener`, causing an error when the `MapEventManager` is destroyed.
These changes add a check to guard against those errors.
Fixes #26514.

fix(google-maps): error if API is initialized incorrectly

---

src/components-examples/cdk/drag-drop/cdk-drag-drop-custom-preview/cdk-drag-drop-custom-preview-example.ts

Missing poster for `Episode V - The Empire Strikes Back`
https://material.angular.io/cdk/drag-drop/overview#customizing-the-drag-preview

docs(cdk/drag-drop): put back Episode V poster exemple ✨

---

src/material/dialog/_dialog-theme.scss

We were using MDC's `surface` variable to set the background of the dialog, however the `surface` was being mapped to our `card` variable. In practice the values for both are the same, but the new behavior breaks apps with custom palettes.
Fixes #26272.

fix(material/dialog): take dialog background from theme palette

---

src/material/tabs/_tabs-common.scss

Fixes that the MDC-based tabs implementation didn't allow clicks on the projected content inside a tab, because MDC was setting `pointer-events: none`.
Fixes #26195.

fix(material/tabs): unable to click projected content in tab label

---

src/material/tabs/_tabs-theme.scss

Fixes that we weren't setting an explicit color on disabled tabs which meant that they would fall back to the user agent colors.
Fixes #26304.

fix(material/tabs): set color on disabled tabs

---

src/material/checkbox/checkbox.html
src/material/checkbox/checkbox.spec.ts
src/material/checkbox/checkbox.ts
tools/public_api_guard/material/checkbox.md

Fixes that while we were toggling the checked state of a checkbox when its touch target is clicked, we weren't moving focus to the internal `input`.
Fixes #26486.

fix(material/checkbox): focus not moved to input when clicking on touch target

---

guides/v15-mdc-migration.md

The specificity of the CSS-Selector is not enough to change the behaviour. I've added the "input"-Type.

docs(material/guides/v15-mdc-migration): Change CSS-Selector-Specificity

---

guides/typography.md
guides/v15-mdc-migration.md

We no longer include the typography hierarchy automatically. These changes update the docs to mention it.
Fixes #26524.

docs: mention that typography hierarchy isn't included by default

---

src/material/chips/chip-action.ts
src/material/chips/chip-row.spec.ts

Fixes that the default action of the spacebar was being prevented while the chip is in its editing state, not allowing users to enter whitespace.

fix(material/chips): unable to add space when editing chip

---

CHANGELOG.md

docs: release notes for the v15.1.4 release

---

src/material/package-base.json

Import of the legacy prebuilt-theme in the scss did not work:
`@import '@angular/material/legacy-prebuilt-themes/legacy-indigo-pink.css';` nor the `@import '@angular/material/legacy-prebuilt-themes/indigo-pink.css';`

fix(material/core): Fix legacy prebuilt themes export

---

src/cdk/a11y/a11y.md
src/cdk/a11y/focus-trap/focus-trap.md

I am not sure if the new URL is the correct one, but the old one https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal seems outdated since it gets redirected to https://www.w3.org/WAI/ARIA/apg/ and the page contains nothing about modal dialogs. So I suggest changing it to https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/ .

docs: fix outdated wai-aria-practices dialog_modal url

---

src/material/radio/radio.html
src/material/radio/radio.spec.ts
src/material/radio/radio.ts
tools/public_api_guard/material/radio.md

Fixes that the radio button's internal `input` wasn't receiving focus when the touch target is clicked.
Fixes #26487.

fix(material/radio): input not focused when clicking on touch target

---

CHANGELOG.md

docs: release notes for the v15.1.5 release

---

src/material/tabs/tab-group.html
src/material/tabs/tab-group.spec.ts

The tab group wasn't passing the `disablePagination` input to the tab header so it wasn't being picked up.
Fixes #26621.

fix(material/tabs): disablePagination not working

---

src/components-examples/material/datepicker/datepicker-views-selection/datepicker-views-selection-example.ts

add missing encapsulation  to disable pointer-events for periodButtonLabel.
fixes #24915

docs(material/datepicker): avoid CalendarView switching

---

package.json

Main branch should target v16 similar to the framework.

build: prepare for v16 in `main` branch

---

.ng-dev/google-sync-config.json

As of the MDC list token PR, the sync configs are slightly out of sync. This commit fixes it.

build: update sync config to reflect internal config

---

CHANGELOG.md

docs: release notes for the v15.1.6 release

---

guides/v15-mdc-migration.md
src/material/chips/chip-option.ts
src/material/chips/chip-row.ts
src/material/chips/chip.ts
tools/public_api_guard/material/chips.md

Updates the selector for chips to allow attributes like in the legacy chips.
Fixes #26677.

fix(material/chips): allow attribute selectors for chips

---

src/material/snack-bar/snack-bar-container.scss

Fixes that multiple lines of text weren't aligned correctly in the snack bar on Safari.
Fixes #26685.

fix(material/snack-bar): misaligned lines on safari for long messages

---

src/material/chips/chip.ts
tools/public_api_guard/material/chips.md

Some of the chip styling depends on the presence of chips actions and it wasn't being updated when they were toggled.
Fixes #26691.

fix(material/chips): styling not updating when actions are removed

---

src/material/chips/chip-grid.ts
src/material/chips/chip-listbox.ts
src/material/chips/chip-set.ts

Uses `div` instead of `span` for the top-level chip wrappers since some a11y tools flag nesting `div` inside of `span` as invalid.

fix(material/chips): remove spans from top level of component

---

package.json
src/dev-app/dev-app/dev-app-layout.ts
src/dev-app/theme.scss
src/material/chips/_chips-theme.scss

fix(material/chips): chips should assume their minimum density rather than error for small densities

---

guides/v15-mdc-migration.md

To install a package, the version must be prefixed by `@`

docs: fix update command for v15 migration

---

src/material/schematics/ng-generate/mdc-migration/rules/index.ts
src/material/schematics/ng-generate/mdc-migration/rules/ts-migration/runtime-migration.ts
src/material/schematics/ng-generate/mdc-migration/rules/ts-migration/runtime-migrator.spec.ts

Fixes mdc-migration to migrate only the selected components.
Fixes #26426

fix(mdc-migration): migrate components selectively bug

---

guides/typography.md

docs(material/typography): **reverse body-1 and body-2 description**
Reverse the description of `body-1` and `body-2` in the documentation for 'Typography levels'. Looking at how mat-body-1 (mat-h4) and mat-body-2 (mat-body) classes are applied, it seems that the descriptions in the documentation are reversed.
BREAKING CHANGE: the description for body-1 and body-2 has changed
Closes #26251

reverse body-1 and body-2 description

---

src/material/list/list-base.ts
src/material/list/list.spec.ts

Previously, mat-list-item buttons did not have the `disabled` attribute set when either the `mat-list-item` or the `mat-action-list` are disabled.
This commit adds the `disabled` attribute to `mat-list-item` buttons when it should be applied.
Fixes #26574.

fix(material/list): add disabled attribute for mat-list-item buttons

---

src/material/chips/chip-set.ts

Fixes that it wasn't possible for the user to use shift + tab to move out of a chip set. We had some logic to handle it already, but it was resetting the tabindex before focus has a chance to escape.
Fixes #26698.

fix(material/chips): unable to shift + tab out of a chip set

---

src/material/legacy-snack-bar/snack-bar-container.html
src/material/snack-bar/snack-bar-container.html
src/material/snack-bar/snack-bar-container.ts
tools/public_api_guard/material/snack-bar.md

Implements a workaround to the issue where some browsers don't expose live elements to the accessibility tree if there's an `aria-modal` on the page.
Fixes #26708.

fix(material/snack-bar): live region not working when modal is open

---

src/material/core/option/option.ts
src/material/legacy-core/option/option.ts
src/material/legacy-select/select.spec.ts
src/material/select/select.spec.ts
tools/public_api_guard/material/core.md

For mat-option, set `aria-selected="false"` on deselected options. Confirms with [WAI ARIA Listbox authoring practices guide](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/), which says to always include aria-selected attribute on listbox options that can be selected. Fix issue where VoiceOver reads every option as "selected" (21491).
Fix #21491

fix(material/core): mat-option sets aria-selected="false"

---

src/material/datepicker/calendar-body.ts

Fixes that the datepicker was referring to the `window` which throws an error during server-side rendering.
Fixes #26729.

fix(material/datepicker): resolve server-side rendering error

---

src/material/paginator/paginator.html

Opt-out of the single-selection indicator for mat-select. Fix bug where text is truncated when there are 10 or more items per page.

fix(material/paginator): opt-out of single-selection indicator

---

CHANGELOG.md

docs: release notes for the v15.2.2 release

---

src/material/chips/chip-row.spec.ts
src/material/chips/chip-row.ts
tools/public_api_guard/material/chips.md

The chip row was calling `preventDefault` on `mousedown` events in order to avoid sending focus to the chip grid which in turn moves it to the first chip. This is problematic, because preventing the default `mousedown` action also stops native drag&drop and `click` events.
These changes resolve to original issue by making the chip focusable on clicks and forwarding focus through there.

fix(material/chips): don't prevent default mousedown action

---

src/components-examples/material/chips/chips-stacked/chips-stacked-example.css

Fixes that the stacked chips example was using the wrong selector so the chips were too wide.
Fixes #26589.

docs(material/chips): fix stacked chips example

---

src/cdk/table/table.ts
src/material/autocomplete/autocomplete.ts
src/material/chips/chip-listbox.ts
src/material/legacy-autocomplete/autocomplete.ts
src/material/legacy-chips/chip-list.ts
src/material/legacy-form-field/form-field.ts
src/material/legacy-menu/menu.ts
src/material/legacy-select/select.ts
src/material/legacy-table/table.ts
src/material/legacy-tabs/tab-group.ts
src/material/menu/menu.ts
src/material/select/select.ts
src/material/sidenav/drawer.ts
src/material/sidenav/sidenav.ts
src/material/sort/sort.ts
src/material/stepper/stepper.ts
src/material/table/table.ts
src/material/tabs/tab-group.ts

This adds the skip hydration host binding to every component where direct dom manipulation occurs that would break hydration. This allows anyone that uses material components to not have to worry about manually adding this attribute themselves.

refactor(multiple): Updated components to use host binding for ngSkipHydration

---

src/dev-app/chips/chips-demo.html
src/dev-app/chips/chips-demo.scss
src/material/chips/chip-option.ts
src/material/chips/chip-set.ts
src/material/chips/chip.scss
src/material/chips/chip.ts
tools/public_api_guard/material/chips.md

Fixes several issues that prevented the basic chips from appearing basic in `mat-chip-listbox` and `mat-chip-grid`:
* `basicChipAttrName` was overwritten to the correct value, but because we were checking it in the constructor, the override value wasn't picked up.
* The proper host bindings weren't in place to clear the styling.
* The user agent styles typography styles of the `button` inside the `mat-basic-chip-option` weren't cleared.
* The logic that checks if a click originates from a chip was excluding basic chips.

fix(material/chips): styling not cleared on basic chips in listbox and grid

---

src/material/legacy-tabs/tab-header.spec.ts
src/material/tabs/paginated-tab-header.ts
src/material/tabs/tab-header.spec.ts

<s>_scrollheader() computes the distance to move a tab list. Originally it set the scroll amount to a third of the length of the tab list view window, which did not consider the length of the tab label itself. When the screen size is small, the label might be clipped and not completely readable on its own and users see just the left or right of the tab text.
This PR updates _scrollheader() function to make it smarter on distance calculation. It introduced two variables,
- `minLeftSpace`: the distance from the first fully rendered label to the left border of the viewport.
- `minRightSpace`: the distance from the last fully rendered label to the right border of the viewport. 
Now the new scroll amount is,
- 'before' direction: `MINIMUM(minRightSpace, 1/3 * viewLength)`
- 'after' direction: …

 fix(material/tabs): update MatTab _scrollToLabel function to always display a label from its start

---

src/material/chips/chip.scss

Fixes that the `z-index`, which is set on the chip labels, appears on top of sticky columns inside a table.
Fixes #26793.

fix(material/chips): chip label appearing above sticky columns

---

src/material/tooltip/tooltip.scss

Fixes that we were adding an additional hover area on all sides of the tooltip, rather than only the side that is next to the trigger.
Fixes #26557.

fix(material/tooltip): only expand hover area on side closest to trigger

---

src/material/datepicker/date-range-input.spec.ts
src/material/datepicker/date-range-input.ts

Fixes that the date range input wasn't styled as being required when using the `required` reactive forms validator.
Fixes #26654.

fix(material/datepicker): date range input not marked as required when using reactive forms

---

src/material/core/option/option.html
src/material/core/option/option.scss
src/material/core/option/option.spec.ts
src/material/core/option/option.ts

Apply strong focus styles to the selected option. Do this by putting the `.mat-mdc-focus-indicator` class on the ripple element.
Fix issue where the List styles from MDC override the strong focus style, which causes the strong focus indicator to not be present on selected option (angular#26801).
Align maat-option with list-item's implementation by putting the focus indicator on a child element of the component root, rather than directly on the component root.
Does not add aditional DOM nodes.

fix(material/core): apply strong focus styles to selected option

---

CHANGELOG.md

docs: release notes for the v15.2.4 release

---

src/dev-app/autocomplete/autocomplete-demo.html
src/dev-app/autocomplete/autocomplete-demo.ts
src/dev-app/select/select-demo.html
src/dev-app/select/select-demo.ts
src/material/autocomplete/autocomplete-trigger.ts
src/material/autocomplete/autocomplete.spec.ts
src/material/autocomplete/autocomplete.ts
src/material/core/option/_option-theme.scss
src/material/core/option/option.scss
src/material/select/select.spec.ts
src/material/select/select.ts
tools/public_api_guard/material/autocomplete.md
tools/public_api_guard/material/select.md

Allow keyboard navigation to disabled options of Select and Autocomplete
component. Align with WAI ARIA instructions for list options from
[Developing a Keyboard
Interface](https://www.w3.org/WAI/ARIA/apg/practices/keyboard-interface/).
Fix accessibility issues where some screen readers are not able to navigate
to disabled options.
The user can focus disabled options using keyboard, but the user cannot
click disabled options.

fix(material/core): allow keyboard navigation to disabled options 

---

src/material/datepicker/calendar-body.html
src/material/datepicker/calendar-body.scss

Fixes that we had divs as children of buttons which some a11y tools complain about.
Fixes #26825.

fix(material/datepicker): remove div as a child of button

---

src/cdk/overlay/scroll/close-scroll-strategy.spec.ts
src/cdk/overlay/scroll/close-scroll-strategy.ts

Fixes that the `CloseScrollStrategy` was being triggered by scrollables inside the overlay.
Fixes #26780.

fix(cdk/overlay): don't close if scroll is coming from inside overlay

---

src/material/checkbox/checkbox.html
src/material/radio/radio.html
src/material/slide-toggle/slide-toggle.html

This is added to prevent a bug with the upcoming Theming API for Form Field.

feat(material/formfield): Add `mdc-label` class to `<label>`

---

package.json
src/google-maps/google-map/google-map.ts
src/google-maps/map-marker/map-marker.ts
src/google-maps/package.json
tools/public_api_guard/google-maps/google-maps.md
yarn.lock

Updates the Google Maps package to use the latest version of the typings.

fix(google-maps): update to latest typings

---

CHANGELOG.md

docs: release notes for the v15.2.5 release

---

src/material/dialog/dialog.scss

Removes an unused import from the dialog styles.

refactor(material/dialog): resolve lint error

---

src/cdk/menu/menu-bar.spec.ts
src/cdk/menu/menu-trigger.spec.ts
src/cdk/menu/menu-trigger.ts
src/cdk/menu/menu.spec.ts

Fixes that the CDK menu wasn't moving focus to the first item when opening using a click. This caused other issues like not being able to use the escape key to close the menu.
Fixes #26858.

fix(cdk/menu): move focus when opening via click

---

src/material/core/typography/_typography-utils.scss

This avoids overriding font properties with default values that can't be configured in the current typography config, e.g. the font-variant-caps or font-feature-settings property.
Fixes #26864

fix(material/core): don't use font shorthand property in typography-level

---

src/material/button/_icon-button-theme.scss

The icon button theme was using a slash for division instead of `math.div` which causes a deprecation warning to be logged which was breaking one of the tests.

refactor(material/button): resolve build failures

---

CHANGELOG.md

docs: release notes for the v15.2.6 release

---

src/material-luxon-adapter/adapter/luxon-date-adapter.spec.ts
src/material-luxon-adapter/adapter/luxon-date-adapter.ts

Fixes a bug where the timezone on the Luxon DateTime is thrown away during conversion to string, resulting in using the Luxon defaultZone regardless of how the particular DateTime is configured.
Fixes #26869

fix(material-luxon-adapter): zone on DateTime ignored

---

src/cdk/tree/tree-redesign.spec.ts
src/cdk/tree/tree.ts

feat(cdk/tree): add tests for the new cdk/tree APIs

---

src/material/core/tokens/m2/mat/_tab-header.scss
src/material/core/tokens/m2/mdc/_tab-indicator.scss
src/material/tabs/_tabs-common.scss
src/material/tabs/tab-nav-bar/tab-link.scss

Adds new tokens to the tabs to make it easier to implement the gmat variant.

refactor(material/tabs): introduce new tokens

---

src/material/tabs/_tabs-common.scss

Resolves a recent regression where tabs no longer have a `background: none` which can cause them to be grey when used on a `<button>` element.

fix(material/tabs): remove background color from tabs

---

src/components-examples/package.json

build: update no longer available export
`fesm2020` was replaced with `fesm2020` no longer available. This is needed to fix https://app.circleci.com/pipelines/github/angular/components/52235/workflows/84d2aaf9-f235-4c55-a63d-d712619d1f50/jobs/469364

build: remove no longer available export

---

src/material/schematics/ng-add/index.spec.ts
src/material/schematics/ng-add/setup-project.ts

Switches to generating `provideAnimations` and `provideNoopAnimations` instead of `importProvidersFrom(BrowserAnimationsModule)` in `ng add`.

fix(material/schematics): use provider functions in ng add

---

CHANGELOG.md

docs: release notes for the v15.2.7 release

---

src/material/schematics/migration.json

Fixes that the Material `ng update` schematic was pointing to a file that doesn't exist.
Fixes #26929.

fix(material/schematics): reference correct entrypoint in schematic definition

---

src/material/button/_icon-button-theme.scss

Fix specificity for density so that it correctly overrides the state layer size

fix(material/button): add specificity to icon button density

---

integration/harness-e2e-cli/yarn.lock
integration/mdc-migration/golden/yarn.lock
integration/mdc-migration/sample-project/yarn.lock
integration/ng-add-standalone/yarn.lock
integration/ng-add/yarn.lock
yarn.lock

Some PRs started failing, because of an outdated `caniuse-lite` database. These changes updates them.

build: update caniuse database in integration tests

---

src/material/form-field/BUILD.bazel
src/material/form-field/_user-agent-overrides.scss
src/material/form-field/form-field.scss

Fixes that some non-text input variants were taller than the text ones.
Fixes #26915.

fix(material/form-field): inconsistent height for non-text inputs

---

CHANGELOG.md

docs: release notes for the v15.2.8 release

---

src/material/chips/chip-listbox.ts

Fixes that the chips listbox was emitting change events both when a chip is toggled and when the listbox is blurred.
Fixes #26942.

fix(material/chips): avoid double emit of changed event on blur

---

src/material/button/_button-base.scss
src/material/button/button.scss
src/material/button/icon-button.scss

The style for ripple were not added for mat-fab and mat-mini-fab buttons in #26568.
Spotting the issue on demo is a little bit tricky, because there are always a button (mat-button, mat-icon-button), which provides the global style for .mat-mdc-button-ripple. But without this components mat-fab button will look as on the screenshot below.
I was considering adding the overflow: hidden into fab.scss, but the _button-base.scss file is more appropriate in my opinion.
The ripple problem without overflow: hidden:

fix(material/button): fix ripple style for all types of buttons

---

tools/example-module/generate-example-module.ts

This new helper removes the examples' reliance on internal APF structure and naming. Currently the examples hard code the ECMAScript version into the application which can and will change over time. The helper function also removes the need to use Webpack-specific magic comments in the documentation website to prevent unwanted files from being loaded.
The recent updates to the APF for v16 required several manual changes to both the examples and the documentation site which will no longer be needed in the future. This change retains the existing functionality to allow for the documentation site to be updated with the new functionality. Once updated, additional cleanup is possible to remove the then unused loading functionality.

build: add a generated helper function to load examples

---

src/material/chips/_chips-theme.scss

* Chip density styles were not being applied properly because of specificity issues - [Stackblitz example](https://stackblitz.com/edit/angular-ujvygb?file=src%2Ftheme.scss)

fix(material/chips): fix chip density styles

---

src/cdk/dialog/dialog-container.ts
src/material/dialog/dialog-container.ts
src/material/dialog/dialog.spec.ts
tools/public_api_guard/cdk/dialog.md

When we trigger a dialog animation, we set a CSS variable and a couple of classes to start it, however because we were adding the classes imemdiately after setting the variable, sometimes the animation would be skipped because the browser didn't have time to recalculate the styles.
These changes resolve the issue by adding the classes in a `requestAnimationFrame` which gives the browser enough time to pick up the animation duration.
Fixes #26931.

fix(material/dialog): opening animation sometimes being skipped

---

src/material/select/_select-theme.scss

On lower densities some form field appearances hide the label which caused the arrow to be misaligned. These changes add an override to center the label again.
Fixes #26757.

fix(material/select): ensure arrow is centered on all densities

---

src/cdk/a11y/key-manager/tree-key-manager.spec.ts
src/cdk/a11y/key-manager/tree-key-manager.ts

Based on #24659. Followed by #26587.

feat(cdk/tree): implement expansion methods for TreeKeyManager

---

src/material/tabs/ink-bar.ts

There's a resize observer in the `paginated-tab-header`, that calls `_alignInkBarToSelectedTab` method here https://github.com/angular/components/blob/946cc6743c4d0f46c943fca7fdb2ed07148535d9/src/material/tabs/paginated-tab-header.ts#L206 
This causes the ink bar to be updated each time there's any size change. Sometimes it can cause additional problems. For example, in our case we are slightly customizing the UI so that selected tab has larger font weight than others. And this actually triggers the resize observer, which attempts to redraw the ink bar twice and breaks the ink bar animation
https://user-images.githubusercontent.com/33101123/236193271-2e37a5c6-a267-4846-b680-554e944c554c.mp4

fix(material/tabs): avoid unnecessary updates of tab ink bar

---

src/cdk/schematics/update-tool/utils/parse-tsconfig.ts

Fixes that the `ng update` schematics were throwing an error if the tsconfig doesn't match any files.
Fixes #27055.

fix(cdk/schematics): avoid throwing an error for empty program

---

src/material/legacy-tooltip/testing/tooltip-harness.ts
src/material/legacy-tooltip/tooltip.ts
src/material/tooltip/testing/shared.spec.ts
src/material/tooltip/testing/tooltip-harness.ts
src/material/tooltip/tooltip.ts
tools/public_api_guard/material/legacy-tooltip-testing.md
tools/public_api_guard/material/tooltip-testing.md

feat(material/tooltip): add isDisabled method to tooltip harness

---

src/material/tabs/_tabs-common.scss
src/material/tabs/tab-group.spec.ts
src/material/tabs/tab-group.ts
src/material/tabs/tab-nav-bar/tab-nav-bar.spec.ts
src/material/tabs/tab-nav-bar/tab-nav-bar.ts
tools/public_api_guard/material/tabs.md

feat(material/tabs): ink bar animation synchronize
The animation of the ink bar of the mat tab group and the mat tab nav bar is now synchronized with the animationDuration of the tab body. When the animation duration of the tab body was set to e.g. 0ms the ink bar still had an animation of 500ms. The following feat extends the animationDuration property to not only affect the tab body but also the ink bar of the tab group and the tab nav bar.
Fixes angular#25068

feat(material/tabs): ink bar animation synchronize

---

integration/mdc-migration/golden/yarn.lock
integration/mdc-migration/sample-project/yarn.lock
src/material/form-field/form-field.scss

Fixes that the prefix and suffix sometimes might not be clickable because they're underneath the label.
Fixes #27043.

fix(material/form-field): ensure prefix and suffix are on top of other content

---

src/dev-app/badge/badge-demo.html
src/material/badge/badge.md
src/material/badge/badge.spec.ts
src/material/badge/badge.ts

The badge current applies `aria-describedby` to surface the developer-provided description. However, assistive technology generally doesn't read these description on non-interactive elements. So, we can take advantage of our handy `InteractivityChecker` and do something different if the host is not focusable; we add the description inline as the next sibling with `.cdk-visually-hidden`.
Fixes #26190

fix(material/badge): insert inline description for non-interactive hosts

---

src/material/core/tokens/m2/mdc/_linear-progress.scss
src/material/core/tokens/tests/test-validate-tokens.scss

Also, temporarily comment out token slots validation test while
`bar-and-track-height` is removed from MDC.

refactor(material/progress-bar): Delete temp `bar-and-track-height` token

---

src/material/legacy-core/option/optgroup.html

Corrects ARIA semantics for the mat-optgroup component. Add role="presentation" to the label and remove aria-hidden="true" from the label.
Fix compatibility issue with MAC Hover text a11y feature #27080. The label of the option group does not need to be aria-hidden, and the Mac Hover text feature seems to rely on it.
Fix #27080

fix(material/core): Fix MacOS Hover feature compatibility with optgroup

---

src/cdk/schematics/testing/test-project.ts

Replaces the usages of `runExternalSchematicAsync` with `runExternalSchematic`.

refactor(cdk/schematics): remove deprecated utility usages

---

src/material/paginator/paginator.html

For the mat-paginator component, add aria-hidden="true" to the decorative svg elements.
Previously, the svg elements for the chevron icons would produce an img node in the a11y tree nested under the button node for "Previous page"/"Next page". This seemed to cause issue with JAWS screenreader where screen reader navigation would have duplicate navigation (#26967).
With this change applied, the svg elements are aria-hidden and do not affect the accessibility tree. This is appripriate since the chevron icons are purely decorative.
Fix #26967

fix(material/paginator): add aria-hidden="true" to decorative svg's

---

FAQ.md

The angular flex-layout project is no longer supported. Remove reference to this project within the FAQ.md.
Fixes: #27110

fix(documentation/faq.md) - Update FAQ.md - Fixes #27110

---

src/material/chips/chip-option.html
src/material/datepicker/datepicker-toggle.html
src/material/legacy-menu/menu-item.html
src/material/legacy-paginator/paginator.html
src/material/menu/menu-item.html
src/material/select/select.html
src/material/slide-toggle/slide-toggle.html

Adds `aria-hidden` on all SVG nodes that didn't have them already to prevent them from being treated as images.
Fixes #27113.

fix(multiple): set aria-hidden on presentational svgs

---

src/material/datepicker/calendar-body.ts

Fixes that the date range picker might log a warning, because we aren't setting some events as explicitly active.
Fixes #27072.

fix(material/datepicker): set explicit event options

---

src/material/checkbox/_checkbox-theme.scss
src/material/checkbox/checkbox.scss
src/material/core/style/_sass-utils.scss
src/material/core/theming/tests/theming-api.spec.ts

For example:
```
.my-el {
@include mat.checkbox-theme(...);
}
```
should emit the token values on `.my-el`, not `.my-el .mat-mdc-checkbox`

fix(material/checkbox): set token values on the element where theme is @included

---

src/cdk/schematics/update-tool/component-resource-collector.ts

Fixes that migrations may throw a "Character out of bounds" error if a template is using BOM.
Fixes #27057.

fix(cdk/schematics): handle templates with byte order mark

---

guides/theming.md

updates pre-built theme doc using incorrect name for blue-grey variable name
fixes #25768

docs: fix blue-grey palette name in theming

---

src/material/tooltip/tooltip.ts
tools/public_api_guard/material/tooltip.md

add description for Input('matTooltipPositionAtOrigin')
fixes #26078

fix(material/tooltip): missing positionAtOrigin documentation

---

src/material/icon/testing/icon-harness.ts
src/material/icon/testing/shared.spec.ts

Fixes that the badge was returning all of its `textContent` for the name which may include other elements (e.g. badges). Only the text directly inside of the icon determines its name.
Fixes #27015.

fix(material/icon): harness returning wrong name if icon has other content

---

src/material/list/list-base.ts

Fixes a bug that input coercion does not work for the `disableRipple` input on any list item because the setter in `MatListItemBase` still requires a `boolean` and not a `BooleanInput` value.
Fixes #27125

fix(material/list): input coercion does not working for `disableRipple` on list items

---

src/material/list/list-base.ts

prior this commit on properties table disableRipple had no description showing table cell to be empty

docs(material/list): description for disableRipple

---

src/material/button/button-base.ts
tools/public_api_guard/material/button.md

The button has a host binding that doesn't actually set the attribute it is bound to, but rather it is used to update the state of the ripple. This is an antipattern since data bindings aren't supposed to have side effects.

refactor(material/button): clean up antipattern

---

src/material/slider/slider-input.ts
src/material/slider/slider.spec.ts
tools/public_api_guard/material/slider.md

* fixes yaqs/6342072129453817856

fix(material/slider): handle ngModel initial null value

---

src/material/datepicker/datepicker.md

fix : https://github.com/angular/components/issues/27159

docs(material/datepicker): fix description for matDatepickerFilter

---

src/material/select/select.ts
tools/public_api_guard/material/select.md

Fixes that in some cases the select was resolving its overlay origin too early which caused it to position itself incorrectly when it is opened.
Fixes #27063.

fix(material/select): incorrect position if initialized late

---

src/dev-app/chips/chips-demo.html
src/material/chips/chip-set.scss

Ensure that the click target of stacked chips is the entire width of the chip. Fix issue where applying .mat-mdc-chip-set-stacked causes chips to respond to clicks when clicking on the text; did not respond when clicking inside the chip but not over the text (#26590).
Ensure the clickable elemen tof the chip takes up the whole visual area of the chip by overriding styles from MDC library. Angular Material supports vertically-stacked chips, which MDC does not.
Fix #26590

fix(material/chips): fix click target when stacked

---

CHANGELOG.md

Cherry-picks the changelog from the "16.0.x" branch to the next branch (main).

docs: release notes for the v16.0.3 release

---

src/material/tabs/tab-nav-bar/tab-nav-bar.ts

Fixes that the tab nav bar wasn't picking up the default value for `stretchTabs` from the config.
Fixes #27211.

fix(material/tabs): default stretchTabs value not picked up by nav bar

---

src/cdk/stepper/stepper.ts
src/material/stepper/stepper.spec.ts
tools/public_api_guard/cdk/stepper.md

adds two-way binding for selectedIndex, previously stepper had selectionChange which include selectedIndex & other properties in it
fixes #15627

fix(material/stepper): two-way binding for selectedIndex

---

src/material/tabs/_tabs-common.scss

Prior this commit disabled tab header content is clickable and causing event when it shouldn't
Fixes #27071

fix(material/tabs): tab header is clickable if its disable

---

CHANGELOG.md

Cherry-picks the changelog from the "16.0.x" branch to the next branch (main).

docs: release notes for the v16.0.4 release

---

src/material/select/select.ts

The select had configured its positions under the assumption that the dropdown is always as wide as the trigger so it only provided a vertical fallback position. Since users are now able to control the panel width, we also need horizontal fallbacks.
Fixes #27256.

fix(material/select): provide horizontal fallback positions

---

src/components-examples/material/chips/chips-autocomplete/chips-autocomplete-example.ts
src/components-examples/material/chips/chips-form-control/chips-form-control-example.ts
src/components-examples/material/chips/chips-input/chips-input-example.ts
src/dev-app/chips/chips-demo.ts
src/material/chips/chips.md

Update the accessibility instructions for the `MatChipRemove` directive. Require author to communicate to Assisstive Technology when a chip is removed. This can be done by sending a message with `LiveAnnouncer`.
Following these instructions avoids an a11y issue  where removing a chip is communicated only visually, and it is not communicated with any other senses (#12122).
Update all examples to follow these instructions by announcing deletion with `LiveAnnouncer`.
Fix #12122

docs(material/chips): require announcing removal of chip to AT

---

src/dev-app/checkbox/checkbox-demo.html
src/dev-app/theme-token-api.scss
src/material-experimental/_index.scss
src/material-experimental/theming/README.md
src/material-experimental/theming/_card.scss
src/material-experimental/theming/_checkbox.scss
src/material-experimental/theming/_theming.scss
src/material-experimental/theming/_token-resolution.scss
src/material/card/_card-theme.scss
src/material/checkbox/_checkbox-theme.scss
src/material/core/style/_sass-utils.scss

This allows us to expose easier to understand names for users, and
decouples us from changes that MDC might make to token names in the
future

feat(material-experimental/theming): Introduce a facade layer between user-facing customizable keys and actual MDC token names

---

src/material/tabs/tab-nav-bar/tab-nav-bar.spec.ts
src/material/tabs/tab-nav-bar/tab-nav-bar.ts

Fixes that while we were preventing clicks on disabled links using `pointer-events`, we didn't prevent keyboard events.
Fixes #27270.

fix(material/tabs): prevent default keyboard actions on disabled links

---

src/components-examples/cdk/drag-drop/cdk-drag-drop-disabled/cdk-drag-drop-disabled-example.css

docs(cdk/drag-drop): fix cursor for disable drag

---

.bazelrc

Bazel detects maximum number of jobs based on host resources. Since we run remotely, we can increase this number significantly.

build: speed up RBE by allowing more concurrent jobs

---

src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
src/cdk/a11y/focus-monitor/focus-monitor.ts

The `FocusMonitor` is set up to emit `null` when an element is blurred and we have some components that depend on that value to mark themselves as touched. However, it's also set up to return an rxjs observale `of(null)` on the server which means that it'll emit and complete immediately. This is problematic, because it can mark components as touched even though they haven't been.
These changes remove the parameter from `of()` so it never emits.
Fixes #27234.

fix(cdk/a11y): don't emit blurred events on the server

---

src/material/chips/_chips-theme.scss
src/material/chips/chip.scss
src/material/core/tokens/m2/mdc/_chip.scss

[refactor(material/chips): Use tokens for state layer](https://github.com/angular/components/pull/27245/commits/9d6bfd6822150addd2d136213ca7cf80a3f21deb) 
Refactors how the state layer for chips components is styled. Use the
`focus-state-layer-color` and `focus-state-layer-opacity` to style the
focus state layer.
Does not make visual changes.
Googlers: see also http://cl/538867829

refactor(material/chips): Use tokens for state layer

---

src/cdk/testing/tests/test-main-component.html

The Selenium Webdriver tests for harnesses have been flaky for a while now, because the click coordinates haven't been consistent across test runs. My theory is that it's due to the page being scrolled down on some of them.
These changes attempt to reduce the flakes by making the clicked element fixed.

test(cdk/testing): attempt to deflake webdriver tests

---

guides/theming-your-components.md

Fixes missing $theme variable in [Reading color values](https://material.angular.io/guide/theming-your-components#reading-color-values) in [Theme your own components](https://material.angular.io/guide/theming-your-components)
Fixes https://github.com/angular/components/issues/24405

docs(material/theming): add missing theme variable to theming guide docs

---

src/material/core/tokens/m2/mat/_select.scss
src/material/select/select.scss

Renames some of the `mat-select` tokens to make it clearer what they're referring to.

refactor(material/select): rename some tokens for more clarity

---

src/dev-app/slide-toggle/slide-toggle-demo.html
src/material/slide-toggle/slide-toggle-config.ts
src/material/slide-toggle/slide-toggle.html
src/material/slide-toggle/slide-toggle.spec.ts
src/material/slide-toggle/slide-toggle.ts
tools/public_api_guard/material/slide-toggle.md

Adds an input that allows users to opt into hiding the slide toggle icon.
Fixes #27321.

feat(material/slide-toggle): allow for icon to be hidden

---

src/cdk/a11y/key-manager/tree-key-manager.ts
src/cdk/tree/control/nested-tree-control.ts
src/cdk/tree/nested-node.ts
src/cdk/tree/toggle.ts
src/cdk/tree/tree-redesign.spec.ts
src/cdk/tree/tree.spec.ts
src/cdk/tree/tree.ts
src/components-examples/cdk/tree/cdk-tree-flat-children-accessor/cdk-tree-flat-children-accessor-example.ts
src/components-examples/cdk/tree/cdk-tree-flat-level-accessor/cdk-tree-flat-level-accessor-example.ts
src/components-examples/cdk/tree/cdk-tree-flat/cdk-tree-flat-example.html
src/components-examples/cdk/tree/cdk-tree-nested-level-accessor/cdk-tree-nested-level-accessor-example.ts
src/components-examples/cdk/tree/cdk-tree-nested/cdk-tree-nested-example.html
src/dev-app/tree/tree-demo.ts
src/material/tree/node.ts
src/material/tree/testing/shared.spec.ts
src/material/tree/tree.spec.ts
src/material/tree/tree.ts
tools/public_api_guard/cdk/a11y.md
tools/public_api_guard/cdk/tree.md
tools/public_api_guard/material/tree.md

feat(cdk/tree): integrate TreeKeyManager with cdk/tree

---

src/material/core/tokens/_token-utils.scss

Currently we look up if a token is set to null in the token map, and if it is, we don't emit the slot at all. The problem is that `null` is also returned if the token doesn't exist at all which may mask some bugs.
These changes add a check to verify that the token exists before trying to look it up.

fix(material/core): add validation to create-token-slot

---

src/cdk/schematics/ng-update/devkit-migration-rule.ts
src/cdk/schematics/ng-update/devkit-migration.ts
src/cdk/schematics/utils/ast.ts
src/cdk/schematics/utils/build-component.ts
src/cdk/schematics/utils/get-project.ts
src/cdk/schematics/utils/project-index-file.ts
src/cdk/schematics/utils/project-main-file.ts
src/cdk/schematics/utils/project-style-file.ts
src/cdk/schematics/utils/project-targets.ts
src/cdk/schematics/utils/project-tsconfig-paths.ts
src/cdk/schematics/utils/schematic-options.ts
src/material/schematics/ng-add/index.spec.ts
src/material/schematics/ng-add/theming/theming.ts

Removes deep imports for some devkit APIs from the CDK schematics code to avoid potential build issues.
Fixes #27344.

fix(cdk/schematics): clean up deep imports of devkit APIs

---

src/material/core/ripple/ripple-renderer.ts

Fixes some flakes that have shown up in the ripple tests. It seems that sometimes the browser doesn't assign the `changedTouches` in tests which leads to flakiness.

refactor(material/core): resolve flakes in ripple tests

---

src/material/chips/chip-row.html
src/material/chips/chip-row.spec.ts
src/material/chips/chip.scss

[fix(material/chips): remove button role from editable chips](https://github.com/angular/components/pull/27317/commits/b056fc25b8bccce941b861cc774ad9185aa9a303) 
Removes the button role from editable input chips. Fix accessibility
issue in ChipRow where the chip action element is mislabeled as a
button (https://github.com/angular/components/issues/27106). Remove butotn role by remove DOM node thtat used to
have button role and using the gridcell role element for the primary
chip action instead.
Tested cross-browser with supported screen readers on MacOS and Windows.
Tested on "Chips with input" example by verifying that a chip could be
added then edited after adding. Also verifying that AT read the chip's
aria description.
Testing Environment
- macOS 13.4 (22F66) / VoiceOver
- Chrome …

fix(material/chips): remove button role from editable chips

---

src/material/badge/badge.ts

prior this commit there was no warning for matBadge being use with <mat-icon> as it is aria-hidden by default which means badge content is invisible to screen readers
fixes #27035

fix(material/badge): warn if use with mat-icon

---

CHANGELOG.md

docs: release notes for the v16.1.3 release

---

src/material/menu/_menu-theme.scss
src/material/menu/menu-trigger.ts
tools/public_api_guard/material/menu.md

The menu theme was including the MDC list styles directly at the root of the theme which caused to leak into other components like `mat-list`.
The mixins will be removed in #27377, however currently the screenshot tests of a lot of internal targets assume that the leaky styles will be there which breaks the presubmit of #27377.
These changes introduce a *temporary* wrapper class around the mixins so that the incorrect screenshots can be approved before trying to land #27377.

fix(material/menu): prevent menu styles from leaking to other components

---

src/material/core/typography/_typography-utils.scss

Currently the typography functions assume that a config and the level being looked up will exist, but that's not necessarily the case which leads to some cryptic error messages that take a while to parse.
These changes add some validations so that it's easier to figure out what's wrong.

fix(material/core): throw better error messages from typography utils

---

src/material/button-toggle/button-toggle.spec.ts
src/material/button-toggle/button-toggle.ts

The button toggle keeps track of the raw value to determine which option is preselected on init. The problem is that the raw value is never updated so if the user selects a different option, removes the preselected one and then re-adds it, the initial preselected option will become selected.
Fixes #27397.

fix(material/button-toggle): not preserving value if preselected option is removed

---

src/cdk/menu/event-detection.ts
src/cdk/menu/menu-item.ts
src/cdk/menu/menu-trigger.ts
tools/public_api_guard/cdk/menu.md

In #26296 I added a condition in the click handler for menu triggers and menu items to skip clicks dispatched by the keyboard so that they don't trigger the menu twice. The problem is that this also ends up ignoring the default keyboard shortcut that VoiceOver mentions should be used to trigger the menu (Control + Option + Space), because it ends up being dispatched as a plain `click` event and it doesn't trigger the `keydown` event at all.
These changes address the issue by removing the previous condition and inferring whether the event will trigger a click by looking at it and the element it's coming from.
Fixes #27376.

fix(cdk/menu): control + option + space not working on VoiceOver

---

src/material/chips/chip-set.spec.ts
src/material/chips/chip-set.ts

Fixes that the `empty` getter wasn't null checking the `chips` field and would throw an error if it is accessed before `ngAfterContentInit`.
Fixes #27404.

fix(material/chips): error if empty getter is accessed too early

---

src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html.template
src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template

Fixes that the table schematic was producing a template diagnostic for null checking a value that doesn't need to be null checked. Also removes an unnecessary constructor.
Fixes #27329.

fix(material/schematics): fix template diagnostic in table schematic

---

src/material/core/tokens/_token-utils.scss
src/material/core/tokens/m2/mat/_stepper.scss
src/material/stepper/_stepper-theme.scss
src/material/stepper/step-header.scss
src/material/stepper/stepper.scss

Reworks the stepper to use the tokens theming API.

refactor(material/stepper): switch to tokens API

---

src/components-examples/material/sidenav/index.ts
src/components-examples/material/sidenav/sidenav-configurable-focus-trap/sidenav-configurable-focus-trap-example.css
src/components-examples/material/sidenav/sidenav-configurable-focus-trap/sidenav-configurable-focus-trap-example.html
src/components-examples/material/sidenav/sidenav-configurable-focus-trap/sidenav-configurable-focus-trap-example.ts
src/material/sidenav/drawer.spec.ts
src/material/sidenav/drawer.ts

Correct when Sidenav enabled focus trapping. When backdrop is show, trap focus. Do no trap focus when backdrop is not shown.
Existing behavior is that Sidenav traps focus whenever it is not in side mode. This causes the end user to not be able to interact with the sidenav content when the mode is push/over, backdrop is disabled and using ConfigurableFocusTrapFactory (#26572).
With this commit applied, Sidenav always traps focus when backdrop is shown. Sidenav never traps focus when backdrop is not shown, regardless of what mode the sidenav is in, focus trapping will respect if the backdrop is shown or not shown.
Fix this issue by correcting boolean logic for detecting if backdrop is enabled and using that logic to determine when to trap focus. Add an example that injects …

fix(material/sidenav): only trap focus when backdrop is enabled

---

src/material/chips/chips.md

Update the accessibility section of chips component to adress editable chips. Require developer to communicate to AT how to edit a chip using a keyboard.
Relates to issue #27106.

docs(material/chips): require communicating to AT how to edit a chip

---

CHANGELOG.md

docs: release notes for the v16.1.4 release

---

.circleci/config.yml
src/material/legacy-dialog/testing/dialog-opener.ts
src/material/legacy-menu/menu.ts
src/material/legacy-table/text-column.ts
src/material/legacy-tabs/tab.ts
src/material/legacy-tooltip/tooltip.ts

Resolves all of the current component ID collisions and adds an automated CI check to prevent further ones from being introduced.
Fixes #27163.

Resolve component ID collisions

---

src/dev-app/theme-token-api.scss
src/material-experimental/_index.scss
src/material-experimental/theming/README.md
src/material-experimental/theming/_theming.scss
src/material/card/_card-theme.scss
src/material/checkbox/_checkbox-theme.scss

Rather than having a separate mixin for "retheming" we have a single mixin `matx.theme` that can either emit fallback token defaults or not depending on how its configured. Added `matx.token-defaults` which can be used to configure the fallbacks.

refactor(material-experimental/theming): condense matx.theme and matx.retheme into a single mixin

---

src/material/autocomplete/autocomplete-trigger.ts
src/material/autocomplete/autocomplete.spec.ts
src/material/core/option/option.ts
tools/public_api_guard/material/core.md

Fixes that the selected state was lingering on the selected option even after the input value is cleared.
Fixes #26761.

fix(material/autocomplete): clear selected option if input is cleared

---

src/material/autocomplete/autocomplete-trigger.ts
src/material/autocomplete/autocomplete.spec.ts

The autocomplete trigger attaches an overlay even if there are no options in the list. It also subscribes to keydown events and clicks while the panel is open which block events from reaching other overlays. This means that if the user focuses an autocomplete input with no options, the events from it won't reach other overlays.
These changes resolve the issue by subcribing and unsubscribing from the event streams depending on the visibility state of the panel.
Fixes #26479.

fix(material/autocomplete): blocking events to other overlays when there are no results

---

src/components-examples/material/autocomplete/autocomplete-require-selection/autocomplete-require-selection-example.css
src/components-examples/material/autocomplete/autocomplete-require-selection/autocomplete-require-selection-example.html
src/components-examples/material/autocomplete/autocomplete-require-selection/autocomplete-require-selection-example.ts
src/components-examples/material/autocomplete/index.ts
src/dev-app/autocomplete/autocomplete-demo.html
src/dev-app/autocomplete/autocomplete-demo.ts
src/material/autocomplete/autocomplete-trigger.ts
src/material/autocomplete/autocomplete.html
src/material/autocomplete/autocomplete.md
src/material/autocomplete/autocomplete.spec.ts
src/material/autocomplete/autocomplete.ts
src/material/legacy-autocomplete/autocomplete.ts
tools/public_api_guard/material/autocomplete.md
tools/public_api_guard/material/legacy-autocomplete.md

Adds the `requireSelection` input to the autocomplete, which when enabled will clear the input value if the user doesn't select an option from the list.
Fixes #3334.

feat(material/autocomplete): add input to require selection from the panel

---

src/material/menu/menu.md

Update a11y documentation for MatMenu. REquest that MatMenu should not contain interactive controls, aside from MatMenuItem.
Add clarification for the supported configurations of MatMenu. A common accessibility mistake is to nest interactive controls inside of a menu popup.
Addresses #27426

docs(material/menu): require only static content and MenuItems in popup

---

src/material/expansion/expansion-animations.ts

The expansion panel was setting `visibility: visible` on the content which meant that it would be visible when placed inside of a parent that is `visibility: hidden`.
These changes resolve the issue by clear the `visibility` instead.
Fixes #27436.

fix(material/expansion): panel content visible when placed inside a hidden parent

---

src/components-examples/material/slider/slider-configurable/slider-configurable-example.html

* Change the displayed value to be the current value of the slider instead of the value set by the user

docs(material/slider): make component example more intuitive

---

src/cdk/clipboard/pending-copy.ts
src/dev-app/clipboard/clipboard-demo.html

Fixes that the clipboard service didn't work when the page is fullscreen.
Fixes #27447.

fix(cdk/clipboard): not working inside fullscreen element

---

CHANGELOG.md

docs: release notes for the v16.1.5 release

---

src/material/chips/chip-row.ts

Fixes an issue that showed up in an internal app where the edit input query wasn't being evaluated on time which led to a runtime error.
Fixes #27462.

fix(material/chips): ensure that edit input query is re-evaluated on time

---

src/material/radio/radio.spec.ts
src/material/radio/radio.ts
tools/public_api_guard/material/radio.md

In  #18081 the radio group was changed so that deselected buttons receive `tabindex="-1"` when there's a selected button. The problem is that we weren't clearing the reference to the selected button so it gets removed, the deselected buttons become unfocusable using the keyboard.
These changes clear the selected radio button on destroy.
Fixes #27461.

fix(material/radio): clear selected radio button from group

---

src/material/slide-toggle/slide-toggle.scss

our label in slider doesn't contain cursor pointer style as we can still click on label and toggle slider
fixes #26490

fix(material/slide-toggle): add cursor pointer for label

---

src/material/chips/chip.scss

* avoids issues where chip ripple styles are overriden by mat-ripple styles

fix(material/chips): increase specificity of chip ripple selector

---

src/material-luxon-adapter/adapter/luxon-date-adapter.spec.ts
src/material-luxon-adapter/adapter/luxon-date-adapter.ts

Add defaultOutputCalendar option to be able to change default calndar through MAT_LUXON_DATE_ADAPTER_OPTIONS

feat(material-luxon-adapter): add option to set default calendar

---

guides/creating-a-custom-form-field-control.md

Resolves #23387.
I'm not sure if we should also mention the  [`ErrorStateMatcher`](https://github.com/angular/components/blob/main/src/material/core/error/error-options.ts#L22) in the guide, as it might be too much information for some users. What do you think? :)

docs(material/form-field): add guide for handling unsubscribable error triggers in custom form field control

---

src/material/chips/chip-grid.spec.ts
src/material/datepicker/date-range-input.spec.ts
src/material/form-field/form-field.html
src/material/input/input.spec.ts

Fix duplicate screen reader announcement of form controls.
Remove the aria-owns from the form label. Commit
https://github.com/zarend/components/commit/4191b4d66e4dc79fc1dfa446caf48e5d3224d4fa added aria-owns on the label to
work around issue in JAWS and NVDA. That commit is from 2017, and it
appears the JAWS and NVDA issues have been fixed.
Tested on NVDA, JAWS and VoiceOver by verifying that I am able to read
the form field's label using screen reader. Tested on both Windows and
Firefox.
Testing environment:
- Windows 10 Enterprise Version 22H2
- Chrome Version 114.0.5735.199 (Official Build) (64-bit)
- Firefox 115.0 (64-bit)
- NVDA version 2022.3
- JAWS Verison 2020.2006.12 ILM
- MacOS 13.4.1 (22F82)
- VoiceOver
- Chrome Version 114.0.5735.198 (Official Build) (arm64)
- Firefox Version …

fix(material/form-field): fix duplicate announcement of form controls

---

src/cdk/testing/testbed/fake-events/type-in-element.ts
src/cdk/testing/tests/cross-environment.spec.ts
src/cdk/testing/tests/harnesses/main-component-harness.ts
src/cdk/testing/tests/test-main-component.ts
src/material/chips/testing/BUILD.bazel
src/material/chips/testing/chip-input-harness.spec.ts

Fixes that the `TestElement.sendKeys` was triggering a keyboard event with the wrong `keyCode` for commas, because a comma has a different `keyCode` than its `charCode`.

fix(cdk/testing): sending incorrect keyCode for comma

---

src/cdk/testing/testbed/fake-events/type-in-element.ts
src/cdk/testing/tests/cross-environment.spec.ts
src/cdk/testing/tests/harnesses/main-component-harness.ts
src/cdk/testing/tests/test-main-component.ts
src/material/chips/testing/BUILD.bazel
src/material/chips/testing/chip-input-harness.spec.ts

This reverts commit 8250a0df0462634b3e2a8b6ef4783dc2a9b45820.

Revert "fix(cdk/testing): sending incorrect keyCode for comma (#27472)"

---

src/cdk/testing/protractor/protractor-element.ts
src/cdk/testing/selenium-webdriver/selenium-webdriver-keys.ts
src/cdk/testing/test-element.ts
src/cdk/testing/testbed/unit-test-element.ts
src/material/chips/testing/BUILD.bazel
src/material/chips/testing/chip-input-harness.spec.ts
tools/public_api_guard/cdk/testing.md

Adds a comma key to `TestKey` since commas aren't treated correctly in strings sent through `sendKeys` and it's common for them to be used as separators in chip lists.

fix(cdk/testing): allow for comma key to be sent

---

src/material/menu/menu-item.html
src/material/menu/menu-item.ts
src/material/menu/menu.html
src/material/menu/menu.scss

After #27377 and #27378 we no longer use MDC classes directly in the markup. Instead we either use our own styles or we target our selectors with MDC mixins. However, the MDC classes were left in to reduce the amount of internal breakages. These leftover styles can still cause styles to bleed in from the MDC list so this change removes any remaining references.

refactor(material/menu): remove MDC classes from markup

---

.circleci/config.yml
.github/workflows/ci.yml

Migrate api golden test to Github Actions

ci: migrate api golden check to GHA

---

src/cdk/listbox/listbox.ts
tools/public_api_guard/cdk/listbox.md

The `activeItemIndex` property of the cdk/listbox component tracks which item in the listbox is currently active or focused. However, some browsers (e.g. Chrome and Firefox) trigger the `focusout` event when the user switches tabs and returns, and set `event.relatedTarget` to null. This causes the `activeItemIndex` to be out of sync with the actual focused element, leading to incorrect behavior and user confusion. To fix this, we use `document.activeElement` as a fallback for `event.relatedTarget`, and update the `activeItemIndex` accordingly.
Fixes #27474.

fix(cdk/listbox): prevent wrong activeItemIndex after browser tab switch

---

CHANGELOG.md

docs: release notes for the v16.1.6 release

---

src/cdk/dialog/dialog-ref.ts
src/cdk/dialog/dialog.spec.ts
src/cdk/dialog/dialog.ts
src/material/bottom-sheet/bottom-sheet-ref.ts
src/material/bottom-sheet/bottom-sheet.spec.ts
src/material/dialog/dialog-ref.ts
src/material/dialog/dialog.spec.ts
src/material/dialog/dialog.ts
tools/public_api_guard/cdk/dialog.md
tools/public_api_guard/material/bottom-sheet.md
tools/public_api_guard/material/dialog.md

Exposes then `ComponentRef` of the components rendered inside the CDK dialog, Material dialog and bottom sheet. Previously we didn't do it, because there wasn't much the user could do with the `ComponentRef`, but as of recently they're able to set the component's inputs which can be useful.
Fixes #27534.

Expose ComponentRef to dialog components

---

src/material/core/tokens/m2/mat/_slide-toggle.scss
src/material/core/tokens/m2/mat/_tab-header.scss
src/material/slide-toggle/slide-toggle.scss
src/material/tabs/_tabs-common.scss

Renames a couple of tokens that were using "letter spacing" instead of "tracking" in order to align them with the rest of the library.

refactor(multiple): align letter spacing terminology

---

CHANGELOG.md

docs: release notes for the v16.1.7 release

---

src/components-examples/material/autocomplete/autocomplete-require-selection/autocomplete-require-selection-example.css
src/components-examples/material/autocomplete/autocomplete-require-selection/autocomplete-require-selection-example.html
src/components-examples/material/autocomplete/autocomplete-require-selection/autocomplete-require-selection-example.ts
src/dev-app/autocomplete/autocomplete-demo.html
src/dev-app/autocomplete/autocomplete-demo.ts
src/material/autocomplete/autocomplete-trigger.ts
src/material/autocomplete/autocomplete.spec.ts

Follow-up to #27423 based on the feedback. Usually `mat-autocomplete` assigns to the model as the user is typing which may not be desired when `requireSelection` is enabled, because at the end of the selection either an option value will set or it'll be reset.
These changes add a condition so that the value isn't assigned while typing and `requireSelection` is enabled.

fix(material/autocomplete): don't assign to model value while typing when requireSelection is enabled

---

src/material/chips/chip-option.ts

Fixes an issue in Safari where clicking on a chip ends up leaving focus on the previously-selected chip.
Fixes #27544.

fix(material/chips): focus lingering on previous chip

---

src/material/slider/slider-input.ts
src/material/slider/slider-interface.ts
src/material/slider/slider-thumb.ts
src/material/slider/slider.spec.ts
src/material/slider/slider.ts
tools/public_api_guard/material/slider.md

* On IOS, the slider is only draggable if the pointer event happens directly on the slider thumb
* On IOS, the slider never receives focus from pointer events

fix(material/slider): match active & focus state on IOS

---

src/material/_index.scss
src/material/checkbox/_checkbox-theme.scss
src/material/checkbox/checkbox.scss

There are new styles emitted by `mat.checkbox-theme` that are not
emitted by any of: `mat.checkbox-color`, `mat.checkbox-typography`,
`mat.checkbox-density`. If you rely on the partial mixins only and don't
call `mat.checkbox-theme`, you can add `mat.checkbox-base` to get the

fix(material/checkbox): Move unthemable tokens to theme mixin

---

src/material/_index.scss
src/material/progress-bar/_progress-bar-theme.scss
src/material/progress-bar/progress-bar.scss

There are new styles emitted by mat.progress-bar-theme that are not
emitted by any of: mat.progress-bar-color, mat.progress-bar-typography,
mat.progress-bar-density. If you rely on the partial mixins only and don't
call mat.progress-bar-theme, you can add mat.progress-bar-base to get the

fix(material/progress-bar): Move unthemable tokens to theme mixin

---

src/material/_index.scss
src/material/tooltip/_tooltip-theme.scss
src/material/tooltip/tooltip.scss

There are new styles emitted by mat.tooltip-theme that are not
emitted by any of: mat.tooltip-color, mat.tooltip-typography,
mat.tooltip-density. If you rely on the partial mixins only and don't
call mat.tooltip-theme, you can add mat.tooltip-base to get the

fix(material/tooltip): Move unthemable tokens to theme mixin

---

src/material/_index.scss
src/material/progress-spinner/_progress-spinner-theme.scss
src/material/progress-spinner/progress-spinner.scss

There are new styles emitted by mat.progress-spinner-theme that are not
emitted by any of: mat.progress-spinner-color, mat.progress-spinner-typography,
mat.progress-spinner-density. If you rely on the partial mixins only and don't
call mat.progress-spinner-theme, you can add mat.progress-spinner-base to get the

fix(material/progress-spinner): Move unthemable tokens to theme mixin

---

src/material/_index.scss
src/material/card/_card-theme.scss
src/material/card/card.scss

There are new styles emitted by `mat.card-theme` that are not emitted by any of: `mat.card-color`, `mat.card-typography`, `mat.card-density`. If you rely on the partial mixins only and don't call `mat.card-theme`, you can add `mat.card-base` to get the missing styles.

fix(material/card): Move unthemable tokens to theme mixin

---

src/dev-app/youtube-player/youtube-player-demo.html
src/dev-app/youtube-player/youtube-player-demo.ts
src/youtube-player/youtube-player.spec.ts
src/youtube-player/youtube-player.ts

When using a YouTube Player, it is possible to specify a playlist without specifying a videoId. This is useful when you want to play a playlist and don't have a VideoId.
Previously, the player would not initialise if a VideoId wasn't specified but a Playlist was specified, even though the YouTube API supports this use case.
This commit adds support for this use case.
Fix #27529

fix(youtube-player): Allow playlists without specifying videoId (#27529)

---

src/material/core/tokens/m2/mat/_form-field.scss
src/material/core/tokens/m2/mdc/_filled-text-field.scss
src/material/core/tokens/m2/mdc/_outlined-text-field.scss
src/material/form-field/_form-field-subscript.scss
src/material/form-field/_form-field-theme.scss
src/material/form-field/form-field.scss

Switches our custom typography styles on top of MDC to use tokens.

refactor(material/form-field): switch custom typography styles to tokens

---

src/material/card/_card-theme.scss

Applies card tokens at the theme mixin's root selector (or html if the mixin is called with no selector). This makes it easier for users to override tokens without worrying about specificity.

fix(material/card): Apply tokens at mixin root

---

src/material/_index.scss
src/material/slider/_slider-theme.scss
src/material/slider/slider.scss

There are new styles emitted by `mat.slider-theme` that are not emitted by any of: `mat.slider-color`, `mat.slider-typography`, `mat.slider-density`. If you rely on the partial mixins only and don't call `mat.slider-theme`, you can add `mat.slider-base` to get the missing styles.

fix(material/slider): Move unthemable tokens to theme mixin

---

CHANGELOG.md

docs: release notes for the v16.1.8 release

---

src/cdk/a11y/a11y.md
src/cdk/a11y/key-manager/tree-key-manager.spec.ts
src/cdk/a11y/key-manager/tree-key-manager.ts
src/cdk/tree/nested-node.ts
src/cdk/tree/tree-errors.ts
src/cdk/tree/tree.md
src/cdk/tree/tree.ts
src/components-examples/cdk/tree/BUILD.bazel
src/components-examples/cdk/tree/cdk-tree-complex/cdk-tree-complex-example.css
src/components-examples/cdk/tree/cdk-tree-complex/cdk-tree-complex-example.html
src/components-examples/cdk/tree/cdk-tree-complex/cdk-tree-complex-example.ts
src/components-examples/cdk/tree/cdk-tree-flat-children-accessor/cdk-tree-flat-children-accessor-example.html
src/components-examples/cdk/tree/cdk-tree-flat-level-accessor/cdk-tree-flat-level-accessor-example.html
src/components-examples/cdk/tree/cdk-tree-nested-level-accessor/cdk-tree-nested-level-accessor-example.html
src/components-examples/cdk/tree/cdk-tree-nested/cdk-tree-nested-example.html
src/components-examples/cdk/tree/index.ts
src/components-examples/material/tree/tree-nested-overview/tree-nested-overview-example.html
src/dev-app/tree/tree-demo.html
src/dev-app/tree/tree-demo.ts
src/material/tree/tree.md
src/material/tree/tree.ts
tools/public_api_guard/cdk/a11y.md
tools/public_api_guard/cdk/tree.md

feat(cdk/tree): general bug fixes, error handling, updating examples & docs

---

src/material/table/row.ts
src/material/table/table.ts

The Material table had a few places where it was importing a component's template as a string. This is incompatible with the upcoming local compilation mode in the compiler. These changes inline the templates instead.

fix(material/table): resolve local compilation issues

---

src/material/_index.scss
src/material/snack-bar/_snack-bar-theme.scss
src/material/snack-bar/snack-bar-container.scss

There are new styles emitted by `mat.snack-bar-theme` that are not emitted by any of: `mat.snack-bar-color`, `mat.snack-bar-typography`, `mat.snack-bar-density`. If you rely on the partial mixins only and don't call `mat.snack-bar-theme`, you can add `mat.snack-bar-base` to get the missing styles.

fix(material/snack-bar): Move unthemable tokens to theme mixin

---

src/material/progress-bar/progress-bar.scss

Fixes that the progress bar's alignment was affected by the parent's element's `text-align`.
Fixes #27613.

fix(material/progress-bar): alignment affected by parent text-align

---

src/dev-app/autocomplete/autocomplete-demo.html
src/dev-app/autocomplete/autocomplete-demo.ts

Make a bug fix to the template-driven autocomplete example. Fix demo issue where clicking the reset button doesn't reset the autocomplete options and the value in the input to the original state. Reset the form field by resetting the value of the input and the tdStates to the value when the demo is first rendered.

docs(material/autocomplete): reset template driven autocomplete example

---

src/components-examples/cdk/tree/cdk-tree-flat-children-accessor/cdk-tree-flat-children-accessor-example.html
src/components-examples/cdk/tree/cdk-tree-flat-level-accessor/cdk-tree-flat-level-accessor-example.html
src/components-examples/cdk/tree/cdk-tree-nested-level-accessor/cdk-tree-nested-level-accessor-example.html
src/components-examples/cdk/tree/cdk-tree-nested-level-accessor/cdk-tree-nested-level-accessor-example.ts

Fix an issue in the tree demos where the keyboard can navigate to nodes that are not rendered to the screen. This happend because nodes where hidden using CSS and the TreeKeyManager did not know to skip over them. Fix this issue by disabled nodes that are hidden so that the TreeKeyManager will skip them.
Steps to reproduce issue
1. Go to CDK Flat tree (levelAccessor) demo
2. Tab onto Fruit
3. Press down the up
4. (Expands the collapses)
5. Press down
6. (Expecting Vegetables to be focused but focus ring is still around Fruit)
7. Press down five times.
8. (Focus ring is around Fruit).
With this commit applied, above issue no longer reproduces.
This commit message is only for code reviewers and can be deleted when landing this change in main.

docs(material/tree): fix demos where keyboard navigates to hidden nodes

---

CHANGELOG.md

docs: release notes for the v16.2.1 release

---

src/material/select/select.scss

Fixes that only some parts of the form field had `cursor: pointer` when a `mat-select` is projected.
Fixes #27655.

fix(material/select): set pointer cursor on entire form field

---

src/material/snack-bar/snack-bar.md

fixes broken annotated custom component example
fixes #27679
---
Before:
After:

docs(material/snack-bar): fix broken doc example

---

src/cdk/dialog/dialog-container.ts
src/cdk/dialog/dialog-injectors.ts
src/cdk/dialog/dialog-module.ts
src/cdk/dialog/dialog.ts
tools/public_api_guard/cdk/dialog.md

Reworks the CDK dialog to use a standalone component and to use `providedIn: 'root'` for its providers.

refactor(cdk/dialog): changes to accommodate standalone

---

src/cdk/table/table.spec.ts
src/cdk/table/table.ts

fix(cdk/table): the CdkNoDataRow directive does not render in the OnPush strategy
Fixes a bug in the Angular CDK `table` component where the CdkNoDataRow directive with binding data is not rendered correctly when the parent component has the OnPush strategy set

fix(cdk/table): the CdkNoDataRow directive does not render in the OnPush strategy

---

src/cdk/tree/BUILD.bazel
src/cdk/tree/toggle.ts
src/cdk/tree/tree-redesign.spec.ts
src/components-examples/cdk/tree/cdk-tree-flat-children-accessor/cdk-tree-flat-children-accessor-example.html
src/components-examples/cdk/tree/cdk-tree-flat-level-accessor/cdk-tree-flat-level-accessor-example.html
src/components-examples/cdk/tree/cdk-tree-flat/cdk-tree-flat-example.html
src/components-examples/cdk/tree/cdk-tree-nested-level-accessor/cdk-tree-nested-level-accessor-example.html
src/components-examples/cdk/tree/cdk-tree-nested/cdk-tree-nested-example.html
src/components-examples/material/tree/tree-dynamic/tree-dynamic-example.html
src/components-examples/material/tree/tree-flat-overview/tree-flat-overview-example.html
src/components-examples/material/tree/tree-harness/tree-harness-example.html
src/components-examples/material/tree/tree-loadmore/tree-loadmore-example.html
src/components-examples/material/tree/tree-nested-overview/tree-nested-overview-example.html
tools/public_api_guard/cdk/tree.md

Implement keydown event for CdkTreeNodeToggle to perform that same action as click when receiving Enter or Space. Update examples to expand/collapse nodes when pressing enter.
Fix a11y issue in demos where pressing Enter when focused on a tree node seems to not perform any action. Use CdkTreeNodeToggle to perform the action of expanding or collaping the node.
Align with instructions in [APG Tree View
Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/treeview/):
"Enter: activates a node, i.e., performs its default action. For parent nodes, one possible default action is to open or close the node. In single-select trees where selection does not follow focus (see note below), the default action is typically to select the focused node."

fix(cdk/tree): CdkTreeNodeToggle responds to Enter and Space keys

---

src/material/_index.scss
src/material/dialog/_dialog-theme.scss
src/material/dialog/dialog.scss

There are new styles emitted by `mat.dialog-theme` that are not emitted by any of: `mat.dialog-color`, `mat.dialog-typography`, `mat.dialog-density`. If you rely on the partial mixins only and don't call `mat.dialog-theme`, you can add `mat.dialog-base` to get the missing styles.

fix(material/dialog): Move unthemable tokens to theme mixin

---

.stylelintrc.json
src/dev-app/theme.scss
src/material/card/_card-theme.scss
src/material/checkbox/_checkbox-theme.scss
src/material/core/_core-theme.scss
src/material/core/option/_optgroup-theme.scss
src/material/core/option/_option-theme.scss
src/material/core/ripple/_ripple-theme.scss
src/material/core/selection/pseudo-checkbox/_pseudo-checkbox-theme.scss
src/material/core/style/_private.scss
src/material/core/style/_sass-utils.scss
src/material/core/theming/_m2-inspection.scss
src/material/core/theming/_theming.scss
src/material/core/theming/tests/test-css-variables-theme.scss
src/material/core/tokens/m2/mat/_card.scss
src/material/core/tokens/m2/mat/_form-field.scss
src/material/core/tokens/m2/mat/_optgroup.scss
src/material/core/tokens/m2/mat/_option.scss
src/material/core/tokens/m2/mdc/_elevated-card.scss
src/material/core/tokens/m2/mdc/_filled-text-field.scss
src/material/core/tokens/m2/mdc/_linear-progress.scss
src/material/core/tokens/m2/mdc/_outlined-card.scss
src/material/core/tokens/m2/mdc/_outlined-text-field.scss
src/material/form-field/_form-field-density.scss
src/material/form-field/_form-field-theme.scss
src/material/progress-bar/_progress-bar-theme.scss

Converts the following components to use the new theme inspection API
under the hood: card, core, form-field, optgroup, option, progress-bar,
pseudo-checkbox, ripple
As a side effect, this allows us to start cleaning up all of the
theme normalization logic that previously had to be baked into every
theme mixin.
The goal once all components are converted is that apps can opt
themselves into only supporting the inspection API to access theme
values and throw errors on all attempts to access the theme via other
means. This will identify usages of the theme that need to be updated to
work with M3.

refactor(multiple): convert components to theme inspection API 

---

src/material/button/button-base.ts
src/material/button/button.ts
src/material/button/fab.ts
src/material/button/icon-button.ts
src/material/button/testing/BUILD.bazel
src/material/button/testing/button-harness.ts
tools/public_api_guard/material/button.md

Reworks the button to replace usages of mixin classes with either input transforms or host bindings. This is a test to see how breaking the approach is before we roll it out across the entire library.

refactor(material/button): remove mixin class usages

---

src/components-examples/material/tree/tree-loadmore/tree-loadmore-example.html
src/components-examples/material/tree/tree-loadmore/tree-loadmore-example.ts

Fix keyboard navigation issues with the "Load more flat tree" demo.
- "Load more" button will respond to Enter or Space keys
- Expanding and collapsing using keyboard shortcuts will trigger loading.

docs(material/tree): fix keyboard issues with "Load more flat tree"

---

src/cdk/tree/toggle.ts
src/cdk/tree/tree-redesign.spec.ts

Fix focus behavior of CdkTreeNodeToggle. When toggling the expanded or collapsed state of a node, focus that node. Fix issue where end user cannot tab into tree component when collaping the parent of the active node.
Before this commit is applied, there is a bug where end user cannot tab into the tree.
Reproduction steps
1. Active a tree node
2. (focus state renders)
3. Using mouse, collapse parent of node from step 1.
4. (tree node collapses)
5. Press Tab, then shift + tab
6. (item before tree is focused. Can tab into the tree)
With this commit applied, above issue is no longer expected to reproduce.
This commit message is only for reviewers of this PR and can be deleted when landing this change in main.

fix(cdk/tree): CdkTreeNodeToggle focuses node when toggling it

---

CHANGELOG.md

docs: release notes for the v16.2.2 release

---

src/dev-app/drag-drop/drag-drop-demo.ts
src/dev-app/slider/slider-demo.ts
src/material/autocomplete/autocomplete-trigger.ts
src/material/autocomplete/autocomplete.ts
src/material/badge/BUILD.bazel
src/material/badge/badge.ts
src/material/button-toggle/BUILD.bazel
src/material/button-toggle/button-toggle.ts
src/material/checkbox/BUILD.bazel
src/material/checkbox/checkbox.html
src/material/checkbox/checkbox.ts
src/material/core/option/optgroup.ts
src/material/core/option/option.ts
src/material/menu/menu-item.ts
src/material/menu/menu.ts
src/material/slide-toggle/BUILD.bazel
src/material/slide-toggle/slide-toggle.html
src/material/slide-toggle/slide-toggle.ts
tools/public_api_guard/material/autocomplete.md
tools/public_api_guard/material/badge.md
tools/public_api_guard/material/button-toggle.md
tools/public_api_guard/material/checkbox.md
tools/public_api_guard/material/core.md
tools/public_api_guard/material/menu.md
tools/public_api_guard/material/slide-toggle.md
tslint.json

Reworks some of the components not to use mixin classes anymore. I'll be sending PRs like this to tackle mixins in batches to reduce the amount of breakages during TGP. Includes changes in the following components:
* Checkbox
* Autocomplete
* Badge
* Button toggle
* Option and option group
* Menu
* Slide toggle

Remove mixin usages from a handful of components

---

src/material/tabs/tab-group.html
src/material/tabs/tab-group.spec.ts

Make accessibility fix for Tabs component. Add `aria-hidden="true"` to inactive tab panels. Fix issue where chromevox would read the names of inactive tab panels when navigating past the active tab panel (#27741). Fix this by adding `aria-hidden="true"` to inactive tab panels to exclude them from the a11y tree.
I believe what was happening is that the inactive tab panels had an aria-labelled by references that pointed to the tab header. Existing behavior seems to be that Chromevox was following the aria-labelledby references and announcing the labels of the inactive tabs. With this commit applied, Chromevox no longer reads panels of inactive tabs.
Fix #27741

fix(material/tabs): add aria-hidden to inactive tabs

---

src/cdk/menu/menu-trigger.ts

Fixes an issue where menu triggers placed inside components using OnPush change detection would not have their `aria-expanded` property updated correctly when switching between sibling triggers.
Fixes #27725

fix(cdk/menu): run change detection for  changes to overlay ref of trigger

---

src/material/dialog/_mdc-dialog-structure-overrides.scss
src/material/dialog/dialog-container.ts
src/material/dialog/dialog.ts
tools/public_api_guard/material/dialog.md

* change the css structure of the dialog surface and it's children

fix(material/dialog): css structure change

---

src/material/core/testing/option-harness.ts
tools/public_api_guard/material/core-testing.md

This allows users to obtain harnesses for more complex elements inside of the `MatOption`. The current `MatOptionHarness` offers only `getText()`, which is limiting with rich content in the MatOption. [Example from MatAutocomplete documentation](https://material.angular.io/components/autocomplete/examples#autocomplete-overview) where rich content is even encouraged.

feat(MatOptionHarness): make MatOptionHarness extend ContentContainerComponentHarness

---

CHANGELOG.md

docs: release notes for the v16.2.3 release

---

src/material/input/input.md

The mat-error can only rendered if the input has touched and the input is invalid. The "either" term in the explanation may be confusing and lead to the assumption that the mat-error is rendered if it has a touch or an invalid status.

fix(doc): mat-error can only rendered if the input has touched and is invalid state

---

src/material/autocomplete/autocomplete-trigger.ts
src/material/autocomplete/autocomplete.spec.ts

The autocomplete has a check not to reset the value if the user didn't interact with the input. The problem was that we only accounted for it when there are options, because while technically an autocomplete is _attached_ when the user focuses, we don't consider it _open_ until it shows some options.
Fixes #27767.

fix(material/autocomplete): requireSelection incorrectly resetting value when there are no options

---

src/cdk/schematics/update-tool/component-resource-collector.ts

Updates the `ComponentResourceCollector` to account for the new changes in v17 where `@Component.styles` can be a single string and there's a new `@Component.styleUrl` property.

fix(cdk/schematics): account for single string in styles and new styleUrl

---

src/cdk/scrolling/virtual-scroll-viewport.ts

Initially the virtual scroll viewport was written under the assumption that it is the scrollable and that it doesn't need to unsubscribe from its `elementScrolled` stream, because it'll be completed on destroy. This might not be the case if a `CdkVirtualScrollableElement` is provided and the viewport might be destroyed without the scrollable being destroyed.
These changes add a `takeUntil` to avoid any potential leaks.
Fixes #27799.

fix(cdk/scrolling): unsubscribe from scrolled stream when viewport is destroyed

---

src/material/form-field/_mdc-text-field-structure-overrides.scss

fix(material/form-field): style the cursor the same way as the rest of the input

---

.github/workflows/build-dev-app.yml
.github/workflows/deploy-dev-app.yml

We renamed the preview deploy folder in dev-infra but looks like the workflow was never updated to reflect this.

ci: fix preview deploys not working due to folder rename

---

CHANGELOG.md

docs: release notes for the v16.2.5 release

---

src/material/_index.scss
src/material/radio/_radio-theme.scss
src/material/radio/radio.scss

Though these tokens are not currently affected by the theme, in the
future they will be affected by the design system used for theming (M2
or M3)
There are new styles emitted by `mat.radio-theme` that are not
emitted by any of: `mat.radio-color`, `mat.radio-typography`,
`mat.radio-density`. If you rely on the partial mixins only and don't
call `mat.radio-theme`, you can add `mat.radio-base` to get the

fix(material/radio): move unthemable tokens to theme mixin

---

src/material/card/_card-theme.scss

This is no longer needed now that everything is using the new theme inspection APIs

refactor(material/card): remove legacy theme normalization

---

src/cdk/menu/context-menu-trigger.ts

Works around a browser inconsistency that was causing the context menu to close immediately when it is opened with control + left click on Safari.
Fixes #27832.

fix(cdk/menu): context menu closing immediately on control + click on Safari

---

src/material/datepicker/datepicker-errors.ts

The error message for missing dateAdapter was missing `MatDateFnsModule` and `MatLuxonDateModule` this pr updates the error message to include these modules

fix: improved missing dateAdapters error message to include matLuxon and matDateFns

---

src/material/slider/slider.md

Clarifies possible behavior/values of matStartThumb and matEndThumb in slider component 'Selecting a range' documentation.
Addresses #27837

docs(material/slider): clarify behavior of slider range thumbs

---

CHANGELOG.md

docs: release notes for the v16.2.6 release

---

src/material/dialog/dialog-container.ts
src/material/dialog/dialog-content-directives.ts
src/material/dialog/dialog.ts
src/material/dialog/module.ts
tools/public_api_guard/material/dialog.md

Reworks `MatDialog` to support standalone.

feat(material/dialog): switch to standalone

---

src/material/tabs/tab-nav-bar/tab-nav-bar.spec.ts
src/material/tabs/tab-nav-bar/tab-nav-bar.ts

Fixes that the tab nav bar wasn't navigating when pressing the enter key.
Fixes #27843.

fix(material/tabs): nav bar not navigating on enter presses

---

.github/workflows/ci.yml

Setup the slack messages for failed integration tests on releasable branchces

ci: setup slack messages for integration test

---

src/material/list/_list-theme.scss
src/material/radio/_radio-theme.scss

Applies radio tokens at the theme mixin's root selector (or html if the mixin is called with no selector). This makes it easier for users to override tokens without worrying about specificity.

fix(material/radio): Apply tokens at mixin root

---

src/material-experimental/column-resize/_column-resize-theme.scss
src/material-experimental/popover-edit/_popover-edit-theme.scss
src/material/_index.scss
src/material/core/theming/tests/theming-inspection-api.spec.ts

This PR opens up the following Sass APIs used to access theme values:
- `get-theme-version`: Gets the version of the theme object
- `get-theme-type`: Gets the type of theme (light or dark)
- `get-theme-color`: Gets a color from the theme
- `get-theme-typography`: Gets a typography value from the theme
- `get-theme-density`: Gets the density scale from the theme
- `theme-has`: Checks if the theme has information for the given theming system

feat(material/theming): Open up new APIs to access theme values

---

src/cdk/schematics/utils/project-index-file.ts
src/cdk/schematics/utils/project-main-file.ts
src/cdk/schematics/utils/project-targets.ts
src/material/schematics/ng-add/index.spec.ts
src/material/schematics/ng-add/theming/theming.ts

In #27792 the schematics were updated to use the new default `application` builder instead of the `browser` builder. According to the CLI team we'll have to support both so these changes update our existing logic to account for both cases.

fix(cdk/schematics): support both application and browser builders

---

CHANGELOG.md

docs: release notes for the v16.2.7 release

---

src/material/_index.scss
src/material/autocomplete/_autocomplete-theme.scss
src/material/badge/_badge-theme.scss
src/material/core/option/_optgroup-theme.scss
src/material/core/option/_option-theme.scss
src/material/datepicker/_datepicker-theme.scss
src/material/grid-list/_grid-list-theme.scss
src/material/icon/_icon-theme.scss
src/material/input/_input-theme.scss
src/material/paginator/_paginator-theme.scss
src/material/select/_select-theme.scss
src/material/stepper/_stepper-theme.scss
src/material/toolbar/_toolbar-theme.scss

This ensures API consistency and gives us a place to put base tokens, should any be added in the future.

refactor(multiple): Add base mixin for components with no base tokens

---

src/material/core/style/_sass-utils.scss
src/material/core/theming/tests/theming-mixin-api.spec.ts

There was a sublte bug in the previous implementation. Consider the case:
```scss
div {
@include current-selector-or-root() {
color: red;
}
color: green;
}
```
The previous implementation lifted the `color: red;` into a separate selector block that came *after* the initial one, resulting in the order being flipped:
```css
div {
color: green;
}
div {
color: red;
}
```
The new code will produce the correct ordering:
```css
div {
color: red;
color: green;
}
```

fix(material/theming): Fix subtle bug in current-selector-or-root

---

src/material/_index.scss
src/material/menu/_menu-theme.scss
src/material/menu/menu.scss

There are new styles emitted by mat.menu-theme that are not emitted by any of: mat.menu-color, mat.menu-typography, mat.menu-density. If you rely on the partial mixins only and don't call mat.menu-theme, you can add mat.menu-base to get the missing styles.

fix(material/menu): move unthemable tokens to theme mixin

---

src/material/_index.scss
src/material/sidenav/_sidenav-theme.scss
src/material/sidenav/drawer.scss

There are new styles emitted by mat.sidenav-theme that are not emitted by any of: mat.sidenav-color, mat.sidenav-typography, mat.sidenav-density. If you rely on the partial mixins only and don't call mat.sidenav-theme, you can add mat.sidenav-base to get the missing styles.

fix(material/sidenav): move unthemable tokens to theme mixin

---

src/material/_index.scss
src/material/table/_table-theme.scss
src/material/table/table.scss

There are new styles emitted by mat.table-theme that are not emitted by any of: mat.table-color, mat.table-typography, mat.table-density. If you rely on the partial mixins only and don't call mat.table-theme, you can add mat.table-base to get the missing styles.

fix(material/table): move unthemable tokens to theme mixin

---

src/material/_index.scss
src/material/bottom-sheet/_bottom-sheet-theme.scss
src/material/bottom-sheet/bottom-sheet-container.scss

There are new styles emitted by mat.bottom-sheet-theme that are not emitted by any of: mat.bottom-sheet-color, mat.bottom-sheet-typography, mat.bottom-sheet-density. If you rely on the partial mixins only and don't call mat.bottom-sheet-theme, you can add mat.bottom-sheet-base to get the missing styles.

fix(material/bottom-sheet): move unthemable tokens to theme mixin

---

src/components-examples/material/form-field/form-field-custom-control/example-tel-input-example.css

In the Form Field docs, there is an example how to create a custom control. In this example, the inputs of the custom control don't inherit the text color from the form field. In light mode, this is just fine. But when switching to a dark mode theme, the color of the inputs default to the browser default (black):
It should inherit the color from the form field, which is fixed by this PR.

docs(material/form-field): use correct input color in custom control example

---

src/components-examples/material/toolbar/toolbar-overview/toolbar-overview-example.html

Fixes the indentation of the toolbars' Overview example code.

docs(material/toolbar): fix indentation in example

---

src/material/_index.scss
src/material/chips/_chips-theme.scss
src/material/chips/chip.scss

There are new styles emitted by mat.chips-theme that are not emitted by any of: mat.chips-color, mat.chips-typography, mat.chips-density. If you rely on the partial mixins only and don't call mat.chips-theme, you can add mat.chips-base to get the missing styles.

fix(material/chips): move unthemable tokens to theme mixin

---

.circleci/config.yml
.github/angular-robot.yml
.github/workflows/ci-privileged.yml
scripts/saucelabs/start-tunnel.sh
test/karma.conf.js

Move Browserstack and Saucelabs testing from CircleCI to GHA
In testing I found no appreciable difference between different runner sizes and opted to use the free tier, we can revisit if we identify issues in the future.

ci: migrate saucelabs and browserstack tests to GHA

---

.circleci/config.yml
.github/angular-robot.yml
.github/workflows/ci.yml

Migrate browser tests to Github Actions

ci: migrate browser tests to GHA

---

src/material/_index.scss
src/material/tabs/_tabs-common.scss
src/material/tabs/_tabs-theme.scss

There are new styles emitted by mat.tabs-theme that are not emitted by any of: mat.tabs-color, mat.tabs-typography, mat.tabs-density. If you rely on the partial mixins only and don't call mat.tabs-theme, you can add mat.tabs-base to get the missing styles.

fix(material/tabs): move unthemable tokens to theme mixin

---

src/material/_index.scss
src/material/button-toggle/_button-toggle-theme.scss
src/material/button-toggle/button-toggle.scss

There are new styles emitted by mat.button-toggle-theme that are not emitted by any of: mat.button-toggle-color, mat.button-toggle-typography, mat.button-toggle-density. If you rely on the partial mixins only and don't call mat.button-toggle-theme, you can add mat.button-toggle-base to get the missing styles.

fix(material/button-toggle): move unthemable tokens to theme mixin

---

src/cdk/a11y/key-manager/tree-key-manager.spec.ts
src/cdk/a11y/key-manager/tree-key-manager.ts
src/cdk/tree/tree.spec.ts
src/cdk/tree/tree.ts
src/components-examples/material/tree/tree-loadmore/tree-loadmore-example.html
src/components-examples/material/tree/tree-loadmore/tree-loadmore-example.ts
tools/public_api_guard/cdk/a11y.md

[fix(cdk/tree): update active item on focus](https://github.com/angular/components/pull/27908/commits/1c0149354a31f70626f3b0d4718fef6dd806f8b9) 
Update CdkTreeNode, TreeKeyManager and Tree "Load More" example
regarding progrmatic focus.
- In CdkTreeNode, update the active item on the focus event.
- expose TreeKeyManager.updateActiveItem
- remove TreeKeyManager.onClick
- In "Load More" example, when clicking "Load More", focus first node
that is added.

fix(cdk/tree): update active item on focus

---

src/material/_index.scss
src/material/slide-toggle/_slide-toggle-theme.scss
src/material/slide-toggle/slide-toggle.scss

There are new styles emitted by mat.slide-toggle-theme that are not emitted by any of: mat.slide-toggle-color, mat.slide-toggle-typography, mat.slide-toggle-density. If you rely on the partial mixins only and don't call mat.slide-toggle-theme, you can add mat.slide-toggle-base to get the missing styles.

fix(material/slide-toggle): move unthemable tokens to theme mixin

---

src/material/_index.scss
src/material/button/_button-theme.scss
src/material/button/_icon-button-theme.scss
src/material/core/_core-theme.scss
src/material/core/ripple/_ripple-theme.scss
src/material/core/selection/pseudo-checkbox/_pseudo-checkbox-theme.scss
src/material/core/theming/_all-theme.scss
src/material/divider/_divider-theme.scss
src/material/expansion/_expansion-theme.scss
src/material/form-field/_form-field-theme.scss
src/material/sort/_sort-theme.scss
src/material/tree/_tree-theme.scss

Adds a `base` theming dimension to go along with `color`,`typography`, and `density`. The base dimension includes styles such as border-radiuses that do not vary with the chosen color, typography, or density, but may vary depending on the theming system (e.g. Material 2 vs Material 3).
There are new styles emitted by `mat.<component>-theme` that are not emitted by any of: `mat.<component>-color`, `mat.<component>-typography`, or `mat.<component>-density`. If you rely on the partial mixins only and don't call `mat.<component>-theme`, you can add `mat.<component>-base` to get the missing styles. Alternatively you can call `mat.all-component-bases` to get just the base styles for all components.

feat(material/theming): Add 'base' theming dimension to all components

---

CHANGELOG.md

docs: release notes for the v16.2.8 release

---

CHANGELOG.md
package.json

Also this PR cherry-picks the changelog for v17.0.0-next.7 into the main branch so that the changelog is up to date.

Update next branch to reflect new release-train "v17.1.0-next.0".

---

src/cdk/tree/tree-with-tree-control.spec.ts
src/cdk/tree/tree.ts
src/components-examples/material/tree/tree-nested-overview/tree-nested-overview-example.html
src/material/tree/tree-using-tree-control.spec.ts

Fork mat-tree tests to mat-tree-using-tree-control.Remove uses of deprecated members from mat-tree tests. Tests in mat-tree-using-tree-control remain unchanged.
This commit message will be squashed away after merging in cdk-tree-revamp.

refactor(material/tree): fork tests for using and not using tree control

---

src/material/tree/node.ts
tools/public_api_guard/material/tree.md

remove dead code around MatTreeNode#tabinde. update code comments
This commit message will be removed when squashing the cdk-tree-revamp brand.

refactor(material/tree): remove dead code around MatTreeNode#tabindex.

---

src/material/button/_button-theme.scss
src/material/button/button.scss
src/material/core/tokens/m2/mdc/_filled-button.scss
src/material/core/tokens/m2/mdc/_protected-button.scss
src/material/core/tokens/tests/test-validate-tokens.scss

We were using the `button-filled` and `button-protected` prefixes for our tokens, likely because that's the naming that MDC is using in their filenames. This was incorrect, because MDC uses the `filled-button` and `protected-button` prefixes for the actual tokens. This will be problematic when start looking up tokens based on their names so this PR updates the prefixes to be in line with MDC.

fix(material/button): align prefixes with MDC

---

src/material/expansion/_expansion-theme.scss
src/material/expansion/expansion-panel.scss

fix(material/expansion): move unthemable tokens to theme mixin

---

src/dev-app/live-announcer/BUILD.bazel
src/dev-app/live-announcer/live-announcer-demo.html
src/dev-app/live-announcer/live-announcer-demo.ts

Update the live-announcer demo in the dev-app. Add an example of calling LiveAnnouncer inside of a Dialog. Create another way to reproduce issues with using live regions inside an aria-modal (#22733).

docs(cdk/a11y): add example of LiveAnnouncer inside dialog

---

src/youtube-player/youtube-player.ts
tools/public_api_guard/youtube-player/youtube-player.md

The `youtube-player` component was set up to use long rxjs chains everywhere which made it difficult to reason about and unnecessarily complex. This complexity would've prevented us from adding new features to it.
These changes reduce the component by ~30% while preserving its behavior and making it easier to reason about.

refactor(youtube-player): simplify component internals

---

src/material/button/_button-theme.scss

When tokenizing the text buttons, I found an issue where MDC previously was resetting the margin of buttons on lower densities. This is something that goes against our coding standards since we don't want to affect anything outside of the component.

refactor(material/button): clean up margin reset

---

CHANGELOG.md

docs: release notes for the v17.0.0-rc.0 release

---

src/material/divider/_divider-theme.scss
src/material/divider/divider.scss

fix(material/divider): move unthemable tokens to theme mixin

---

src/material/button/button-base.ts

Use vararg version of classList.add which has been allowed since https://github.com/angular/components/commit/cac8359747582b1bd606344f95fa8ab017a8bd02
also don't use a loop to check the attribute, it's only ever a single thing.

Minor optimizations to button-base

---

src/material/_index.scss
src/material/schematics/ng-update/index.ts
src/material/schematics/ng-update/migrations/theme-base-v17/index.ts
src/material/schematics/ng-update/migrations/theme-base-v17/migration.ts
src/material/schematics/ng-update/test-cases/theme-base.spec.ts

As of v17, users need to include the new "base" theme dimension for the components they use. For users that are using the "theme" mixins now, the base dimension will be pulled in automatically. However, for users using the "color", "typography", and "density" mixins only, they will need to include the "base" mixin as well.
This schematic works by scanning all of the app's Sass to determine which components had their "color", "typography", or "density" mixins included, but did *not* have their "theme" mixin included. It then locates all of the calls to "mat.core()" and inserts calls to the "base" mixins for the identified compoennts, immediately following. It makes sense to use "mat.core()" as a signal for when to insert them, because the "base" mixins should be used once-per-app, like …

fix(material/schematics): Create a schematic to add the base theme dimension

---

src/material/form-field/_form-field-theme.scss
src/material/form-field/form-field.scss

fix(material/form-field): move unthemable tokens to theme mixin

---

src/material/checkbox/checkbox.html
src/material/checkbox/checkbox.spec.ts

Adding aria-checked to the checkbox input. Technically this is redundant but Material Web's new styling requires indeterminate mode to have aria-checked=mixed when enabled.

fix(material/checkbox): add aria-checked

---

src/dev-app/button/button-demo.html
src/material/button/_icon-button-theme.scss
src/material/button/icon-button.scss
src/material/core/tokens/m2/mdc/_icon-button.scss

* Fixes that icon buttons weren't using the right token for disabled state.
* Fixes that the specificity of the icon button disabled styles was really high.
* Moves the logic for generating the palette tokens into the icon button tokens file.
* Fixes one place where we were referencing a token directly instead of using the API to generate the name.

refactor(material/button): handle disabled state of icon buttons through tokens

---

CHANGELOG.md

docs: release notes for the v17.0.0-rc.1 release

---

CHANGELOG.md

docs: release notes for the v16.2.10 release

---

src/material/button/_button-base.scss
src/material/button/_button-theme-private.scss
src/material/button/_button-theme.scss
src/material/button/button.scss
src/material/core/tokens/m2/mdc/_outlined-button.scss

MDC applies disabled styles through the `:disabled` selector which forced us to work around it by using a selector like `.mat-mdc-button[disabled][disabled]` and setting both the disabled and enabled button tokens. This is problematic, because it increases the specificity too much and it introduces space for mistakes, because we have to duplicate the tokens values.
These changes resolve the issue by re-applying the token slots to disabled buttons with the correct selector so that they can reuse the same tokens as the `button` nodes.

refactor(material/button): handle disabled states through tokens

---

guides/theming.md

Demo: https://mmalerba-demo.web.app/guide/theming

docs(material/theming): Add docs for the new base theming dimension

---

guides/theming-your-components.md
guides/theming.md
guides/typography.md

Demo: https://material2-docs-dev.web.app/guide/theming-your-components

docs(material/theming): Update docs on accessing theme values

---

guides/theming.md
src/material/schematics/ng-update/migrations/theme-base-v17/migration.ts
src/material/schematics/ng-update/test-cases/theme-base.spec.ts

Our docs site does not support the definition-list markdown, so I switched to headers instead. I also added a link from the generated schematic comment to the relevant documentation so users can learn more.

docs(material/theming): Fix broken theme guide formatting

---

src/material/chips/chip-input.ts
src/material/chips/chip-set.ts
tools/public_api_guard/material/chips.md

The original FR is this (https://github.com/angular/components/issues/28012). There are two changes in this PR,
1. Expose _chipGrid from MatChipInput
2. Add a stream of chip removal events in MatChipSet

feat(material/chips): expose _chipGrid in MatChipInput and add a stream of chip removal events

---

src/cdk/a11y/key-manager/legacy-tree-key-manager.ts
src/cdk/a11y/key-manager/tree-key-manager.spec.ts
src/cdk/a11y/key-manager/tree-key-manager.ts
src/cdk/a11y/public-api.ts
src/cdk/tree/tree-module.ts
src/cdk/tree/tree.ts
src/components-examples/cdk/tree/cdk-tree-custom-key-manager/cdk-tree-custom-key-manager-example.css
src/components-examples/cdk/tree/cdk-tree-custom-key-manager/cdk-tree-custom-key-manager-example.html
src/components-examples/cdk/tree/cdk-tree-custom-key-manager/cdk-tree-custom-key-manager-example.ts
src/components-examples/cdk/tree/cdk-tree-legacy-keyboard-interface/cdk-tree-legacy-keyboard-interface-example.css
src/components-examples/cdk/tree/cdk-tree-legacy-keyboard-interface/cdk-tree-legacy-keyboard-interface-example.html
src/components-examples/cdk/tree/cdk-tree-legacy-keyboard-interface/cdk-tree-legacy-keyboard-interface-example.ts
src/components-examples/cdk/tree/index.ts
src/dev-app/tree/tree-demo.html
src/dev-app/tree/tree-demo.ts
src/material/tree/node.ts
tools/public_api_guard/cdk/a11y.md
tools/public_api_guard/cdk/tree.md
tools/public_api_guard/material/tree.md

[fix(cdk/tree): add injectable key manager and opt-out](https://github.com/angular/components/pull/27985/commits/95fd972b2f15451d1a8b46899263285c127e7573) 
Make backwards compatibility improvements to cdk-tree-revamp regarding
focus management, the key manager and tabindex attribute.
* Add TreeKeyMangerStrategy interface
* Add injection toekn for tree key manager
* Add LegacyTreeKeyManager
Provide LegacyTreeKeyManager to use legacy tabindex behavior from before
TreeKeyManager was introducted.
This commit message will be squashed away.

fix(cdk/tree): add injectable key manager and opt-out

---

src/cdk/a11y/key-manager/tree-key-manager.ts
src/cdk/tree/tree-module.ts
src/material/tree/BUILD.bazel
src/material/tree/tree-module.ts

Change how tree-key-manager token is provided. Provide default TreeKeyManager at root. Remove provider from NgModule.

fix(cdk/tree): cleanup tree-key-manager token

---

src/cdk/schematics/utils/project-targets.ts
src/material/schematics/ng-add/index.spec.ts

Fixes that the schematics would throw if the app is using the `browser-esbuild` builder from the CLI.

fix(material/schematics): account for browser-esbuild builder

---

src/material/schematics/ng-add/fonts/material-fonts.ts

This is now added automatically by the CLI  angular/angular-cli#25318

refactor(schematics): don't add the preconnect for fonts

---

src/cdk/accordion/public-api.ts
tools/public_api_guard/cdk/accordion.md

Fixes an issue in the Angular CDK `accordion` component where `CDK_ACCORDION` injection token cannot be imported from `@angular/cdk/accordion`. This is because `public-api.ts` did not contain `CDK_ACCORDION` export.

fix(cdk/accordion): add `CDK_ACCORDION` export

---

guides/v15-mdc-migration.md
src/material/schematics/migration.json
src/material/schematics/ng-update/BUILD.bazel
src/material/schematics/ng-update/index.ts
src/material/schematics/ng-update/migrations/legacy-imports-error.ts
src/material/schematics/ng-update/test-cases/legacy-imports-error.spec.ts

These changes add a schematic that will log a fatal error and prevent the app from updating to v17 if it's using legacy components. Legacy components have been deleted in v17 so the app won't build if it updates.
Updating to Material v17 using `ng update` will look like this:

fix(material/core): prevent updates to v17 if project uses legacy components

---

CHANGELOG.md

docs: release notes for the v16.2.11 release

---

CHANGELOG.md

docs: release notes for the v17.0.0-rc.2 release

---

src/components-examples/material/expansion/expansion-overview/expansion-overview-example.css
src/components-examples/material/expansion/expansion-overview/expansion-overview-example.ts

This particular example had css for a mdc form field that isn't reference in the mat-expansion docs overview example, so I removed it here.

docs(material/expansion): remove unused styling

---

.github/workflows/deploy-dev-app-main-push.yml

Instead of using a preview channel, we are deploying to a live channel so that we have a static URL for team members.
For this we created a separate new sub-site in the ng-dev-previews Firebase project- still allowing us to benefit from the dev-infra maintenance of the project (and token/secret management).

ci: deploy dev-app to ng-comp-devapp.web.app

---

src/cdk/a11y/fake-event-detection.ts
src/cdk/a11y/focus-monitor/focus-monitor.spec.ts
src/cdk/a11y/input-modality/input-modality-detector.spec.ts
src/cdk/drag-drop/directives/drag.spec.ts
src/cdk/testing/testbed/fake-events/event-objects.ts
src/material/core/ripple/ripple.spec.ts

Fixes #28010
I found that testing `screenX` / `screenY` as suggested in the issue does not work. Testing `detail` seems to work on Chrome and Safari, but not Firefox (Firefox already had an alternate check). I wasn't able to test on Edge, but as part of the webkit family, it probably works like Chrome/Safari
Edit: @zarend helped me test some more configurations. Works with Chrome, Firefox, Safari, Edge & VoiceOver, NVDA, JAWS

perf(cdk/a11y): Don't trigger re-layout when detecting fake mousedown

---

src/material/schematics/ng-generate/navigation/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template

When running `ng generate @angular/material:navigation navigation`, the `asyncPipe` is used in the generated template but never imported into the Standalone Component imports.
While the `AsyncPipe`  should be imported to fix the issue, the `*ngIf` is also used in the template (even though I think this disappears when the new control flow syntax adoption is finalized).
The fix proposes to import the  `CommonModule`  as we usually do when working with Standalone Components.

fix(material/schematics): AsyncPipe and NgIF not imported

---

CHANGELOG.md

docs: release notes for the v17.0.0-rc.3 release

---

CHANGELOG.md

docs: release notes for the v16.2.12 release

---

scripts/deploy/publish-build-artifacts.sh
scripts/deploy/publish-docs-content.sh

With https://github.com/angular/components/commit/1d677215ee047967dc5e6f25ccb09e0225c16f1a, the snapshots CI job was migrated from CircleCI to GitHub actions, but the underlying
scripts were not updated to no longer depend on CircleCI specifics.

ci: publish snapshots to correct builds repository branch

---

src/google-maps/google-map/README.md

Fix missing declaration for display, used type google.maps.LatLngLiteral.

Fix missing declaration in README.md

---

src/components-examples/material/table/table-expandable-rows/table-expandable-rows-example.ts

Resolved a bug causing simultaneous row expansion in a MatTab when a nested MatTable component with expandable rows was used. The problem stemmed from animations triggered by the parent's visibility set to 'hidden.'
Solution: Incorporated void state within animations to reset them after eraseStyles function execution, ensuring consistent row expansion behavior within MatTabs.
Fix #27560

fix(material/table): Simultaneous Row Expansion Issue in MatTab with Nested MatTable Component

---

src/components-examples/material/datepicker/datepicker-locale/datepicker-locale-example.ts

docs(material/datepicker): Update close calendar label
Previously, the close calendar label was not updating correctly when switching languages. This commit fixes that issue.
Fixes: #25021

docs(material/datepicker): Update close calendar label

---

README.md

Pretty simple PR. Just one sentence for folks looking to contribute for the first time.

docs: add good first issue sentence

---

src/components-examples/material/datepicker/datepicker-locale/datepicker-locale-example.ts
src/material/list/list-base.ts
src/material/list/list.spec.ts

Fixes that the list was using the wrong variable to verify that it has the correct number of lines.
Fixes #27582.

fix(material/list): validation using wrong variable

---

.github/workflows/deploy-dev-app-main-push.yml

That way the static URL to the dev-app is always easy to discover.

ci: incorporate static dev-app deploy URL in GitHub deployments UI

---

src/material/autocomplete/autocomplete-trigger.ts
src/material/autocomplete/autocomplete.spec.ts

prior to this commit the previous selection on reactive form field wasn't getting unselected on programmatically reset of field
fixes #27652

fix(material/autocomplete): clear previous selection on reactive form reset

---

src/material/datepicker/calendar-body.ts

In the function [`isInRange`](https://github.com/angular/components/blob/bdef0c399ae37a64cf6cb204fdb273b5e619daf5/src/material/datepicker/calendar-body.ts#L617) numeric values are supposed to be compared. It is being called from [`_isInRange`](https://github.com/angular/components/blob/bdef0c399ae37a64cf6cb204fdb273b5e619daf5/src/material/datepicker/calendar-body.ts#L342) where `value` is compared to `startValue` and `endValue` which are calculated in [`_setRanges`](https://github.com/angular/components/blob/1dc30e8eacae1f318b53a9d22a462571b9de8ddb/src/material/datepicker/month-view.ts#L599-L600) using [`_getCellCompareValue`](https://github.com/angular/components/blob/1dc30e8eacae1f318b53a9d22a462571b9de8ddb/src/material/datepicker/month-view.ts#L578) which returns a number derived from …

fix(material/datepicker): Fix raw date value being compared

---

src/components-examples/material/dialog/dialog-animations/dialog-animations-example.ts
src/components-examples/material/dialog/dialog-data/dialog-data-example.ts
src/components-examples/material/dialog/dialog-elements/dialog-elements-example.ts
src/components-examples/material/dialog/dialog-from-menu/dialog-from-menu-example.ts
src/components-examples/material/dialog/dialog-harness/dialog-harness-example.spec.ts
src/components-examples/material/dialog/dialog-harness/dialog-harness-example.ts
src/components-examples/material/dialog/dialog-overview/dialog-overview-example.ts
src/dev-app/autocomplete/autocomplete-demo.ts
src/dev-app/dialog/dialog-demo.ts
src/dev-app/focus-trap/focus-trap-demo.ts
src/dev-app/slider/slider-demo.ts
src/material/dialog/testing/dialog-harness.spec.ts
src/universal-app/kitchen-sink/kitchen-sink.ts

Now that `@angular/material/dialog` was reworked for standalone, we can update the docs not to have to import the `MatDialogModule` anymore.

docs(material/dialog): use standalone imports in docs

---

src/components-examples/material-experimental/popover-edit/popover-edit-mat-table/popover-edit-mat-table-example.ts
src/components-examples/material/snack-bar/snack-bar-annotated-component/snack-bar-annotated-component-example.ts
src/components-examples/material/snack-bar/snack-bar-component/snack-bar-component-example.ts
src/components-examples/material/snack-bar/snack-bar-harness/snack-bar-harness-example.spec.ts
src/components-examples/material/snack-bar/snack-bar-harness/snack-bar-harness-example.ts
src/components-examples/material/snack-bar/snack-bar-overview/snack-bar-overview-example.ts
src/components-examples/material/snack-bar/snack-bar-position/snack-bar-position-example.ts
src/material/snack-bar/testing/snack-bar-harness.spec.ts
src/universal-app/kitchen-sink/kitchen-sink.ts

Now that `@angular/material/snack-bar` was reworked for standalone, we don't have to import the `MatSnackBarModule` everywhere.

docs(material/snack-bar): adjust docs for standalone

---

src/material/autocomplete/autocomplete-trigger.ts
tools/public_api_guard/material/autocomplete.md

In #27781 the call to capture the input value was moved into the root of `_attachOverlay` in order to capture it even when there are no options. This is problematic, because `_attachOverlay` is called as the user is typing which basically breaks the `requireSelection` feature.
These changes resolve the issue while preserving the original fix by only capturing the value when the overlay is actually attached.
Fixes #28113.

fix(material/autocomplete): regression in requireSelection when options are filtered

---

src/cdk/tree/nested-node.ts
src/cdk/tree/tree.ts

Refactor CdkTree implementation to simplify code in lifecycle hooks. Create a RenderingData type definition to simplify the Tree's rendering pipeline.
The render pipeline looks like this. It has two entry points ngAfterContentChecked and whener the datasource is switched.
1. ngAfterContentChecked OR datasource changed
2. call _subscribeToDataChanges
From here, the pipeline diverges. Tree subscribes to changes in the datasource and expansion state. From there, the pipeline goes on two paths: emit changes to expansion state, and render the changes from the datasource.
Add RenderingData type to make it more clear what stages are in the pipeline.
This commit message will be squashed away.

refactor(cdk/tree): simplify code in lifecycle hooks

---

src/material/autocomplete/autocomplete-trigger.ts
src/material/autocomplete/autocomplete.spec.ts

Based on an internal bug report. Clears the selected option in the autocomplete if the user types in something else.

fix(material/autocomplete): clear selected option if it is removed while typing

---

src/material/schematics/ng-update/migrations/legacy-imports-error.ts

Fixes that the `ng update` schematic was cheking `node_modules` and .d.ts files when looking for legacy imports. Also changes the logic to only look at top-level imports and exports, as well as any files that don't include `@angular/material` at all.
Fixes #28150.

fix(material/core): prevent ng update schematic from checking node_modules

---

src/material/chips/chip-grid.ts
src/material/core/common-behaviors/error-state.ts
src/material/core/common-behaviors/index.ts
src/material/datepicker/date-range-input-parts.ts
src/material/input/input.ts
src/material/select/select.ts
tools/public_api_guard/material/chips.md
tools/public_api_guard/material/core.md
tools/public_api_guard/material/datepicker.md
tools/public_api_guard/material/input.md
tools/public_api_guard/material/select.md

Removes all remaining usages of the error mixin by moving the functionality into a new class that is used internally inside the components. This allows us to further clean up some boilerplate and a hacky workaround in the chip grid.

Remove error mixin usages

---

src/dev-app/youtube-player/youtube-player-demo.ts
src/youtube-player/README.md
src/youtube-player/public-api.ts
src/youtube-player/youtube-module.ts
src/youtube-player/youtube-player.spec.ts
src/youtube-player/youtube-player.ts
tools/public_api_guard/youtube-player/youtube-player.md

Includes the following new features for the YouTube player component:
Adds input coercion support to the `youtube-player` component. Previously we couldn't do it because we didn't want to introduce a dependency to `@angular/cdk`.
Currently users have to load the YouTube API themselves which can be tricky to get right and be prone to race conditions. Since there's only one way to load it, these changes switch to doing so automatically. Loading the API automatically also enables us to optimize the component further in a follow-up PR by showing a placeholder image.
If users don't want the API to be loaded automatically, they can disable it through an input or using the newly-introduced `YOUTUBE_PLAYER_CONFIG` injection token.
Fixes #17037.
**Note:** there was an earlier attempt at this …

YouTube player features

---

src/material/tooltip/tooltip.scss

Fixes that the specificity of the `mat-mdc-tooltip-panel-non-interactive` class was too low which meant that it was easy to override by other structural styles.
Fixes #28145.

fix(material/tooltip): increase specificity of non-interactive styles

---

src/material/form-field/form-field.ts
tools/public_api_guard/material/form-field.md

The changes from #28149 appear to have triggered an error when `mat-chip-grid` is used inside of a `mat-form-field` and optimized with Closure compiler in a configuration that uses type information to do property renaming. These changes work around the issue within `mat-form-field`.

fix(material/form-field): work around closure compiler issue

---

src/dev-app/dev-app/dev-app-layout.html

Minor UX improvement to the dev app that makes it so the icons in the toolbar change depending on the state. This makes it easier to tell when the value has changed.

build: change icons in dev app based on state

---

test/angular-test-init-spec.ts
tools/tslint-rules/lightweightTokensRule.ts
tools/tslint-rules/noCrossEntryPointRelativeImportsRule.ts
tools/tslint-rules/noLifecycleInvocationRule.ts
tools/tslint-rules/requireLicenseBannerRule.ts
tools/tslint-rules/validateDecoratorsRule.ts
tslint.json

We have some custom lint rules that only apply to specific files. Currently the filtering is implemented by opting in specific files through a glob pattern. We do so by converting the absolute `SourceFile.fileName` to a relative one and checking it against the pattern.
The problem is that in some recent version either the OS or TypeScript started returning lower-cased paths in `SourceFile.fileName` while `process.cwd()` which we resolve the path against is case-sensitive. This ends up producing an invalid path which doesn't get covered by the lint rules.
These changes fix the issue by having custom rules apply to all files and using the glob pattern to _exclude_ some of them.

build: custom lint rules not working locally

---

.stylelintrc.json
src/dev-app/youtube-player/youtube-player-demo.html
src/dev-app/youtube-player/youtube-player-demo.ts
src/youtube-player/BUILD.bazel
src/youtube-player/README.md
src/youtube-player/public-api.ts
src/youtube-player/youtube-player-placeholder.scss
src/youtube-player/youtube-player-placeholder.ts
src/youtube-player/youtube-player.spec.ts
src/youtube-player/youtube-player.ts
tools/public_api_guard/youtube-player/youtube-player.md

Currently the `youtube-player` component loads the YouTube API and sets up the video on initialization. This can slow the page down a lot, because it loads and executes ~150kb of JavaScript, even though the video isn't playing.
These changes rework the `youtube-player` component to show the thumbnail of the video and a fake button instead. When the button is clicked, the API will be loaded and the video will be autoplayed, thus moving the YouTube API out of the critical path.
There are a few cases where the placeholder won't be shown:
* A video that plays automatically.
* When the `youtube-player` is showing a playlist, rather than a single video.

feat(youtube-player): improve initial load performance using a placeholder image

---

CHANGELOG.md

docs: release notes for the v17.0.2 release

---

src/components-examples/material/datepicker/datepicker-views-selection/datepicker-views-selection-example.ts

Datepicker emulating a Year and month picker:
If the user deletes the value of the control manually leaving the value of the control as null, the function "setMonthAndYear" breaks because the variable "ctrlValue" does not have the functions that assign the month and year (year, month). Allowing to enter the day (option that should not be shown).

fix(material/datepicker): fix create control value when null

---

src/material/checkbox/checkbox-required-validator.ts
src/material/checkbox/checkbox.spec.ts
src/material/checkbox/checkbox.ts
src/material/checkbox/module.ts
src/material/slide-toggle/module.ts
src/material/slide-toggle/slide-toggle-required-validator.ts
src/material/slide-toggle/slide-toggle.ts
tools/public_api_guard/material/checkbox.md
tools/public_api_guard/material/slide-toggle.md

Currently `MatCheckbox` and `MatSlideToggle` implement required validation with separate directives, similarly to how `@angular/forms` handles it. This is problematic, because it would require `standalone` users to add two imports.
These changes deprecate the separate directives and move the required validation into the components.

Remove dedicated required validator directives

---

src/cdk/a11y/key-manager/list-key-manager.spec.ts
src/cdk/a11y/key-manager/list-key-manager.ts
src/cdk/a11y/key-manager/noop-tree-key-manager.ts
src/cdk/a11y/key-manager/tree-key-manager-strategy.ts
src/cdk/a11y/key-manager/tree-key-manager.ts
src/cdk/a11y/key-manager/typeahead.ts
src/cdk/tree/tree.ts
src/components-examples/cdk/tree/cdk-tree-custom-key-manager/cdk-tree-custom-key-manager-example.ts
tools/public_api_guard/cdk/a11y.md

refactor(cdk/a11y): factor out a typeahead class for key managers

---

src/material/slider/slider-input.ts
src/material/slider/slider.spec.ts
src/material/slider/slider.ts

* Fixes https://github.com/angular/components/issues/26459
* Fixes a bug where the number of tick marks can be miscalculated when the step is a decimal (e.g. 1.5)

fix(material/slider): fix tick mark precision

---

CHANGELOG.md

docs: release notes for the v17.0.3 release

---

src/material/chips/chip-listbox.ts
src/universal-app/kitchen-sink/kitchen-sink.html

Removes the `ngSkipHydration` from `mat-chip-listbox` since it seems to work fine in the test app.

fix(material/chips): enable hydration

---

src/components-examples/material/tabs/tab-group-dynamic/tab-group-dynamic-example.ts

bug(mat-tabs): Example of mat-tabs deletion is showing wrong index : FIXED
Set Selected value at time of splicing the array

FIX: Example of mat-tabs deletion is showing wrong index

---

src/material/tabs/tab-group.ts
tools/public_api_guard/material/tabs.md

Tabs background colors should be customized using the theming API instead of using component inputs. Adding a boolean check that can be modified internally to perform cleanup before v20.

fix(material/tabs): deprecate backgroundColor API

---

src/components-examples/material/button/button-disabled-interactive/button-disabled-interactive-example.css
src/components-examples/material/button/button-disabled-interactive/button-disabled-interactive-example.html
src/components-examples/material/button/button-disabled-interactive/button-disabled-interactive-example.ts
src/components-examples/material/button/index.ts
src/dev-app/button/BUILD.bazel
src/dev-app/button/button-demo.html
src/dev-app/button/button-demo.ts
src/material/button/_button-base.scss
src/material/button/button-base.ts
src/material/button/button.md
src/material/button/button.scss
src/material/button/button.spec.ts
src/material/button/fab.scss
src/material/button/public-api.ts
src/material/button/testing/button-harness.ts
src/material/core/tokens/m2/mat/_fab.scss
src/material/core/tokens/m2/mat/_filled-button.scss
src/material/core/tokens/m2/mat/_icon-button.scss
src/material/core/tokens/m2/mat/_outlined-button.scss
src/material/core/tokens/m2/mat/_protected-button.scss
src/material/core/tokens/m2/mat/_text-button.scss
tools/public_api_guard/material/button.md

Native disabled buttons don't allow focus and prevent the button from dispatching events. In some cases this can be problematic, because it prevents the app from showing to the user why the button is disabled.
These changes introduce a new opt-in input that will style buttons as disabled and set `aria-disabled="true"`, but not set the native `disabled` attribute, allowing them to be interactive.
**Note for reviewers:** there's an example of the feature in the button demo, but you have to scroll down and check the "Allow disabled button interactivity" checkbox. Afterwards you should see tooltips when hovering over the disabled buttons.

feat(material/button): add the ability to interact with disabled buttons

---

CHANGELOG.md

docs: release notes for the v17.0.4 release

---

src/material/paginator/paginator.scss

Fix accessibility issue in MatPaginator component. When screen is narrow, maintain the visual order with the DOM order.
Current behavior is swappign visual order of "Items Per Page" and "1 of 4" on narrow screens. With this commit applied, no longer swap the order.

fix(material/paginator): match visual and reading order

---

src/material/select/select.html
src/material/select/select.ts

Fixes that the select was closing and reopening if it's opened from inside a `focus` handler on click. Also avoids a bit of work in the `open` and `close` methods.
Fixes #28280.

fix(material/select): flicker if opened from inside a focus handler

---

src/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
src/material/schematics/ng-generate/address-form/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
src/material/schematics/ng-generate/address-form/index.spec.ts
src/material/schematics/ng-generate/dashboard/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html.template
src/material/schematics/ng-generate/dashboard/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
src/material/schematics/ng-generate/navigation/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
src/material/schematics/ng-generate/tree/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template

* Fixes that the generated dashboard had a couple of errors in it.
* Switches the schematic-generated code to use `styleUrl` and a single `styles` string.
Fixes #28299.

Fixes for ng generate schematics

---

src/material/expansion/accordion.ts
src/material/expansion/expansion-panel.ts
tools/public_api_guard/material/expansion.md

The bases classes of the CDK already define the input with transforms. Technically the new `inputs` declarations override the full metadata, loosing the transforms. This is currently a bug in the framework where components relied on the behavior that transforms were inherited independently. This commit fixes this and cleans up the code. The inputs do not need to be re-declared.

refactor(material/expansion): remove incorrect `inputs` overrides

---

src/material-experimental/theming/_m3-tokens.scss

Fixes that disabled M3 form fields were a solid black color and that filled form fields didn't have a valid border radius.

Fix M3 form field disabled state and shape

---

src/material/autocomplete/autocomplete-trigger.ts

Fixes that the autocomplete was ignoring clicks on the entire form field area, including hints, rather than just the form field inner container.
Fixes #28271.

fix(material/autocomplete): not closing when clicking on hint area

---

src/components-examples/material/list/list-variants/list-variants-example.html

Fix opening `<span>` tag formatting

docs(material/list): Fix code example formatting

---

src/cdk/a11y/focus-trap/focus-trap.ts
src/cdk/dialog/dialog-container.ts
src/universal-app/kitchen-sink/kitchen-sink.html
src/universal-app/kitchen-sink/kitchen-sink.ts

These changes disable the focus traps during server-side rendering, because they change the DOM structure and can break hydration.

Resolve hydration issues with focus traps

---

src/material/_index.scss
src/material/core/mdc-helpers/_mdc-helpers.scss
src/material/slide-toggle/_slide-toggle-theme.scss

Now that we're completely switched over to tokens, we don't need the code that was patching MDC's theming API with our own values.

refactor(material/core): remove MDC theme patches

---

src/cdk/drag-drop/directives/drag.spec.ts
src/cdk/drag-drop/directives/drag.ts
src/cdk/drag-drop/dom/dom-rect.ts
src/cdk/drag-drop/dom/parent-position-tracker.ts
src/cdk/drag-drop/drag-ref.ts
src/cdk/drag-drop/drop-list-ref.ts
src/cdk/drag-drop/sorting/single-axis-sort-strategy.ts
src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
src/cdk/overlay/position/flexible-connected-position-strategy.ts
src/cdk/overlay/position/scroll-clip.ts
src/cdk/scrolling/viewport-ruler.ts
src/cdk/scrolling/virtual-scrollable.ts
src/dev-app/drag-drop/drag-drop-demo.ts
src/material/core/ripple/ripple-renderer.ts
src/material/tabs/ink-bar.ts
tools/public_api_guard/cdk/drag-drop.md

The `ClientRect` type is deprecated in favor of `DOMRect`. These changes replace all the references.

refactor(multiple): remove references to deprecated ClientRect

---

src/components-examples/material/chips/chips-avatar/chips-avatar-example.html

since using mat-chip inside mat-chip-listbox is unsupported (#28210)

fix(material/chip-set): fixed chips-avatar-example

---

src/material/schematics/ng-generate/mdc-migration/schema.json

[A recent change in the CLI](https://github.com/angular/angular-cli/pull/26685) added a `-d` flag to `ng generate` which is the same as the alias for `--directory` in the MDC migration. This caused an error, because the default boolean value from the CLI was being picked up and was failing the schema validation.
These changes remove the alias since it isn't really necessary.
Fixes #28335.

fix(material/schematics): schema error in mdc migration

---

scripts/approve-api-golden.js

Updates the `approve-api` script to allow more than one package to be approved at the same time.

build: support multiple packages in api approval script

---

src/material/autocomplete/autocomplete.ts
src/material/menu/menu.ts
src/material/select/select.ts
tools/public_api_guard/material/select.md

Hydration was disabled for `mat-autocomplete`, `mat-menu` and `mat-select`, even though it currently seems to work. These changes enable it to allow for better initial performance.

fix(multiple): enable hydration in autocomplete, menu and select

---

src/cdk/drag-drop/directives/drag.spec.ts
src/cdk/drag-drop/drop-list-ref.ts

The drop list has some logic that prevents auto-scrolling when the container isn't scrollable. It didn't account for RTL which meant that, even though the rest of the logic works in RTL, auto-scrolling was being disabled incorrectly.
Fixes #28326.

fix(cdk/drag-drop): auto-scroll to the left not starting in rtl layout

---

src/cdk/dialog/dialog-container.ts
src/material/bottom-sheet/bottom-sheet-container.ts
src/material/dialog/dialog-content-directives.ts
src/material/dialog/dialog.spec.ts
tools/public_api_guard/cdk/dialog.md
tools/public_api_guard/material/bottom-sheet.md

The `mat-dialog-title` directive updates state in a microtask and should call `ChangeDetectorRef.markForCheck`. Failing to do this will cause the component tree to not be checked if it lives under an `OnPush` component that has not otherwise been marked for check.

fix(material/dialog): `mat-dialog-title` should work under `OnPush` `viewContainerRef`

---

guides/theming.md

I guess the word "us" might be a typo of "use". 
The recommended approach is to rely on the `theme` mixins to lay down your base styles, and if needed _**us**_ the single dimension mixins to override particular aspects for parts of your app (see the section on...

fix(guides/theming.md) Typo fix of theming.md

---

src/material/slider/slider-input.ts
src/material/slider/slider.spec.ts
src/material/slider/slider.ts
tools/public_api_guard/material/slider.md

* fixes https://github.com/angular/components/issues/28206

fix(material/slider): update inactive input width on value change

---

tools/sass/compiler-main.ts
tools/sass/local-sass-importer.ts

This PR will will use `import` instead of `require` for sass.

build: import sass

---

package.json
src/material-date-fns-adapter/adapter/date-fns-adapter.ts
src/material-date-fns-adapter/package.json
yarn.lock

Adds support for `date-fns` 3 to the date adapter.
Fixes #28357.

feat(material-date-fns-adapter): support date-fns 3.0

---

src/material/snack-bar/snack-bar-container.ts
src/material/snack-bar/snack-bar.spec.ts

By updating the "arbitrary-component" to `OnPush`, the following test fails:
`MatSnackBar should set the old snack bar animation state to complete and the new snack bar animation`.
The assertion that fails is the `afterDismissed` spy, which never gets called. Adding `markForCheck` in the `exit` ensures the `_animationState` is applied to the host and completes. If this is not done, the following listener never executes, including the `_completeExist`: `'(@state.done)': 'onAnimationEnd($event)'`.

fix(material/snack-bar): Ensure snackbar enter/exit works with OnPush ancestor

---

src/material/slider/slider-input.ts
src/material/slider/slider-thumb.ts
src/material/slider/slider.spec.ts

* Fixes https://github.com/angular/components/issues/28211

fix(material/slider): fix internal focus state on safari

---

src/material/tabs/tab-group.html
src/material/tabs/tab-group.ts
src/material/tabs/tab.ts
src/universal-app/kitchen-sink/kitchen-sink.html
tools/public_api_guard/material/tabs.md

Adds a workaround that allows us to enable hydration in the tab group component.

fix(material/tabs): enable hydration

---

src/material-date-fns-adapter/adapter/index.ts
src/material-luxon-adapter/adapter/index.ts
src/material-moment-adapter/adapter/index.ts
src/material/core/datetime/index.ts

This commit refactors the NgModules for date adapters to use the provide* functions directly in the providers array, so we don't have code repetition.

fix(multiple): use provide functions in providers for date adapters

---

src/cdk/table/sticky-styler.ts
src/cdk/table/table.ts
src/material/table/table.ts
src/universal-app/kitchen-sink/kitchen-sink.html
src/universal-app/kitchen-sink/kitchen-sink.ts
tools/public_api_guard/cdk/table.md
tools/public_api_guard/material/table.md

Reworks the table so that it can support hydration. There were a few issues that broke hydration:
1. There wasn't a catch-all `ng-content` slot which meant that the comment nodes representing the table content were dropped, causing an error.
2. The table needs to conditionally wrap some content with native table sections (`thead`,  `tbody` etc.) which was done with direct DOM manipulation. This breaks hydration because Angular won't know about those elements.
The first issue is easily resolved by adding an `ng-content` element. It shouldn't affect existing tables, since all the projected content is composed of comment nodes.
The second issue is a bit trickier, because we were using content queries to resolve the individual table outlets. Wrapping them in a conditional breaks the query so …

fix(cdk/table): support hydration

---

src/material/button/_button-theme.scss
src/material/button/_icon-button-theme.scss
src/material/button/button.scss
src/material/core/tokens/m2/mdc/_text-button.scss
src/material/toolbar/toolbar.scss

* Moves the base tokens of the button to the theme, rather than the structural styles. This is necessary for M3.
* Emits the non-palette button tokens at the root of the theme.

Button token fixes

---

src/material/snack-bar/snack-bar-container.ts

`onMicrotaskEmpty` will not emit when an application is using `NoopNgZone`. There wasn't a test around this bit of code when it was added so I can't be completely sure this doesn't break anything. It's unclear to me whether it's meant to wait for rendering or just meant to be async. It's possible that simply making the code execute in the microtask queue will have the same overall effect as before.

refactor(material/snack-bar): Remove NgZone.onMicrotaskEmpty dependency

---

src/cdk/table/cell.ts
src/cdk/table/table.spec.ts
src/cdk/table/table.ts
tools/public_api_guard/cdk/table.md

1) Uplevels repeated logic to the host CdkTable which does it once instead of n times.
2) Skips setting role=cell in native tables, for which it is already the default (see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/td#technical_summary)
This saves just over a tenth of a millisecond per cell in the native TD case and about a twentieth in other cases. Doesn't sound like much, but it adds up in larger tables.

perf(cdk/table): Optimize a11y role logic in CdkCell.

---

src/material/slider/slider-input.ts
src/material/slider/slider-interface.ts
src/material/slider/slider.spec.ts
src/material/slider/slider.ts
tools/public_api_guard/material/slider.md

* Fixes a bug where the slider's min and max value could go beyond the first and last tick marks.
This caused the slider thumb to never truly line up with the tick marks except at the exact center
of the slider track.

fix(material/slider): slider tx imprecision 

---

src/material/datepicker/calendar.scss

Fixes that at some point during the tokens transition the disabled state of the calendar buttons started being overwritten by the enabled state.

fix(material/datepicker): unable to distinguish disabled buttons in the calendar

---

src/dev-app/theme-m3.scss
src/material-experimental/theming/_custom-tokens.scss
src/material-experimental/theming/_m3-density.scss
src/material-experimental/theming/_m3-tokens.scss
src/material/button/_button-theme.scss
src/material/core/tokens/m2/_index.scss

Sets up the tokens for the M3 buttons.

feat(material-experimental/theming): add M3 button tokens

---

src/material/_index.scss

We intended to expose this function along with the other theme inspection APIs, but forgot to add it to the list. It is necessary for users to be able to create their own versions of mixins like `all-component-colors`

fix(material/theming): Expose the `theme-remove` Sass function

---

guides/theming-your-components.md

Fixes a typo which is used in a code block as an example. The typo is "desity" instead of "density", and thus is a code block that does not work.
No breaking changes, just a doc change.

docs(material/theming-your-component): Typo in code-block example

---

src/cdk/table/sticky-styler.ts

Fixes that after #28356 the table rows were measured too early which caused multiple sticky rows not to work as expected.

fix(cdk/table): measuring sticky row too early

---

src/universal-app/BUILD.bazel
src/universal-app/hydration.e2e.spec.ts
src/universal-app/kitchen-sink/kitchen-sink.html
src/universal-app/protractor.conf.js
src/universal-app/start-devserver.js

Sets up some tests to verify that we don't regress on our hydration support.

build: add automated test for hydration

---

src/dev-app/theme-m3.scss
src/material-experimental/theming/_custom-tokens.scss
src/material-experimental/theming/_m3-tokens.scss
src/material/core/style/_sass-utils.scss
src/material/core/tokens/_token-utils.scss
src/material/icon/_icon-theme.scss

Adds token infrastructure to be able to support color variants for M3 components. This is accomplished by adding an additional namesapce to the token map per color variant. For example, if the mat-icon tokens live in the token map under `(mat, icon): (token-values...)`, and we want to support a primary color variant, we will add a new namespace `(mat, icon, primary): (token-value-overrides...)`.
When applying a color or theme mixin for an M3 theme, users can specify the desired variant as an extra parameter to the mixin: `@include mat.icon-theme($theme, $color-variant: primary)`. The mixin will then merge any overrides from the variant namespace into the default values from the standard namespace to determine the final value for each CSS variable. Note that the user must provide this a …

feat(material-experimental/theming): Add support for color variants

---

CHANGELOG.md

docs: release notes for the v17.0.5 release

---

src/dev-app/theme-m3.scss
src/material-experimental/theming/_config-validation.scss
src/material/paginator/_paginator-theme.scss

Includes a couple of M3-related density fixes:
1. We weren't validating density scales correctly, because of a missing comma.
2. We weren't setting the density of the form field in the paginator in M3.

M3-related density fixes

---

src/material/button/button-base.ts
src/material/chips/chip.ts
src/material/core/private/ripple-loader.ts
tools/public_api_guard/material/core.md

Backports an existing fix from 17.0.x to 16.2.x.
The `MatRippleLoader` that is used in the button doesn't track any ripples, but instead patches the ripples onto the DOM nodes which in theory should avoid leaks since the ripple will be collected together with the node. The problem is that each ripple registers itself with the `RippleEventManager` which needs to be notified on destroy so that it can dereference the DOM nodes and remove the event listeners.
These changes avoid the leaks by:
1. Destroying the ripple when the trigger is destroyed.
2. Cleaning up all the ripples when the ripple loader is destroyed.
3. No longer patching directives onto the DOM nodes.
Fixes #28240.
(cherry picked from commit a962bb77f2e68b44e4e3ccf88841f63495661036)

Backport ripple memory leak fix to LTS

---

CHANGELOG.md

docs: release notes for the v16.2.13 release

---

src/material-experimental/theming/_custom-tokens.scss

Fixes that disabled radio buttons didn't have the correct color of the label when disabled. Also switches some existing `rgba` calls to use the `safe-color-change` function.

fix(material-experimental/theming): disabled radio button incorrect label color

---

src/material-experimental/theming/_m3-tokens.scss
src/material/checkbox/_checkbox-theme.scss
src/material/core/tokens/m2/_index.scss
src/material/radio/_radio-theme.scss
src/material/slide-toggle/_slide-toggle-theme.scss

Fixes that the tokens for the internal form field weren't being provided in M3. Also includes the tokens in the components where the internal form field is used.

fix(material-experimental/theming): set up internal form field in M3

---

src/material/schematics/ng-add/index.spec.ts
src/material/schematics/ng-add/setup-project.ts

* Reworks the `ng add` schematic so it doesn't depend on deprecated functions.
* Imports the async animations instead of the eagerly-loaded ones.

fix(material/schematics): import async animations  and remove deprecated function usages

---

src/material/progress-bar/_progress-bar-theme.scss
src/material/progress-bar/progress-bar.scss

Previously we couldn't get the `track-color` to work through tokens, because it was generating an inline SVG. That's no longer the case so we can remove the workaround which also fixes the progress bar under M3.

fix(material/progress-bar): remove track color workaround

---

src/dev-app/theme-m3.scss
src/material-experimental/theming/_custom-tokens.scss
src/material-experimental/theming/_m3-tokens.scss
src/material/core/_core-theme.scss
src/material/core/tokens/m2/_index.scss

* Sets up the `core` theme for tokens.
* Adds the app-level tokens.

fix(material-experimental/theming): set up core theme and app tokens

---

CHANGELOG.md

docs: release notes for the v17.0.6 release

---

src/dev-app/theme-m3.scss
src/material-experimental/theming/_custom-tokens.scss
src/material-experimental/theming/_m3-tokens.scss
src/material/slider/_slider-theme.scss
src/material/tabs/_tabs-theme.scss

Based on https://github.com/angular/components/pull/28412
Note: originally this PR added color variants to toolbar as well, but removed since that is not part of the M3 spec and it doesn't play well with other parts of the spec (namely icons)

fix(material-experimental/theming): Add support for color variants in tabs and slider

---

src/material/core/common-behaviors/error-state.ts
tools/public_api_guard/material/core.md

Fix Closure Compiler issue with <mat-error/>. Fix issue where <mat-error/> does not render.
Existing behavior is that _ErrorStateTracker sometimes reports error state as false when there is an error. This happens because Closure Compiler renames the _ErrorStateTracker's ErrorStateMatcher. The compiler renames all the other implementations of ErrorStateMatcher, but they have different names. Causes the matcher to be null in _ErrorStateTracker. Since ErrorStateMatcher is used as a class in some situations, Closure Compiler is not aware that it is intended to be the same type as the other implementations of ErrorStateMather.
Fix issue by declaring ErrorStateMatcher as an interface. When this commit applied, <mat-error/> will render when built with Closure Compiler.
Googlers: see [internal …

fix(material/core): fix mat-error not rendering with Closure Compiler

---

src/dev-app/button/button-demo.html
src/material-experimental/theming/_custom-tokens.scss
src/material-experimental/theming/_m3-density.scss
src/material/button/_button-base.scss
src/material/button/_button-theme.scss
src/material/button/button.scss
src/material/core/tokens/_token-utils.scss
src/material/core/tokens/m2/mat/_filled-button.scss
src/material/core/tokens/m2/mat/_outlined-button.scss
src/material/core/tokens/m2/mat/_protected-button.scss
src/material/core/tokens/m2/mat/_text-button.scss

Includes the following changes that allow us to set the proper horizontal spacing for buttons in M3:
Adds a utility that generates a `var()` reference to a token. This is necessary for some more complex declarations like `padding` where `create-token-slot` isn't enough.
In M3 the buttons will have a different padding. These changes introduce tokens that will allow us to customize it.
**Note:** the text button in M3 has a different padding depending on whether it has icons so it needs an additional token.
Adds the proper paddings to the M3 buttons.
Fixes that the icon button was becoming smaller than its icon at the lowest density.

M3 button paddings

---

src/dev-app/dialog/dialog-demo.ts
src/material/dialog/dialog.scss

[A change in MDC](https://github.com/material-components/material-components-web/commit/d153db62b3f665934a1d7445f14653b9ef0d4f66) moved the `transform` animation from the container to the surface which broke our implementation.
These changes also take the chance to fix that the animation was targeting all properties, rather than just `transform` and `opacity`. I've also fixed up the demo a bit to make it less jumpy.
Fixes #28447.

fix(material/dialog): scale animation not working

---

src/material/chips/chips.md

Update Chips a11y documentation. Remove instructions to make an announcement when deleting chips.
Remove the call to LiveAnnouncer. Remove unnecessary live regions to avoid disrupting users who use Assistive Technology.

docs(material/chips): remove instructions to announce deletion

---

src/material/badge/BUILD.bazel
src/material/badge/_badge-theme.scss
src/material/badge/badge-module.ts
src/material/badge/badge.scss
src/material/badge/badge.spec.ts
src/material/badge/badge.ts
src/material/badge/public-api.ts
tools/public_api_guard/material/badge.md

Historically we've had the structural styles for the badge in the theme, because Angular doesn't support adding styles to a directive. This can lead to duplicate CSS and can be problematic for M3.
These changes move the styles into a dummy component that is used to load the style only once per app.

fix(material/badge): move structural styles out of theme

---

src/cdk-experimental/column-resize/resize-strategy.ts
src/cdk-experimental/table-scroll-container/table-scroll-container.ts
src/cdk/table/coalesced-style-scheduler.ts
src/cdk/table/sticky-styler.ts
src/cdk/table/table.ts
tools/public_api_guard/cdk/table.md

Per Chrome devtools, in the Angular Material devapp, cuts down startup rendering time by about 60ms (~25%). In a real app screen with a single large table, the reduction is ~16%. The main difference is that the change makes a bigger difference when multiple tables are rendering at the same time, since previously separate CoalescedStyleScheduler instances would be grouping tasks separately per-table. Seems to reduce scripting time a smidge as well.

perf(cdk/table): Use afterRender hooks

---

src/cdk-experimental/column-resize/resize-strategy.ts
src/cdk-experimental/table-scroll-container/table-scroll-container.ts
src/cdk/table/coalesced-style-scheduler.ts
src/cdk/table/sticky-styler.ts
src/cdk/table/table.ts
tools/public_api_guard/cdk/table.md

This reverts commit 81cb5acc8b2545b5674362a6f4c0b1768136dd66.

Revert "perf(cdk/table): Use afterRender hooks (#28354)"

---

src/material/slide-toggle/_slide-toggle-theme.scss
src/material/slide-toggle/slide-toggle.scss

* Create a css var to allow teams to override the label text color of a disabled switch

fix(material/slide-toggle): use css var for disabled label color

---

CHANGELOG.md

Cherry-picks the changelog from the "17.1.x" branch to the next branch (main).

docs: release notes for the v17.1.1 release

---

src/dev-app/theme-m3.scss
src/material-experimental/theming/_custom-tokens.scss
src/material/core/tokens/m2/mat/_stepper.scss
src/material/stepper/_stepper-theme.scss
src/material/stepper/step-header.scss

Example of the different color variants for stepper in the dev-app
Primary: 
Secondary: 
Tertiary: 
Warn:

fix(material/stepper): Update token values for M3 and add color variant support

---

src/material/schematics/ng-add/index.spec.ts
src/material/schematics/ng-add/setup-project.ts

* Reworks the `ng add` schematic so it doesn't depend on deprecated functions.
* Imports the async animations instead of the eagerly-loaded ones.

[Cherry pick] fix(material/schematics): import async animations and remove deprecated function usages

---

src/material-experimental/theming/_custom-tokens.scss
src/material/core/option/option.scss

Fixes the following issues in the M3 `mat-option`:
* Font size was too small and font weight too high. This appears to have been a bug in the spec that MDC is also working around. These changes apply the same workaround as MDC.
* Multi-select options in the selected state had a darker background, even though they shouldn't. This happened to work by accident in M2 and only became visible now in M3.

fix(material-experimental/theming): resolve M3 issues in mat-option

---

src/material-experimental/theming/_custom-tokens.scss

Fixes that the track color for the progress bar didn't match the palette color.

fix(material-experimental/theming): incorrect track color for alternate progress bar palettes

---

src/material/slider/slider-thumb.ts
src/material/slider/slider.spec.ts

Fixes that the slider was throwing an error if it's destroyed before `ngAfterViewInit` has run.
Fixes #28475.

fix(material/slider): error if slider is destroyed before first change detection

---

src/material/core/tokens/m2/mat/_form-field.scss

Removes :hover and .mat-focused opacity changes to .form-field-focus-overlay 
which was causing a low color contrast ratio between the text and form-field input
background fill color.

fix(material/form-field): failing color contrast text to bg color ratio

---

CODING_STANDARDS.md

With #27778, the input coercion was changed to use Angular's built-in input transform functions. This PR reflects these changes in the coding standards.

docs: update coercion coding standards

---

CHANGELOG.md

Cherry-picks the changelog from the "17.1.x" branch to the next branch (main).

docs: release notes for the v17.1.2 release

---

src/material-experimental/theming/_custom-tokens.scss
src/material/chips/chip.scss
src/material/core/tokens/m2/mdc/_chip.scss

Depends on https://github.com/angular/components/pull/28488

fix(material/chips): Tokenize the hover & focus overlays

---

src/cdk/dialog/dialog.spec.ts
src/components-examples/material/dialog/dialog-animations/dialog-animations-example-dialog.html
src/components-examples/material/dialog/dialog-data/dialog-data-example-dialog.html
src/components-examples/material/dialog/dialog-elements/dialog-elements-example-dialog.html
src/components-examples/material/dialog/dialog-overview/dialog-overview-example-dialog.html
src/dev-app/slider/slider-demo.ts
src/material/dialog/dialog.spec.ts

Because the vast majority of pages will already have an `<h1>`, and MDN now recommends to avoid using multiple `<h1>` elements on one page. So we should strive to show code examples that can be copy-pasted as is.
See also:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#avoid_using_multiple_h1_elements_on_one_page
- https://stackoverflow.com/a/38467898/37706
- https://accessibleweb.com/question-answer/how-should-i-handle-headings-in-a-modal/

docs(material/dialog): use h2 for dialog title

---

src/material/schematics/ng-generate/mdc-migration/schema.json

Cherry-picks the fix for the MDC migration to the 16.2.x branch.
[A recent change in the CLI](https://github.com/angular/angular-cli/pull/26685) added a `-d` flag to `ng generate` which is the same as the alias for `--directory` in the MDC migration. This caused an error, because the default boolean value from the CLI was being picked up and was failing the schema validation.
These changes remove the alias since it isn't really necessary.
Fixes #28510.

[Cherry pick] fix(material/schematics): schema error in mdc migration

---

CHANGELOG.md

docs: release notes for the v16.2.14 release

---

src/dev-app/autocomplete/autocomplete-demo.html
src/dev-app/autocomplete/autocomplete-demo.scss
src/dev-app/theme-m3.scss
src/material-experimental/theming/_custom-tokens.scss
src/material/autocomplete/_autocomplete-theme.scss
src/material/autocomplete/autocomplete.scss
src/material/core/option/option.scss
src/material/core/tokens/m2/mat/_autocomplete.scss

* Aligns the autocomplete with M3.
* Fixes that `mat-option` had a different background from its container.
* Fixes some jumpiness in the autocomplete demo.
* Fixes the spacing between buttons in the dev app toolbar.

M3 autocomplete

---

src/dev-app/BUILD.bazel
src/dev-app/theme-m3.scss
src/material-experimental/_index.scss
src/material-experimental/theming/_color-api-back-compat.scss

Also changes our back-compat styles to make chips and options with `.mat-primary` secondary colored rather than primary. This sounds odd, but the spec really treats "secondary" as an extended set of primary hues, and these components look much better when defaulted to secondary.
A user who really does want the primary color can still get it by calling e.g. `@include mat.chips-theme($theme, $color-variant: primary)`, this only affects what our back-compat mixin outputs (`@include matx.color-variants-back-compat($theme)`).

fix(material-experimental/theming): Make color API back-compat styles available

---

src/material-experimental/theming/_custom-tokens.scss
src/material/chips/chip.scss
src/material/core/tokens/m2/mat/_chip.scss
src/material/core/tokens/m2/mdc/_chip.scss

Depends on https://github.com/angular/components/pull/28498

fix(material-experimental/theming): Fix chip trailing icon opacity in M3

---

src/cdk/scrolling/scrolling.md

Fix typo in cdk/scrolling documentaiton.
Fix #28544

docs(cdk/scrolling): fix typo

---

src/material-experimental/theming/_m3-tokens.scss

The Material 3 spec is inconsistent with how the list's item background should appear. E.g. in a select, menu, or bottom sheet - it should defer to those container colors (which are all different). This matches the internal implementation

fix(material/list): use transparent background for M3

---

src/material/core/theming/tests/m3-theme.spec.ts

Specifically it should:
1. Only emit styles under the user specified selector
2. Only emit CSS variable definitions

test: Ensure M3 theme is well behaved

---

src/material/tabs/tab-nav-bar/tab-nav-bar.ts

This appears to be a regression from #27862 where the `preventDefault` was removed both from space and enter presses. We still need it on space so that the page doesn't scroll.
Fixes #28392.

fix(material/tabs): prevent page scroll on space press

---

src/material/menu/menu.scss

Fixes that the icon the menu item was collapsing if the menu item text was too long.
Fixes #28502.

fix(material/menu): prevent icon from collapsing when text is long

---

src/material/list/selection-list.spec.ts
src/material/list/selection-list.ts

The buggy logic was using a truthiness check for checking for presence in a list; this check needs to compare against -1 instead.  This bug causes mismanagement of tabIndex, which caused an accessibility bug where, if the list of items changed, the selection list could not be tab selected until the selection list was focused.

Fixing indexOf usage bug when selection-list handles changes in items.

---

src/cdk/table/sticky-styler.ts
src/cdk/table/table.ts
tools/public_api_guard/cdk/table.md

Fixes that the table was throwing an error if all outlets are assigned before `ngAfterContentInit`.
Fixes #28538.

fix(cdk/table): error if outlets are assigned too early

---

src/material/_index.scss

Removes a bunch of private APIs that were re-exported from the root so that they can be reused in the legacy components.
Fixes #28297.

refactor(material/core): remove private APIs from root export

---

src/material/form-field/form-field.scss

* The 12px padding being applied to the mat-icon was preventing the form-field container height from condensing in lower densities.

fix(material/form-field): container height in lower densities

---

src/material-experimental/theming/_custom-tokens.scss
src/material-experimental/theming/_m3-density.scss
src/material-experimental/theming/_m3-tokens.scss
src/material/button/_button-theme.scss
src/material/core/theming/_inspection.scss
src/material/core/theming/tests/m3-theme.spec.ts
src/material/core/theming/tests/theming-inspection-api.spec.ts
src/material/core/tokens/m2/mat/_paginator.scss
src/material/core/typography/_all-typography.scss
src/material/paginator/_paginator-theme.scss
src/material/paginator/paginator.scss

Additional tests that help ensure our M3 theme conforms to the following rules:
- Does not add any additional selector specificity
- Emits only CSS variable definitions
- Emits each token for one and only one theme dimension
Also fixes several existing bugs that were discovered by the new tests.

fix(material-experimental/theming): Add more tests for M3 theme tokens

---

src/material/datepicker/calendar-body.scss
src/material/list/list.scss
src/material/progress-bar/progress-bar.scss

Updates all the places where we have to invert `text-align` manually to use `text-align: start`.
Fixes https://github.com/angular/components/issues/28572.

Avoid extra styles for text-align

---

src/dev-app/dev-app/dev-app-layout.html
src/dev-app/dev-app/dev-app-layout.ts

Fixes a minor gripe where the density tooltip closes when the button is pressed so the user needs to re-focus to see which density is currently active.

build: minor improvement to dev app density toggling

---

.github/CODEOWNERS

Currently everything under `/tools` is set to be owned by dev infra which means that if a public API golden doesn't have an owner, it falls back to dev infra. These changes assign all directories in `tools` *except* the goldens to dev infra so that the owners linting can pick up any missing files.
I've also redistributed the public API golden owners so they match the component owners, and I've added myself to the owners for the Tslint and Stylelint rules.

build: ensure component owners are assigned to public API changes

---

src/dev-app/list/list-demo.scss

Fix trailing icon color in M3 List demo. Fix icon color by removing style override in List demo.

docs(material/list): fix m3 demo trailing icon color

---

src/cdk/listbox/listbox.spec.ts
src/cdk/listbox/listbox.ts

Fixes that the listbox didn't allow focus back in when its active option is removed.
Fixes #28557.

fix(cdk/listbox): unable to tab in if active option is removed

---

src/cdk/testing/tests/webdriver.e2e.spec.ts

Attempt at deflaking the e2e tests by reducing the implicit timeout.

build: reduce implicit timeouts in webdriver test

---

src/material/paginator/paginator.ts
src/material/sort/sort.ts
tools/public_api_guard/material/paginator.md
tools/public_api_guard/material/sort.md

Removes the `mixinInitialized` from the sort header and paginator.

Remove usages of the initialized mixin

---

src/cdk/listbox/listbox.ts
tools/public_api_guard/cdk/listbox.md

Allows the `cdkOptionTypeaheadLabel` to be set to a nullable value.
Fixes #28464.

fix(cdk/listbox): make typeahead label nullable

---

src/dev-app/google-map/google-map-demo.html
src/dev-app/google-map/google-map-demo.ts
src/google-maps/google-map/google-map.spec.ts
src/google-maps/google-map/google-map.ts
src/google-maps/map-advanced-marker/map-advanced-marker.ts

Fixes that the `mapId` input wasn't being passed along to the map.
Fixes that the advanced marker wasn't being removed from the map on destroy.
Fixes https://github.com/angular/components/issues/28608.
Fixes https://github.com/angular/components/issues/28609.

Fixes for the advanced Google Maps marker

---

src/material-experimental/theming/_custom-tokens.scss
src/material/core/tokens/m2/mat/_expansion.scss
src/material/expansion/expansion-panel-header.html
src/material/expansion/expansion-panel-header.scss

Currently the expansion panel arrow is drawn with borders which makes it difficult to center. It's also problematic in high contrast mode where it renders as a rectangle. We've wanted to fix this for a while, but it breaks a lot of internal screenshot tests (see #10503).
These changes resolve the issue for apps using M3 by having two indicators that we toggle using tokens.
Fixes #28037.

fix(material/expansion): center indicator icon in M3

---

src/cdk/overlay/overlay-directives.spec.ts
src/cdk/overlay/overlay-directives.ts
src/cdk/overlay/position/flexible-connected-position-strategy.ts

Includes the following fixes:
Currently we emit the `positionChanges` event whenever a position is recalculcated which can be on each scroll event. These changes switch to doing so only if either the actual position or the scrolled state has changed.
Fixes that the `positionChange` event of the `CdkConnectedOverlay` directive was running outside the zone.
Fixes #28568.

Avoid emitting position change event unnecessarily and emit inside the zone

---

CHANGELOG.md

Cherry-picks the changelog from the "17.2.x" branch to the next branch (main).

docs: release notes for the v17.2.1 release

---

src/cdk/table/can-stick.ts
src/cdk/table/cell.ts
src/cdk/table/row.ts
src/material/table/cell.ts
src/material/table/row.ts
tools/dgeni/common/directive-metadata.ts
tools/dgeni/common/property-bindings.ts
tools/public_api_guard/cdk/table.md
tools/public_api_guard/material/table.md

Removes the final usages of TypeScript mixins in the CDK table by adding the sticky functionality to the individual usages. Ideally we'd have a base class for this, but that won't be usable in `CdkHeaderRowDef` and `CdkFooterRowDef` because they already inherit from `BaseRowDef` and we can't put the sticky functionality there, because `CdkRowDef` shouldn't support `sticky`. The logic is pretty basic so I think it's fine to duplicate it.

refactor(cdk/table): remove mixin function usages

---

src/material/autocomplete/autocomplete-trigger.ts
src/material/autocomplete/autocomplete.spec.ts

Fixes that if the user has `requireSelection` enabled, selects a value and then deletes a character while the input still has a value, the selection wasn't being cleared as expected.
Fixes #28432.

fix(material/autocomplete): requireSelection sometimes not clearing value when editing after selection

---

guides/theming.md
src/material/schematics/ng-add/theming/create-custom-theme.ts

Fixes that the template for a custom theme didn't include a typography config and a density.
Fixes #28642.

fix(material/schematics): add typography and density to custom theme

---

src/cdk-experimental/popover-edit/lens-directives.ts
src/cdk-experimental/popover-edit/table-directives.ts
src/cdk/menu/context-menu-trigger.ts
src/cdk/menu/menu-trigger.ts
src/cdk/portal/portal-directives.ts
src/cdk/tree/node.ts
src/material-experimental/column-resize/resizable-directives/common.ts
src/material-experimental/popover-edit/lens-directives.ts
src/material-experimental/popover-edit/table-directives.ts
src/material-experimental/selection/row-selection.ts
src/material-experimental/selection/selection-toggle.ts
src/material/tabs/ink-bar.ts
src/material/tabs/tab-label-wrapper.ts
src/material/tree/node.ts
src/material/tree/toggle.ts
tools/public_api_guard/material/tabs.md

Switches to using the object literal syntax in the `inputs` array which is a bit more readable than the string syntax. This shouldn't have an effect on users.

refactor(multiple): use object literal syntax in inputs array

---

src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
src/cdk/overlay/position/flexible-connected-position-strategy.ts

When the overlay is opening 'left-ward' (the content flows to the left) the margin is not calculated correctly because the margin is subtracted twice from the width ([line: 1092](https://github.com/angular/components/blob/0762d69b394343555488b5aaada9444dd1a5083a/src/cdk/overlay/position/flexible-connected-position-strategy.ts#L1092)), but [here](https://github.com/angular/components/blob/0762d69b394343555488b5aaada9444dd1a5083a/src/cdk/overlay/position/flexible-connected-position-strategy.ts#L805) it is added only once

fix(cdk/overlay): fix overlay margin in isBoundedByLeftViewportEdge

---

src/cdk/drag-drop/directives/drag-handle.ts
src/cdk/drag-drop/directives/drag-placeholder.ts
src/cdk/drag-drop/directives/drag-preview.ts
src/cdk/drag-drop/directives/drag.ts
src/cdk/drag-drop/drag-parent.ts
tools/public_api_guard/cdk/drag-drop.md

Currently `CdkDrag` resolves its helper directives (e.g. handle or preview) using a content query, but that doesn't work when it's applied as a host directive, because no content is being projected.
These changes switch to having the helper directives inject the closest drag directive and register themselves manually.
Fixes #28614.

fix(cdk/drag-drop): resolve helper directives with DI for proper hostDirectives support

---

src/dev-app/button-toggle/button-toggle-demo.html
src/dev-app/button-toggle/button-toggle-demo.ts
src/material/button-toggle/button-toggle.html
src/material/button-toggle/button-toggle.scss
src/material/button-toggle/button-toggle.spec.ts
src/material/button-toggle/button-toggle.ts
tools/public_api_guard/material/button-toggle.md

Needed as a part of the pre-work for M3, as well as a11y improvements.

fix(material/button-toggle): Add checkmark indicators with hideSingleSelectionIndicator and hideMultipleSelectionIndicator input and config options

---

guides/material-3.md

Encountering an error with $config.typography in the provided Angular Material 3 example.
I believe that `brand` and `bold` should be replaced with `brand-family` and `bold-weight` .

docs(material-3): fix typography config

---

src/material/form-field/_mdc-text-field-structure-overrides.scss

MDC was setting `will-change` on a couple of elements which caused significant scrolling performance issues on pages with a lot of form fields. These changes reset the `will-change`, because one of the elements wasn't being animated at all and the other one was only animating `transform` which is hardware-accelerated.
Fixes #27249.
For reference, this is before:
https://github.com/angular/components/assets/4450522/923fbb24-4984-47ba-b87b-5645fd344bf6
And this is after:
https://github.com/angular/components/assets/4450522/26565ce1-662d-4c52-b3a3-a5a209027ddb

perf(material/form-field): resolve scrolling performance issues

---

src/material/tooltip/tooltip.ts
tools/public_api_guard/material/tooltip.md

Right now it is not possible to customize the delay for the longpress on touch devices. Sometimesit might be desirable to use other value than 500ms, adding this as a `touchLongPressShowDelay` option for `MAT_TOOLTIP_DEFAULT_OPTIONS`

feat(material/tooltip): be able to customize the longpress delay

---

src/material/core/theming/_inspection.scss
src/material/core/theming/tests/theming-inspection-api.spec.ts
src/material/core/tokens/_token-utils.scss
src/material/core/tokens/m2/mat/_datepicker.scss
src/material/core/tokens/m2/mat/_fab-small.scss
src/material/core/tokens/m2/mat/_fab.scss
src/material/core/tokens/m2/mat/_filled-button.scss
src/material/core/tokens/m2/mat/_form-field.scss
src/material/core/tokens/m2/mat/_icon-button.scss
src/material/core/tokens/m2/mat/_menu.scss
src/material/core/tokens/m2/mat/_option.scss
src/material/core/tokens/m2/mat/_outlined-button.scss
src/material/core/tokens/m2/mat/_protected-button.scss
src/material/core/tokens/m2/mat/_radio.scss
src/material/core/tokens/m2/mat/_select.scss
src/material/core/tokens/m2/mat/_tab-header.scss
src/material/core/tokens/m2/mat/_text-button.scss
src/material/core/tokens/m2/mdc/_dialog.scss
src/material/core/tokens/m2/mdc/_filled-button.scss
src/material/core/tokens/m2/mdc/_filled-text-field.scss
src/material/core/tokens/m2/mdc/_outlined-button.scss
src/material/core/tokens/m2/mdc/_outlined-text-field.scss
src/material/core/tokens/m2/mdc/_protected-button.scss
src/material/core/tokens/m2/mdc/_radio.scss
src/material/core/tokens/m2/mdc/_text-button.scss

During the transition to tokens, we ended up with a bunch of places with hardcoded values in the form of `if($is-dark, #fff, #000)`. This is problematic for custom palettes, because the value is always hardcoded.
These changes attempt to derive the same values from the palette directly.
Fixes #26056.

fix(multiple): derive all token values from theme

---

src/material/core/tokens/m2/mdc/_checkbox.scss
src/material/core/tokens/m2/mdc/_chip.scss

Fixes a couple of hardcoded places in the tokens that were missed in #28664.

Palette followup fixes

---

src/material/autocomplete/autocomplete.scss

The autocomplete hides its dropdown if there are no options, but it is still clickable. These changes add `pointer-events: none` to prevent it from blocking interactions.
Fixes #28670.

fix(material/autocomplete): prevent hidden overlay from blocking clicks

---

src/material/schematics/BUILD.bazel
src/material/schematics/ng-add/setup-project.ts

In some custom scenarios adding the animations module can fail and the code that does it is outside of our control. These changes add some error handling so the rest of the schematic isn't interrupted.
Fixes #28640.

fix(material/schematics): don't interrupt ng add if adding the animations module fails

---

src/material/datepicker/date-range-input-parts.ts

When the user presses backspace on an empty end input of a range picker, we move focus to the start input and assume that the caret will be at the end. It appears that in some cases the browser decides to move it to the beginning instead so these changes reuse the logic from the left/right arrow handling to explicitly move it to the end on backspace as well.
Fixes #28665.

fix(material/datepicker): always move caret to the end of the start input on backspace

---

src/cdk/table/can-stick.ts
src/material/core/common-behaviors/color.ts
src/material/core/common-behaviors/disable-ripple.ts
src/material/core/common-behaviors/disabled.ts
src/material/core/common-behaviors/error-state.ts
src/material/core/common-behaviors/initialized.ts
src/material/core/common-behaviors/tabindex.ts
tools/public_api_guard/cdk/table.md
tools/public_api_guard/material/core.md

Marks the TypeScript mixin functions and their related interfaces as deprecated since they are difficult to use and not really necessary now that we have input transforms.

refactor(material/core): deprecate TypeScript mixin functions

---

src/material/datepicker/calendar-header.html
src/material/datepicker/calendar.scss

Fixes a bug in the Angular Material component where when the selected year range is updated by moving forward to the next range or by moving to the previous range the screenreader announces the original date range rather than the newly selected date range. This is because the label class was removing the updated value from the Firefox accessibility tree.
Fixes #28360

fix(material/datepicker): datepicker doesn't announce newly selected range in firefox

---

src/material/core/common-behaviors/error-state.ts

Updates a couple of the fields on `HasErrorState` to be nullable to align them with the `_ErrorStateTracker`.
Fixes #28688.

fix(material/core): mark fields on HasErrorState as nullable

---

CHANGELOG.md

Cherry-picks the changelog from the "17.2.x" branch to the next branch (main).

docs: release notes for the v17.2.2 release

---

CHANGELOG.md
package.json

Also this PR cherry-picks the changelog for v17.3.0-rc.0 into the main branch so that the changelog is up to date.

Update next branch to reflect new release-train "v17.4.0-next.0".

---

src/cdk/overlay/overlay-ref.ts
src/cdk/overlay/overlay.spec.ts
src/cdk/overlay/overlay.ts
src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
src/cdk/overlay/position/global-position-strategy.spec.ts
tools/public_api_guard/cdk/overlay.md

draft - Probably a breaking change and definitely not a good idea until `afterNextRender` runs only after `ApplicationRef.tick`. At the moment, this passes tests only because they're using fixtures and the fixtures are directly triggering change detection. However, in an application, the app component will refresh and trigger `afterNextRender` before the overlay views are refreshed.

refactor(cdk/overlay): Reduce dependency on NgZone

---

src/cdk/a11y/live-announcer/live-announcer.ts

Should it be possible for it to be undefined within the timeout body? No. But ZoneJS and test environments do weird things so it's better to be safe.

refactor(cdk/a11y): only call currentResolve if defined

---

src/material/slider/slider-input.ts
src/material/slider/slider-interface.ts

* the slider track animation would break in the case where a user clicks one thumb, tabs to the other, then uses an arrow key to change value.
* for some reason, this bug only happens when the slider is not discrete.

fix(material/slider): fix animation issue

---

README.md

The "What we're working on" section is more than a year out of date and historically we've kept forgetting to update it. These changes remove it for now.

docs: remove current work from readme

---

src/material/core/theming/_theming.scss

Fixes that theming validation for M2 themes was firing incorrectly, because the validation code was going through the `get-color-config`, `get-density-config` and `get-typography-config` functions which in turn were reading the internalized version of the theme where all the values were the same. Since Sass maps are immutable, they were being compared based on their values and always considered as the same theme.

fix(material/core): theming validation for m2 themes firing incorrectly

---

src/material/datepicker/calendar-body.ts
src/material/datepicker/calendar.spec.ts
src/material/datepicker/datepicker-base.ts

refactor(material/datepicker): Remove use of zone onStable for focus and dropdown positioning

---

src/material/tabs/paginated-tab-header.ts

Depends on moving overlay off of `NgZone.onStable` first (passing TGP after that)

refactor(material/tabs): Remove use of zone onStable for aligning tab header

---

src/material/form-field/form-field.scss

When `will-change` was removed in #27251, the form field lost its implicit stacking context which means that some of its descendants may be stacked on top of the container.
These changes add an explicit `z-index` on the container to resolve the issue.
Fixes #28708.

fix(material/form-field): ensure same stacking context as container

---

src/material/chips/chip.ts

refactor(material/chips): Remove use of zone onStable for blur events

---

src/material/core/private/ripple-loader.ts
src/material/core/ripple/ripple.ts

ripple-loader registers an event handler on the document to do event delegation. If there are multiple instances of ripple-loader on one page, then they will both try to handle events for [mat-ripple-loader-uninitialized] elements. If a namespace is provided, then the handler will only handle events for [mat-ripple-loader-uninitialized="{namespace}"] elements.

feat(material/core): Allow namespacing ripple-loader event handler

---

src/material/core/tokens/m2/mat/_fab-small.scss
src/material/core/tokens/m2/mat/_fab.scss
src/material/core/tokens/m2/mat/_filled-button.scss
src/material/core/tokens/m2/mat/_icon-button.scss
src/material/core/tokens/m2/mat/_outlined-button.scss
src/material/core/tokens/m2/mat/_protected-button.scss
src/material/core/tokens/m2/mat/_text-button.scss

The changes from #28664 appear to have caused ripples to be solid in some setups. These changes add a fallback to the old behavior if that's the case.
Fixes #28706.

fix(material/core): avoid solid ripples in buttons

---

src/cdk/table/table.ts
tools/public_api_guard/cdk/table.md

Handful of tests failing in g3 because they were not properly flushing and took screenshots in an intermediate state. This fixes the screenshots, diffs will need to be approved.

refactor(material/table): Remove use of zone onStable in scheduling sticky column updates

---

src/cdk/drag-drop/directives/drag-placeholder.ts
src/cdk/drag-drop/directives/drag-preview.ts

Fixes a regression from #28633 where using `cdkDragPlaceholder` or `cdkDragPreview` without a `cdkDrag` would throw. Technically this is a no-op, but it appears that folks started depending on the old behavior so these changes bring it back.
Fixes #28744.

fix(cdk/drag-drop): optionally inject parent drag in preview and placeholder

---

CHANGELOG.md

docs: release notes for the v17.3.1 release

---

src/cdk/listbox/listbox.ts
src/universal-app/kitchen-sink/kitchen-sink.html
src/universal-app/kitchen-sink/kitchen-sink.ts

This PR addresses the `ReferenceError: window is not defined` error that gets thrown when the CDK Listbox is rendered on the server.
The `_setPreviousActiveOptionAsActiveOptionOnWindowBlur` method in the `CdkListbox` class uses RxJS' `fromEvent` with `window` as its target. This is problematic when the application is being rendered on the server, since `_setPreviousActiveOptionAsActiveOptionOnWindowBlur` is called in the constructor.
The solution is to add a simple `_isBrowser` property that leverages the `Platform` API and a check in the constructor before calling `_setPreviousActiveOptionAsActiveOptionOnWindowBlur`.

fix(cdk/listbox): improve SSR compatibility by adding an _isBrowser check before calling _setPreviousActiveOptionAsActiveOptionOnWindowBlur

---

src/material/chips/chip.scss

Currently the remove icon is a bit brittle, because the size is set to `inherit` which only works if there's a `button` around it. These changes set the specific width instead.
Fixes #28467.

fix(material/chips): use concrete value for remove icon size

---

src/cdk/a11y/key-manager/list-key-manager.spec.ts
src/cdk/a11y/key-manager/list-key-manager.ts
tools/public_api_guard/cdk/a11y.md

Updates the `ListKeyManager` to support passing in a signal. Also expands the type to allow readonly arrays.
Fixes #28710.

fix(cdk/a11y): support signals in ListKeyManager

---

.github/workflows/deploy-dev-app-main-push.yml

Looks like the action simply relied on caching.

build: add missing yarn install block

---

.ng-dev/google-sync-config.json

For the primitives sync in FW, a new field was added, that is apparently not optional. This commit adds it now.

ci: add missing google sync config entry

---

src/material/tabs/paginated-tab-header.ts

Reverts angular/components#28653 due to reports of latency regression and test failures in g3

Revert "refactor(material/tabs): Remove use of zone onStable for aligning tab header"

---

src/material/menu/menu.spec.ts
src/material/menu/menu.ts

Depends on moving overlay off of `NgZone.onStable` first (passing TGP after that)

refactor(material/menu): Remove use of zone onStable to focus items

---

src/cdk-experimental/table-scroll-container/table-scroll-container.spec.ts
src/cdk/table/coalesced-style-scheduler.ts
src/cdk/table/table.spec.ts
src/material-experimental/column-resize/column-resize.spec.ts
tools/public_api_guard/cdk/table.md
tslint.json

Reverts angular/components#28747 because it broke column resize

Revert "refactor(material/table): remove use of zone onStable for style scheduling"

---

src/cdk-experimental/table-scroll-container/table-scroll-container.spec.ts
src/cdk/table/coalesced-style-scheduler.ts
src/cdk/table/table.spec.ts
src/material-experimental/column-resize/column-resize.spec.ts
tools/public_api_guard/cdk/table.md
tslint.json

Roll forward with fix for column resizer
This reverts commit b01f682c93601b5cbf076829c52addf46f2fa0da.

refactor(material/table): remove use of zone onStable for style scheduling

---

CHANGELOG.md
package.json

This PR cherry-picks the changelog for v18.0.0-next.2 into the main branch so that the changelog is up to date.

Bump version to "v18.0.0-next.2" with changelog.

---

CHANGELOG.md

docs: release notes for the v17.3.2 release

---

src/cdk-experimental/column-resize/resize-strategy.ts
src/cdk-experimental/table-scroll-container/table-scroll-container.ts
src/cdk/layout/media-matcher.ts
src/youtube-player/youtube-player.ts

Uses `setAttribute` to set the nonce, instead of DOM property in order to work properly in SSR.
Fixes #28780.

fix(multiple): set nonce using setAttribute

---

src/material/sort/sort-header.ts

Fixes that the sort header wasn't clearing its ARIA description when it gets destroyed, causing a memory leak.

fix(material/sort): clear aria description on destroy

---

CHANGELOG.md

docs: release notes for the v17.3.3 release

---

guides/material-3.md

The only actual change here is "anuglar" --> "angular", the rest is auto-formatting changes

docs: fix typo in M3 themeing docs

---

src/cdk/drag-drop/drag-ref.ts

Fixes #18296
If you set a value for `dragStartThreshold` greater than 0, it will throw console errors saying: "[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted."
```ts
@Component({
standalone: true,
selector: 'app-carousel',
changeDetection: ChangeDetectionStrategy.OnPush,
imports: [CdkDrag],
providers: [
{
provide: CDK_DRAG_CONFIG,
useValue: {
dragStartThreshold: 20,
},
},
],
```
Adding a condition to check if the event is `cancelable` will prevent that error.

fix(cdk/drag-drop): make sure event is cancelable before calling "preventDefault"

---

src/material/core/style/_menu-common.scss

Fixes a regression from #28470 where the nested menu icon isn't being inverted in RTL anymore.
Fixes #28813.

fix(material/menu): invert arrow in RTL

---

package.json

As discussed, these changes remove the `engines` enforcement since it can be annoying given that our project isn't sensitive to Node version changes.

build: remove engines field from package.json

---

src/cdk/scrolling/virtual-scroll-viewport.ts
src/dev-app/main.ts

This fixes an issue with the virtual scroll when run coalescing is
turned on which caused the virtual scroll viewport to incorrectly
determine when items has been rendered.

fix(cdk/scrolling): fix virtual scrolling jankiness with run coalescing

---

src/material/core/tokens/m2/mat/_list.scss
src/material/list/list.scss

* https://m2.material.io/components/navigation-drawer#states
* https://m3.material.io/components/navigation-drawer/specs

fix(material/list): nav list item border-radius

---

src/components-examples/material/chips/chips-overview/chips-overview-example.html

Fixes the documentation example in the Angular Material `chips` component. Previously the text description of static chips did not match code example
Fixes #28845

docs(material/chips): added an example that corresponds to the title static chips

---

CHANGELOG.md

docs: release notes for the v17.3.4 release

---

src/material/slider/slider.md

this screen is correct
but this screen is wrong because the value should go in the input tag

docs(material/slider): value should go in the input tag

---

src/cdk/drag-drop/directives/drag.spec.ts
src/cdk/drag-drop/drag-ref.ts

Fixes that text selection wasn't being disabled when the `cdkDrag` directive is inside the shadow DOM on Firefox. The issue appears to be that the `selectstart` event wasn't crossing the shadow boundary so we have to bind it at the shadow root as well.
Fixes #28792.

fix(cdk/drag-drop): text selection not disabled inside shadow dom on firefox

---

guides/material-3.md

docs: replace incorrect word in M3 theming guide

---

src/material/datepicker/datepicker-base.ts
src/material/datepicker/datepicker-content.html

We can set classes directly through `[class]` instead of having to import `NgClass`.

fix(material/datepicker): remove dependency on NgClass

---

src/material/autocomplete/autocomplete-trigger.ts
src/material/autocomplete/autocomplete.ts
tools/public_api_guard/material/autocomplete.md

Fixes that if one panel is tied to multiple triggers, it ends up becoming invisible because the original trigger resets the state after the next trigger picks it up. These changes avoid the state reset if the trigger has changed.
Fixes #28362.

fix(material/autocomplete): panel not visible when opened from multiple triggers

---

src/material/core/tokens/_token-utils.scss

Fixes that calling a theming mixin for a component that doesn't support color variants was throwing a cryptic error.
Fixes #28860.

fix(material/core): throw better error when mixin doesn't support color variants

---

src/material/menu/menu.html
src/material/menu/menu.ts

We can set classes directly through `[class]` instead of having to import `NgClass`. I had to adjust the code a bit, because the built-in `[class]` binding doesn't do diffing on the object literal.

fix(material/menu): remove dependency on NgClass

---

src/dev-app/google-map/BUILD.bazel
src/dev-app/google-map/google-map-demo.html
src/dev-app/google-map/google-map-demo.ts
src/google-maps/map-advanced-marker/map-advanced-marker.ts
src/google-maps/map-anchor-point.ts
src/google-maps/map-info-window/README.md
src/google-maps/map-info-window/map-info-window.ts
src/google-maps/map-marker/README.md
src/universal-app/kitchen-sink/kitchen-sink.html
src/universal-app/kitchen-sink/kitchen-sink.ts
tools/public_api_guard/google-maps/google-maps.md

Includes a couple of changes:
Currently the info window has two methods: one for any `MapAnchorPoint` and one for an advanced marker. These changes deprecate the latter and make the former compatible with advanced markers.
Adding new options to the Google Maps demo has been a bit cumbersome, because it's using `click` handlers on checkboxes to manage the state. These changes switch to using `ngModel`.

Clean up Google Maps advanced marker

---

CHANGELOG.md

docs: release notes for the v17.3.5 release

---

integration/yarn-pnp-compat/src/styles.scss
src/dev-app/theme.scss
src/material-experimental/theming/_m3-tokens.scss
src/material/_index.scss
src/material/core/_m2.scss
src/material/core/theming/tests/test-theming-bundle.scss
src/material/core/theming/tests/theming-definition-api.spec.ts
src/material/core/theming/tests/theming-inspection-api.spec.ts
src/material/core/theming/tests/theming-mixin-api.spec.ts
src/material/core/typography/_definition.scss

These changes rename the theming APIs that are specific to M2 to be prefixed with `m2-`. Subsequent changes will move the M3 APIs out of `experimental` and introduce a schematic to automatically migrate users.
The following APIs have been renamed. If you update using `ng update`, your app will be fixed automatically.
* `define-light-theme` to `m2-define-light-theme`
* `define-dark-theme` to `m2-define-dark-theme`
* `define-palette` to `m2-define-palette`
* `get-contrast-color-from-palette` to `m2-get-contrast-color-from-palette`
* `get-color-from-palette` to `m2-get-color-from-palette`
* `get-color-config` to `m2-get-color-config`
* `get-typography-config` to `m2-get-typography-config`
* `get-density-config` to `m2-get-density-config`
* `$red-palette` to `$m2-red-palette` …

feat(material/core): namespace m2-specific theming APIs

---

src/material/checkbox/_checkbox-theme.scss
src/material/core/tokens/_token-utils.scss

* Refactor token-utils.batch-create-token-values to allow us to pass in as many token maps as we want. This is change is relevant for components like the button which would want to pass in token maps for each button variant.

refactor(material/theming): make batch-create-token-values more flexible

---

src/components-examples/material/slide-toggle/slide-toggle-overview/slide-toggle-overview-example.html
src/dev-app/slide-toggle/slide-toggle-demo.html

Add examples of using the slide toggle with labelPosition="before". This renders the label before the toggle button.
Allow testing of issues when label is before the toggle button (#26880).
Relates to #26880

docs(material/slide-toggle): add examples with labelPosition="before"

---

src/cdk/a11y/key-manager/list-key-manager.ts

The `setLastItemActive` method of the `ListKeyManager` used the items input directly to determine the length without checking if it is a `Signal` instead of a `QueryList`.
The fix uses the already present `_getItemsArray` for safe access.

fix(cdk): handle signal based items in list key manager

---

src/cdk/testing/tests/webdriver.e2e.spec.ts
src/e2e-app/components/component-harness-e2e.ts
src/e2e-app/components/e2e-app/e2e-app.ts

Reworks the Webdriver tests to avoid the frequent timouts that we've been seeing. Working theory is that refreshing the page on each test and then waiting for Angular to stabizilize causes Webdriver to eventually time out. These changes switch to only loading the page once and resetting its state within the same session.

build: fix webdriver tests

---

src/material/schematics/ng-update/BUILD.bazel
src/material/schematics/ng-update/index.ts
src/material/schematics/ng-update/migrations/m2-theming-v18/index.ts
src/material/schematics/ng-update/migrations/m2-theming-v18/migration.ts
src/material/schematics/ng-update/test-cases/m2-theming.spec.ts

Adds a migration to account for the breaking changes in #28892. The migration changes all the places where functions and variables were renamed, as well as the usages of experimental APIs that were moved into stable.

fix(material/core): add migration for M2 theming APIs

---

src/material/progress-bar/progress-bar.html

The `buffer` mode requires an element that uses a `data:` URI in its styles. This can be problematic for CSP.
Fixes #28938.

fix(material/progress-bar): avoid CSP issues for apps not using buffer mode

---

src/material/datepicker/date-range-input.ts
src/material/form-field/form-field-control.ts
src/material/form-field/form-field.html
src/material/select/select.ts
tools/public_api_guard/material/datepicker.md
tools/public_api_guard/material/form-field.md
tools/public_api_guard/material/select.md

Adds an option to remove the `for` attribute from the `<label>` inside the form field from elements that can't be labeled. Also applies the new option to `mat-select` and `mat-date-range-picker`. This isn't an accessibility regression, because those elements were already being labeled using `aria-labelledby`.
Fixes #27241.

fix(multiple): remove label for attribute on non-native elements

---

src/cdk/drag-drop/directives/drag.spec.ts
src/cdk/drag-drop/dom/root-node.ts
src/cdk/drag-drop/dom/styling.ts
src/cdk/drag-drop/drag-ref.ts
src/cdk/drag-drop/preview-ref.ts

Wraps the preview element in a native popover which allows it to always be rendered on top of everything and to avoid issues when the parent element has a `transform`.
Fixes #28889.

fix(cdk/drag-drop): use native popover to avoid stacking issues with preview

---

package.json

Updates the patch deployment scripts to avoid a ts-node error.

build: fix patch deployment

---

CHANGELOG.md

docs: release notes for the v17.3.6 release

---

CHANGELOG.md
package.json

Also this PR cherry-picks the changelog for v18.0.0-next.6 into the main branch so that the changelog is up to date.

Update next branch to reflect new release-train "v18.1.0-next.0".

---

src/material/dialog/dialog-content-directives.ts
src/material/dialog/dialog.spec.ts
tools/public_api_guard/material/dialog.md

Adds `CdkScrollable` to `MatDialogContent` so that overlays inside of it can reposition on scroll.
Fixes #28936.

fix(material/dialog): mark dialog content as scrollable

---

guides/material-3.md
src/material/_index.scss

Fixes that the `$spring-green-palette` wasn't being exported.
Fixes #28924.

fix(material/core): export all available M3 palettes

---

src/cdk/drag-drop/preview-ref.ts

Fixes that the `showPopover` call was being minified by Closure and preventing the popover from opening.

fix(cdk/drag-drop): resolve incompatibility with property minification

---

src/material/core/tokens/m2/mat/_switch.scss
src/material/core/tokens/m3/mat/_switch.scss
src/material/slide-toggle/slide-toggle.scss

Fixes that the M3 slide toggle didn't have an outline when it's selected in high contrast mode.

fix(material/slide-toggle): no outline when selected in high contrast mode

---

src/cdk/drag-drop/BUILD.bazel
src/cdk/drag-drop/directives/drag.spec.ts
src/cdk/drag-drop/drag-drop.ts
src/cdk/drag-drop/preview-ref.ts
src/cdk/drag-drop/resets.scss

Includes the following fixes related the preview popovers:
After #28945 the preview is inserted into a `popover` element which has a user agent styling of `color: canvastext`. These changes reset it to `inherit` to match the old behavior.
Switches back to positioning the preview directly instead of using a wrapper which can be breaking for existing apps. Instead we load a stylesheet dynamically with the necessary resets.
Fixes #28974.

Preview popover fixes

---

src/cdk/drag-drop/drag-drop.md
src/components-examples/cdk/drag-drop/BUILD.bazel
src/components-examples/cdk/drag-drop/cdk-drag-drop-table/cdk-drag-drop-table-example.css
src/components-examples/cdk/drag-drop/cdk-drag-drop-table/cdk-drag-drop-table-example.html
src/components-examples/cdk/drag-drop/cdk-drag-drop-table/cdk-drag-drop-table-example.ts
src/components-examples/cdk/drag-drop/index.ts

Adds an example that shows how to drag and drop table rows Fixes #25168

docs(cdk\drag-drop): Add table drag drop example

---

CHANGELOG.md

docs: release notes for the v18.0.0-rc.0 release

---

CHANGELOG.md

docs: release notes for the v17.3.7 release

---

src/material/button/icon-button.ts
tools/public_api_guard/material/button.md

Fixes that the icon button anchor was using the base button template instead of the icon button one.
Fixes #28990.

fix(material/button): incorrect template for icon button anchor

---

src/material/chips/chip.scss

Remaps some of the tokens so that the `highlighted` input can work in M3.
Fixes #28923.

fix(material/chips): highlighted not working in M3

---

src/cdk/menu/context-menu-trigger.ts
src/cdk/menu/menu-trigger-base.ts
src/cdk/menu/menu-trigger.ts
tools/public_api_guard/cdk/menu.md

Adds an injection token that allows users to configure the scroll strategy of a CDK menu.
Fixes #28965.

fix(cdk/menu): allow for scroll strategy to be configured

---

CHANGELOG.md

docs: release notes for the v17.3.8 release

---

scripts/build-packages-dist.mts

Temporarily force the local spawn strategy for building during release due to seeing unexpected and yet to be traced failures in the Sass compiler within workers.

build: temporarily force local spawn strategy during release builds

---

CHANGELOG.md

docs: release notes for the v18.0.0-rc.1 release

---

src/material/button/button.spec.ts
src/material/core/private/ripple-loader.ts

Fixes the following issues that prevented the button ripples from being loaded in the shadow DOM:
* We weren't resolving the event target properly.
* We were using `click` as a fallback which happens too late for the very first ripple. These changes switch to `mousedown`.
Fixes #29011.

fix(material/core): ripple loader not working in shadow DOM

---

src/material/core/ripple/ripple-renderer.ts

fix(material/core): ripple element not destroyed after trigger change

---

src/material/datepicker/calendar-body.html
src/material/datepicker/calendar-body.ts
src/material/datepicker/month-view.html
src/material/datepicker/month-view.ts
tools/public_api_guard/material/datepicker.md

Fixes that the calendar was triggering some newly-introduced warnings from the framework.
Fixes #29008.

fix(material/datepicker): resolve repeater warnings in calendar

---

src/cdk/observers/private/shared-resize-observer.ts

The function `loopLimitExceededErrorHandler` never logs "ResizeObserver loop limit exceeded" errors because an [error event](https://developer.mozilla.org/en-US/docs/Web/API/Window/error_event) (fired by a `Window` object) is an instance of [`ErrorEvent`](https://developer.mozilla.org/en-US/docs/Web/API/ErrorEvent).

fix(cdk/observers): logs "ResizeObserver loop limit exceeded" errors

---

src/cdk/overlay/overlay-directives.ts

Adds some logic to skip the trigger when considering clicks outside of the overlay since filtering them is the most common case (e.g. we do it in some of our components) and can be annoying to deal with.
Fixes #28949.

fix(cdk/overlay): skip trigger interactions in outside click event

---

CHANGELOG.md

docs: release notes for the v17.3.9 release

---

CHANGELOG.md

docs: release notes for the v18.0.0-rc.2 release
