- src/material/chips/chip-grid.spec.ts
- src/material/chips/chip-input.ts
- src/material/chips/chip-row.spec.ts
- src/material/chips/chip.ts
- tools/public_api_guard/material/chips.md
We have some logic that prevents chip removal if the users is holding down the backspace key. It currently breaks down in the case where a value is pasted into the input via click.
These changes simplify our detection by using `KeyboardEvent.repeat` which also resolves the paste issue.
> fix(material/chips): simplify repeat chip removal prevention

- src/cdk/tree/tree.spec.ts
- src/cdk/tree/tree.ts
- src/components-examples/cdk/tree/cdk-tree-complex/cdk-tree-complex-example.html
- src/components-examples/cdk/tree/cdk-tree-custom-key-manager/cdk-tree-custom-key-manager-example.html
- src/components-examples/cdk/tree/cdk-tree-flat-children-accessor/cdk-tree-flat-children-accessor-example.html
- src/components-examples/cdk/tree/cdk-tree-flat-level-accessor/cdk-tree-flat-level-accessor-example.html
- src/components-examples/cdk/tree/cdk-tree-flat/cdk-tree-flat-example.html
- src/components-examples/cdk/tree/cdk-tree-nested-children-accessor/cdk-tree-nested-children-accessor-example.html
- src/components-examples/cdk/tree/cdk-tree-nested-level-accessor/cdk-tree-nested-level-accessor-example.html
- src/components-examples/cdk/tree/cdk-tree-nested/cdk-tree-nested-example.html
- src/components-examples/material/tree/tree-dynamic/tree-dynamic-example.html
- src/components-examples/material/tree/tree-flat-overview/tree-flat-overview-example.html
- src/components-examples/material/tree/tree-harness/tree-harness-example.html
- src/components-examples/material/tree/tree-loadmore/tree-loadmore-example.html
- src/components-examples/material/tree/tree-nested-overview/tree-nested-overview-example.html
- tools/public_api_guard/cdk/tree.md
Implement typeahead labels for Tree. Follow the established pattern that Menu and List use.
- implement CdkTreeNode#cdkTreeNodeTypeaheadLabel
- implement CdkTreeNode#getLabel
Copy of #28251
> fix(cdk/tree): implement typeahead label

- src/cdk/drag-drop/drag-drop-registry.ts
- src/cdk/drag-drop/drag-drop.ts
- src/cdk/drag-drop/public-api.ts
Currently we load the reset styles for the preview up-front which seems to break some Jest tests since Jest's CSS parser doesn't understand layers.
These changes switch to loading the styles only once dragging has started.
Fixes #29053.
> fix(cdk/drag-drop): defer loading reset styles

- .github/workflows/deploy-dev-app-main-push.yml
- .github/workflows/dev-infra.yml
- .github/workflows/google-internal-tests.yml
- .github/workflows/pr.yml
- .github/workflows/preview-build-dev-app.yml
- .github/workflows/preview-deploy-dev-app.yml
- .github/workflows/scheduled-ci.yml
Split the workflows to prevent unexpected overlap between environments.
> ci: split ci into privileged and unprivileged workflows

- src/cdk/menu/context-menu-trigger.spec.ts
- src/cdk/menu/context-menu-trigger.ts
- src/cdk/menu/menu-item-checkbox.spec.ts
- src/cdk/menu/menu-item-radio.spec.ts
- src/cdk/menu/menu-item.spec.ts
- src/cdk/menu/menu-trigger.spec.ts
- src/cdk/menu/pointer-focus-tracker.spec.ts
- src/material/menu/menu.spec.ts
This removes 'provideZoneChangeDetection' from menu tests. Change summary:
* Many tests set inputs directly. This isn't really how it happens in applications - inputs set from the template automatically mark components for check. When tests set inputs directly like this, they need to call `markForCheck` manually (or something similar).
* One test seems to be calling a public API (`CdkContextMenuTrigger.open`) that failed to call `markForCheck` so that was added to the implementation
* `fakeAsync` had an additional timer so I just added `flush` to make it work.
> test(menu): remove provideZoneChangeDetection for all menu tests

- CHANGELOG.md
> docs: release notes for the v18.0.0-rc.3 release

- CHANGELOG.md
> docs: release notes for the v17.3.10 release

- CHANGELOG.md
> docs: release notes for the v18.0.0 release

- guides/material-2.md
- guides/theming-your-components.md
- guides/theming.md
Fixes some broken links to the M2 guide.
Fixes #29101.
> docs: fix broken links

- src/youtube-player/youtube-player.ts
Fixes a couple of issues:
1. We were using the `PlayerState` enum before the API has been loaded which will cause a runtime error because the enum is usually read off the `window`.
2. Fixes that calling the `playVideo` method wasn't load the YouTube API.
Fixes #29030.
> fix(youtube-player): error when interacting with the player before the API has been loaded

- src/material/tabs/paginated-tab-header.ts
Fixes a bug reported internally where the tabs pagination was going into an infinite loop at some widths.
The root cause is a bit unclear, but it looks like in some cases Safari rounds up the `scrollWidth` and in some it doesn't which we end up hitting when adding/removing the pagination.
These changes work around it by adding a 5px threshold that needs to be crossed before we start showing the pagination. The threshold shouldn't be noticable for users since the tabs have a 24px padding on each side.
> fix(material/tabs): avoid pagination infinite loop in safari

- package.json
husky v9 deprecated `husky install` command. We need to use `husky` command instead to avoid the below warning when running `yarn`.
```
$ husky install
install command is deprecated
```
Husky v9 changelog(https://github.com/typicode/husky/releases/tag/v9.0.1):
> Removed husky install. Use husky or husky some/dir for the same functionality (deprecation notice to be added).
> build: fix deprecated husky install command

- src/material/form-field/form-field.ts
Fixes the outline label position when a prefix is present and the form field is not yet rendered.
Fixes #29064
> fix(material/form-field): outline label position

- src/material/form-field/form-field.ts
Reverts #29123, because it broke some internal tests.
> Revert "fix(material/form-field): outline label position (#29123)"

- CHANGELOG.md
> docs: release notes for the v18.0.1 release

- src/material/slider/slider.ts
Fixes the bug in the Angular Material 'slider' component. 
Changed the function in the calculation from .floor to .round 
Due to floating-point precision in JavaScript. (1 - 0.9) / 0.1 evaluates to 0.9999999999999999 
Even though mathematically it should be 1
The calculation in the code resulted in slightly smaller value. 
Math.floor(0.9999999999999999) evaluates to 0.
Math.round(0.9999999999999999) evaluates to 1.
Fixes #29084
> fix(material/slider): Tick marks changes position as the slider is changed (for a step that is decimal number)

- src/material/checkbox/_checkbox-common.scss
- src/material/checkbox/_checkbox-theme.scss
- src/material/checkbox/checkbox.scss
- src/material/core/tokens/m2/mdc/_checkbox.scss
- src/material/list/BUILD.bazel
- src/material/list/_list-item-hcm-indicator.scss
- src/material/list/_list-theme.scss
- src/material/list/list-option.scss
Simplifies the styles for the checkbox to make them smaller and easier to follow.
> refactor(material/checkbox): simplify structural styles

- src/material/schematics/ng-add/theming/create-custom-theme.ts
adds project name to commented theme styles & backwards compatibility mixins on generating custom theme
> refactor(material/schematics): add project name for theme styles & backwards compatibility

- src/material/schematics/ng-update/migrations/m2-theming-v18/migration.ts
- src/material/schematics/ng-update/test-cases/m2-theming.spec.ts
Fixes that the migration didn't account for CRLF line endings when figuring out the Sass namespace.
Fixes #29147.
> fix(material/schematics): theming API migration not working with CRLF line endings

- src/material/snack-bar/_snack-bar-theme.scss
- src/material/snack-bar/snack-bar-container.html
- src/material/snack-bar/snack-bar-container.scss
- src/material/snack-bar/snack-bar-container.ts
Cleans up the snack bar's structural styles to make them smaller and easier to maintain.
> refactor(material/snack-bar): clean up structural styles

- src/material/core/ripple/_ripple.scss
When we create previews and placeholders for the drag&drop module, we clone the DOM node in its current state. This means that if there are ripples, they'll be in the clone as well.
These changes add a default styles to hide the ripple in such cases since it'll never disappear.
Fixes #29159.
> fix(material/core): hide ripples inside drag&drop elements

- src/cdk/scrolling/scroll-dispatcher.spec.ts
- src/cdk/scrolling/scroll-dispatcher.zone.spec.ts
- src/cdk/scrolling/viewport-ruler.spec.ts
- src/cdk/scrolling/viewport-ruler.zone.spec.ts
- src/cdk/text-field/autofill.zone.spec.ts
- src/dev-app/main.ts
- src/material-experimental/popover-edit/popover-edit.spec.ts
- tools/tslint-rules/noZoneDependenciesRule.ts
- tslint.json
Only allow `provideZoneChangeDetection` and `NgZone` in tests that explicitly test integration with Zone.js (and tests which have not yet been migrated to zoneless).
> test: Extend zoneless lint to cover tests

- CHANGELOG.md
> docs: release notes for the v18.0.2 release

- src/material/core/theming/_config-validation.scss
- src/material/core/theming/_definition.scss
- src/material/core/tokens/_m3-tokens.scss
- src/material/schematics/ng-generate/m3-theme/README.md
The component tokens (CSS variables) can reference the system variables abstraction with the configuration use-system-variables at the color and typography options level. 
With this PR, you can replace the `--sys-` prefix with, for example, `--md-sys-`. This makes it more flexible to adopt your own tokens, which are based on the Material 3 naming scheme but include a custom design system prefix, e.g., `--labs-sys-`. This saves additional mapping.
Demo configuration:
```scss
// Create a theme with the specified color type and density.
@function create-theme($type: light, $density: 0) {
@return mat.define-theme((
color: (
theme-type: $type,
primary: mat.$azure-palette,
tertiary: mat.$blue-palette,
use-system-variables: true,
system-variables-prefix: md-sys,
),
typography: …
```
> feat(material/core): add option to configure prefix of system variables

- src/material/_index.scss
> fix(material/snack-bar): fix overrides mixin name typo

- src/dev-app/list/list-demo.scss
- src/material/core/tokens/m3/mat/_divider.scss
- src/material/core/tokens/m3/mat/_expansion.scss
- src/material/core/tokens/m3/mat/_stepper.scss
- src/material/core/tokens/m3/mat/_table.scss
Fixes color contrast issues with non-text elements, including divider. Changed from "outline-variant" to "outline" colors to pass 3:1 ratio between light/dark mode backgrounds. Also changing for expansion, stepper, and table so they can also pass not-text color contrast.
Before (Light mode):
FG- #c4c6d0 (neutral-variant80)
BG- #fff
Ratio: 1.70:1
Screenshot: 
After (Light mode):
FG- #747775 (neutral-variant50)
BG- #fff
Ratio: 4.52:1
Screenshot: 
Before (Dark mode):
FG- #44474E (neutral-variant30)
BG- #1f1f1f
Ratio: 1.77:1
Screenshot: 
After (Dark mode):
FG- #8e9099 (neutral-variant60)
BG- #1f1f1f
Ratio: 5.17:1
Screenshot: 
Fixes b/291964002
> fix(material/divider): non-text color contrast issues

- src/cdk/dialog/dialog-container.ts
- src/material/dialog/dialog-container.ts
- src/material/dialog/dialog.spec.ts
fixes #29194, blocked on https://github.com/angular/components/pull/29203
> fix(material/dialog): Make autofocus work with animations disabled

- src/material/bottom-sheet/bottom-sheet.spec.ts
Fixes some tests that were broken by a recent change.
> test(material/bottom-sheet): fix broken tests

- src/cdk/dialog/dialog.md
Added instructions for including structural styles required by CDK dialogs. Noted that without importing `@angular/cdk/overlay-prebuilt.css` in the global stylesheet, CDK dialogs did not work correctly.
> docs(cdk/dialog): add initial setup instructions for CDK dialogs

- src/cdk/drag-drop/directives/config.ts
- src/cdk/drag-drop/directives/drop-list-shared.spec.ts
- src/cdk/drag-drop/directives/mixed-drop-list.spec.ts
- src/cdk/drag-drop/directives/single-axis-drop-list.spec.ts
- src/cdk/drag-drop/directives/test-utils.spec.ts
- src/cdk/drag-drop/drag-drop.md
- src/cdk/drag-drop/drag-ref.ts
- src/cdk/drag-drop/drop-list-ref.ts
- src/cdk/drag-drop/sorting/drop-list-sort-strategy.ts
- src/cdk/drag-drop/sorting/mixed-sort-strategy.ts
- src/cdk/drag-drop/sorting/single-axis-sort-strategy.ts
- src/components-examples/cdk/drag-drop/cdk-drag-drop-mixed-sorting/cdk-drag-drop-mixed-sorting-example.css
- src/components-examples/cdk/drag-drop/cdk-drag-drop-mixed-sorting/cdk-drag-drop-mixed-sorting-example.html
- src/components-examples/cdk/drag-drop/cdk-drag-drop-mixed-sorting/cdk-drag-drop-mixed-sorting-example.ts
- src/components-examples/cdk/drag-drop/index.ts
- src/dev-app/drag-drop/BUILD.bazel
- src/dev-app/drag-drop/drag-drop-demo.html
- src/dev-app/drag-drop/drag-drop-demo.scss
- src/dev-app/drag-drop/drag-drop-demo.ts
- tools/public_api_guard/cdk/drag-drop.md
Currently the drop list sorts items by moving them using a `transform` which keeps the DOM stable and allows for the sorting to be animated, but has the drawback of only allowing sorting in one direction.
These changes implement a new `DropListSortStrategy` that allows sorting of lists that can wrap by moving the DOM nodes around directly, rather than via a `transform`. It has the caveat that it can't animate the sorting action.
The new strategy can be enabled by setting `cdkDropListOrientation="mixed"`.
Fixes #13372.
> feat(cdk/drag-drop): add mixed orientation support

- CHANGELOG.md
> docs: release notes for the v18.0.3 release

- src/material/core/_core-theme.scss
- src/material/core/_core.scss
- src/material/core/tokens/m2/mat/_app.scss
- src/material/core/tokens/m2/mat/_menu.scss
- src/material/core/tokens/m3/mat/_app.scss
- src/material/core/tokens/m3/mat/_menu.scss
- src/material/menu/menu.spec.ts
- src/material/menu/menu.ts
- src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html.template
- src/material/tabs/tab-header.html
- src/material/tabs/tab-nav-bar/tab-nav-bar.html
Includes a couple of fixes that implement the elevation classes for M3 and update some existing components to handle them properly.
Fixes #28618.
> Elevation classes in M3

- src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.ts
Fixes that if an overlay contains a component using shadow DOM encapsulation, the clicks within it will be incorrectly picked up as outside clicks.
Fixes #29241.
> fix(cdk/overlay): incorrectly dispatching outside click for shadow DOM

- guides/getting-started.md
- guides/schematics.md
- guides/theming.md
Adds a table with all of the pre-built themes in the theming guide.
Fixes #29152.
> docs(material/core): list out pre-built themes

- src/material/core/_core-theme.scss
Fixes that we weren't generating the CSS variables for `mat-optgroup` in an M3 theme.
> fix(material/core): generate mat-optgroup tokens in M3

- src/material/core/tokens/m2/mat/_app.scss
Fixes a missing import when generating elevation tokens.
> build: fix missing elevation import

- src/components-examples/material/card/card-harness/card-harness-example.spec.ts
> docs(material/card): remove unneeded null coalescing from example

- src/material/menu/menu.scss
Simplifies the menu structural styles to make them more maintainable.
> refactor(material/menu): simplify structural styles

- src/cdk/tree/tree.spec.ts
- src/cdk/tree/tree.ts
- src/material/tree/tree.spec.ts
- tools/public_api_guard/cdk/tree.md
Fixed an issue to where leaf nodes were wrongly being assigned the aria-expanded attribute, which could confuse screen reader users.
https://screencast.googleplex.com/cast/NjMzNDkwNjM4MzcyODY0MHxkMTY5ZTdkNC05Mw
Fixes #21922
Fixes #21143
> fix(material/tree): aria-expanded attribute should not appear in the leaf node

- src/material/core/option/optgroup.scss
- src/material/core/option/option.scss
Simplifies the structural styles of `mat-option` and `mat-optgroup` to make them easier to maintain.
> refactor(material/core): simplify structural styles

- src/cdk/tree/tree.spec.ts
- src/cdk/tree/tree.ts
- src/material/tree/tree.spec.ts
- tools/public_api_guard/cdk/tree.md
This reverts commit 43b8dcbb1f17a9d5fcedc88e996c241ab9e28dd8.
> Revert "fix(material/tree): aria-expanded attribute should not appear in the leaf node (#29096)"

- src/material/tsconfig.json
The `tools/` directory was previously missing which caused red squigglies when we tried to import from the tools directory. e.g., in our theming tests: `import {createLocalAngularPackageImporter} from '../../../../../tools/sass/local-sass-importer';`
> build: fix rootDir

- src/material/bottom-sheet/bottom-sheet-container.ts
Fixes that when closing and immediately reopening bottom sheet in a zoneless app, we were causing a "changed after checked" error to be thrown. It seems to be because we were calling `detectChanges` without marking for check first.
Fixes #29258.
> fix(material/bottom-sheet): changed after checked error with zoneless

- src/material/menu/menu.scss
If the same menu is passed to different triggers and the user moves quickly between the menus (e.g. in a nested menu), an empty menu panel can show up while the closed menu is animating away. This is because the content needs to be moved over to the new menu.
These changes hide the empty menu panel immediately using CSS to avoid the glichy behavior.
> fix(material/menu): animation issue when same menu is used for multiple nested triggers

- src/cdk/drag-drop/directives/drop-list-shared.spec.ts
- src/cdk/drag-drop/directives/drop-list.ts
- src/cdk/drag-drop/drop-list-ref.ts
- src/cdk/drag-drop/sorting/drop-list-sort-strategy.ts
- src/cdk/drag-drop/sorting/mixed-sort-strategy.ts
- src/cdk/drag-drop/sorting/single-axis-sort-strategy.ts
- tools/public_api_guard/cdk/drag-drop.md
Adds the new `cdkDropListElementContainer` input that allows users to specify a different element that should be considered the root of the drop list. This is useful in the cases where the user might not have full control over the DOM between the drop list and the items, like when making a tab list draggable.
Fixes #29140.
> feat(cdk/drag-drop): add the ability to specify an alternate drop list container

- CHANGELOG.md
> docs: release notes for the v18.0.4 release

- src/material/sidenav/drawer.ts
Fixes that the sidenav wasn't triggering change detection when closing via a escape key press.
> fix(material/sidenav): not closing on escape key press

- src/material/button/button-base.ts
- src/material/button/button.spec.ts
- tools/public_api_guard/material/button.md
Adds the ability to configure the default button color through the `MAT_BUTTON_CONFIG` injection token.
> feat(material/button): allow button color to be configured through DI

- src/components-examples/material/form-field/form-field-custom-control/form-field-custom-control-example.ts
Ensure that `effect` code that emits on public rxjs streams is run as untracked.
> docs: Fix usage of `effect` in examples

- src/material/button-toggle/button-toggle.ts
Fixes that the button toggle was selecting disabled buttons and attempting to focus them when using the arrow keys.
Fixes #29304.
> fix(material/button-toggle): skip disabled buttons during keyboard navigation

- src/material/core/style/_vendor-prefixes.scss
- src/material/progress-bar/_progress-bar-theme.scss
- src/material/progress-bar/progress-bar.scss
Reworks the progress bar styles to be simpler and easier to maintain.
> refactor(material/progress-bar): simplify structural styles

- src/material/tooltip/_tooltip-theme.scss
- src/material/tooltip/tooltip.html
- src/material/tooltip/tooltip.scss
Simplifies the structural styles of `MatTooltip` to make them smaller and easier to maintain.
> refactor(material/tooltip): simplify structural styles

- src/material/autocomplete/autocomplete-trigger.ts
- src/material/chips/chip-grid.ts
- src/material/radio/radio.ts
- tools/public_api_guard/material/chips.md
blocked on https://github.com/angular/components/pull/29295
> fix(multiple): remove workarounds for formControl directive

- src/material/button/_button-base.scss
Some time ago we started stacking the button's text on top of the ripple and touch target for accessibility reasons, but we didn't apply the same to icons.
Fixes #28888.
> fix(material/button): stack icons on top of touch target

- src/material/core/tokens/_density.scss
- src/material/core/tokens/m2/_index.scss
- src/material/core/tokens/m2/mdc/_secondary-navigation-tab.scss
- src/material/core/tokens/m3/_index.scss
- src/material/core/tokens/m3/mdc/_secondary-navigation-tab.scss
- src/material/core/tokens/tests/test-validate-tokens.scss
- src/material/tabs/_tabs-common.scss
- src/material/tabs/_tabs-theme.scss
Simplifies the structural styles for the tabs to make them smaller and easier to maintain. I also had to rename the prefix for the `tab` tokens, because MDC was doing something weird where it was renaming the tokens to be `mdc-secondary-navigation-tab` instead of `tab`.
> refactor(material/tabs): simplify structural styles

- guides/typography.md
Removes an oversight about a deprecated `input` typography level
Fixes #28245
> docs(material/core): update the typography guide

- CHANGELOG.md
> docs: release notes for the v18.0.5 release

- src/material/core/ripple/ripple-renderer.ts
- src/material/slider/slider.spec.ts
Currently ripples assume that after the transition is started, either a `transitionend` or `transitioncancel` event will occur. That doesn't seem to be the case in some browser/OS combinations and when there's a high load on the browser.
These changes add a fallback timer that will clear the ripples if they get stuck.
Fixes #29159.
> fix(material/core): add fallback if ripples get stuck

- src/components-examples/material/expansion/expansion-steps/expansion-steps-example.html
- src/components-examples/material/sidenav/sidenav-responsive/sidenav-responsive-example.html
- src/material/badge/badge.ts
- src/material/button/fab.ts
- src/material/checkbox/checkbox-config.ts
- src/material/checkbox/checkbox.md
- src/material/chips/chips.md
- src/material/datepicker/datepicker-base.ts
- src/material/datepicker/datepicker.md
- src/material/form-field/form-field.ts
- tools/public_api_guard/material/button.md
This is the last of the color examples and descriptions that need to be updated I found in doing a final pass to check all the components docs
> docs: remove color property from remaining examples and overview pages and make description comment consistent across components

- src/material/card/_card-theme.scss
- src/material/card/card.scss
- src/material/core/tokens/m2/mdc/_elevated-card.scss
- src/material/core/tokens/m2/mdc/_outlined-card.scss
- src/material/core/tokens/m3/mdc/_elevated-card.scss
- src/material/core/tokens/m3/mdc/_outlined-card.scss
Simplifies the structural styles for the card to make them smaller and easier to maintain.
> refactor(material/card): simplify structural styles

- src/material/button/_icon-button-theme.scss
- src/material/button/icon-button.scss
Simplifies the structural styles for the icon button to make them smaller and easier to maintain.
> refactor(material/button): simplify icon button structural styles

- src/material/button/_fab-theme.scss
- src/material/button/button-base.ts
- src/material/button/fab.scss
- src/material/core/tokens/m2/mdc/_extended-fab.scss
- src/material/core/tokens/m2/mdc/_fab-small.scss
- src/material/core/tokens/m2/mdc/_fab.scss
- src/material/core/tokens/m3/mdc/_extended-fab.scss
- src/material/core/tokens/m3/mdc/_fab-small.scss
- src/material/core/tokens/m3/mdc/_fab.scss
- src/material/core/tokens/tests/test-validate-tokens.scss
Simplifies the styles of the FAB to make them smaller and easier to maintain.
> refactor(material/button): simplify FAB structural styles

- CHANGELOG.md
> docs: release notes for the v18.0.6 release

- CHANGELOG.md
- package.json
Also this PR cherry-picks the changelog for v18.1.0-rc.0 into the main branch so that the changelog is up to date.
> Update next branch to reflect new release-train "v18.2.0-next.0".

- src/material/chips/chip-grid.spec.ts
- src/material/chips/chip-grid.ts
Currently the up/down arrows behave in the same way as left/right, however that's incorrect based on [the reference implementation](https://www.w3.org/WAI/ARIA/apg/patterns/grid/examples/layout-grids/#ex2_label) which shows them navigating between the rows.
These changes update the logic in the chip grid so that it matches the expected behavior.
Fixes #29359.
> fix(material/chips): navigate between rows on up/down arrow

- src/cdk/drag-drop/resets.scss
When we create the preview and placeholder, we set `pointer-events: none` on them so they don't interfere with the `elementFromPoint` calls, however descendants of the element could be resetting it back to `auto` for themselves. These changes update the reset to prevent it from happening.
> fix(cdk/drag-drop): reset pointer events on descendants

- src/components-examples/material/table/table-http/table-http-example.css
The fix is to use the width property instead of max-width since this can be misleading as though the width will never exceed the max-width provided.
Fixes #29294
> docs-bug(mat-table): Example suggesting to use max-width to set column width is misleading

- src/components-examples/material/form-field/form-field-prefix-suffix/form-field-prefix-suffix-example.ts
Fixes minor bug in demo file where icon cannot be toggled. This is because `signal` was not called correctly
> fix: unable to toggle icon in demo file

- src/cdk/listbox/listbox.md
- src/components-examples/cdk/listbox/cdk-listbox-forms-validation/cdk-listbox-forms-validation-example.html
- src/components-examples/cdk/listbox/cdk-listbox-forms-validation/cdk-listbox-forms-validation-example.ts
CDK listbox doc have wrong part about forms-validation
https://material.angular.io/cdk/listbox/overview#forms-validation
`cdkListboxUnexpectedOptionValues` and `cdkListboxUnexpectedMultipleValues `  have removed in this PR https://github.com/angular/components/pull/25856, but doc not updated.
This PR is remove forms-validation from cdk listbox doc.
> doc-bug(cdk/listbox): remove forms validation and validation example

- src/material/tabs/tab-group.spec.ts
- src/material/tabs/tabs-animations.ts
Before this commit, when using pre-rendering, the styling animation would only remove the `transform` style when hydrating the component. This commit fixes this by including `visibility` as styles to remove when playing the animations.
----
Context for this issue is adev: https://angular.dev/api/common/AsyncPipe?tab=usage-notes
As you can see, the tabs doesn't hydrate correctly, `visibility:hidden` on the tab body isn't removed when the animation flushes. 
I tried the fix in angular/angular#56340
Demo link: https://ng-dev-previews-fw--pr-angular-angular-56340-adev-prev-xdjybnyt.web.app/api/common/AsyncPipe?tab=usage-notes
----
Edit: narrowed down repro: https://github.com/JeanMeche/mat-tabs-prerendering-bug
> fix(material/tabs): remove visibility style when hydrating

- src/cdk/drag-drop/directives/drag.ts
- src/cdk/drag-drop/directives/drop-list-shared.spec.ts
- src/cdk/drag-drop/directives/single-axis-drop-list.spec.ts
- src/cdk/drag-drop/directives/standalone-drag.spec.ts
- src/cdk/drag-drop/drag-ref.ts
- src/cdk/drag-drop/sorting/single-axis-sort-strategy.ts
- tools/public_api_guard/cdk/drag-drop.md
In some cases the parent of the dragged element might be scaled (e.g. when implementing zoom) which can throw off the positioning. Detecting this would be expensive, because we'd have to check the entire DOM tree so instead these changes add an input so the user can specify the scale amount.
> feat(cdk/drag-drop): add input to specify dragged item scale

- src/cdk-experimental/popover-edit/popover-edit.spec.ts
- src/cdk-experimental/popover-edit/table-directives.ts
- src/material-experimental/popover-edit/popover-edit.spec.ts
- src/material-experimental/popover-edit/table-directives.ts
Use the correct role attribute and allow setting aria label on the dialog/popup element.
See internal ticket 349939031
> fix(cdk-experimental/popover-edit): Fix dialog role and allow aria label on popup

- src/cdk/dialog/dialog.md
Updated the dialog in the cdk to add an example on accessing the dialogRef when using TemplateRef
Fixes #26193
> fix(cdk/dialog): CDK Dialog docs missing explanation on how to access dialogRef when using a TemplateRef

- src/youtube-player/README.md
- Code snippet => `yotube-player` -> `youtube-player`
- Double spaces, missing comma.
> docs: fix typo

- src/material/tooltip/tooltip.spec.ts
- src/material/tooltip/tooltip.ts
- tools/public_api_guard/material/tooltip.md
We have tests that already set these values (but used to use nullness assertions to overcome the build failures) and protect against it by treating these values as empty strings (and thus we hide the tooltip), but we don't allow anyone who uses templates with strict type checking to set optional values unless they add their own nullness assertion.
> Allow undefined & null values in [matTooltip] explicitly

- CHANGELOG.md
> docs: release notes for the v18.1.0 release

- src/material/core/tokens/m2/mdc/_circular-progress.scss
- src/material/progress-spinner/_progress-spinner-theme.scss
- src/material/progress-spinner/progress-spinner.scss
Reworks the structural styles of the progress spinner to be smaller and easier to maintain.
> refactor(material/progress-spinner): simplify structural styles

- src/material/core/tokens/m2/mdc/_switch.scss
- src/material/core/tokens/m3/mdc/_switch.scss
- src/material/core/tokens/tests/test-validate-tokens.scss
- src/material/slide-toggle/BUILD.bazel
- src/material/slide-toggle/_slide-toggle-theme.scss
- src/material/slide-toggle/slide-toggle.scss
Reworks the structural styles for the slide toggle to be smaller and easier to maintain.
> refactor(material/slide-toggle): simplify structural styles

- src/material/core/tokens/m2/mat/_form-field.scss
- src/material/core/tokens/m2/mat/_paginator.scss
- src/material/form-field/BUILD.bazel
- src/material/form-field/_form-field-subscript.scss
- src/material/form-field/_form-field-theme.scss
- src/material/form-field/_mdc-text-field-density-overrides.scss
- src/material/form-field/_mdc-text-field-structure-overrides.scss
- src/material/form-field/_mdc-text-field-structure.scss
- src/material/form-field/directives/notched-outline.html
- src/material/form-field/form-field.scss
Reworks the form field styles to make them smaller and easier to maintain.
> refactor(material/form-field): simplify structural styles

- src/components-examples/material/datepicker/BUILD.bazel
- src/components-examples/material/datepicker/datepicker-dialog/datepicker-dialog-example-dialog.html
- src/components-examples/material/datepicker/datepicker-dialog/datepicker-dialog-example.html
- src/components-examples/material/datepicker/datepicker-dialog/datepicker-dialog-example.ts
- src/components-examples/material/datepicker/index.ts
Adds an example that demonstrates how to display a datepicker inside a matDialog component.
Fixes #28186
> fix(material/datepicker): display datepicker inside a dialog example

- src/material/table/table.md
Added a description of how to update MatTableDataSource without breaking sorting
Fixes #27708
> docs(material/table): describe how to properly update MatTableDataSource #27708

- src/material/core/tokens/m2/mdc/_slider.scss
- src/material/core/tokens/m3/mdc/_slider.scss
- src/material/slider/BUILD.bazel
- src/material/slider/_slider-theme.scss
- src/material/slider/slider.scss
Reworks the slider styles to be smaller and easier to maintain.
> refactor(material/slider): simplify structural styles

- src/material/core/tokens/m2/mat/_optgroup.scss
- src/material/core/tokens/m2/mat/_option.scss
Removes the fallback for generating typography tokens for `mat-option` and `mat-optgroup` even if there's no theme. This isn't a supported configuration and the previous setup was temporary.
> fix(material/core): require theme for option typography

- guides/getting-started.md
Updates the Getting Started guide:
- Change links from angular.io to angular.dev
- Update guidance on importing the components (default to standalone guidance)
> docs: update getting started

- src/material/chips/chip-grid.ts
Fixed an issue to where users can get stuck in a focus trap in mat-grid. If a user were to try to navigate backwards out of the chip grid, the user gets stuck.
fixes b/290959510
> fix(material/chips): fix focus issue

- src/material/tabs/_tabs-common.scss
Adds a `min-height` to the tab header when it is placed inside a drop list. This is useful when dragging between connected lists since the header may collapse when it has no tabs.
> fix(material/tabs): prevent tab header from collapsing when empty inside a drop list

- src/cdk/drag-drop/drag-ref.ts
- src/cdk/drag-drop/preview-ref.ts
The comparison between the event target element and this._preview never returned true because this._preview is a class, and we need to compare its element instead. This regression was introduced in commit https://github.com/angular/components/commit/ebab924601c3d93933aed2698b4db96b4cafa3d4#diff-65b82ba5c290701d792881e9e389e8f1961848abb740bb20940d4383dfae4eacL121-R117.
> fix(cdk/drag-drop): remove preview after animate to placeholder animation completes

- src/material/core/tokens/_token-utils.scss
- src/material/core/tokens/m2/mdc/_switch.scss
Reworks the logic for generating tokens so it doesn't have external dependencies.
> refactor(material/core): simplify token utils

- src/material/button/_icon-button-theme.scss
- src/material/core/theming/_color-api-backwards-compatibility.scss
- src/material/core/tokens/m3/mat/_icon-button.scss
- src/material/core/tokens/m3/mdc/_icon-button.scss
Fixes that palettes weren't implemented for the icon button in M3. This was done initially, because M3 doesn't explicitly support palettes, but it can make it harder for users to migrate.
Fixes #29307.
> fix(material/button): support palettes for icon button in M3

- CHANGELOG.md
> docs: release notes for the v18.1.1 release

- src/material/chips/chip.scss
Fixes Angular Components Chip component where the touch target of the remove button of a chip is too small. Updates .mat-mdc-chip-remove to target more specific styles to override original style of padding: 8px so that the user has a larger touch target particularly on mobile devices.
Fixes b/286959517
Before [screenshot](https://screenshot.googleplex.com/LY4J6jk4b3TFyQo)
After [screenshot](https://screenshot.googleplex.com/5zpHzNya7CxhMnx)
BREAKING CHANGE: updates chip remove button touch target to increase accessibility of the button especially on touch/mobile devices.
> fix(material/chips): remove button is too small

- src/components-examples/cdk/drag-drop/cdk-drag-drop-sorting/cdk-drag-drop-sorting-example.css
The style `border-bottom: solid 1px #ccc;` was initially applied to all elements with the class `example-box`, except for the last child which had its border removed with `border: none`. However, when the last element was dragged, it lost the `border: none` style and regained the `border-bottom: 1px solid #ccc`, causing the scrollbar to appear.
To fix this issue, I applied `border: none` to the class `cdk-drag-preview`. This ensures that all dragged elements lose their `border-bottom`, preventing the scrollbar from appearing during the drag operation.
Fixes #29419
> fixed show scrollbar in preview of the last element

- src/dev-app/input/BUILD.bazel
- src/dev-app/input/input-demo.html
- src/dev-app/input/input-demo.ts
- src/material/input/input.ts
- tools/public_api_guard/material/input.md
In blink and webkit browsers the default behavior of increasing or decreasing a focused number input on wheel events is broken until a wheel event listener is explicitly added.
Fixes #29074
> fix(material/input): Number input not changing on wheel interaction

- src/dev-app/input/input-demo.html
- src/dev-app/input/input-demo.ts
- src/material/form-field/form-field.ts
- src/material/input/input.spec.ts
There is a method _shouldLabelFloat that determines if the label should float. A check was added `_hasFloatingLabel` to see if a floating label exists before deciding whether the label should float. Examples were added at the end of the input-demo file, where you can see inputs without labels (both fixed and dynamic). Removing the solution also allows you to simulate the described error. Unit tests were added to validate the solution.
Fixes #29401
> fix(material/form-field): hiding a label after it has been shown leaves a blank space

- tools/dgeni/common/normalize-function-parameters.ts
We were extracting the type of a function parameter by splitting on `:` and taking the second item. The problem is that if the type is an object literal, it'll have more than one colon in its text.
These changes fix the issue by only looking for the first colon and extracting the name based on it.
> build: docs incorrectly outputting function parameters with object literal type

- src/components-examples/material/chips/chips-reactive-form/chips-reactive-form-example.css
- src/components-examples/material/chips/chips-reactive-form/chips-reactive-form-example.html
- src/components-examples/material/chips/chips-reactive-form/chips-reactive-form-example.ts
- src/components-examples/material/chips/chips-template-form/chips-template-form-example.css
- src/components-examples/material/chips/chips-template-form/chips-template-form-example.html
- src/components-examples/material/chips/chips-template-form/chips-template-form-example.ts
- src/components-examples/material/chips/index.ts
- src/material/chips/chips.md
Added a description and examples in the docs of how to use chips in both reactive and template-driven forms.
Fixes #22906
> docs(material/chips): describe how to use chips in forms #22906

- src/dev-app/checkbox/BUILD.bazel
- src/dev-app/checkbox/checkbox-demo.html
- src/dev-app/checkbox/checkbox-demo.ts
- src/material/checkbox/_checkbox-common.scss
- src/material/checkbox/checkbox-config.ts
- src/material/checkbox/checkbox.html
- src/material/checkbox/checkbox.scss
- src/material/checkbox/checkbox.spec.ts
- src/material/checkbox/checkbox.ts
- tools/public_api_guard/material/checkbox.md
Adds the `disabledInteractive` input to the checkbox that allows users to opt into having disabled checkboxes be interactive. The disabled state is communicated through `aria-disabled` instead.
> feat(material/checkbox): add the ability to interact with disabled checkboxes

- CHANGELOG.md
> docs: release notes for the v18.1.2 release

- src/material/slide-toggle/slide-toggle.html
Replaces `div` nodes inside the `button` with `span` since the former trigger some automated checkers.
Fixes #29484.
> fix(material/slide-toggle): remove divs from button

- src/dev-app/radio/BUILD.bazel
- src/dev-app/radio/radio-demo.html
- src/dev-app/radio/radio-demo.ts
- src/material/checkbox/checkbox.spec.ts
- src/material/radio/_radio-common.scss
- src/material/radio/radio.html
- src/material/radio/radio.scss
- src/material/radio/radio.spec.ts
- src/material/radio/radio.ts
- tools/public_api_guard/material/radio.md
Adds the `disabledInteractive` input that allows users to opt into being able to interact with a disabled radio button (e.g. focus or show a tooltip).
Also fixes that we weren't setting `pointer-events: none` on the entire container when it's disabled.
> feat(material/radio): add the ability to interact with disabled radio buttons

- src/material/badge/badge.scss
- src/material/button-toggle/button-toggle.scss
- src/material/button/_button-base.scss
- src/material/button/icon-button.scss
- src/material/checkbox/_checkbox-common.scss
- src/material/chips/chip.scss
- src/material/core/option/option.scss
- src/material/core/ripple/_ripple.scss
- src/material/core/tokens/_token-utils.scss
- src/material/datepicker/calendar-body.scss
- src/material/form-field/_mdc-text-field-density-overrides.scss
- src/material/form-field/_mdc-text-field-structure.scss
- src/material/form-field/form-field.scss
- src/material/grid-list/grid-list.scss
- src/material/menu/menu.scss
- src/material/progress-bar/progress-bar.scss
- src/material/radio/_radio-common.scss
- src/material/slide-toggle/slide-toggle.scss
- src/material/slider/slider.scss
- src/material/stepper/stepper.scss
- src/material/toolbar/toolbar.scss
- rename `get-token-variable` to `get-token-variable-name`
- rename `get-token-variable-reference` to `get-token-variable`
- switch uses of `get-token-variable-name` to `get-token-variable` (remove wrapper of "var" since function does this)
> refactor(material/core): use util to build token vars

- src/dev-app/autocomplete/autocomplete-demo.ts
- src/dev-app/bottom-sheet/bottom-sheet-demo.ts
- src/dev-app/cdk-dialog/dialog-demo.ts
- src/dev-app/clipboard/clipboard-demo.ts
- src/dev-app/connected-overlay/connected-overlay-demo.ts
- src/dev-app/datepicker/datepicker-demo.ts
- src/dev-app/dev-app/dev-app-layout.ts
- src/dev-app/dialog/dialog-demo.ts
- src/dev-app/drag-drop/drag-drop-demo.ts
- src/dev-app/example/example.ts
- src/dev-app/focus-origin/focus-origin-demo.ts
- src/dev-app/focus-trap/focus-trap-demo.ts
- src/dev-app/google-map/google-map-demo.ts
- src/dev-app/icon/icon-demo.ts
- src/dev-app/input-modality/input-modality-detector-demo.ts
- src/dev-app/live-announcer/live-announcer-demo.ts
- src/dev-app/platform/platform-demo.ts
- src/dev-app/screen-type/screen-type-demo.ts
- src/dev-app/slider/slider-demo.ts
- src/dev-app/snack-bar/snack-bar-demo.ts
- src/dev-app/youtube-player/youtube-player-demo.ts
- src/universal-app/kitchen-sink/kitchen-sink.ts
Changes the dev app to use `inject` instead of constructor-based injection.
> build: switch dev app to inject

- src/material/slide-toggle/slide-toggle.scss
Fixes that the slide toggle was triggering the `:active` styles for the entire container, even though only parts of it are interactive.
Fixes #29483.
> fix(material/slide-toggle): don't trigger active state for entire container

- src/material/core/theming/_definition.scss
- src/material/core/theming/tests/theming-definition-api.spec.ts
- src/material/core/tokens/_m3-tokens.scss
Fixes that the `system-level-colors` and `system-level-typography` mixins weren't using the `system-variables-prefix` passed in by the user.
Note: a bit of a gotcha here is that we need to store two separate prefixes, because in theory the user can pass different prefixes into `color` and `typography`.
Fixes #29504.
> fix(material/core): custom system-level variable prefix not used in some mixins

- src/material/dialog/dialog.scss
We were emitting a font family value like `var(--mat-dialog-font, Roboto, sans-serif)` which is invalid. These changes remove the fallback since it was primarily there to make it easier to land the MDC changes.
> fix(material/dialog): invalid font-family declaration

- src/material/chips/chip-option.html
- src/material/chips/chip-row.html
- src/material/chips/chip-row.spec.ts
- src/material/chips/chip-row.ts
- src/material/chips/chip.ts
- tools/public_api_guard/material/chips.md
remove tabindex attribute from mat-chip as this makes the mat-chip element focusable for mobile screen readers (see YAQS link below). Having tabindex=-1 causes mobile screen readers to focus on the chip twice. removing makes it to where user only needs to swipe once to get the content of the chip.
https://yaqs.corp.google.com/eng/q/4811580888973312?ved=0CAAQ_rQKahcKEwiw_YGl9a6HAxUAAAAAHQAAAAAQHA
Before: https://screencast.googleplex.com/cast/NjAzNzgyNzIyMDQwNjI3MnwyMDVjMjkyZi02Mw
After: https://screencast.googleplex.com/cast/NTQxMzQ2MzM5NTQwMTcyOHw3NThhZjdlNi1mOQ
fixes b/286286473
> fix(material/chips): remove tab-index attribute from mat-chip host

- src/material/_index.scss
- src/material/core/style/_elevation.scss
- src/material/core/style/_sass-utils.scss
- src/material/core/tokens/_m3-tokens.scss
- src/material/core/tokens/_token-definition.scss
- src/material/core/tokens/_token-utils.scss
- src/material/core/tokens/m3/mat/_app.scss
Introduces a new `theme` API that takes the theme-config and emits system-level CSS variables. Component tokens will fallback to these system-level variables, removing the need to call component-specific mixins and setting fine-grained tokens.
This `theme` API is not exposed, because hardcoded values still fallback to M2 values in some cases. This will need to be updated before this API can be used, but it will require updating a number of internal screenshots. This will be a follow-up change before adding `theme` to the `index.scss`.
> feat(multiple): fallback to system level variables

- CHANGELOG.md
> docs: release notes for the v18.1.3 release

- src/material/tooltip/tooltip.spec.ts
- src/material/tooltip/tooltip.ts
Fixes that we were setting an `aria-describedby` even if the tooltip won't show up because it's disabled.
Fixes #29501.
> fix(material/tooltip): remove aria-describedby when disabled

- src/material/core/tokens/m3/mdc/_chip.scss
Fixes that the chips weren't generating the `with-avatar-avatar-shape-radius` and `elevated-container-color` tokens in M3.
> fix(material/chips): missing tokens in M3

- src/cdk/drag-drop/drop-list-ref.ts
Removes the `RootNode` internal type since it isn't necessary anymore.
> refactor(cdk/drag-drop): remove unnecessary type

- src/cdk/drag-drop/drag-drop-registry.spec.ts
- src/cdk/drag-drop/drag-drop-registry.ts
- src/cdk/drag-drop/drag-drop.ts
- src/cdk/drag-drop/drag-ref.ts
- src/cdk/drag-drop/drop-list-ref.ts
- src/cdk/drag-drop/sorting/mixed-sort-strategy.ts
- src/cdk/drag-drop/sorting/single-axis-sort-strategy.ts
- tools/public_api_guard/cdk/drag-drop.md
Previously we used generics in the `DragDropRegistry` to avoid circular dependencies. Now that we can use type-only imports, we don't need the generics anymore.
> refactor(cdk/drag-drop): remove unnecessary generics

- src/material/checkbox/_checkbox-common.scss
- src/material/checkbox/checkbox.scss
We had a patch to show the checkmark in high contrast mode, but it was only applied to `mat-checkbox`. These changes move it to the common styles so it also shows up for `mat-list-option`.
> fix(material/list): checkmark not visible in high contrast mode

- src/material/sidenav/drawer.spec.ts
- src/material/sidenav/drawer.ts
Completely disables the sidenav's focus trap while it's closed so users can't tab to the anchors.
Fixes #29545.
> fix(material/sidenav): disable focus trap while closed

- CHANGELOG.md
> docs: release notes for the v18.1.4 release

- src/dev-app/button-toggle/button-toggle-demo.html
- src/dev-app/button-toggle/button-toggle-demo.ts
- src/material/button-toggle/button-toggle.html
- src/material/button-toggle/button-toggle.scss
- src/material/button-toggle/button-toggle.spec.ts
- src/material/button-toggle/button-toggle.ts
- src/material/button-toggle/testing/button-toggle-harness.spec.ts
- src/material/button-toggle/testing/button-toggle-harness.ts
- tools/public_api_guard/material/button-toggle.md
Adds the `disabledInteractive` input to the button toggle that allows users to opt into supporting focus on disabled button toggles.
> feat(material/button-toggle): allow disabled buttons to be interactive

- CHANGELOG.md
- package.json
Also this PR cherry-picks the changelog for v18.2.0-rc.0 into the main branch so that the changelog is up to date.
> Update next branch to reflect new release-train "v18.3.0-next.0".

- CONTRIBUTING.md
- src/cdk/accordion/accordion-item.ts
- src/cdk/portal/portal.ts
- src/cdk/text-field/_index.scss
- src/material/core/datetime/native-date-adapter.ts
- src/material/core/tokens/m2/mat/_standard-button-toggle.scss
- src/material/core/tokens/m2/mdc/_checkbox.scss
- src/material/expansion/expansion-animations.ts
- src/material/form-field/_form-field-native-select.scss
- src/material/list/list-option.ts
Some comments that get marked up into text on the webapp have grammar mistakes. Usually don't bother with spelling but this one caught my eye :)
> Fix spelling mistakes that appear on the webapp

- src/components-examples/material/list/index.ts
- src/components-examples/material/list/list-single-selection-reactive-form/list-single-selection-form-example.html
- src/components-examples/material/list/list-single-selection-reactive-form/list-single-selection-reactive-form-example.ts
- src/components-examples/material/list/list-single-selection/list-single-selection-example.html
- src/components-examples/material/list/list-single-selection/list-single-selection-example.ts
- src/dev-app/list/list-demo.html
- src/dev-app/list/list-demo.ts
Updated the single selection list example from a template-driven form to a reactive form.
Fixes #25894
> fix(material/list): Mat Selection List example is limited to html temp

- .stylelintrc.json
Enables the use of `initial` for CSS values
IE is no longer tested against for Angular Material
> build: remove ie-based lint rule

- src/material/autocomplete/autocomplete.spec.ts
Fix typos in comments and test descriptions, fix query selectors and unresolved variables
> fix(material/autocomplete): typos and unresolved variables in tests

- src/components-examples/material/tree/tree-dynamic/tree-dynamic-example.html
- src/components-examples/material/tree/tree-dynamic/tree-dynamic-example.ts
The example currently fails to remove the progress bar due to change detection not being triggered even though isLoading is set to false
> fix(material/tree): switch example to signals

- .github/workflows/pr.yml
It occasionally happens that we get a PR that has both the incorrect commit message and a lint failure. The process of fixing it can take multiple runs, because the author has to fix the commit, re-run and then fix the lint failures.
These changes move the commit message check to be last since if everything else passes, the caretaker can fix the commit message while merging the PR.
> build: move commit message check to be last in pipeline

- src/material/chips/chips.md
Fixes that the chips doc weren't referring the an example correctly.
Fixes #29571.
> docs(material/chips): wrong example name

- src/material/checkbox/testing/checkbox-harness.spec.ts
- src/material/checkbox/testing/checkbox-harness.ts
- src/material/radio/testing/radio-harness.spec.ts
- src/material/radio/testing/radio-harness.ts
- src/material/slide-toggle/slide-toggle.html
- src/material/slide-toggle/testing/slide-toggle-harness.spec.ts
- src/material/slide-toggle/testing/slide-toggle-harness.ts
Fixes that a few test harnesses weren't accounting for the new `disabledInteractive` inputs.
> Account for disabledInteractive in test harnesses

- src/material/form-field/form-field.ts
Fixes that the form field wasn't accounting for the case where the form control is swapped out.
Fixes #29402.
> fix(material/form-field): update state if control changes

- src/material/tabs/tab-group.html
- src/material/tabs/tab-group.spec.ts
- src/material/tabs/tab-group.ts
- src/material/tabs/tab-header.html
- src/material/tabs/tab-header.ts
- tools/public_api_guard/material/tabs.md
According to the [W3C reference implementation](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/), the inner `tablist` can be labelled using `aria-label` or `aria-labelledby`. These changes add an input to allow them to be set.
Fixes #29486.
> fix(material/tabs): allow for tablist aria-label and aria-labelledby to be set

- CHANGELOG.md
> docs: release notes for the v18.1.5 release

- CHANGELOG.md
> docs: release notes for the v18.2.0 release

- src/dev-app/input/input-demo.html
- src/dev-app/input/input-demo.ts
- src/material/form-field/_mdc-text-field-structure.scss
- src/material/input/input.spec.ts
- src/material/input/input.ts
- src/material/input/public-api.ts
- src/material/input/testing/input-harness.spec.ts
- src/material/input/testing/input-harness.ts
- tools/public_api_guard/material/input.md
Adds the `disabledInteractive` input to `MatInput` which allows users to opt into having disabled input receive focus and dispatch events. Changing the value is prevented through the `readonly` attribute while disabled state is conveyed via `aria-disabled`.
> feat(material/input): add the ability to interact with disabled inputs

- src/cdk-experimental/column-resize/column-resize-notifier.ts
- src/cdk/a11y/interactivity-checker/interactivity-checker.spec.ts
- src/cdk/platform/platform.ts
- src/cdk/testing/testbed/task-state-zone-interceptor.ts
- src/material-experimental/selection/row-selection.ts
- src/material/dialog/dialog-container.ts
- src/material/select/select.ts
- tools/public_api_guard/cdk/platform.md
- tools/public_api_guard/material/dialog.md
- tools/public_api_guard/material/select.md
Fixes the cases where the initializers of properties were referencing members initialized in the constructor. This was preventing compatibility with `useDefineForClassFields`.
> refactor(multiple): fix initializers using constructor members

- src/material/icon/icon-registry.ts
Updates the message saying that `HttpClient` is missing to refer to a non-deprecated API.
Fixes #29587.
> fix(material/icon): update error message for missing HttpClient

- scripts/docs-deploy/docs-deps-install.mts
The `--non-interactive` option is not supported on newer version of yarn and should not be used moving forward to ensure support with yarn version upgrades.
> build: remove outdated `--non-interactive` yarn option from doc site install

- src/material/core/style/_menu-common.scss
Fixes that the offset of the submenu icon wasn't identical between LTR and RTL.
Fixes #29599.
> fix(material/menu): inconsistent layout of submenu icon

- src/cdk/drag-drop/directives/drop-list-shared.spec.ts
- src/cdk/drag-drop/preview-ref.ts
As of #28945 we use a popover to display the preview so that it's always on top. To do so we need to push the popover from its default position at the center to the top/left which is done using `margin: auto`. Since we were setting `margin: 0`, the element was ending up at top/right in RTL, if `dir="rtl"` is set on the `html` or `body`.
These changes fix the issue by pushing the element to the top/left using `margin-right: auto`.
Fixes #29604.
> fix(cdk/drag-drop): preview positioned incorrectly when RTL is set on the body

- src/material/tabs/_tabs-common.scss
- src/material/tabs/tab-header.html
- src/material/tabs/tab-nav-bar/tab-nav-bar.html
These changes undo #14640 and #24338 since they are causing Chrome to log accessibility warnings. We don't want to use native `button` elements here, because they're always focusable (unless disabled) and these buttons should be completely invisible to assistive technology. AT users can navigate the tabs directly without having to use the pagination.
> fix(material/tabs): switch pagination to not use native buttons

- package.json
- src/material/badge/badge.scss
- src/material/button-toggle/button-toggle.scss
- src/material/button/_button-base.scss
- src/material/button/button.scss
- src/material/button/fab.scss
- src/material/button/icon-button.scss
- src/material/checkbox/_checkbox-common.scss
- src/material/checkbox/checkbox.scss
- src/material/chips/chip.scss
- src/material/core/option/option.scss
- src/material/core/selection/pseudo-checkbox/_pseudo-checkbox-theme.scss
- src/material/core/style/_list-common.scss
- src/material/core/theming/tests/m3-theme.spec.ts
- src/material/core/tokens/_m3-tokens.scss
- src/material/core/tokens/_token-utils.scss
- src/material/datepicker/calendar-body.scss
- src/material/dialog/dialog.scss
- src/material/expansion/expansion-panel.scss
- src/material/form-field/form-field.scss
- src/material/grid-list/grid-list.scss
- src/material/menu/menu.scss
- src/material/radio/radio.scss
- src/material/slide-toggle/_slide-toggle-theme.scss
- src/material/slide-toggle/slide-toggle.scss
- src/material/stepper/stepper.scss
- src/material/tabs/_tabs-common.scss
- src/material/tabs/tab-group.scss
- yarn.lock
Fixes a ton of warnings that showed up in the latest version of Sass as a result of https://sass-lang.com/documentation/breaking-changes/mixed-decls/.
* In order for Material to be compatible with [recent changes in Sass](https://sass-lang.com/documentation/breaking-changes/mixed-decls/) and upcoming changes in the CSS standard, tokens are now emitted in-place, rather the being hoisted to the top of the selector. As a result, some token overrides might not apply anymore. This is relevant primarily for the cases like `@include mat.button-theme($theme); --mat-button-color: red;`. It can be resolved by wrapping the overrides with `& {}`, for example `@include mat.button-theme($theme); & { --mat-button-color: red; }`.
Fixes #29591.
> fix(multiple): account for mixed declarations in latest Sass version

- src/material/core/_core.scss
- src/material/core/tokens/_token-utils.scss
When possible, use token fallbacks defined by the MDC system tokens instead of the M2 hardcoded values (or nothing).
This will affect the appearance of applications that are incorrectly lacking calls to component theme mixins, since all of these fallbacks should be ignored in favor of the fine-grained token values.
Applications that have styles changed from this should ensure that they are calling component theme mixins, e.g. `mat.button-theme()` if a button is used. 
For example, here's the change for expansion panel expanded height:
```
.mat-expansion-panel-header.mat-expanded {
// Before: 
height: var(--mat-expansion-header-expanded-state-height);
// After:
height: var(--mat-expansion-header-expanded-state-height, 64px);
}
```
> fix(multiple): change fallbacks to use m3

- src/material/_index.scss
- src/material/core/tokens/_m3-system.scss
- src/material/core/tokens/_m3-tokens.scss
- src/material/core/tokens/_token-utils.scss
No-op change that moves a subset of m3 theme mixins and functions that will otherwise create a circular dependency after depending on `definitions.scss`.
No code is changed, just moving
> refactor(material/core): split out m3 theme mixins

- src/material/button/button-base.ts
- src/material/button/button.spec.ts
- src/material/checkbox/checkbox.spec.ts
- src/material/checkbox/checkbox.ts
- src/material/chips/chip.spec.ts
- src/material/chips/chip.ts
- src/material/core/private/ripple-loader.ts
- tools/public_api_guard/material/button.md
- tools/public_api_guard/material/checkbox.md
- tools/public_api_guard/material/chips.md
- tools/public_api_guard/material/core.md
Removes the code that exposes the ripple implementations of some components since they are internal details and they require some hacky workarounds to keep exposed.
* `MatButton.ripple` is no longer available.
* `MatCheckbox.ripple` is no longer available.
* `MatChip.ripple` is no longer available.
> fix(multiple): stop exposing internal ripple implementation

- src/material/core/private/ripple-loader.ts
- tools/public_api_guard/material/core.md
Previously we had to manually instantiate `MatRipple` in order to maintain backwards compatibility, but it was problematic because it would break whenever we tried to use DI in `MatRipple` and it prevented us from switching to the `inject` function.
Instantiating `MatRipple` is no longer necessary after #29622 so these changes switch to creating an internal `RippleRenderer` instead.
> fix(material/core): stop manually instantiating MatRipple directive

- src/cdk/drag-drop/drag-ref.ts
Fixes that the drag&drop module wasn't checking for `ngDevMode` correctly.
Fixes #29633.
> fix(cdk/drag-drop): error if ngDevMode is undefined

- src/material/core/tokens/_m3-system.scss
- src/material/core/tokens/m3/mat/_sidenav.scss
- Adds variable definitions for palette variables directly referenced by the sidenav (neutral-variant20) and form field (neutral10). These are the only spots where references are made outside of the normal system values.
- Only emit defined system variables in `theme` (color, typography, and density) and adds support for defaults and simplified arguments (this is an experimental private API, and still under design and implementation)
> fix(material/core): add missing system variables

- src/cdk/overlay/BUILD.bazel
- src/cdk/overlay/_index.scss
- src/cdk/overlay/fullscreen-overlay-container.spec.ts
- src/cdk/overlay/overlay-container.ts
- src/cdk/overlay/overlay.ts
- src/cdk/private/style-loader.ts
- src/cdk/text-field/BUILD.bazel
- src/cdk/text-field/autofill.ts
- src/cdk/text-field/autosize.ts
- src/cdk/text-field/text-field-style-loader.ts
- src/e2e-app/components/block-scroll-strategy/block-scroll-strategy-e2e.ts
- src/material/core/BUILD.bazel
- src/material/core/_core.scss
- src/material/core/private/ripple-loader.ts
- src/material/core/ripple/index.ts
- src/material/core/ripple/ripple-renderer.ts
- src/material/core/ripple/ripple-structure.scss
- src/material/core/ripple/ripple.ts
- src/material/list/BUILD.bazel
- src/material/list/list-base.ts
- tools/public_api_guard/cdk/overlay.md
- tools/public_api_guard/material/core.md
Reworks `cdk/overlay`, `cdk/text-field` and `material/ripple` so that they load their structural styles automatically. In the past this has been a source of a lot of bugs.
* The ripples styles are now loaded slightly later than before which can change their specificity. You may have to update any ripple style overrides.
* The overlay stays are now loaded slightly later than before which can change their specificity. You may have to update any overlay style overrides.
> Simplify structural style setup

- src/material/core/style/_elevation.scss
- src/material/table/table-data-source.ts
Since goo.gl is being turned down, these links will start 404ing soon.
> build: remove goo.gl links

- .stylelintrc.json
- src/dev-app/BUILD.bazel
- src/dev-app/dev-app/dev-app-layout.html
- src/dev-app/dev-app/dev-app-layout.ts
- src/dev-app/dev-app/dev-app-state.ts
- src/dev-app/routes.ts
- src/dev-app/theme-m3.scss
- src/dev-app/theme/BUILD.bazel
- src/dev-app/theme/theme-demo.html
- src/dev-app/theme/theme-demo.scss
- src/dev-app/theme/theme-demo.ts
- src/material/_index.scss
Preview: https://ng-dev-previews-comp--pr-angular-components-29636-dev-6fy759rh.web.app/theme
Be sure to enable M3 and System Theme in the header
> feat(material/core): add experimental theme demo

- src/cdk/a11y/key-manager/tree-key-manager-strategy.ts
- src/cdk/a11y/key-manager/tree-key-manager.ts
- src/cdk/tree/tree.ts
- tools/public_api_guard/cdk/a11y.md
- tools/public_api_guard/cdk/tree.md
The tree implements a roving tabindex which needs to have an initial item with `tabindex = 0` to work correctly. This happens by waiting for the data to be initialized in the `TreeKeyManager` and focusing the active/first item. The problem is that this ends up stealing focus on load. We didn't notice this issue in the demo app, because all the tree are `visibility: hidden` since they're inside closed `mat-expansion-panel`, but the issue is visible in the docs site.
These changes resolve the issue by setting the `tabindex` without actually moving focus.
Fixes #29628.
> fix(cdk/tree): capturing focus on load

- src/cdk/tree/tree.ts
- tools/public_api_guard/cdk/tree.md
In #29062 a new parameter was added to the `CdkTree` constructor which is a breaking change.
These changes switch to using `inject` which allows us to avoid the breaking change.
Fixes #29595.
> fix(cdk/tree): avoid breaking change in constructor

- src/material/tooltip/tooltip.ts
clearTimeout() is surprisingly expensive. Only call it when there's an active timeout.
> perf(material/tooltip): Avoid unneeded calls to clearTimeout

- package.json
- tools/postinstall/patches/@angular+bazel+16.0.0-next.6.patch
- yarn.lock
See: https://github.com/angular/angular/pull/57559
> build: update `@angular/bazel` to consume new format of APF

- CHANGELOG.md
> docs: release notes for the v18.2.2 release

- src/material/core/style/_sass-utils.scss
Hover styles for some components (like menu and select) weren't being shown properly since the opacity was not formatted like a number.
Before: https://screencast.googleplex.com/cast/NTA2NDE5ODgzNTkyOTA4OHwzZjVjNDlmZi1lMw
After: https://screencast.googleplex.com/cast/NjcwMTk4MDg2Mzk1NDk0NHxhMzU3YzYyZC1mMA
> fix(material/core): Allow system variables to be formatted for opacity

- src/material/badge/badge.ts
The badge had an extra unnecessary check which meant that it would sometimes leak memory through the style loader. This isn't a big deal on the client since there's usually only one app on the page, but it can be a problem on the server which can create and destroy an app for each request.
Note that this is no longer an issue in 19.x where we use the common style loader, but we need to backport the fix to 18.x.
Fixes https://github.com/angular/angular/issues/57529.
> fix(material/badge): resolve memory leak

- .github/workflows/ci.yml
- .github/workflows/pr.yml
Some of the `build` jobs have been OOMing recently. These changes bump them up to a bigger machine which is identical to the `test` job.
> build: bump up machine size

- src/material/tooltip/tooltip.ts
Removes a workaround for an IE bug that is no longer necessary.
> fix(material/tooltip): remove old IE workaround

- src/material/checkbox/checkbox.scss
- src/material/core/private/ripple-loader.ts
- src/material/tabs/_tabs-common.scss
Fixes the following issues that prevented the ripples from showing up:
* We weren't passing an injector into the `RippleRenderer` created by the `RippleLoader` which meant that it was never injecting the structural styles.
* The checkbox and tabs ripple selectors weren't specific enough which meant that they would be overridden in some cases. We were handling this in other components, but for some reason these two were skipped.
Fixes #29670.
> fix(multiple): ripples not showing up in some cases

- src/cdk-experimental/column-resize/column-resize-directives/column-resize-flex.ts
- src/cdk-experimental/column-resize/column-resize-directives/column-resize.ts
- src/cdk-experimental/column-resize/column-resize-directives/default-enabled-column-resize-flex.ts
- src/cdk-experimental/column-resize/column-resize-directives/default-enabled-column-resize.ts
- src/cdk-experimental/column-resize/event-dispatcher.ts
- src/cdk-experimental/column-resize/resize-strategy.ts
- src/cdk-experimental/combobox/combobox-popup.ts
- src/cdk-experimental/combobox/combobox.ts
- src/cdk-experimental/popover-edit/edit-event-dispatcher.ts
- src/cdk-experimental/popover-edit/edit-ref.ts
- src/cdk-experimental/popover-edit/edit-services.ts
- src/cdk-experimental/popover-edit/focus-dispatcher.ts
- src/cdk-experimental/popover-edit/focus-escape-notifier.ts
- src/cdk-experimental/popover-edit/lens-directives.ts
- src/cdk-experimental/popover-edit/table-directives.ts
- src/cdk-experimental/selection/row-selection.ts
- src/cdk-experimental/selection/select-all.ts
- src/cdk-experimental/selection/selection-column.ts
- src/cdk-experimental/selection/selection-toggle.ts
- src/cdk-experimental/selection/selection.spec.ts
- src/cdk-experimental/table-scroll-container/table-scroll-container.ts
- src/material-experimental/column-resize/column-resize-directives/column-resize-flex.ts
- src/material-experimental/column-resize/column-resize-directives/column-resize.ts
- src/material-experimental/column-resize/column-resize-directives/default-enabled-column-resize-flex.ts
- src/material-experimental/column-resize/column-resize-directives/default-enabled-column-resize.ts
- src/material-experimental/column-resize/overlay-handle.ts
- src/material-experimental/column-resize/resizable-directives/default-enabled-resizable.ts
- src/material-experimental/column-resize/resizable-directives/resizable.ts
- src/material-experimental/column-resize/resize-strategy.ts
- src/material-experimental/selection/selection-column.ts
Switches all the experimental packages to use `inject` instead of constructor-based injection.
> refactor(multiple): switch experimental packages to inject

- CHANGELOG.md
> docs: release notes for the v18.2.3 release

- src/material/core/_core-theme.scss
- src/material/core/common-behaviors/common-module.ts
- src/material/core/theming/tests/m3-theme.spec.ts
- src/material/core/theming/tests/theming-inspection-api.spec.ts
- tools/public_api_guard/material/core.md
Removes the sanity checks since they won't execute with standalone by default, they mostly aren't necessary now that we're loading structural styles automatically and they produce some concrete styles that are problematic for the new theming APIs.
> fix(material/core): drop sanity checks

- src/material/form-field/_mdc-text-field-structure.scss
- src/material/form-field/form-field.html
- src/material/form-field/form-field.ts
- tools/public_api_guard/material/form-field.md
Fixes #26558
Note: the label may still briefly be larger than the form-field, during transition from resting to floating. Users may choose to add a CSS animation for this, but we don't want to bake it in because it may negatively impact performance.
> fix(material/form-field): Don't allow label to grow larger than input

- src/cdk/overlay/overlay-ref.ts
The `OverlayRef` was triggering an `afterEachRender` and passing in an `EnvironmentInjector`. Under the hood this uses a `DestroyRef` that is never destroyed, because the `EnvironmentInjector` is almost never destroyed.
These changes add an explicit `destroy` call to avoid the issue.
Fixes #29696.
> fix(cdk/overlay): avoid leaking memory through afterNextRender

- src/material/core/option/option.scss
- src/material/list/_list-inherited-structure.scss
- src/material/list/list.scss
Fixes a couple of issues with how selected options were being shown in high contrast mode.
> Fix selected indication for options in high contrast mode

- src/material/core/option/option.scss
> fix(material/select): Update checkbox color to match the selected label text color

- src/material/badge/badge.scss
- src/material/core/tokens/m3/mat/_badge.scss
Correct M3 value for the line height is 16px - make this explicit in the styles
> fix(material/badge): change legacy container size default

- src/material/list/_list-inherited-structure.scss
Re-adds the `::before` element that was removed in #29707, because the removal broke some internal tests.
> refactor(material/list): restore before pseudo element

- CHANGELOG.md
> docs: release notes for the v18.2.4 release

- src/cdk/listbox/listbox.ts
When the CDK listbox has `useActiveDescendant` enabled, it won't focus the individual options so they won't be scrolled into the view automatically. This change adds a manual call to scroll them in instead.
Fixes #28989.
> fix(cdk/listbox): scroll active option into view when using aria-activedescendant

- src/cdk/overlay/BUILD.bazel
- src/cdk/overlay/_index.scss
- src/cdk/overlay/overlay-container.ts
- src/cdk/overlay/overlay-structure.scss
Recently we switched to loading the styles of the overlay dynamically which can make them more specific than pre-existing themes. These changes use a cascade layer in order to reduce their specificity.
> fix(cdk/overlay): load structural styles in a cascade layer

- src/cdk/portal/dom-portal-outlet.ts
- src/cdk/portal/portal-directives.ts
- src/cdk/portal/portal.spec.ts
- src/cdk/portal/portal.ts
- src/material/dialog/dialog.spec.ts
- tools/public_api_guard/cdk/portal.md
We now have all the necessary APIs to allow to remove our usages of the deprecated `ComponentFactoryResolver`.
Fixes #24334.
> fix(cdk/portal): remove ComponentFactoryResolver usages

- package.json
- src/material-date-fns-adapter/package.json
- yarn.lock
Updates the `date-fns` adapter to support version 4.
Fixes #29740.
> feat(material-date-fns-adapter): add support for date-fns 4

- src/cdk/drag-drop/directives/drag.ts
- src/cdk/drag-drop/directives/standalone-drag.spec.ts
Fixes that the scale was only being synced when the user drags, but we need it also when setting the free drag position.
Fixes #29737.
> fix(cdk/drag-drop): account for scale when setting free drag position

- src/components-examples/material/select/select-custom-trigger/select-custom-trigger-example.css
The `mat-select` in the custom trigger example was jumping around, because the projected `span` didn't have a `line-height`.
Fixes #29743.
> docs(material/select): prevent select from jumping in custom trigger example

- src/material/slider/slider-thumb.ts
- src/material/slider/slider.ts
Fixes that we were throwing a cryptic error if the slider isn't set up properly.
Fixes #29738.
> fix(material/slider): log proper error when slider isn't configured correctly

- src/material/datepicker/calendar-body.html
- src/material/datepicker/calendar-header.html
Fixes that the datepicker had some `<label>` elements that weren't pointing to anything via the `for` attribute which was being flagged by Chrome.
Fixes #29749.
> fix(material/datepicker): replace labels not pointing to anything

- src/google-maps/map-advanced-marker/map-advanced-marker.spec.ts
- src/google-maps/map-advanced-marker/map-advanced-marker.ts
- tools/public_api_guard/google-maps/google-maps.md
This PR adds support for the following mouse events to the map-advanced-marker component:
- Double click (dblclick)
- Mouse out (mouseout)
- Mouse over (mouseover)
- Mouse up (mouseup)
- Right click (right-click)
These events were available in the deprecated map-marker and are now implemented to enable similar functionality in map-advanced-marker.
**Testing:**
- Unit tests added for each event.
> feat(google-maps/map-advanced-marker): Add support for some mouse events #29741

- src/cdk/tree/tree.ts
The CDK tree was calling `ChangeDetectorRef.detectChanges` recursively for each node in the tree which was overflowing the call stack with some larger trees.
These changes resolve the issue by only calling `detectChanges` on the root.
Fixes #29733.
> fix(cdk/tree): resolve maximum call stack error

- src/material/select/select.ts
Fixes a bug reported in MatSelect where the usage of aria-autocomplete is not a valid attribute that can be used with aria role=listbox. Removes the aria-autocomplete attribute to fix the violation: aria-allowed-attr.
[W3 Documentation on allowed attributes for role="listbox"](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/#wai-ariaroles,states,andproperties)
Fixes [b/352496530](b/352496530)
> fix(material/select): remove incompatible aria-autocomplete attribute

- src/material/chips/chip.scss
Fixes Angular Components Chips component accessibility issue where the touch target is too small. Updates the chips' remove button ::after margin and padding styles to create a larger touch target to meet the minimum 48px x 48px size.
[Before screenshot](https://screenshot.googleplex.com/LY4J6jk4b3TFyQo)
[After screenshot](https://screenshot.googleplex.com/7Nwr6gzbWkwBwum)
Fixes b/286959517
> fix(material/chips): increase chip remove touch target size

- src/cdk/tree/tree.md
- src/components-examples/material/tree/index.ts
- src/components-examples/material/tree/tree-flat-child-accessor-overview/tree-flat-child-accessor-overview-example.html
- src/components-examples/material/tree/tree-flat-child-accessor-overview/tree-flat-child-accessor-overview-example.ts
- src/components-examples/material/tree/tree-nested-child-accessor-overview/tree-nested-child-accessor-overview-example.css
- src/components-examples/material/tree/tree-nested-child-accessor-overview/tree-nested-child-accessor-overview-example.html
- src/components-examples/material/tree/tree-nested-child-accessor-overview/tree-nested-child-accessor-overview-example.ts
- src/dev-app/tree/tree-demo.html
- src/dev-app/tree/tree-demo.ts
- src/material/tree/tree.md
> docs(mat/tree): update examples on docs pages, add new childrenAccessor examples

- src/material/select/select.spec.ts
After #29645, the assertion for `aria-autocomplete` isn't valid anymore.
> test(material/select): fix broken test

- CHANGELOG.md
> docs: release notes for the v18.2.5 release

- src/cdk/private/BUILD.bazel
- src/cdk/private/public-api.ts
- src/cdk/private/visually-hidden/visually-hidden.scss
- src/cdk/private/visually-hidden/visually-hidden.ts
- tools/public_api_guard/cdk/private.md
This is part of a larger effort to remove the `mat.core()` mixin. The goal of this PR is to provide a way for components to load the styles for the `.cdk-visually-hidden` class without needing it to be loaded via `mat.core()`'s call to `cdk.a11y-visually-hidden()`.
> feat(cdk/private): create cdk-visually-hidden style loader

- src/google-maps/google-map/google-map.ts
- src/google-maps/map-advanced-marker/map-advanced-marker.ts
- src/google-maps/map-base-layer.ts
- src/google-maps/map-circle/map-circle.ts
- src/google-maps/map-directions-renderer/map-directions-renderer.ts
- src/google-maps/map-directions-renderer/map-directions-service.ts
- src/google-maps/map-geocoder/map-geocoder.ts
- src/google-maps/map-ground-overlay/map-ground-overlay.ts
- src/google-maps/map-heatmap-layer/map-heatmap-layer.ts
- src/google-maps/map-info-window/map-info-window.ts
- src/google-maps/map-kml-layer/map-kml-layer.ts
- src/google-maps/map-marker-clusterer/map-marker-clusterer.ts
- src/google-maps/map-marker/map-marker.ts
- src/google-maps/map-polygon/map-polygon.ts
- src/google-maps/map-polyline/map-polyline.ts
- src/google-maps/map-rectangle/map-rectangle.ts
- src/google-maps/map-traffic-layer/map-traffic-layer.ts
- tools/public_api_guard/google-maps/google-maps.md
Reworks the Google Maps module to use the `inject` function instead of constructor-based injection.
> refactor(google-maps): switch to inject function

- src/youtube-player/youtube-player.ts
- tools/public_api_guard/youtube-player/youtube-player.md
Reworks the `youtube-player` to use the `inject` function instead of constructor-based injection.
> refactor(youtube-player): switch to inject function

- src/material/datepicker/calendar.scss
Sets a `line-height` on the calendar, otherwise it inherits the one from the `body` which can throw off the layout.
Fixes #29756.
> fix(material/datepicker): set explicit line height on calendar

- src/dev-app/theme.scss
- src/material/_index.scss
- src/material/core/_core.scss
- src/universal-app/styles.scss
* This is an intermediary step so we can roll out calls to these empty mixins progressively.
* Once all of the instances of mat.core have been updated to also call mat.app-background and mat.elevation-classes we can move the styles over without breaking any clients
> refactor: create mixins for core classes

- src/material/schematics/ng-update/index.ts
- src/material/schematics/ng-update/migrations/mat-core-removal.ts
- src/material/schematics/ng-update/test-cases/v19-mat-core-removal.spec.ts
* Removes uses of the core mixin and replaces them with two mixins. One to generate the mat-app-background class, and one to generate the mat-elevation classes.
> feat(material/schematics): create v19 core removal schematic

- CHANGELOG.md
> docs: release notes for the v18.2.6 release

- src/material/tabs/tab-config.ts
- src/material/tabs/tab-group.spec.ts
- src/material/tabs/tab-group.ts
- tools/public_api_guard/material/tabs.md
users can align tabs label via config now rather than adding `mat-tab-align` property on each tab group
fixes #29685
> feat(material/tabs): add `alignTabs` in `MatTabsConfig`

- src/material-date-fns-adapter/adapter/date-fns-adapter.spec.ts
- src/material-date-fns-adapter/adapter/date-fns-adapter.ts
- src/material-date-fns-adapter/adapter/date-fns-formats.ts
- src/material-luxon-adapter/adapter/luxon-date-adapter.spec.ts
- src/material-luxon-adapter/adapter/luxon-date-adapter.ts
- src/material-luxon-adapter/adapter/luxon-date-formats.ts
- src/material-moment-adapter/adapter/moment-date-adapter.spec.ts
- src/material-moment-adapter/adapter/moment-date-adapter.ts
- src/material-moment-adapter/adapter/moment-date-formats.ts
- src/material/core/datetime/date-adapter.ts
- src/material/core/datetime/date-formats.ts
- src/material/core/datetime/native-date-adapter.spec.ts
- src/material/core/datetime/native-date-adapter.ts
- src/material/core/datetime/native-date-formats.ts
- src/material/core/option/option-parent.ts
- src/material/core/option/option.ts
- src/material/input/input-value-accessor.ts
- src/material/input/input.ts
- tools/public_api_guard/material/core.md
- tools/public_api_guard/material/input.md
Includes a few adjustments to the date adapters.
> Date adapter changes

- src/material/chips/chip-listbox.spec.ts
- src/material/chips/chip-set.ts
- src/material/chips/chip.ts
- tools/public_api_guard/material/chips.md
The chip set has been set up in a way where it syncs its state to the chips, instead of the other way around which we follow in other components. This means that if its `disabled` state changes later, it can ovewrite the state that the user explicitly set on the chip.
These changes make the logic a bit more robust by writing to a different field.
Fixes #29783.
> fix(material/chips): chip set overwriting disabled state

- src/material/core/datetime/native-date-adapter.ts
Some browsers provide information about the first day of the week so we can infer it in the `NativeDateAdapter`.
> fix(material/core): infer first day of week in native date adapter

- src/material-date-fns-adapter/adapter/date-fns-adapter.spec.ts
- src/material-date-fns-adapter/adapter/date-fns-adapter.ts
- src/material-luxon-adapter/adapter/luxon-date-adapter.spec.ts
- src/material-luxon-adapter/adapter/luxon-date-adapter.ts
- src/material-moment-adapter/adapter/moment-date-adapter.spec.ts
- src/material-moment-adapter/adapter/moment-date-adapter.ts
- src/material/core/datetime/date-adapter.ts
- src/material/core/datetime/native-date-adapter.spec.ts
- src/material/core/datetime/native-date-adapter.ts
- tools/public_api_guard/material/core.md
Makes the changes that came up during the code review of #29799, but weren't pushed to the branch by accident.
> refactor(multiple): re-add missing feedback

- src/google-maps/map-advanced-marker/map-advanced-marker.ts
refactor(google-maps/map-advanced-marker): remove duplicate condition for setting content
Seems like the condition for setting the `advancedMarker.content` is redundant here:
I think it's safe to remove the first condition.
> refactor(google-maps/map-advanced-marker): remove duplicate condition for setting content

- src/cdk/drag-drop/resets.scss
Fixes that the combination of setting `align-self: center` and the user agent styling of `inset: 0` on popovers was breaking the positioning of the preview.
Fixes #29809.
> fix(cdk/drag-drop): positioning thrown off with align-self

- src/material/datepicker/datepicker.md
update Datepicker documentation for mobile a11y screen reader compatibility for datepickers with no icon buttons. will also be removing the two examples in the XAP gallery that have no Datepicker toggles in order to pass GAR testing. See cl/681589416
fixes b/292120265
> fix(material/datepicker): update documentation

- CHANGELOG.md
> docs: release notes for the v18.2.7 release

- src/cdk/stepper/stepper.ts
- tools/public_api_guard/cdk/stepper.md
Fixes a couple of issues with the integration between the CDK stepper and the forms module.
Previously we were mocking out the `AbstractControl` type, because we didn't want to bring in additional code for the optional forms integration. That's no longer necessary, because we can use type-only imports.
`CdkStepper` has a `reset` method that reset all the controls to their initial values, but that won't necessarily put the form into its initial state, because form controls also show errors on submit by default and `AbstractControl.reset` won't reset the submitted state.
These changes add a call to reset all child forms to their unsubmitted state.
Fixes #29781.
> Stepper forms integrations fixes

- src/cdk/dialog/dialog-config.ts
- src/cdk/dialog/dialog.ts
- src/cdk/overlay/overlay.ts
- src/cdk/portal/dom-portal-outlet.ts
- src/material/dialog/dialog-config.ts
- src/material/menu/menu-content.ts
- src/material/tabs/tab-body.ts
- tools/public_api_guard/cdk/dialog.md
- tools/public_api_guard/cdk/portal.md
- tools/public_api_guard/material/dialog.md
Removes the final places where we were referring to `ComponentFactoryResolver` in our code.
> fix(multiple): remove final references to ComponentFactoryResolver

- .ng-dev/commit-message.mts
`form-field` scope was repeated twice in in commit message config
> ci: `form-field` was added twice to commit scopes array

- tools/extract-tokens/extract-tokens.ts
Reworks how we extract the tokens so we can output `override` calls instead of the full CSS variables.
> build: rework tokens extraction

- src/material/core/_core-theme.scss
- tools/extract-tokens/extract-tokens.ts
Includes a couple of changes (see individual commits) to ensure that we extract tokens correctly from the `core-theme` and that we correctly reflect tokens whose names overlap between different prefixes.
> Token extraction updates

- tools/extract-tokens/extract-tokens.ts
Fixes an error that is currently breaking the patch branch, because we didn't have a resolver for imports like `@use '@angular/cdk';`.
> build: account for absolute paths in token extraction

- src/material/icon/icon.ts
This pull request fixes a broken link in the documentation for the Angular Material `icon` component. 
**Changes:**
- The incorrect link in `components/src/material/icon/icon.ts` has been updated to the correct one.
**Motivation:**
- A broken link can lead to confusion and a poor user experience when reading the documentation.
**No functionality or API was modified.**
- closes #29838 
Please review and merge if everything looks good. Let me know if any further changes are needed.
> docs(material/icon): #29838 update broken link in icon documentation

- CHANGELOG.md
> docs: release notes for the v18.2.8 release

- src/material/badge/badge.scss
- src/material/core/tokens/m2/mat/_badge.scss
- src/material/core/tokens/m3/mat/_badge.scss
Fixes that at some point the M3 badge regressed to where the content was always being truncated. The regression was likely, because the previous setup was very fragile and it was relying on some tokens never being emitted.
These changes remove the need to rely on fallbacks and resolve the issue by setting the correct token values.
Fixes #29788.
> fix(material/badge): content incorrectly truncated in M3

- src/material/dialog/dialog.scss
Updates Angular Component Dialog component to have a max-height of 95vh which gives it a calculable height for its contents to adjust on smaller screens or in landscape mode so that the action buttons are able to be accessed by scrolling rather than the dialog window cutting them off.
[Before screencast](https://screencast.googleplex.com/cast/NDYwNTM5NjIzNTg0NTYzMnxkNTBkMzBmYS1mZQ)
[After screencast](https://screencast.googleplex.com/cast/NTI3OTgxMDMwNDYwNjIwOHw0YTkxYjc3ZS04Yw)
Fixes b/323588333
> fix(material/dialog): updates dialog max-height in landscape

- src/material/core/tokens/m3/definitions/_md-comp-elevated-card.scss
update elevated card container color from `surface` to  `surface-container-low` matching the M3 specification
fixes #29163
---
before:
after:
> fix(material/card): elevated card container color

- src/dev-app/theme/theme-demo.html
- src/dev-app/theme/theme-demo.scss
- src/material/_index.scss
- src/material/core/tokens/_m3-system.scss
Adds a new Sass mixin API to let clients change specific system-level tokens. Similar to the overrides API provided by component theme files
> feat(material/core): add theme-overrides mixin

- src/components-examples/cdk/tree/cdk-tree-nested-children-accessor/cdk-tree-nested-children-accessor-example.css
- src/components-examples/cdk/tree/cdk-tree-nested-children-accessor/cdk-tree-nested-children-accessor-example.html
- src/components-examples/cdk/tree/cdk-tree-nested-children-accessor/cdk-tree-nested-children-accessor-example.ts
- src/components-examples/cdk/tree/cdk-tree-nested-level-accessor/cdk-tree-nested-level-accessor-example.css
- src/components-examples/cdk/tree/cdk-tree-nested-level-accessor/cdk-tree-nested-level-accessor-example.html
- src/components-examples/cdk/tree/cdk-tree-nested-level-accessor/cdk-tree-nested-level-accessor-example.ts
- src/components-examples/cdk/tree/cdk-tree-nested/cdk-tree-nested-example.css
- src/components-examples/cdk/tree/cdk-tree-nested/cdk-tree-nested-example.html
Fixes the following issues with the tree live examples:
* Both the tree node and the toggle were marked as toggles which meant that clicking anywhere would close the tree.
* The toggles weren't centered relative to the text.
* A couple of examples had the same name and one had weird punctuation.
Fixes #29830.
> docs(cdk/tree): fix several live example issues

- src/cdk/tree/tree.spec.ts
- src/cdk/tree/tree.ts
- tools/public_api_guard/cdk/tree.md
Currently the CDK tree handle any keyboard event coming from a descendant. This problematic if there are interactive elements like inputs inside the tree, because their default behavior will be prevented.
This change switches to only handling events coming either directly from the tree or directly from a tree node.
Fixes #29828.
> fix(cdk/tree): only handle keyboard events directly from the node

- CHANGELOG.md
> docs: release notes for the v18.2.9 release

- src/material/chips/chip-input.spec.ts
- src/material/chips/chip-input.ts
Fixes that that the chip input was emitting the `matChipEnd` event while the user is holding down the separator key.
Fixes #29883.
> fix(material/chips): emitting end event multiple times when holding down key

- src/material/core/_core-theme.scss
Fixes that we were supporting overrides for `mat-option` through the `core-overrides` mixin, but not for `mat-optgroup`.
> fix(material/core): allow optgroup overrides through core-overrides

- src/google-maps/public-api.ts
- tools/public_api_guard/google-maps/google-maps.md
Exposes all the types related to the clusterer from the `google-maps` endpoint.
Fixes #29901.
> fix(google-maps): expose all clusterer types

- tools/dgeni/common/decorators.ts
- tools/dgeni/common/dgeni-definitions.ts
- tools/dgeni/templates/macros.html
changes how deprecated fields are generated for docs content, before this commit deprecated related text was shown via `title` attribute on hover and the `deprecated` tag description was never shown unless user check it manually via code. this commit exports `deprecated` tag description to reflect it directly in docs using `material/tooltip` on doc site
> build: update dgeni templates to include `deprecated` tag description

- src/dev-app/theme-m3.scss
- src/material/core/theming/_config-validation.scss
- src/material/core/tokens/_m3-system.scss
By default, system variable use `light-dark()` CSS values. Users can define `light`, `dark`, or `light dark` (user system) to change between modes.
> feat(material/core): default to color-scheme theme type

- src/cdk-experimental/popover-edit/popover-edit.spec.ts
- src/cdk/listbox/listbox.spec.ts
- src/cdk/portal/portal.spec.ts
- src/cdk/scrolling/virtual-scroll-viewport.spec.ts
- src/material-experimental/popover-edit/popover-edit.spec.ts
- src/material/button-toggle/button-toggle.spec.ts
- src/material/chips/chip-set.spec.ts
- src/material/datepicker/datepicker-actions.spec.ts
- src/material/progress-spinner/progress-spinner.spec.ts
- src/material/radio/radio.spec.ts
- src/material/sidenav/drawer.spec.ts
- src/material/sidenav/sidenav.spec.ts
- src/material/tabs/tab-body.spec.ts
- src/material/tabs/tab-group.spec.ts
- src/material/tabs/tab-header.spec.ts
- src/material/toolbar/toolbar.spec.ts
Removes all our imports of `CommonModule` in tests since it wasn't being used for anything.
> test(multiple): remove CommonModule imports

- src/material/tabs/tab-body.ts
Removes a workaround that's no longer necessary now that we don't support IE.
> fix(material/tabs): remove IE animation workaround

- src/material/core/theming/_config-validation.scss
- src/material/core/tokens/_m3-system.scss
Color input was checking if a map was provided (primary, tertiary, theme type) but the alternative is a palette, which is also a map. This adds the right nuance.
TODO: Send a PR that adds types to Sass so this can be more  intuitive
> fix(material/core): correctly identify color input

- src/material/core/theming/_definition.scss
- src/material/core/theming/tests/theming-definition-api.spec.ts
- src/material/core/tokens/_m3-system.scss
TODO: Write a schematic that makes this backwards-compatible for any existing usages of "use-system-variables" by **adding `use-system-prefix: sys` to existing theme code**
> feat(material/core): switch system prefix from sys to mat-sys

- src/material/schematics/ng-generate/theme-color/README.md
- src/material/schematics/ng-generate/theme-color/index.spec.ts
- src/material/schematics/ng-generate/theme-color/index.ts
Schematic changes needed to work with #29907
> feat(material/schematics): Update custom theme schematic to work with light-dark and use theme-overrides mixin

- CHANGELOG.md
> docs: release notes for the v18.2.10 release

- CHANGELOG.md
- package.json
Also this PR cherry-picks the changelog for v19.0.0-next.10 into the main branch so that the changelog is up to date.
> Update next branch to reflect new release-train "v19.1.0-next.0".

- src/material/stepper/stepper.ts
Removes a workaround that's no longer necessary now that we don't support IE.
> fix(material/stepper): remove IE animation workaround

- src/cdk-experimental/selection/selection-module.ts
- src/material-experimental/selection/selection-module.ts
- src/material/autocomplete/module.ts
- src/material/card/module.ts
- src/material/datepicker/datepicker-module.ts
- src/material/form-field/module.ts
- src/material/list/list-module.ts
- src/material/menu/module.ts
- src/material/progress-spinner/module.ts
- src/material/radio/module.ts
- src/material/select/module.ts
- src/material/stepper/stepper-module.ts
- src/material/tooltip/module.ts
- tools/public_api_guard/material/autocomplete.md
- tools/public_api_guard/material/card.md
- tools/public_api_guard/material/datepicker.md
- tools/public_api_guard/material/form-field.md
- tools/public_api_guard/material/list.md
- tools/public_api_guard/material/menu.md
- tools/public_api_guard/material/progress-spinner.md
- tools/public_api_guard/material/radio.md
- tools/public_api_guard/material/select.md
- tools/public_api_guard/material/stepper.md
- tools/public_api_guard/material/tooltip.md
Removes all the imports of `CommonModule` from the individual components since it isn't being used anywhere.
> refactor(multiple): remove CommonModule imports

- src/material/sidenav/drawer.ts
Removes a workaround that's no longer necessary now that we don't support IE.
> fix(material/sidenav): remove IE animation workaround

- src/material/core/tokens/_m3-system.scss
None of our components use these 36 motion variables and it takes up quite a bit of space in the styles
> fix(material/core): remove unused motion system vars

- src/material/button/button-base.ts
- src/material/button/button.spec.ts
Fixes that the anchor-based `MatButton` wasn't setting `aria-disabled` when `disabledInteractive` is enabled.
Fixes #29923.
> fix(material/button): anchor not handling disabledInteractive correctly

- src/components-examples/material/form-field/form-field-custom-control/form-field-custom-control-example.ts
Fixes that form-field-custom-control-example.ts wasn't correctly handling focused events. 
This can easily be checked on the official docs page or the stackblitz, here's two sample screenshots:
In the above screenshot, the user has focused the input, but the form field outline is not becoming blue.
Another failure case is when you leave the input: in this case, it will stay forever outlined in blue:
> fix(form-field-custom-control-example) _focused signal not firing stateChanges

- src/google-maps/schematics/ng-update/index.ts
* Fixes that the schematic was throwing an error for non-UTF8 files, because we were using `Tree.readText` instead of `Tree.read.toString`.
* Fixes that we appear to be traversing the `node_modules`.
Fixes #29917.
> fix(google-maps): resolve CLI errors in ng update schematic

- CHANGELOG.md
> docs: release notes for the v18.2.11 release

- tools/extract-tokens/BUILD.bazel
- tools/extract-tokens/extract-tokens.ts
Currently the example in the styling pages on the docs site is generated at runtime which doesn't allow us to highlight it as code correctly. These changes move the generation of the example into the main repo and add syntax highlighting.
> build: generate styling example during the build

- src/material/datepicker/calendar-header.html
- src/material/datepicker/calendar.scss
The calendar's next/previous icons are currently rendered using an `:after` element, borders and a transform. This makes them hard to position accurately and fragile to changes in the container size. These changes switch to using SVG which is more robust.
Fixes #29956.
> fix(material/datepicker): use SVG icons for calendar

- src/material/core/tokens/_token-definition.scss
- src/material/core/tokens/m3/mdc/_filled-text-field.scss
Fixes that the form field had the wrong border radius when using a system-level theme in M3.
> fix(material/form-field): incorrect form field border radius with system-level themes

- src/google-maps/map-advanced-marker/README.md
> docs(google-maps/map-advanced-marker): README.md added

- src/material/core/tokens/m2/mat/_menu.scss
- src/material/core/tokens/m3/mat/_menu.scss
- src/material/menu/menu-panel.ts
- src/material/menu/menu-trigger.ts
- src/material/menu/menu.html
- src/material/menu/menu.scss
- src/material/menu/menu.spec.ts
- src/material/menu/menu.ts
- tools/public_api_guard/material/menu.md
Currently the menu's elevation is set using elevation classes, because earlier versions of the Material spec called for the elevation to increase for each level in a nested menu. That's no longer part of the spec and in v19 we won't include the elevation classes by default anymore. These changes remove the code that was handling the dynamic elevation and set the elevation using a token instead.
> fix(material/menu): use static elevation

- package.json
- src/material/core/m2/_theming.scss
- src/material/core/theming/_theming.scss
- src/material/core/tokens/_m3-tokens.scss
- src/material/core/tokens/m2/mat/_badge.scss
- src/material/core/tokens/m2/mat/_datepicker.scss
- src/material/core/tokens/m2/mat/_sort.scss
- yarn.lock
In the latest version of Sass, the compiler logs a warning for usages of global functions. These changes switch our code to import the functions instead.
> fix(multiple): remove usages of Sass globals

- CHANGELOG.md
> docs: release notes for the v19.0.0-rc.1 release

- CHANGELOG.md
> docs: release notes for the v18.2.12 release

- src/material/schematics/ng-update/index.ts
- src/material/schematics/ng-update/migrations/explicit-system-variable-prefix.ts
- src/material/schematics/ng-update/test-cases/v19-explicit-system-variable-prefix.spec.ts
In v19 we're changing the default system variables prefix from `sys` to `mat-sys`. These changes add a schematic that will update existing apps to keep the `sys` prefix.
> fix(material/schematics): add explicit system variable prefix schematic

- src/cdk/schematics/update-tool/index.ts
This commit addresses a typographical error in the documentation by replacing "form" with "from" for accuracy and clarity.
> Corrected typo in documentation: change "form" to "from"

- src/material/bottom-sheet/bottom-sheet-config.ts
- src/material/bottom-sheet/bottom-sheet.spec.ts
- tools/public_api_guard/material/bottom-sheet.md
these properties were missing from the config but still worked as they were passed to dialog under the hood to avoid type errors
fixes #28832
> fix(material/bottom-sheet): add `height` `minHeight` `maxHeight` to config

- src/cdk/table/table.spec.ts
- src/cdk/table/table.ts
We were omitting `role="cell"` on native `td` elements, because the browser should be setting it implicitly, but based on the discussion in #29784, it seems like Safari doesn't do it. These changes switch to always setting the `role`.
Fixes #29784.
> fix(cdk/table): set explicit role on all cells

- src/material/sidenav/drawer.scss
- src/material/sidenav/drawer.ts
- src/material/sidenav/sidenav.ts
- tools/public_api_guard/material/sidenav.md
Fixes that the content of the sidenav was jumping when the page is hydrated, because we can't measure the sidenav on the server.
> fix(material/sidenav): prevent the content from jumping when hydrated

- src/material/core/theming/_inspection.scss
- src/material/core/theming/_m2-inspection.scss
- src/material/core/theming/tests/theming-inspection-api.spec.ts
Fixes that the `get-theme-color` function was incorrectly validating its number of arguments. We were always checking if the arguments are between 2 and 4, whereas it actually accepts either 2 or 3 for M3 themes and between 2 and 4 for M2 themes.
Fixes #29819.
> fix(material/core): incorrect validation in get-theme-color

- src/dev-app/youtube-player/youtube-player-demo.html
- src/dev-app/youtube-player/youtube-player-demo.ts
- src/youtube-player/youtube-player.spec.ts
- src/youtube-player/youtube-player.ts
- tools/public_api_guard/youtube-player/youtube-player.md
Includes the following fixes for the `youtube-player`:
Fixes that the `startSeconds` input wasn't doing anything if there's a placeholder. This used to work, but seems to have broken during the transition to using the placeholder.
Fixes that the `youtube-player`'s `ready` event wasn't emitting. The issue is that we create the outputs lazily based on a stream of newly-created players, however that stream emits after the `ready` event.
Fixes #29874.
> Youtube player startSeconds and ready event not working

- src/cdk/tree/nested-node.ts
- src/cdk/tree/tree.ts
- src/components-examples/material/tree/tree-nested-child-accessor-overview/tree-nested-child-accessor-overview-example.css
- src/components-examples/material/tree/tree-nested-child-accessor-overview/tree-nested-child-accessor-overview-example.html
- src/components-examples/material/tree/tree-nested-overview/tree-nested-overview-example.css
- src/components-examples/material/tree/tree-nested-overview/tree-nested-overview-example.html
- src/material/tree/testing/tree-harness.spec.ts
- tools/public_api_guard/cdk/tree.md
Currently the tree somewhat works if a flat node and a nested node are used together, however they can break down depending on the data that is passed in.
These changes add a warning that will tell users to use a consistent node type.
Fixes #29927.
> fix(cdk/tree): warn if mixed node types are used within the same tree 

- src/cdk/testing/selenium-webdriver/selenium-web-driver-element.ts
- src/cdk/testing/testbed/unit-test-element.ts
`plaintext-only` is a valid value for `contenteditable` that specifies that the raw text is editable but rich formatting is disabled. This is supported now for every browser except for Firefox, where it is now supported in a nightly version. See more specifications [here]([https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable](https://www.google.com/url?sa=D&q=https%3A%2F%2Fdeveloper.mozilla.org%2Fen-US%2Fdocs%2FWeb%2FHTML%2FGlobal_attributes%2Fcontenteditable)).
> Allow setting setContenteditableValue to `plaintext-only` for tests

- CHANGELOG.md
> docs: release notes for the v18.2.13 release

- CHANGELOG.md
> docs: release notes for the v19.0.0-rc.2 release

- src/material/form-field/form-field.ts
- src/material/input/input.spec.ts
- src/material/input/input.ts
Includes the following fixes for how we deal with `ariab-describedby` in the form field:
Currently we set the `aria-describedby` every time the state of the form control changes. This is excessive, because it only needs to happen if the error state or `userAriaDescribedBy` change.
Currently there are two sources of an `aria-describedby` for a `matInput`: the IDs of the hint/error message in the form field and any custom ones set through `aria-describedby`. This is insufficient, because the ID can also come from a direct DOM manipulation like in the `AriaDescriber`.
These changes tweak the logic to try and preserve them, because currently they get overwritten.
Fixes #30011.
> Form field aria-describedby fixes

- src/material/menu/menu-trigger.ts
- src/material/menu/menu.html
- src/material/menu/menu.spec.ts
- src/material/menu/menu.ts
- src/material/menu/testing/menu-harness.ts
Currently `mat-menu` handles it keyboard events in the template, however this ignores the overlay's stacking context which can capture some events that it shouldn't.
These changes switch the menu to handling the events through the common dispatcher instead.
Fixes #29996.
> fix(material/menu): handle keyboard events through dispatcher

- src/cdk/table/table.ts
Cloned from original author's change but is failing CLA https://github.com/angular/components/issues/29922
This ensures the differ is run without short-circuiting and skipping columns, which is apparently important for change detection reasons
Fixes https://github.com/angular/components/issues/29922
> fix(cdk/table): run differ for all columns

- CHANGELOG.md
> docs: release notes for the v19.0.0-rc.3 release

- CHANGELOG.md
> docs: release notes for the v18.2.14 release

- src/material/datepicker/calendar-body.html
- src/material/datepicker/calendar-body.ts
- src/material/datepicker/datepicker-intl.ts
- tools/public_api_guard/material/datepicker.md
Updates Angular Components Datepicker calendar-body .ts and .html files to add id values for if there is a comparison start/end date and to provide values to their respective html values to provide an aria-describedby value to be announced for screenreaders when comparison dates are present.
[Before screenshot button no aria-describedby](https://screenshot.googleplex.com/AFmGuJMVmyxm94d)
[Before screenshot no comparison date spans](https://screenshot.googleplex.com/4fiZy7k5iFBnDTt)
[Before fix screencast](https://screencast.googleplex.com/cast/NTc5Mjk1NTQ5ODQ5NjAwMHw0MTM4ZGYyYy03NA)
[After screenshot button aria-describedby](https://screenshot.googleplex.com/AZan8gohXj4wzVX)
[After screenshot span with respective aria-describedby id](https://screenshot.googleplex.com/9AM4kgcU2xQdy9J) …
> fix(material/datepicker): adds comparison ids and aria-describedby spans

- src/material/slider/slider.md
update documentation to let users know about passing 3:1 non text contrast ratio for active and inactive slider tracks
fixes b/286300099
> fix(material/slider): update documentation

- src/material/chips/chip-grid.ts
Fixes that the chip grid wasn't emitting to its `stateChanges` when it becomes disabled which meant that the parent form field might not update correctly.
Fixes #30017.
> fix(material/chips): emit state changes when chip grid is disabled

- src/material/button-toggle/button-toggle.html
- src/material/button-toggle/button-toggle.scss
- src/material/button-toggle/button-toggle.spec.ts
- src/material/button-toggle/button-toggle.ts
Currently the checkbox inside button toggle is a bit jarring. These changes add an animation to it.
> fix(material/button-toggle): animate checkbox

- src/cdk/a11y/focus-monitor/focus-monitor.ts
- src/cdk/a11y/live-announcer/live-announcer.ts
- src/material/bottom-sheet/bottom-sheet-ref.ts
- src/material/dialog/dialog-ref.ts
- src/material/snack-bar/snack-bar-container.ts
- src/material/snack-bar/snack-bar-ref.ts
Fixes that some places were raising an error due to the return type of `setTimeout` being different between the browser and Node.
> fix(multiple): use cross-compatible type for setTimeout

- tools/extract-tokens/extract-tokens.ts
Fixes that the token extraction script wasn't exposing some tokens, because it failed to determine their type. The two main root causes I saw were that some tokens aren't defined in M3 and some tokens were hardcoded. I've also added a hard error in case we can't resolve the type of a token.
Fixes #30082.
> build: some tokens not being extracted

- src/material/sort/sort-animations.ts
- src/material/sort/sort-header.html
- src/material/sort/sort-header.scss
- src/material/sort/sort-header.ts
- src/material/sort/sort.spec.ts
- tools/public_api_guard/material/sort.md
For a long time the sort header's animation was set up by rendering out 4 `div` elements and then arranging them to look like an arrow. This is somewhat complicated to maintain, difficult to customize, in some cases it leads to weird visual bugs and ends up triggering excessive change detections. On top of that, because it depends on `@angular/animations`, it is prone to memory leaks (see https://github.com/angular/angular/issues/54149).
These changes aim to simplify the component and make it more robust by using an `svg` icon and dealing with the animations using CSS.
Fixes #9758.
Fixes #9844.
Fixes #10088.
Fixes #15451.
Fixes #19441.
Fixes #10242.
> fix(material/sort): simplify animations

- src/material/core/option/optgroup.scss
Fixes that we weren't setting the color of the `mat-optgroup` label correctly, resulting in it being taken from `mat-list`.
Fixes #30081.
> fix(material/core): optgroup label color not inferred correctly

- src/cdk/menu/menu-trigger.ts
Disables flexible dimensions for the CDK menu since supporting them properly requires some CSS tweaks and we don't control the CSS of the menu.
Fixes #30077.
> fix(cdk/menu): disable flexible dimensions

- src/components-examples/material/button/button-overview/button-overview-example.css
Fixes that the container in the button example was too narrow and was clipping the button.
Fixes #30091.
> docs(material/button): avoid clipping icon

- src/components-examples/material/timepicker/timepicker-custom-icon/timepicker-custom-icon-example.html
Fixes that one of the timepicker examples didn't have an icon.
Fixes #30076.
> docs(material/timepicker): fix missing icon in example

- src/material/button-toggle/button-toggle.spec.ts
- src/material/button-toggle/button-toggle.ts
Fixes an issue where the button toggle group would reset all the buttons back to `tabindex="-1"` if they're all static (e.g. not in a loop) and none of them match the value.
Fixes #30097.
> fix(material/button-toggle): unable to tab into ngModel-based group on first render

- package.json
- src/youtube-player/package.json
- src/youtube-player/youtube-player.ts
- yarn.lock
Updates the YouTube player to the latest typings to account for a breaking change.
> fix(youtube-player): update to latest typings

- CHANGELOG.md
> docs: release notes for the v19.0.2 release

- src/material/expansion/expansion-animations.ts
- src/material/expansion/expansion-panel-header.html
- src/material/expansion/expansion-panel-header.scss
- src/material/expansion/expansion-panel-header.ts
- src/material/expansion/expansion-panel.html
- src/material/expansion/expansion-panel.scss
- src/material/expansion/expansion-panel.ts
- src/material/expansion/expansion.spec.ts
- tools/public_api_guard/material/expansion.md
Reworks the expansion panel to animate purely with CSS, rather than going through the `@angular/animations` module. This simplifies the setup and allows us to resolve several long-standing bug reports.
Fixes #27946.
Fixes #22715.
Fixes #21434.
Fixes #20517.
Fixes #17177.
Fixes #16534.
Fixes #16503.
Fixes #14952.
Fixes #14759.
Fixes #14075.
Fixes #11765.
> fix(material/expansion): switch away from animations module

- src/material/timepicker/timepicker-input.ts
- src/material/timepicker/timepicker-toggle.html
- src/material/timepicker/timepicker-toggle.ts
- src/material/timepicker/timepicker.scss
- src/material/timepicker/timepicker.spec.ts
- src/material/timepicker/timepicker.ts
- tools/public_api_guard/material/timepicker.md
Fixes that the timepicker toggle wasn't considered as disabled automatically when the timepicker is disabled.
Fixes #30134.
> fix(material/timepicker): disable toggle if timepicker is disabled

- src/material/paginator/paginator.html
- src/material/paginator/paginator.spec.ts
- src/material/paginator/paginator.ts
- tools/public_api_guard/material/paginator.md
The changes in #29379 made the paginator interactive while they're disabled in order to improve accessibility, but as a result it also allows for the buttons to navigate while they're disabled.
These changes add internal checks to ensure that the buttons don't navigate while disabled. I've also cleaned up the logic a bit so we don't have four different places that deal with navigations.
Fixes #30124.
> fix(material/paginator): ignore clicks on disabled buttons

- src/material/timepicker/timepicker-input.ts
Fixes that the timepicker was clobbering otherwise parseable values when they're assigned through the `ControlValueAccessor`.
Fixes #30140.
> fix(material/timepicker): deserialize ControlValueAccessor values correctly

- src/components-examples/material/select/index.ts
- src/components-examples/material/select/select-selectable-null/select-selectable-null-example.html
- src/components-examples/material/select/select-selectable-null/select-selectable-null-example.ts
- src/material/select/select.md
- src/material/select/select.spec.ts
- src/material/select/select.ts
- tools/public_api_guard/material/select.md
By default `mat-select` treats options with nullable values as "reset options", meaning that they can't be selected, but rather they clear the select's value. This behavior is based on how the native `select` works, however in some cases it's not desirable. These changes add an input that users can use to opt out of the default behavior.
Fixes #25120.
> fix(material/select): add opt-in input that allows selection of nullable options

- src/material/menu/menu-content.ts
- src/material/menu/menu-trigger.ts
- src/material/menu/menu.spec.ts
Reworks the menu so that its removal isn't bound by animations. The current approach is somewhat brittle and makes it difficult to eventually switch to a fully CSS-based animation.
> fix(material/menu): decouple menu lifecycle from animations

- src/material/table/table-data-source.ts
Simplifies the table datasource's default filter predicate so that it iterates over each data value directly rather than building a string with delimited characters.
Code was pulled and slightly modified from #21362
New logic performs quite a bit better than before: https://jsbench.me/4bkjp85g44/1
> fix(material/table): improve filter predicate efficiency

- src/material/tooltip/tooltip.scss
Fixes that the line height of the `body` element was affecting the gap between the tooltip and the trigger.
Fixes #30132.
> fix(material/tooltip): body line height affecting gap

- src/cdk/drag-drop/directives/drag-handle.ts
- src/cdk/drag-drop/directives/drag.ts
- src/cdk/drag-drop/directives/standalone-drag.spec.ts
- src/cdk/drag-drop/drag-drop-registry.ts
- tools/public_api_guard/cdk/drag-drop.md
Currently the `cdkDragHandle` directive registers itself with the parent by resolving it through DI. This doesn't work if the directive is declared in a separate embedded view (e.g. `ng-template`) that is then projected into the draggable element. It can be problematic when adding dragging support to a `mat-table`.
These changes fix the issue by falling back to resolving the draggable directive through the DOM.
Fixes https://github.com/angular/components/issues/29475.
> fix(cdk/drag-drop): resolve projected handles

- src/cdk/dialog/dialog-container.ts
- src/cdk/drag-drop/drag-drop.ts
- src/cdk/drag-drop/drag-ref.ts
- src/cdk/drag-drop/preview-ref.ts
- src/cdk/observers/private/shared-resize-observer.ts
- src/cdk/overlay/dispatchers/overlay-keyboard-dispatcher.spec.ts
- src/cdk/overlay/dispatchers/overlay-keyboard-dispatcher.ts
- src/cdk/overlay/fullscreen-overlay-container.ts
- src/cdk/overlay/overlay-ref.ts
- src/cdk/overlay/overlay.ts
- src/cdk/scrolling/viewport-ruler.ts
- src/cdk/text-field/autosize.ts
- src/material/autocomplete/autocomplete-trigger.ts
- src/material/button/button-base.ts
- src/material/expansion/expansion-panel.ts
- src/material/form-field/directives/line-ripple.ts
- src/material/input/input.ts
- src/material/list/selection-list.ts
- src/material/progress-bar/progress-bar.ts
- src/material/radio/radio.ts
- src/material/sidenav/drawer.ts
- src/material/slider/slider-input.ts
- src/material/slider/slider-thumb.ts
- src/material/timepicker/timepicker-input.ts
- tools/public_api_guard/cdk/drag-drop.md
- tools/public_api_guard/cdk/overlay.md
Switches our manual calls into `addEventListener` to use the renderer instead so that tooling (e.g. the tracing service) gets notified about them.
Note that these changes only include the events that don't pass event options. The remaining events will be changed in a follow-up, because they require us to update to the latest `next` version of Angular.
> refactor(multiple): use renderer for manual event bindings

- src/cdk/drag-drop/directives/standalone-drag.spec.ts
- src/cdk/drag-drop/drag-drop-registry.spec.ts
- src/cdk/drag-drop/drag-drop-registry.ts
In some cases we might not get a `touchend`, because the sequence was interrupted. These changes add a fallback.
> fix(cdk/drag-drop): stop dragging on touchcancel

- src/material/list/selection-list.spec.ts
- src/material/list/selection-list.ts
Fixes https://github.com/angular/components/issues/24781
> fix(material/list): enable MacOS select all with command+a

- src/material/table/table.scss
This affects tables that want to use a `th` element in each data row. The last row's header cell should not have a bottom border, similar to other data cells in the last row
Inspired by #27762 which cannot be merged due to missing CLA. 
Fixes https://github.com/angular/components/issues/27731
> fix(material/table): set border none for header cells on last row

- tools/extract-tokens/extract-tokens.ts
System variables are prefixed with "mat-sys", not "sys" (this was the case in v18)
Currently the docs use the old prefix
> docs: update system var prefix

- src/material/schematics/ng-generate/theme-color/README.md
This PR fixes a syntax error in the usage of the `mat.theme` mixin in the SCSS files of the project. The error occurred due to incorrect wrapping of the Sass map passed as an argument to the `mat.theme` mixin. Specifically, the map was not correctly enclosed in an additional pair of parentheses, leading to a compilation error.
```
✘ [ERROR] expected ")".
╷
36 │         color: (
```
- Wrapped the theme configuration map inside an additional set of parentheses for proper syntax in the `@include mat.theme()` function.
> docs(material/theming): fix typo in custom theme guide

- src/cdk-experimental/column-resize/column-resize.ts
- src/cdk-experimental/column-resize/overlay-handle.ts
- src/cdk/listbox/listbox.ts
- src/cdk/menu/menu-aim.ts
- src/cdk/menu/menu-base.ts
- src/cdk/menu/menu-item-checkbox.spec.ts
- src/cdk/menu/menu-item-radio.spec.ts
- src/cdk/menu/menu-item.spec.ts
- src/cdk/menu/menu-item.ts
- src/cdk/menu/menu-trigger.ts
- src/cdk/menu/pointer-focus-tracker.spec.ts
- src/cdk/menu/pointer-focus-tracker.ts
- src/cdk/overlay/position/flexible-connected-position-strategy.spec.ts
- src/cdk/scrolling/scroll-dispatcher.spec.ts
- src/cdk/scrolling/scroll-dispatcher.ts
- src/cdk/scrolling/scrollable.ts
- src/cdk/scrolling/virtual-scrollable-window.ts
- src/cdk/text-field/autosize.ts
- src/material/tabs/paginated-tab-header.ts
- tools/public_api_guard/cdk/menu.md
- tools/public_api_guard/cdk/scrolling.md
Replaces all of our usages of the rxjs `fromEvent` with direct event listeners going through the renderer. This has a few benefits:
* In most cases it made our code simpler and easier to follow.
* By going through the renderer, other tooling can hook into it (e.g. the tracing service).
* It reduces our reliance on rxjs.
I also ended up cleaning up the fragile testing setup in `cdk/menu` which would've broken any time we introduce a new `inject` call.
> refactor(multiple): replace fromEvent usages

- src/material/sort/sort-header.scss
Copied with #27494 which has failing CLA
> fix(material/sort): avoid center align for sort header

- src/material/autocomplete/autocomplete.ts
- src/material/chips/tokens.ts
- src/material/list/tokens.ts
- src/material/select/select.ts
This pr fixes a similar typo in below material components:
1. `autocomplete`
2. `chips`
3. `list`
4. `select`
A typo "**Wheter**" in above mentioned components.
Updated "**Wheter**" to "**Whether**".
> docs(material/components): fix typos in material components

- CHANGELOG.md
> docs: release notes for the v19.0.4 release

- src/cdk-experimental/popover-edit/table-directives.ts
- src/cdk/a11y/focus-monitor/focus-monitor.ts
- src/cdk/a11y/input-modality/input-modality-detector.ts
- src/cdk/drag-drop/drag-drop-registry.ts
- src/cdk/drag-drop/drag-ref.ts
- src/cdk/overlay/dispatchers/overlay-keyboard-dispatcher.spec.ts
- src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.spec.ts
- src/cdk/overlay/dispatchers/overlay-outside-click-dispatcher.ts
- src/cdk/text-field/autofill.ts
- src/material/core/private/ripple-loader.ts
- src/material/datepicker/calendar-body.ts
- src/material/menu/menu-trigger.ts
- src/material/tooltip/tooltip.ts
Rolls back the changes from https://github.com/angular/components/pull/30195, because it broke some internal clients.
> Roll back event changes

- WORKSPACE
Bazel needs to be told about the nested workspace, to avoid descending into that folder.
Followup for #30208
> build: point to the new material.angular.io workspace

- src/material/sort/sort-header.scss
Fixes that the sort header wasn't showing the arrow when it's focused.
Fixes #30196.
> fix(material/sort): show arrow on focus

- src/components-examples/material/sidenav/sidenav-responsive/sidenav-responsive-example.html
- src/components-examples/material/sidenav/sidenav-responsive/sidenav-responsive-example.ts
improvements:
- use signal instead of manually detect changes
- add access modifier to the class properties
- add missing import of routerLink
- replace deprecated add/removeListener with add/removeEventListener
> docs(material/sidenav): improve responsive example

- src/cdk/tree/tree.spec.ts
- src/cdk/tree/tree.ts
Fixes that the tree wasn't recursing down and expanding all child nodes when calling `expandAll`.
Fixes #29865.
> fix(cdk/tree): expandAll not expanding all nodes

- src/cdk/menu/menu-trigger.ts
- tools/public_api_guard/cdk/menu.md
Fixes that the CDK menu wasn't updating its position strategy after the first open.
Fixes #30145.
> fix(cdk/menu): not responding to position changes

- src/material/timepicker/timepicker-input.ts
- src/material/timepicker/timepicker.spec.ts
Fixes that the timepicker was marking itself as touched too early when clicking on an item in the dropdown.
Fixes #30223.
> fix(material/timepicker): don't mark as touched when blurred while dropdown is open

- material.angular.io/src/app/pages/component-category-list/component-category-list.html
> Fixed displaying external link in component-category-list.html

- src/cdk/menu/menu-base.ts
The CDK menu has some logic that forwards focus to the first item when the host is focused. The problem is that every time the user clicks on the scrollbar, they blur the current item and focus the menu which then forwards focus back to the first item which in turn causes the scroll position to jump to the top.
These changes add some logic to not forward focus when focus comes from a mouse interaction.
Fixes #30130.
> fix(cdk/menu): avoid resetting the scroll position when using the mouse

- src/material/datepicker/date-range-input-parts.ts
- src/material/datepicker/date-range-input.ts
- tools/public_api_guard/material/datepicker.md
Previously we had to define an injection token for the `MatDateRangeInput` in order to avoid circular references. Now we can do the same with a type-only imports so we can simplify the setup.
Fixes #30238.
> fix(material/datepicker): simplify DI setup

- src/cdk/scrolling/virtual-scrollable-window.ts
The `CdkVirtualScrollableWindow` was referring to the `document` directly which can break in SSR. These changes use the DI token instead.
> fix(cdk/scrolling): avoid SSR error in CdkVirtualScrollableWindow

- src/components-examples/cdk/overlay/cdk-overlay-basic/cdk-overlay-basic-example.html
Updates the overlay example to ensure that the state of the `isOpen` flag reflects the state of the overlay.
Fixes #30185.
> docs(cdk/overlay): keep state in sync in example

- src/material/paginator/paginator.ts
- tools/public_api_guard/material/paginator.md
Switches `mat-paginator` to use the `inject` function now that we've cleaned up the internal usages.
> refactor(material/paginator): switch to inject function

- src/dev-app/sidenav/sidenav-demo.ts
- src/material/sidenav/drawer-animations.ts
- src/material/sidenav/drawer.scss
- src/material/sidenav/drawer.ts
- src/material/sidenav/sidenav.ts
- tools/public_api_guard/material/sidenav.md
Reworks the sidenav to animate using CSS, rather than the animations module. This requires less JavaScript, is simpler to maintain and avoids some memory leaks caused by the animations module.
> fix(material/sidenav): switch away from animations module

- guides/material-2.md
- src/material/badge/badge.ts
- src/material/button/button-base.ts
- src/material/button/fab.ts
- src/material/checkbox/checkbox-config.ts
- src/material/checkbox/checkbox.ts
- src/material/chips/chip.ts
- src/material/datepicker/datepicker-base.ts
- src/material/form-field/form-field.ts
- src/material/icon/icon.ts
- src/material/list/list-option.ts
- src/material/list/selection-list.ts
- src/material/paginator/paginator.ts
- src/material/progress-bar/progress-bar.ts
- src/material/progress-spinner/progress-spinner.ts
- src/material/radio/radio.ts
- src/material/slide-toggle/slide-toggle-config.ts
- src/material/slide-toggle/slide-toggle.ts
- src/material/slider/slider.ts
- src/material/stepper/step-header.ts
- src/material/stepper/stepper.ts
- src/material/tabs/tab-group.ts
- src/material/tabs/tab-nav-bar/tab-nav-bar.ts
- src/material/toolbar/toolbar.ts
> docs: Update references to M2 theming guide color variants section and add link to styling tab for color input descriptions

- CHANGELOG.md
> docs: release notes for the v19.0.5 release

- CHANGELOG.md
- package.json
Also this PR cherry-picks the changelog for v19.1.0-rc.0 into the main branch so that the changelog is up to date.
> Update next branch to reflect new release-train "v19.2.0-next.0".

- src/material-luxon-adapter/adapter/luxon-date-adapter.spec.ts
- src/material-luxon-adapter/adapter/luxon-date-adapter.ts
Fixes that the Luxon date adapter was hardcoding the first day of the week to Sunday, unless it's provided through DI.
Fixes #30278.
> fix(material-luxon-adapter): infer first day of week from locale

- src/material/menu/menu-trigger.ts
- src/material/menu/menu.spec.ts
Fixes a regression after #30148 where we no longer detached the lazy content panel, causing its items to be retained until the next open when they get destroyed and re-created.
> fix(material/menu): lazy content not detached after animation

- src/material/tooltip/tooltip-animations.ts
- tools/public_api_guard/material/tooltip.md
The `matTooltipAnimations` haven't been used for a while. These changes deprecate it so we can remove it completely later.
> fix(material/tooltip): deprecate matTooltipAnimations

- src/material/tabs/tab-nav-bar/tab-nav-bar.ts
- tools/public_api_guard/material/tabs.md
Fixes a regression introduced in #30121. It looks like we were depending on the incorrect internal state to animate correctly.
These changes fix the issue by removing a call that was redundant in the first place.
Fixes #30303.
> fix(material/tabs): tab nav bar animation not working when navigating forwards

- src/material/select/select.scss
this commit ensures select with disabled placeholder matches the color with label
fixes #29807
> fix(material/select): match disabled placeholder color with label

- src/material/tabs/tab-body.html
- src/material/tabs/tab-body.scss
- src/material/tabs/tab-body.spec.ts
- src/material/tabs/tab-body.ts
- src/material/tabs/tab-group.html
- src/material/tabs/tab-group.spec.ts
- src/material/tabs/tab-group.ts
- src/material/tabs/tab.ts
- src/material/tabs/tabs-animations.ts
- tools/public_api_guard/material/tabs.md
Reworks the tabs so they don't depend on the animations module anymore. This is both simpler and avoids some of the pitfalls of the animations module.
> fix(material/tabs): switch away from animations module

- src/material/slider/slider.spec.ts
* This is just some prep work for a set of incoming changes to the slider tick marks
> test(material/slider): Ensure tick marks are rendered correctly

- src/dev-app/timepicker/timepicker-demo.html
- src/material/timepicker/timepicker-toggle.html
- src/material/timepicker/timepicker-toggle.ts
- tools/public_api_guard/material/timepicker.md
Updates Angular Component Timepicker so the timepicker toggle has a default aria-label value if no aria-label is applied for the timepicker toggle button to make it more accessible.  Also adds additional option of applying aria-labelledby to Timepicker toggle button.
[Before screencast](https://screencast.googleplex.com/cast/NjQxMDM4NjI4OTk4MzQ4OHxmYTQyYzVjNC02Zg)
[After screencast](https://screencast.googleplex.com/cast/NTI5MTA0NTgzODM4OTI0OHw3NmY4MjQ3Ny02Zg)
Fixes b/380308482
> fix(material/timepicker): adds default aria-label to timepicker toggle

- src/material/timepicker/timepicker.spec.ts
Updates Timepicker.spec.ts to match recent changes to Timepicker toggle having
a default aria-label.
> test(material/timepicker): update timepicker tests to match timepicker toggle changes

- src/cdk/stepper/stepper.ts
- src/material/stepper/stepper-animations.ts
- src/material/stepper/stepper.html
- src/material/stepper/stepper.scss
- src/material/stepper/stepper.spec.ts
- src/material/stepper/stepper.ts
- tools/public_api_guard/cdk/stepper.md
- tools/public_api_guard/material/stepper.md
Reworks the stepper so it uses CSS directly to animate, instead of going through the animations module. This both simplifies the setup and allows us to avoid the issues that come with the animations module.
> fix(material/stepper): switch away from animations module

- src/material/checkbox/checkbox.scss
The specificity for the checkbox's focus indicator was very low which means that if the ripple styles are loaded later, it can be overwritten.
Fixes #30326.
> fix(material/checkbox): ensure focus indicator has the correct shape

- CHANGELOG.md
> docs: release notes for the v19.1.0 release

- src/material/expansion/expansion-panel-header.scss
Fixes that the focus indicator had a different shape from the header.
Fixes #30350.
> fix(material/expansion): inherit shape for focus indicator

- src/material/form-field/_form-field-subscript.scss
- src/material/form-field/_mdc-text-field-structure.scss
- src/material/form-field/form-field-animations.ts
- src/material/form-field/form-field.html
- src/material/form-field/form-field.scss
- src/material/form-field/form-field.ts
- src/material/input/input.spec.ts
- src/material/select/select.scss
- tools/public_api_guard/material/form-field.md
Switches the form field to use CSS for the subscript animations, instead of going through the animations module.
> fix(material/form-field): remove dependency on animations module

- src/material/datepicker/datepicker-animations.ts
- src/material/datepicker/datepicker-base.ts
- src/material/datepicker/datepicker-content.html
- src/material/datepicker/datepicker-content.scss
- src/material/datepicker/datepicker.spec.ts
- tools/public_api_guard/material/datepicker.md
Reworks the datepicker so it no longer depends on the animations module.
> fix(material/datepicker): switch away from animations module

- CHANGELOG.md
> docs: release notes for the v19.1.1 release

- material.angular.io/tools/lighthouse-audit.mjs
- package.json
- scripts/docs-deploy/clone-docs-repo.mts
- scripts/docs-deploy/docs-deps-install.mts
- yarn.lock
This fixes a few issues:
- uses the monorepo checked-in docs sources for deployment of >=v19
- properly installs dependencies for that repository, avoiding mismatches with the checked-in yarn of the monorepo root.
- avoids sandbox when launching puppeteer for audits
> build: initial attempt to fix docs site deployment

- src/material/button-toggle/button-toggle.scss
Fixes that the first/last buttons in a vertical button group had the wrong shape.
Fixes #30368.
> fix(material/button-toggle): incorrect shape of focus indicator in vertical group

- .ng-dev/commit-message.mts
since [material.angular.io](https://material.angular.io/) is now part of this repository we should probably add a scope for it unless we still want to refer changes in that folder under `docs` scope then we can close this
> ci: add `material-angular-io` to commit scopes

- src/google-maps/map-info-window/map-info-window.ts
Fixes that the info window would become visible when it is opened with explicit content.
Fixes #30298.
> fix(google-maps): hide info window node when opened with content

- src/material/snack-bar/snack-bar-animations.ts
- src/material/snack-bar/snack-bar-container.scss
- src/material/snack-bar/snack-bar-container.ts
- src/material/snack-bar/snack-bar.spec.ts
- src/material/snack-bar/snack-bar.ts
- tools/public_api_guard/material/snack-bar.md
Reworks the snack bar so it animates using CSS instead of the animations module.
> fix(material/snack-bar): switch away from animations module

- src/material/core/option/option.scss
Fixes a bug in the Angular Material `select` component where the selected options in a  `select` with the multiple attribute have the wrong text color. This is because the the text color styling for the `select` without the multiple attribute is applied.
fixes #30366
> fix(material/select): fixed text color for selected options in multiple select

- src/material/button/button.md
Updates Buttons with icons documentation to recommend that any icon button be a minimum of 48x48 to be fully accessible and easily clickable on smaller screens.
> docs: updates buttons with icons a11y recommendations

- src/material/timepicker/timepicker.html
- src/material/timepicker/timepicker.scss
- src/material/timepicker/timepicker.ts
- tools/public_api_guard/material/timepicker.md
Reworks the timepicker to move it away from the animations module for the dropdown animation.
> fix(material/timepicker): switch away from animations module

- src/cdk/a11y/key-manager/noop-tree-key-manager.ts
- tools/public_api_guard/cdk/a11y.md
add `Provider` type to `NOOP_TREE_KEY_MANAGER_FACTORY_PROVIDER` as the inferred type throws error when running dev-app locally
> refactor(cdk/a11y): explicitly add `Provider` type

- src/cdk/drag-drop/drag-drop-registry.ts
- src/cdk/platform/features/backwards-compatibility.ts
- tools/public_api_guard/cdk/platform.md
Fixes that we were importing a symbol only available in Angular 19.1, even though our peer dependencies allow 19.0.x.
Fixes #30388.
> fix(cdk/platform): preserve compatibility with angular versions less than 19.1

- src/material/bottom-sheet/bottom-sheet-animations.ts
- src/material/bottom-sheet/bottom-sheet-container.scss
- src/material/bottom-sheet/bottom-sheet-container.ts
- src/material/bottom-sheet/bottom-sheet-ref.ts
- src/material/bottom-sheet/testing/bottom-sheet-harness.ts
- tools/public_api_guard/material/bottom-sheet.md
Reworks the bottom sheet so it doesn't use the animations module to animate itself.
> fix(material/bottom-sheet): switch away from animations module

- src/material/select/select.spec.ts
- src/material/select/select.ts
Fixes a regression after #30363 where the select panel throws an error if `open` and `close` are called before Angular has had a chance to resolve the `panel`.
> fix(material/select): avoid error if panel is closed too quickly

- src/cdk/dialog/dialog-config.ts
- src/cdk/dialog/dialog.spec.ts
- src/material/bottom-sheet/bottom-sheet-config.ts
- src/material/bottom-sheet/bottom-sheet.spec.ts
- src/material/dialog/dialog-config.ts
- src/material/dialog/dialog.spec.ts
Having `aria-modal="true"` appears to hide other overlay-based components like `mat-select` from assistive technology. These changes set the default to `false` since the attribute is redundant anyway, because the dialog marks all outside content as `aria-hidden`.
> fix(cdk/dialog): default aria-modal to false

- src/cdk/text-field/autosize.ts
Fixes that our logic for measuring the `textarea` was being thrown off by user code that stretches it out.
> fix(cdk/text-field): auto sizing broken if user styles stretch the element

- CHANGELOG.md
> docs: release notes for the v19.1.2 release

- src/material/button-toggle/button-toggle.spec.ts
- src/material/button-toggle/button-toggle.ts
When button-toggle have init value as null, it's not get selected. This fix remove condition which stopping null button to select.
FYI:  there is no null check on the value of the radio buttons for selection. [Ref](https://github.com/angular/components/blob/d70fd6c2de45ea9999de0623f1a96a815dbfe5f3/src/material/radio/radio.ts#L202)
Fixes #25472
> fix(material/button-toggle): make null value selected on init

- src/material/sidenav/drawer.scss
Fixes a regression that happened when we switched the sidenav away from the animations module. The specificity of the selector that shows the sidenav was decreased which meant that the RTL styles were overriding it.
Fixes #30422.
> fix(material/sidenav): end positioned sidenav not opening in RTL

- guides/theming.md
previous links were getting redirect to new ones which may be a bit confusing, this commit updates them with new URL
> docs: update links for Shadow DOM & Constructable Stylesheets

- material.angular.io/src/app/shared/doc-viewer/doc-viewer-module.ts
- material.angular.io/src/app/shared/doc-viewer/doc-viewer.spec.ts
- material.angular.io/src/app/shared/doc-viewer/doc-viewer.ts
- material.angular.io/src/app/shared/doc-viewer/module-import-copy-button.ts
- material.angular.io/src/styles/_api.scss
- tools/dgeni/templates/entry-point.template.html
adds icon button next to module import text allowing users to copy
fixes #16127
> feat(material-angular-io): allow module imports to be copied from API tab

- material.angular.io/src/app/pages/component-viewer/token-table.html
fixes upon resetting the filters type filter value persists in component styling tab
> docs(material-angular-io): fix clearing filter doesnt reset type filter

- .vscode/settings.json
previously vscode used to warn about commit lines when they exceed certain characters but this was changed to be off by default, lets explicitly add this to vscode settings so it aligns with our contributing docment that no line should 100 characters
> docs: add commit input validation in vscode settings

- src/material/chips/chip-listbox.spec.ts
- src/material/chips/chip-listbox.ts
Fixes a bug in the Angular Material `chips` component where async chips with a delay were not highlighted correctly.
Fixes #27370
> fix(material/chips): Async chips with a delay are not highlighted

- src/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
- src/cdk/schematics/ng-generate/drag-drop/index.spec.ts
- src/material/schematics/ng-generate/address-form/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
- src/material/schematics/ng-generate/address-form/index.spec.ts
- src/material/schematics/ng-generate/dashboard/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
- src/material/schematics/ng-generate/dashboard/index.spec.ts
- src/material/schematics/ng-generate/navigation/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
- src/material/schematics/ng-generate/navigation/index.spec.ts
- src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
- src/material/schematics/ng-generate/table/index.spec.ts
- src/material/schematics/ng-generate/tree/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts.template
- src/material/schematics/ng-generate/tree/index.spec.ts
since v19 Angular components are standalone by default so we don't have to add `standalone` flag to be true explicitly in schematics
> refactor(material/schematics): drop standalone flag from schematics

- CHANGELOG.md
> docs: release notes for the v19.1.3 release

- src/material/schematics/ng-add/index.spec.ts
- src/material/schematics/ng-add/index.ts
- src/material/schematics/ng-add/schema.json
- src/material/schematics/ng-add/schema.ts
- src/material/schematics/ng-add/setup-project.ts
Since we no longer depend on the animations module, we can remove the prompt and its related code from the `ng add` schematic.
> fix(material/core): remove animations from ng add

- src/components-examples/material/table/table-expandable-rows/table-expandable-rows-example.css
- src/components-examples/material/table/table-expandable-rows/table-expandable-rows-example.html
- src/components-examples/material/table/table-expandable-rows/table-expandable-rows-example.ts
Uses a CSS transition for the expandable rows example, instead of relying on the animations module. This will allow us to remove the animations module from the docs site.
> docs(material/table): use CSS transition for animation

- src/cdk/table/sticky-styler.ts
The table has some logic that queues up measurements of rows that will become sticky so that they can be measured once we set up the resize observer. Afterwards the queue is cleared once the measurements are done. #29814 introduced a memory leak where the tracking was happening even if the row isn't actually sticky which meant that the resize observer was never set up and the queue kept growing as new rows are rendered.
These changes resolve the leak by only queuing the measurement if it's necessary.
I've also fixed another potential leak where we were setting up the resize observer, but we weren't destroying it.
Fixes #30453.
> fix(cdk/table): memory leak when no rows are sticky

- guides/getting-started.md
- guides/schematics.md
- src/material-experimental/package.json
- src/material/package.json
All Material components have been moved away from requiring the `@angular/animations` module. These changes update the docs and `peerDependencies` not to require it.
This means that users can remove the BrowserAnimationsModule from their apps, if they weren't using Angular's animations system in their own code or in other dependencies. This has a few advantages:
1. It removes ~16kb of minified JS from production bundle.
2. It resolves a bunch of bugs and memory leaks that were caused by the animations. E.g. previously if there was an expansion panel inside a tab, it would be open while the animations are running and then snap into place.
3. It reduces some runtime overhead for Angular.
4. It causes fewer change detections.
This change **does not** imply that the `@angular/animations` …
> feat(material/core): drop dependency on animations module

- src/material/select/select.ts
Fixes an issue that was reported internally where in some setups the select would animate away, but wouldn't be detached after the exit animation until the next change detection.
> fix(material/select): overlay not detached on time after exit animation in some cases

- src/cdk/package.json
Adds a `packageGroup` to the `package.json` of the CDK to avoid some warnings during `ng update`.
Fixes #30464.
> build: add packageGroup to CDK

- src/material/badge/badge.ts
- src/material/chips/chip.ts
- src/material/core/option/option.ts
- src/material/stepper/step-header.ts
inject() is pretty cheap, but not free.
> perf(multiple): Don't double-inject the style loader.

- src/material/dialog/testing/dialog-harness.ts
Fixed a typo in the JSDocs of `MatDialogHarness#getText` method.
> docs(dialog-harness): fix typo

- src/cdk/overlay/backdrop-ref.ts
- src/cdk/overlay/overlay-ref.ts
Prior to #30179 the overlay ref was able to handle multiple backdrops being removed at the same time, because we didn't need to retain any state about them, aside from the DOM node. After the switch to the renderer that's no longer the case, because we also retain the event cleanup functions. This is a problem, because they can end up overriding each other and causing events to be dropped incorrectly.
These changes move the backdrop-related logic to a new `BackdropRef` class to make the removal process easier to manage, clean up the `overlay-ref.ts` a bit and resolve the issue.
Fixes #30426.
> fix(cdk/overlay): avoid issues with overlapping backdrop removals

- src/material/timepicker/timepicker.ts
- tools/public_api_guard/material/timepicker.md
Adds an injection token to the timepicker that allows the scroll strategy to be customized, similar to other components.
Fixes #30421.
> fix(material/timepicker): allow scroll strategy to be customized

- CHANGELOG.md
> docs: release notes for the v19.1.4 release

- packages.bzl
- src/cdk-experimental/package.json
- src/cdk/package.json
- src/material-date-fns-adapter/package.json
- src/material-experimental/package.json
- src/material-luxon-adapter/package.json
- src/material-moment-adapter/package.json
- src/material/package.json
This commit fixes multiple `package.json` files by adding the missing `packageGroup` field. Additionally, it ensures that all required packages are included within `packageGroup`. These updates are necessary because the affected packages have peer dependencies on `@angular/cdk` or `@angular/material`, and updating them individually.
> build: add missing `packageGroup` fields and packages in `package.json`

- .github/workflows/pr.yml
The license check was in the API golden job which seems unintentional. These changes move it into the lint job.
> build: move license check to lint job

- src/material/radio/_radio-common.scss
- src/material/radio/radio.scss
Descendant selectors containing :state selectors as ancestors are slow as they require the css engine to check all the way up to the dom root for matching elements. Using child selectors instead limits the scope of these checks to just the direct parent element.
> perf(material/radio): Optimize costly css selectors.

- src/material/slide-toggle/slide-toggle.scss
Fixes a rendering issue that was causing the icon inside the slide toggle to flicker or not display at all.
Fixes #30487.
> fix(material/slide-toggle): rendering issue in Safari 18.3

- src/material/core/tokens/m2/mat/_snack-bar.scss
Fixes a bug in the Angular Material snack-bar, where accent color is used for action button color in light themes and grey is used in dark themes. This does not follow the material design guidelines which recommend a tone of primary color is used in both light and dark themes, and that the color should contrast with the background.
Fixes #13905
> fix(material/snack-bar): snack-bar action button does not follow material guidelines

- src/material/paginator/paginator.scss
#29379 changed the selector for disabled buttons from `[disabled]` to `[aria-disabled]`, however it didn't apply the same change to the high contrast styles which led to them being invisible in dark mode.
I've also improved the experience by styling the buttons as disabled in high contrast mode.
Fixes #30504.
> fix(material/paginator): disabled buttons not visible in high contrast mode

- src/cdk/accordion/accordion-item.spec.ts
- src/cdk/accordion/accordion.spec.ts
- src/material/chips/chip-grid.spec.ts
- src/material/dialog/dialog.spec.ts
- src/material/expansion/accordion.spec.ts
- src/material/input/input.spec.ts
- src/material/sidenav/drawer.spec.ts
- src/material/tabs/tab-group.spec.ts
- src/material/tabs/tab-nav-bar/tab-nav-bar.spec.ts
Removes the `BrowserAnimationsModule` from all of our unit tests.
> test(multiple): remove animations module from tests

- src/material/tooltip/tooltip.ts
#30440 deferred the injection of some dependencies in the tooltip, including `ViewContainerRef`. This is problematic, because the act of injecting `ViewContainerRef` changes the shape of some internal data structures in the framework's runtime. As a result, hovering over a tooltip that has been hydrated will throw a runtime error because the structure from the server no longer matches the structure on the client.
Fixes #30498.
> fix(material/tooltip): regression when injecting ViewContainerRef

- src/material/checkbox/_checkbox-common.scss
The `input` element inside the checkbox was stacked under some other elements which might prevent clicks. These changes ensure it's stacked on top.
Fixes #30494.
> fix(material/checkbox): ensure native control receives clicks

- src/dev-app/youtube-player/BUILD.bazel
- src/dev-app/youtube-player/youtube-player-demo.html
- src/dev-app/youtube-player/youtube-player-demo.ts
- src/youtube-player/BUILD.bazel
- src/youtube-player/youtube-player-placeholder.scss
- src/youtube-player/youtube-player.scss
- src/youtube-player/youtube-player.ts
- tools/public_api_guard/youtube-player/youtube-player.md
Adds a method on the `YouTubePlayer` to put the element in fullscreen mode. This is a bit more involved than just calling `requestFullScreen`, because we also need to change the styles to ensure that the placeholder and the `iframe` cover the whole screen.
Fixes #30485.
> feat(youtube-player): add API to put the player in fullscreen mode

- src/cdk/drag-drop/directives/drop-list.ts
We have some logic that registers and de-registers the items on create/destroy. That logic only syncs the item with the internal `DragRef` once the next dragging starts which means that we might retain a destroyed item if another drag doesn't start.
These changes switch to always syncing the list when an item is removed.
I've also added some context around why things are set up as they are right now since it took a while to remember the reasoning.
Fixes #30506.
> fix(cdk/drag-drop): avoid retaining destroyed items until next drag

- CHANGELOG.md
> docs: release notes for the v19.1.5 release

- CHANGELOG.md
- package.json
Also this PR cherry-picks the changelog for v19.2.0-rc.0 into the main branch so that the changelog is up to date.
> Update next branch to reflect new release-train "v19.3.0-next.0".

- src/cdk/stepper/stepper.ts
- src/material/stepper/stepper.spec.ts
Set all the previous steps as interacted if it's linear step and is not the first step.
Fixes #15449
> fix(cdk/stepper): Linear stepper after initialization navigating to previous step issue

- src/material/radio/radio.ts
- tools/public_api_guard/material/radio.md
This event should be typed. Added type and fallback to any to make this optional and backwards compatible.
> Optional typing of MatRadioChange

- src/material/select/select.ts
- tools/public_api_guard/material/select.md
This event should be typed. Added type and fallback to any to make this optional and backwards compatible.
> Optional typing of MatSelectChange

- src/material/form-field/form-field.ts
- src/material/input/input.spec.ts
fixes the issue we were not marking component for changes when form is reassigned making it not update UI for required asterisk
fixes #29066
> fix(material/form-field): trigger CD when form gets reassigned

- src/material/button/button-base.ts
- src/material/button/button.ts
- src/material/button/fab.ts
- src/material/button/icon-button.ts
- src/material/button/module.ts
- src/material/datepicker/datepicker-toggle.html
- src/material/timepicker/timepicker-toggle.html
- tools/public_api_guard/material/button.md
Currently we have two directives for each button variant: `MatButton` which applies to `button` elements and `MatButtonAnchor` which applies to anchors.
This is problematic in a couple of ways:
1. The styles, which can be non-trivial, are duplicated if both classes are used.
2. Users have to think about which class they're importing.
These changes combine the two classes to resolve the issues and simplify our setup.
`tabindex` values set as `[attr.tabindex]` set on a Material button might not work as expected. Use `tabindex` for static values, or `[tabindex]`/`[tabIndex]` for dynamic ones.
> fix(material/button): combine MatButton and MatAnchor

- src/material/chips/chip.scss
doesn't apply forced color to disabled chips to distingiush from active chips
BEFORE: https://screenshot.googleplex.com/3hAWxwjoxEntW5V
AFTER: https://screenshot.googleplex.com/6wkdMVSXsEmYpPY
fixes b/383354169
> fix(material/chips): forced colors disabled chip fix

- src/cdk/drag-drop/directives/config.ts
- src/cdk/drag-drop/directives/drag.ts
- src/cdk/drag-drop/drag-ref.ts
- src/cdk/drag-drop/public-api.ts
- tools/public_api_guard/cdk/drag-drop.md
Fixes type DragConstrainPosition, which of сorrect configuration of CdkDrag  is not possible when using in providers
Fixes #30509
> fix(cdk/drag-drop): incorrect type DragConstrainPosition

- src/material/datepicker/date-range-input-parts.ts
- tools/public_api_guard/material/datepicker.md
Fixes that there was a hidden "changed after checked" error in the range picker when the secondary value was being assinged without notifying Angular.
Fixes #30526.
> fix(material/datepicker): changed after checked error when assigning end value

- src/material/list/selection-list.spec.ts
- src/material/list/selection-list.ts
Fixes that we weren't change detecting the view of the selection list options when the form control for the entire list is disabled. The visual difference is subtle for unchecked options, but it's noticeable for checked ones.
Fixes #30522.
> fix(material/list): option views not change detected when control is disabled

- src/material/core/animation/animation.ts
- tools/public_api_guard/material/core.md
The `AnimationCurves` and `AnimationDurations` were exposed from `material/core`, because some Material components were using them to define JavaScript-based animations. That's no longer the case so they can be removed.
> fix(material/core): deprecate AnimationCurves and AnimationDurations

- src/material/button/button-high-contrast.scss
- src/material/button/button.scss
Fixes that the focus overlay on outlined buttons wasn't covering the outlined button fully when its border radius is customized.
Fixes #30484.
> fix(material/button): incorrect outlined focus overlay shape when border radius is customized

- CHANGELOG.md
> docs: release notes for the v19.2.0 release

- CHANGELOG.md
> docs: release notes for the v19.2.1 release

- src/material/bottom-sheet/bottom-sheet-config.ts
- src/material/bottom-sheet/bottom-sheet-container.ts
- src/material/bottom-sheet/bottom-sheet.spec.ts
- tools/public_api_guard/material/bottom-sheet.md
Switches the bottom sheet to focusing the first tabbale element by default like we do in `MatDialog`.
Note that we had a comment saying that the previous behavior was intentional. That seems to be a leftover from #14534 where the underlying cause was that we were delaying focus until the animation is done. We now have better ways of handling it so the comment isn't relevant anymore.
Fixes #30483.
> fix(material/bottom-sheet): focus first tabbable element by default

- src/material/timepicker/BUILD.bazel
- src/material/timepicker/timepicker.spec.ts
- src/material/timepicker/timepicker.ts
The timepicker wasn't updating its internal state when it gets closed through the overlay which meant that the user can't reopen it.
Fixes #30558.
> fix(material/timepicker): unable to reopen if closed by scroll strategy

- material.angular.io/src/app/pages/component-sidenav/component-nav.html
- material.angular.io/src/app/pages/component-sidenav/component-sidenav.html
- material.angular.io/src/app/pages/component-sidenav/component-sidenav.ts
Fixes that the links in the docs sidenav weren't updating on navigation and avoids passing route parameters around.
> fix(material-angular-io): sidenav links not updating

- src/cdk/schematics/ng-generate/drag-drop/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template
- src/material/schematics/ng-generate/address-form/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template
- src/material/schematics/ng-generate/dashboard/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template
- src/material/schematics/ng-generate/navigation/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template
- src/material/schematics/ng-generate/table/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template
- src/material/schematics/ng-generate/tree/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template
Removes the `NoopAnimationsModule` from the tests generated by `ng generate` since it requires the animations module to be installed.
Fixes #30560.
> fix(material/schematics): remove NoopAnimationsModule from generated tests

- src/cdk/dialog/dialog-config.ts
- src/cdk/overlay/overlay.ts
- src/cdk/portal/dom-portal-outlet.ts
- src/cdk/portal/portal.spec.ts
- src/cdk/portal/portal.ts
- src/material/dialog/dialog-config.ts
- src/material/menu/menu-content.ts
- tools/public_api_guard/cdk/dialog.md
- tools/public_api_guard/cdk/portal.md
- tools/public_api_guard/material/dialog.md
Removes the remaining APIs that were referencing `ComponentFactoryResolver`. These were all placeholders since we removed the code that was passing the values along a couple major versions ago.
* `DialogConfig.componentFactoryResolver` has been removed.
* The constructor of `DomPortalOutlet` has changed.
* `ComponentPortal.componentFactoryResolver` has been removed.
* The constructor signature of `ComponentPortal` has changed.
* `MatDialogConfig.componentFactoryResolver` has been removed.
> fix(multiple): remove remaining references to ComponentFactoryResolver

- src/cdk/stepper/stepper.ts
- src/material/stepper/stepper.spec.ts
Fixes that the stepper was marking an item as interacted and emitting an event whenever the `selectedIndex` is assigned, even if it's the same.
Fixes #30540.
> fix(cdk/stepper): emitting interacted event when item has not changed

- src/material/chips/chip-listbox.ts
- src/material/chips/chip-row.ts
- src/material/list/list-option.ts
- src/material/sort/sort-header.ts
- tools/public_api_guard/material/list.md
Resolves the following issues with host bindings that weren't caught due to a lack of type checking:
* The `aria-describedby` binding on `mat-chip-listbox` was doing nothing, because the `_ariaDescribedBy` property does not exist.
* The `focus` handler on `mat-chip-row` was passing an event to `_handleFocus` even though one isn't required.
* `MatListOption` was referencing a private method.
* `mat-sort-header` was setting an invalid value to the `_recentlyCleared` signal.
> fix(multiple): resolve host binding issues

- CHANGELOG.md
> docs: release notes for the v19.2.2 release

- src/material/timepicker/timepicker.ts
#30561 accidentally switched the default scroll strategy for the timepicker to be `close` instead of `reposition`. It was unintentional so these changes switch it back to `reposition`.
> fix(material/timepicker): wrong default scroll strategy

- WORKSPACE
- package.json
- tools/postinstall/patches/@angular+bazel+20.0.0-next.1.patch
- yarn.lock
See: https://github.com/angular/angular/commit/1f1039475c573d7b87b0f9a2e01619736b17bbf5
> build: update `@angular/bazel` for relative imports in `ng_package`

- src/material/schematics/ng-generate/theme-color/schema.json
Fixes that the `neutralVariantColor` and `errorColor` were missing from the schema which meant that users can't pass them in.
Fixes #30571.
> fix(material/schematics): some options missing from schema

- src/cdk/portal/dom-portal-outlet.ts
- src/cdk/portal/portal.spec.ts
This commit fixes a regression that was introduced in #27427, where the injector hierarchy
did not respect nested environment injectors. `DomPortalOutlet` was always using the application
root as environment injector, yet the element injector may have a custom child environment injector
as ancestor. This child environment injector has to be retrieved manually and passed as environment
injector of the portal component.
Fixes #30609
> fix(cdk/portal): fix incorrect injector hierarchy with DomPortalOutlet and child environment injectors

- src/material/autocomplete/autocomplete-trigger.ts
There are a few places where the autocomplete was checking if it has focus which were breaking down when inside the shadow DOM, because `document.activeElement` will point to the closest shadow root.
These changes consolidate the places where we check for focus and use our utility for resolving the focused element through shadow boundaries.
Fixes #30611.
> fix(material/autocomplete): incorrectly resolving focused element in shadow DOM

- src/material/button/button-base.ts
- src/material/paginator/paginator.html
- src/material/paginator/paginator.spec.ts
Previous and next buttons should not be in the tab order if they are disabled
Fixes b/395610398
> fix(material/paginator): prevent keyboard nav to disabled buttons

- src/material/button/button-base.ts
- src/material/button/button.ts
- src/material/button/fab.ts
- src/material/button/icon-button.ts
- tslint.json
Following up on https://github.com/angular/components/pull/30626#discussion_r1994327339, these changes move the button's shared host bindings into the base class and turn some classes that are added manually into host bindings.
The previous approach was only necessary with ViewEngine, because it wasn't doing inheritance of host bindings correctly and wasn't merging classes. These are no longer issues in Ivy.
Finally, these changes allow us to take advantage of an upcoming framework feature: https://github.com/angular/angular/pull/60267
> refactor(material/button): simplify host bindings

- src/material/select/select.html
When the browser window is small, the select's listbox panel does not shrink in size, which causes options to become unreachable.
With flexible positioning, the overlay is constrained in height causing the panel to shrink as well, rendering all available options with scrolling
Before:
After:
Before: 
After:
> fix(material/select): use flexible overlay dimensions

- src/material/select/select.html
- src/material/select/select.spec.ts
Enable detection of the detach output event on the panel of the mat-select component. This ensures that when CloseScrollStrategy is set via MAT_SELECT_SCROLL_STRATEGY, the panel correctly closes on scroll, updating the panelOpen property to false.
Fixes #30620
> fix(material/select): close panel on detach output event

- src/material/autocomplete/autocomplete.md
Remove `instead` word from autocomplete doc to fix grammatical mistake.
> docs: fix typo in autocomplete by removing redundant word

- src/cdk/text-field/autosize.ts
When we have a long multiline textfield and put the cursor on almost an end (For example, on 3rd last line), the scroll moves up to the top of textarea. This fix will cache the `scrollTop` in the`resizeToFitContent` method
Fixes #20255
> fix(cdk/text-field): Long multiline textfield  focus issue

- CHANGELOG.md
> docs: release notes for the v19.2.4 release

- src/material/timepicker/timepicker-input.ts
- src/material/timepicker/timepicker.spec.ts
Fixes an issue where the value of the input element referenced by a TimepickerInput component inside a shadow DOM was getting formatted too often due to `TimepickerInput._hasFocus()` assuming the component wasn't in the shadow DOM.
Fixes #30641
> fix(material/timepicker): TimepickerInput component in shadow DOM

- src/cdk/tree/tree.ts
fixes component retaining old data in memory even when its not used causing memory usage to increase
fixes #30322
> fix(cdk/tree): retainining previous objects

- src/material/chips/chip-set.scss
The chip input is inheriting some styles from `MatInput` which were causing it not to show its placeholder unless it's focused.
These changes override the inherited styles to show it correctly.
Fixes #16380.
> fix(material/chips): chip input not showing placeholder

- goldens/material/chips/index.api.md
- src/dev-app/chips/BUILD.bazel
- src/dev-app/chips/chips-demo.html
- src/dev-app/chips/chips-demo.ts
- src/material/chips/chip-input.spec.ts
- src/material/chips/chip-input.ts
- src/material/chips/testing/BUILD.bazel
- src/material/chips/testing/chip-input-harness.spec.ts
- src/material/chips/testing/chip-input-harness.ts
- src/material/chips/tokens.ts
Adds a `disabledInteractive` input to `MatChipInput`, similar to what we have in other components.
I've also cleaned up the chips demo a bit.
> fix(material/chips): implement disabledInteractive in chip input

- integration/module-tests/BUILD.bazel
- integration/module-tests/find-all-modules.mts
- integration/module-tests/index.bzl
- integration/module-tests/index.mts
- integration/module-tests/tsconfig.json
- src/cdk/dialog/dialog-module.ts
- src/cdk/drag-drop/drag-drop-module.ts
- src/cdk/overlay/overlay-module.ts
- src/cdk/scrolling/scrolling-module.ts
As of recently, we switched our imports from module imports to relative imports, when inside the same package. This is expected for proper code splitting, and also for our upcoming `rules_js` migration.
Unfortunately this highlights an issue with the Angular compiler. We occasionally re-export other entry-point modules from one entry-point module. This is likely done for convenience, but we should stop doing that going forward (and likely will naturally resolve this over time with standalone either way).
The problem is that the Angular compiler, especially with HMR enabled (i.e. no tree-shaking of imports), will try to generate imports in the user code to symbols that are indirectly re-exported. This worked before because the Angular compiler leveraged the "best guessed module", based on …
> fix(multiple): ensure re-exported module symbols can be imported

- integration/module-tests/BUILD.bazel
- integration/module-tests/index.bzl
- integration/module-tests/index.mts
- src/cdk/overlay/overlay-module.ts
This is a follow-up to cb3b0a87a7528aa2f3525f951a021398821df970 which did miss this transitive re-export of the `Dir` directive. The compiler will try the last module import, so even if e.g. `./scrolling` re-exported `Dir` as of the initial commit, the compiler would try importing via `@angular/cdk/overlay`.
This commit fixes this remaining instance, and updates the new testing infrastructure to import/test every module in isolation. The tests didn't notice that issue because the compiler discovered the `Dir` directive/"Reference" already via another import that "worked".
Fixes #30663.
> fix(cdk/overlay): ensure re-exported transitive `Dir` directive can be imported

- CHANGELOG.md
> docs: release notes for the v19.2.6 release

- src/material/core/tokens/_density.scss
Fixes that the `touch-target-display` token wasn't being set properly for the tonal button in M3.
> fix(material/button): tonal touch target token transgression

- .aspect/rules/external_repository_action_cache/npm_translate_lock_MzA5NzUwNzMx
- package.json
- pnpm-lock.yaml
This version of `angular-linking` has the new license (MIT), and also disables Babel config lookups. That potentially fixes the flakiness where Babel fails reading some incomplete config file
> build: update `angular-linking` to attempt fix postinstall flakiness

- src/material/sort/sort-header.scss
Sets the `cursor` on the entire sort header, rather than the inner container, since the whole element is clickable.
Fixes #30690.
> fix(material/sort): set cursor on entire clickable area

- CHANGELOG.md
> docs: release notes for the v19.2.7 release

- .bazelrc
- .github/workflows/assistant-to-the-branch-manager.yml
- .github/workflows/ci.material-aio.yml
- .github/workflows/ci.yml
- .github/workflows/deploy-dev-app-main-push.yml
- .github/workflows/dev-infra.yml
- .github/workflows/google-internal-tests.yml
- .github/workflows/pr.material-aio.yml
- .github/workflows/pr.yml
- .github/workflows/preview-build-dev-app.yml
- .github/workflows/preview-deploy-dev-app.yml
- .github/workflows/scheduled-ci.yml
Update to use the latest bazel/configure-remote action from dev-infra and set up trusted builds for CI runs from upstream branches.
> ci: update bazel RBE setup on CI and use trusted build configuration for upstream CI runs

- goldens/material/form-field/index.api.md
- goldens/material/input/index.api.md
- goldens/material/select/index.api.md
- src/material/chips/chip-grid.spec.ts
- src/material/form-field/directives/error.ts
- src/material/form-field/form-field.html
- src/material/form-field/form-field.ts
- src/material/input/input.spec.ts
This is a slight change in behavior where the aria-live is always set to polite even if the user puts a different aria-live value on the error. Based on internal usage, this is very rare (and not part of the documented API)
Fixes https://github.com/angular/components/issues/29616
Revised version of https://github.com/angular/components/pull/30155 which uses a single aria-live wrapper container div for both error and hints (changing the class appropriately). This prevents issues with existing usage caused by introducing a new wrapper div.
> fix(material/form-field): move error aria-live to parent container

- material.angular.io/src/app/shared/documentation-items/documentation-items.ts
- material.angular.io/src/app/shared/guide-items/guide-items.ts
We recently updated some of the filenames to avoid collisions. This commit fixes the rendering in the doc site. We already did this initially with the overviews; but guides apparently are handled separately.
We should explore why no tests fail here.
> docs: fix incorrect guide links after recent collision change

- goldens/material/core/index.api.md
- src/dev-app/main.ts
- src/material/core/animation/animation.ts
Even though Material is currently decoupled from the animations module, users still need to import the `NoopAnimationsModule` to disable them.
These changes introduce a custom token so that users don't have to depend on the animations-related packages at all.
> feat(material/core): introduce custom token for controlling animations

- material.angular.io/scenes/src/app/scenes/snack-bar/snack-bar-scene.scss
- src/material/core/tokens/_density.scss
- src/material/core/tokens/m2/mdc/_snack-bar.scss
- src/material/core/tokens/m3/mdc/_snack-bar.scss
- Some CSS variables are renamed from "--mat-snackbar-" to "--mat-snack-bar", aligning with the rest of snack bar tokens
> fix(material/snack-bar): rename snackbar token prefix

- src/cdk/drag-drop/directives/drop-list.ts
#30514 changed the logic that syncs destroyed items to apply to non-dragged items as well. This led to a performance regression where swapping out a large list of items can lock up the entire browser. The problem is that the items need to be re-sorted each time an item is destroyed which is expensive.
These changes resolve the issue by keeping track of the last set of items and dropping the item from it without re-sorting.
Fixes #30737.
> perf(cdk/drag-drop): fix performance regression when destroying items

- src/cdk-experimental/listbox/listbox.ts
- src/cdk-experimental/ui-patterns/behaviors/list-focus/list-focus.ts
- src/cdk-experimental/ui-patterns/behaviors/list-selection/list-selection.spec.ts
- src/cdk-experimental/ui-patterns/behaviors/list-selection/list-selection.ts
- src/cdk-experimental/ui-patterns/listbox/listbox.ts
- src/cdk-experimental/ui-patterns/listbox/option.ts
- src/components-examples/cdk-experimental/listbox/cdk-listbox/cdk-listbox-example.html
* Switch to using values instead of ids for tracking selected items in a list
> refactor(cdk-experimental/ui-patterns): track list selection by value

- goldens/material/tabs/index.api.md
- src/material/tabs/tab-group.html
- src/material/tabs/tab-group.spec.ts
- src/material/tabs/tab-group.ts
- src/material/tabs/tab.ts
Fixes a long-standing issue where users weren't able to assign an ID to a tab.
Fixes #4136.
> fix(material/tabs): allow ID to be set on tab

- src/material/autocomplete/autocomplete-trigger.ts
- src/material/autocomplete/autocomplete.spec.ts
- src/material/autocomplete/autocomplete.ts
If a mat-autocomplete element does not contain any mat-options it will throw a null pointer when it is unloaded. Adding a simple null check solves this.
Googlers see cl/741219851
> Add a null check to autocomplete options

- CHANGELOG.md
> docs: release notes for the v19.2.8 release

- tools/extract-tokens/extract-tokens.ts
Log accidentally committed in PR #30765
> refactor: remove extraneous log

- goldens/material/core/index.api.md
- src/material/core/animation/BUILD.bazel
- src/material/core/animation/animation.ts
Adds some logic so that animations automatically get disabled if the `prefers-reduced-motion` media query matches.
> feat(material/core): handle prefers-reduced-motion automatically

- src/components-examples/material/chips/chips-form-control/chips-form-control-example.html
Fixes the aria-label binding of the remove keyword button in chips-form-control-example html. The aria-label used string concatenation with an attribute instead of a property binding.
> docs(material/chips-form-control): fix aria-label binding of chips-form-control-example

- src/components-examples/material/chips/chips-reactive-form/chips-reactive-form-example.html
- src/components-examples/material/chips/chips-template-form/chips-template-form-example.html
Fixes the aria-label binding of the remove keyword button in chips reative and template driven form. The aria-label used string concatenation with an attribute instead of a property binding.
> docs(material/chips): fix aria label binding for reactive and template driven form

- goldens/cdk/table/index.api.md
- src/cdk/table/BUILD.bazel
- src/cdk/table/table.spec.ts
- src/cdk/table/table.ts
Fixes that the table was throwing an error if `renderRows` is called before the data has been loaded for the first time.
Fixes #30795.
> fix(cdk/table): error if data is accessed too early

- WORKSPACE
- scripts/create-legacy-tests-bundle.mjs
- src/BUILD.bazel
- src/cdk/a11y/key-manager/list-key-manager.spec.ts
- src/cdk/testing/tests/webdriver-test.bzl
- src/cdk/testing/tests/webdriver.e2e.spec.ts
- test/BUILD.bazel
- test/angular-test.init.ts
- test/karma.conf.js
- tools/defaults.bzl
- tools/defaults2.bzl
> [19.2.x]: build: switch karma tests to `rules_browsers`

- CHANGELOG.md
> docs: release notes for the v19.2.9 release

- .aspect/rules/external_repository_action_cache/npm_translate_lock_MzA5NzUwNzMx
- package.json
- pkg-externals.bzl
- pnpm-lock.yaml
- src/youtube-player/BUILD.bazel
- src/youtube-player/package.json
- src/youtube-player/youtube-player.ts
- yarn.lock
Use Google's `safevalues` package to avoid casting to `any` for the url in the youtube player
> fix(youtube-player): use safevalues

- src/material/core/tokens/_m3-system.scss
This ensures component styles have a system fallback for density values
> fix(material/core): include density tokens in system theme

- goldens/cdk/dialog/index.api.md
- goldens/material/bottom-sheet/index.api.md
- src/cdk/dialog/dialog-container.ts
- src/material/bottom-sheet/bottom-sheet-container.ts
The bottom sheet has an animation where it starts off-screen and animates in. At the same time it moves focus into itself. It seems like under certain conditions (e.g. having `backdrop-filter` on the `body`) this causes the entire page the jump in a jarring way due to the focus being moved.
These changes resolve the issue by telling the browser not to scroll the page when moving focus.
Fixes #30774.
> fix(material/bottom-sheet): page jumping if backdrop-filter is applied

- WORKSPACE
Updates dev-infra to a version that includes the `http_server` runfile fix.
> build: update dev-infra to version with `http_server` fix

- src/cdk/overlay/_index.scss
Disables the CDK's backdrop transition if the `prefers-reduced-motion` media query is enabled.
> fix(cdk/overlay): disable overlay animation with prefers-reduced-motion

- src/universal-app/kitchen-sink/kitchen-sink.html
- src/universal-app/kitchen-sink/kitchen-sink.ts
Adds the timepicker to the SSR test app so we can verify that it'll work.
> test(material/timepicker): add timepicker to SSR test app

- .github/workflows/ci.material-aio.yml
- .github/workflows/pr.material-aio.yml
- WORKSPACE
We can/should always run these tests. Bazel will use cached results if there are no changes.
> build: always run material CI checks

- goldens/material/chips/index.api.md
- goldens/material/datepicker/index.api.md
- goldens/material/form-field/index.api.md
- goldens/material/input/index.api.md
- goldens/material/select/index.api.md
- src/material/chips/chip-grid.ts
- src/material/chips/chip-input.spec.ts
- src/material/chips/chip-input.ts
- src/material/chips/chip-text-control.ts
- src/material/datepicker/date-range-input.spec.ts
- src/material/datepicker/date-range-input.ts
- src/material/form-field/form-field-control.ts
- src/material/form-field/form-field.ts
- src/material/input/input.ts
- src/material/select/select.spec.ts
- src/material/select/select.ts
Expand fix for Input to properly handle aria-describedby set manually (e.g. by AriaDescriber) to all form fields when syncing described by ids.
> fix(material/form-field): preserve aria-describedby set externally across all form controls

- docs/BUILD.bazel
Looks like due to some rebasing, the incorrect target was used, so that the token assets wasn't available.
> build: fix docs site styling token loading

- CHANGELOG.md
> docs: release notes for the v19.2.10 release

- src/material/paginator/paginator.spec.ts
- src/material/select/select.spec.ts
- src/material/select/select.ts
Remove the select value's element ID from the combobox's list of `aria-labelledby`
Closes #24899
> fix(material/select): remove value from aria-labelledby

- src/cdk/a11y/focus-trap/focus-trap.spec.ts
- src/cdk/overlay/overlay.spec.ts
- src/cdk/scrolling/virtual-scroll-viewport.spec.ts
- src/material/bottom-sheet/bottom-sheet.spec.ts
- src/material/chips/chip-grid.spec.ts
- src/material/datepicker/datepicker.spec.ts
- src/material/dialog/testing/dialog-opener.spec.ts
- src/material/menu/menu.spec.ts
- src/material/tabs/tab-group.spec.ts
- src/material/toolbar/toolbar.spec.ts
- src/material/tooltip/tooltip.spec.ts
We have some really old tests that were depending on `fixture.whenStable` even though they don't need to. These changes clean them up.
> test(multiple): rework whenStable usages

- src/cdk/dialog/dialog.ts
https://github.com/angular/components/pull/30702 added a `valueSignal` property to `Directionality`, this PR adds it to the directionality provided by cdk-dialog as well.
> fix(cdk/dialog): provide proper shaped Directionality

- src/material/list/list.md
update list a11y documentation
fixes b/247892626
> fix(material/list): update A11y documentation

- goldens/cdk/drag-drop/index.api.md
- src/cdk/drag-drop/directives/drag.ts
- src/cdk/drag-drop/directives/standalone-drag.spec.ts
- src/cdk/drag-drop/dom/dom-rect.ts
- src/cdk/drag-drop/drag-ref.ts
this commit introduces `resetToBoundary` in DragRef which allows user to align DragItem to its boundary on demand if at one point it was at a place where the boundary element used to be and has shrinked causing DragItem to be outside of the boundary box
fixes #30325
> feat(cdk/drag-drop): introduce `resetToBoundary`

- src/cdk/schematics/utils/project-targets.ts
https://github.com/angular/angular-cli/pull/29640 introduced a new Karma builder that appears to be the default in v20. These changes update our code so that the new builder is recognized.
I also move the names of the builders out into a constant so they're easier to update.
> fix(cdk/schematics): account for new karma builder

- docs/scenes/src/app/scene-overlay-container.ts
- docs/scenes/src/main.ts
- integration/harness-e2e-cli/src/app/app.module.ts
Removes the `NoopAnimationsModule` from the docs site and integration tests.
> build: remove miscellaneous usages of the noop animations module

- src/components-examples/material/autocomplete/autocomplete-harness/autocomplete-harness-example.spec.ts
- src/components-examples/material/bottom-sheet/bottom-sheet-harness/bottom-sheet-harness-example.spec.ts
- src/components-examples/material/datepicker/datepicker-harness/datepicker-harness-example.spec.ts
- src/components-examples/material/dialog/dialog-harness/dialog-harness-example.spec.ts
- src/components-examples/material/expansion/expansion-harness/expansion-harness-example.spec.ts
- src/components-examples/material/form-field/form-field-harness/form-field-harness-example.spec.ts
- src/components-examples/material/input/input-harness/input-harness-example.spec.ts
- src/components-examples/material/menu/menu-harness/menu-harness-example.spec.ts
- src/components-examples/material/paginator/paginator-harness/paginator-harness-example.spec.ts
- src/components-examples/material/select/select-harness/select-harness-example.spec.ts
- src/components-examples/material/sidenav/sidenav-harness/sidenav-harness-example.spec.ts
- src/components-examples/material/snack-bar/snack-bar-harness/snack-bar-harness-example.spec.ts
- src/components-examples/material/sort/sort-harness/sort-harness-example.spec.ts
- src/components-examples/material/stepper/stepper-harness/stepper-harness-example.spec.ts
- src/components-examples/material/tabs/tab-group-harness/tab-group-harness-example.spec.ts
- src/components-examples/material/timepicker/timepicker-harness/timepicker-harness-example.spec.ts
- src/components-examples/material/tooltip/tooltip-harness/tooltip-harness-example.spec.ts
Removes the `NoopAnimationsModule` from the harness examples since it isn't necessary for most of them. The rest of the examples have been switched to our token for disabling animations.
> docs: remove noop module from harness examples

- src/cdk/overlay/overlay.spec.ts
https://github.com/angular/components/pull/30878 cleaned up usages of `whenStable` that were no longer needed. However, the change that makes them unneeded (https://github.com/angular/components/pull/30703) is not on the patch branch, so this PR reverts the tests to their original form on the patch branch.
> test: add back fixture.whenStable for patch branch

- CHANGELOG.md
> docs: release notes for the v19.2.11 release

- src/cdk-experimental/listbox/listbox.ts
- src/cdk-experimental/ui-patterns/behaviors/list-focus/list-focus.ts
- src/cdk-experimental/ui-patterns/listbox/listbox.spec.ts
- src/cdk-experimental/ui-patterns/listbox/listbox.ts
- src/components-examples/cdk-experimental/listbox/cdk-listbox/cdk-listbox-example.html
- src/components-examples/cdk-experimental/listbox/cdk-listbox/cdk-listbox-example.ts
* The first option to receive focus in a listbox should be either the first selected option or the first option in the list if no option is selected.
> fix(cdk-experimental/listbox): initial listbox focus state

- src/cdk/stepper/stepper.ts
The stepper initializes its key manager in `ngAfterViewInit`, but uses it in methods that can technically be called before it is available. These changes add some null checks and update the type to avoid throwing errors.
Fixes #30864.
> fix(cdk/stepper): resolve null pointer errors

- goldens/material/autocomplete/index.api.md
- goldens/material/snack-bar/index.api.md
- goldens/material/tooltip/index.api.md
- src/material/autocomplete/autocomplete-trigger.ts
- src/material/snack-bar/snack-bar-container.ts
- src/material/tooltip/tooltip.ts
Exposes some private APIs in a few components to help with an internal migration.
> refactor(multiple): expose private APIs for internal migration

- goldens/cdk/dialog/index.api.md
- goldens/material/dialog/index.api.md
- goldens/material/dialog/testing/index.api.md
- src/cdk/dialog/dialog-config.ts
- src/cdk/dialog/dialog-container.ts
- src/cdk/dialog/dialog-ref.ts
- src/cdk/dialog/dialog.spec.ts
- src/material/dialog/dialog-config.ts
- src/material/dialog/dialog-ref.ts
- src/material/dialog/dialog.spec.ts
- src/material/dialog/dialog.ts
**Note:** this is basically a re-implementation of #25174. It was easier to redo it than rebase the original PR.
Updates the CDK and Material dialogs with the new `closePredicate` option that allows users to programmatically prevent a dialog from closing. This is different from the current `disableClose` which only covers closing through the backdrop and escape key.
Fixes #14292.
> Add closePredicate option to dialog

- src/google-maps/BUILD.bazel
- src/google-maps/deprecated-map-marker-clusterer/deprecated-map-marker-clusterer.ts
- src/google-maps/google-map/google-map.ts
- src/google-maps/map-advanced-marker/map-advanced-marker.ts
- src/google-maps/map-anchor-point.ts
- src/google-maps/map-base-layer.ts
- src/google-maps/map-bicycling-layer/map-bicycling-layer.ts
- src/google-maps/map-circle/map-circle.ts
- src/google-maps/map-directions-renderer/map-directions-renderer.ts
- src/google-maps/map-directions-renderer/map-directions-service.ts
- src/google-maps/map-geocoder/map-geocoder.ts
- src/google-maps/map-ground-overlay/map-ground-overlay.ts
- src/google-maps/map-heatmap-layer/map-heatmap-layer.ts
- src/google-maps/map-info-window/map-info-window.ts
- src/google-maps/map-kml-layer/map-kml-layer.ts
- src/google-maps/map-marker-clusterer/map-marker-clusterer.ts
- src/google-maps/map-marker/map-marker.ts
- src/google-maps/map-polygon/map-polygon.ts
- src/google-maps/map-polyline/map-polyline.ts
- src/google-maps/map-rectangle/map-rectangle.ts
- src/google-maps/map-traffic-layer/map-traffic-layer.ts
- src/google-maps/map-transit-layer/map-transit-layer.ts
- src/google-maps/tsconfig-build.json
- src/google-maps/tsconfig.json
Previously, due to an issue with the `rules_nodejs` toolchain we had to include the `google.maps` namespace types via a triple slash comment with preserve set to true, this changes to instead include the types in the tsconfig as normal
> fix(google-maps): implicitly include google.maps types instead of the triple slash workaround

- goldens/cdk/table/index.api.md
- src/cdk/table/public-api.ts
- src/cdk/table/table.ts
- src/material/table/table.ts
Removes some symbols that are only constructed privately in the table from the public API. These shouldn't be exported or depended upon, because there's no way to actually pass them back into the table.
I also ended up removing the `CDK_TABLE_TEMPLATE` variable, because it doesn't work in local compilation and it may become a problem in the future if we end up having single-file compilation in the framework.
* `CanStick` has been removed.
* `CDK_TABLE_TEMPLATE` has been removed.
* `StickyDirection` has been removed.
* `StickyStyler` has been removed.
> fix(cdk/table): remove private symbols from public API

- src/material/form-field/_mdc-text-field-structure.scss
- src/material/form-field/directives/notched-outline.ts
- src/material/form-field/form-field.ts
We were setting the `--mat-form-field-notch-max-width` on the entire form field which can cause style recalculations. These changes move to the relevant element only.
> perf(material/form-field): set notch outline variable only on relevant element

- goldens/material/tabs/index.api.md
- src/material/tabs/tab-group.html
- src/material/tabs/tab-group.ts
The tabs have a fallback that sets `transition-delay: 1ms` in case users disabled animations without going through one of our APIs. That was also applying when they set `animationDuration="0"` which is a supported API. The result was a slight flicker.
These changes resolve the flicker by treating `animationDuration="0"` in the same way as if animations were disabled globally.
Fixes #30964.
> fix(material/tabs): flicker when animationDuration is set to zero

- goldens/material/tabs/index.api.md
- src/material/tabs/tab-group.html
- src/material/tabs/tab-group.ts
**Note:** this is a patch port of #30966
The tabs have a fallback that sets `transition-delay: 1ms` in case users disabled animations without going through one of our APIs. That was also applying when they set `animationDuration="0"` which is a supported API. The result was a slight flicker.
These changes resolve the flicker by treating `animationDuration="0"` in the same way as if animations were disabled globally.
Fixes #30964.
> [Patch port] fix(material/tabs): flicker when animationDuration is set to zero

- src/cdk/schematics/utils/project-index-file.ts
The project index file discovery process now supports finding paths for projects that use the object-form of the `index` field and also for projects that do not explicitly specify an index. Starting with v20, the index field will default to `<project_source_root>/index.html` if not present in the build options for the `application` build system.
> fix(cdk/schematics): support project index file discovery for object-form and default

- src/dev-app/BUILD.bazel
Disables minification in the dev app to make errors easier to debug and since we don't really care about performance when developing locally.
> build: disable minification in the dev app

- src/material/autocomplete/autocomplete.scss
- src/material/select/select.scss
- src/material/timepicker/timepicker.scss
We have several components where we use the `offsetTop` of the `mat-option` to determine how much to scroll, however this only works if the panel is the option's `offsetParent`. For that to happen we need a position different from `static`.
Fixes #30974.
> fix(multiple): ensure mat-option parents are the offsetParent

- src/google-maps/map-event-manager.ts
- src/material-date-fns-adapter/adapter/date-fns-adapter.ts
- src/material-experimental/column-resize/column-resize.spec.ts
- src/material-luxon-adapter/adapter/luxon-date-adapter.ts
- src/material-moment-adapter/adapter/moment-date-adapter.ts
- src/universal-app/hydration.e2e.spec.ts
- src/universal-app/kitchen-sink/kitchen-sink.ts
- src/youtube-player/fake-youtube-player.ts
- src/youtube-player/youtube-player.spec.ts
- Replace `any` with `unknown` or more specific types
- ~Fix `ban-script-src-assignments` vulnerability in `youtube-player`~ submitted as a separate PR by andrewseguin (https://github.com/angular/components/pull/30773)
> refactor(multiple): eliminate usages of `any` type (batch 2)

- src/material/autocomplete/autocomplete.scss
- src/material/select/select.scss
- src/material/timepicker/timepicker.scss
**Note:** this is a cherry-pick of #30977.
We have several components where we use the `offsetTop` of the `mat-option` to determine how much to scroll, however this only works if the panel is the option's `offsetParent`. For that to happen we need a position different from `static`.
Fixes #30974.
> [Cherry pick] fix(multiple): ensure mat-option parents are the offsetParent

- src/material/table/_table-flex-styles.scss
Fixes that the flexbox-based table had a hardcoded height for the rows, instead of using the tokens.
Fixes #30906.
> fix(material/table): height tokens not applying to flex table

- src/material/table/_table-flex-styles.scss
#30978 was cherry-picked into the patch branch, but it's using APIs that aren't available in v19. These changes resolve the build failure.
> build: fix patch CI

- src/material/schematics/ng-generate/theme-color/index.spec.ts
- src/material/schematics/ng-generate/theme-color/index.ts
Fixes that the `theme-color` schematic wasn't generating the `surface-container-low` token.
Fixes #30948.
> fix(material/schematics): surface-container-low token not emitted

- .github/workflows/docs-preview-deploy.yml
- docs/firebase.json
The `material-angular-io` project name is no longer part of the `dist` directory, so we need to remove it.
> build: fix docs deployment directory

- scripts/docs-deploy/utils.mts
Right now because the `dist` directory is pre-created, the `dist/dist` structure is being created accidentally.
> build: ensure `docs/dist` directory contains site sources

- scripts/build-packages-dist.mts
The release script decides which packages to publish by looking for targets with the `release-package` tag, however with the latest infra changes there are actually two targets per package: `npm_package` and `npm_package_files`. This resulted in the release script trying to publish to npm twice which in turn caused an error since versions can't be published over.
These changes resolve the issue by:
1. Adjusting the query so it only returns the `npm_package` target.
2. Adding validation that we don't resolve the same package twice.
> build: release script producing duplicate results

- src/material/stepper/_m3-stepper.scss
Fixes that the stepper wasn't emitting values for the `header-done-state-icon-background-color` and `header-done-state-icon-foreground-color` tokens in M3.
Fixes #30987.
> fix(material/stepper): done icon tokens not emitted in M3

- CHANGELOG.md
- package.json
Also this PR cherry-picks the changelog for v20.0.0-next.10 into the main branch so that the changelog is up to date.
> Update next branch to reflect new release-train "v20.1.0-next.0".

- src/cdk-experimental/tabs/tabs.ts
- src/cdk-experimental/ui-patterns/behaviors/expansion/BUILD.bazel
- src/cdk-experimental/ui-patterns/behaviors/expansion/expansion.spec.ts
- src/cdk-experimental/ui-patterns/behaviors/expansion/expansion.ts
- src/cdk-experimental/ui-patterns/tabs/BUILD.bazel
- src/cdk-experimental/ui-patterns/tabs/tabs.ts
- Added expansion behavior that will be used in Accordion pattern later on.
- Updated Tabs jsdoc.
- Refactored Tabs to use show-hide behavior
> feat(cdk-experimental/ui-patterns): add expansion behavior and refactor tabs

- src/cdk/dialog/dialog-config.ts
- src/material/dialog/dialog-config.ts
Removes the default value for the `maxWidth` from the doc string since it's different depending on if it's M2 or M3 and it tends to get out of sync.
> docs(material/dialog): remove default value from doc string

- docs/src/app/pages/homepage/homepage.scss
- docs/src/app/pages/homepage/homepage.ts
- docs/src/app/shared/carousel/carousel.scss
- docs/src/app/shared/carousel/carousel.ts
There were a couple of places in the docs site where we were injecting the `ANIMATIONS_MODULE_TYPE`. They were both no-ops because we don't use the animations module for anything.
> build: remove unused code from docs site

- goldens/cdk/dialog/index.api.md
- src/cdk/dialog/dialog-config.ts
- src/cdk/dialog/dialog-container.ts
- src/cdk/dialog/dialog-ref.ts
- src/cdk/dialog/dialog.ts
The dialog moves focus in an `afterRender`, because it needs to give the content some time to be rendered. This is problematic with some relatively recent behavior in Chrome where the `aria-hidden` gets blocked and a warning is logged if it contains the focused element.
These changes add a way for the container to indicate when it's done moving focus and use the new API to apply the `aria-hidden`.
Fixes #30187.
> fix(cdk/dialog): avoid setting aria-hidden before focus has moved

- goldens/cdk/dialog/index.api.md
- src/cdk/dialog/dialog-config.ts
- src/cdk/dialog/dialog-container.ts
- src/cdk/dialog/dialog-ref.ts
- src/cdk/dialog/dialog.ts
Cherry-picks #31030 into the patch branch.
The dialog moves focus in an `afterRender`, because it needs to give the content some time to be rendered. This is problematic with some relatively recent behavior in Chrome where the `aria-hidden` gets blocked and a warning is logged if it contains the focused element.
These changes add a way for the container to indicate when it's done moving focus and use the new API to apply the `aria-hidden`.
Fixes #30187.
> [Cherry pick] fix(cdk/dialog): avoid setting aria-hidden before focus has moved

- docs/src/app/pages/component-sidenav/component-sidenav.scss
Fixes a flexbox issue where if a flex item has `flex-basis: auto` and `min-height: auto`, it exceeds the height of its flex parent. Consequently, when `scrollBy` is called by `scrollDetector` in `drop-list-ref.ts`, the container is not scrollable because its height is determined by its content. Removing `min-height: auto` forces the flex item to match the height of its flex parent, allowing `scrollBy` to function correctly.
Fixes #26476
> fix(docs): Automatic scrolling fails on screens smaller than 721px

- goldens/cdk/testing/index.api.md
- goldens/material/checkbox/testing/index.api.md
- goldens/material/chips/testing/index.api.md
- goldens/material/dialog/testing/index.api.md
- goldens/material/paginator/testing/index.api.md
- goldens/material/radio/testing/index.api.md
- goldens/material/slide-toggle/testing/index.api.md
- goldens/material/tree/testing/index.api.md
- src/cdk/testing/BUILD.bazel
- src/cdk/testing/change-detection.ts
- src/cdk/testing/component-harness.ts
- src/cdk/testing/element-dimensions.ts
- src/cdk/testing/harness-environment.ts
- src/cdk/testing/protractor/BUILD.bazel
- src/cdk/testing/selenium-webdriver/BUILD.bazel
- src/cdk/testing/test-element.ts
- src/cdk/testing/testbed/BUILD.bazel
- tools/adev-api-extraction/extract_api_to_json.bzl
- tools/adev-api-extraction/index.mts
Demo:
[api index](https://ng-dev-previews-fw--pr-angular-angular-60853-adev-prev-qbx2pg5n.web.app/api)
[cdk/testing](https://ng-dev-previews-fw--pr-angular-angular-60853-adev-prev-qbx2pg5n.web.app/api/cdk/testing/AsyncOptionPredicate)
[cdk/testing/testbed](https://ng-dev-previews-fw--pr-angular-angular-60853-adev-prev-qbx2pg5n.web.app/api/cdk/testing/testbed/TestbedHarnessEnvironment)
[cdk/testing/selenium-webdriver](https://ng-dev-previews-fw--pr-angular-angular-60853-adev-prev-qbx2pg5n.web.app/api/cdk/testing/selenium-webdriver/SeleniumWebDriverElement)
[cdk/testing/protractor](https://ng-dev-previews-fw--pr-angular-angular-60853-adev-prev-qbx2pg5n.web.app/api/cdk/testing/protractor/ProtractorElement)
> docs(cdk/testing): cleanup apis for landing on adev

- tools/adev-api-extraction/index.mts
This should make it easier to diff the API changes when PRs are auto-opened in the framework repository.
> build: pretty-print adev CDK docs manifests

- CHANGELOG.md
> docs: release notes for the v19.2.15 release

- CHANGELOG.md
> docs: release notes for the v20.0.0-rc.0 release

- src/material/schematics/ng-update/BUILD.bazel
- src/material/schematics/ng-update/index.ts
- src/material/schematics/ng-update/test-cases/rename-mdc-tokens.spec.ts
Adds a migration to rename tokens:
1. Switches from `--mdc-` prefixes to `--mat-`
2. Switches around some component prefixes, like from `--mat-tonal-button-` to `--mat-button-tonal` (component goes first, then variant)
3. Renames component names to match our terms, like from `text-field` to `form-field`
> fix(material/schematics): add schematic to rename tokens

- src/material/schematics/ng-generate/theme-color/index.spec.ts
- src/material/schematics/ng-generate/theme-color/index.ts
Fixes that the `theme-color` schematic was generating the wrong color for `on-tertiary`.
Fixes #30603.
> fix(material/schematics): incorrect on-tertiary color being generated

- renovate.json
The previous 'pin' rangeStrategy caused several issues:
* It unexpectedly pinned exact versions of dependencies in the distributed `package.json` files.
* It also automatically updated the Node.js version and engine ranges to their latest versions, which was not the desired behavior for our CI/CD pipeline.
Switching to the 'replace' strategy resolves these problems, ensuring more predictable and stable dependency management within our CI setup.
See: https://github.com/angular/components/pull/31062
> ci: Use 'replace' rangeStrategy to prevent unintended dependency pinning

- src/material/button-toggle/_m3-button-toggle.scss
Currently the button toggle uses the `corner-full` value for its broder radius which starts too look weird for a vertical group with text inside the toggles.
These changes switch to using the `corner-extra-large` value instead.
Fixes #31010.
> fix(material/button-toggle): use smaller border radius

- src/material/badge/_badge-theme.scss
- src/material/badge/_m3-badge.scss
- src/material/badge/badge.scss
- src/material/button-toggle/_m3-button-toggle.scss
- src/material/button/_button-base.scss
- src/material/button/fab.scss
- src/material/core/color/_all-color.scss
- src/material/core/theming/_all-theme.scss
- src/material/core/theming/_color-api-backwards-compatibility.scss
- src/material/core/theming/_definition.scss
- src/material/core/theming/_inspection.scss
- src/material/core/theming/tests/theming-definition-api.spec.ts
- src/material/core/theming/tests/theming-inspection-api.spec.ts
- src/material/core/tokens/_m3-system.scss
- src/material/core/tokens/_m3-tokens.scss
- src/material/core/tokens/_m3-utils.scss
- src/material/core/tokens/_token-utils.scss
- src/material/form-field/form-field.ts
- tools/extract-tokens/extract-tokens.ts
Refactors the M3 theme config so that it contains system-level values (colors, typography, density, shape, motion, state, elevation) so that component M3 token files can be given the theme config to derive its values.
Previously, M3 token files were used to insert values into the theme config directly when the theme config was created. When a component's `theme ` mixin was called, those values were used. This indirection is difficult to follow in the code, making it unclear when values were created and how they are pulled, because the theme files were not actually calling the m3 token files.
```
mat.define-theme() -> m3-badge.get-tokens($system) -> $theme
...
mat.badge-theme($theme) -> map.get($theme, tokens) -> token-utils.create-token-values($tokens)
```
This change makes the flow very …
> refactor: remove badge component token values from theme

- src/cdk-experimental/scrolling/virtual-scroll-viewport.spec.ts
- src/components-examples/material/checkbox/checkbox-harness/checkbox-harness-example.spec.ts
- src/material/button-toggle/button-toggle.spec.ts
- src/material/checkbox/testing/checkbox-harness.spec.ts
- src/material/datepicker/calendar.spec.ts
- src/material/datepicker/date-range-input.spec.ts
- src/material/expansion/accordion.spec.ts
- src/material/list/selection-list.spec.ts
- src/material/menu/menu.spec.ts
- src/material/radio/radio.spec.ts
- src/material/select/select.spec.ts
- src/material/sidenav/drawer.spec.ts
- src/material/sidenav/sidenav.spec.ts
- src/material/sidenav/testing/sidenav-harness.spec.ts
- src/material/stepper/stepper.spec.ts
- src/material/tabs/tab-nav-bar/tab-nav-bar.spec.ts
- test/angular-test.init.ts
When components use `OnPush`, they prevent `ExpressionHasChanged...`
from being thrown when it should (https://github.com/angular/angular/issues/45612).
The exhaustive option ignores dirty
flags and traverses the entire view tree checking for changes. This
commit configures component tests to do this by default and opts out any
tests with existing issues.
This also includes a commit to show one of the issues that surfaced along with the fix
> Use exhaustive checkNoChanges by default

- src/cdk/testing/component-harness.ts
- src/cdk/testing/harness-environment.ts
- src/cdk/testing/test-harnesses.md
- src/material/datepicker/testing/date-range-input-harness.spec.ts
- src/material/datepicker/testing/date-range-input-harness.ts
- src/material/datepicker/testing/datepicker-harness-filters.ts
- src/material/datepicker/testing/datepicker-input-harness-base.ts
- src/material/datepicker/testing/datepicker-input-harness.spec.ts
- src/material/form-field/testing/control/form-field-control-harness-filters.ts
- src/material/form-field/testing/control/form-field-control-harness.ts
- src/material/form-field/testing/control/index.ts
- src/material/input/testing/input-harness-filters.ts
- src/material/input/testing/input-harness.spec.ts
- src/material/input/testing/input-harness.ts
- src/material/input/testing/native-select-harness-filters.ts
- src/material/input/testing/native-select-harness.spec.ts
- src/material/input/testing/native-select-harness.ts
- src/material/select/testing/select-harness-filters.ts
- src/material/select/testing/select-harness.spec.ts
- src/material/select/testing/select-harness.ts
This pull request adds the following functionalities to the harness test kit
This new function works acts like `getHarness`, but returns an instance of the harness corresponding to the matching element at the given index. This throws an error if the index is out of bounds.
Example usage:
```
// Retrieves the 4th option on screen
const option = await loader.getHarnessAtIndex(MatOptionHarness, 3);
```
This new function counts the number of matching component instances and returns the result.  
Example usage:
```
// Expect there to be five options on the screen
expect(await loader.countHarnesses(MatOptionHarness)).toBe(5);
```
New functionality makes it possible to fetch harnesses for certain form components using their floating label text. Previously, the user would have to either label the …
> feat(material/testing): Extend Angular harness testing functionality 

- src/material/datepicker/testing/date-range-input-harness.ts
- src/material/form-field/testing/control/form-field-control-harness.ts
- src/material/select/testing/select-harness-filters.ts
Fixes some code that's breaking the `main` branch.
> build: fix broken build

- CHANGELOG.md
> docs: release notes for the v19.2.16 release

- src/cdk-experimental/popover-edit/popover-edit.spec.ts
- src/cdk/dialog/dialog.spec.ts
- src/cdk/listbox/listbox.spec.ts
- src/cdk/menu/context-menu-trigger.spec.ts
- src/cdk/menu/menu-trigger.spec.ts
- src/cdk/table/table.spec.ts
- src/cdk/tree/tree-using-legacy-key-manager.spec.ts
- src/cdk/tree/tree-with-tree-control.spec.ts
- src/cdk/tree/tree.spec.ts
Switches the remaining CDK tests that weren't standalone to standalone.
For the `popover-edit` tests specifically I ended up removing the templates that were created using string interpolation, because it made them hard to read and it can be a problem if we start running the tests in AoT.
> test(multiple): switch CDK tests to standalone

- src/material/datepicker/calendar.ts
An earlier change added some logic to the calendar to re-focus the active date if an input requiring a full re-render changes which can potentially cause focus to be lost.
The problem with this is that if the calendar is used on its own, it might steal away focus even though the user wasn't interacting with it.
These changes add a check that focus is inside the calendar before attempting to recapture it.
Fixes #30635.
> fix(material/datepicker): prevent calendar from stealing away focus

- src/material/tabs/_m3-tabs.scss
Fixes that the tabs weren't emitting the `disabled-ripple-color` in M3 which prevented the focus indication from being shown on disabled tabs.
Fixes #31133.
> fix(material/tabs): not emitting token in M3

- src/material/autocomplete/autocomplete.spec.ts
- src/material/autocomplete/autocomplete.zone.spec.ts
- src/material/grid-list/grid-list.spec.ts
- src/material/input/input.spec.ts
- src/material/menu/menu.spec.ts
- src/material/select/select.spec.ts
- src/material/slider/slider.spec.ts
- src/material/tooltip/tooltip.spec.ts
Converts about half of the remaining non-standalone tests in Material to standalone. Also tries to clean up the testing setup a bit.
> test(multiple): convert Material tests to standalone

- goldens/material/tabs/index.api.md
- src/material/tabs/paginated-tab-header.ts
- src/material/tabs/tab-nav-bar/tab-nav-bar.spec.ts
- src/material/tabs/tab-nav-bar/tab-nav-bar.ts
In #26397 we made it possible to navigate to disabled tabs with the keyboard, however in the tabs nav bar they're still set to `tabindex="-1"` unless they're active. This means that if the nav bar only has disabled tabs, there's no way to enter it.
These changes make it so the tab index is based on the focus index which ensures that at least one tab is always focusable. It also aligns the behavior with `mat-tab-group`.
> fix(material/tabs): avoid not having any focusable tabs

- .github/workflows/ci.material-aio.yml
- .github/workflows/pr.material-aio.yml
The original problem seems to apply anyone with the latest updates
> ci: update lighthouse test to run on `ubuntu-latest`

- src/material/sidenav/drawer.ts
- src/material/sidenav/sidenav.ts
Updates Angular Components SideNav component so that when
the mode is not equalt to side the tabIndex value is -1.
Otherwise provide a null value.
[Before fix screenshot](https://screenshot.googleplex.com/65vh5qPmjsDBphi)
[After fix screenshot](https://screenshot.googleplex.com/3pLLsoTDcKQH9a2)
[After fix screenshot of mat-drawer-end comparison](https://screenshot.googleplex.com/62DCitRjqkCzB75)
Fixes b/286459024
> fix(material/sidenav): removes -1 tabindex from sidenav 

- WORKSPACE
This will be the minimum supported version by Angular FW and CLI from the next RC version.
> build: update Node.js version to `22.12.0`

- src/material/radio/radio.spec.ts
- src/material/radio/radio.ts
This change ensures that updates to the required value of the radio button also mark the component for check, ensuring OnPush compatibility.
> fix(material/radio): updating required value should mark for check

- goldens/cdk/scrolling/index.api.md
- src/cdk-experimental/scrolling/virtual-scroll-viewport.spec.ts
- src/cdk/scrolling/virtual-scroll-viewport.html
- src/cdk/scrolling/virtual-scroll-viewport.ts
This fixes an expressionchanged... error in the scrolling where template updates
were not accompanied by a change notification (`markforCheck`/signal
update, etc).
First commit is https://github.com/angular/components/pull/31069
> fix(cdk-experimental/scrolling): Fix ExpressionChangedAfterItWasCheckedError

- src/material/button-toggle/button-toggle.spec.ts
- src/material/button-toggle/button-toggle.ts
Reworks the button toggle so it doesn't cause a "changed after checked" error when its tabindex is updated.
> fix(material/button-toggle): changed after checked error when updating tabindex

- CHANGELOG.md
> docs: release notes for the v19.2.17 release

- CHANGELOG.md
> docs: release notes for the v20.0.0-rc.2 release

- src/material/sort/_m2-sort.scss
Sort icon used to be a mix of different elements, and opacity would cause problems. This is no longer the case
Sort color should just match "text" which is what the table header label does
> fix(material/sort): simplify m2 sort color

- goldens/cdk/stepper/index.api.md
- goldens/material/stepper/index.api.md
- src/cdk/a11y/key-manager/list-key-manager.ts
- src/cdk/stepper/stepper.ts
- src/material/list/list-base.ts
- src/material/list/selection-list.spec.ts
- src/material/list/selection-list.ts
- src/material/menu/menu.spec.ts
- src/material/stepper/step-header.html
- src/material/stepper/step-header.ts
- src/material/stepper/stepper.html
- src/material/stepper/stepper.spec.ts
- src/material/stepper/stepper.ts
Resolves the remaining "changed after checked" errors that were masked by exhaustive checks being turned off in tests.
> Resolve more changed after checked errors

- src/material/button-toggle/_m2-button-toggle.scss
Change already landed internally with divider changes - was missed on the divider PR #31200
> fix(material/button-toggle): simplify divider color

- src/material/button-toggle/_m2-button-toggle.scss
- src/material/button/_m2-button.scss
- src/material/button/_m2-fab.scss
- src/material/checkbox/_m2-checkbox.scss
- src/material/core/m2/_theming.scss
- src/material/core/style/_form-common.scss
- src/material/core/style/_sass-utils.scss
- src/material/datepicker/_m2-datepicker.scss
- src/material/dialog/_m2-dialog.scss
- src/material/form-field/_m2-form-field.scss
- src/material/list/_m2-list.scss
- src/material/paginator/_m2-paginator.scss
- src/material/radio/_m2-radio.scss
- src/material/select/_m2-select.scss
- src/material/sidenav/_m2-sidenav.scss
- src/material/tabs/_m2-tabs.scss
Converge on using `get-theme-color` to get theme colors with opacity. The missing piece was that `get-theme color` wasn't variable-friendly, so now it returns a color-mix if the color is not a "color"
Also, when possible, just use the foreground base color instead of various different colors when passing any opacity
> refactor: remove safe-color-change mixin

- package.json
- pnpm-lock.yaml
- scripts/docs-deploy/deploy-to-site.mts
Apparently there is a bug in the latest firebase CLI version that requires more permissions than actually needed; so our deployment in `main` fails.
> build: update firebase-tools

- src/material/button/_m2-icon-button.scss
- src/material/button/_m3-icon-button.scss
- src/material/button/icon-button.scss
Fixes that it wasn't possible to customize the shape of the icon button using tokens.
Fixes #30525.
> fix(material/button): add token for icon button shape

- src/material/badge/_m2-badge.scss
This matches M3 experience where disabled badges just include an opacity.
The intent here was to make a disabled badge look better on a disabled button by making it be opaque, but the mix makes it more difficult to use system colors. This also has to make an assumption about the background of the disabled element's container, which is not easily determined anyways. In this case, the button is more likely on a "surface" color anyways, since background is mostly used in other rare situations.
Note also that the M2/M3 spec does not consider disabled badges.
If it seems that this is a common enough UI problem, perhaps we can come up with a new system token about an opaque disabled color without the use of opacity
> fix(material/badge): remove badge opacity color mix

- src/material/button/_m2-button.scss
- src/material/button/_m2-fab.scss
- src/material/checkbox/_m2-checkbox.scss
- src/material/datepicker/_m2-datepicker.scss
- src/material/expansion/_m2-expansion.scss
- src/material/form-field/_m2-form-field.scss
- src/material/radio/_m2-radio.scss
- src/material/select/_m2-select.scss
Text should be on-surface with opacity 38%, and containers should be on-surface with opacity 12%
> refactor: align on disabled colors

- goldens/material/chips/index.api.md
- src/material/chips/chip-row.spec.ts
- src/material/chips/chip-row.ts
Some screen readers have difficulty with allowing users to say double click or enter with voice control, preventing them from being able to edit a chip which currently requires a double click or an enter key event.
Single click conflicts with other behaviors, but allowing a click when the chips has already been focused is a natural way to edit the chip and does not affect other current behaviors.
Fixes b/290806246.
> fix(material/chips): provide ability to edit for all screen readers with a click on already focused chip

- src/material/button-toggle/_m2-button-toggle.scss
- src/material/card/_m2-card.scss
- src/material/core/m2/_theming.scss
- src/material/core/selection/pseudo-checkbox/_m2-pseudo-checkbox.scss
- src/material/core/tokens/_m2-utils.scss
- src/material/datepicker/_m2-datepicker.scss
- src/material/expansion/_m2-expansion.scss
- src/material/list/_m2-list.scss
- src/material/stepper/_m2-stepper.scss
Replaces palette's secondary-text color
> refactor: add surface-variant system color

- src/material/button-toggle/_m2-button-toggle.scss
Resolves accessibility issues where the contrast was too low for legacy appearance
> fix(material/button-toggle): use system colors

- src/material/core/tokens/_m3-system.scss
If a non-map value is set for the `typography`, we were only setting the plain font family while the brand one was falling back to Roboto.
Fixes #31254.
> fix(material/core): brand family not set for plain value

- src/material/schematics/ng-update/index.ts
Fixes that the v20 update migration was overwriting all files, even if they didn't change.
Fixes #31259.
> fix(material/schematics): avoid overwriting files that didn't change

- src/material/schematics/ng-update/index.ts
- src/material/schematics/ng-update/test-cases/rename-mdc-tokens.spec.ts
Fixes that the v20 `ng update` migration was only replacing the first instance of tokens.
Fixes #31276.
> fix(material/schematics): token migration not replacing all instances

- goldens/cdk/drag-drop/index.api.md
- src/cdk/drag-drop/directives/drop-list-shared.spec.ts
- src/cdk/drag-drop/directives/drop-list.ts
- src/cdk/drag-drop/drag-drop.md
- src/cdk/drag-drop/drag-ref.ts
- src/cdk/drag-drop/drop-list-ref.ts
- src/cdk/drag-drop/sorting/drop-list-sort-strategy.ts
- src/cdk/drag-drop/sorting/mixed-sort-strategy.ts
- src/cdk/drag-drop/sorting/single-axis-sort-strategy.ts
- src/components-examples/cdk/drag-drop/cdk-drag-drop-copy-list/cdk-drag-drop-copy-list-example.css
- src/components-examples/cdk/drag-drop/cdk-drag-drop-copy-list/cdk-drag-drop-copy-list-example.html
- src/components-examples/cdk/drag-drop/cdk-drag-drop-copy-list/cdk-drag-drop-copy-list-example.ts
- src/components-examples/cdk/drag-drop/index.ts
Currently we create a placeholder element to indicate where an item will be dropped. The placeholder gets moved around between drop containers as the user is dragging. In some cases this might not be desirable, because the data representing the dragged item might be copied, rather than moved.
These changes address this use case by adding the `cdkDropListHasAnchor` input. When enabled, it'll tell the drop list to leave an anchor element, representing the dragged item, inside the original list. The anchor differs from the placeholder in that it will stay in the original container and won't move to any subsequent containers.
Fixes #13906.
> feat(cdk/drag-drop): add opt-in indicator of pick-up position

- CHANGELOG.md
> docs: release notes for the v20.0.2 release

- src/material/button/button.scss
Updates Angular Components Button component specifically for .mat-icon buttons to add a min-height of min-content to avoid the icon from being cut off on the bottom when text-spacing is applied.
Fixes b/411228600
[BEFORE screenshot](https://screenshot.googleplex.com/7LDWZxpgLr6oqHh)
[AFTER screenshot](https://screenshot.googleplex.com/7U3oWSLTAJnwWdM)
> fix(material/button): prevents mat-icon being cut off by text-spacing

- SECURITY.md
The security policy link in `SECURITY.md` leads to a nonexistent page. This change updates that link so that it correctly points to Angular's current security documentation.
> docs: update link to Angular security policy

- src/material/radio/_m3-radio.scss
Fixes that when passing in a variant into the radio button's `get-tokens` function, we were removing the color tokens altogether, because passing in multiple arguments into `map.remove` removes all those keys, rather than removing a nested value.
Fixes #31319.
> fix(material/radio): color tokens excluded when passing in variant

- src/material/button/testing/button-harness.spec.ts
- src/material/button/testing/button-harness.ts
Fixes that the button harness wasn't finding buttons with a dynamic appearance, because then Angular won't set an attribute to the DOM for data bindings. These changes switch to using a class selector instead.
> fix(material/button): harness not picking up buttons with dynamic appearance

- src/material/core/tokens/m2/_md-sys-typescale.scss
- src/material/slide-toggle/_slide-toggle-theme.scss
Some changes in the typography PR #31334 couldn't land (yet). These were included in the internal CL but not the PR
> refactor: realign changes with g3

- tools/markdown-to-html/docs-marked-renderer.ts
Currently we style the content in the docs by setting a `docs-markdown` class around it which then targets element tags that can be produced by the markdown renderer like `p` and `h1`. The problem with this is that some components use these elements for their own styling, e.g. the main `mat-card` example looks off because its `p` tag styling is overridden by `docs-markdown`.
These changes update the docs generation script to exclude the component styles from the markdown styles.
Example of the card docs now:
After the changes:
> build: prevent markdown styling from bleeding into examples

- src/material/input/input.ts
Reverts the workaround from #29074, because it appears to make the behavior inconsistent between browsers and users don't have an easy way to opt out.
Instead of adding the event from Material, users that care about this behavior can add a `wheel` event themselves.
Fixes #31372.
> fix(material/input): revert wheel workaround

- goldens/cdk/menu/index.api.md
- src/cdk/menu/menu-base.ts
- src/cdk/menu/menu.spec.ts
See https://github.com/angular/components/issues/31370 for more details
> feat(cdk/menu): add setActiveMenuItem to cdkMenu

- goldens/material/menu/index.api.md
- goldens/material/menu/testing/index.api.md
- src/components-examples/material/menu/context-menu/context-menu-example.css
- src/components-examples/material/menu/context-menu/context-menu-example.html
- src/components-examples/material/menu/context-menu/context-menu-example.ts
- src/components-examples/material/menu/index.ts
- src/dev-app/menu/menu-demo.html
- src/dev-app/menu/menu-demo.scss
- src/material/menu/BUILD.bazel
- src/material/menu/context-menu-trigger.spec.ts
- src/material/menu/context-menu-trigger.ts
- src/material/menu/menu-trigger-base.ts
- src/material/menu/menu-trigger.ts
- src/material/menu/menu.md
- src/material/menu/module.ts
- src/material/menu/public-api.ts
- src/material/menu/testing/context-menu-harness.spec.ts
- src/material/menu/testing/context-menu-harness.ts
- src/material/menu/testing/menu-harness-filters.ts
- src/material/menu/testing/menu-harness.ts
- src/material/menu/testing/public-api.ts
Adds the new `MatContextMenuTrigger` directive that allows users to mark an area as a trigger for a menu. When the user right-clicks inside of the area, the menu will be opened next to their pointer.
Fixes #5007.
> feat(material/menu): add support for context menu 

- package.json
- pnpm-lock.yaml
- renovate.json
Makes the following changes to our dependency management:
1. Removes `yaml` since we don't use it anywhere.
2. Disables updates for `stylelint` and `selenium-webdriver`, because their latest versions have breaking changes that will take some effort to get around.
> build: dependency management updates

- WORKSPACE
Changes the version of `rules_browsers` which include a fix that should resolve the failing Firefox tests on the `main` branch.
> build: fix failing firefox tests on main

- CHANGELOG.md
> docs: release notes for the v19.2.19 release

- docs/src/app/shared/doc-viewer/doc-viewer.ts
- docs/src/app/shared/doc-viewer/header-link.ts
Fixes that a previous commit stopped setting the `example` on the `HeaderLink` which means that its link isn't constructed correctly.
> build: links to headers not working

- src/cdk-experimental/accordion/accordion.ts
In short, in the demo page
```
<button cdkAccordionTrigger disabled>
```
Makes the button natively disabled and not focusable, so even with `skipDisabled=false` it can't be focused by the focus manager.
Change it to
```
<button cdkAccordionTrigger [disabled]="true">
```
Makes the `cdkAccordionTrigger` to be disabled without changing the button state.
Also added the `inert` attribute to the button when it's completely disabled(disabled and skip disabled), so it can't be focused by a pointer.
> fix(cdk-experimental/accordion): fix disabled trigger button can't be focused when skipDisabled=false

- renovate.json
Updates the Renovate config to skip more dependencies and to not touch integration tests and the Stackblitz template.
> build: update renovate config

- goldens/cdk/a11y/index.api.md
- src/cdk/a11y/key-manager/activedescendant-key-manager.ts
- src/cdk/a11y/key-manager/focus-key-manager.ts
- src/cdk/a11y/key-manager/list-key-manager.ts
- src/cdk/menu/menu-base.ts
This is a follow-up to https://github.com/angular/components/pull/31371#discussion_r2163199446. `ListKeyManager.setActiveItem` supports both a reference to an item or an index, however there's no override that allows `T | number` which can be inconvenient.
These changes add extra overrides to resolve the issue.
> fix(cdk/a11y): allow mixed types to be passed into setActiveItem

- src/cdk/tree/tree.ts
Fixes that we weren't unsubscribing from one observable in the tree.
Fixes #31454.
> fix(cdk/tree): remove leaking subscription

- CHANGELOG.md
> docs: release notes for the v20.0.5 release

- CHANGELOG.md
- package.json
Also this PR cherry-picks the changelog for v20.1.0-rc.0 into the main branch so that the changelog is up to date.
> Update next branch to reflect new release-train "v20.2.0-next.0".

- src/cdk/scrolling/virtual-scroll-viewport.spec.ts
tick is not called by schedulers anymore (they use an internal _tick)
> test(cdk/scrolling): Change test spying on tick

- src/cdk/dialog/BUILD.bazel
- src/e2e-app/BUILD.bazel
- src/material/badge/BUILD.bazel
- src/material/checkbox/BUILD.bazel
- src/material/chips/BUILD.bazel
- src/material/slide-toggle/BUILD.bazel
Removes unnecessary references to the animations module from BUILD files.
> build: clean up animations references in build files

- .gemini/config.yaml
Configures gemini to not interact with new pull requests, only review on demand
> ci: add gemini code assist config

- guides/theming.md
The headers in the theming guide were using bold or italic formatting which overrides the docs site styling and makes them look inconsistent. These changes remove the formatting.
> docs: remove formatting from theming guide headers

- src/cdk/drag-drop/directives/drag.ts
- src/cdk/drag-drop/directives/drop-list.ts
Currently we only sync drop container in the `CdkDrag` container. These changes move the logic into `addItem` to ensure that it always happens.
Fixes #31514.
> fix(cdk/drag-drop): ensure container is registered in addItem

- CHANGELOG.md
Cherry-picks the changelog from the "20.1.x" branch to the next branch (main).
> docs: release notes for the v20.1.2 release

- goldens/material/table/index.api.md
- src/material/table/table-data-source.ts
Extend types of the sort and paginator setter to include undefined to avoid `?? null` when using singals (e.g. `viewChild`).
> feat(material/table): accept undefined sort and paginator

- src/material/datepicker/_m3-datepicker.scss
- src/material/datepicker/datepicker-toggle.scss
There were two issues preventing the active styles for the datepicker toggle from showing up in M3:
1. In M2 the inner button had a `color: inherit` which allowed it to inherit the color from the toggle, however in M3 the button has a specific color.
2. The M3 tokens for the datepicker weren't setting the right color.
> fix(material/datepicker): toggle button active color not showing up in M3

- src/material/datepicker/calendar-header.html
- src/material/datepicker/calendar-header.spec.ts
- src/material/datepicker/calendar.spec.ts
- src/material/datepicker/calendar.ts
If the user hits the end of the calendar (e.g. when a min/max date is set), we disable the calendar button which causes focus to be returned to the `body`.
These changes use `disabledInteractive` on the buttons so that focus stays on the button.
> fix(material/datepicker): focus lost when hitting the end of calendar

- src/material/form-field/form-field.ts
This is something that showed up in some internal tests a while ago. Because we set `mat-focused` through a host binding while `mdc-text-field--focused` is set through direct DOM manipulation, nothing guarantees that they'll be in sync and in some internal tests they aren't.
These changes sync both of them up from the same place.
> fix(material/form-field): ensure that focused classes are in sync

- src/material/table/table-data-source.spec.ts
Accidentally stumbled on this old test we had with legacy components that didn't make their way into the MDC directory
> fix(material/table): add missing sort tests

- src/cdk/drag-drop/sorting/mixed-sort-strategy.ts
When an item enters a mixed orientation list, we were figuring out its index, removing the item from the list and then trying to insert it in that index. The problem is that by removing the item, we might have changed the array in a way where the index isn't valid anymore.
These changes resolve the issue by removing the item first before making any index calculations.
Fixes #31505.
> fix(cdk/drag-drop): incorrect index when returning item in mixed list

- src/material/datepicker/testing/date-range-input-harness.ts
- src/material/form-field/testing/control/form-field-control-harness.ts
- src/material/input/testing/input-harness.spec.ts
Updates the FormFieldControlHarness label capabilities to support a wider range of implementations. This affects any harness that derives from MatFormFieldControlHarnessBase, such as MatInputHarness and MatSelectHarness.
The current implementation works as expected when searching for a floating mat-label within a mat-form-field. However, it fails when searching for a label that is provided via `<label for=...>` or `aria-label`, as are suggested in the [Material documentation](https://material.angular.dev/components/input/overview#aria-attributes). This change aims to expand support for these patterns to match the supporting documentation.
> fix(material/testing): Fix minor issue preventing the `label` filter from working for some implementations

- src/material/core/tokens/m3/_md-sys-color.scss
Some internal color tokens have changed - this brings them back into spec. The keys are removed since the defaults for internal and external match and do not need the custom overrides
> fix(material/core): align gm3 colors

- goldens/cdk/listbox/index.api.md
- src/cdk/listbox/listbox.ts
Fixes that the CDK listbox option wasn't coercing its `tabindex` value.
Fixes #31595.
> fix(cdk/listbox): coerce tabindex value

- goldens/material/slider/index.api.md
- src/material/slider/slider.ts
Fixes that if `showTickMarks` is `false` initially and then switches to `true`, the slider wasn't updating to show the tick marks.
Fixes #31590.
> fix(material/slider): tick marks not showing dynamically

- src/material/radio/BUILD.bazel
- src/material/radio/_radio-common.scss
Currently the circle inside the radio button is rendered out as an element with a solid border. Presumably MDC did it this way, because it allows more CSS rules to be combined and it handles high contrast mode automatically. The problem with this approach is that depending on the user's screen and zoom level, there can be rendering artifacts on Windows like a dot in the middle of the radio button.
These changes resolve the rendering artifacts by using a background color for the circle and which is overridden to `CanvasText` for high contrast mode.
Fixes #31466.
> fix(material/radio): rendering artifacts at some zoom levels

- src/material/schematics/ng-add/theming/create-custom-theme.ts
The custom theme that we generate during `ng add` adds changes the `font` on the `html` element which is problematic, because it affects all the components where we use `rem` units. These changes move the styles to the `body` to resolve the issue.
I've also changed the selector for the variables from `html` to `:root`. In practice they're the same, but `:root` seems to be the standard target for global variables.
Fixes #31611.
> fix(material/schematics): set generated font family on body

- CHANGELOG.md
Cherry-picks the changelog from the "20.1.x" branch to the next branch (main).
> docs: release notes for the v20.1.4 release

- src/components-examples/cdk/drag-drop/index.ts
Fixes that the scrollable example wasn't showing up properly, because it wasn't exported from the index file.
Fixes #31619.
> docs(cdk/drag-drop): scrollable example not showing

- src/cdk-experimental/listbox/listbox.ts
The `value` field is an input, but is `protected` which isn't supported.
> refactor(cdk-experimental/listbox): update visibility on value field

- goldens/material/chips/index.api.md
- src/material/chips/chip-row.spec.ts
- src/material/chips/chip.spec.ts
- src/material/chips/chip.ts
Fixes (or at least first step in fixing) b/286287327 where ripple shows static chips as being interactive even when they are not.
> fix(material/chips): static chips should disable ripple

- goldens/material/chips/index.api.md
- src/material/chips/chip-option.html
- src/material/chips/chip-option.spec.ts
- src/material/chips/chip-row.html
- src/material/chips/chip-row.spec.ts
- src/material/chips/chip.ts
FIxes b/351897224 where the extra spans just used for aria-describedby cause the linear navigation to read them as members of an extra group and confuses the narration for the chipset group.
> fix(material/chips): remove extra span for aria-description

- src/cdk/observers/observers.md
When using the **cdkObserveContent** directive, I noticed that it reacts to changes in any content within the element it applies to, not just **ng-content**, or is this a coincidence?
If this is intended, I suggest improving the documentation so that this feature does not seem like a coincidence.
https://material.angular.dev/cdk/observers/overview
_The suggested changes to the code could be edited better to convey the information more simply_
Example:
```html
<div class="content-wrapper" (click)="changeText()" (cdkObserveContent)="textChanged()">
{{ text }}
</div>
```
```
text = 'text1';
textChanged() {
console.log(this.text);
}
changeText() {
this.text = 'text2';
}
```
When I click on the div in the console I see a message:
> docs(material/cdk/observers):  Documentation supplement due to extended capabilities of the directive

- src/components-examples/material/datepicker/datepicker-dialog/datepicker-dialog-example-dialog.html
- src/components-examples/material/datepicker/datepicker-dialog/datepicker-dialog-example.html
- src/components-examples/material/datepicker/datepicker-dialog/datepicker-dialog-example.ts
The example that shows a datepicker inside a dialog looked weird. These changes fix it up.
> docs(material/datepicker): fix up dialog example

- goldens/cdk/menu/index.api.md
- src/cdk/menu/menu-base.ts
- src/cdk/menu/menu-item.ts
- src/cdk/menu/menu.spec.ts
Fixes that the CDK menu was picking up items from nested menu instances which in turn were throwing off the keyboard navigation.
Fixes #31678.
> fix(cdk/menu): picking up items from child menu

- src/material/schematics/ng-generate/theme-color/README.md
The link to Material's accessible design guidance currently leads to a [404 page](https://m3.material.io/foundations/accessible-design/patterns). This link has been updated to point to the latest Material documentation on color and contrast instead, which seems to be the most suitable replacement page.
> docs: fix broken link in theme-color schematic documentation

- CHANGELOG.md
Cherry-picks the changelog from the "20.1.x" branch to the next branch (main).
> docs: release notes for the v20.1.6 release

- src/material/menu/menu-trigger-base.ts
The menu has some logic that detaches its lazy content when the animation is finished, however while the animation was running, the panel might've been picked up by another trigger. This ends up opening an empty menu panel to the new trigger.
These changes resolve the issue by checking if another trigger picked up the panel before detaching the lazy content.
Fixes #31687.
> fix(material/menu): incorrectly detaching lazy content when menu is transferred to a new trigger

- src/cdk/table/table.spec.ts
- src/cdk/table/table.ts
Fixes #24483
When `CdkTable` is used with the `OnPush` change detection strategy and a `trackBy` function, changes to the `dataSource` might not trigger a view update if the `trackBy` function indicates that the row instances themselves haven't changed. This can lead to the data-bound elements within the table rows displaying outdated information, even if their underlying data properties have been modified.
This PR addresses the issue by adding `_changeDetectorRef.markForCheck()` calls within the `renderRows` method of `CdkTable`. These calls ensure that whenever the table's data or row definitions are updated, the component is explicitly marked for change detection. This forces a re-evaluation of the bindings for all visible rows, ensuring the view remains consistent with the latest …
> fix(cdk/table): ensure CdkTable updates view with OnPush and trackBy

- goldens/cdk/menu/index.api.md
- src/cdk/menu/menu-base.ts
- src/cdk/menu/menu-item.spec.ts
- src/cdk/menu/menu-item.ts
Fixes the following issues with the disabled behavior of the CDK menu item:
* The item wasn't receiving focus like specified in the spec.
* There wasn't a proper way to style disabled items which led users to use `aria-disabled`.
* Clicking the disabled item didn't prevent the default behavior.
Fixes #31179.
> fix(cdk/menu): disabled behavior fixes for menu item

- src/material/schematics/migration.json
Fixes that we were targeting v20 with the v21 migration.
> build: set proper version on v21 migration

- src/cdk-experimental/ui-patterns/behaviors/list-selection/list-selection.spec.ts
- src/cdk-experimental/ui-patterns/behaviors/list-selection/list-selection.ts
* Change deselectAll to deselect values that are not accounted for in the items array.
> fix(cdk-experimental/ui-patterns): deselectAll unavailable items

- renovate.json
This change allows Renovate to run on all branches, not just the base branch. Note that it will only update cross-repo, Bazel, and GitHub Actions dependencies on these branches.
This is needed as due to the bazel module lock file changes to the package.json cannot be cherry-picked.
> ci: enable Renovate on non-base branches

- goldens/material/chips/index.api.md
- src/material/chips/chip-action.ts
- src/material/chips/chip-icons.ts
- src/material/chips/chip-listbox.ts
- src/material/chips/chip-row.spec.ts
- src/material/chips/chip-row.ts
- src/material/chips/chip-set.ts
- src/material/chips/chip.html
- src/material/chips/chip.spec.ts
- src/material/chips/chip.ts
Fixes b/286287327 where non-interaction actions still have a click handler and thus get picked up as interactive by screen readers. 
- `MatChipAction` no longer has an `isInteractive` input, it is always interactive and new `MatChipContent` should be used when not interactive.
- `MatChipTrailingIcon` now extends from `MatChipContent` and can not be made interactive.
> fix(material/chips): refactor non-interactive actions to prevent adding click handlers

- src/material/datepicker/BUILD.bazel
- src/material/datepicker/calendar-header.html
- src/material/datepicker/calendar.ts
Adds tooltips to the calendar next/previous buttons so that they have visible labels.
Fixes #31536.
> fix(material/datepicker): add visible labels to calendar buttons

- CHANGELOG.md
Cherry-picks the changelog from the "20.2.x" branch to the next branch (main).
> docs: release notes for the v20.2.1 release

- src/material/chips/chip-grid.spec.ts
We had a few tests in the chips that were only passing with `NoopAnimationsModule`. These changes rework the tests and drop the dependency.
> test(material/chips): remove dependency on NoopAnimationsModule

- .github/workflows/ci.yml
- .github/workflows/pr.yml
- BUILD.bazel
- MODULE.bazel
- MODULE.bazel.lock
Within our module.bazel file when describing the version of typescript to use for rules_ts, we use ts_version instead of ts_version_from to prevent our package.json file from being
part of the set of files used to calculate the sha for the lock file.  Any unrelated change to the version of the typescript file would end up causing our lockfile to be out of date.
This amount of churn has proven to be too much for our current setup. We instead now test to validate the versions defined in the package.json and MODULE.bazel files match.
Backport of https://github.com/angular/angular/pull/63431/commits
> build: define typescript version via string in module.bazel file

- src/material/progress-bar/progress-bar.scss
Currently the way we render the buffer dots in the progress bar is by using a `data:` URL with an inline SVG. The problem with this approach is that it can trigger CSP errors and require users to allow all `data:` URLs, even if they don't use the buffer mode.
These changes work around the issue by rendering the dots using a radial gradient instead.
Fixes #31808.
> fix(material/progress-bar): avoid CSP issues due to buffer dots

- src/material/core/option/option.scss
Fixes b/259542956 by excluding selected state color overrides when the option item is focused or hovered on, so user can see the focus/hover state even when item has been selected.
> fix(material/select): ensure proper highlighting on selection

- src/material/button/button.scss
- src/material/button/fab.scss
Disables the hover state for buttons on devices that don't support it (e.g. touch devices) since it can look off.
Fixes #31841.
> fix(material/button): do not show hover state on devices that don't support hover

- src/material/tabs/tab-body.ts
The tabs run their animation events outside the zone which means that attaching the content as a result will be outside the zone as well. These changes bring it back into the zone to ensure that things like error handling work correctly.
Fixes #31867.
> fix(material/tabs): attach content inside the zone

- src/material/stepper/step-header.ts
- src/material/stepper/stepper.html
- src/material/stepper/stepper.spec.ts
- src/material/stepper/stepper.ts
- src/material/stepper/testing/step-harness.ts
Fixes b/361783174 by addressing the incorrect placement of tabpanel roles inside the tab list.
For horizontal, can move the tablist down to the div which only wraps the actual tabs.
For vertical, it is triickier as the tab content is placed inline with the tab headers. For that, had to change to no longer use the tab roles.
> fix(material/stepper): Adjust aria tab-related roles to fix violations

- goldens/material/button/testing/index.api.md
- src/material/button/testing/BUILD.bazel
- src/material/button/testing/button-harness-filters.ts
- src/material/button/testing/button-harness.spec.ts
- src/material/button/testing/button-harness.ts
In its current implementation, icon buttons and FABs are more difficult to filter for compared to text-based buttons, which can use their { text} filter property, usually relying on a custom selector (eg: class or id) or ancestor. This change aims to simplify this by allowing a user to filter via a contained icon. The filtering logic is quite simple and reuses the existing logic inside `MatIconHarness` for simplicity and reliability.
Example usage:
```
const iconButton = await getHarness(MatButtonHarness.with({ iconName: "favorite" }));
```
> feat(material/testing): Add icon name filtering to MatButtonHarness

- DEV_ENVIRONMENT.md
Updated docs to use `pnpm i` instead of `pnpm`, since `pnpm` alone does not install dependencies.
> docs: correct pnpm install command

- CHANGELOG.md
Cherry-picks the changelog from the "20.2.x" branch to the next branch (main).
> docs: release notes for the v20.2.5 release

- goldens/material/chips/index.api.md
- src/material/chips/chip-input.spec.ts
- src/material/chips/chip-input.ts
- src/material/chips/tokens.ts
Currently we ignore separator keys if any modifier is pressed, but in some cases that might not be desirable. These changes add an option to specify a separator key with modifiers so that users can customize the behavior.
> feat(material/chips): allow for modifiers to be specified on separator keys

- src/cdk/platform/features/scrolling.ts
Currently angular has a side effect which checks for scrollbehavior on module load. This is throwing an exception in our chrome extension content script when running on an xml page when style are undefined
Added a null check to make sure undefined exception is not thrown
> fix(cdk/scrolling): Fix undefined error when documentElement.style is undefined

- goldens/material/menu/index.api.md
- src/material/menu/menu.html
- src/material/menu/menu.ts
Switches the `_isAnimating` state to a signal in order to avoid "changed after checked" errors.
Fixes #31933.
> fix(material/menu): switch internal state to signals

- goldens/material/core/index.api.md
- src/material/core/animation/animation.ts
- src/material/core/datetime/native-date-adapter.ts
Deletes APIs that were marked for removal in v21.
* `AnimationCurves` has been removed.
* `AnimationDurations` has been removed.
* `NativeDateAdapter.useUtcForDisplay` has been removed.
> fix(material/core): remove deprecated APIs for v21

- src/material/menu/menu-trigger.ts
Fixes that it was possible for the user to re-open a child menu if they quickly hover back to the parent meny while it's animating away.
Fixes #31956.
> fix(material/menu): prevent child menu reopening while parent is animating away

- goldens/material/datepicker/index.api.md
- src/material/datepicker/calendar-body.ts
- src/material/datepicker/month-view.html
- src/material/datepicker/month-view.ts
- src/material/datepicker/multi-year-view.html
- src/material/datepicker/multi-year-view.ts
- src/material/datepicker/year-view.html
- src/material/datepicker/year-view.ts
The month view had a `detectChanges` call that was happening inside a `blur` event which ended up causing re-entrant change detection and hitting an assertion in the framework. These changes remove it since it doesn't appear to be necessary anymore.
Fixes #31959.
I've also converted the internal calendar state to signals to get a feel for how breaking something like this might be.
> fix(material/datepicker): error due to synchronous change detection

- src/material/menu/menu.scss
The material/divider component sets its color using the `border-top-color` but the material/menu component attempts to override this by setting the `color` property which causes any overrides to not get applied.
> fix(material/menu): fix divider color property

- goldens/material/timepicker/index.api.md
- src/material/timepicker/timepicker-input.ts
- src/material/timepicker/timepicker.spec.ts
- src/material/timepicker/timepicker.ts
Fixes that we were emitting some events before the form control value was assigned.
Fixes #31950.
> fix(material/timepicker): assign form control value before emitting events

- goldens/material/datepicker/index.api.md
- src/material/datepicker/calendar.ts
- src/material/datepicker/date-range-input.ts
- src/material/datepicker/datepicker-base.ts
- src/material/datepicker/datepicker-input-base.ts
- src/material/datepicker/datepicker-input.ts
- src/material/datepicker/month-view.ts
- src/material/datepicker/multi-year-view.ts
- src/material/datepicker/year-view.ts
Makes the date filter function nullable so users can reset it.
Fixes #31976.
> fix(material/datepicker): make date filter nullable

- goldens/material/bottom-sheet/index.api.md
- src/material/bottom-sheet/bottom-sheet-config.ts
- src/material/bottom-sheet/bottom-sheet.spec.ts
Add injector to `MatBottomSheetConfig`.
Close #31951
> feat(material/bottom-sheet): add injector to MatBottomSheetConfig

- src/material/radio/radio.scss
This is a backport for 20.2 branch of the already merged #31894. So it might get released in the future 20.2.8.
> feat(material/radio): Hovering over label of a radio will show the pointer cursor

- src/cdk/a11y/a11y.md
Removes a note from the focus monitor docs that is no longer valid.
Fixes #30529.
> docs: remove inaccurate note from focus monitor docs

- goldens/material/sort/index.api.md
- src/components-examples/material/sort/BUILD.bazel
- src/components-examples/material/sort/index.ts
- src/components-examples/material/sort/sort-custom-icon/sort-custom-icon-example.html
- src/components-examples/material/sort/sort-custom-icon/sort-custom-icon-example.ts
- src/material/sort/sort-header.html
- src/material/sort/sort-header.scss
- src/material/sort/sort.md
Adds the `matSortHeaderIcon` content projection slot that users can use to customize the sorting icon.
Fixes #32002.
> feat(material/sort): add content projection slot for custom icon
